### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by teramandiri** [spatie/laravel-permission#10]
Hi, I'm very begginer with Laravel. I try to use your awesome package.
I found error when running php artisan db:seed

[BadMethodCallException]
Call to undefined method Illuminate\Database\Query\Builder::assignRole()

Here my UserTableSeeder:
<?php
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;

class UserTableSeeder extends Seeder
{
    public function run()
    {
		//--create Role
		$adminRole = Role::create(['name' => 'admin']);
        		
        $password = 1234;

        // ---------- Administrator
        $user = User::create([
            'name' => 'Administrator',
            'email' => 'admin@example.com',
            'password' => $password,
        ]);
        $user->assignRole($adminRole);
        
or same 
        $user->assignRole('admin');

Could you explain to me, how to make usertableseeder?
Thanks

**Comment by freekmurze** [comment]
I'm guessing that you didn't add the `Spatie\Permission\Traits\HasRole` to the `User`.

If you want to learn more about creating seeders, take a look at [the official documentation](http://laravel.com/docs/5.1/seeding)

**Comment by teramandiri** [comment]
Here my User model :

<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Spatie\Permission\Traits\HasRoles;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    protected $table = 'users';

    protected $fillable = ['name', 'email', 'password'];

    protected $hidden = ['password', 'remember_token'];
	
	public function roles()
    {
        return $this->belongsToMany(Role::class);
    }
	
	public function assignRole($role)
    {
        return $this->roles()->attach($role);
    }
}

**Comment by freekmurze** [comment]
You imported the namespace but did not add the trait to the model.

Change the line
```php
use Authenticatable, Authorizable, CanResetPassword;
```
to 
```php
use Authenticatable, Authorizable, CanResetPassword, HasRoles;
```

**Comment by teramandiri** [comment]
Ok, it's work.
Many thanks

**Comment by freekmurze** [comment]
:+1:

**Comment by Omazon** [comment]
I tried that and it still does not work

**Comment by drbyte** [comment]
Closing the loop on this. As @Omazon said in https://github.com/spatie/laravel-permission/issues/305#issuecomment-362651530 the wrong User model was imported.

**Comment by lavenkin** [comment]
I use it in my db seeder ,  I can add some permissions and role by artisan, but I can't use user model to bind the permissions, It will has a error: `Method Illuminate\Database\Eloquent\Collection::assignRole does not exist.`, I check my model It has `Spatie\Permission\Traits\HasRole`

**Comment by drbyte** [comment]
> I use it in my db seeder , I can add some permissions and role by artisan, but I can't use user model to bind the permissions, It will has a error: `Method Illuminate\Database\Eloquent\Collection::assignRole does not exist.`, I check my model It has `Spatie\Permission\Traits\HasRole`

This is a basic Laravel usage issue.
If you study the error message, it will tell you a lot:
`Method Illuminate\Database\Eloquent\Collection::assignRole does not exist`
Notice that your object has an Eloquent Collection, not an individual user. This is the same as having an array of objects but you're trying to treat it as though it's only a single object.

Rework your db query to give you a single result ... an actual user object ... before trying to call methods/properties on the object.
