### ISSUE TITLE
migration tables not created

### ISSUE THREAD

**Issue by asinan007** [spatie/laravel-permission#1004]
I've run the command
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"

but only permission table was created

below tables weren't created
role_has_permissions
model_has_roles
model_has_permissions
roles

I am using laravel 5.6 and followed as the tutorial. Not sure what i am missing here

**Comment by drbyte** [comment]
> I am using laravel 5.6 and followed as the tutorial. Not sure what i am missing here

Which tutorial?

What was the output message when you ran the migrations?

**Comment by asinan007** [comment]
no error was given off, i am just running as it is in this tutorial.
permission table was created in the migration, but other tables weren't.

**Comment by drbyte** [comment]
You still didn't say which "tutorial" you followed. Did you mean the README in this github project? Or were you using somebody's tutorial on a blog somewhere?


I'm guessing there's something wrong with the database you're using?

I just did a fresh app install, and it created the tables fine. In this case I used Sqlite. I did an app deploy yesterday with it on MySQL/mariadb.

Here are the commands and their output:
`laravel new testapp`
```
Application ready! Build something amazing.
```

`cd testapp`

(edit my .env file to specify a database)

`composer require spatie/laravel-permission`
```
Using version ^2.29 for spatie/laravel-permission
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing spatie/laravel-permission (2.29.0): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/nexmo-notification-channel
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-permission
Package manifest generated successfully.
```

`php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"`
```
Copied File [/vendor/spatie/laravel-permission/config/permission.php] To [/config/permission.php]
Copied File [/vendor/spatie/laravel-permission/database/migrations/create_permission_tables.php.stub] To [/database/migrations/2019_01_19_222331_create_permission_tables.php]
Publishing complete.
```

`php artisan migrate`
```
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2019_01_19_222331_create_permission_tables
Migrated:  2019_01_19_222331_create_permission_tables
```

Check for tables in database:
`sqlite3 database/database.sqlite`
```
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> .tables
migrations             password_resets        roles
model_has_permissions  permissions            users
model_has_roles        role_has_permissions
```

**Comment by elfeffe** [comment]
I have a similar problem.
I'm using latest Laravel and package, and after I require the package and publish following the instructions here: https://docs.spatie.be/laravel-permission/v3/installation-laravel/

There are no migrations being published.

**Comment by jihadismail8** [comment]
same issue here

**Comment by krijustviktor** [comment]
I has too same problem.
I created permission using spaite and composer require command.
In migrations directory there is create_permission file exist.
So, i migrated but table not created.
i discovered this error when i rollback migration using php artisan migrate:rollback or php artisan migrate:reset.
what is the problem?
i used laravel 8 
And other laravel 8 project create table but now current project is same laravel 8 but not create table and has error when rollback.
also, i can see to be created personal_access_token table in current project.
what is reason?
Please help me.

**Comment by elfeffe** [comment]
I used them in a new project, with Laravel 8 and Composer 2 and they work.
Did you try with composer 2?

**Comment by krijustviktor** [comment]
how can i use composer 2?
i tried only "composer install spatie...".
i used same command but on other project it works well. but on current project, it not work.
Please..

**Comment by elfeffe** [comment]
Check the version that you have, search for "check composer version" on Google.
And if it's not 2, search for "how to install composer 2" again on Google.

**Comment by abdallah84** [comment]
i have Laravel 8 and i run  composer require spatie/laravel-permission and installed successfully but they didn't create the config file and migration files

**Comment by dayo116** [comment]
update composer and run php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"

**Comment by lennine3** [comment]
I faced the same error. but I fixed it. when I run  php artisan migrate it has an error
Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `permissions` add unique `permissions_name_guard_name_unique`(`name`, `guard_name`))
After searching, I found out that you have to add  Schema::defaultStringLength(191); in the boot function of the AppServiceProvider file, I delete the permission table in my DB and rerun the migration and it works.
The create_permission_tables migration file has contain all the files you need. just run it and it will work
By the way, if you use Laravel >8, check the migration file there are some notes for Laravel >8.

**Comment by SilvioArg** [comment]
> then migrate the tables will be created

Tnx buddy. This solution helps me!
