### ISSUE TITLE
assignRole() not working at RegisterController

### ISSUE THREAD

**Issue by xerod** [spatie/laravel-permission#1008]
I want to give my users a 'client' role (which i've been create with my seeder) every time they have register. 

I have `use HasRole` on my User model from the beginning but this code still didn't work for me. it work on my seeder but didn't work for this one (at RegisterController). 

**Code that didn't work:**
```
protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ])->assignRole('client');
    }
```

**Code that work:**
```
public function run()
{
        User::create([
            'name' => 'Admin', 
            'email' => 'admin@test.test',
            'password' => bcrypt('testing')
        ])->assignRole('admin');
}
```

why these two are different?

**Comment by drbyte** [comment]
"didn't work for me" is kinda vague.

You expected "something" to happen, and "something else" happened. What were those "something"s?

**Comment by xerod** [comment]
@drbyte the user that have register get a client role, but there's nothing happen in `model_has_roles`.

**Comment by xerod** [comment]
no error, no custom guards, i'm just using the web guard.

```
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
```

**Comment by drbyte** [comment]
1. I'll have to set up a custom app to try to recreate this. Is there anything I need to know to make sure my new Laravel 5.7 app works just like yours?

2. Have you tried not chaining the assignment? ie:
```diff
protected function create(array $data)
    {
-        return User::create([
+        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
-        ])->assignRole('client');
+        ]);
+        $user->assignRole('client');
+        return $user;
    }
```

**Comment by xerod** [comment]
i've tried to chaining the assignment before but still gives nothing :(

**Comment by xerod** [comment]
I create some workaround to solve this, i think this is not the laravel-permission issue. it's just the backpack. So i think i should set the issue as closed.
