### ISSUE TITLE
I want to add the an instance_id in Spatie laravel Package. When i put the field instance_id in Spatie builtin db table, After saving the record in table it return me error "SQLSTATE[HY000]: General error: 1364 Field 'instance_id' doesn't have a default value (SQL: insert into `language_lines`". How can i fix this issue any help ? 

### ISSUE THREAD

**Issue by TalhaZulfiqar69** [spatie/laravel-permission#1009]

**Comment by drbyte** [comment]
> "SQLSTATE[HY000]: General error: 1364 Field 'instance_id' doesn't have a default value (SQL: insert into `language_lines`"

The db error message you posted quotes the SQL statement `insert into 'language_lines'`. The `language_lines` table isn't part of this Spatie permissions package.

Two things to consider: 
1. Is this error really related to this spatie package?
2. When adding new fields to the database, you can specify a default value for those fields as part of your database schema in the migration logic, or directly in the database itself.
See https://laravel.com/docs/5.7/migrations#column-modifiers for the `->default()` syntax.
