### ISSUE TITLE
Add option to disable caching

### ISSUE THREAD

**Issue by csspcc** [spatie/laravel-permission#101]
It would be great if there was an option to disable permission caching in config file. 

What do you guys think?

**Comment by freekmurze** [comment]
Why would you want to disable the caching?

**Comment by csspcc** [comment]
Correct me if i'm wrong, but the cache gets reset every time you create/update/delete some model.

For example, I have "last_seen" date for User, every time user loads a page, the "last_seen" date gets updated and the cache gets reset, so for me there is no point in caching and I would disable it. 

But it would be cool to reset cache only when changes are made to roles and permissions tables, if this is a viable option.

**Comment by freekmurze** [comment]
You're certainly right, the cache does get deleted whenever the user gets updated. 

Unless you have some benchmarks that prove otherwise, I don't think the extra overhead of the deletion of the cache has a big hit on the performance of the package. So I'd like to keep it simple and just leave the code as it is.

**Comment by sazo** [comment]
I got a good argument - Testing.

I need to clear the cache before each test. Woot be nice just to disable it.

**Comment by Thirdwrist** [comment]
Here is my solution to this and how I went about it: 

`trait RefreshesPermissionCache
{
    public static function bootRefreshesPermissionCache()
    {
        static::saved(function () {
            app(PermissionRegistrar::class)->forgetCachedPermissions();
        });

        static::deleted(function () {
            app(PermissionRegistrar::class)->forgetCachedPermissions();
        });
    }
}`

**Comment by hayder1994ZH** [comment]
I solved it by set 1 seconds in expiration_time in the permissions config file, 
`'expiration_time' => \DateInterval::createFromDateString('1 seconds')`

**Comment by DevBodin** [comment]
I'd like to at least let it be known that such a feature would indeed have a use case, whether or not it might be worth the trouble. 

I'm currently developing a multitenant productivity site, which necessitated applying a global scope to my Role class.  (Each Account Owner is able to define their own roles.) So, anytime the cache is reset, it's reset with only one Account's Roles (every other Account appears to have none).

Setting the cache to 1 second seemed like a workable solution when I was testing locally on my own, but with concurrent users on different accounts, breakages happen regularly.

**Comment by erikn69** [comment]
Did you test `array` cache?
