### ISSUE TITLE
"Class 'App\Http\Controllers\User' not found"

### ISSUE THREAD

**Issue by JTD420** [spatie/laravel-permission#1019]
Trying to get this installed but keep running into issues along the way unfortunately :( This one I can't seem to get past, was hoping someone would be able to help me!

"
        $users = User::role('active subscriber')->get();
"

I get the error when using this code or just trying to call the "User::" function

Thanks

**Comment by drbyte** [comment]
Instead of `User::role`, use `\App\User::role` or add a `use \App\User;` statement to the top of your controller's imports list.

**Comment by DilshanDilipudara** [comment]
use App\User;
