### ISSUE TITLE
Duplicate permissions being created through artisan command

### ISSUE THREAD

**Issue by sumit22** [spatie/laravel-permission#1021]
On running this command two times two permissions with same name and guard name was created
$this->call('permission:create-permission',['name'=>'some_permission_name']);

Will suggest to add unique index on permissions.name and permissions.guard fields of permissions table or this should be handled in code itself.

**Comment by drbyte** [comment]
That command calls the `create` method on the model, which already does a lookup to prevent duplicates, and throws an exception it already exists:

https://github.com/spatie/laravel-permission/blob/5f9960854295c6aec1c706aaa3b146962d6ee905/src/Models/Permission.php#L39-L41

**Comment by sumit22** [comment]
After creation of permission, cache doesn't gets updated, and this check you mentioned is done from cache. as a result duplicate permission will be generated.

**Comment by drbyte** [comment]
Interesting. 
The cache should be updated because of the `RefreshesPermissionCache` trait on that model.

Will mark it as a bug. 

Thanks!
