### ISSUE TITLE
"@can" not working with this package.

### ISSUE THREAD

**Issue by narges70** [spatie/laravel-permission#1026]
Hi,
I  succesfully created roles and assigned permission to those roles.

Calling @can('project managment') is simply doing nothing. and does not work @role('admin') in blade. No Exception. No return.

i used the following command to flush your cache but does not work:
php artisan cache:forget spatie.permission.cache

i deleted cache manually and by command but does not work!

any ideas??

**Comment by drbyte** [comment]
This package registers your defined permissions with Laravel's Gate layer, and then the `@can` directive simply responds to whether Laravel's Gate agrees that the permission is allowed at this time.

So, if `@can` is not responding as expected, then multiple things could be at play:
- the permission is not registered for the current user, for the guard the user is using
- another package is interfering
- your own app code is interfering

**Comment by narges70** [comment]
thank you @drbyte 

i create admin role and assign permissions, so make user and assign role for its.
how to fix this problem...?!
does not work @can, @role, and can() function!

**Comment by drbyte** [comment]
The package tests for `@can` and `@role` pass, and you can see a demo app here where the directives work: https://github.com/drbyte/spatie-permissions-demo/

So, something must be wrong in your app.

**Comment by quchuanbao** [comment]
The package default guard in 'config/auth.php' is first one ,if you have myself guard, You can modify "config/auth.php" like this 
`  'guards' => [
        'admin' => [
            'driver' => 'passport',
            'provider' => 'users',
            'hash' => false,
        ],
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],`
put your define guard first , Your code will run smoothly！
