### ISSUE TITLE
The command "permission:cache-reset" does not exist

### ISSUE THREAD

**Issue by ahmedkandel** [spatie/laravel-permission#1029]
Hi @freekmurze 

Trying to call the reset cache command using Artisan Facade:

`Artisan::call('permission:cache-reset');`

It throws exception CommandNotFoundException.

while if manually registered on app/Console/Kernel.php

```
protected $commands = [
    \Spatie\Permission\Commands\CacheReset::class,
];
```
It works.

Thanks

**Comment by drbyte** [comment]
Where in your app are you doing this Artisan call? 

Is it in Tests?
Is it in core app code?

Why are you using an Artisan call instead of just [calling the service provider directly](https://github.com/spatie/laravel-permission#manual-cache-reset)? 
(I'm asking because understanding your reasoning helps us determine the best way to resolve your reported issue.)

**Comment by ahmedkandel** [comment]
It's in the app code.

I do an Artisan call as I am using Laravel Nova with [command runner](https://github.com/guratr/nova-command-runner) to give the admin the ability to do some cache related tasks, one of them is resting the permissions cache. I do have a middleware to do this whenever permission is assigned so it is optional to give a better user experience.

as a solution, I have registered the command manually on the kernel and it is working. But regardless of Nova or the approach if I create a simple route with a closure to call the command using Artisan it fails.

**Comment by drbyte** [comment]
@ahmedkandel Can you list some packages whose artisan commands "do" work with the approach you're trying?

**Comment by ahmedkandel** [comment]
Hello @drbyte 
`debugbar:clear` from [laravel-debugbar](https://github.com/barryvdh/laravel-debugbar)
`backup:clean` from [laravel-backup](https://github.com/spatie/laravel-backup)

**Comment by drbyte** [comment]
Interesting. Neither of those run the check in the serviceProvider to only register "when in console mode", like this package does. Theoretically that's because one of them is already a console-only tool, and the other is a non-production tool.

**Comment by drbyte** [comment]
At this time there are no plans to expose this package's Artisan commands outside of command-line use.
As you posted, you can simply register the command in your app if your app needs to run the command under other circumstances.
