### ISSUE TITLE
Web app is slow after giving permissions to roles

### ISSUE THREAD

**Issue by Zolak94** [spatie/laravel-permission#1030]
I have around 50 permissions and 4 roles, after giving permissions to roles (around 150 in total in role_has_permissions table), my web app is really slow. My way of checking for permissions is in almost every function that returns view in my controllers Iwould have something like this:

```
if(!Auth::user()->hasPermissionTo('show location')) {
    return redirect()->back()->with('fail', 'You have no permission for that.');
}
```

Am I doing something wrong or?

**Comment by Zolak94** [comment]
One more thing, I use a lot of @can in my navbar and I manage to get the time of loading and its 300+ms before it was only 20-30ms.

**Comment by JinalSomaiya** [comment]
i have also same issue more query listed in laravel-debugbar. so, what to do?

**Comment by drbyte** [comment]
Given that #1031 suggests there may be an issue with caching for certain drivers, a couple questions:
1. What cache driver are you using?
2. Does downgrading to version 2.25.0 improve the performance issue? (the caching logic was changed in 2.26.0)

**Comment by JinalSomaiya** [comment]
i am using
1. CACHE_DRIVER=array
2.  "spatie/laravel-permission": "^2.15",

**Comment by drbyte** [comment]
@JinalSomaiya is this query issue "new" for you? Or when did it start?

**Comment by JinalSomaiya** [comment]
when i add more times check more query added in laravel-debugbar. 
like this:
`@if(auth()->user()->can(\App\Domain\Permission\Permission::PERMISSION_VIEW_AND_MANAGE_LEADS) || auth()->user()->can(\App\Domain\Permission\Permission::PERMISSION_ALLOCATE_LEADS))
                <li class="nav-item {{ request()->is('leads*') ? 'active' : '' }}">
                    <a href="{{ route('dealer:leads') }}" class="nav-link">
                        <i class="sidebar-icon lead-inquiries-icon"></i>
                        <p>Lead inquiries</p>
                    </a>
                </li>
            @endif`
if i am add more if condition then more query added. so, what to do?

**Comment by matthewgoslett** [comment]
I've noticed the same huge performance drop after updating to the latest version (which has the caching tweaks & optimisations).

As an example, we have a page which displays a table of data.  For each row in the table, we check against various permissions.  In this particular sample, we land up doing 1740 synchronous calls (387ms) to a memcached server.

<img width="748" alt="screenshot_1074" src="https://user-images.githubusercontent.com/1571743/53149502-8b5da180-35b6-11e9-9e96-6c8a5fe9ddb6.png">

**Comment by drbyte** [comment]
> ... after updating to the latest version ...

What version were you using before you "updated"?

**Comment by matthewgoslett** [comment]
> > ... after updating to the latest version ...
> 
> What version were you using before you "updated"?

We were on 2.21

**Comment by Zolak94** [comment]
> Given that #1031 suggests there may be an issue with caching for certain drivers, a couple questions:
> 
> 1. What cache driver are you using?
> 2. Does downgrading to version 2.25.0 improve the performance issue? (the caching logic was changed in 2.26.0)

1. I'm using default one which is file `'default' => env('CACHE_DRIVER', 'file'),`
2. I don't know how to downgrade (can you help me with that?).

**Comment by drbyte** [comment]
@Zolak94 to downgrade to 2.25.0, you can run: `composer require spatie/laravel-permission:"2.25.0"`

Alternatively you can specify the version you want in your `composer.json` and then run `composer update`.

**Comment by Zolak94** [comment]
@drbyte unfortunately after downgrading to 2.25.0 it's still taking a long time to load pages, up to 5 seconds.

**Comment by drbyte** [comment]
https://github.com/spatie/laravel-permission/releases/tag/2.35.0 contains the excellent fixes from @matthewgoslett which should help with these performance issues.

**Comment by Zolak94** [comment]
> https://github.com/spatie/laravel-permission/releases/tag/2.35.0 contains the excellent fixes from @matthewgoslett which should help with these performance issues.

Sorry for late response, now everything is working, thank you.
