### ISSUE TITLE
Permissions may not be cached if permission name contains a space

### ISSUE THREAD

**Issue by matthewgoslett** [spatie/laravel-permission#1031]
Version: 2.32.0
Cache Driver: memcached

This is dependent on the cache driver, and specifically, what the cache driver deems a safe cache key.

The cache read/write & subsequent read will never hit if the permission contains a space: eg: "Manage Users".  The cache key in this case is "spatie.permissions.Manage Users".
I'd suggest hashing the key in the `getKey` method of the `PermissionRegistrar`.

**Comment by matthewgoslett** [comment]
The `getPermissionCacheKey` in the `HasPermissions` trait is also affected by this.  I haven't dug too deeply yet, so not sure if there any other areas in the code which touch the cache.

**Comment by matthewgoslett** [comment]
I'm busy testing a WIP fork here - https://github.com/spatie/laravel-permission/compare/master...MasterStart:master

In addition to this, and whilst a separate issue, but checking for the same permission multiple times, when the cache driver is memcached, will have a significant impact on performance.

ie: If you have a page which spits out a table of users, and for each row in the table, you want to check that the user can `View User`, can `Edit User`, can `Change User Password`, etc.  200 rows of data * 3 permissions = 600 memcached calls.  A solution previously suggested is to also implement an in-memory object cache.

**Comment by drbyte** [comment]
On the "permission name contains a space" I get all the package tests passing for other drivers, but need to re-install memcached to test that.

On the separate performance comment, #804 began some discussion and investigation on improving performance, but it's been stalled awhile.

**Comment by drbyte** [comment]
Confirmed. Spaces are indeed a problem when using memcached.

**Comment by drbyte** [comment]
.. and array or redis ... :(

**Comment by drbyte** [comment]
@matthewgoslett I'm thinking the following changes to CacheTest.php should be a suitable test for a possible fix:

```diff
    /** @test */
    public function has_permission_to_should_use_the_cache()
    {
+        app(Permission::class)->create(['name' => 'with spaces']);
-        $this->testUserRole->givePermissionTo(['edit-articles', 'edit-news']);
+        $this->testUserRole->givePermissionTo(['edit-articles', 'edit-news', 'with spaces']);
        $this->testUser->assignRole('testRole');

        $this->resetQueryCount();
        $this->assertTrue($this->testUser->hasPermissionTo('edit-articles'));
        $this->assertQueryCount($this->cache_init_count + $this->cache_load_count + $this->cache_run_count + $this->cache_relations_count);

        $this->resetQueryCount();
        $this->assertTrue($this->testUser->hasPermissionTo('edit-news'));
        $this->assertQueryCount($this->cache_run_count + $this->cache_untagged_count);

        $this->resetQueryCount();
+        $this->assertTrue($this->testUser->hasPermissionTo('with spaces'));
        $this->assertTrue($this->testUser->hasPermissionTo('edit-articles'));
        $this->assertQueryCount($this->cache_init_count);
    }
```

**Comment by nickparker39** [comment]
I believe I have the same issue. My app uses spaces in permission names as well.

When checking the permission on the role, it will return true. Checking on the user will return false.

```php
$role = Role::find(1);
$role->hasPermissionTo('view plans'); // true

$user = User::find(1);
$user->roles; // has same role as above
$user->hasPermissionTo('view plans'); // false
$user->roles()->first()->hasPermissionTo('view plans'); // true
```

Running `php artisan cache:clear` is a temporary fix, but I've been trying to figure this out for a couple weeks now. I'll take a look at the code, but I'm also not quite as familiar.

**Comment by dudedigital** [comment]
I also face this issue with spaces in my permissions. I'm running Vagrant Homestead with Laravel 5.7 locally. I have an API call that checks 200+ permissions against the user to build the navigation. With file as my cache driver, it was taking 80 seconds to complete. Switching to memcached reduced it to 6.8 seconds. With @matthewgoslett changes, file and memcached both drop to 2.9 seconds.

**Comment by drbyte** [comment]
https://github.com/spatie/laravel-permission/releases/tag/2.35.0 is released, with @matthewgoslett fixes
