### ISSUE TITLE
more query added in barryvdh/laravel-debugbar if more condition check in sidebar?

### ISSUE THREAD

**Issue by JinalSomaiya** [spatie/laravel-permission#1032]
if i add condition like this:
`@if(auth()->user()->can(\App\Domain\Permission\Permission::PERMISSION_VIEW_AND_MANAGE_LEADS) || auth()->user()->can(\App\Domain\Permission\Permission::PERMISSION_ALLOCATE_LEADS))
                <li class="nav-item {{ request()->is('leads*') ? 'active' : '' }}">
                    <a href="{{ route('dealer:leads') }}" class="nav-link">
                        <i class="sidebar-icon lead-inquiries-icon"></i>
                        <p>Lead inquiries</p>
                    </a>
                </li>
            @endif`

and add another if condition then more query added. so, what to do?

**Comment by drbyte** [comment]
2.35.0 fixed a bug with permission names containing spaces. Perhaps that will help.
