### ISSUE TITLE
Label field in roles and permissions

### ISSUE THREAD

**Issue by amieiro** [spatie/laravel-permission#104]
Hello

The Laracasts project in which is based this package has the "label" field in the tables "roles" and "permissions". You can take a look at the [migration](https://github.com/laracasts/laravel-5-roles-and-permissions-demo/blob/master/database/migrations/2015_09_10_193651_create_roles_tables.php).

I think that could be interesting add this "label" field, because with this element a "role" or a "permission" could have:
- "name", to use in the code: an ugly text for the end user.
- "label", to show to the end user in the views: a readable element.

If you consider it interesting I can make the enhancement and send a pull request.

Thank you

**Comment by freekmurze** [comment]
Currently I'm not in favour of including a `label` field by default. If you need this you could just add the field in your own project.
