### ISSUE TITLE
cache not right when using multi guard

### ISSUE THREAD

**Issue by zhengwhizz** [spatie/laravel-permission#1040]
`$u->hasPermissionTo("revoke permission",'api');`
first run , it's ok, but when it's cached , i changed to 
`$u->hasPermissionTo("revoke permission",'api2');`
 it always retrun the same result, even I don't have the guard named "api2"

**Comment by drbyte** [comment]
What cache driver are you using with this package?

**Comment by zhengwhizz** [comment]
i'm using  redis  for cache. i know why, the cache key only using spatie....App.User.id , not has guard.

**Comment by drbyte** [comment]
I've added another cache test to ensure that the cache respects multiple guards.
