### ISSUE TITLE
Call to undefined method App\\User::hasAnyRole()

### ISSUE THREAD

**Issue by rajdipchauhan** [spatie/laravel-permission#1041]
Hello,

I have install this package in Laravel 5.7.

Everything is work fine like assignRole, getAllPermissions, getDirectPermissions, getPermissionsViaRoles but when I'm applying it in route its give me error for hasAnyRole and hasRole.

Please help me to resolve this ASAP.

**Comment by hamidafghan** [comment]
Any code snippets please.

**Comment by rajdipchauhan** [comment]
Hello,

Here is the code snippets of Model, Controllers

User.php (Model File)

`namespace App\Models;

use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    use HasRoles;
    protected $guard_name = 'api';
}`

MemberController.php (Controller file)

`namespace App\Http\Controllers\Api\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
//use App\Models\Role;
use Illuminate\Support\Facades\Auth;
use Hash;
use Validator;
use Config;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class MemberController extends Controller
{
    public function createMember(Request $request)
    {
     $user->assignRole('Admin');
    }
}
`
I have added this path in route Middleware
`protected $routeMiddleware = [
    // ...
    'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,
    'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,
    'role_or_permission' => \Spatie\Permission\Middlewares\RoleOrPermissionMiddleware::class,
];`

Now When I'm adding middleware for Role Authentication its give me error,

`Route::group(['middleware' => ['role:Admin']], function () {
}`

**Comment by hamidafghan** [comment]
Make sure the user is login be for attempting ``` Route::group(['middleware' => ['role:Admin']], function () {
} ``` routes.

**Comment by rajdipchauhan** [comment]
Yes I already did that, I have written this above routes in Admin.php route file and imported this route file in Api.php in which I had check Auth middleware.
Look at snippets of it.

```
Route::middleware(['auth:api', 'cors'])->group(function () {
   require base_path() . '/routes/admin.php';
}
```

In Admin.php route file

```
    Route::group(['middleware' => ['role:Admin']], function () {
        // Member Route
        Route::post('/create-member', 'Api\Admin\MemberController@createMember');
        Route::post('/edit-member', 'Api\Admin\MemberController@editMember');
        Route::get('/view-member/{id}', 'Api\Admin\MemberController@viewMember');
        Route::get('/delete-member/{id}', 'Api\Admin\MemberController@deleteMember');
        Route::post('/members', 'Api\Admin\MemberController@getMembers');
    });
```

**Comment by hamidafghan** [comment]
Where did you use the ``` hasAnyRole ``` middleware exactly?

**Comment by rajdipchauhan** [comment]
I didn't use it separately but when I'm using

```
Route::group(['middleware' => ['role:Admin']], function () {
}
```
 in admin routes it goes on below path where its check  hasAnyRole()

/vendor/spatie/laravel-permission/src/Traits/HasRoles.php

**Comment by drbyte** [comment]
I notice you're using the `api` guard in your User model. Is your app using any other guards? Is `api` the default guard in your config file?

**Comment by rajdipchauhan** [comment]
Yes, api is default guard in a config file.

I found my issue and its related App\User object. It's not working when I am using App/User but it's working fine when I am using Query\Builder object.

What should I need to change for this?

I'm assigning role when User created

```
$user = User::create($data);
$user->assignRole('Member');
```

**Comment by drbyte** [comment]
I can't duplicate this situation. Is something else in your app conflicting with what Auth::user() returns?

**Comment by banstola** [comment]
I have issue but it seems the thread does not provide a solution.

**Comment by drbyte** [comment]
@banstola Please create a quick sample app where this is occurring and post a link to it on github.

**Comment by esmatulla** [comment]
Please help me this error any one

 BadMethodCallException 

  Call to undefined method App\User::assignRole()

  at vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50
    46|      * @throws \BadMethodCallException
    47|      */
    48|     protected static function throwBadMethodCallException($method)
    49|     {
  > 50|         throw new BadMethodCallException(sprintf(
    51|             'Call to undefined method %s::%s()', static::class, $method
    52|         ));
    53|     }
    54| }
