### ISSUE TITLE
  PermissionAlreadyExists  : A `edit users` permission already exists for guard `web`

### ISSUE THREAD

**Issue by juancrescente** [spatie/laravel-permission#1044]
Even doing the required cache clearing I still get that the permission already exists
```
app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();
app()['cache']->forget('spatie.permission.cache');
        // create permissions
        Permission::create(['name' => 'edit users']);
```

php artisan cache:clear
 php artisan cache:forget spatie.permission.cache

**Comment by drbyte** [comment]
Yes, the `PermissionAlreadyExists` will fire when the permission is already present in the table.
And, since your call to `create` doesn't specify a guard, the `web` guard is being detected from the config automatically. 

This is by design.

**Comment by juancrescente** [comment]
oh ok, so I should add the permissions creation in a Migration, so it is executed only once. Sorry for the little understanding I have even of Laravel
