### ISSUE TITLE
Delete User not deleting roles and permissions

### ISSUE THREAD

**Issue by NHuebner1983** [spatie/laravel-permission#1047]
I am using $user->forceDelete() -- I want the user's permissions gone.

They are still in the database.

This is kind of like on Facebook if you "Delete Account" you want every trace of your data gone.

We're expecting millions of users, so it's important to clean up as much as possible.

What's the best way to handle this? Does it involve iterating?

**Comment by drbyte** [comment]
Do you have permissions directly registered to the user? or are they connected via roles? 
Are you using SoftDeletes?

The `HasPermissions` and `HasRoles` [traits register a `deleting` event action to `detach` permissions from the model](https://github.com/spatie/laravel-permission/blob/35a85e4c7b787ebfc1e700640ff8c39c3d6571e7/src/Traits/HasPermissions.php#L25), and it specifically checks for force-deleting.

**Comment by NHuebner1983** [comment]
yeh it looks like it only happens on force-delete, which is right. Sorry to bug you :)
