### ISSUE TITLE
Conflict of HasPermissions trait with Model Role class upon extension

### ISSUE THREAD

**Issue by highstrike** [spatie/laravel-permission#1049]
Okay so,

I've extended the `Spatie\Permission\Models\Role` class to my own `App\Models\Role` and then also extended the `Spatie\Permission\Traits\HasPermissions` trait to my own `App\Models\Trait\LogHasPermissions`

However, when I want to use my own trait in the extended class, like so:
```
namespace App\Models;

use App\Models\Traits\LogHasPermissions;
use Spatie\Permission\Models\Role as SpatieRole;
use Spatie\Activitylog\Traits\LogsActivity;

class Role extends SpatieRole
{
    use LogsActivity;
    use LogHasPermissions;
```

I get the following fatal error `Declaration of App\Models\Traits\LogHasPermissions::permissions(): Illuminate\Database\Eloquent\Relations\MorphToMany must be compatible with Spatie\Permission\Models\Role::permissions(): Illuminate\Database\Eloquent\Relations\BelongsToMany`

Apparently the `permissions` function defined in the original trait is overwritten in the original role model class (because the function is defined there, therefore it overwrites the trait).

So extending the class and using my own trait (while not having the function defined because i was expecting it from the parent) will use the function from the trait instead, resulting in the above error.

I can avoid the error by also defining a `permissions` function in my own role class like so
```
public function permissions(): BelongsToMany {
    return parent::permissions();
}
```

But surely there must be a better way to do this?
Thank you!

**Comment by drbyte** [comment]
Have you used PHP's built-in trait method overloading?
See example posted by @robjbrain at https://github.com/spatie/laravel-permission/issues/754#issuecomment-468228085

```php
trait HasRolesTrait
{
    use HasRoles {
        assignRole as protected originalAssignRole;
        removeRole as protected originalRemoveRole;
        syncRoles as protected originalSyncRoles;
    }
//...
}
```

**Comment by highstrike** [comment]
Yeah, that's actually what inspired me to pursue extending the trait.

But traits are like copy / paste code and whatever is in the class will overwrite them, in my case extending the class as well, the trait takes precedent.

So my trait looks exactly like what @robjbrain wrote in #754 

> Apparently the `permissions` function defined in the original trait is overwritten in the original role model class (because the function is defined there, therefore it overwrites the trait).

> So extending the class and using my own trait (while not having the function defined because i was expecting it from the parent) will use the function from the trait instead, resulting in the above error.

This is the underlying problem, I don't think it's a problem with the code of this repository, but with the architecture of PHP.

My question was if there was a better way to achieve what i wanted, without defining this function in my class
```
public function permissions(): BelongsToMany {
    return parent::permissions();
}
```

**Comment by drbyte** [comment]
Agreed.

I haven't run into the problem myself, so haven't had to explore alternatives that deeply. :(

**Comment by highstrike** [comment]
okay, thanks anyway :)

**Comment by drbyte** [comment]
@highstrike, the feedback I've gotten by consulting some colleagues is that the approach you've taken is the right one.
