### ISSUE TITLE
PermissionDoesNotExist exception when permission exists

### ISSUE THREAD

**Issue by beard7** [spatie/laravel-permission#1057]
I've just upgraded to Laravel 5.8 and laravel-permission 2.36.0, and now I'm getting `PermissionDoesNotExist` exceptions for all permissions except one.

This is happening when performing something like `$user->hasPermissionTo('do something')`, but when doing `$user->getAllPermissions()` the `do something` permission is in the returned collection. In Blade templates, `@can('do something')` is also returning false.

I've noticed a couple of similar issues that were caused by caching, but I've cleared the cache using `php artisan permission:cache-reset` and also manually removing eveything in the `storage/framework/cache`  folder.

Any suggestions?

**Comment by drbyte** [comment]
Hm, I haven't run into that (and the test suite shows the tests are passing), but do the symptoms change if you edit your `composer.json` to set this package to version `2.35.0` and run `composer update`?  Then test `2.34.0`.

Also, it would help to see your app code, or at least explain how exactly I could recreate the same symptoms on a fresh L5.8 install.

**Comment by beard7** [comment]
@drbyte thanks for the suggstion re. using `2.35.0`: the symptoms are dramatically different, i.e. it fixes my issues. I'll see if I can figure out what's changed, but I'm happy to stick with `2.35.0` for now.

**Comment by drbyte** [comment]
Thanks. Researching the "why", to figure out a broader solution.
In your app are you doing anything guard-specific? Or just using the default `web` guard?

**Comment by beard7** [comment]
There are a coupke of things that springs to mind.

Firstly, I'm using the `adldap2/adldap2-laravel` package for authenticating against our AD server. The guard is still `web`, the only real difference in the `config/auth.php` is in the `providers` array:
````
'providers' => [
        'users' => [
            'driver' => 'ldap',
            'model' => App\User::class,
        ],
    ],
````
the driver is `ldap` rather than `eloquent`.

Secondly, I'm using my own Role and Permission models (but I can't remember why). I'll try reverting to the package supplied models.

I don't know if that helps.

**Comment by beard7** [comment]
Using the supplied Role and Permission models has solved the issue (apologies, it was a bit stupid of me to forget I'd done that).

I think the only reason I'd used my own models was that I added an extra `descripion` field, but that doesn't require different models.

Thanks for your quick response.
