### ISSUE TITLE
Data table is very very slow for large data

### ISSUE THREAD

**Issue by shifatbuet** [spatie/laravel-permission#1060]
How to overcome this issue??

**Comment by drbyte** [comment]
> How to overcome this issue??

No idea. We can't guess what your code is doing, especially since you've provided no troubleshooting information.
Supply complete details for how I could recreate your exact same problem starting with a new Laravel app.

**Comment by shifatbuet** [comment]
Just try to get 10000 user
 row in index blade of user.

(User view blade has datatable)


Thanks for your quick reply

**Comment by drbyte** [comment]
I'm not surprised that displaying 10,000 users on one page is "slow" (and you didn't define how slow is "slow"), regardless of application. Even without using a datatable strategy or package.
But this package isn't providing datatables.

**Comment by shifatbuet** [comment]
That's what I am talking about.
I don't want to fetch 100000 at a time ....
I want first 100, then on click next 100 something like this.
....

**Comment by drbyte** [comment]
Laravel has built-in pagination capabilities with Eloquent.
https://laravel.com/docs/5.8/pagination

**Comment by shifatbuet** [comment]
Okay. I will try that.
Thanks for your suggestions
And also for this amazing project.
I will  keep in touch with you 
Coz I am using your project. 😊

**Comment by josegus** [comment]
This is not aboud datatable. This usually happen because the roles are getting retrieved with the user model. This happen to me using medialibrary.
