### ISSUE TITLE
hasAnyPermission not repecting Gate::before for Super Admin

### ISSUE THREAD

**Issue by waw3** [spatie/laravel-permission#1062]
auth()->user()->hasAnyPermission(['some.permission']) returns false
auth()->user()->can('some.permissions') return true

composer:
laravel/framework": "5.8.*
spatie/laravel-permission": "^2.36

**Comment by samfrjn11** [comment]
What's the value of your `name` in your database?

**Comment by waw3** [comment]
permissions table as follows

id, name, guard_name, created_at, updated_at

**Comment by waw3** [comment]
real world example
auth()->user()->hasAnyPermission(['product.update', 'product.create']) returns false
auth()->user()->can('product.update') return true
auth()->user()->can('product.create') return true

**Comment by samfrjn11** [comment]
Yes, but do you have a record in that table where `name` is exactly `product.update`?

**Comment by waw3** [comment]
yes

**Comment by waw3** [comment]
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`)
VALUES
	(30, 'product.update', 'web', '2019-03-11 02:45:16', NULL);

**Comment by waw3** [comment]
if you or someone else cant reproduce then no worries.. i got something screwy

**Comment by waw3** [comment]
also 

auth()->user()->hasAllPermissions(['product.update', 'product.create']) return false

**Comment by samfrjn11** [comment]
Only thing I can think of in your case, is that it's looking for a permission under a different `guard`
are all your guards on 'web'? and in your config/auth.php defaults => guard = web?

**Comment by waw3** [comment]
does auth()->user()->hasAnyPermission tie into
Gate::before(function ($user, $ability) { });

Basically in my AuthServiceProvider im setting a global Role to allow for ALL permissions
Gate::before(function ($user, $ability) {
            if ($user->hasRole('Admin#' . $user->business_id)) {
                 return true;
            }
        });

**Comment by waw3** [comment]
i apologize.. this isn't a bug.. i was assuming it does.. but that isnt the case here

**Comment by waw3** [comment]
Gate::before(function ($user, $ability) {
            return $user->hasRole('Admin#' . $user->business_id) ? true : null;
        });

this does return true;

**Comment by waw3** [comment]
> Only thing I can think of in your case, is that it's looking for a permission under a different `guard`
> are all your guards on 'web'? and in your config/auth.php defaults => guard = web?

yes all guard names are web

**Comment by waw3** [comment]
config/auth.php

'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

**Comment by waw3** [comment]
ok so My role Admin#1 does not have any permission set in the table role_has_permissions
reason is because i have this defined in my AuthServiceProvider:
Per Wiki: https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role
`
Gate::before(function ($user, $ability) {
    return $user->hasRole('Admin#' . $user->business_id) ? true : null;
});
`

This works when you use for Admin#1
`
auth()->user()->can('product.create')
auth()->user()->can('product.update')
`

but NOT when you use:
`
auth()->user()->hasAnyPermission(['product.update', 'product.create'])
auth()->user()->hasAllPermissions(['product.update', 'product.create']) 
auth()->user()->hasPermissionTo('product.update')
auth()->user()->hasPermissionTo('product.create')
`

after adding the permissions to role_has_permissions this works as it should

Questions then is:
Per Wiki: https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role

Should adding the this:
`
Gate::before(function ($user, $ability) {
    return $user->hasRole('Admin#' . $user->business_id) ? true : null;
});
`
Allow me not to have to add all permissions for Role Admin#1?

**Comment by samfrjn11** [comment]
laravel-permission registers your permission in the Laravel Gates, but with 
```
Gate::before(function ($user, $ability) {
return $user->hasRole('Admin#' . $user->business_id) ? true : null;
});
```

you basically say 'if the user has the Admin#BUSINESS_ID role, grant access to everything and don't do any further permission checks'
So if you'd `$user->can('kill a bug')` it will ALWAYS return true, because your before gate already has permission.
BUT:
If you use the laravel-permission methods like `$user->hasPermission()`, laravel-permission will fetch  all the permission for this particular user from the database.

So if you have no relation between this user and this permission or relation between a user with a role (where the role has a relation with the permission) it will return false.

**Comment by samfrjn11** [comment]
So in your example:

`auth()->user()->hasAnyPermission(['some.permission'])` returns false because the user is probably not associated with this permission in any way
`auth()->user()->can('some.permissions')` returns true because the user has granted access via the Gate::before because he has the role Admin#BUSINESS_ID

**Comment by waw3** [comment]
yes what your say is true

i was assuming with the Gate::before, i didnt have to add permission for a user with Role Admin#1. It would act like a Super Admin per the wiki

My implementation is a helper function: 

usage 
userCan('product.update') 
userCan(['product.update', 'product.create']) // allow multiple perm

if (! function_exists('userCan')) {
    function userCan($permission = ''){
        if(is_array($permission)) {
          /*  return auth()->user()->hasAnyPermission($permission); */
            foreach ($permission as $perm) {
                if (!auth()->user()->can($perm)) {
                    return false;
                }
            }
            return true;
        }
        return auth()->user()->can($permission);
    }
}

this works as i need with Gate::before so i dont have to add permissions for a user with Role Admin#BUSINESS_ID (Super Admin)

**Comment by waw3** [comment]
> So in your example:
> 
> `auth()->user()->hasAnyPermission(['some.permission'])` returns false because the user is probably not associated with this permission in any way
> `auth()->user()->can('some.permissions')` returns true because the user has been granted access via the Gate::before because he has the role Admin#BUSINESS_ID


Is it true to say that the wiki https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role is miss leading or wrong

Why would they say:
If you want an "Admin" role to respond `true` to all permissions, without needing to assign all those permissions to a role, you can use Laravel's `Gate::before()` method. For example:

if it does NOT work with any laravel-permission methods and ONLY works with Laravels Native
`auth()->user()->can('some.permissions')`

**Comment by samfrjn11** [comment]
> If you want an "Admin" role to respond true to all permissions, without needing to assign all those permissions to a role, you can use Laravel's

That is actually correct.. In case you use that Gate::before and it returns true, it will return true for any can()

**Comment by drbyte** [comment]
> Is it true to say that the wiki https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role is miss leading or wrong
> 
> Why would they say:
> If you want an "Admin" role to respond `true` to all permissions, without needing to assign all those permissions to a role, you can use Laravel's `Gate::before()` method.
> 
> if it does NOT work with any laravel-permission methods and ONLY works with Laravels Native
> `auth()->user()->can('some.permissions')`

The Wiki article is correct.
- `can` uses Laravel's `Gate` layer, which combines the Gate::before with real permission record lookups.
- `hasPermissionTo`/etc only looks for real permission records
- `hasRole`/etc only looks for real role records

It is best-practice to use `can` for all your permission-checking everywhere in your app.

**Comment by h0wReYa** [comment]
> It is best-practice to use `can` for all your permission-checking everywhere in your app.

How can you make this work with **can** ?
Route::get('...}', '...Controller@edit')->middleware(['role_or_permission:Developer|edit blabla']);

**Comment by drbyte** [comment]
> How can you make this work with **can** ?
> Route::get('...}', '...Controller@edit')->middleware(['role_or_permission:Developer|edit blabla']);

Using `can` requires testing against permissions only, not roles. That was the point of my earlier comment: don't base your app on roles; use roles to group permissions, but have the application only test for permissions. That way you can reassign permissions to various roles if needed, and allows greater granularity when you need it later.
So, to do that with middleware, test for the permission, not the role. Or skip the middleware and put the test into your controller (or better, into a policy that the controller invokes).
