### ISSUE TITLE
Cache reset not working with redis or memcached

### ISSUE THREAD

**Issue by kalemdzievski** [spatie/laravel-permission#1063]
The command 'permission:cache-reset' does not seems to be working with either redis or memcached as cache drivers.

Has anyone else experienced this problem?

Version:2.34.0.

Thanks for any help in advanced!

**Comment by drbyte** [comment]
I haven't encountered that myself. 
Care to provide more details? Particularly anything that would help re-create your exact environment and app functionality.

**Comment by kalemdzievski** [comment]
Hello, sorry for the late response.

I have a Laravel 5.7 application inside Docker container (Custom image with PHP 7.2, nginx). 
Redis or Memcached are also in docker containers (Official docker images: redis, memcached).
Currently using redis container. The redis container is used for other purposes (like queue driver, key-value db), and they are working fine.

Simple scenario is where I have the permissions set and cached, then I delete a permission and run the command `permission:cache-reset`, and the cache is not cleared. The other way around also does not work. If I add new permission, and run the command, the cache is still not cleared.
However the cache resets after 24h (the expiration_time config).

I know that it might be hard to replicate, so would you suggest any steps for debugging ?
Thanks!

**Comment by drbyte** [comment]
You don't need to clear the cache manually when using the package's API for creating/deleting permissions: it takes care of that automatically for you. It does this using the same cache store as the manual reset uses. To do that it's resolving the cache store from your app config, in this section of the code:
https://github.com/spatie/laravel-permission/blob/bf26e5af34831cf6c9b5d937eb76c9fca9a3143b/src/PermissionRegistrar.php#L72-L91

Perhaps your environment has a container/app mismatch happening where your app does its create/delete/reset vs where it does the main reading (and therefore caching) of permissions data.
