### ISSUE TITLE
How to add area_code column to model_has_roles table?

### ISSUE THREAD

**Issue by satishnreddy999** [spatie/laravel-permission#1068]
Hi,
For My Project requirement. i added a new column to model_has_roles table. but not sure how to use it. for example when we retrive roles and permission using default query, i want to select 'area_code column with where condition. 
Please advise. thanks in advance

**Comment by satishnreddy999** [comment]
> Hi,
> For My Project requirement. i added a new column to model_has_roles table. but not sure how to use it. for example when we retrive roles and permission using default query, i want to select 'area_code column with where condition.
> Please advise. thanks in advance

So extending the above question with example select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` in (2) and `model_has_roles`.`model_type` = 'App\User' i want to add my new column value in select statement and i have one where condition at the end. if anybody has idea Please Help on this. thank you

**Comment by drbyte** [comment]
I don't understand. Why is the `area_code` related to roles and permissions?

**Comment by satishnreddy999** [comment]
> I don't understand. Why is the `area_code` related to roles and permissions?

I am building a multi tenant kid of feature where i have few areas, there one user may be admin in one area and admin also in other area or admin in one area and clerk in other area. for this i need to check model_id, role_id , area_id combination

**Comment by satishnreddy999** [comment]
> > I don't understand. Why is the `area_code` related to roles and permissions?
> 
> I am building a multi tenant kid of feature where i have few areas, there one user may be admin in one area and admin also in other area or admin in one area and clerk in other area. for this i need to check model_id, role_id , area_id combination

so far i managed to build query using global scope by extending roles model
select `roles`.*, `model_has_roles`.`area_id` as `community_id`, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` in (2) and `model_has_roles`.`model_type` = 'App\User' and `model_has_roles`.`area_id` = 6
But, still i am getting error "Column not found: 1054 Unknown column 'model_has_roles.area_id' in 'field list'
