### ISSUE TITLE
Permissions returning a result of null instead of false?

### ISSUE THREAD

**Issue by ryanmortier** [spatie/laravel-permission#1069]
First off, thanks for this amazing package. I've generally been using it issue free for other projects. However, I'm working on a larger application now and noticed that any permissions I setup seem to be returning a `null` result rather than `false` and I was wondering perhaps I'm doing something wrong?

First I setup a migration and migrated it:

```php
app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

$view_accounts = Permission::create(['name' => 'view accounts']);

Role::create(['name' => 'Account Manager'])->syncPermissions([
    $view_accounts,
]);
```

Then in my `AuthServiceProvider` class I have this:

```php
Gate::define('list accounts', function (User $user, Territory $territory) {
    if ($territory->name === 'Head Office') {
        return $user->can('view accounts')
            && $user->territories->contains($territory);
    }

    return $user->can('view accounts');
});
```

Now when I try to access a route protected by the `list accounts` gate from a user that doesn't have the `view accounts` permission, I see in my Laravel Debugbar:

```php
error array:4 [▼
  "ability" => "view accounts"
  "result" => null
  "user" => 1022
  "arguments" => "[]"
]
```

The permission appears to be working as I'm denied access to the route but I'm assuming it's because no value of `true` was returned so I'm wondering if the permission still isn't functioning correctly? Shouldn't this gate return a result of `false` instead of `null`?

Also if I `dd(Gate::abilities());` only the `list accounts` ability is defined. The `view accounts` permission appears to be missing?

Edit: I should note that if I view that same route from a user that has the `view accounts` permission via the `Account Manager` role, it returns true:

```php
success array:4 [▼
  "ability" => "view accounts"
  "result" => true
  "user" => 1
  "arguments" => "[]"
]
```

**Comment by drbyte** [comment]
All of those (ie: `can()` results) are coming back from the Gate, not from this package. This package simply registers permissions to the Gate. And then the Gate does the responding.

You'll need to debug your Gate::define closure.

**Comment by ryanmortier** [comment]
What if I'm using `$user->can('view accounts')` somewhere else that isn't in a Gate? It still returns `null`. How can I determine if the permissions are correctly being registered?

**Comment by drbyte** [comment]
> Question, shouldn't `dd(Gate::abilities());` still show the permissions as abilities since they're registered as a Gate?

Yes, but only if the permission is valid for that user at that time. Maybe the fact that it's not showing is a clue to the root problem you're encountering?

(Aside: is it possible that you've got multiple guards mixed up in here? or are you just using a single guard in your app?)

**Comment by ryanmortier** [comment]
I'm only using web guard.

I set up a brand new Laravel install and `dd(Gate::abilities());` is still not showing the permissions.

Repo: https://github.com/ryanmortier/permission-testing

**Comment by amineameur** [comment]
SQLSTATE[HY093]: Invalid parameter number (SQL: select `roles`.*, `user_role`.`user_id` as `pivot_user_id`, `user_role`.`role_id` as `pivot_role_id` from `roles` inner join `user_role` on `roles`.`id` = `user_role`.`role_id` where `user_role`.`user_id` = 1 and `name` = ? limit 1)
when i delete permission from role i got this error please help

**Comment by Mohmdthabet** [comment]
I Should return null, see this according to the docs:
https://docs.spatie.be/laravel-permission/v3/basic-usage/super-admin/#gate-before

Gate::before

If you want a “Super Admin” role to respond true to all permissions, without needing to assign all those permissions to a role, you can use Laravel’s Gate::before() method. For example:
```

use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->registerPolicies();

        // Implicitly grant "Super Admin" role all permissions
        // This works in the app by using gate-related functions like auth()->user->can() and @can()
        Gate::before(function ($user, $ability) {
            return $user->hasRole('Super Admin') ? true : null;
        });
    }
}
```

NOTE: Gate::before rules need to return null rather than false, else it will interfere with normal policy operation. See more.
