### ISSUE TITLE
Middleware 4th param error?

### ISSUE THREAD

**Issue by kirgy** [spatie/laravel-permission#107]
I'm trying to use the roles in middleware on Laravel 5.2, but I'm getting this error I'm not sure how to solve. I've recently removed the bican/roles vendor from my project in preference of this one.

```
// routes.php
Route::group(['middleware' => ['role:admin']], function () {
	Route::get('/account', 'AccountController@index');
});
```

Error being thrown:
> ErrorException in RoleMiddleware.php line 16:
> Missing argument 4 for App\Http\Middleware\RoleMiddleware::handle()

I have my middleware set-up and registered in my $routeMiddleware on kernal.php after running the artisan make command which has out the file there.

Am I missing something? Or is this a bug?

**Comment by sebastiandedeyne** [comment]
Could you post the method signature of `RoleMiddleware::handle`? Since you're only passing in one parameter (`role`), it should be something like `public function handle($request, Closure $next, $role)`.

**Comment by kirgy** [comment]
There is another parameter. Removing that solves the problem but creates another:

`Class 'App\Http\Middleware\Auth' not found`

I am thinking I've missed something... also, some functions in that class rely on that parameter.

Here is the whole class:

```
// RoleMiddleware.php

namespace App\Http\Middleware;

use Closure;

class RoleMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next, $role, $permission)
    {
        if (Auth::guest()) {
            return redirect($urlOfYourLoginPage);
        }

        if (! $request->user()->hasRole($role)) {
           abort(403);
        }

        if (! $request->user()->can($permission)) {
           abort(403);
        }

        return $next($request);
    }
}

```

**Comment by sebastiandedeyne** [comment]
In your route declaration, you're only passing one extra parameter (role):

```
'role:admin'
```

If you're middleware requires two parameters they both need to get passed, for example:

```
'role:admin,doStuff'
```

Where `doStuff` will be the value of permission.

Alternatively, if permissions aren't always necessary, you could make the parameter nullable:

```
public function handle($request, Closure $next, $role, $permission = null)
{
    // ...
}
```

**Comment by kirgy** [comment]
Thanks for your help @sebastiandedeyne.

I see, so I've nulled the permissions parameter which seems to solve these issues. The only issue now is use of the Auth class:

> FatalErrorException in RoleMiddleware.php line 18:
> Class 'App\Http\Middleware\Auth' not found

Including the Auth fascade or directly referencing in the namespace via either:
```
use Auth;
// or
use Illuminate\Support\Facades\Auth

```

throws this:

> HttpException in Application.php line 905:
Which is part of the "getSttyColumns()" function in that file. I'm baffled now.

**Comment by sebastiandedeyne** [comment]
Hmm `use Auth;` should do te trick.

Isn't the `HttpException` caused by `abort`?

**Comment by kirgy** [comment]
Ah yes, where I was going wrong is I never set a catch around the permissions as I don't want to always parse permissions to the middleware. This was the cause of all my woes!

Would be nice to have this as a feature in the package:

```
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next, $role, $permission = null)
    {
        if (Auth::guest()) {
            return redirect($urlOfYourLoginPage);
        }

        if (! $request->user()->hasRole($role)) {
           abort(403);
        }

        if($permission != null) {
            if (! $request->user()->can($permission)) {
               abort(403);
            }
        }

        return $next($request);
    }
```

**Comment by kirgy** [comment]
I'm revisiting this error some days on now I also need to check for "permissions" explicitly in routing middleware.

I've attached permissions to roles, and want to check that someone who's role has the permission "manage-enrolement" can access the route. The user must also be a staff member. The routing is as follows:

```
Route::group(['middleware' => ['role:staff', 'can:manage-enrolement']], function () {
	Route::get('/people', 'PeopleController@index');
});
```

However, Autorize.php returns "This action is unauthorized." The "RoleMiddleware.php" file does get called, but the 4th parameter is never parsed for the permissions.

Any idea what could be wrong here?

**Comment by kirgy** [comment]
Thanks @sebastiandedeyne , a syntax difference from the other permissions provider I had used seemed to have tripped me up here. Working perfectly. Thanks 👍
