### ISSUE TITLE
PermissionAlreadyExists with multitenancy

### ISSUE THREAD

**Issue by adminfriso** [spatie/laravel-permission#1071]
When connecting to a new and clean tenant, and try to seed it, it will give a PermissionAlreadyExists error. however the specific tenant it uses is empty. there is literally no data in it. In the seeders i try to forget all caches etc. Could there be something else I am doing wrong?

Console
```bash
Seeding: RolesAndPermissionsSeeder

In PermissionAlreadyExists.php line 11:
                                                            
  A `Guard App` permission already exists for guard `web`.  
```

Migration

```php
       // Reset cached roles and permissions
        app()['cache']->forget('spatie.permission.cache');
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // Permissions
        Permission::create(['name' => 'Guard App']);
```

Context command
```php
 config(['database.connections.' . $tenant['database'] . '.driver' => 'mysql']);
            config(['database.connections.' . $tenant['database'] . '.host' => config('database.connections.mysql_default.host')]);
            config(['database.connections.' . $tenant['database'] . '.port' => config('database.connections.mysql_default.port')]);
            config(['database.connections.' . $tenant['database'] . '.database' => $tenant['database']]);
            config(['database.connections.' . $tenant['database'] . '.username' => $tenant['username']]);
            config(['database.connections.' . $tenant['database'] . '.password' => secret;) ]);

if ($seed) {
                $this->call('db:seed', ['--class' => 'TenantSeeder', '--database' => $tenant['database']]);
            }
```

PS: **I LOVE YOUR PACKAGES**!!!!

**Comment by drbyte** [comment]
Hmmm ... first thing coming to mind is whether the db:seed call is properly connecting to the right database.

I know this package is agnostic about which db connection it's using ... as in, it just uses the primary/default connection. So maybe that's not actually "agnostic", but rather highly opinionated as in "unconfigurable". :)

You might need to override the models and set your own $connection property in them, as hinted at in the comments on this old non-merged PR: https://github.com/spatie/laravel-permission/pull/719

Aside: Unfortunately I'm going to be AFK for the rest of the week and unable to look at related code until then. But maybe the above gives you something to explore in the meantime. I'd like to see what you discover.

**Comment by adminfriso** [comment]
turned out it was a caching issue. The package works with only 1 cache, which initialises before the middleware initialises where the multitenancy switching is found.

current FIX:
give the cache a prefix bases on db name+default from package after switching to the tenants.

**Comment by drbyte** [comment]
Thanks for posting back with the details of the cause, and a solution!
