### ISSUE TITLE
Auditing model changes with owen-it/laravel-auditing

### ISSUE THREAD

**Issue by eleftrik** [spatie/laravel-permission#1072]
First of all, thanks for this wonderful package!

I'm using https://github.com/owen-it/laravel-auditing to audit/log model changes.
A model, to become "audited", must use a trait and implement an interface, both provided by that package.

No problems to audit `Permission` and `Role`: I defined my own models, extending `\Spatie\Permission\Models\Permission` and `\Spatie\Permission\Models\Role`.

But, for example, how can I audit changes on `model_has_roles` table? There is no model class to extend.
Is there any event or workaround I can rely on?
I need to log which roles are assigned (or removed) to which users.

Thank you

**Comment by drbyte** [comment]
The `model_has_roles` table is a pivot table used by Laravel's polymorphic relations.
Your auditing package will need to offer instructions for you to use it with polymorphism.

**Comment by eleftrik** [comment]
@drbyte Thanks for your reply. `owen-it/laravel-auditing` package relies on Eloquent events so, unless an event is fired when `spatie/laravel-permission` updates `model_has_roles` table, I don't know if there is a way for the auditing package to know what's happening.

I saw in the code that polymorphic relations are used, Is there a way to attach an event, for example, when this happens?

`$this->roles()->sync($roles, false);`

Thank you

**Comment by drbyte** [comment]
If I'm understanding you correctly, you may find this package useful:
https://github.com/fico7489/laravel-pivot

Or, if you're using Laravel 5.8+ you may find this useful: 
https://github.com/laravel/framework/pull/27571

**Comment by securit** [comment]
Surely the easiest way to provide this functionality would be to create a small number of [events](https://laravel.com/docs/5.8/events) raised when roles or permissions are added or deleted which the coder could hook into to perform whatever additional actions they require?

**Comment by eleftrik** [comment]
Thanks to everyone for the support.
Anyway, I solved by replacing _owen-it/laravel-auditing_ with https://gitlab.com/altek/accountant, which supports pivot relations out of the box.

**Comment by trulygowtham** [comment]
@eleftrik  Mine also the same requirement, Can you tell me how you implemented with https://gitlab.com/altek/accountant package please?

**Comment by eleftrik** [comment]
> @eleftrik Mine also the same requirement, Can you tell me how you implemented with https://gitlab.com/altek/accountant package please?

Sorry for the late answer. 
Basically, all my models (for whom I want to audit updates) implements Altek\Accountant\Contracts\Recordable interface and use Altek\Accountant\Recordable trait.
All record modifications are logged to a database table, which you can customize. The documentation is pretty clear.

**Comment by trulygowtham** [comment]
Thanks @eleftrik , For the response.
