### ISSUE TITLE
Identifier is too long when migrating

### ISSUE THREAD

**Issue by cyberfly** [spatie/laravel-permission#1073]
Hi i am facing identifier is too long when migrating on production server (oracle)

![spatie2](https://user-images.githubusercontent.com/1756170/55224172-e7b58000-524a-11e9-83bd-a8be6844bd65.png)

Upon looking at the migration, is it safe if I just rename this line? 

![spatie3](https://user-images.githubusercontent.com/1756170/55224305-2fd4a280-524b-11e9-84bc-816b48545590.png)

Is there any extra steps that need to be done? Thanks

**Comment by hamidafghan** [comment]
I just find this through the Oracle docs
Oracle docs note this about ORA-00972:

```ORA-00972: identifier is too long ```
Cause: ```An identifier with more than 30 characters was specified.```
Action:``` Specify at most 30 characters.```
Many users find themselves encountering ORA-00972 when attempting to access a table that has a large column length. 

Furthermore, ```ORA-00972``` can be caused by column, alias, or table names which are too long.

**Comment by drbyte** [comment]
I'm guessing you're using an older Oracle version?
In Oracle 12.2 they relaxed the 30-char limit to 128-bytes:
https://oracle-base.com/articles/12c/long-identifiers-12cr2

As a workaround, until you can upgrade your database version, you can edit the migration and specify a shorter name for the constraint.
