### ISSUE TITLE
Clone database and permissions not recognize

### ISSUE THREAD

**Issue by jhosepharaujo** [spatie/laravel-permission#1074]
I performed a dump of the database and the @can ('permission: any_permission') method does not recognize the registered permissions. I need to add again via application. Nor adding the permission and relating to model by the database is working. Has anyone ever experienced this?

**Comment by hamidafghan** [comment]
Check if there you have registered the ``` any_permission ``` middleware.

**Comment by drbyte** [comment]
Also, since "performed a dump of the database" suggests you're resetting or relocating the database and app, perhaps your cache also needs clearing?

**Comment by jhosepharaujo** [comment]
> Check if there you have registered the `any_permission` middleware.

Registered my permission in middleware? I add 'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class, in Kernel.php file. It is?

**Comment by jhosepharaujo** [comment]
> Also, since "performed a dump of the database" suggests you're resetting or relocating the database and app, perhaps your cache also needs clearing?

So I'm developing locally and need to deploy the application on the server. I made the design clone on another computer and identified the problem. So, I just generated the database script and imported it on the other PC, everything worked, except the permissions. Only works if I re-cast. I'm sorry for my English.

**Comment by drbyte** [comment]
>Only works if I re-cast. 

What do you mean by `re-cast`? Please show me your code.

**Comment by jhosepharaujo** [comment]
> > Only works if I re-cast.
> 
> What do you mean by `re-cast`? Please show me your code.

I need to register the permission again in the database.

My blade file
`@can('Gerenciar Indicadores')
<li class="{{ Request::is('indicadors*') ? 'active' : '' }}">
    <a href="{!! route('indicadors.index') !!}"><i class="fa fa-bar-chart"></i><span>Indicadores</span></a>
</li>
@endcan`

My UserController file
` public function update(User $user, Request $request)
    {
        $permissions = $request->only(['permissions']);
        $user->syncPermissions($permissions);

        Flash::success('Usuário atualizado com sucesso.');

        return redirect()->route('users.index');
    }`
My PermissionController file
` public function store(Request $request)
    {
        $input = $request->all();

        $permission = Permission::create($input);

        Flash::success('Permissão adicionada com sucesso.');

        return redirect(route('permissions.index'));
    }`

**Comment by drbyte** [comment]
> So I'm developing locally and need to deploy the application on the server. I made the design clone on another computer and identified the problem. So, I just generated the database script and imported it on the other PC, everything worked, except the permissions.

When "deploying" or copying to another PC, you need to ensure:
- all the database tables are copied over
- the cache on the destination PC is cleared, so that it doesn't "remember" old data

And, when symptoms suggest there is a problem, you should check the database on the destination PC to inspect whether the data was copied correctly.  If the data is present in the database, but the application is not displaying it properly, then you probably have a cache problem.

**Comment by jhosepharaujo** [comment]
If the problem is the application cache, how to solve it?

**Comment by drbyte** [comment]
> If the problem is the application cache, how to solve it?

The cache is explained further at: 
https://github.com/spatie/laravel-permission#cache

Normally clearing it with the artisan command is enough:
php artisan permission:cache-reset

If you need to do a complete cache reset for your Laravel application, there's an artisan command for that too. 
https://laravel.com/docs/5.8/cache

**Comment by jhosepharaujo** [comment]
The problem was the cache. Solved here! Thank you guys!
