### ISSUE TITLE
Only using HasPermissions trait will result in undefined method "hasRole"

### ISSUE THREAD

**Issue by FrittenKeeZ** [spatie/laravel-permission#1075]
If you only want to use permissions for a model, and thus use `HasPermissions` instead of `HasRoles`, you'll get an undefined method `hasRole` when checking permissions.

Is it possible to detach `HasPermissions` completely from calling any `HasRoles` methods?

Currently I circumvent this by adding a stub `hasRole` method returning `false`:
```php
/**
 * Determine if the model has (one of) the given role(s).
 *
 * @param string|int|array|\Spatie\Permission\Contracts\Role|\Illuminate\Support\Collection $roles
 *
 * @return bool
 */
public function hasRole($roles): bool
{
    return false;
}
```

**Comment by drbyte** [comment]
@FrittenKeeZ wrote:
> Is it possible to detach `HasPermissions` completely from calling any `HasRoles` methods?
> 
> Currently I circumvent this by adding a stub `hasRole` method returning `false`:

At the present time the package doesn't offer complete detachment from any `HasRoles` methods. Overriding must be done within your own app.
