### ISSUE TITLE
Trait method bootHasPermissions has not been applied because there are collisions

### ISSUE THREAD

**Issue by mstnorris** [spatie/laravel-permission#1076]
Laravel 5.8.8
spatie/laravel-permission: 2.36.1

When adding both the `HasRoles` and `HasPermissions` traits to my `User` model I get the following exception.

> Trait method bootHasPermissions has not been applied, because there are collisions with other trait methods on App\User

Am I using the package incorrectly? I thought I would be able to assign Roles to a User, as well as setting Permissions directly (without the need for a Role).

**Comment by akemys** [comment]
how did you solve it?

**Comment by mstnorris** [comment]
I updated the issue as above:

> I missed that the HasRoles trait already uses the HasPermissions trait so I didn't need to explicitly use it again.

You don't need to use both `HasRoles` and `HasPermissions` at the same time as `HasRoles` already includes the `HasPermissions` trait. You use one or the other.

**Comment by OmathiasO** [comment]
Thanks for the issue, I just stumbled across this and it helped me save some time!

Cheers :-)
