### ISSUE TITLE
belongsToMany error in laravel spatie permission?

### ISSUE THREAD

**Issue by worstn8mare** [spatie/laravel-permission#1078]
My code is working 1 year ago, but now i got an error when i update my composer. I used laravel package from laravel-spatie.

"spatie/laravel-permission": from 1.16.1 updated to 1.3.0,

laravel version : laravel 5.2

```
FatalThrowableError in BelongsToMany.php line 599:
Type error: Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::save() 
must be an instance of Illuminate\Database\Eloquent\Model, array given, called in 
/var/www/html/mto-erp/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php on line 18
```

**Controller**
```

$user = User::where('partner_id',$id)->first();
$permission = Permission::where('name','LIKE','accounting_%')->select('name')->get();
$permission = $permission->pluck('name')->toArray();
$user->revokePermissionTo($permission);
if(Input::get('permissions')){
   $user->givePermissionTo(Input::get('permissions'));
}
```

**Comment by drbyte** [comment]
> My code is working 1 year ago, but now i got an error when i update my composer.
> 
> "spatie/laravel-permission": from 1.16.1 updated to 1.3.0,
> 
> laravel version : laravel 5.2

I'm confused. Why did you "update" from newer 1.16.1 to older 1.3.0, after your app is working for a year? That's not an upgrade. It's a "downgrade". Why downgrade after a year?

That said, I created a new Laravel 5.2 app, and can confirm that you will need to use at least `1.5.0` to avoid that error.
But it would be better to use the latest `1.*` version until you're ready to use the new branch.
