### ISSUE TITLE
Why $guarded is a public function ?

### ISSUE THREAD

**Issue by RERE110** [spatie/laravel-permission#1080]
Hello,
I am a fan of your package. I just created custom models that are extended from your models.
I have a question.
Why your $guarded function is in public rather than protected

**Comment by drbyte** [comment]
Hmmm ... it was originally done that way here: https://github.com/spatie/laravel-permission/commit/d24e84de0210fa3abac2dcba0e5560546d8bc62d

**Comment by freekmurze** [comment]
I blame it on inexperience at the time 😄 This can perfectly be `protected`.

**Comment by drbyte** [comment]
@RERE110 Would you like to submit a PR for this?

**Comment by RERE110** [comment]
@drbyte Yes, if you can do a PR, it would be easier.
I am a bit annoying, but good;)
