### ISSUE TITLE
@role blade directive issue

### ISSUE THREAD

**Issue by elodiecmpn16** [spatie/laravel-permission#1081]
Hi! my problem is that the blade directives @role @hasrole @hasanyrole @hasallroles doesn't work (@can @if etc. are working well), i tried to look into the closed requests but all seems ok, cache, view cache etc. nothing seems to fix my problem...
someone can help me understand what's wrong? thank you! (a french newbie)  
```

 "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "^5.4.0",
        "spatie/laravel-permission": "^2.5.3"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    }
```,

**Comment by drbyte** [comment]
When you run `composer show`, what version of `spatie/laravel-permission` is installed?

I have a demo repository where `@hasrole` works correctly: https://github.com/drbyte/spatie-permissions-demo/blob/master/resources/views/permissions-demo.blade.php 
Perhaps something in your app is conflicting with the proper execution of those directives?

**Comment by elodiecmpn16** [comment]
Hi! thanks for replying! i have spatie/laravel-permission 2.37.0 version. I had used your demo to begin my project which help me a lot! thanks for that!

**Comment by elodiecmpn16** [comment]
sorry but why did you closed this issue?? still going on...

**Comment by drbyte** [comment]
Sorry, I misinterpreted your reply as meaning you had resolved it.

Please post a link to a public repository of your app code for inspection.

**Comment by elodiecmpn16** [comment]
https://github.com/elodiecmpn16/extranet.fr

**Comment by drbyte** [comment]
See https://github.com/elodiecmpn16/extranet.fr/pull/1

While I had to fix several migrations due to mismatched dependencies, and make a few other adjustments for the app to work, simply changing the view to use the `@hasrole` (or `@role`) works properly.
