### ISSUE TITLE
Always use guard "web"

### ISSUE THREAD

**Issue by annethereshewent** [spatie/laravel-permission#1082]
So is there any way to *always* use the web guard for all permissions and roles and routes?

I don't want to differentiate between api or web. I just want to use the web guard for everything, even when using api routes. (All my routes are api routes so it doesn't matter.)

**Comment by drbyte** [comment]
Current options:
a. Define only 1 guard in your `config/auth.php` file. Then the package will always only use that one.
b. If you have only 1 kind of User model (and therefore don't need the polymorphism support), you could use v1 of this package, since it ignores guards.

**Comment by annethereshewent** [comment]
Ok, that seems to have fixed this issue. I'm currently having another issue where Laravel's ->can() method doesn't work but ->hasPermissionTo() does. I'll close this and open a new bug report
