### ISSUE TITLE
 Problem 1 - Installation request for caffeinated/shinobi ^3.3 

### ISSUE THREAD

**Issue by jarayabozo** [spatie/laravel-permission#1084]
When trying to install I get the following error

Problem 1
    - Installation request for caffeinated/shinobi ^3.3 -> satisfiable by caffeinated/shinobi[v3.3].
    - Conclusion: remove laravel/framework v5.8.11
    - Conclusion: don't install laravel/framework v5.8.11
    - caffeinated/shinobi v3.3 requires illuminate/config 5.3.*|5.4.*|5.5.*|5.6.*|5.7.* -> satisfiable by illuminate/config[5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - don't install illuminate/config 5.3.x-dev|don't install laravel/framework v5.8.11
    - don't install illuminate/config 5.4.x-dev|don't install laravel/framework v5.8.11
    - don't install illuminate/config 5.5.x-dev|don't install laravel/framework v5.8.11
    - don't install illuminate/config 5.6.x-dev|don't install laravel/framework v5.8.11
    - don't install illuminate/config 5.7.x-dev|don't install laravel/framework v5.8.11
    - Installation request for laravel/framework (locked at v5.8.11, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.11].

php artisan --version                                                                                                                                                               
Laravel Framework 5.8.11

Please forgive me, I am quite new to Laravel so I don't know a lot about it yet.

**Comment by drbyte** [comment]
Hi,
It looks like you have some version conflicts with the package you're trying to install: `caffeinated/shinobi`.
But, you've posted in the spatie/laravel-permission package support area, which is completely different. I suggest you post in the shinobi support area.
