### ISSUE TITLE
it is possible to use it with apis?

### ISSUE THREAD

**Issue by Pablohack** [spatie/laravel-permission#1085]
I want to implement the roles and permissions but for apis, how to use the package is the same or does it have another consideration?

**Comment by drbyte** [comment]
The only consideration you might want to investigate is removing the `web` guard in your `config/auth.php` file, or at least pushing `api` up as the first one in the array, and making it default.

**Comment by Atiladanvi** [comment]
Please reopen this issue. I am try get an way to provides protection in api routes but i cannot configure the application for this because the package not know the api:auth from driver laravel/passport

**Comment by thilook** [comment]
Hello @Atiladanvi. I was able to use Passport and use laravel-permissions middleware. 
The only thing I needed to do was to change the default guard in config/auth.php

` 'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],`

After that I was able to access middlewares like this:

`
Route::group(['middleware' => ['role:Admin']],function () {
               Route::resource('permissions', 'PermissionAPIController');
});

`

I hope it helps.
