### ISSUE TITLE
Can this be implemented in a service driven pattern ? 

### ISSUE THREAD

**Issue by ronlinet** [spatie/laravel-permission#1086]
I am trying to implement this in a service layer but there are random issue with `\Auth::user() ` calls. More precisely I am getting the `Call to member function on null` errors on` \Auth::user()->getRoleNames()` . 
I have checked your documentation I haven't seen any service driven show cases. 
Is this supposed to work in such a context? 
What would be the best approach to handle the roles in a central class instead of spreading the busyness logic in controllers and blade conditions?  
I am using laravel 5.6

**Comment by drbyte** [comment]
> More precisely I am getting the `Call to member function on null` errors on 
` \Auth::user()->getRoleNames()`

When `Auth::user()` returns null it's usually because you're firing it before said user is determined by your app. Most commonly this is when it's being asked for in middleware that's firing too early in the priority flow. What about your app is making this check before the user is known?

**Comment by ronlinet** [comment]
This is because middleware is being loaded before user session.   The confusion is around since the release 5.3. 
To sort this out is advised to define a Closure based middleware directly in the controller => https://laravel.com/docs/5.3/upgrade#5.3-session-in-constructors.
It is confusing for somebody who expect to identify a user during the creation of an object.
This is because middlware is being loaded before user session.   
The confusion is around since the release 5.3. 
To sort this out is advised to define a Closure based middleware directly in the controller => https://laravel.com/docs/5.3/upgrade#5.3-session-in-constructors.
It is confusing for somebody who expect to identify a user during the creationg of an object.
It has not much to do with your package guys.  
Thank you for your time.
