### ISSUE TITLE
Role::where('column','value) return Illuminate\Database\Eloquent\Builder instead of Spatie\Permission\Models\Role

### ISSUE THREAD

**Issue by serak** [spatie/laravel-permission#1087]
use Spatie\Permission\Models\Role;

$role = Role::where('name','MyRole');

 $role->revokePermissionTo(Permission::all()); 

Error:
  Call to undefined method Illuminate\Database\Query\Builder::revokePermissionTo()

Reason:
  $role  is not Spatie\Permission\Models\Role Object

**Comment by drbyte** [comment]
That's normal, because `Role::where()` is invoking a query.
In Laravel if you want to execute the query and retrieve the Model, add `->first()` or `->get()` to the end of your query.
