### ISSUE TITLE
undefined method Illuminate\Database\Query\Builder::hasAnyRole

### ISSUE THREAD

**Issue by mhelal22** [spatie/laravel-permission#1089]
working on server successfully but didnt work on local and have error 
Call to undefined method Illuminate\Database\Query\Builder::hasAnyRole()

**Comment by drbyte** [comment]
Your error is talking about a QueryBuilder response, which means you haven't retrieved the user Object before running hasAnyRole against it. You probably need to add `->get()` to your app code before adding the hasAnyRole request.
