### ISSUE TITLE
Permissions table is not returning data

### ISSUE THREAD

**Issue by maliksajid** [spatie/laravel-permission#1092]
Hey, Hope you're doing well.

I tried many times to retrieve all the records of the permissions table by using the query builder and eloquent. But in both cases, the permission table returns an empty array.

I wanna display roles as shown in the snapshot.
![image](https://user-images.githubusercontent.com/32770676/57120525-7dcd5080-6d8b-11e9-9212-ca1ac0e759d3.png)

**So, how I can retrieve the records?**

**Comment by Langdi** [comment]
There is no magic involved here, `Permission::all()` should (and does for me) work perfectly fine.

**Comment by drbyte** [comment]
Yes, `Permission::all()` will return all the permission records.

**Comment by munawarAshlar17** [comment]
@drbyte I get empty array if I write this: 
               auth()->user()->getPermissionNames()
But if I write this, i get collection of permissions:
               auth()->user()->getAllPermissions()

why it is not returning permission names only?

**Comment by drbyte** [comment]
> @drbyte I get empty array if I write this:
> auth()->user()->getPermissionNames()
> But if I write this, i get collection of permissions:
> auth()->user()->getAllPermissions()
> 
> why it is not returning permission names only?

`getPermissionNames()` only returns direct permissions assigned to the user, not those inherited by associated roles.
However, `getAllPermissions()` goes and inspects the roles as well. So you could get the names from that by using `getAllPermissions()->pluck('name');`

**Comment by costpawa** [comment]
> > @drbyte I get empty array if I write this:
> > auth()->user()->getPermissionNames()
> > But if I write this, i get collection of permissions:
> > auth()->user()->getAllPermissions()
> > why it is not returning permission names only?
> 
> `getPermissionNames()` only returns direct permissions assigned to the user, not those inherited by associated roles.
> However, `getAllPermissions()` goes and inspects the roles as well. So you could get the names from that by using `getAllPermissions()->pluck('name');`

Thanks dude, you save my day
