### ISSUE TITLE
Enable Eager Loading Roles/Permissions

### ISSUE THREAD

**Issue by ragingdave** [spatie/laravel-permission#1094]
In attempting to call getAllPermissions on a model that has already eager loaded the roles and permissions, causes database queries because the getPermissionViaRoles isn't checking if the roles and roles.permissions are already loaded and calling the database regardless of eager loaded state.

a quick fix might be replacing the load call with loadMissing in getPermissionsViaRoles but I'm not sure if that's the right way to go with it. If it is I would gladly write up a PR with that fix, just wanted to see if there was a reason currently that isn't is place.

**Comment by drbyte** [comment]
I'd entertain a PR with tests showing that it solves the problem stated.

**Comment by NurdTurd** [comment]
👍 Just realized for showing comments with user roles as titles, I'm pulling around 15 queries per request. Oof!

**Comment by drbyte** [comment]
Hmmm ... awhile back I was working on a PR to remove some eager loading because it was doing unnecessary queries. Different spot perhaps, but dropping mention of it here for reference https://github.com/spatie/laravel-permission/pull/1056

**Comment by ragingdave** [comment]
In working the fix and tests, I found that it ends up breaking a test in the cache section, which I'm definitely not familiar with yet, so this PR might take a bit more time to complete. Just wanted to give an update. @NurdTurd, temporarily, if you just override the trait method then you can swap the load with loadMissing, but there may be dragons since the the caching could be affected.

**Comment by NurdTurd** [comment]
@ragingdave Thanks for the response, how would I go about changing the method? Do I have to modify vendor stuff? That feels a bit iffy.

**Comment by NessterGit** [comment]
While I understand the need for the eager loading, the loadMissing() behavior bit me in the arse. In case someone lands here from research, and you want to reset the roles and permissions for a new user check or the same user but different team (my use case), you can use 
```
$this->unsetRelation('roles') 
$this->unsetRelation('permissions') 
```
for example in your switchTeam() function before you do the actual team switch. 

Or override the getPermissionsViaRoles() function in your user model (replacing loadMissing() with load()). But this can cause a LOT more queries. Handle with care ;)

**Comment by drbyte** [comment]
@NessterGit what version of this package were you encountering that with?  Do you mind also testing against `v6.0-dev` because we applied some changes in #2412 which addresses relation loading, albeit not inside the getPermissionsViaRoles() method.

**Comment by NessterGit** [comment]
> @NessterGit what version of this package were you encountering that with? Do you mind also testing against `v6.0-dev` because we applied some changes in #2412 which addresses relation loading, albeit not inside the getPermissionsViaRoles() method.

5.10.2. Might give it a go next week but can't promise anything.

**Comment by drbyte** [comment]
@erikn69 any thoughts on this in regard to switching between teams?

**Comment by erikn69** [comment]
> you want to reset the roles and permissions for a new user check or the same user but different team (my use case), you can use
>$this->unsetRelation('roles') 
>$this->unsetRelation('permissions') 

https://github.com/spatie/laravel-permission/discussions/2136#discussioncomment-3129616
https://github.com/spatie/laravel-permission/discussions/1947#discussioncomment-1737773
https://github.com/spatie/laravel-permission/discussions/2100#discussioncomment-2790798
It's always been done that way, I don't think changing the version makes any difference

**Comment by mohamedds-12** [comment]
- #2803
