### ISSUE TITLE
Cache @can issue

### ISSUE THREAD

**Issue by mina-thomas** [spatie/laravel-permission#1096]
Thanks in advance,
Can I cache usage results for @can method?

Example:
@can('users.edit')

**Comment by drbyte** [comment]
`@can` is provided and operated by the Gate features in the Laravel core.
This package interacts with the Gate by providing lookups for defined permissions, whenever the Gate requests it. The permissions lookups by this package are already cached.

**Comment by mina-thomas** [comment]
Thanks
