### ISSUE TITLE
User Role Relation Table Not Found

### ISSUE THREAD

**Issue by keyboard8** [spatie/laravel-permission#1098]
I just installed the package in fresh laravel application but `php artisan migrate` didn't create the user-role relation table. and when i assign role to a user, nothing happen.

**Comment by drbyte** [comment]
I created a new Laravel application today and added this package and ran the migrations. I can see the necessary tables, and create roles, and assign roles to users.

For your situation, my first guess is that something went wrong when running the migration.
I suggest investigating your error logs (PHP and MySQL or whatever database you're using) for more information.
