### ISSUE TITLE
Is it possible for Roles and Permissions to be statically defined instead of database entries?

### ISSUE THREAD

**Issue by simensen** [spatie/laravel-permission#1099]
Rather than seeding the database, I'd like to define these things in memory. Best example I can think of would be how plans are defined in Spark:

```
Spark::plan('Pro', 'monthly-pro')
        ->price(20)
        ->features([
            'Feature 1',
            'Feature 2',
            'Feature 3',
        ]);
```

Is this possible?

**Comment by drbyte** [comment]
Hmmm ... not currently.

This package is fully geared around expecting Eloquent (active record) records, with polymorphic relations and caching. Moving that to statically defined would require rewiring most of the registrar and the models and a lot of the trait content.

I'm tempted to suggest that if your app only requires a very simple static array for a tiny set of permissions then maybe that belongs in userland code?
Granted, I can see the appeal of a package that's already implemented a bunch of accessor features. I'm not sure which is more work: extending or retrofitting this package vs recreating the necessary features directly in your own app.

**Comment by simensen** [comment]
@drbyte thanks. :)

**Comment by jaumesala** [comment]
I'm looking for the same, but only for permissions. In my case, permissions are "defined" by the features the app itself can do (what it is coded). Then users should only be able to manage (CRUD) groups of permissions , a.k.a. "roles", or assign direct permissions to users.
