### ISSUE TITLE
Feature: hasAnyRole and hasAllRoles

### ISSUE THREAD

**Issue by lowerends** [spatie/laravel-permission#11]
It would be useful to have methods to check whether a user has any of a list of roles or whether a user has all of a list of roles. 

If you agree with this, I can create a PR to add these methods.

**Comment by freekmurze** [comment]
Sounds good. Don't forget to add some tests and update the readme with some examples.

Thanks!

**Comment by lowerends** [comment]
I started working on this and should have something ready later this week.

**Comment by freekmurze** [comment]
:+1:
