### ISSUE TITLE
Possibility to add roles/permissions with same name

### ISSUE THREAD

**Issue by Saarik** [spatie/laravel-permission#110]
Hello again, 

I'd like to switch my current permissions package to this one, but it's missing one feature: the possibility to add roles/permissions with same name to different clients (every client can manage their roles and permissions separately).

Solution would be quite simple. Unique columns could be changed to be combinations of two columns, where the other column can be something like client ID (empty by default for compatibility). Probably some code changes are required too.

Would you accept a PR to this problem?

**Comment by freekmurze** [comment]
Hi,

I'd like to keep this package simple, so I'm not likely to merge such a PR in.

There are a few options you can try out. In the config file you can choose your own model that you could modify to your own needs. You can also edit the migration if you need some extra fields.

If that does not provide enough functionality, I suggest you just fork your package and maintain your own copy that can handle your specific requirements.

**Comment by mahouha** [comment]
@freekmurze and now there is a possibility to add roles/permissions with same name or not yet ??

**Comment by erikn69** [comment]
@mahouha there is teams feature now
