### ISSUE TITLE
Why is role_has_permissions a separate table?

### ISSUE THREAD

**Issue by sergiz** [spatie/laravel-permission#1102]
Hello.

Is there a specific reason why role's permissions are not saved in model_has_permissions table and require a dedicated table?

**Comment by drbyte** [comment]
A different design approach could put everything in one table, but then you'd have less flexibility on how you use the data.

As it is right now, you can use roles-only, or permissions-only, or the combination of both.

What problem is this creating for you?  Why do you find yourself wanting them in the other table?

**Comment by sergiz** [comment]
I am about to use this package and wanted to get to know it better first.

How come you wouldn't be able to use "roles-only, or permissions-only, or the combination of both", if role's permissions would be simply in model_has_permissions, like for every other model?

**Comment by drbyte** [comment]
Apologies - I didn't read your post as deeply as I ought.

You raise a good point. There might be room for an efficiency gain there. I haven't investigated that ... but it requires mapping out all the polymorphic relations happening there.

**Comment by sergiz** [comment]
Yeah, that I was thinking about. It seems to me that a separate table is redundant in this case, since model_has_permissions already includes everything we need to also store role's permissions.

I glanced over the implementation and it doesn't seem to be too hard to make a transition. I can look into it later and make a PR
