### ISSUE TITLE
Assign user's roles from another model's roles

### ISSUE THREAD

**Issue by thezahedi** [spatie/laravel-permission#1107]
Hi,
I have User and Group models and added HasRoles trait to both of them.
I want to assign roles to Groups and use group's assigned roles for Users.
Can anyone help me to do this?

**Comment by drbyte** [comment]
Question: in your app, how do groups differ from roles? Can you give examples?

**Comment by thezahedi** [comment]
I want to make an organization chart of a company.
In my app:
- Groups are organization units.
- Roles are Job titles.

I want to assign roles to groups and add users to groups and when I want to get roles of users, actually get the roles and permissions of the group that user in!

**Comment by thezahedi** [comment]
I solved this problem with an abstract concept in groups.

I just attach roles to groups model and when i want to get the user's roles, i get the group's roles that user in!
