### ISSUE TITLE
why index name so long that it cant be created

### ISSUE THREAD

**Issue by kisssg** [spatie/laravel-permission#1108]
Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access
 violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: a
lter table `model_has_permissions` add index `model_has_permissions_model_id_mod
el_type_index`(`model_id`, `model_type`))

**Comment by kisssg** [comment]
tableName_columnName1_columnName2_index

**Comment by drbyte** [comment]
The database you're using requires a configuration change in your app:
https://laravel-news.com/laravel-5-4-key-too-long-error
