### ISSUE TITLE
Global "Super Admin" role not working

### ISSUE THREAD

**Issue by nemeros111** [spatie/laravel-permission#1111]
I have changed the AuthServiceProvider follow the WIKI but Gate::before function not being called.

use Illuminate\Support\Facades\Gate;

    public function boot()
    {
        $this->registerPolicies();

        Gate::before(function ($user, $ability) {
            dd('Invoked GATE');
            return $user->hasRole('Super-Admin') ? true : null;
        });
        //
    }

Ps: Im using multiple Guards

Has anyone else experienced this problem?

**Comment by nemeros111** [comment]
Thank you,

**Comment by ali-syria** [comment]
I have the same problem, how to fix? @nemeros111

**Comment by nemeros111** [comment]
@ali-syria Just use **@can('permission_name')** for super-admin in your blade.
