### ISSUE TITLE
There is any plan to make prohibitive roles?

### ISSUE THREAD

**Issue by maxcelos** [spatie/laravel-permission#1114]
Example:
I have many roles (admin, intern, manager, editor, etc) with dozens of different permissions and some in common, like "post_publish". So, every one has permission to publish posts.

The problem is, not all managers should publish posts. They are still managers and do all other attributions staff, but, for some reason, cannot publish posts. Same for some editor and other roles.

Instead of create a variant of each role (manager_2, editor_2, etc) removing those unrequired permissions, I wish just create a global prohibitive role to overrride a given permission. Like "block_post_publish". Then apply this additional role to those people who cannot publish posts.

**Comment by drbyte** [comment]
No, this package focuses on being additive about roles/permissions.

You could, however, in your app, change your logic to something like `user can(publish) and does not haveRole(block_post_publish)`, as that would capture the business logic directly where it needs to be enforced. 
Even better, capture that in a policy applied to the model.

**Comment by maxcelos** [comment]
Understood. Thanks for replying.
