### ISSUE TITLE
Error: Non-static method App\User::role() should not be called statically

### ISSUE THREAD

**Issue by reasecret** [spatie/laravel-permission#1115]
I'm trying to get admins with this code:

`$admins = User::role('admin')->get();`

It should work but I'm getting error: `Non-static method App\User::role() should not be called statically`. What should I do?

**Comment by reasecret** [comment]
My mistake. Conflict with role function on user model...

**Comment by anas-chughtai** [comment]
Can you tell what kind of conflict was there in your user model. 
I'm also having same error.

**Comment by drbyte** [comment]
> Can you tell what kind of conflict was there in your user model.
> I'm also having same error.

Check your model to see what functions you've created there. Compare those with all the functions offered by the package traits. Anything in your model overrides the package traits and therefore breaks the package functionality. Same with properties which may clash with relation names.
