### ISSUE TITLE
How to add role to user in Seeder

### ISSUE THREAD

**Issue by arturplo** [spatie/laravel-permission#1116]
Hi, how to add role "Administrator" after create new user in UsersSeeder?
My insert user code:
`DB::table('users')->insert([
              'name' => 'John Doe',
              'email' => 'mail@example.com',
              'password' => bcrypt('password'),
              'created_at' => '2019-05-28 04:45:27',
              'updated_at' => '2019-05-28 04:45:27',
            ]);`

**Comment by drbyte** [comment]
Use Eloquent to retrieve the user, and then assign the role to them using assignRole() as you normally would.
https://github.com/spatie/laravel-permission#using-permissions-via-roles
https://github.com/spatie/laravel-permission#database-seeding

You may find it simpler to use Factories to have Eloquent create the user instead of using the DB facade, as that then also gives you the user object back, allowing you to assign roles afterward.

**Comment by arturplo** [comment]
`$user = User::create([ 'name' => 'John Doe', 'email' => 'mail@example.com', 'password' => bcrypt('password'), 'created_at' => '2019-05-28 04:45:27', 'updated_at' => '2019-05-28 04:45:27' ]);
$user->assignRole('Administrator');`
?

**Comment by drbyte** [comment]
Yes, that's one way.

**Comment by arturplo** [comment]
thanks :)

**Comment by Datalink-Wouter** [comment]
Sorry for waking up this issue.
If you want to create multiple users using a factory and then assign roles you can loop through all roles en inside the loop create the users using the factory.
Afterwards you can assign all those users to the role. You need 2 loops per role, but since this is just a seeder I don't think it's that bad.

An example seeder:

```php
public function run()
{
   foreach(Spatie\Permission\Models\Role::all() as $role) {
      $users = factory(User::class, 50)->create();
      foreach($users as $user){
         $user->assignRole($role);
      }
   }
}
```

**Comment by iBet7o** [comment]
Hello,

The following script creates users and I assign the role.

```php
factory(App\Merchant::class, 5)
    ->create()
    ->each(function ($merchant) {
        $user = factory(App\User::class)->make();
        $user->assignRole('Merchant Admin');

        $merchant->users()->save($user);
    });
```

**Comment by cwilby** [comment]
@iBet7o is there a way to reuse this logic in factories?  I'd like to have a factory state for each user role and just call `factory(App\User::class)->state('admin')->create();` etc.

**Comment by drbyte** [comment]
@cwilby I think you can do that with an `afterCreatingState` callback:
https://laravel.com/docs/master/database-testing#factory-callbacks

**Comment by drbyte** [comment]
eg: 
```php
$factory->state(App\User::class, 'active', function (Faker $faker) {
    return [
        'active' => true,
    ];
});

$factory->afterCreatingState(App\User::class, 'active', function ($user, $faker) {
    $user->assignRole('Member');
});
```

**Comment by rognales** [comment]
@drbyte i did as your example but unable to return anything when executing these codes in Tinker

```php
$u = factory('App\User')->state('product')->make();
$u->roles
````
```$u->roles``` simply return empty collection

This is the factory snippet

```php
$factory->state(User::class, 'product', [
    'status' => 'active' 
]);

$factory->afterMakingState(User::class, 'product', function ($user, $faker) {
    $user->assignRole('product');
});
````

**Comment by drbyte** [comment]
Yes, since the user must be persisted before roles can be assigned, you can only use this with after**Creating**State, not after**Making**State.

**Comment by merakinoya** [comment]
> If you want to create multiple users using a factory and then assign roles you can loop through all roles and inside the loop create the users using the factory.
> Afterwards you can assign all those users to the role.
> 
> An example seeder:
> 
> ```
> public function run()
> {
>    foreach(Spatie\Permission\Models\Role::all() as $role) {
>       $users = factory(User::class, 50)->create();
>       foreach($users as $user){
>          $user->assignRole($role);
>       }
>    }
> }
> ```
> 
> This will create 50 users for every role.

Just want to know, What the mean of `(User::class, 50)`  ?

**Comment by Datalink-Wouter** [comment]
> > If you want to create multiple users using a factory and then assign roles you can loop through all roles and inside the loop create the users using the factory.
> > Afterwards you can assign all those users to the role.
> > An example seeder:
> > ```
> > public function run()
> > {
> >    foreach(Spatie\Permission\Models\Role::all() as $role) {
> >       $users = factory(User::class, 50)->create();
> >       foreach($users as $user){
> >          $user->assignRole($role);
> >       }
> >    }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will create 50 users for every role.
> 
> Just want to know, What the mean of `(User::class, 50)` ?

It just creates 50 users

**Comment by mohsenmojadam2019** [comment]
last go 


<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;

class RolesAndPermissionsSeeder extends Seeder
{
    use  HasRoles;

    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // create permissions
        Permission::create(['name' => 'edit articles']);
        Permission::create(['name' => 'delete articles']);
        Permission::create(['name' => 'publish articles']);
        Permission::create(['name' => 'unpublish articles']);


        $role = Role::create(['name' => 'super-admin']);
        $role->givePermissionTo(Permission::all());

        // Assign roles to demo users
        $superadmin = User::where('id', 1)->get();

//        $superadmin->assignRole('super-admin');
$users=User::all();
        foreach($users as $user){
            $user->assignRole('super-admin');
        }
    }

}

**Comment by mohsenmojadam2019** [comment]
class RolesAndPermissionsSeeder extends Seeder
{
    use  HasRoles;

    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // create permissions
        Permission::create(['name' => 'edit articles']);
        Permission::create(['name' => 'delete articles']);
        Permission::create(['name' => 'publish articles']);
        Permission::create(['name' => 'unpublish articles']);


        $role = Role::create(['name' => 'super-admin']);
        $role->givePermissionTo(Permission::all());

        // Assign roles to demo users
        $superadmin = User::where('id', 1)->get();

//        $superadmin->assignRole('super-admin');
$users=User::all();
        foreach($users as $user){
            $user->assignRole('super-admin');
        }
    }

**Comment by mohsenmojadam2019** [comment]
<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Traits\HasRoles;

class RolesAndPermissionsSeeder extends Seeder
{
    use  HasRoles;

    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // create permissions
        Permission::create(['name' => 'edit articles']);
        Permission::create(['name' => 'delete articles']);
        Permission::create(['name' => 'publish articles']);
        Permission::create(['name' => 'unpublish articles']);


        $role = Role::create(['name' => 'super-admin']);
        $role->givePermissionTo(Permission::all());

        // Assign roles to demo users
        $superadmin = User::where('id', 1)->get();

//        $superadmin->assignRole('super-admin');
$users=User::all();
        foreach($users as $user){
            $user->assignRole('super-admin');
        }
    }

}

**Comment by mohsenmojadam2019** [comment]
class RolesAndPermissionsSeeder extends Seeder
{
    use  HasRoles;

    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // create permissions
        Permission::create(['name' => 'edit articles']);
        Permission::create(['name' => 'delete articles']);
        Permission::create(['name' => 'publish articles']);
        Permission::create(['name' => 'unpublish articles']);


        $role = Role::create(['name' => 'super-admin']);
        $role->givePermissionTo(Permission::all());

        // Assign roles to demo users
        $superadmin = User::where('id', 1)->get();

//        $superadmin->assignRole('super-admin');
$users=User::all();
        foreach($users as $user){
            $user->assignRole('super-admin');
        }
    }

**Comment by akbarhlubis** [comment]
I find another method, maybe this can be helpful

User::factory()->count(10)->create()->each(function ($user) {
    $user->assignRole('student');
});
