### ISSUE TITLE
Undefined variable : user

### ISSUE THREAD

**Issue by damarajati** [spatie/laravel-permission#1117]
$user->assignRole('writer');
// You can also assign multiple roles at once
$user->assignRole('writer', 'admin');
// or as an array
$user->assignRole(['writer', 'admin']);

error : undefined variable : user

what's wrong ??? help please
thankyou..

**Comment by drbyte** [comment]
In the README examples, `$user` refers to a basic Laravel user object you've retrieved using Eloquent.

Example: `$user = \App\User::where('email', 'test@example.com')->get();`

**Comment by damarajati** [comment]
thankyou..
