### ISSUE TITLE
Grant Permission for Guard

### ISSUE THREAD

**Issue by mauxbrewster** [spatie/laravel-permission#1118]
My application leverages both the `web` and `api` guard, I'd like to use both simultaneously. I'm currently building a permission management screen.

How would I go about assigning a permission to a user for a specific guard?

Ie. I can do `$user->givePermissionTo('do.something');`, I'd like to do `$user->givePermissionTo('do.something', 'web');` or something similar.

How can I achieve this?

**Comment by drbyte** [comment]
To assign a permission for a specific guard, first retrieve that permission ID, and then pass that ID to `givePermissionTo($permission_id)`

**Comment by drbyte** [comment]
To assign a permission for a specific guard, first retrieve that permission record object (using Eloquent `where` on `name` and `guard`), and then pass that object to `givePermissionTo($permission_object)`

**Comment by mauxbrewster** [comment]
Would be cleaner to have a method as I've described, but thank you!
