### ISSUE TITLE
@can blade directive is not working if specified permission is not associated to the user

### ISSUE THREAD

**Issue by ankitasoman** [spatie/laravel-permission#1119]
Hello there,

I am trying to apply permission on the menu but i am getting following error:

> Call to a member function getKey() on
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php
     ```
*/
    public function makeVisible($attributes)
    {
        return $this->each->makeVisible($attributes);
    }
 
    /**
     * Get a dictionary keyed by primary keys.
     *
     * @param  \ArrayAccess|array|null  $items
     * @return array
     */
    public function getDictionary($items = null)
    {
        $items = is_null($items) ? $this->items : $items;
 
        $dictionary = [];
 
        foreach ($items as $value) {
            $dictionary[$value->getKey()] = $value;
        }
 
        return $dictionary;
    }
 
```

please help me with the same ASAP

**Comment by ZaidBarghouthi** [comment]
Clarify please.

**Comment by ankitasoman** [comment]
For eg.
Lets say user1 has permission1 and user2 has permission2. In left sidebar when it is checked for every user, 
```
@can('permission1')
    //code
@endcan
```
it throws error
`Call to a member function getKey() on
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php
```
*/
public function makeVisible($attributes)
{
return $this->each->makeVisible($attributes);
}

/**
 * Get a dictionary keyed by primary keys.
 *
 * @param  \ArrayAccess|array|null  $items
 * @return array
 */
public function getDictionary($items = null)
{
    $items = is_null($items) ? $this->items : $items;

    $dictionary = [];

    foreach ($items as $value) {
        $dictionary[$value->getKey()] = $value;
    }

    return $dictionary;
}`

**Comment by drbyte** [comment]
The code you posted isn't related to this package.

It would seem you've got a problem in your app code. Maybe you need to be passing different $items that are actually objects that have a `getKey()` method defined on them?
