### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by joaorik** [spatie/laravel-permission#1120]
Hello,
Nice project 👍 

Is possible to do this:
Users with same role, but with different permissions?

Admin1: perm1, perm2, perm3
Admin2: perm2, perm4

Thank you

**Comment by ZaidBarghouthi** [comment]
Hi!

You can use [direct permissions](https://github.com/spatie/laravel-permission#using-direct-permissions-see-below-to-use-both-roles-and-permissions).

```php
$admin1->assignRole('admin'); // perm1, perm2,
$admin2->assignRole('admin'); // perm1, perm2,
$admin2->givePermissionTo('perm3'); // now admin2 has perm1, perm2, perm3;
```

**Comment by drbyte** [comment]
Yes, you can use roles to assign common permissions, and then specifically grant additional permissions per-user. (or additional roles for additional shared permissions)
