### ISSUE TITLE
Multilevel roles & permissions

### ISSUE THREAD

**Issue by christos312** [spatie/laravel-permission#1121]
Hello, I hope this is the right place to ask this question.

Is it possible with this package to assign multi level roles and permissions?

Suppose that I have many users in my system and each user might belong to multiple Projects.

Is it possible to say that User A has the role **Admin** on Project X, and role ### Member in Project X?

So in general to be able to assign roles per Project?

Project X
--> Admin
--> Member

Project Y
--> Admin
--> Member

**Comment by drbyte** [comment]
I'm not clear what exactly you mean by "Project" in this context. 

But here are some things to consider in case they answer your question:

Some posts about wildcard/cascading permissions include https://github.com/spatie/laravel-permission/issues/382#issuecomment-332627484 and #440 and #512

Other notes:
In a multidatabase-multitenant environment where each tenant has its own database, roles and permissions can be assigned to tenants independently of each other with a simple model override as demonstrated at https://laravel-tenancy.com/docs/hyn/5.4/spatie-laravel-permission

To do it in a single-database setup you'd need to do some other extending with schema changes and global scopes.

**Comment by christos312** [comment]
Thanks for the reply.

Maybe "Project" was a bad word. I mean to assign roles to different contexts, lets say

I have a system
A system has many courses
A course has many assignments

I want to be able to assign the role Admin and member to all 3 contexts independently. 

Thanks for the resources, I will study them now :) I think the answer is in there 👍
