### ISSUE TITLE
Cannot use blade directives with multiple guards

### ISSUE THREAD

**Issue by dimitriskkkk** [spatie/laravel-permission#1124]
What I am trying to make: 
` @role('business_admin', 'super_admin')`

I get the error: "Auth guard [super_admin] is not defined"

**Comment by drbyte** [comment]
The `@role` directive calls Laravel's `auth()` helper, like this:
https://github.com/spatie/laravel-permission/blob/81dbe9d372d70c255b66a2727a235076509f8d45/src/PermissionServiceProvider.php#L72-L76

And your error message is then triggered by this in Laravel:
https://github.com/laravel/framework/blob/9b7520a2ac0009d4c1ff2322e3ef673ef702e7e2/src/Illuminate/Auth/AuthManager.php#L81-L85

So, this all tells me that your `super_admin` guard doesn't exist in your app.

**Comment by dimitriskkkk** [comment]
Yes but, when I am using super_admin or business_admin role alone, it works just fine...
