### ISSUE TITLE
assignRole not working when try to assign role to the user

### ISSUE THREAD

**Issue by antweny** [spatie/laravel-permission#1125]
I created different some roles and users in my system now try to assign roles to users
like this 
```
$user->assignRole('end-user');
```
i end up getting the error below
```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`social`.`model_has_roles`, CONSTRAINT `model_has_roles_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE) (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (4, App\User, 25))
```

How can i fix this. I'm using laravel-permission v2.37

**Comment by drbyte** [comment]
Hi,

Help me recreate your problem. Assume I'm starting from a fresh Laravel app, by running the following:
```sh
laravel new permissions_test_app
cd permissions_test_app
git init
git add .
git commit -m "Fresh Laravel Install"

cp -n .env.example .env
sed -i '' 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env
sed -i '' 's/DB_DATABASE=laravel/#DB_DATABASE=laravel/' .env
touch database/database.sqlite

composer require spatie/laravel-permission
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider"
git add .
git commit -m "Add Spatie Laravel Permissions package"
php artisan migrate:fresh

#add basic auth framework, just for simplicity
php artisan make:auth

# Manually: add HasRoles trait to Users.php
```
Now, on top of this fresh new app, what exactly do I need to do to make your error happen in this app?
Obviously you'll need some migrations, some User code, some Controller code, etc. Please post all that is required.

**Comment by antweny** [comment]
I found that solution the original migration file does not has a relation with the user model.
So on model_has_roles schema i add the following code

```
 $table->foreign($columnNames['model_morph_key'])
                ->references('id')
                ->on('users')
                ->onDelete('cascade');
```

**Comment by drbyte** [comment]
We wouldn’t link directly to the Users table in the default migration because that would (essentially) force you to only use the User model. 
You are of course free to do that with your own app.

**Comment by antweny** [comment]
I have end_user role in my database so i want to assing it automatically every time when a new user register this is how i did it. 
```
 protected function create(array $data)
    {
        $user = $this->register($data);

        $user->assignRole('end-user');

        return $user;
    }
```
but i get this error

> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`social`.`model_has_roles`, CONSTRAINT `model_has_roles_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE) (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (a457ad7d-a957-4859-8469-b07dadfe2b48, App\User, 0))



but if i do this is working by assing a role to a user but only on the first run later throung duplicate error which i understand

```
protected function create(array $data)
    {
        $user = User::register($data);

        $role = Role::create(['name' => 'end_user']);
        $user->assignRole($role);

        return $user;
    }
```
i need help

**Comment by rakishii13** [comment]
I am getting the same error after upgrading to Laravel 5.8 and following to update to latest 2.37 for this package. When I try to assignRole to a user, I get the following error

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `et_model_has_roles` (`model_id`, `model_type`, `role_id`) values (?, App\User, 1))`

It seems as though the assignRole is not taking the id from the user Model and using it to store into model_id.
