### ISSUE TITLE
How do you generate the AppServiceProvider

### ISSUE THREAD

**Issue by BenjaminHoegh** [spatie/laravel-permission#1126]
How do you get this package to generate the AppServiceProvider.php so I can use `@role` in blade?

**Comment by drbyte** [comment]
This package [automatically registers the Blade @role directive](https://github.com/spatie/laravel-permission/blob/81dbe9d372d70c255b66a2727a235076509f8d45/src/PermissionServiceProvider.php#L58-L122) using Laravel's built-in [auto-discovery feature](https://github.com/spatie/laravel-permission/blob/81dbe9d372d70c255b66a2727a235076509f8d45/composer.json#L52-L58). 
You do not need to add anything to AppServiceProvider for this to happen ... unless you're using a very old Laravel version that doesn't support the auto-discovery feature.

If running `php artisan vendor:publish` lists this package, then the service provider has been registered and booted, which includes registering the Blade directives.

**Comment by aman00323** [comment]
@BenjaminHoegh as @drbyte said package has auto discovery. For laravel version >5.5 it is auto discover. Other wise you need to register facades as well aliases.

You can check below code of composer.json which made possible of laravel auto discovery support have look.

https://github.com/spatie/laravel-permission/blob/81dbe9d372d70c255b66a2727a235076509f8d45/composer.json#L55

By adding above lines laravel which support auto discovery it will automatically register AppServiceProvider.
