### ISSUE TITLE
SQLSTATE[HY000]: General error: 1366 Incorrect string value

### ISSUE THREAD

**Issue by GuilhermeMLS** [spatie/laravel-permission#1127]
When running my `PermissionSeeder`, I have the following error message:

```
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE3\xA1rio' for column 'alias' at row 1 (SQL: insert into permissions (name, alias, entity, entity_alias, description, guard_name, updated_at  
  , created_at) values (view_all_employee, ver todos os(as) funcion?rio, employee, Funcionário, Permite ver todos os(as) funcion?rio., web, 2019-06-14 09:48:31, 2019-06-14 09:48:31))`
```
It happens when the `PermissionSeeder` finds the first special character in the table seeder, in this case, it breaks at the `á` from the word `funcionário`.

<b>I've tried:</b>
<ul>
<li> Removing the word `funcionário`, but it breaks at the second special character it finds </li>
<li> verifying the encoding of the files involved, all set to UTF8 </li>
<li> verifying the database encoding and collation, all set to UTF8 too </li>
<li> inserting permissions through the `php artisan tinker` and through the MySQL command line, it works </li>
</ul>

PS.: the seeder works fine at my Linux Mint computer, the problem happens only in my macOS Mojave.

**Comment by drbyte** [comment]
I suspect there's something missing in your local environment configuration.

I just tried inserting `Funcionário` in a permission name on macOS Mojave, without issue. On both SQLite and MySQL.
