### ISSUE TITLE
protected $access explaination

### ISSUE THREAD

**Issue by team6-cn** [spatie/laravel-permission#1128]
Hello, can someone explain to me this situation below? I don't see any purpose of this

```
    protected $access = [
        'permissions' => 'list-users',
        'roles'       => 'user',
    ];
```

If auth user has a role of **user** and that role does not have permission to **list-user**, in this case, the request is approved. For me, that's not logic. 

If the user has role **user** and if that role does not have permission **list-user**, auth user should not be approved.

However, if auth user has **list-user** permission request should be approved.

Sorry if I'm wrong, but I need some explanation. 

Thanks.

**Comment by drbyte** [comment]
I'm not sure where you're seeing that code. 
It's not part of this package.
