### ISSUE TITLE
Retrieve List of Roles related to User using Spatie/laravel-fractal, Permissions works perfectly

### ISSUE THREAD

**Issue by medbooktim** [spatie/laravel-permission#1130]
Hi, I am fairly new to this however I am a fan of Spatie repos on laravel since 5.4.
I followed few discus on getting list of roles and permissions using user model eg. [Getting List of Users By Role or Permission](https://github.com/spatie/laravel-permission/issues/357) but none are speaking of my kind of concern.
How do I retrieve list of roles related to user using spatie/laravel-fractal through `"->parseIncludes(['roles', 'permissions'])->toArray()"`
It throws a `Symfony\Component\Debug\Exception\FatalThrowableError` when I try 
`public function includeRoles(User $user)
    {
        return $this->collection($user->roles, new RoleTransformer);
    }`
But permissions works perfectly when trying ` 'user' => fractal($user, new UserTransformer)->parseIncludes(['permissions'])->toArray()`
Please assist, working on an API project so organizing my data neatly to use on response()->json()

**Comment by drbyte** [comment]
With this package you can retrieve a user's Roles using: `$user->roles`. You can confirm that this works by using `dd()` with it. This will also let you see the format the resulting collection takes.

As far as how the Fractal package interprets that data, I'm sorry I have no experience with that package.

 Perhaps adding some code to inspect the data at various stages may give you clues to what step you're missing?
