### ISSUE TITLE
how to add category for permissions?

### ISSUE THREAD

**Issue by nekooee** [spatie/laravel-permission#1132]
My permissions are too high. And I need to add categories to permissions. So they can be more easily show in the "role edit" page and assigned to roles.
please guide me.
thanks.

**Comment by atymic** [comment]
You can extend the `Permission` model and add a new relation (The permission Category)
https://github.com/spatie/laravel-permission/blob/master/src/Models/Permission.php

Then just update your config file telling the package to use your model:
https://github.com/spatie/laravel-permission/blob/master/config/permission.php#L16

**Comment by drbyte** [comment]
If a naming convention may be helpful, you may find the alteration mentioned here useful: 
https://github.com/spatie/laravel-permission/issues/440
