### ISSUE TITLE
Laravel 5.8.24 compatibility issue?

### ISSUE THREAD

**Issue by Michael-John-King** [spatie/laravel-permission#1133]
Running "composer require spatie/laravel-permission" brings up this issue:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.8.24
    - Conclusion: don't install laravel/framework v5.8.24
    - laravelcollective/html 5.5.x-dev requires illuminate/view 5.5.* -> satisfiable by illuminate/view[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5 requires illuminate/view 5.5.* -> satisfiable by illuminate/view[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5.1 requires illuminate/view 5.5.* -> satisfiable by illuminate/view[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5.3 requires illuminate/view 5.5.* -> satisfiable by illuminate/view[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5.4 requires illuminate/view 5.5.* -> satisfiable by illuminate/view[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5.2 requires illuminate/view 5.6.* -> satisfiable by illuminate/view[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/view 5.5.x-dev|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.0|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.16|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.17|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.2|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.28|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.33|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.34|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.35|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.36|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.37|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.39|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.40|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.41|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.43|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.5.44|don't install laravel/framework v5.8.24
    - don't install illuminate/view 5.6.x-dev|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.0|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.1|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.10|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.11|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.12|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.13|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.14|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.15|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.16|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.17|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.19|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.2|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.20|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.21|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.22|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.23|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.24|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.25|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.26|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.27|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.28|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.29|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.3|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.30|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.31|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.32|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.33|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.34|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.35|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.36|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.37|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.38|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.39|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.4|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.5|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.6|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.7|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.8|don't install laravel/framework v5.8.24
    - don't install illuminate/view v5.6.9|don't install laravel/framework v5.8.24
    - Installation request for laravel/framework (locked at v5.8.24, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.24].
    - Installation request for laravelcollective/html 5.5.* -> satisfiable by laravelcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].

Installation failed, reverting ./composer.json to its original content.

I imagine this has to do with my version of laravel having compatibility issues but am obviously asking on here because I am unsure and quite new to this framework honestly.

**Comment by drbyte** [comment]
The spatie/laravel-permission package works fine with Laravel 5.8.24.
In fact, here are the requirements:
https://github.com/spatie/laravel-permission/blob/81dbe9d372d70c255b66a2727a235076509f8d45/composer.json#L21-L27

Your composer errors seem to be suggesting that the `laravelcollective/html` package you've installed specifically to version `5.5` may be forcing you to an older version of Laravel and thus forcing a matrix of combined incompatibilities.
