### ISSUE TITLE
How we used nested if Condition in Roles

### ISSUE THREAD

**Issue by laraveldeveloper3683** [spatie/laravel-permission#1134]
Hello,
Please help me the issue for "How we used the nested if for four types roles in same blade."

**Comment by drbyte** [comment]
Sorry, I don't understand your question.
You can do blade nesting just as you would in any blade template.
You can test for multiple roles using `hasAnyRole`

**Comment by laraveldeveloper3683** [comment]
I want to used nested if-else condition for checking the role in blade.
Like:
@if(@role('user'))
<h1>Am user</h1>
@elseif(@role('admin'))
<h1>am admin</h1>
@else
<h1>am test</h1>


But this way is wrong.I want to know how we used else if in this way in blade.

**Comment by drbyte** [comment]
`@role('editor')` is the same as `@if(Auth::user()->hasRole('editor'))`, so you could use either syntax.

This syntax also works:
https://github.com/spatie/laravel-permission/blob/81dbe9d372d70c255b66a2727a235076509f8d45/tests/resources/views/role.blade.php#L1-L7

**Comment by laraveldeveloper3683** [comment]
Thanks men

**Comment by laraveldeveloper3683** [comment]
yes thanks men!
