### ISSUE TITLE
Add wildcard check

### ISSUE THREAD

**Issue by shadoWalker89** [spatie/laravel-permission#114]
Hi,

First of all i want to thank you for the great package.

Let's say we have 3 permissions on the article module :

article.create
article.update
article.delete

Executing the following peace of code should return true if a user has one of the permissions above

``` php
$user->hasPermissionTo('article.*');
```

This would be a very good addition to the package

**Comment by freekmurze** [comment]
I'm glad you like the package 😄 

I'd accept a PR that adds this to the package. Be sure to include a lot of tests to make sure the introduced functionality works properly and convers all the edge cases.
