### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation 1452 Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by antweny** [spatie/laravel-permission#1144]
I have end_user role in my database so i want to assing it automatically everytime when a new user register this is how i did it. 
```
 protected function create(array $data)
    {
        $user = $this->register($data);

        $user->assignRole('end-user');

        return $user;
    }
```
i get this error

> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`social`.`model_has_roles`, CONSTRAINT `model_has_roles_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE) (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (a457ad7d-a957-4859-8469-b07dadfe2b48, App\User, 0))

but if i do this is working by assing a role to a user but only on the first run later throung duplicate error which i understand

```
protected function create(array $data)
    {
        $user = User::register($data);

        $role = Role::create(['name' => 'end_user']);
        $user->assignRole($role);

        return $user;
    }
```
i need help

**Comment by antweny** [comment]
this works too but not good.
```
protected function create(array $data)
    {
        $user = $this->register($data);

        $role = Role::where('name','end_user')->first();

        $user->assignRole($role);

        return $user;
    }
```

**Comment by drbyte** [comment]
1. `end-user` is different from `end_user`. You're using both in the code you posted. Which one is correct?

2. You already posted about this previously, but didn't provide answers to the request for further information:
https://github.com/spatie/laravel-permission/issues/1125#issuecomment-500958700

After you provide instructions for exactly how to re-create the problem in a new Laravel app, then we may be able to help you further.

**Comment by rakishii13** [comment]
I am getting the same error after upgrading to Laravel 5.8 and following to update to latest 2.37 for this package. When I try to assignRole to a user, I get the following error

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `et_model_has_roles` (`model_id`, `model_type`, `role_id`) values (?, App\User, 1))

It seems as though the assignRole is not taking the id from the user Model and using it to store into model_id.

**Comment by drbyte** [comment]
@rakishii13 I think your `1048 Column 'model_id' cannot be null` is different from the `1452 Cannot add or update a child row: a foreign key constraint fails` that this issue is about. 

Yours is likely that you're using a different field type for your model_id, and haven't consistently indicated that change. 

Please start a new issue if you need to discuss this, as it is different from the one in this discussion.

**Comment by rakishii13** [comment]
Okay will do that.
