### ISSUE TITLE
Dynamically set middleware for new role that will be created

### ISSUE THREAD

**Issue by eternalBlast** [spatie/laravel-permission#1145]
Hi, How to dynamically set middleware for new role that has been created. For example:
1. In initial stage, i set 2 roles, the superuser and manager. 
2. Meanwhile, in the future, i create new role.
3. I have to update the route middleware

Is there any way to do this? Please help. Thanks.
P.S: I am trying permissions but got this [issue](https://github.com/laravel/framework/issues/25466) on laravel 5.5.45 LTS

**Comment by drbyte** [comment]
I'm really not understanding your question "I have to update the route middleware". Yes, you do. And in most cases that should be app code, not dynamic lookups.

Best practice is to stick to "less is more". So, is there a "lower common denominator" that could be used for your middleware check? Instead of degrading your app performance by waiting for database lookups for randomly-changing lists of roles? 

Or maybe I'm completely missing what you're trying to accomplish. Lots more detail and context would help.

**Comment by eternalBlast** [comment]
Ok @drbyte. If i created a new role, let's say it's called operator. If i would use middleware using role like this snippet. 
```
Route::group(['middleware' => ['role:superuser|manager']], function () {
    //
});
```
In the future, i would need to add that params again like this.
```
Route::group(['middleware' => ['role:superuser|manager|operator']], function () {
    //
});
```
Meanwhile, the superuser who will create the user will be waiting for always updating the middleware if i am using role middleware check.

**Comment by drbyte** [comment]
Does your application use [route caching](https://laravel.com/docs/5.5/controllers#route-caching)?
If yes, then you won't be able to make the list of roles dynamic like that.

However, you could explore creating another custom middleware that performs what the `role` middleware does now, but also does a dynamic lookup. And then name that middleware in your route declaration. And then it wouldn't break route caching.

**Comment by drbyte** [comment]
The more I think about this, I'm pretty sure a custom middleware is the ideal solution.

**Comment by eternalBlast** [comment]
yes, i already achieved what i want. Thank you.

**Comment by sairamsalim** [comment]
> yes, i already achieved what i want and it is more flexible. Thank you.

hi, i wonder how you achieved that because i have the same issue.

could you describe how you achieve that?

thank you

**Comment by matinwd** [comment]
Any solutions? I have the same problrm

**Comment by eternalBlast** [comment]
Sorry for the late reply, I created a middleware file and do looping from permissions table. If permission is not found, then return value that user doesn't have permission to access.

**Comment by mohammadreza-soft74** [comment]
hi @eternalBlast  
i already have this problem . i hand assign a role dynamically to a middleware . 
can you put here code snippet?
