### ISSUE TITLE
Laravel Gares SuperAdmin create problem

### ISSUE THREAD

**Issue by HasanurHimel** [spatie/laravel-permission#1148]
Hi ....i facing some problem at the time of using superAdmin of laravel gates feature
I use below code in my AuthService provider into Boot method

                  

```
Gate::before(function (Admin $user, $ability) {
                          if ($user->isSuperAdmin('Super-admin')){
                                 return true;
                                }
                            });
```

Then i define the IsSuperAdminMethod into my Admin Model like below

                          public function isSuperAdmin($ability){
                                  foreach (\auth()->user()->roles as $role){
                                   foreach ($role->permissions as $permission){
                                      return $permission->name == $ability;
                                 }
                            }
                     }

But it doesn't work . What should i do ....

**Comment by drbyte** [comment]
The code you posted is checking whether your `Admin` user has a `permission` (not a `role`) named `Super-admin`.

Usually people use a `role` for Admin/superadmin functionality, not a `permission`.

Is there an intentional reason why you wrote it to look at permissions instead of roles?
