### ISSUE TITLE
syncPermissions with guard_name

### ISSUE THREAD

**Issue by ajaypatidarlipl** [spatie/laravel-permission#1153]
I'm using below function to sync user permissions

`$user->syncPermissions(['edit articles', 'delete articles']);`

but it's showing error "There is no permission named `edit article` for guard `web`."

let you know this user role guard is not `web`, its web_admin,

**Comment by drbyte** [comment]
To sync permissions for a specific guard, do a lookup of those permissions Model records, and pass those objects to `syncPermissions` instead of text strings.
(When you pass just text strings it uses the Default guard from your config, which in your case is evidently `web`.)

**Comment by ajaypatidarlipl** [comment]
Thank you, 
It's Working Now

**Comment by ajay-patidar** [comment]
Thank you,
It's Working Now

**Comment by Andr1yk0** [comment]
The following method also works for me. I'm working with Laravel 10
`$user->syncAllGuardsPermissions(['edit articles', 'delete articles'])`
