### ISSUE TITLE
Filter getAllPermissions with custom columns

### ISSUE THREAD

**Issue by ajay-patidar** [spatie/laravel-permission#1154]
I'm using this below function to get all permissions of a user
`$user->getAllPermissions();`

But I have created some columns in the permissions table and I want to filter `$user->getAllPermissions();`  according to those new columns, means use `Where `and `OrderBy` .
Please help me.

Thanks

**Comment by drbyte** [comment]
You could copy the `getAllpermissions` method from the trait as a new function in your user model and add your own logic to that (manipulating the collection before it is returned), and then use that new function in your app code when you need the filtering.
https://github.com/spatie/laravel-permission/blob/ba7ede883a0a1ba82a9cd7c70882fb02658b6dc0/src/Traits/HasPermissions.php#L279-L293
