### ISSUE TITLE
Tip: Wildcard guard for permissions and roles

### ISSUE THREAD

**Issue by mikemand** [spatie/laravel-permission#1156]
I know there are already a lot of (closed) issues about the guards, but I thought I'd document my solution for v2. Hopefully, v3 is in the works and will either include a wildcard ability or remove guards altogether. :smiley:

I have a use case similar to #968, where I have to support the same permissions for `web` and `api` guards equally.

Here's what I've done:

1. Extend the default Role and Permission models, and add a property called `$guard_name`. It can be set to whatever you want the default "guard" to be called. Don't forget to update the config to use your new models.
	```php
	<?php
	
	namespace App;
	
	class Role extends \Spatie\Permission\Models\Role
	{
	    protected $guard_name = '*';
	}
	```
	```php
	<?php
	
	namespace App;
	
	class Permission extends \Spatie\Permission\Models\Permission
	{
	    protected $guard_name = '*';
	}
	```
1. In your model(s) that `HasRoles` or `HasPermissions`, overwrite the `hasPermissionTo` and `getDefaultGuardName` methods:
	```php
	<?php
	
	namespace App;
	
	class User extends ...
	{
		use ...HasRoles...;
	
		public function hasPermissionTo($permission, $guardName = '*'): bool
		{
			// Since this method comes from a trait,
			// you cannot simply `parent::hasPermissionTo($permission, '*')`.
			// You'll have to copy the entire body of the method into yours.
			// Just replace '*' with the "guard" name from above.
		}

		protected function getDefaultGuardName(): string
	    {
	        return '*';
	    }
	}
	```
1. Create all of your permissions and roles with `'guard_name' => '*'` (replace `'*'` with whatever you want the default "guard" to be.)

So far, this seems to be working. I have not seen any downsides, but if @drbyte or someone else knows any pitfalls or gotchas, please let me know.

**Comment by drbyte** [comment]
Thanks @mikemand -- appreciate your sharing this simple workaround!

The guard-agnostic `v3` has been percolating on the back-burner for awhile, but hope to give it some love and a solid push in a couple months.

**Comment by drbyte** [comment]
@mikemand 
In a future major version, I'm thinking perhaps we can allow (maybe via a configuration option) a form of wildcard guard support as default, but for those who really require the specificity they could enable the additional restrictions.

Given that you've been using a wildcarding approach for awhile now, do you have any suggestions for implementation? Any gotchas you've run into? Any interest in participating with coding?

**Comment by mikemand** [comment]
Hi @drbyte,

My only suggestion would be to stick with Laravel's convention of using `*` as a wildcard "operator".

I have not had any problems and the only thing I have to do after recent updates to enable wildcard permissions and roles is to do the following:

* Extend the default `Role` and `Permission` models, and add `protected $guard_name = '*';`:
```php
<?php

namespace App\Entities;

/**
 * @mixin \Eloquent
 */
class Permission extends \Spatie\Permission\Models\Permission
{
    protected $guard_name = '*';
}
```

Now that I'm looking at the code, I think this is actually short-circuiting Eloquent... That's not my intention, but it is working... LOL

* For my `User` model, I only had to add the following (and I'm not even sure the property is used, just the method):
```php
public $guard_name = '*';

protected function getDefaultGuardName(): string
{
    return '*';
}
```

This method usually calls `Guard::getDefaultName()`, so maybe this is where we need to do the configuration (in the `Guard` class). Instead of using `$default = config('auth.defaults.guard');` we could add a key to the config for permissions.

Time permitting, I would be happy to help wherever I can to implement the solution that gets chosen.

**Comment by ErnestStaug** [comment]
Thanks for the TIP, saved the day.
Also my suggestion would be instead of copy/paste `hasPermissionTo` method you can rename the original when importing trait and do it something like:
```
   use HasRoles {
        hasPermissionTo as hasPermissionToOriginal;
    }

    public function hasPermissionTo($permission, $guardName = '*'): bool
    {
        return $this->hasPermissionToOriginal($permission, $guardName);
    }
```
this would prevent breaking if something changes in the method

**Comment by Mina-R-Meshriky** [comment]
by using this workaround if I query the `$this->users()->count()` on any of the permission model or the role model (extended from the package) it fails with "Class name must be a valid object or a string"
due to the function: `getModelForGuard` present in `users()` function ..... So I extended the function in both to include my only user model that has permissions or roles, 
```php
public function users(): MorphToMany {
        return $this->morphedByMany(
            User::class,
            'model',
            config('permission.table_names.model_has_permissions'),
            'permission_id',
            config('permission.column_names.model_morph_key')
        );
    }
```

**Comment by mikemand** [comment]
You shouldn't have to do this. Did you set up your User model correctly? https://docs.spatie.be/laravel-permission/v3/prerequisites/

**Comment by Mina-R-Meshriky** [comment]
actually yes the user model is set up correctly, however as I mentioned earlier the problem was in the function getModelForGuard : the following snippet is from the package
```php
    /**
     * @param string $guard
     *
     * @return string|null
     */
    function getModelForGuard(string $guard)
    {
        return collect(config('auth.guards'))
            ->map(function ($guard) {
                if (! isset($guard['provider'])) {
                    return;
                }

                return config("auth.providers.{$guard['provider']}.model");
            })->get($guard);
    }
```
the function will try to find the "*" guard in the auth.guards (which is not there) and then will retrieve the model for that guard -> since there is none it will return empty, which in return will produce that error.

if I put the "*" as a guard and put the provider for that guard as the User model, everything works normally.

**Comment by mikemand** [comment]
Ah! I see. I don't know why it is working for me, but I will dig further into my application and see if I have anything that differs from the steps in this thread. It could be that I did encounter your problem and solved it somewhere and just don't remember.

**Comment by ctf0** [comment]
not sure if this is the correct place to post this but an easier/better way to get around the guards issue, override the relations under ur model and limit it to a specific guard name ex.

```php
public function roles(): MorphToMany
    {
        return $this->morphToMany(
            config('permission.models.role'),
            'model',
            config('permission.table_names.model_has_roles'),
            config('permission.column_names.model_morph_key'),
            'role_id'
        )->where('guard_name', 'web');
    }

    public function permissions(): MorphToMany
    {
        return $this->morphToMany(
            config('permission.models.permission'),
            'model',
            config('permission.table_names.model_has_permissions'),
            config('permission.column_names.model_morph_key'),
            'permission_id'
        )->where('guard_name', 'web');
    }
```

now your app works exactly the same whether u have single or multi guards ex.`auth()->user()->roles`

**Comment by karlshea** [comment]
This is really not working well with 4.0. I'm getting `GuardDoesNotMatch` exceptions thrown when trying to assign a role to a user.

I've done some looking around and this package matches what I'd like to do way closer than any of the others, except for this guard issue.

**Comment by karlshea** [comment]
`getModelForGuard()` is only used to get the user model for the Role and Permission users relationship. You can fix that error by overriding it in your Role/Permission models by just manually passing your user class:

```php
public function users(): BelongsToMany
{
    return $this->morphedByMany(
        User::class,
        'model',
        config('permission.table_names.model_has_roles'),
        'role_id',
        config('permission.column_names.model_morph_key')
    );
}
```

**Comment by marijoo** [comment]
@freekmurze Would there be any chance to have this as a core functionality? If so I would happily create a PR for something like that.

**Comment by cesarreyes3** [comment]
@marijoo make the PR but add some testing

**Comment by drakakisgeo** [comment]
I wanted the same permissions/roles for both guards ( web and API ) so I just did this in my User model:

` protected function getDefaultGuardName(): string
    {
        return 'web';
    }`

**Comment by sebastian-adwise** [comment]
I want to know if this solution is currently recommended? I am using laravel permission version 5.7 and laravel version 9.

**Comment by drbyte** [comment]
@sebastian-adwise the solution posted above your post works, and is simple to do when using v5 of this package.
