### ISSUE TITLE
Move docs to documentation site

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-permission#1158]
Since the readme of this package is quite long, it makes sense to move it to our docs site.

Are you ok with this @drbyte? The readme will be converted to a set of markdown files in the `docs` directory of this repo.

**Comment by drbyte** [comment]
That seems sensible.

**Comment by riasvdv** [comment]
Docs can now be found here: https://docs.spatie.be/laravel-permission/v2/introduction/

@drbyte All the markdown files are in this repo in the `docs` folder, so feel free to restructure or change some things around. Netlify deploys automatically when something is changed in this repository, build time is about 1min so changes should be visible quickly :)

**Comment by riasvdv** [comment]
It also might take a while before the search starts working, Algolia needs to scrape the docs site, I don't know how soon or on what schedule they do this.

**Comment by drbyte** [comment]
Thanks @riasvdv
