### ISSUE TITLE
PermissionMiddleware not handling role permissions

### ISSUE THREAD

**Issue by paragonsoftwaresolutions** [spatie/laravel-permission#1159]
When I try to access a route protected by the PermissionMiddleware I get an error that user does not have permissions. The users assigned role has the permission. If I run $user->getAllPermissions() I see the permission there. If I add the permission to the user model I can then access the route.

**Comment by drbyte** [comment]
Sounds like your route is using a different guard than your default guard and the guard assigned to the role when you created it.

**Comment by paragonsoftwaresolutions** [comment]
The role guard is 'api'. The route group is using api middleware. The default guard set in config/auth is 'api'.

**Comment by drbyte** [comment]
The `PermissionMiddleware` simply calls `$user->can($permission)` on it ... which works like any other `can` or `@can` call in the app. This is defined to the Gate in the Registrar. Is something in your app changing the Gate registration process?
https://github.com/spatie/laravel-permission/blob/c7bb3d1bb6090006ee75bc312ff70e96cf3fb01f/src/Middlewares/PermissionMiddleware.php#L21

7 sentences really isn't enough context. Probably need to see your app code. Can you create a repo with a very simplified app that recreates just this problem? That would expose the solution more quickly too.

**Comment by paragonsoftwaresolutions** [comment]
Sorry for the delay, had to move on to something else for a bit. I created a repo that you can look at. https://bitbucket.org/smccoy78/laradmin

I hope this helps. If not, I'm sure I can figure out a way around it.

**Comment by drbyte** [comment]
After spending 45 minutes trying to install and get your code to run, including fixing all the things you've removed from the core Laravue distribution which break the provided migrations, in order to even stand up this repo, I'm pretty sure your symptoms are a result of inconsistencies you've introduced in your code ... whether that be missing ACL constants or other things in your implementation of Laravue.
