### ISSUE TITLE
Permission don't save in database

### ISSUE THREAD

**Issue by allowing** [spatie/laravel-permission#1160]
Permissions are part of the application. So it should be stay in the code.

saving in database is good too, but the thing is, when development add a permission, it's toooooo step to do.

writing permission in migration? yes it can be, but too many files quickly.

Database seeding? good idea. but I got permission exists exception. It for a developing project so bad.

😁

**Comment by drbyte** [comment]
> Database seeding? good idea. but I got permission exists exception. 

That means you're re-seeding an already-seeded database.
That's not a problem with this package. It's a problem with your app or tests or deployment process.
