### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null

### ISSUE THREAD

**Issue by rakishii13** [spatie/laravel-permission#1168]
I am getting an error after upgrading to Laravel 5.8 and following to update to latest 2.37 for this package. When I try to assignRole to a user, I get the following error

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `et_model_has_roles` (`model_id`, `model_type`, `role_id`) values (?, App\User, 1))

It seems as though the assignRole is not taking the id from the user Model and using it to store into model_id.

**Comment by drbyte** [comment]
Please explain more about the Upgrade you mentioned. What version of Laravel and Spatie-Permission did you upgrade from?

In your `App\User` model, what's the field type in the database? This package expects it to be an integer. Have you changed it to something else?

What steps can I take to replicate your situation on a brand new Laravel app?

**Comment by rakishii13** [comment]
I upgraded  Laravel from 5.7 to 5.8 and as part of it spatie/laravel-permissions upgraded form 2.31 to 2.37 and then I just tryied creating a user using the following the commands. 

`$user = User::firstOrCreate(['email' => $email]);`
`dd($user);`

The dd() does not contain 'id' as a attribute. In addition, the field type is bigIncrements which is the new default in laravel. And it is auto-incremented using laravel, which I am guessing is an integer.

**Comment by drbyte** [comment]
Seems like something wrong in your app, and not with this package. I can't create the problem here.
Need more information, as I have the same question as in your other thread: https://github.com/laravel/framework/issues/29221 
Please respond over there to the questions they're asking.

**Comment by rakishii13** [comment]
Oka, yea that is what I thought after further digging and hence placed the bug over there, as when I do  User::find() then I am able to retrieve the full model instance. 

Thank you!

**Comment by erikn69** [comment]
@vansh-rana the package is tested against Laravel 9, i'm using Laravel 9 without problems, pretty sure that your implementation is the problem, try to reproduce the problem on a fresh installation
