### ISSUE TITLE
Bug Guard.php

### ISSUE THREAD

**Issue by simonecicognani** [spatie/laravel-permission#1173]
The `$default` value is never returned

```
public static function getDefaultName($class): string
    {
        $default = config('auth.defaults.guard');

        return static::getNames($class)->first() ?: $default;
    }
```

**Comment by rslhdyt** [comment]
same here, I am using version 2.37.0

I can't assign roles to a selected user with the same guards.

**Comment by drbyte** [comment]
>         return static::getNames($class)->first() ?: $default;

This is by design in v2.
Changing it in v2 will break existing installations.
There are plans to remove the guard complexity in v3.

**Comment by lamemind** [comment]
Workaround: put the guard you want as the first item in the 'guards' array.

```
'guards' => [
        'backpack' => [
            /**
             * Workaround: put the guard you want as the first item in the 'guards' array
             * @see Spatie\Permission\Guard#getDefaultName
             */
            "driver" => "session",
            "provider" => "backpack"
        ],
        'web' => [ .....
```

**Comment by vcnwafor** [comment]
thanks man.
