### ISSUE TITLE
assignRole not work in 5.8

### ISSUE THREAD

**Issue by fh32000** [spatie/laravel-permission#1178]
```
        $employee = Employee::find(13);
        $user =$employee->user();
        $user->assignRole('manager');
```

    "message": "Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\HasOne::assignRole()",
    "exception": "BadMethodCallException",

**Comment by drbyte** [comment]
That is an error in your app, not in this package.
Maybe here:
```diff
-    $user =$employee->user();
+    $user =$employee->user;
```
