### ISSUE TITLE
Question about @role in blade

### ISSUE THREAD

**Issue by thetpainghtut** [spatie/laravel-permission#1179]
Hello, I am getting an error. I use spatie for 3 user roles and one for super admin. How to test super admin role in laravel blade. not using => @role('user|admin') ------ @endrole. I ever test with (|) and i think it is not a right way. please advice me.

**Comment by drbyte** [comment]
Yes, `@role('user|manager|member')` would be truthy if the currently-logged-in-user has `one` of those roles.
It is roughly equivalent to calling `@if(auth()->check() && auth()->user()->hasRole('user|manager|member'))`

**Comment by thetpainghtut** [comment]
But, i don't want to write | (or) for super admin. I think if super admin login, ignore all role and permission , and can access all not writing | (or) in blade role testing.

**Comment by drbyte** [comment]
If you've defined a Gate::before() rule for super admin and wish to not have to mention super admin in your application, then you must use the `@can` directive for all your permissions checking, not the `@role` directives.
https://docs.spatie.be/laravel-permission/v2/best-practices/roles-vs-permissions/

**Comment by thetpainghtut** [comment]
Thanks it work (error is checking with @role directive) :D
