### ISSUE TITLE
Problema con @can

### ISSUE THREAD

**Issue by rnmontufar** [spatie/laravel-permission#1182]
Hola, tengo un problema, tengo el siguiente codigo:
`@can('crear-tipo-documento')
                        <a href="{{route('tipo_documento_crear')}}" class="btn btnProyecto">Crear tipo de Documento</a>
@endcan`

- Tengo un usuario "Rolfy" con el rol "X" este rol tiene el permiso 'crear-tipo-documento', sin embargo en la vista no me muestra el link.
- Hice varias pruebas de lo mismo y despues de algun tiempo apareció el link.
- Cada cierto tiempo actualiza los permisos?
- Podria ser problema del cache del servidor?
- Borré la caché local.

Por favor alguna sugerencia?

**Comment by drbyte** [comment]
Do you mind posting in English please?

**Comment by rnmontufar** [comment]
Of course, thanks.
Hello, I have a problem, I have the following code:
`@can('crear-tipo-documento')
                        <a href="{{route('tipo_documento_crear')}}" class="btn btnProyecto">Crear tipo de Documento</a>
@endcan`

- I have the user  "Rolfy" with role "X" this rol has permissions 'crear-tipo-documento', however in the view it does not show me the link.
- I did several tests of the same and after some time the link appeared.
- Do you update permissions every **some** time?
- Could it be server cache problem?
- I cleared the local cache.

Please any suggestions?

**Comment by drbyte** [comment]
The `@can` directive checks whether the current user has the defined permission on the default guard.
Permissions provided by this package are registered by the package's ServiceProvider, where it reads the cache and/or database for all permissions for the current user.

The cache is automatically cleared every time a permission or role is created/removed/assigned using the built-in methods such as `givePermissionTo`, `revokePermissionTo`, `assignRole`, `removeRole`, `syncPermissions`, `syncRoles`, and the `create` method on the Permission and Role models.

The default guard in a Laravel app is `web`. Is your app using only the `web` guard? Or are you using other guards as well? If you're not primarily using `web` then you should set your default guard correctly in your `config/auth.php` file.

**Comment by rnmontufar** [comment]
I'm so sorry, It was a problem on the server. Thanks a lot for your support.

**Comment by drbyte** [comment]
Thanks for posting back that it is solved. 👍

**Comment by Marje123456** [comment]
> I'm so sorry, It was a problem on the server. Thanks a lot for your support.

hola, tengo el mismo problema. ¿Cómo lo solucionaste?
