### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Rajeshrj202** [spatie/laravel-permission#1183]
Invalid argument supplied for foreach() while using Middleware permission And @can with permission

**Comment by drbyte** [comment]
Hi,
Given that the tests for this package show middleware to be working, it sounds like you have an error in your application code.

It's very difficult to provide support without seeing any of your code or instructions on how exactly to recreate the same problem when starting with a brand new Laravel app.
Please provide the steps to recreate the problem.

**Comment by bzarzuela** [comment]
Can I chime in? Because I just figured this out in my codebase. I had a field called roles in my users table. It was causing the conflict with the accessor that the HasRoles Trait expects

**Comment by wapmastaz** [comment]
> Can I chime in? Because I just figured this out in my codebase. I had a field called roles in my users table. It was causing the conflict with the accessor that the HasRoles Trait expects

Thank you so much. this save many days of tears

**Comment by ibsam** [comment]
@wapmastaz Great this make my day easier thanks for the answer
