### ISSUE TITLE
Granular Permissions

### ISSUE THREAD

**Issue by Continuum81** [spatie/laravel-permission#1187]
Consider software that allows users to share files with other individual users within the same organisation. (Not Multi-tenant)

There does not seem like there is a simple way to discriminantly share certain files with certain users with a specific permission. 
User 1, allows User 2, to [read|write|delete] File 1

Is there an workable way to extend functionality to allow this, or is this on a road-map for future development ?

**Comment by drbyte** [comment]
Am I correct that all three of these issues are essentially exploring the same thing?
#1187 by @Continuum81 
#1186 by @Roemerb
#1135 by @liamoreilly 

... ie: wanting to extend the polymorphic permissions-to-User relationship another layer deeper, by enforcing those rules onto specific records of another model

**Comment by Continuum81** [comment]
Sure, I guess its the same issue.

**Comment by drbyte** [comment]
@Continuum81, apologies: I could have worded that differently ;)
I wasn't necessarily looking to close the issue, but rather to confirm that the underlying inquiry is largely similar.
... and then the next objective would be to invite collaboration amongst the interested parties to come up with the solution.
ie: multiple developer minds looking at the same issue from different ways often leads to a better solution, faster.

Shall we take this discussion over to one of the other threads by @liamoreilly or @roemerb ?

**Comment by Roemerb** [comment]
Yes @drbyte This is basically exactly what I meant in my issue. Where would you like to move? All issues are closed 😄

**Comment by drbyte** [comment]
@Roemerb 2 of them are open, including yours ;)
