### ISSUE TITLE
How do I send users to different dashboards by their roles?

### ISSUE THREAD

**Issue by sarderiftekhar** [spatie/laravel-permission#1189]
HI,

I am struggling to send the users to different dashboards by detecting user roles.
I tried using RedirectIfAutheticated and LoginController file. But nothing works.
How can I detect who is logged in  by role?

**Comment by drbyte** [comment]
> How can I detect who is logged in by role?

If you really mean "how can I detect whether the logged in user has a certain role" (in order to direct them accordingly), then you have to first have a logged-in user.
Next, your debugging can include dumping out `$user->roles` so that you can inspect the object properties.
Then you should be able to use the `$user->hasRole('foo')` method to take action accordingly.

**Comment by sarderiftekhar** [comment]
HI thanks for the reply,

I am using this code in RediectIfAuthenticated 

    public function handle($request, Closure $next, $guard = null)
    {
         if (Auth::guard($guard)->check() && User::role('admin')) {
            return redirect()->route('admin-dashboard');
         }
        // else
        if (Auth::guard($guard)->check() && User::role('compliance')) {
            return redirect()->route('compliance-dashboard');
         }
        return $next($request);
    }

And these codes in LoginController
protected $redirectTo;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        if(Auth::check() && User::role('admin')){
            $this->$redirectTo = route('admin-dashboard');
        }
        elseif(Auth::check() && User::role('compliance')){
            $this->$redirectTo = route('compliance-dashboard');
        }
        $this->middleware('guest')->except('logout');
    }

But its not detecting properly, only the admin check works but if I try to login using the compliance details it tries to send me to admin route.

**Comment by drbyte** [comment]
`User::role('admin')` is going to return a collection of all users having the `admin` role. It's not going to tell you whether the authenticated user has that role.

You need to use `hasRole()` for that.

**Comment by sarderiftekhar** [comment]
Hi if I put hasRole() instead of role() it throws error! How can I check as soon as a user log's in to check what role he has?

**Comment by drbyte** [comment]
What's the error?

**Comment by drbyte** [comment]
Also, are you really using `$` twice like this? Was this intentional?
`$this->$redirectTo = ...`

**Comment by sarderiftekhar** [comment]
HI here is the error,
ErrorException (E_DEPRECATED)
Non-static method App\User::hasRole() should not be called statically

I got rid of the $ , so its like $this->redirectTo =

**Comment by sarderiftekhar** [comment]
"What's the output of dd($user->roles)?"
the $user is not recognised....

**Comment by drbyte** [comment]
https://laravel.com/docs/5.8/authentication#retrieving-the-authenticated-user

Test a role:
`Auth::user()->hasRole('foo')`

Dump all the user's roles:
`dd(Auth::user()->roles)`
