### ISSUE TITLE
Laravel 6.0 Support

### ISSUE THREAD

**Issue by meldsza** [spatie/laravel-permission#1193]
[Laravel 6.0 is officially released now](https://laravel.com/docs/6.0/releases)

I want to update to it but laravel-permission needs illuminate/database ~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0

Any idea when Laravel 6 support is going to be added?

**Comment by drbyte** [comment]
Soon. 
After 6.0 is actually released. 

Read more in the release notes, or at at https://laravel-news.com/is-laravel-6-0-out-yet?

**Comment by zack6849** [comment]
@drbyte  are you guys open to PRs to bump the illuminate/database DEP providing all tests still pass?

Also, would that require a major version bump since it's bumping laravel's requirement to 6.0?

Thanks

**Comment by flowser** [comment]
i need an update to support laravel 6

**Comment by drbyte** [comment]
v3.0.0 was released a couple minutes ago.
