### ISSUE TITLE
Is that possible to make edit role interface like this one?

### ISSUE THREAD

**Issue by RobbyAJM** [spatie/laravel-permission#1195]
![edit role illustration](https://user-images.githubusercontent.com/29008865/63910578-84c25200-ca51-11e9-996c-067f27d284c5.png)

I wanna do like that, is that possible? Teach me how to do like that one please 😃

**Comment by drbyte** [comment]
The process is the same for any forms whose data are stored in the database: retrieve the values, display the form to the user, parse and validate what they submit, and save the validated inputs back to the database.

Your question is not really about this package, but about how to build a UI in Laravel.
