### ISSUE TITLE
permission issue in package. can() and @can return while user has permission

### ISSUE THREAD

**Issue by irtzamazhar** [spatie/laravel-permission#1198]
In my scenario admin user has "income_tax_slabs" permission and in my blade if i restrict using **@can('income_tax_slabs') and $user->('income_tax_slabs')** both return false and i am just at this time. I already google this issue but I think this problem is in this package.

**Comment by drbyte** [comment]
I'm not understanding your question.

Please provide your code, including controller, blade template, config/auth.php and config/permissions.php files.
