### ISSUE TITLE
Use custom exception messages in API applications?

### ISSUE THREAD

**Issue by menadio** [spatie/laravel-permission#1199]
I want to display custom messages when exception is thrown for users who do no have specific roles or permission. I tried doing this by checking if the user has the required role but I still get the default 403 html page. How can I use custom exception messages in API applications? 

Tried this code but I still got the default exception message
```
if (auth()->user()->hasRole('admin')) {

    // create & store the product
    $product = Product::create($request->all())

    // return new product
    $responseMessage    = 'Successful operation';
    $responseStatus     = 200;
    $productResource    = new ProductResource($product);

    return response()->json([
        'responseMessage'   => $responseMessage,
        'responseStatus'    => $responseStatus,
        'product'           => $productResource
    ]);
} else {
    
    return response()->json([
        'responseMessage'   => 'You do not have required authorization.',
        'responseStatus'    => 403,
    ]);
}
```

**Comment by drbyte** [comment]
This package won't throw a 403 exception when calling `hasRole('admin')`.
Your syntax for using `hasRole()` is fine. 
Thus this is not an issue with this package or your use of it, but rather the problem is in your application code.
