### ISSUE TITLE
Feature: add blade directives to check if user has certain role

### ISSUE THREAD

**Issue by lowerends** [spatie/laravel-permission#12]
It would be useful to have a blade directive that checks if a user has all or any of a given list (array) of roles. The syntax could be like this:

````
@has(['role_1', 'role_2', 'role_3'])
<some html/php here>
@else
<some other html/php here>
@endhas
````

What are your thoughts on this?

**Comment by freekmurze** [comment]
I think it's a good idea to have that functionality, but I don't like the naming. 

This would be better:
```php
@role('administrator')
<some html/php here>
@endrole
```

`@can` does not have an `else` so I think `@role` shouldn't have `else`.  `@norole` would be better.

Of course the directives should handle both strings and arrays.

If you would make a PR for this, I'd likely accept it.

**Comment by lowerends** [comment]
I'm using `@can` with an `@else` part successfully. I think it will be important that you can define what needs to happen if the user doesn't have any or all of the roles.

As for the naming, it may be even better to make them consistent with the other PR I'm working on, to have `@hasAnyRole` and `@hasAllRoles`.

**Comment by freekmurze** [comment]
In that case our blade directives should have an `@else` has well. Thanks for correcting me on this. 

Good idea on the naming. Blade directives are generally lowercase so I prefer if the ones you add are lowercase as well. On top of the ones you're proposing a `@role` one (that has the behaviour of `@hasanyrole`) would be nice. `@norole` is still valuable so you aren't required to use an `else`.

Thoughts?

**Comment by lowerends** [comment]
Agree, also with the fact that `@norole` can still be valuable.

So to sum up, we would have:

````
@role = @hasanyrole
@hasallroles
@else
@endrole, @endhasanyrole, @endhasallroles
@norole
````

**Comment by freekmurze** [comment]
:+1: go forth and code!
