### ISSUE TITLE
guard_name also as a function

### ISSUE THREAD

**Issue by gerardnll** [spatie/laravel-permission#1203]
Could it be possible to make $guard_name a property and a static function in the same way Nova does it with 'group' and 'name'? So we can use config('nova.guard')? I'm using a 'web' guard for normal users and a 'back' guard for admin users.

**Comment by drbyte** [comment]
> I'm using a 'web' guard for normal users and a 'back' guard for admin users.

Do the actual permissions need to be "different" for each guard? (It's planned to remove the guard-specific linkage in the next version, since most apps end up defining the same permissions for each guard, meaning they're defined multiple times for no benefit, and so far there seems to be no advantage to the keeping all the complexities of guard-specific code.)

**Comment by dennis-git** [comment]
yes, we need different permissions per guard. We use one set for nova guard, one set for web and one set for api. They are not related in any way.

**Comment by drbyte** [comment]
> yes, we need different permissions per guard. We use one set for nova guard, one set for web and one set for api. They are not related in any way.

And they have completely different names, too?

**Comment by dennis-git** [comment]
> > yes, we need different permissions per guard. We use one set for nova guard, one set for web and one set for api. They are not related in any way.
> 
> And they have completely different names, too?

yes, completely different. We use nova guard for all nova resources in the nova panel only, separate from web and separate from api. Only functionality that is lacking now is inability to check the guard name on the Role. Guard can be passed during creation like so $new_role = Role::findOrCreate($roleName, $guard);

But currently $user->hasRole('Admin') ignores guard setting completely.

**Comment by drbyte** [comment]
> But currently $user->hasRole('Admin') ignores guard setting completely.

Passing a string will have it lookup the guard from various criteria (the implementation of which is controversial, and is why guard infrastructure is being phased out).

However, if you pass the Role model instead of the string name, it will do exactly as you expect.

**Comment by dennis-git** [comment]
ok, I will try that. I am not sure how you can phase out guard infrastructure when guard is internal to Laravel infrastructure and is attached to all routes.

**Comment by drbyte** [comment]
> ok, I will try that. I am not sure how you can phase out guard infrastructure when guard is internal to Laravel infrastructure and is attached to all routes.

By "phase out" I mean this package won't tie itself to specific guards. Maybe "guard-agnostic" would have been a better way to say it. You're free to use guards however you wish, but simply use role/permission names related to what you're controlling.

**Comment by dennis-git** [comment]
I am personally against that change because it will make this package not usable for our needs. I can understand having a default guard so you don't have to pass a name around to various calls if developers are lazy or don't want to use it. It should still be an option to use custom guard names/namespaces if one needs it.

**Comment by drbyte** [comment]
Can you explain a use-case? Where's the specific value in passing a guard (which is an authentication component) when checking against a permission (which is an authorization component)? Some practical examples will help inform the decision-making moving forward.

**Comment by dennis-git** [comment]
Example of how we use it:
User logs in to nova admin panel, .env file has NOVA_GUARD=nova so nova guard is used. User Provider has $guard_name set to nova. Therefore all policies can check specific permissions against nova namespace only. Same applies to web, api, custom guards etc. Current namespaces help to separate thousands of permissions by their corresponding guard and make the code easier to write/follow as well.

I understand that everything can be lumped together into 1 big mess where you have 2000 permissions and no idea which one goes where. That's the benefit of this package that it does provide guard namespaces.

**Comment by dennis-git** [comment]
I forgot to mention that Laravel `can` function does indeed check against the correct guard and namespace. So permission 'A' in guard nova is different than permission 'A' in guard web.

**Comment by drbyte** [comment]
Thanks. It's helpful to know your use-case.

Seems quite similar to adding various custom fields to either of the roles/permissions tables in order to track additional values/data/patterns not offered already by the package.

I've rarely encountered a case where an app aggressively wants a permission named "A" to exist in multiple guards for entirely different purposes: thus far they've always recognized that they're using for different reasons, so naming differently has actually made more semantic business sense anyway.

**Comment by drbyte** [comment]
Also, thanks for engaging in the discussion - there are lots of ways to build an app, and I'm grateful for the different contexts shared here!

**Comment by dennis-git** [comment]
Well if you don't have namespaces, you have to have different permission names for different guards. There is no other way. If I want the user to view_user in their account, that's different than view_user in nova admin panel. As a matter of fact, most of the time user should not be able to access admin panel at all unless they are an admin or have special permissions. In this case, admin user can have view_user permission in both nova and web, but they do mean different things. Without namespaces, there must be 2 permission view_user_nova and view_user_web vs view_user namespace nova and view_user namespace web.

**Comment by drbyte** [comment]
It also means you "must" provide permissions (even duplicates) for every guard you support, even if you "are" using them for identical purposes ... which means a lot more records to process when the app is only using guards as a way to access the application but isn't actually doing anything different between guards as far as role/permission goes.

**Comment by dennis-git** [comment]
I am not sure why you would have the same permission semantically for different guards. What's a good example of that use case?

**Comment by drbyte** [comment]
> I am not sure why you would have the same permission semantically for different guards. What's a good example of that use case?

eg: User can use the app via browser (non-SPA, web guard, where authentication is via session), and via mobile app (api guard where authenticated via tokens), but the user's roles/permissions are the same regardless which guard controls how they connect to the application.

**Comment by dennis-git** [comment]
ok, in this case you can ignore the guard and do something like $user->hasPermissionTo('view_something'), which will use the default guard like `web` and no need to duplicate permissions.

**Comment by drbyte** [comment]
> ok, in this case you can ignore the guard and do something like $user->hasPermissionTo('view_something'), which will use the default guard like `web` and no need to duplicate permissions.

In a perfect world, yes.

**Comment by dennis-git** [comment]
If there is a case where a permission needs to be shared between different guards say `api` and `web`, one can simply check if `web` permission is allowed without needing to replicate it. I think it's easier to share a permission and not having to replicate it vs not having a namespace functionality at all and having to mix all permissions together for different guards. Also, Laravel's `can` function might still be broken if `api` guard was used but the developer wants to check against `web` guard.

**Comment by drbyte** [comment]
@dennis-git I've posted in a couple other issues that I'm willing to entertain a tested PR which allows this package to (keep its current guard support but also) respect the guard that the user has logged in through, instead of defaulting to the name of a property on a model.

I'm thinking it'd be nice to also allow (perhaps via a configuration option) wildcard guard support, so that people not needing specific different behavior for the same permission-name used in separate guards, could disable that 3D-matrix complexity, but still allow its capability for those such as yourself who use it specifically.

Would you be interested in participating with either or both?

**Comment by drbyte** [comment]
@gerardnll @dennis-git 
Will the changes proposed in #1384 provide the fix you were seeking? 
Will it create any problems in your app (ie: breaking changes)?

**Comment by drbyte** [comment]
@gerardnll for your Nova use, if we add possibility of a `guard_name()` function, do you envision the following would be sufficient?

`Guard.php`
```diff
    public static function getNames($model): Collection
    {
        if (is_object($model)) {
+            if (\method_exists($model, 'guard_name')) {
+                $guardName = $model->guard_name();
+            } else {
                $guardName = $model->guard_name ?? null;
+            }
        }
        //...
    }
```

Perhaps you're already doing something like this by overriding the `protected function getGuardNames()` method in the trait?

**Comment by gerardnll** [comment]
Sorry, this was a long time ago, I may not remember exactly was I was trying to do but I think (and as far as I see) I'm just overriding the $guard_name property on the model.

`protected $guard_name = 'back';`

If I remember correctly, what I was asking was for something like this:

```
public function guardName()
{
    return config('nova.guard');
}
```

So yes, that's pretty much what you did. Maybe the function name should be in camelcase?

**Comment by musapinar** [comment]
I'm a bit late to the party as I just noticed the latest commit referencing this issue, but why not make use of Laravel's accessors, instead of having such a ```guard_name()``` ?

Wasn't something like the following enough?
```php
public function getGuardNameAttribute() {
    // your custom logic
}
```

@drbyte

**Comment by drbyte** [comment]
@musapinar good point ... hmmmm ... 👀

**Comment by gerardnll** [comment]
> I'm a bit late to the party as I just noticed the latest commit referencing this issue, but why not make use of Laravel's accessors, instead of having such a `guard_name()` ?
> 
> Wasn't something like the following enough?
> 
> ```
> public function getGuardNameAttribute() {
>     // your custom logic
> }
> ```
> 
> @drbyte

"Accessors and mutators allow you to format Eloquent attribute values when you retrieve or set them on model instances."

To me, it looks like a hack.

**Comment by musapinar** [comment]
https://www.youtube.com/watch?v=pWdd6_ZxX8c

To me, this merge looks like a hack.

Here is why :

- I can certainly understand the need for a custom method.
- We do not need both a ```guard_name()``` method and a ```$guard_name``` property. They do the same.
- But I guess we cannot remove the ```$guard_name``` property unless we introduce a breaking change to this package.
- So you guys quickfixed it that way, adding an other layer of complexity to that mishmash logic of "this has precedence over that".

That's why the accessor, to me, looks like the most elegant solution. and does not even require any PR at all to this package ¯\\_(ツ)_/¯

**Comment by gerardnll** [comment]
Funny video. 

If Eloquent models are a representation of a DB model, and mutators are there to alter the value of those columns, I don’t think your proposal is adecuate. 

Also, the PR/commit applies a solution that can also be found in Nova. 

I think this package should stick to the conventions of the ecosystem and Laravel itself.

I just don’t see any downside to the changes made.

**Comment by musapinar** [comment]
I see what you mean now. That is a valid concern indeed.
I was bothered by the property becoming unnecessary because of that new method but there is no other way around at this point.

**Comment by stevebauman** [comment]
I'm not really understanding the point of having permissions be resolved per guard? Why not simply namespace them in the name of the permission itself? You're already having to create two permission records.

For example: `nova.view-user` or `web.view-user`.

You can easily identify and scope queries for your permissions with a simple SQL `LIKE`:

```php
// Get all nova permissions the user has.
$user->permissions()->where('name', 'like', 'nova.%')->get();
```

I'm all for removing this permission "resolution". Hoping this is phased out in future versions 👍
