### ISSUE TITLE
No way to check against specific 'guard' for HasRole

### ISSUE THREAD

**Issue by dennis-git** [spatie/laravel-permission#1204]
$user->hasRole() has no way to check against a specific guard like $user->hasRole('Admin', 'api').

$user->hasPermissionTo('edit_article', 'api') does. 

roles table has a guard_name column but no way in the library code to check against it.

Thank you.

**Comment by drbyte** [comment]
First obtain the Role model:

`$role = Role:: findByName($name, $guardName);`
`$user->hasRole($role);`

**Comment by dennis-git** [comment]
```$role = Role:: findByName($name, $guardName);
$user->hasRole($role); ```

works but it throws an Exception if the Role is not found instead of returning true/false like $user->hasRole('Admin'); would do

also how would this work in the Blade templates with @role('') and @hasrole('') directives if developers need to check the role against a guard name?

**Comment by dennis-git** [comment]
$role = Role:: findByName($name, $guardName);
$user->hasRole($role); 

works but it throws an Exception if the Role is not found instead of returning true/false like $user->hasRole('Admin'); would do

also how would this work in the Blade templates with @role('') and @hasrole('') directives if developers need to check the role against a guard name?

**Comment by drbyte** [comment]
@dennis-git 
I'd entertain a tested PR which adds a guard check for hasRole, without introducing breaking changes.

**Comment by dennis-git** [comment]
ok, I will work on it this weekend. Thank you.

> @dennis-git
> I'd entertain a tested PR which adds a guard check for hasRole, without introducing breaking changes.

**Comment by dennis-git** [comment]
@drbyte
