### ISSUE TITLE
UNIQUE constraint should be added to roles and permissions tables in the migration

### ISSUE THREAD

**Issue by dennis-git** [spatie/laravel-permission#1205]
UNIQUE constraint should be added to roles and permissions tables in the migration like so:

        Schema::create($tableNames['permissions'], function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('guard_name');
            $table->timestamps();
            $table->unique(['name', 'guard_name']);
        });

        Schema::create($tableNames['roles'], function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('guard_name');
            $table->timestamps();
            $table->unique(['name', 'guard_name']);
        });

to prevent creating duplicate Roles and Permissions, which can break someone's code quite easily.

**Comment by drbyte** [comment]
Ref: #1206
