### ISSUE TITLE
Blade directives not working inside "vendor" views.

### ISSUE THREAD

**Issue by williambeeler** [spatie/laravel-permission#1207]
Forgive me for not being able to explain this better than I am here. So, I had Tabler installed, and I pulled those files in for editing within my view folder. The way Laravel organized it was by putting the tabler views within the following structure: '/views/vendor/tabler/' .. I then began to modify those files and use laravel-permission within them. All was working awhile ago (I had v2 installed on an earlier version of Laravel, like v5.6 or something). However, I upgraded to Laravel 5.8 or thereabouts and I started to have some issues. @role and other blade directives were being dumping into the code instead of being interpreted as expected. So, I finally figured out that it had to do with those directives being called within the /views/vendor/ folder. So I took the Tabler files outside of that folder and put it in the main /views/ folder, and everything worked fine with laravel-permission blade directives. I'm not sure if this is a Laravel problem, or a laravel-permission problem. I just wanted to let someone know. Thanks! I love your package and use it in all my work!

**Comment by drbyte** [comment]
Thanks for sharing the tip!
