### ISSUE TITLE
Could not install in Laravel 5.5

### ISSUE THREAD

**Issue by xlkit456852** [spatie/laravel-permission#1208]
Laravel : "laravel/framework": "5.5.*",

I run this :
composer require spatie/laravel-permission 2.0

and get:
Problem 1
    - Installation request for spatie/laravel-permission 2.0 -> satisfiable by spatie/laravel-permission[2.0.0].
    - Conclusion: remove laravel/framework v5.5.48
    - Conclusion: don't install laravel/framework v5.5.48
    - spatie/laravel-permission 2.0.0 requires illuminate/container ~5.4.0 -> satisfiable by illuminate/container[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5
.4.36, v5.4.9].
    - don't install illuminate/container v5.4.0|don't install laravel/framework v5.5.48
    - don't install illuminate/container v5.4.13|don't install laravel/framework v5.5.48
    - don't install illuminate/container v5.4.17|don't install laravel/framework v5.5.48
    - don't install illuminate/container v5.4.19|don't install laravel/framework v5.5.48
    - don't install illuminate/container v5.4.27|don't install laravel/framework v5.5.48
    - don't install illuminate/container v5.4.36|don't install laravel/framework v5.5.48
    - don't install illuminate/container v5.4.9|don't install laravel/framework v5.5.48
    - Installation request for laravel/framework (locked at v5.5.48, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.48].

Installation failed, reverting ./composer.json to its original content.

Is there any way to resolve this?

**Comment by lizhineng** [comment]
The latest version of the package requires minimal version of Laravel 5.8, so you can't install v2 Laravel-permission on your Laravel 5.5 project, consider downgrade to v1 instead.

**Comment by vdbelt** [comment]
You are trying to install 2.0.0 which is not compatible with L5.5.

`composer require spatie/laravel-permission "^2.0"` should do the trick. This allows composer to search for any minor version within v2.

**Comment by xlkit456852** [comment]
I really appreciate your help~

**Comment by asipbajrami** [comment]
or u can run 
`composer require spatie/laravel-permission:*`
