### ISSUE TITLE
@can blade directive is not working

### ISSUE THREAD

**Issue by xlkit456852** [spatie/laravel-permission#1212]
composer.json:
"laravel/framework": "^6.0",
"spatie/laravel-permission": "^3.0"

User(guard_name=brand) has the 'edit_articles' permission ( I confirm it by using $user->getAllPermissions() ) ,when I use 
```
@if(auth('brand')->user()->hasPermissionTo('edit_articles')) 
...
@endif
```
in blade , I got the true result (correct) . But when I use
```
@can('edit_articles','brand')
...
@endcan
```
I got the false result (wrong) .  Is there any part that I make mistake?

**Comment by xlkit456852** [comment]
I found that is my problem . I forgot to add auth:brand in my route's middleware attribute .

**Comment by alcarazolabs** [comment]
I had the same problem using the versión 5 and downgrade to 4 versión and worked with laravel 8.

**Comment by Fredericld** [comment]
I seem to have the same problem.
I am using laravel 8 and spatie version 5.9
I checked my route middleware and it is setup as it should
