### ISSUE TITLE
@can Blade Problems vs Backend

### ISSUE THREAD

**Issue by mprythero** [spatie/laravel-permission#1213]
I'm unsure where to go to next so I am just going to start here. I have several permissions, but I can't get any of them to work in a blade setting. So I can use the following in my controller:
`if(Auth::user()->can('Tasks Edit'))`
The permission works exactly as intended. But if I use in the blade:
`@if(auth()->user()->can('Tasks Edit'))`
or
`@can('Tasks Edit')`

The permission doesn't work...

I have tried this command: `php artisan permission:cache-reset` but unfortunately all I get is "Unable to flush cache". If anyone has any suggestions, I'd be so grateful. My current version is 2.38 but will try to upgrade to 3.* tomorrow depending on the results from this post.

Thank you!

**Comment by mprythero** [comment]
@drbyte - I do use the `api` guard but only for the mobile applications I've built to communicate. Based on what you're saying, at this point it time, I should create the duplicate permissions for the api guards? Is there a place I can stay up to date on the potential for the duplicate permissions though? I can see their purpose but it still sounds like an interesting concept. And thank you for your help, I really do appreciate it!

**Comment by dennis-git** [comment]
how are you using api responses and blade templates together? Doesn't make any sense.

**Comment by mprythero** [comment]
@dennis-git - Not together, @drbyte just mentioned "anywhere in the app", and I do use the api guard in conjunction with Passport for integration with external mobile applications. But all of the blade templates only use the `web` guards.

**Comment by drbyte** [comment]
In Blade, does explicitly stating the `web` guard with `@can('permission name', 'web')` work for you?

If not, then I wonder if you've got the same permission name defined another way in your app, and that's interfering.

**Comment by Huntelaer** [comment]
I got this error when using the same cache for 2 different environments. Solved it by adding a cache prefix.

**Comment by criticon** [comment]
I also got the "Unable to flush cache" issue. In my case, the solution was to run cache-reset command under the user cache files belong to.
Like this:
`sudo -u www-data php artisan permission:cache-reset`
