### ISSUE TITLE
Laravel 6.0 upgrade error

### ISSUE THREAD

**Issue by iteearmah** [spatie/laravel-permission#1215]
- spatie/laravel-permission 2.38.0 requires illuminate/database ~5.4.0|~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by laravel/framework[v5.8.35], illuminate/database[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34...

**Comment by drbyte** [comment]
This package uses version `^3.0` for Laravel 6 compatibility.
