### ISSUE TITLE
Extending Role model and triggering Observer events

### ISSUE THREAD

**Issue by luchorengo** [spatie/laravel-permission#1221]
In trying to send some notifications when a Role is updated.
For some reason, when extending the Role model, Observer events are not being triggered.
Please ignore the fact that extended Role model has nothing special, it will have some custom fields in the future, that's why I'm extending it.
In the same way, I will have some extra fields in the Permission model.

This what I have so far:

Role model:
```
<?php
namespace App;
use Spatie\Permission\Models\Role as Roles;

class Role extends Roles
{
    protected $table    = 'roles';
    protected $fillable = ['name','title','guard_name'];
}
```
Role observer:
```
<?php

namespace App\Observers;

use App\Role;
use App\User;
use App\Notifications\RoleUpdated;

class RoleObserver
{
    public function updated(Role $role)
    {
        \Log::debug('Role: '.$role->name);
        $users = User::whereHas("roles", function($q) use ($role){ $q->where('name', $role->name); })->get();
        \Notification::send($users, new RoleUpdated($role));
    }
}
```
AppServiceProvider:
```
<?php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

use App\Role;
use App\Observers\RoleObserver;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Role::observe(RoleObserver::class);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

Permissions.php config file:
```
<?php

return [
    'models' => [
        'permission' => App\Permission::class,
        'role' => App\Role::class,
    ],
    .......................
```

Using the default Role model works like a charm, but no luck when extending it.
Am I missing something? BTW I've cleared the config cache by using `php artisan config:cache`

Thanks in advance

**Comment by drbyte** [comment]
First, it's not cache-related.

In your app, wherever you're triggering the `update`, it seems like it's using the wrong `Role` model.

I just used your sample code above, and the following test ... and it correctly fires the observer (triggering the "notification not found" because I didn't create that):

```php
    /** @test */
    public function the_observer_fires_when_role_is_updated()
    {
        $role = App\Role::create(['name' => 'writer']);
        $role->name = 'writer2';
        $role->save();
    }
```

**Comment by luchorengo** [comment]
This is my controller extract where the update is done. I don't see anything wrong here...

```
<?php

namespace App\Http\Controllers;

use App\Role;

use Illuminate\Http\Request;
use App\Http\Requests\UpdateRole;

class RoleController extends Controller
{
    public function update(UpdateRole $request)
    {
            $role = Role::findOrFail($request->role['id']);
            $role->name = $request->role['name'];
            $role->title = $request->role['title'];
            $role->guard_name = $request->role['guard_name']['name'];
            $role->save();
    }
}
````

**Comment by drbyte** [comment]
Keep in mind that the `update` event is not triggered if the saved data is not actually different from the data already in the model.
Perhaps your code isn't correctly passing through any new changes?

**Comment by luchorengo** [comment]
@drbyte thanks! You saved my day! 
You were completely right, it was working all the time but not triggering because no change was done  :man_facepalming:

Taking advantage of your knowledge, do you know if it's possible to trigger events when role permissions are updated?
In my Role update function, I'm doing something like `$role->syncPermissions($permissions);` but of course, it doesn't impact the Role model itself. Is there any way to do it? I want to avoid to have multiple observers for the same purpose.

**Comment by drbyte** [comment]
@luchorengo You might find the suggestions in #754 or #724 useful for inspiring ways to do that.
