### ISSUE TITLE
assign different permission to same role

### ISSUE THREAD

**Issue by nikulnayi** [spatie/laravel-permission#1222]
I m in a state of development where i ought to assign different permissions to the same role.is there any solution to tackle with it

**Comment by richardkeep** [comment]
You can do this

```
$role = Role::find(1);

$permissions = Permission::all();

foreach($permissions as $permission) {
    $role->givePermissionTo($permission);
}
```

**Comment by nikulnayi** [comment]
we have many users with same role but we want to assign different permissions to each user.
for e.g. 
we have role "admin"  which has assigned to 20 users now we want to give them different permissions

**Comment by richardkeep** [comment]
Then assign different permissions to different users. Read the user guide https://docs.spatie.be/laravel-permission/v3/introduction/

```
$user1->givePermissionTo('do task one');
$user1->givePermissionTo('do task two');

$user2->givePermissionTo('do task two');
$user2->givePermissionTo('do task six');

$user3->givePermissionTo('do task one');
$user3->givePermissionTo('do task six');
```
