### ISSUE TITLE
Testing issues with laravel passport

### ISSUE THREAD

**Issue by Magiczne** [spatie/laravel-permission#1225]
Hi!

I have a controller with middleware setup in the constructor:
```
public function __construct()
{ 
$this->middleware('permission:manage-foo')->only('index');
}
```

And it works good when i consume API from JS frontend. On the other hand I have tests for API, for example one of them could look like that:
```
public function testFoo()
{
  $perm = Permission::create(['name' => 'manage-foo']);
  $role = Role::create(['name' => 'role-foo']);
  $user = factory(User::class)->create();

  $role->givePermissionTo($perm);
  $user->assignRole($role);

  Passport::actingAs($user);

  $this->json('GET', 'api/foo')->assertStatus(200);
}
```

After i run the test i get 403 status code instead of expected 200, but when consuming API everything is ok.

Things I have checked:
1. Assigning permission directly to the user -> _changes nothing, still getting 403_
2. Re-registering permissions as told in [The docs](https://docs.spatie.be/laravel-permission/v3/advanced-usage/unit-testing/#) -> _no changes_
3. Database structure step by step when assigning permissions and roles -> _everything looks fine_

PS. I am migrating from zizaco/entrust to spatie/laravel-permission. When i used entrust all tests were passing, now it's broken.

Thanks for any help.

**Comment by drbyte** [comment]
Looks like you're using different guards for `web` and `api` access, but haven't defined permissions for the other guard.
`v2` and `v3` of this package require either that you define all permissions for all guards, or in all your checks against permissions you specify the one guard for which you've defined your permissions. Same with roles.
A future version of the package "may" drop this, but for now that's what's required.
