### ISSUE TITLE
filter roles

### ISSUE THREAD

**Issue by goldcoders** [spatie/laravel-permission#1226]
i know i can return all roles of the user using with
but i wanna filter a specific list of roles
form example if all roles are ["admin","members","staff"]
i wanna filter only users with ["admin","staff"] roles
is there a query undocumented here that can help me do it
thanks

**Comment by drbyte** [comment]
The `role` scope is available for this. In the `hasRoles` trait, the `scopeRole` method leverages Laravel's convention of offering a scope with lookup capability.

`User::role(['admin', 'staff'])->get();` will give you a list of all users having the `admin` or `staff` role.
