### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by warlord0** [spatie/laravel-permission#123]
Not an issue, but a thought you may want to add into the docs to help us mere mortals :)

I discovered I can use a permission check on the current user simply by doing:
```blade
@if(Gate::check('Asset Read') || Gate::check('Task Read'))
    <p>Something!</p>
@endif
```
Which seemed to simplify things a bit for me. It means I can use more complex and|or in blades, but also outside in controllers as:
```php
if (Gate::check('Asset Read') || Gate::check('Task Read'))
{
    // Some thing
}
```
Thanks for a great addon by the way.

**Comment by freekmurze** [comment]
Hi, I'm glad you like this package 😄 

I'm not going to add this to our readme. I expect that users of the package already have knowledge about Laravels Gate.
