### ISSUE TITLE
How to remove user permission, if permission refers to the role?

### ISSUE THREAD

**Issue by Leopandro** [spatie/laravel-permission#1230]
For example i have manager role, which gives permission "manage_contacts". How to revoke this permission from user?

**Comment by drbyte** [comment]
This package only allows you to **add**, not subtract.

So, if you have a `manager` user who really isn't allowed to be a "full" `manager`, then you need to assign them a lesser role, and then add individual permissions to the user to grant them the extra capabilities they need.
