### ISSUE TITLE
@can Blade Profile table alternative

### ISSUE THREAD

**Issue by coursera-ricardor** [spatie/laravel-permission#1231]
I'm trying to implement this auth schema:
Users->Profile
 Profile->Roles
 Profile->Permissions

Authentication via "Users" table, Authorization via "Profiles" table.

I don't know if it is possible to use the @can searching in the profile model instead of the user or in both models.

My guess is; I missed something in the documentation, by definition the @can works with laravel-permission using the user table and the solution that I implemented works but it is **AWFUL!**

Which documentation do you recommend me to read?

Thanks.

### tests and code
This works, returning an empty array, due the relationships with permissions don't exist.

Controller
```
        dd(auth()->user()->getAllPermissions()); // returns empty
```
This works returning the object with the permissions
```
     dd(auth()->user()->profile->getAllPermissions()); // returns collection with permissions
```

Blade

```
<!-- Authorization Requires Spatie/permissions-->
@can('edit')
	<a href="{{ route( $master_model . '.edit',[$user->id]) }}" class="btn btn-xs btn-info">{{ __('Edit') }}</a>
@endcan
```
@can works returns false - correct behavior due users table doesn't have assigned permissions

```
@if(auth()->user()->profile->can('read')) 
	<a href="{{ route( $master_model . '.edit',[$user->id]) }}" class="btn btn-xs btn-info">{{ __('Edit') }}</a>
@endif
```
This fails, ->can() is not a method implemented

```
@if( in_array('edit',$profilePermissions->toArray()) )
	<a href="{{ route( $master_model . '.edit',[$user->id]) }}" class="btn btn-xs btn-info">{{ __('Edit') }}</a>
@endif
```
This works, passing from the controller the variable with all the permissions via role or direct assignment.

```
@if( in_array('edit', auth()->user()->profile->getAllPermissions()->pluck('name')->toArray() ) )
	<a href="{{ route( $master_model . '.edit',[$user->id]) }}" class="btn btn-xs btn-info">{{ __('Edit') }}</a>
@endif
```
This works

In the users controller:

```
   /**
     * Sync up the list of roles assigned to the Profile
     *
     * @param  Profile  $profile
     * @param  array  $rolesToUpdate
     */
    private function syncRoles(Profile $profileToSync, array $rolesToUpdate = null)
    {
        $profileToSync->roles()->sync($rolesToUpdate);
    }

    /**
     * Sync up the list of permissions assigned to the Profile
     *
     * @param  Profile  $profile
     * @param  array  $rolesToUpdate
     */
    private function syncPermissions(Profile $profileToSync, array $permissionsToUpdate = null)
    {
        $profileToSync->permissions()->sync($permissionsToUpdate);
    }
```

In the roleController

```
   /**
     * Sync up the list of permissions assigned to the Role
     *
     * @param  Role  $role
     * @param  array  $permissionsToUpdate
     */
    private function syncRoles(Role $roleToSync, array $permissionsToUpdate = null)
    {
        $roleToSync->permissions()->sync($permissionsToUpdate);
    }


    /**
     * Save a new role.
     *
     * @param  Rolerequest  $request
     * @return mixed
     */
    private function createRole(Request $request)
    {
        // Creates the role
        $role = Role::create($request->except('permissionsSelected'));

        // Obtrain the Permissions ID to add
        // $permissionIds = $request->input('permissionsSelected');
        // Create the Detail
        // $role->permissions()->attach($permissionIds);
        // $role->permissions()->sync($request->input('permissionIds'));
        if ( !empty($request->input('permissionsSelected'))) {        
            $this->syncRoles($role, $request->input('permissionsSelected'));
        }

        return $role;
    }
```

DB: 

model_has_roles

| role_id | model_type | model_id 
|----|-------------|---
| 12 | App\Profile | 4 
| 11 | App\Profile | 4 
| 10 | App\Profile | 4 

model_has_permissions

| role_id | model_type | model_id |
|----|-------------|---
|8	| App\Profile |	4 |
|16	| App\Profile |	4 |
|3	| App\Profile |	4 |

Profile Model

```
use Illuminate\Database\Eloquent\Model;

// Notifications
// use Illuminate\Notifications\Notifiable;

// Access Control List
use Spatie\Permission\Traits\HasRoles;


class Profile extends Model
{

    /**
     * @todo: Add the Spatie\Permission\Traits\HasRoles trait
    */
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','first_name','last_name','email',
        'status',
        'language_id','language_code','language',
        'country_id','country_code','country','state_id','state_code','state','zip_code',
        'street','street_number','city',
        'latitude','longitude','created_by','updated_by','status',
    ];


    /*
        Get the User associated with the Profile
    */
    public function user() {
        return $this->belongsTo('App\User');
    }
}
```

**Comment by drbyte** [comment]
Why does your `Profile` model have name/address properties as though it's actually a User?

**Comment by coursera-ricardor** [comment]
> Why does your `Profile` model have name/address properties as though it's actually a User?

My Idea is to be able to use php artisan make:auth with the minimal modifications as possible, and maintain all the additional information in the Profile table. 

With this approach, user (as a authentication) could be use to control -> Customers or ->Vendors or Visitor with different Table structures (ACL).

After, maybe it is possible to assign "required" permissions/roles to the "action/process" and avoid hard code the condition and be able to have something like:

```
@canany( App()->Module()->Action->getAllPermissions()....)
or
@if(Auth::user()->hasAnyPermission(App()->Module()->Action->getAllPermissions()....)
```
Which in both cases my guess is an OR condition and the implementation will require an AND condition and have:

```
@canall( App()->Module()->Action->getAllPermissions()....)
or
@if(Auth::user()->hasAllPermission(App()->getAllPermissions()....)
@if(Auth::user()->hasAllPermission(App()->Module()->getAllPermissions()....)
@if(Auth::user()->hasAllPermission(App()->Module()->Action->getAllPermissions()....)
```

With this it is possible to avoid that "someone" by "mistake" change the "permission/role-name" and all the access control gets ruined due:

```
@can('users_manage') <> @can('manage users')
```

**Comment by drbyte** [comment]
> With this it is possible to avoid that "someone" by "mistake" change the "permission/role-name" and all the access control gets ruined due:
> 
> ```
> @can('users_manage') <> @can('manage users')
> ```

I find it's generally better to not let end-users change the names of permissions, since those names are legitimately hard-coded into your app. 
I think the folks at Laravue have made an excellent choice to use Class Constants as Enums in order to create some structure and to abstract away some of risk of naming changes:
https://github.com/tuandm/laravue/blob/1ef8bc9895f37d3c119564808510c373ba762bdc/app/Laravue/Acl.php#L17-L43

**Comment by drbyte** [comment]
> > Why does your `Profile` model have name/address properties as though it's actually a User?
> 
> My Idea is to be able to use php artisan make:auth with the minimal modifications as possible, and maintain all the additional information in the Profile table.

I see. I don't have the full context of the app you're building or the complex problems it's trying to solve, so accept my apologies if the following is going in the wrong direction...
I wonder if you're over-engineering it. Backstory: I used to strive to avoid changing the code generated by `make:auth`, because I didn't understand the auth layer. But after writing more apps and taking the time to understand what `make:auth` creates and why, and understanding how to identify what changes in it between versions, I no longer treat that code as so "fragile". 
That's just part of understanding the underlying framework functionality. It's easy to avoid learning the auth layer until "later". But if it causes you to over-engineer something that doesn't need it, then maybe "later" isn't such a good idea.

(That said, there are still many parts of Laravel's auth layer I'm no expert on! From others I've talked to, I think many people "just trust it", rather than study-to-understand-it. This rapid app-building feature is one of the beautiful traits of Laravel!)

All that said, I'll ask: would you architect it differently if you fully understood all the auth layer, including what `make:auth` generates, and more? Or would you stay on the same path with the extra intermediate Profile model?

**Comment by coursera-ricardor** [comment]
Thank you for your answer. 

I'm new in using Laravel, and all the great implementations that are available to enable the "rapid app-building", but that creates a great risks if those components or implementations are not maintained, and then the effort to update them or replace them could be really complicated and expensive. Spend some time trying to understand them could lead to learn something new. _(**thanks for the help**, I made some progress)_ 

Small changes adding a migration to add the field "description" to Roles and Permissions it is not a big risk, but lazy programming could be.

## Extra information

### Progress based on your recommendations

I changed the definition of the "Profile" Model as Authenticable and I can use in the Policies\ProfilePolicy.php:

```php
 /**
     * Determine whether the user can view the profile.
     *
     * @param  \App\User  $user
     * @param  \App\Profile  $profile
     * @return mixed
     */
    public function view(User $user, Profile $profile)
    {

        return auth()->user()->profile->can('browse')

```

### Call from the Controller

```php
   /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
    $this->authorize('view',[Profile::class,$user->profile]); // Call to the ProfilePolicy.php even if it is not registered in Providers\AuthServiceProvider.php
```
### changes to the Model
```php
namespace App;

// use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

// Notifications
// use Illuminate\Notifications\Notifiable;

// Access Control List
use Spatie\Permission\Traits\HasRoles;

// class Profile extends Model
class Profile extends Authenticatable
{
    // use Notifiable;
    /**
     * @todo: Add the Spatie\Permission\Traits\HasRoles trait
     *
    */
    use HasRoles;
...
```

### Optimizations

Using a @can or extra code in the blade file could like in one of my views, "Why do I need to query the tables every time in the loop? _(auth()->user()->profile->getAllPermissions()->pluck('name')->toArray(). Works, but It is wrong, my fault!):_

```php
		<tbody>
			@foreach ($users as $user)
				<tr data-entry-id="{{ $user->id }}">
....
                        <!--
                            Really annoying validation.
                            @todo: Change the validation to the controller
                        -->
                        @if( auth()->check() && (! is_Null(auth()->user()->profile) ))
                            @if( in_array('edit', auth()->user()->profile->getAllPermissions()->pluck('name')->toArray() ) )
					<a href="{{ route( $master_model . '.edit',[$user->id]) }}" class="btn btn-xs btn-info">{{ __('Edit') }}</a>
                            @endif
                        @endif

```

**Comment by coursera-ricardor** [comment]
From a philosophical point of view, will be the same, now that I discovered that the Gate::class works with any Model extended from Authenticatable as a first parameter:

```php
if( Gate::forUser($user->profile)->allows('test-gate', $user->id))
```
```php
        if( Gate::forUser(auth()->user())->allows('test-gate', $user->id)) {
```

```php
       /*
         * Gate Example using Profile Model
        */
        Gate::define('test-gate', function($model, $record_id) {
            return $model->id === $record_id;
        });

```


> I find it's generally better to not let end-users change the names of permissions, since those names are legitimately hard-coded into your app.
> I think the folks at Laravue have made an excellent choice to use Class Constants as Enums in order to create some structure and to abstract away some of risk of naming changes:
> https://github.com/tuandm/laravue/blob/1ef8bc9895f37d3c119564808510c373ba762bdc/app/Laravue/Acl.php#L17-L43
> 
> <img alt="ACL const laravue" width="601" src="https://user-images.githubusercontent.com/404472/65976243-d63d7280-e43d-11e9-950c-d96a9d68665a.png">

This is the perfect example, you have a beautiful dashboard, with great features, _(I will check how does it work, looks great)_, then you have a small organization who has offices around the world and you need to add more "permissions" or "roles", great, not a problem, and then you add more features not related to the main "package". - Fork and change or follow the instructions: https://doc.laravue.dev/guide/essentials/router-and-nav.html#router

or create something old fashion table like:

| Option | Message  | Route| Rule| Icon | State
| --- | --- |---|---|---|---
| Catalogs | System Operational Catalogs |Menu(['customers','products','vendors',''])|R(['administrator','manager','editor','System Catalogs']) OR P(['customers','products','vendors']) |'fas fa-address-book'|'active'
| Customers | Customers  |/customers|R(['customers'])|'fas fa-address-book'|'active'

Obviously, I don't want to replicate: https://developer.salesforce.com/docs/atlas.en-us.salesforce_record_access_under_the_hood.meta/salesforce_record_access_under_the_hood/uth_examples.htm

Which at the end, it is a simple table relationships model.

**Comment by wensonsmith** [comment]
My solution

`Profile` model:

```php

class Profile extends Model implements AuthorizableContract, AuthenticatableContract
{
      use HasRoles, Authorizable, Authenticatable;
}

```

`User ` model: 

```php
...
public function profile()
{
    return $this->belongsTo(Profile::class);
}

// overwrite can 
public function can($abilities, $arguments = [])
{
       return app(Gate::class)->forUser($this->profile)->check($abilities, $arguments);
}
...
```

now can use `Auth::user()->can()` to check permissions
