### ISSUE TITLE
Unable to call the Policy on Laravel 6

### ISSUE THREAD

**Issue by antweny** [spatie/laravel-permission#1234]
i am unable to check the policy's methods (view,create,delete,read etc) when using policy

This is my UserPolicy file:
```
<?php
namespace App\Policies;
use App\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class UserPolicy
{
    use HandlesAuthorization;

    /**
     * Create a new policy instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Determine whether the user can create new resource.
     */
    public function create(User $user)
    {
        $user->can('user-create');
    }

    /**
     * Determine whether the user can view the resources.
     */
    public function read(User $user)
    {
        return $user->can('user-read');
    }

    /**
     * Determine whether the user can update the question.
     */
    public function update(User $user)
    {
        return $user->can('user-update');
    }

    /**
     * Determine whether the user can delete the question.
     */
    public function delete(User $user)
    {
        return $user->can('user-delete');
    }
   
}
```
and my UserController file:
```
<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(User $user)
    {
        $this->authorize('read',$user);
    }
}
```
If using `$this->authorize('create', $user); ` return false even if the user has the permission

and when i changed to this `$this->authorize('user-create', $user);`  return true

So how can i check the policy first instead of directly checking the permission ?

**Comment by dennis-git** [comment]
you need to add your policy file to app/Providers/AuthServiceProvider.php inside protected $policies = [ User:class => UserPolicy::class ] array

**Comment by antweny** [comment]
So what you are saying laravel 6 can not discover policies automaticaly like previous version 5.8  untill you register??

**Comment by dennis-git** [comment]
it can discover it if it's placed in the right location relative to your model. If it's not, you have to add it to the AuthServiceProvider

**Comment by drbyte** [comment]
@dennis-git is correct. You need to follow Laravel's convention. It's well documented:
https://laravel.com/docs/6.x/authorization#registering-policies

<img width="962" alt="Screen Shot 2019-10-02 at 4 52 23 PM" src="https://user-images.githubusercontent.com/404472/66081010-36fba680-e535-11e9-8368-7f54b7fafbea.png">
