### ISSUE TITLE
How can i use laravel-permission with a single user having polymorfic roles or permission within a system 

### ISSUE THREAD

**Issue by suleodu** [spatie/laravel-permission#1239]
Hello Guyz, Great work on this... I have a peculiar case trying to use this library with my school management system ... I designed the system in such a way that there is a database table to store  **institution** another table for **sub_schools** withing the **institution** the user table store record of all user in the institution the user table has an extended table for student  and staff ... my case now is staff can be in multiple sub_school  and have different roles and permission withing those schools i.e a staff can have permission to edit student result in school 1 and does not have permission to edit student results in school 2 ...

How can I still use the spatie/laravel-permission to handle my roles and permission in this kind of scenario

**Comment by drbyte** [comment]
Hi, you may find the discussion by @liamoreilly and others in #1135 to be helpful in your scenario.
