### ISSUE TITLE
Not Logged In exception with Ajax

### ISSUE THREAD

**Issue by nanaaikinson24** [spatie/laravel-permission#1241]
Hello. I am using this package with laravel and building an SPA alongside. I am using a custom authentication with firebase/jwt. When i use the provided middleware, it throws the exception of not logged in

**Comment by drbyte** [comment]
This package provides **authorization** features.

Your "not logged in" issues relate to doing **authorization** in your Laravel app. You may find help for building your authorization code on sites like the Laracasts forums at https://laracasts.com or https://laravel.io

**Comment by nanaaikinson24** [comment]
> This package provides **authorization** features.
> 
> Your "not logged in" issues relate to doing **authorization** in your Laravel app. You may find help for building your authorization code on sites like the Laracasts forums at https://laracasts.com or https://laravel.io

I am not using laravel's authentication system. 

`// Validation passes
			$user = User::where("email", (string) $request->email)->first();
			if ($user) {
				// Check for user password
				if (Hash::check($request->password, $user->password)) {
					if ($user->status == ST_ACTIVE) {
						// Get user permissions
						$userPermissions = [];
						if ($user->designation) {
							$permissions = Role::findByName($user->designation)->permissions;
							if ($permissions) {
								foreach ($permissions as $key => $perm) {
									$userPermissions[] = $perm->name;
								}
							}
						}

						// JWT Payload
						$payload = [
							"iss" => url(),
							"iat" => time(),
							"exp" => WEBSITE_JWT_LIFESPAN,
							"id" => $user->id,
							"permissions" => $userPermissions
						];

						$token = JWT::encode($payload, env("APP_KEY", "JesusIsAlive"));

						$data = [
							"username" => $user->username,
							"name" => $user->first_name . " " . $user->last_name,
							"token" => $token,
							"permissions" => $userPermissions
						];
						return $this->successResponse("", $data);
					}
					$message = "Your account inactive. Kindly contact your administrator concerning your account";
					return $this->errorResponse($message);
				}
				return $this->errorResponse("Incorrect email or password");
			}
			return $this->errorResponse("Incorrect email or password");`
This is my code for auth. And because of this, i can access the $user->getPermissionNames()

**Comment by drbyte** [comment]
This package only works with logged-in users. You cannot check permissions for a user which is not logged in.
The middleware will trigger `UnauthorizedException` with a message of "not logged in" if your user is not according to Laravel's Authentication layer:
https://github.com/spatie/laravel-permission/blob/37aeaf4e75d26b5b588a60f081dfbcc687260339/src/Middlewares/PermissionMiddleware.php#L12-L14

You will need to either make your app compatible with Laravel's Authentication layer so that the User is not seen as only a not-logged-in guest, or you'll need to extend/rewrite the middleware to determine the authenticated user a different way, or just skip the middleware altogether and write all the middleware protections into your application code.

**Comment by nanaaikinson24** [comment]
> This package only works with logged-in users. You cannot check permissions for a user which is not logged in.
> The middleware will trigger `UnauthorizedException` with a message of "not logged in" if your user is not according to Laravel's Authentication layer:
> https://github.com/spatie/laravel-permission/blob/37aeaf4e75d26b5b588a60f081dfbcc687260339/src/Middlewares/PermissionMiddleware.php#L12-L14
> 
> You will need to either make your app compatible with Laravel's Authentication layer so that the User is not seen as only a not-logged-in guest, or you'll need to extend/rewrite the middleware to determine the authenticated user a different way, or just skip the middleware altogether and write all the middleware protections into your application code.

Thanks for the help. Will write or extend the middleware to suit the app.
