### ISSUE TITLE
Error checking permissions

### ISSUE THREAD

**Issue by PlaidFoxSG** [spatie/laravel-permission#1244]
` return $this->permissions->contains('id', $permission->id);` on line 258 of HasPermissions.php
`Call to a member function contains() `

My Admin model uses HasRoles and has `protected $guard_name = 'admin';`

The model_has_permissions table has:
6 | App\Models\Admin | 4 

The role_has_permissions has:
6 | 1
5 | 2

The permissions has:
5 | crm-finance-update | admin
6 | order-delete | admin

The roles has:
1 | Admin | admin
2 | Account Manager | admin

No idea what I'm missing and why this isn't working.  If I don't check permissions, I can run `$admin->syncPermissions(['order-delete']);`

I can check permissions against a permission value that doesn't exist, like 
`$admin->hasPermissionTo('blah')` and it works fine.

but if I do:
`$admin->hasPermissionTo('order-delete')`, I get the above error.

For reference, config/auth.php has:
```php
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
        'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ]
    ]`
`'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
        'admins' => [
            'driver' => 'eloquent',
            'model' => Admin::class,
        ],
        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

**Comment by drbyte** [comment]
Does it make a difference if you first lookup the actual Permission model and pass that to `hasPermissionTo` instead of the permission name?

Does the same problem occur on your User model, with a permission that exists for that model?

Does it make a difference if you reorder your guards in the auth.php config file to put admin first, even if just as a temporary test?

Also, is the config you quoted really using Admin::class instead of your fully qualified class name?
Perhaps you've imported it in the top of the file and that's just not quoted here, but it stands out as inconsistent.

**Comment by PlaidFoxSG** [comment]
1) yes, still happens when I pass the permission model
2) The User model doesn't require permissions
3) reordering the guards didn't do anything
4) yes, it's imported.  PHPStorm automatically cleans up newly added stuff. 

I don't see any database queries to the `model_has_permissions` table in the debugging.  Not sure at which point this should be called.

**Comment by PlaidFoxSG** [comment]
Not sure what else to look at ... checking `dd($this->permissions)` returns `null`.

**Comment by PlaidFoxSG** [comment]
`dd(Auth::guard('admin')->user()->permissions);` also returns `null`

**Comment by drbyte** [comment]
If `$this->permissions` is returning null, then that means the model it's in has no permissions assigned to it. 
The data you posted above shows only Admin id 4 having access to permission 6. Are you actually testing in admin user 4?

How have you created these permissions and roles? Did you use the methods provided by this package? Or did you write your own code to inject things into the database directly thus bypassing the cache resets?

It would help if I could see the actual app. Or a fresh Laravel app with "only" the code that recreates this problem. Can you recreate the problem on a new Laravel app?

**Comment by PlaidFoxSG** [comment]
yup.  Even if I was testing another Admin, it shouldn't break when running `hasPermissionTo()` ... it should return false.

I used ` $admin->syncPermissions(['order-delete']);` to add the permissions.

**Comment by PlaidFoxSG** [comment]
I'm a dummy ... I created a repo with all the code and then started creating the database dump ... I was going to implement permissions a different way, so I created a table column called "permissions" ... deleted the column and all is well.  Thank you for your help ... would never have figured it out if I didn't go through this whole process.

**Comment by drbyte** [comment]
I agree - recreating in another app often exposes our error. Or else proves where it really is!
