### ISSUE TITLE
func hasRoleNames maybe need ()

### ISSUE THREAD

**Issue by Enoliu** [spatie/laravel-permission#1246]
Spatie\Permission\Traits\HasRoles， line:258

public function getRoleNames(): Collection
    {
        return $this->roles->pluck('name');
    }

should be 
public function getRoleNames(): Collection
    {
        return $this->roles()->pluck('name');
    }
?

**Comment by drbyte** [comment]
No, `roles` is an Eloquent relationship. Accessing it via the property (not the function) gives the resolved values.
See https://laravel.com/docs/master/eloquent-relationships#many-to-many
