### ISSUE TITLE
Migration errors after removing this package

### ISSUE THREAD

**Issue by riddla** [spatie/laravel-permission#1247]
(Maybe this is more of a best practice question than a real issue ...)

A colleague of mine introduced this package in a recent Laravel project. I was trying to remove it via composer (and mentions of `PermissionServiceProvider` etc.).
Afterwards I encountered an error when I was setting up a new server/environment that tried to do a `migrate:fresh`. As the migration referred to (deleted) config values it threw an error.

Is it good practice to just delete the generated migration file? And write a migration that removes the now obsolete tables (if they exist)?

**Comment by drbyte** [comment]
Yes, standard Laravel best practice regarding migrations is to first create a new one to undo the additions of the first one. That way you clean up existing databases.
Then you can later optionally go in to the old related migration files and remove/comment-out the code in the `up` method.
Once you've run those migrations on all affected environments/installs, and the related tables are removed, you could explore whether to delete those migration entries from the `migrations` table in your database/s.

**Comment by riddla** [comment]
@drbyte, Thanks for the insights. That makes sense :)
