### ISSUE TITLE
Force roles by name

### ISSUE THREAD

**Issue by RPSimon** [spatie/laravel-permission#1251]
Hi,

I'm working on an application who is using an JWT token to login. In this token, there is a claim that contains the roles for this user.

Would it be possible to force the roles for this user in the middleware? Because there is almost no information about the user in the my database. If possible, I would like to keep to connection between the user and the roles only in the JWT Token.

At the moment this is what I got in the token.

```
{#273
  ...
  +"roles": array:1 [
    0 => "writer"
  ]
  ...
}
```

But I would like to force in a middleware layer that the request this 'token' is sending has the "writer" role.

Thanks!

**Comment by drbyte** [comment]
Why not just apply the `role:writer` middleware to the route you're trying to access? 
https://docs.spatie.be/laravel-permission/v3/basic-usage/middleware/

That would then identify the route, fire the middleware, lookup the link between the requested role and the specified user id, and return pass/fail.
