### ISSUE TITLE
Uuid not working

### ISSUE THREAD

**Issue by LucasTeodoro** [spatie/laravel-permission#1260]
Illuminate\Database\QueryException  : SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: uuid = integer
LINE 1: ...les"."role_id" where "model_has_roles"."model_id" in (7) and...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select "roles".*, "model_has_roles"."model_id" as "pivot_model_id", "model_has_roles"."role_id" as "pivot_role_id", "model_has_roles"."model_type" as "pivot_model_type" from "roles" inner join "model_has_roles" on "roles"."id" = "model_has_roles"."role_id" where "model_has_roles"."model_id" in (7) and "model_has_roles"."model_type" = App\Models\System\User)

**Comment by sergiz** [comment]
Did you do appropriate modifications (migrations and configuration) to actually make it working?

Here are some ideas
https://github.com/spatie/laravel-permission/issues/948

**Comment by LucasTeodoro** [comment]
Yes i made.  

I found a solution by declaring 
protected $keyType = "string";

**Comment by sergiz** [comment]
So your issue was not even realted to this package, but to Laravel in general.
