### ISSUE TITLE
Session is not getting generated due to config/permissions.php

### ISSUE THREAD

**Issue by saikat62300** [spatie/laravel-permission#1263]
I'm facing a weird kind of scenario where the session is not getting generated. I removed the config/permission.php and it started working. Can you please help me what is causing this? I'm checking this in the local system(windows) and it is working fine and on the server(Linux), it is having this issue.

**Comment by drbyte** [comment]
Sounds like maybe a PHP syntax error in your file? Maybe an incorrectly named class/namespace?

Perhaps the server's PHP logs may show details about the error?

What's the PHP version in both local and server?

**Comment by saikat62300** [comment]
Thanks for your reply.

I did not change anything in permission.php. it is autogenerated during this package installation.

Perhaps the server's PHP logs may show details about the error?
-- Not generating any error and  laravel error reporting is turned on already.

I'm using Laravel 6. PHP version 7.3.9 in my local system and 7.2.23 in my server.

**Comment by drbyte** [comment]
I can't see anything in this package that would cause the situation you mention.
It's working fine on many Linux servers.

It feels like something wrong with your app settings or your server configs (perhaps .env or laravel session config settings)
