### ISSUE TITLE
hasPermissionTo don't accept array what should i do?

### ISSUE THREAD

**Issue by Piturong-c** [spatie/laravel-permission#1264]
![image](https://user-images.githubusercontent.com/55744727/67691386-135f3b00-f9d1-11e9-8cf2-83af8e0d8f13.png)
hasPermissionTo didn't accept my $row from User table It's only happened when It's converted to array in Controller@index I have to do it because i use it to display table but It didn't work when come to Spatie method what should i do? 
I want to generate a button in each row in my table that depend on user's level

my idea is to send $row['id'] to my brand new function in Controller that use row's id to convert back to data by using User::find($id) then return back to table to create each button
but the problem It's i don't know how to call function and It's need to happened in for loop I search a lot like @php can call but It's doesn't work with @if and @foreach or i just too stupid nothing work I'm so hopeless.

**Comment by atymic** [comment]
You should be looping over a collection of user objects, not the results of a raw query.

For example, when looping over `User::all()` you'll be able to use `hasPermissionTo` on the objects in the collection.

Can you post your controller code?
