### ISSUE TITLE
Guard.php -> getDefaultName() will always pick the web guard.

### ISSUE THREAD

**Issue by nitin-aika** [spatie/laravel-permission#1265]
I have set default guard to api but when I am trying to access it from middleware it is always fetching the web guard. 

**config/auth.php**

```
'defaults' => [
   'guard' => 'api',
   'passwords' => 'users',
],
```
When I read the source code, I found issue in line:45. Here is the reference link
https://github.com/spatie/laravel-permission/blob/master/src/Guard.php#L45. It will always return web guard because it's in the first position. 

```
 public static function getDefaultName($class): string
    {
        $default = config('auth.defaults.guard');
        return static::getNames($class)->first() ?: $default;
    }
```
If I set _**api**_ array to first position then it works (**config/auth.php**)
```
'guards' => [
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
       'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],
```

**Comment by drbyte** [comment]
Yes. Changing that will be a breaking change. It's being considered for a future version.

In the meantime, you can set it in the config file, as you mentioned.
Alternatively, while it may not suit all situations, per https://github.com/spatie/laravel-permission/blob/e3821559c69b2b1ea8fdd967fa89ba13a01ead78/src/Guard.php#L17-L25 you can set the `guard_name` property on the User model.

**Comment by nitin-aika** [comment]
Thanks for the update @drbyte

**Comment by Ir00man** [comment]
Just wanna say that current behavior when `config('auth.defaults.guard')` has lower priority than first-defined item in guards array looks crazy for me. 
Because when you have auth middleware in routes, like:
```
Route::group(['middleware' => 'auth:api'], function () {
...
}
```
`config('auth.defaults.guard')` will be overridden on **api**.
And actually I was waiting that this package will respect that, but nope.

Swapping items in config array... who've ever decided that an order (in array) is so important?

**Comment by drbyte** [comment]
@Ir00man a PR respecting the user's guard would be welcome. Ideally with tests.

**Comment by Ir00man** [comment]
@drbyte Are you agree that current behavior should be fixed?

**Comment by drbyte** [comment]
@Ir00man wrote:
> @drbyte Are you agree that current behavior should be fixed?

Yes and no. I would like to see it changed ("fixed" as you call it), but I'm aware that it's a breaking change for very many apps which have been coded to work with the current behavior. (Granted, most of those affected will probably be grateful to remove their "workaround" code.)

So, yes, I'd entertain a tested PR which more intuitively respects the user's active guard.
