### ISSUE TITLE
users by role in controller issue

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-permission#1270]
I am trying to provide different panel options to different type of users and for that i am getting users roles in controller but the issue is it always return first statement!

#example

```php
$user = Auth::user();

if($user->role('distributor'))
{
  $company = CompanyData::where('user_id', $user->id)->first();
  return view('admin.panel', compact('customers', 'staffs', 'distributors', 'dropshippers', 'company'));
} elseif ($user->role('dropshipper'))
{
  $dropshipper = User::where('id', $user->id)->first();
  return view('admin.panel', compact('customers', 'staffs', 'distributors', 'dropshippers', 'dropshipper'));
}
else
{
  return view('admin.panel', compact('customers', 'staffs', 'distributors', 'dropshippers'));
}
```

with code above i'm always getting this part `if($user->role('distributor'))` when i login as `dropshipper` i do not get `$dropshipper` data instead still getting `$company` data.

**Any idea?**

**Comment by drbyte** [comment]
Instead of `$user->role('foo')` (which is a Query Scope), use `$user->hasRole('foo')` (which tests for the named role)
