### ISSUE TITLE
Role name problem

### ISSUE THREAD

**Issue by adeguntoro** [spatie/laravel-permission#1272]
```
"laravel/framework": "5.8.*",
"spatie/laravel-permission": "^2.37",
"laravelcollective/html": "^5.8.0"
```
This is my Role name :
1. User
2. Admin
3. Super_admin

I can update / create permission for each role, but why i can't update / create permission for role  with "Super_admin" name ?
Does spatie have rule about Role name ? like it should be no character.
My current controller 

    public function update(Request $request, $id) {
        $role = Role::findOrFail($id); //Get role with the given id
        $this->validate($request, [
            'name'=>'required|max:10|unique:roles,name,'.$id,
            'permissions' =>'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
        $role->fill($input)->save();

        $p_all = Permission::all();//Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return json_encode([$request->name, $request->permissions]);
    }

```
<div class='container'>
    <h1><i class='fa fa-key'></i> Edit Role: {{$role->name}}</h1>
    <hr>
    {{ Form::model($role, array('route' => array('role.update', $role->id), 'method' => 'PUT')) }}
    <div class="form-group">
        {{ Form::label('name', 'Role Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
    </div>
    <h5><b>Assign Permissions</b></h5>
    @foreach ($permissions as $permission)
        {{Form::checkbox('permissions[]',  $permission->id, $role->permissions ) }}
        {{Form::label($permission->name, ucfirst($permission->name)) }}<br>
    @endforeach
    <br>
    {{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}
    {{ Form::close() }}    
</div>
```

**Comment by drbyte** [comment]
Your validation rule says: `max:10` ... but `Super_admin` is 11 characters.
