### ISSUE TITLE
mongo support

### ISSUE THREAD

**Issue by jampzo** [spatie/laravel-permission#1273]
when's gonna be release an official mongo support repository? PLS

**Comment by drbyte** [comment]
Hi @jampzo 
There are no plans to do something specific for Mongo. (And I'm certainly not an expert on Mongo.)

However, this package uses Eloquent everywhere, so a solid Mongo package that implements all of Eloquent should give you most of what you need. I know there are a few Eloquent-Mongo packages out there. Not sure which would suit your need best though.

**Comment by jampzo** [comment]
:( Thanks. Yes I found a fews but they're already deprecated or without laravel 6 support.

**Comment by kristremblay** [comment]
@jampzo https://github.com/jenssegers/laravel-mongodb does not meet your needs?

**Comment by jampzo** [comment]
> @jampzo https://github.com/jenssegers/laravel-mongodb does not meet your needs?

Yes, of course. I'm working with it. Thanks

**Comment by marooj** [comment]
yes i am have this problem 
there is a package for work with mongo 
https://github.com/mostafamaklad/laravel-permission-mongodb/

i am know that have  problem with laravel 6.x
please add mongodb usage

**Comment by mstaack** [comment]
@jampzo how has your experience been so far with `laravel-mongodb` and this package?

**Comment by mostafamaklad** [comment]
you could use this package [laravel-permission-mongodb](https://github.com/mostafamaklad/laravel-permission-mongodb/) if you are using [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) package.
