### ISSUE TITLE
app is slow after updating package from 2.34 to 2.35

### ISSUE THREAD

**Issue by SanChes-tanker** [spatie/laravel-permission#1276]
Recently I have updated laravel to 6.0 and spatie/laravel-permission package to 3.2 version. And found out that permissions starts working very slow.
If it's more than 50 permission and 2 roles for them it could even fail by execution time error within 30 secons.
So I started to test it only with 4 permission and 1 role.
They process for 3500ms on average (that's not a good result for 4 perm).
I tried to change cache driver, no matter it is file or redis. Works the same.
So I started to downgrade package step by step throug the releses list and found out that on version 2.34 it works fine, same 4 permissions process only for 250ms (that's 14 times faster).
When I upgraded to 2.35 the issue backed to 3500ms.

So I think the problem somewhere in 2.35 release. Can you help me? It becames very critical for my project and I can't back to 2.34 because I've updated laravel as well

**Comment by SanChes-tanker** [comment]
I don't think it could be related to slow queries, but I have suspicion about how cache works, I debugged it with laravel telescope so here are screenshots that could help you:
https://prnt.sc/ptni4e
https://prnt.sc/ptndp5
https://prnt.sc/ptndzf

**Comment by bcorcoran** [comment]
@SanChes-tanker did you switch to facade/ignition? I found that the new error page package causes me a TON of issues and it's basically a bad idea if you need performance out of your app. It's very pretty but very erm, slow 😉.

If you did, I would try switching back to filp/whoops and see if that helps.

**Comment by dennis-git** [comment]
disable your XDEBUG, it will be 10-100x faster

**Comment by SanChes-tanker** [comment]
@bcorcoran no, I didn't use facade/ignition. If you'd ask about laravel/telescope it also always disabled

**Comment by SanChes-tanker** [comment]
@dennis-git thanks for advise. it has helped a bit. but not enough, because when I try to give 50 permissions to role it takes about 15 sec.
by the way, it works very fast on 2.34 release even with XDEBUG.

**Comment by dennis-git** [comment]
make sure you turn off XDEBUG and then restart PHP and your server. You should see 10x-100x speed jump.

**Comment by SanChes-tanker** [comment]
@dennis-git yes, I'm sure. I see result, now it works faster about 4 times than it was. But still very slow where I create a few roles and about 50 permissions per one request. And as I said above on 2.34 it's fine and super fast

**Comment by dennis-git** [comment]
Try to attach Roles to permissions, not permissions to Roles

**Comment by dennis-git** [comment]
/*
             * Important Note from DZ
             *
             * Do not use $role->hasPermissionTo() and $role->givePermissionTo():
             * they are 2x-3x slower than $permission->hasRole() and $permission->assignRole()
             */
            if (!$permissionObj->hasRole($role)) {
                $permissionObj->assignRole($role);
            }

**Comment by SanChes-tanker** [comment]
@dennis-git thanks for suggest but I can't change the code of app. I need real help from this package authors to understand what caused this issue and maybe find a solution in next update.

**Comment by drbyte** [comment]
I've tried to create an app with performance problems with "50 permissions and 2 roles".
But I'm not experiencing the slowness you mention.
Seeing your application code would make for easier troubleshooting or problem re-creation.

Later you mentioned "creating 50 permissions per one request". What's the workflow here?

**Comment by SanChes-tanker** [comment]
@drbyte 
First of all I'd like to mention what I have i my db(maybe it will help you to experiencing the slowness).
In 'roles' table I have 171 records
In 'model_has_roles' I have 71 records
In 'permissions' I have 1982 records
In 'role_has_permissions' I have 2397 records

Here is the workflow:
`
// factory returns a simple array with default permissions name
foreach ($this->permissionFactory->getDefaultPermissions() as $permissionValue) {
    $permissionName = $permissionValue . '-' . $organization_id;
    if (!Permission::where('name', $permissionName)->first()) {
        Permission::create([
            'name' => $permissionName,
            'guard_name' => 'api'
        ]);
    }
    $organizationRole->givePermissionTo($permissionName);
}

// factory returns multidimensional array with strings ( names of default roles and permissins ), there are 2 roles and about 50 permissions
foreach ($this->permissionFactory->getDefaultRolesWithTheirPermissions() as $roleName => $permissionsArray) {
    $permissionForAssign = [];
    foreach ($permissionsArray as $permissionValue) {
        $permissionName = $permissionValue . '-' . $organization_id;
        $permissionForAssign[] = $permissionName;
    }

    $customRole = Role::create(['name' => $roleName . ' role for organization ' . $organization_id, 'guard_name' => 'api']);
    $customRole->syncPermissions($permissionForAssign);
}
`

Right now, query with this code takes 14 secons for me, but if I downgrade laravel to 5.7 and spatie/laravel-permission to 2.34 it take 2.3 secons

**Comment by SanChes-tanker** [comment]
@drbyte have some ideas? The discussion is stopped, but I hope the work in process with my issue?

**Comment by ChrisTurk** [comment]
> ```
>         /*
>          * Important Note from DZ
>          *
>          * Do not use $role->hasPermissionTo() and $role->givePermissionTo():
>          * they are 2x-3x slower than $permission->hasRole() and $permission->assignRole()
>          */
>         if (!$permissionObj->hasRole($role)) {
>             $permissionObj->assignRole($role);
>         }
> ```

Would it be a good idea to update some of the documentation/examples to indicate this? Had I never clicked onto issues I'd have no clue since  [docs/introduction.md](https://github.com/spatie/laravel-permission/blob/master/docs/introduction.md) uses the $role->givePermissionTo() and so does the [Seeder example](https://github.com/drbyte/spatie-permissions-demo/blob/3386743149d08d3bf58d0aa272c9c44923301ca9/database/seeds/PermissionsDemoSeeder.php#L28)

I'll happily do it if it's worth it just not sure why it's displayed as it is by default. Was looking into using the package and came across this.

**Comment by dennis-git** [comment]
> > ```
> >         /*
> >          * Important Note from DZ
> >          *
> >          * Do not use $role->hasPermissionTo() and $role->givePermissionTo():
> >          * they are 2x-3x slower than $permission->hasRole() and $permission->assignRole()
> >          */
> >         if (!$permissionObj->hasRole($role)) {
> >             $permissionObj->assignRole($role);
> >         }
> > ```
> 
> Would it be a good idea to update some of the documentation/examples to indicate this? Had I never clicked onto issues I'd have no clue since [docs/introduction.md](https://github.com/spatie/laravel-permission/blob/master/docs/introduction.md) uses the $role->givePermissionTo() and so does the [Seeder example](https://github.com/drbyte/spatie-permissions-demo/blob/3386743149d08d3bf58d0aa272c9c44923301ca9/database/seeds/PermissionsDemoSeeder.php#L28)
> 
> I'll happily do it if it's worth it just not sure why it's displayed as it is by default. Was looking into using the package and came across this.

please do

**Comment by SanChes-tanker** [comment]
Hi.
I have managed this issue by two steps:
1. As suggested earlier, I changed all `givePermissionTo()` and `syncPermissions()` to `$permission->assignRole($role);` method.
2. I changed 
```
Permission::create([
                'name' => $permissionName,
                'guard_name' => 'api'
            ]);
```
to just 
```
$permission = Permission::make([
                'name' => $permissionName,
                'guard_name' => 'api'
            ]);
            $permission->saveOrFail();
```


These two steps has increased speed about 20 times. I hope it help to somebody.

**Comment by drbyte** [comment]
A Performance section was added to the docs.

**Comment by drbyte** [comment]
A Performance section was added to the docs.

Thanks for sharing your insights!
