### ISSUE TITLE
Install steps getting Column not found: 1054 Unknown column 'roles' in 'field list'

### ISSUE THREAD

**Issue by markaduffy** [spatie/laravel-permission#1280]
Column not found: 1054 Unknown column 'roles' in 'field list'

I had an old roles and permissions table. I dropped them during migration.  Ran it again after dropping these old tables and get above error. Tried rolling back migration.

Laravel 6.0
spatie/laravel-permission 3.2
vyuldashev/nova-permission 2.2

**Comment by lmatab** [comment]
I have the same problema, how did you solve it? @markaduffy

**Comment by drbyte** [comment]
@lmatab please explain more. It sounds like you haven't published and run the migrations for the package.

**Comment by lmatab** [comment]
Thanks was exactly the problem @drbyte !, thanks a lot for the fast feedback.

If anybody is having the same problem, you just need to : 

php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"


php artisan migrate

**Comment by drbyte** [comment]
Adding the documentation link here for quick reference:
https://docs.spatie.be/laravel-permission/v3/installation-laravel/
