### ISSUE TITLE
Switch Between Roles of Multiple Roles User

### ISSUE THREAD

**Issue by wdebusschere** [spatie/laravel-permission#1282]
We have 4 roles: Role1,Role2,Role3,Role4.  
Each roles has its own dashboard.  
Some users have multiple roles.

What would be the best approach to let a user switch between his roles = set a role as the active role.

**Comment by drbyte** [comment]
This is something you'd do at your application level. 
Probably something as simple as setting an internal variable to say which role is currently "active".
That could be a property on your User object, or maybe a Session variable. Whatever suits your needs best.

**Comment by Dredas** [comment]
Hi, I have two options to log in to the same user - with a regular password and with a simple pin. I want to restrict the user who connects by the pin so he can't do a bunch of things. What would be the best solution?
