### ISSUE TITLE
How can i have departments on top of roles, so that each departments can have & manage their own set of roles.

### ISSUE THREAD

**Issue by shahilnissam** [spatie/laravel-permission#1283]
How can i have departments on top of roles, so that each departments will have their own set of roles.
Please assist me to tweak the library for this functionality.

**Comment by drbyte** [comment]
One person I talked to said they did something like set up separate Eloquent models for each department and created their own set of db relations between each dept and role. I haven't seen their code though. That's one approach to consider.

There are some related discussions in #682, #382, and #440 which might give you some other ways to think of it.

**Comment by ultrono** [comment]
There no need to tweak this package as your use case is very specific.

I did something very similar and tried to keep things simple. I created a naming convention for the actual permissions i.e. `department-123-destroy`, `department-123-view` etc. 

The UI displayed filtered permissions based upon the desired department level. When saving, I filtered the permission by title before applying the permission.

This way I kept the structure of this package intact and made no datbase changes.
