### ISSUE TITLE
Error Array to string conversion during Role in syncPermission with array

### ISSUE THREAD

**Issue by ekoilkom** [spatie/laravel-permission#1285]
i have error in my code. Array to string conversion after syncPermission($data)
My $data["1","2","3"] id of permissions

**Comment by drbyte** [comment]
Yes, it seems like you have an error in your code.

Without seeing the complete error message it's difficult to offer any assistance. Even better if you show your code.

Also, why are you passing strings like `$data["1","2","3"]` instead of just `$data[1,2,3]`?
