### ISSUE TITLE
Call to undefined method App\Models\User::can() in Lumen 5.8

### ISSUE THREAD

**Issue by giorgifti** [spatie/laravel-permission#1287]
Hello, I am using this package and I have noticed that when registering permissions in route middleware it throws error as following:
```
BadMethodCallException: Call to undefined method App\Models\User::can()
```

It's stated in the docs but I guess this is not correct for me:

> Because all permissions will be registered on Laravel’s gate, you can check if a user has a permission with Laravel’s default can function:

> $user->can('edit articles');

I am using Lumen 5.8 and PHP 7.3

Any ideas what might be wrong or any possible solutions?

Thanks.

**Comment by dennis-git** [comment]
are you calling ::can() statically and not of the user instance?

**Comment by giorgifti** [comment]
> are you calling ::can() statically and not on the user instance?

Thanks for reply. It's called by middelware on the user instance as written in the `PermissionMiddleware`:
```php
class PermissionMiddleware
{
    public function handle($request, Closure $next, $permission)
    {
        if (app('auth')->guest()) {
            throw UnauthorizedException::notLoggedIn();
        }

        $permissions = is_array($permission)
            ? $permission
            : explode('|', $permission);

        foreach ($permissions as $permission) {
            if (app('auth')->user()->can($permission)) {
                return $next($request);
            }
        }

        throw UnauthorizedException::forPermissions($permissions);
    }
}
```

Finally I figured it out, and the problem was my User model, which in Lumen turns out that it requires Authorizable contract, so I implemented:

-  `Illuminate\Contracts\Auth\Access\Authorizable` 
-  and then used the trait: `Laravel\Lumen\Auth\Authorizable;`.

These steps resolved the issue.

**Comment by drbyte** [comment]
> the problem was my User model, which in Lumen turns out that it requires Authorizable contract

Yes, the `Authorizable` contract is necessary to enable Laravel's authorization layer.

**Comment by richoandika** [comment]
Can we calling using Auth::user()->can(); ?
