### ISSUE TITLE
UnauthorizedException when performing AJAX call.

### ISSUE THREAD

**Issue by DivyaRigel** [spatie/laravel-permission#1289]
-> Suppose we are passing the permission middleware into the constructor like the below example.

     public function __construct()
     {
         $this->middleware('permission:invoicing delete', ['only' => ['destroy']]);
     }

-> When we call **destroy** method via ajax and users have no permission to perform this action, that time it will occur exception.

Exception:
exception: "Spatie\Permission\Exceptions\UnauthorizedException"
file: "C:\xampp\htdocs\XN360-Prod\vendor\spatie\laravel-permission\src\Exceptions\UnauthorizedException.php"
line: 37
message: "User does not have the right permissions."

**Comment by drbyte** [comment]
> message: "User does not have the right permissions."

For troubleshooting I recommend temporarily editing your `config/permissions.php` to turn on the exception reporting setting, so that the exception explains which permission was expected.

Are you using multiple guards in your application? Have you specified the guard_name property in this model?
