### ISSUE TITLE
Missing argument 4 for App\Http\Middleware\RoleMiddleware::handle()

### ISSUE THREAD

**Issue by azorpax** [spatie/laravel-permission#129]
Missing argument 4 for App\Http\Middleware\RoleMiddleware::handle()

**Comment by ChiefScript** [comment]
Did you get a solution to the error? I'm facing it right now

**Comment by azorpax** [comment]
try to adding default parameter value.
public function handle($request, Closure $next, $role, $permission = '')

**Comment by drbyte** [comment]
Or something akin to this may help if you're also considering supporting multiple optional roles, and allowing to specify a string of "null" for permissions that can be unspecified: https://github.com/spatie/laravel-permission/pull/120/files

**Comment by mojoblanco** [comment]
I tried using an empty string as a default parameter value as suggested by @azorpax  and it seems to be working
