### ISSUE TITLE
@can blade with guard name not working

### ISSUE THREAD

**Issue by AhmedHdeawy** [spatie/laravel-permission#1290]
Hi, thanks for this awesome package,

i have a problem that is:

i have multiple guards [ 'web', 'admin' ]

in Admin Model i have 
`protected $guard_name = 'admin';`

and i have guard name for each permission in
> permissions table

like the image below 
![p](https://user-images.githubusercontent.com/15928500/69720519-78669780-111b-11ea-8a1d-148146662e5f.png)

the problem is when use @can directive like: 
`@can('admin.users.view')`
it doesn't work, not show the code that in it, even if this admin is Super Admin or Admin

also when use 
`@can('admin.users.view', 'admin')`
it doesn't work also

but when use 
`@if(auth('admin')->user()->can('admin.users.view'))`
it works fine

how i can use @can only because is simple for code.

thanks in advance

**Comment by sameervirus** [comment]
+1

**Comment by drbyte** [comment]
You cannot pass the guard to `@can`. You must use the method you described, or maybe `hasPermissionTo`.

**Comment by malickateeq** [comment]
Anyone solved this issue?

**Comment by drbyte** [comment]
Nothing to "solve". It's operating by design.

**Comment by itsaxay** [comment]
@AhmedHdeawy, You can create own blade directive like

```
        Blade::directive('canhas', function ($permission, $guard = "admin") {
            return "<?php if (auth()->user()->hasPermissionTo({$permission} , \"{$guard}\")) { ?>";
        });
        Blade::directive('endcanhas', function () {
            return '<?php } ?>';
        });
```

**Comment by MD-Khalid-Hosain** [comment]
Solved my problem... Thank you bro @AhmedHdeawy AhmedHdeawy

**Comment by jishujian** [comment]
why can't create own blade directive just like @can('','','')

**Comment by Lukmauu** [comment]
@auth('admin')

Works fine if you admin guard set in your config/auth.php

**Comment by axlwild** [comment]
Given this problem, I've created [a PR](https://github.com/spatie/laravel-permission/pull/2515) to be able to use another blade directive in this case, a little bit more confortable than the whole `@if(auth('admin')->user()->can('admin.users.view'))` sentence.

With this change, you can use the following directive
```
@haspermissionto('admin.users.view', 'admin')
   ...
@endhaspermissionto
```

**Comment by nguyencuongcd44** [comment]
The @can does not work with my custom guard so I changed the default guard to my custom guard, and it worked. 
Is anyone else experiencing the same issue as me?
How can I use this with custom work ? 
Thank you very much.

**Comment by parallels999** [comment]
Did you try ```auth('admin')->user()->can('admin.users.view', 'YOUR_CUSTOM_GUARD')``` ?

**Comment by nguyencuongcd44** [comment]
It worked! I spent 2 days on this issue. Thank you very much for your help!
