### ISSUE TITLE
Is it possible for allow / deny on permission direction?. It is cool.

### ISSUE THREAD

**Issue by chitainguyen** [spatie/laravel-permission#1294]
Dear Mr..,

I want a permission system like Discord.

It is same like that, but need an override way on permission direction.
Can you add it on this source too?

Thanks a lot

**Comment by drbyte** [comment]
I'm not sure I understand your question.

I think most of what you're talking about is something to build into your app, not into this package.

**Comment by chitainguyen** [comment]
@drbyte i mean: can this package support for allow, deny on permission

**Comment by drbyte** [comment]
This package supports assigning permissions to users/roles.

Your application can then use Laravel's Gate features to call `can()` and `cannot()` against those permissions. (There are additional functions like hasRole or hasPermissionTo, but those are more advanced.)

So, if by "deny" you mean calling `$user->cannot()` then yes.

But, if by "deny" you mean you want to give users a "Manager" role but then "subtract"/deny a permission that the Manager normally has, then no, this package doesn't do that.

This package does "additive" permission assignment, not subtracting.
