### ISSUE TITLE
Feature request: Assign a target to a role.

### ISSUE THREAD

**Issue by leoleoasd** [spatie/laravel-permission#1297]
Use case: Let's assume that we have a model called Class. A role called `manager` have a `target_type` field, which is `"App\\Models\\Class"`. 

The manager role have a couple of permissions, for example, `manage`.

Then this role can be assigned to a user, which means that user is the manager of a class.  The `user_has_roles` table will have a `target_id` field, means the target id of the target.

Then, when run $user->can method:
```php
$user = User::find(1);
$class = Class:find(5);
if($user->can("manage",$class)){
do something.....
}
```
The can method first checks that if there is a role targeting a `"App\\Models\\Class"`, and if the user is assigned that role, also if the `target_id` field is equals to 5 in the  `user_has_roles` table. After that it checks if the manager role have the manage permission.

This feature is fundamental in my project. since i don't know much about SQL, my implementation may have very bad performance. So i made this feature request.

**Comment by leoleoasd** [comment]
In my condition, we have a Class and two roles called teacher and assistant. A user can be assigned with a "assistant to a class".

**Comment by drbyte** [comment]
There are various ways you could reach your end result. You could perhaps change the code to add a target_type field as you proposed. Or you could create another polymorphic relationship between Roles and Classes.

While I don't think you'll see this sort of thing become "built in" to this Spatie package, what you mention has "some" similarities to issues #846 or #1145. 

I'm not fully certain, but you might check whether the Bouncer package already supports the extra levels of data-storage and relationship-checking that you're asking about.

**Comment by leoleoasd** [comment]
@drbyte
I've checked the Bouncer package you mentioned, but it have some difference with my request.
I mean if a created a role called manager "Targeting" a App\\Models\\Group, two different user with this role may have different group to manage. 
```
$user = User::find(1);
$group = Group::find(5);
$another_group = Group::find(6);
$role = Role::create(['name'=>'manager', 'target' => get_class($group)]);
$role-> givePermissionTo("manage");
$user->addRole($role,$group);
// this user is a manager of the 5th group.

$user->can("manage",$group);
// true

$user->can("manage",$another_group);
// false
```

**Comment by drbyte** [comment]
The theory for how to implement this is something like the following:

1. You add your custom `target` field to the Role class and table, along with methods to manage that additional field.
2. You create a Model Policy for the Group model, with a method named `manage`, and in there you do any necessary lookups for whether the user should be allowed to interact with the Group you pass to it.
