### ISSUE TITLE
Problem with mongodb on laravel 6.x

### ISSUE THREAD

**Issue by marooj** [spatie/laravel-permission#1298]
i am have problem .
there is a package (that forked from your project) for work with mongodb 
https://github.com/mostafamaklad/laravel-permission-mongodb/

i am know that have  problem with laravel 6.x
please add mongodb usage

**Comment by drbyte** [comment]
See #1273 
There are no plans to support mongodb with this package.

If you are having a problem with someone else's package (such as Maklad's package that you linked to), it's best to open an issue with them and seek their assistance, or offer to help them implement what you need in their package.

**Comment by mostafamaklad** [comment]
Now it is compatible with Laravel 6.x
