### ISSUE TITLE
guard_name in permissions tale is blank

### ISSUE THREAD

**Issue by woottonn** [spatie/laravel-permission#1299]
Hi there.

When I run ... `Role::create(['name'=>'Regular User']);` - it enters the name and also the guard_name "web" into the database - great.

However, when I run... `Permission::create(['name'=>'view-users']);` - the guard name is blank in the database. I can add this manually with `Permission::create(['name'=>'view-users, 'guard_name'=>'web'']);`, but it doesn't seem like I should have to.

Is there something silly I'm missing here? Or is this a bug? I'm running Laravel 6 and the latest laravel-permission build.

**Comment by drbyte** [comment]
Have you made any customizations to your config/auth.php file?

**Comment by woottonn** [comment]
Hi drbyte, thanks for the response! No changes, the contents are as follows.. I have also tried restarting artisan server with no luck

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
            'throttle' => 60,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Password Confirmation Timeout
    |--------------------------------------------------------------------------
    |
    | Here you may define the amount of seconds before a password confirmation
    | times out and the user is prompted to re-enter their password via the
    | confirmation screen. By default, the timeout lasts for three hours.
    |
    */

    'password_timeout' => 10800,

];
`

**Comment by drbyte** [comment]
Another question: I noticed in the title you said `guarded_name`, not `guard_name`. Was that just a typo? Or were you actually looking for a field named `guarded_name` (that field doesn't exist).

I can't seem to recreate the problem, so it feels like an error in your application. 
Help me recreate it, starting with a fresh new Laravel installation. What steps do I need to take to recreate this symptom?

**Comment by drbyte** [comment]
Notice how your controllers use `\App\Permission`:
https://github.com/woottonn/permissions-roles/blob/59c61dbdb609b9d28674e069e0ad048129bda0ba/app/Http/Controllers/SuperAdmin/PermissionsController.php#L3-L11

... but your `\App\Permission` model is just a basic Eloquent model, and doesn't extend the Spatie permission model, thus it doesn't have access to any of the logic of the Spatie model:
https://github.com/woottonn/permissions-roles/blob/59c61dbdb609b9d28674e069e0ad048129bda0ba/app/Permission.php#L3-L11

Additionally, your `config` file doesn't tell your app to use your extended model:
https://github.com/woottonn/permissions-roles/blob/59c61dbdb609b9d28674e069e0ad048129bda0ba/config/permission.php#L5-L16

See: https://docs.spatie.be/laravel-permission/v3/advanced-usage/extending/

**Comment by woottonn** [comment]
Thanks drbyte, I got it working all great in the end, although the one thing I had to do was manually enter "web" to the database when create a permission. However - I did not change any of the things you just mentioned and its working great.. ?? The permissions controller and roles controllers and models I made just so I could have an admin area to add/remove roles...

![image](https://user-images.githubusercontent.com/6769984/71160239-17744000-223f-11ea-96d2-c2ac79035291.png)
