### ISSUE TITLE
@can not working as expected

### ISSUE THREAD

**Issue by santiagogg** [spatie/laravel-permission#13]
Hi there, 
I upgraded from version 5.1.  following http://laravel.com/docs/5.1/upgrade#upgrade-5.1.11 
Everything seems to work but $user->can('create post') is false when $user->hasPermissionTo('create post') is true... What I'm missing?

Thanks!

**Comment by freekmurze** [comment]
Did you [register the service provider](https://github.com/spatie/laravel-permission#install)?

**Comment by AEK-BKF** [comment]
same issue with me !!!

**Comment by freekmurze** [comment]
@AEK-BKF Do you register the service provider? Which error are you getting?

**Comment by AEK-BKF** [comment]
Yes I did, @role works fine, but @can always returns true if the permission exists, and false when not.
here my User Model code :
<?php 

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Database\Eloquent\softDeletes;
use Spatie\Permission\Traits\HasRoles;



class User extends Model implements AuthenticatableContract,  
                                    AuthorizableContract,                                 
                                    CanResetPasswordContract                                                                                                        
{
    use Authenticatable, CanResetPassword, Authorizable, SoftDeletes, hasRoles;

**Comment by jpmurray** [comment]
I'm not sure if I'm having the same trouble, but...

```
$permission = Permission::create(['name' => 'create user']);
$role = Role::findByName('superadmin');
$role->givePermissionTo('create user');
```

Works fine.For the current user, `$user->hasRole('superadmin');` returns true.

But trying to do `$user->can('create user');` will result in

```
FatalErrorException in Model.php line 1011:
Class name must be a valid object or a string
```

Any idea?

**Comment by AEK-BKF** [comment]
I solved my issue by editing hasRole & PermissionServiceProvider classes like this :
Function hasDirectPermission in hasRole class :
 public function hasDirectPermission($permissions)
    {
        if (is_string($permissions)) {
            return $this->permissions->contains('name', $permissions);
        }
        if ($permissions instanceof Permission) {
            return $this->permissions->contains('id', $permissions->id);
        }

        //return (bool) !!$permissions->intersect($this->permissions)->count();

        return $this->permissions->contains('name', $permissions);
    }

registerBladeExtensions in PermissionServiceProvider class :
Add these lines :
 $bladeCompiler->directive('permission', function ($permission) {
                return "<?php if(auth()->check() && auth()->user()->hasDirectPermission({$permission})): ?>";
            });
            $bladeCompiler->directive('endpermission', function () {
                return '<?php endif; ?>';
            });

And all is working fine :))
Try it @jpmurray  and tell me if it's ok ^^'

**Comment by jpmurray** [comment]
I'll wait for @freekmurze input on that before messing with the package files ;-)

**Comment by jpmurray** [comment]
Welp, shame on me. My issue is basically related to me not scrolling enough in my files. I just found a old stray "permissions" function in my User model. Now that it's gone, everything works fine :/

**Comment by freekmurze** [comment]
@jpmurray nice, I'm glad you found the solution quickly :+1:

**Comment by jpmurray** [comment]
@freekmurze although are the permissions functions (`can`, `hasPermissionTo`, etc) works with `$roles` ?

Curently trying to do a `$role->hasPermissionTo($permission->name)` that results a `Call to undefined method Illuminate\Database\Query\Builder::hasPermissionTo()`...

**Comment by freekmurze** [comment]
No, see #31

On Sunday, 10 January 2016, Jean-Philippe Murray <notifications@github.com>
wrote:

> @freekmurze <https://github.com/freekmurze> although are the permissions
> functions (can, hasPermissionTo, etc) works with $roles ?
>
> Curently trying to do a $role->hasPermissionTo($permission->name) that
> results a Call to undefined method
> Illuminate\Database\Query\Builder::hasPermissionTo()...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-permission/issues/13#issuecomment-170360211>
> .
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91

**Comment by razikallayi** [comment]
What is the final answer? `@can` is not working for me too.

**Comment by desaijay** [comment]
public function boot(GateContract $gate)
    {
        $this->registerPolicies($gate);

         foreach ($this->getPermissions() as $permission) {
            $gate->define($permission->name, function ($user) use ($permission) {
                return $user->hasPermission($permission);
            });
        }
    }

      protected function getPermissions()
    {
        return Permission::with('roles')->get();
    }


add this to the AuthServiceProvider.php file and you can then use @can ???

I dont know wat @freekmurze  will suggest, but even after registering the service provider class in app.php, @can doesnt work.

Well i dnt know whether to mess thecode or try it like @AEK-BKF did.


the only problems you can face is when assigning multiple roles andmultiple permissions. I think that multiple permissions can be assigned to a role, but users should be only given the role and then the role must check whether the user is assigned the role and it has certain permissions on it.

**Comment by freekmurze** [comment]
Normally if you the service provider is registered correctly, the package will [register all permissions at the gate](https://github.com/spatie/laravel-permission/blob/master/src/PermissionServiceProvider.php#L31).

This package has tests to prove that the provided functionality is working. If you are still having problem, could you please submit a failing test? That would help me immensely in finding the problem/solution.

**Comment by desaijay** [comment]
it was just a suggestion to above user, for me this package is working perfectly except @can is not working in blade templates and my testing is little poor, so cnt help you out much, lots of usage coming across the way.

I had jut one simple question, i had done something from the scratch , and was able to relate all the users roles and permission, and assigning the roles the permissions, and fetching, revoking and updating the roles and permission.

But i am still figuring how will i use the middleware to check the role of  the user and then redirect to following path , and also the routes should be served to that roles only.

I have tried your another package, n thats works perfectly for me, but if you can help me from scratch.
There is function redirectPath , which i have modified in authcontroller.php, and it works with the redirection of particular type if users.

But this should be more normalised and i dnt want to mess with the authcontroller file, any help/hint would be good for me?

**Comment by Sekonda** [comment]
I know this issue was closed, but I'm still running into the same issue. I've registered the service provider. 

_can()_ returns false even though the user has the permission through the role(s) assigned. 
_hasPermission_To returns correctly

**Comment by freekmurze** [comment]
Could you PR a failing test?
