### ISSUE TITLE
@hasanyrole('admin|subscriber|membersubscriber') gives blank page

### ISSUE THREAD

**Issue by Thomasosho** [spatie/laravel-permission#1301]
I am just getting blank page when i use the hasanyrole by when i use hasrole with a single role it work

My code
@hasanyrole('admin|subscriber|membersubscriber')

@if(count($posts) > 0)

    @foreach($posts as $post)

        <div class="row">
           <div class="col-6 offset-3">
                <img src="/storage/public/image/{{$post->image}}" alt="" class="w-100">
                <div class="interaction">
                         
                <hr>
                </div>
            </div>
            <div class="row pt-2 pb-4">
            <div class="col-6 offset-3">
                <div>
                    <div class="d-flex align-items-center">
                        <div class="pr-3">
                            <img src="/storage/avatars/{{$post->user->avatar}}" class="rounded-circle" style="max-width: 35px;">
                        </div>
                        <div>
                            <div class="font-weight-bold"> 
                                <a href="/profile/{{$post->user->id}}"> 
                                    <span class="text-dark">
                                        {{$post->user->username}}
                                    </span>
                                </a>
                            </div>
                            <span class="align-items-center">{{$post->caption}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    @endforeach
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            {{$posts->links()}}
        </div>
    </div>
@else

@foreach($displayusers as $user)
@cannot ('update', $user->profile)
        <div class="row">
            <div class="col-3 offset-4">
                <img src="{{$user->profile->avatar}}" alt="" class="w-100">
            </div>
        </div>

        <div class="row pt-2 pb-4">
            <div class="col-3 offset-4 align-items-center">
                <div>
                    <div class="d-flex align-items-center">
                        <div>
                            <div class="font-weight-bold"> 
                                <a href="/profile/{{$user->id}}"> 
                                    <span class="text-dark">
                                        {{$user->username}}
                                    </span>
                                </a>
                            </div>
                            <span class="align-items-center"><a href="/profile/{{$user->id}}">View to follow</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endcannot
    @endforeach
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            {{$displayusers->links()}}
        </div>
    </div>

@endif

@else

    <h2>You have not subscribed</h2>
    <a href="/subscribe">Subscribe model</a>|
    <a href="/membersubscribe">Subscribe member</a>
@endhasanyrole

**Comment by drbyte** [comment]
> getting blank page

A blank page is often a result of a PHP error. Is there anything recorded in the Laravel logs?

**Comment by Thomasosho** [comment]
Not a blank Page
My page loads just fine, just that the @hasanyrole('admin|subscriber|membersubscriber') is not working. I only get the else statement. I am currently signed in as as admin.

**Comment by drbyte** [comment]
The package tests related to `@hasanyrole()` are working correctly.

I wonder with your app, is it guard-related? How many guards are you using in your application, and why?

**Comment by Thomasosho** [comment]
Just the normal auth guard

**Comment by drbyte** [comment]
Puzzling

**Comment by Thomasosho** [comment]
I'll just figure out another way to go through it.

**Comment by drbyte** [comment]
Does passing an array, instead of a pipe-delimited string make any difference?

**Comment by drbyte** [comment]
Is it caused by any specific role in the list?  ie: if you just use `@hasanyrole('admin')` does it behave just like `@hasrole('admin')`? It should since `hasAnyRole` is just a proxy to `hasRole` anyway.

Then, does just replacing `@hasanyrole('string|of|roles')` with `@hasrole('string|of|roles')` give no result?

**Comment by Thomasosho** [comment]
Let me try that

**Comment by drbyte** [comment]
Aside: I find it's usually way more performant to use `@can` (with a permission name), and only use roles for "grouping" permissions for convenience of assigning capabilities to users.
ie: users have roles, and roles have permissions, and your app always checks for `permissions`, not `roles`.

https://docs.spatie.be/laravel-permission/v3/best-practices/roles-vs-permissions/

**Comment by Thomasosho** [comment]
@hasanyrole('admin') behaves the same as @hasrole('admin').
Replacing it gives the same result.

**Comment by drbyte** [comment]
> @hasanyrole('admin') behaves the same as @hasrole('admin').
> Replacing it gives the same result.

Okay, that's expected.

So, is the problem just when adding additional role names?

**Comment by drbyte** [comment]
If your User object has a `role` or `roles` property (or field in the db), or a `roles()` method on it, those will interfere with the properties and methods added by the `HasRoles` trait in this package, causing unexpected outcomes when this package's methods are used to inspect roles and permissions.

**Comment by Thomasosho** [comment]
I have roles in mu User Model... let me comment it out
