### ISSUE TITLE
The given role or permission should use guard `admin` instead of `web`.

### ISSUE THREAD

**Issue by DevChristians** [spatie/laravel-permission#1303]
Hi community.
I have a problem assigning a role with the 'guard_name' 
`Seeder`
![image](https://user-images.githubusercontent.com/27924062/70929455-8cf6cb00-2009-11ea-8466-8b5ffd824ee1.png)
to a user of the 'Admin' model
`App\Models\Admin.php`
![image](https://user-images.githubusercontent.com/27924062/70929528-ad268a00-2009-11ea-82f3-a693ce181d07.png)
my `config/auth.php`
![image](https://user-images.githubusercontent.com/27924062/70929695-055d8c00-200a-11ea-8bb8-d89f393f16e0.png)
![image](https://user-images.githubusercontent.com/27924062/70929697-08f11300-200a-11ea-8ac0-b1d18e63c425.png)
![image](https://user-images.githubusercontent.com/27924062/70929677-f8d93380-2009-11ea-9630-f86c3f84f79d.png)

Exception
![image](https://user-images.githubusercontent.com/27924062/70929753-2c1bc280-200a-11ea-97a1-ac3f18252809.png)

note: I have followed the steps of the documentation and seen similarities but I cannot resolve, thanks for the attention.

**Comment by dennis-git** [comment]
you need to do $admin->assignRole($role); // assign correct object and and not just a string 'super-admin' in 'web' guard

**Comment by DevChristians** [comment]
@dennis-git 
I've tried friend, but still the same exception

**Comment by DevChristians** [comment]
@dennis-git 
It is confusing, I tried changing the default guard in the `config/auth.php` and there is no problem, but depending on the package configuration it should work without problems.

**Comment by mehrshad1367** [comment]
change the guard name in your Admin Model to api(or guard column content in role and permission table) and check it...
