### ISSUE TITLE
Why setting guard_name in the my model, but it doesn't take effect.

### ISSUE THREAD

**Issue by carveybunt** [spatie/laravel-permission#1304]
- my model code
    
        <?php
        
        namespace App\Http\Models\Api\Server;
        
        use Auth;
        use Illuminate\Database\Eloquent\SoftDeletes;
        use Illuminate\Foundation\Auth\User as Authenticatable;
        use Spatie\Permission\Models\Permission;
        use Spatie\Permission\Traits\HasRoles;
        use Tymon\JWTAuth\Contracts\JWTSubject;
        
        class Servers extends Authenticatable implements JWTSubject
        {
            use HasRoles;
            protected $guard_name = 'server';
            public function __construct()
            {
                if (!cache()->has('hasPermission_server_manage_user')) {
                    if (Permission::findOrCreate(0,'server_manage_user', '管理用户')) {
                        cache()->set('hasPermission_server_manage_user', 1, 60 * 60 * 24);
                    }
                }
            }
            public function getJWTIdentifier()
            {
                return $this->getKey();
            }
- After it is executed

![微信图片_20191219100327](https://user-images.githubusercontent.com/37894474/71138575-f4e62500-2246-11ea-96d3-1da98832cc8a.png)

- config/auth.php

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'user' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
        'server' => [
            'driver' => 'jwt',
            'provider' => 'servers',
        ],
    ],

someone can help me？

**Comment by carveybunt** [comment]
@drbyte Thanks.
However, due to business needs, I have modified the following contents:

- Spatie\Permission\Contracts\Permission;

        public static function findOrCreate(int $pid = 0, string $name, $title = null, $guardName = null): PermissionContract
        {
            $guardName = $guardName ?? Guard::getDefaultName(static::class);
            $permission = static::getPermissions(['pid' => $pid, 'name' => $name, 'title' => $title, 'guard_name' => $guardName])->first();
    
            if (!$permission) {
                return static::query()->create(['pid' => $pid, 'name' => $name, 'title' => $title, 'guard_name' => $guardName]);
            }
    
            return $permission;
        }
        
and

- Spatie\Permission\Contracts
    
       public static function findOrCreate(int $pid,string $name, $title, $guardName): self;

So,if i wanna use Permission::findOrCreate(0,'server_manage_user', '管理用户')，how do I make the Guard set in my model work?Or is this feasible?

**Comment by drbyte** [comment]
I'll look into it over the holidays.

But I think if I was in your situation I'd be inclined to simply pass your `$this->guard_name` as your 4th parameter when calling your custom `findOrCreate` from inside your constructor, since it makes sense in the context already anyway.

**Comment by carveybunt** [comment]
> I'll look into it over the holidays.
> 
> But I think if I was in your situation I'd be inclined to simply pass your `$this->guard_name` as your 4th parameter when calling your custom `findOrCreate` from inside your constructor, since it makes sense in the context already anyway.

Thanks again, I'll try use $this->guard_name make it effect.
