### ISSUE TITLE
Want to add a status(active/inactive) column to the roles table

### ISSUE THREAD

**Issue by suparnaCC** [spatie/laravel-permission#1305]
Hi,

I am in situation where I need to add a status column for roles table. So that admin person can active or inactive a role. Also I want to know what will be the modifications in other functions like @can etc.

Please help, its urgent.
Thanks in advance.

**Comment by drbyte** [comment]
In the docs there's a section on Extending this package. In there it talks about "Replacing" the Role model. You'd want to do that. You'd need to also add your column to the db, and then update all the methods to check the status when returning a response.
Unfortunately I think you'll also need to override some of the methods in the HasRoles trait, as well as the middleware. Maybe even the ServiceProvider.

**Comment by drbyte** [comment]
Potential shortcut: If your app uses only one Guard, then you could perhaps explore using the guard_name field as a status field, and just change the guard_name to something like 'disabled' until you want to re-enable it.

**Comment by suparnaCC** [comment]
I am very thankful for your response.
I have added a column in role table and modified some core functions in HasRole. It is working fine for checking the permissions. But I am not able not find the required method for @can. Could you please tell me which function is need to modify for that?

**Comment by drbyte** [comment]
The `@can()` only works on "permissions", not roles. 
It appears you will need to add your custom restriction into the query that determines the permissions from the user's roles:
The PermissionServiceProvider reads the permissions from the user's roles, and then registers them onto Laravel's Gate, which then allows `@can` and `->can()` to respond.

**Comment by suparnaCC** [comment]
Thank you for this explanations. It helps me a lot. Ok I will modify the functions there.

**Comment by segmatehire02** [comment]
@suparnaCC r u facing any problem after adding column to role.?

**Comment by suparnaCC** [comment]
@segmatehire02 No, I am not facing any problem after adding column. Everything is working fine.

**Comment by segmatehire02** [comment]
what kind of changes that you have made in HasRoles Trait and Service Provider, that @drbyte has mentioned?.

**Comment by suparnaCC** [comment]
I have added an extra where condition for sql queries.
Like:
Before: $this->roles->where('guard_name', $guard)->contains('name', $roles)
After: $this->roles->where('guard_name', $guard)->where('status','active')->contains('name', $roles)

**Comment by segmatehire02** [comment]
In my case i have to add column(foreign key of some table) in permission table. but let see what and how i have to made changes in HasPermission Trait. Thanks for the quick response.

**Comment by suparnaCC** [comment]
Welcome. Happy coding.
