### ISSUE TITLE
Spatie\Permission\Exceptions\RoleDoesNotExist when guard change to web to admin

### ISSUE THREAD

**Issue by meet0929** [spatie/laravel-permission#1307]
> Spatie\Permission\Exceptions\RoleDoesNotExist 
> There is no role named `administrator`.

showing error when change guard to admin.and its taking default guard name web

still showing error after using 
```
use Illuminate\Support\Facades\Auth;

protected function guard(){
   return Auth::guard('admin');
}
```

**Comment by drbyte** [comment]
You haven't given enough code/context to understand your problem well. 
But you said "when guard change to web to admin", so I'm assuming you're changing your application to use a different guard than what you started with.
When a role is created, its associated guard is also stored in the database.
If you later change the guard in your application, you will need to either update the database record for the affected roles, or create new roles for that new guard.
