### ISSUE TITLE
Auto create role

### ISSUE THREAD

**Issue by ScooterSam** [spatie/laravel-permission#131]
I dont know why, but when i started to use this package, I had in mind that i could do:

`$user->assignRole('rolename')`

And it would automatically create role if it doesnt exist. 

It seems like this is the case with _->givePermissionTo('permission');

Why not assignRole?

Also, this shouldn't remove the role if using _->removeRole('rolname')

**Comment by freekmurze** [comment]
To my knowledge `givePermissionTo` won't auto create roles.  If you want this behaviour just override the `assignRole` function of the trait with your own method.
