### ISSUE TITLE
'api' guard requests not working when roles created with 'web' guard

### ISSUE THREAD

**Issue by woottonn** [spatie/laravel-permission#1320]
Hi there. I have a database structure as follows:

![image](https://user-images.githubusercontent.com/6769984/71972161-0a29f000-3204-11ea-9ce3-fedd398644d7.png)

I have web guards all setup and working fantastically. I'm using them fantastically in my web routes:

![image](https://user-images.githubusercontent.com/6769984/71972268-39d8f800-3204-11ea-8c24-c391ebc93c64.png)

However, when trying to use them in API's they do not function . Every user is blocked, even a super admin. (assuming because in the database the roles are listed as "web" only? This is an example of my API route file...

![image](https://user-images.githubusercontent.com/6769984/71972338-5aa14d80-3204-11ea-90cd-921ce1b76819.png)

What is the best way to do this? Is there a way to tell it to use web permissions for APIs? Or am I missing something silly here?

**Comment by drbyte** [comment]
Yes, that's a limitation of this package, and a reason why I'm exploring removing guard-specific permissions altogether: because most people use the "same" roles/permissions for ALL guards, and they're confused when it only works for the original guard they created things for. 

In the meantime, you can use the workaround posted in https://github.com/spatie/laravel-permission/issues/1156#issue-466659658 to tell your app to handle the guard as a wildcard.

**Comment by woottonn** [comment]
Cheers drbyte. I'm having a small issue... I am not quite following point 2.) as follows...

In your model(s) that HasRoles or HasPermissions, overwrite the hasPermissionTo and getDefaultGuardName methods:
```
<?php

namespace App;

class User extends ...
{
	use ...HasRoles...;

	public function hasPermissionTo($permission, $guardName = '*'): bool
	{
		// Since this method comes from a trait,
		// you cannot simply `parent::hasPermissionTo($permission, '*')`.
		// You'll have to copy the entire body of the method into yours.
		// Just replace '*' with the "guard" name from above.
	}

	protected function getDefaultGuardName(): string
    {
        return '*';
    }
```
Can you advise?

**Comment by woottonn** [comment]
A bit more info on the above - when I add those functions to my Role and Permission Models I get the error "Interface function Spatie\Permission\Contracts\Role::hasPermissionTo() cannot contain body"

If I removed the body of the function I then get the error "Non-abstract method App\Role::hasPermissionTo() must contain body"

**Comment by drbyte** [comment]
It seems to me that the comments you've copied over need to be replaced by the actual code they're referring to: https://github.com/spatie/laravel-permission/blob/a5f9d2b50a5bde5d275bbe5fb0d3d86664880a24/src/Traits/HasPermissions.php#L120-L142

**Comment by woottonn** [comment]
Hi drbyte - sorry, Laravel and OOP is generally new to me after just coming out of the dark ages of PHP spaghetti code! I'm starting to gauge the usefulness and speed at which you can plough through things, although at the moment it is a slower process for me as I'm still getting used to the ideas of Models and Controllers - slowly slowly getting there :)

I've managed to figure out what to do (I think) but I am still getting an 401 error when trying to pull from an API.


Model - Role.php:

```
<?php

namespace App;

class Role extends \Spatie\Permission\Models\Role
{
    protected $guarded = [];
    protected $guard_name = 'web'; 

}
```

Model - Permission:

```
<?php

namespace App;

class Permission extends \Spatie\Permission\Models\Permission
{
    protected $guarded = [];
    protected $guard_name = 'web';

}

```

A model where I want to over-ride the guard:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Contracts\Permission;
use Spatie\Permission\Exceptions\PermissionDoesNotExist;
use Spatie\Permission\Traits\HasRoles;

class Group extends Model
{
    protected $guarded = [];
    use HasRoles;

    public function hasPermissionTo($permission, $guardName = 'web'): bool
    {
        $permissionClass = $this->getPermissionClass();

        if (is_string($permission)) {
            $permission = $permissionClass->findByName(
                $permission,
                $guardName ?? $this->getDefaultGuardName()
            );
        }

        if (is_int($permission)) {
            $permission = $permissionClass->findById(
                $permission,
                $guardName ?? $this->getDefaultGuardName()
            );
        }

        if (! $permission instanceof Permission) {
            throw new PermissionDoesNotExist;
        }

        return $this->hasDirectPermission($permission) || $this->hasPermissionViaRole($permission);
    }

    protected function getDefaultGuardName(): string
    {
        return 'web';
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }
}

```

VUE calling the API:

```
            getTimes(){
                //Get time data to populate table
                axios.post('/api/group_times', {
                    group_id: this.group_id,
                    amount: 5,
                    season_id: this.season_id
                })
                    .then(response => {
                            this.times = response.data;
                        }
                    );
            },
```

401: 
![image](https://user-images.githubusercontent.com/6769984/72142797-653b1e80-338d-11ea-8404-fff8513248e6.png)

**Comment by robertnicjoo** [comment]
In case to use this package in your Laravel-Vue app or `any JavaScript front-end` here is how you do it:

1. You **don't need to add middleware** to your API routes
2. You restrict user access by their roles **in your components** 

# Example

```javascript
//component
data() {
        return {
            user: '',
            type: '', // type here is role i like to call it type
       }
},
created () {
        this.fetchAuthenticatedUser()
},
beforeRouteEnter (to, from, next) {
      const token = localStorage.getItem('access_token')
      return token ? next() : next('/login')
},
methods: {
    fetchAuthenticatedUser () {
            axios
                .get('/api/auth/user', {
                    headers: {
                        Authorization: 'Bearer ' + localStorage.getItem('access_token')
                    }
                })
                .then(response => {
                    this.type = response.data.type
                    if(response.data.type !== 'admin') {
                        this.$router.push({name: 'home'})
                    }
                })
                .catch(function (error) {
                    console.log('error', error);
                });
        },
}
```


```php
// controller
public function user(Request $request)
    {
        $user = $request->user();
        return response()->json(new usersResource($user)); //notice this resource "usersResource"
    }
```

```php
//resource
  public function toArray($request)
  {
            $role = $this->roles->pluck('name')->first(); // returns "admin" or "customer" in my case
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'type' => $role,
            'photo' => url('storage/img', $this->photo),
  }
```

> Note: The trick here is that you need to store your users token in localStorage when they're login that way you can send request to controller and see if user has specific roles to access this page or not. (PS: it's not about roles only it can be permissions as well, it's up to you what data you want to request)


# Additionally

Based on your question, here you won't need to worry about storing roles with `web` value in database or anything in that matter.
**Again:** you won't need to add middleware to your API routes.


Hope it solve your issue.

**Comment by woottonn** [comment]
> In case to use this package in your Laravel-Vue app or `any JavaScript front-end` here is how you do it:
> 
> 1. You **don't need to add middleware** to your API routes
> 2. You restrict user access by their roles **in your components**
> 
> # Example
> ```js
> //component
> data() {
>         return {
>             user: '',
>             type: '', // type here is role i like to call it type
>        }
> },
> created () {
>         this.fetchAuthenticatedUser()
> },
> // before open this route see if this user even is logged or not? if yes proceed if not redirect to login page
> beforeRouteEnter (to, from, next) {
>       const token = localStorage.getItem('access_token')
>       return token ? next() : next('/login')
> },
> methods: {
>     fetchAuthenticatedUser () {
>             axios
>                 .get('/api/auth/user', {
>                     headers: {
>                         Authorization: 'Bearer ' + localStorage.getItem('access_token')
>                     }
>                 })
>                 .then(response => {
>                     this.type = response.data.type
> // if user is logged and role is admin proceed otherwise redirect to homepage
>                     if(response.data.type !== 'admin') {
>                         this.$router.push({name: 'home'})
>                     }
>                 })
>                 .catch(function (error) {
>                     console.log('error', error);
>                 });
>         },
> }
> ```
> 
> ```
> // controller
> public function user(Request $request)
>     {
>         $user = $request->user();
>         return response()->json(new usersResource($user)); //notice this resource "usersResource"
>     }
> ```
> 
> ```
> //resource
>   public function toArray($request)
>   {
>             $role = $this->roles->pluck('name')->first(); // returns "admin" or "customer" in my case
>             'id' => $this->id,
>             'name' => $this->name,
>             'email' => $this->email,
>             'type' => $role,
>             'photo' => url('storage/img', $this->photo),
>   }
> ```
> 
> > Note: The trick here is that you need to store your users token in localStorage when they're login that way you can send request to controller and see if user has specific roles to access this page or not. (PS: it's not about roles only it can be permissions as well, it's up to you what data you want to request)
> 
> # Additionally
> Based on your question, here you won't need to worry about storing roles with `web` value in database or anything in that matter.
> **Again:** you won't need to add middleware to your API routes.
> 
> Hope it solve your issue.

Thank you! This looks promising. One thing (apologies as I am still new to laravel after hard coding PHP for years), the "toArray" function in the last block of code you say is for the resource. Which file would this be in? There is nothing in the App/HTTP/Resources folder. Does this need to go into the model?

**Comment by robertnicjoo** [comment]
> here is nothing in the App/HTTP/Resources folder. Does this need to go into the mode

You can create resource file by this command

```bash
php artisan make:resource ResourceName
```

ref: https://laravel.com/docs/5.8/eloquent-resources#generating-resources

**Comment by woottonn** [comment]
I saw a little bit of information earlier that I hadn't spotted before.

THIS DIDN'T WORK (it would work in web.php):

    Route::post('privacy_change', 'UsersController@privacy_change')->middleware('can:change_privacy');
THIS WORKED!

Route::group(['middleware' => ['auth:api']], function () {

    Route::post('privacy_change', 'UsersController@privacy_change')->middleware('can:change_privacy');

});
Apparently because of this bit of information I found, which I had no knowledge of before... "Out of the box, the web middleware group is automatically applied to your routes/web.php file by the RouteServiceProvider."

It is now working!! I just needed to wrap the API routes

**Comment by twf-nikhila** [comment]
@drbyte @woottonn @robertnicjoo Did you get any proper solution to this?
facing similar issues...please share if you got a solution

**Comment by saurav-volition** [comment]
https://spatie.be/docs/laravel-permission/v6/basic-usage/multiple-guards
this single function in the user model worked like charm to use the role for both the guards
    protected function getDefaultGuardName(): string { return 'web'; }
