### ISSUE TITLE
How to check same set of permissions already assigned to another role?

### ISSUE THREAD

**Issue by afrasiyabhaider** [spatie/laravel-permission#1323]
#Question #Guidance #Issue
I want to make sure that two roles with different names must not have same permissions while creating a role e.g

> Role A
>  - Pemission 1
>  - Permission 2
>  - Permission 3
> 
> Role B
>  - Pemission 1
>  - Permission 2
>  - Permission 3

If this happens system should not create the 2nd role "Role B"

Can anyone please guide me?

**Comment by drbyte** [comment]
You can use `$role->getPermissionNames()` to get the names of the permissions assigned to each role. So, one way to do that is to loop through all the system's roles and check against the list of permissions you're intending to assign.

**Comment by afrasiyabhaider** [comment]
@drbyte 
For $role I have to find role from the table.
But I want to check before creating a role that is there any other role with same set of information exists or not.
That's the ambiguity

**Comment by drbyte** [comment]
I understand.
This package doesn't do that check for you. But you can do it yourself by reading all the roles from the table and checking them against the list of permissions you intend to assign.

**Comment by afrasiyabhaider** [comment]
Found Solution

```
 $roles = Role::get();
        $permissions = $request->input('permissions');
        $notSame = false;
        $sameRole = null;
        for ($i = 0; $i < count($roles); $i++) {
            $role_permissions[$i] = $roles[$i]->getAllPermissions()
                ->pluck('id')->toArray();
            for ($j = 0; $j < count($role_permissions[$i]); $j++) {
                if ($role_permissions[$i] == $permissions) {
                    $notSame = true;
                    $sameRole = $roles[$i];
                    break;
                }
            }
        }
        /**
         * Below condition will check if same set of permissions is
         * not assigned to any other role then It will be processed
         * further otherwise user have to choose different set of
         * permission
         *
         */
        if ($notSame && ($sameRole != null)) {
            alert()->warning('Role Already Exists', 'A role named as "' . $sameRole->name . '" with same permissions 
             already exists try with another permissions set');
         return redirect()->back();

        } else {

    - Write here your code to store into DB
    }
```
