### ISSUE TITLE
User::role('User') query

### ISSUE THREAD

**Issue by michaelr0** [spatie/laravel-permission#1327]
Hi There,

During some refactoring on a project of mine, I noticed that anytime the scopeRole method was being called from a model, a query to get that role would fire.

Checking this with barryvdh/laravel-debugbar, I noticed the following queries would happen by running something like `App\User::role('User')->first();`.

``select * from `roles` where `name` = 'User' and `guard_name` = 'web' limit 1``
Finished in 330us

``select * from `users` where exists (select * from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `users`.`id` = `model_has_roles`.`model_id` and `model_has_roles`.`model_type` = 'App\User' and (`roles`.`id` = 1)) limit 1``
Finished in 390us

Upon looking at the code for scopeRole
  ```
 /**
     * Scope the model query to certain roles only.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string|array|\Spatie\Permission\Contracts\Role|\Illuminate\Support\Collection $roles
     * @param string $guard
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeRole(Builder $query, $roles, $guard = null): Builder
    {
        if ($roles instanceof Collection) {
            $roles = $roles->all();
        }

        if (!is_array($roles)) {
            $roles = [$roles];
        }

        $roles = array_map(function ($role) use ($guard) {
            if ($role instanceof Role) {
                return $role;
            }

            $method = is_numeric($role) ? 'findById' : 'findByName';
            $guard = $guard ?: $this->getDefaultGuardName();

            return $this->getRoleClass()->{$method}($role, $guard);
        }, $roles);

        return $query->whereHas('roles', function ($query) use ($roles) {
            $query->where(function ($query) use ($roles) {
                foreach ($roles as $role) {
                    $query->orWhere(config('permission.table_names.roles') . '.id', $role->id);
                }
            });
        });
    }
```

I can see that this additional query is coming from `$this->getRoleClass()->{$method}($role, $guard);`

I can also understand that there are checks in place which will return an exception if needed.

However would you be open to a PR to introduce an alternative to scopeRole, for those that wish to just generate the needed SQL for the query builder, nothing more, nothing less?

This alternative method could be whereRole, roleRaw, whereRoleRaw or something else along those lines.

```
   /**
     * Scope the model query to certain roles only.
     * This will not return an exception if the role does not exist.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string|array|\Spatie\Permission\Contracts\Role|\Illuminate\Support\Collection $roles
     * @param string $guard
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWhereRole(Builder $query, $roles, $guard = null): Builder
    {
        if ($roles instanceof Collection) {
            $roles = $roles->all();
        }

        if (!is_array($roles)) {
            $roles = [$roles];
        }

        $roles = array_map(function ($role) {
            if ($role instanceof Role) {
                return $role->id;
            }

            return $role;
        }, $roles);

        $guard = $guard ?: $this->getDefaultGuardName();

        return $query->whereHas('roles', function ($query) use ($roles, $guard) {
            $query->where(function ($query) use ($roles, $guard) {
                foreach ($roles as $role) {
                    $column = is_numeric($role) ? 'id' : 'name';
                    $query->orWhere([
                        [config('permission.table_names.roles') . ".{$column}", '=', $role],
                        [config('permission.table_names.roles') . '.guard_name', '=', $guard]
                    ]);
                }
            });
        });
    }
```

Running `App\User::whereRole('User')->first();` resulted in the following query.
``select * from `users` where exists (select * from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `users`.`id` = `model_has_roles`.`model_id` and `model_has_roles`.`model_type` = 'App\User' and (`roles`.`id` = 1)) limit 1``
Finished in 340us

Thanks for your time.

**Comment by michaelr0** [comment]
Something else that caught my eye is that scopeRole/Permission will continue to query for each (int, string or collection) parameter that has been passed to it.

In a scenario where the a role exists with the id of 1 and a name of 'User'
`App\User::role([1, 'User'])->first();` will cause two queries to be fired off, however both will return the same result.

``select * from `roles` where `id` = 1 and `guard_name` = 'web' limit 1`` Finished in 390us.
``select * from `roles` where `name` = 'User' and `guard_name` = 'web' limit 1`` Finished in 370us.

Alternatively it might be worthwhile to change the original scopeRole to combat duplicate lookups.
```
    /**
     * Scope the model query to certain roles only.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string|array|\Spatie\Permission\Contracts\Role|\Illuminate\Support\Collection $roles
     * @param string $guard
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeRole(Builder $query, $listOfRoles, $guard = null): Builder
    {
        if ($listOfRoles instanceof Collection) {
            $listOfRoles = $listOfRoles->all();
        }

        if (!is_array($listOfRoles)) {
            $listOfRoles = [$listOfRoles];
        }

        $guard = $guard ?: $this->getDefaultGuardName();

        $listOfRoleNames = [];
        $roles = [];

        foreach ($listOfRoles as $role) {
            if ($role instanceof Role) {
                $roles[$role->id] = $role;
            } else {
                $method = is_numeric($role) ? 'findById' : 'findByName';

                if (!is_numeric($role) && !isset($listOfRoleNames[$role])) {
                    $thisRole = $this->getRoleClass()->{$method}($role, $guard);
                    $roles[$thisRole->id] = $thisRole;
                    $listOfRoleNames[$thisRole->name] = null;
                } elseif (is_numeric($role) && !isset($roles[$role])) {
                    $thisRole = $this->getRoleClass()->{$method}($role, $guard);
                    $roles[$thisRole->id] = $thisRole;
                }
            }
        }

        return $query->whereHas('roles', function ($query) use ($roles) {
            $query->where(function ($query) use ($roles) {
                foreach ($roles as $role) {
                    $query->orWhere(config('permission.table_names.roles') . '.id', $role->id);
                }
            });
        });
    }
```

**Comment by michaelr0** [comment]
@musapinar like a config option?

```
disabled_exceptions = [
    'RoleDoesNotExist' => true, // true for disabled?
]
```

And then at the start of scopeRole do a check to see if RoleDoesNotExist exception has been set as disabled and `return $this->scopeRoleRaw();` or such?

**Comment by musapinar** [comment]
No, my comment was meant to "upvote" your initial post. I like ```scopeWhereRoleRaw```.

(btw, I wish ```scopeRole``` was named ```scopeWhereRole``` in the first place...)

**Comment by michaelr0** [comment]
> No, my comment was meant to "upvote" your initial post. I like `scopeWhereRoleRaw`.
> 
> (btw, I wish current `scopeRole` was named `scopeWhereRole`, and `scopePermission` as `scopeWherePermission` ...)

Ah I see, thanks @musapinar

**Comment by michaelr0** [comment]
Closing this in favour of other PR's
