### ISSUE TITLE
Error using hasPermissionTo() method

### ISSUE THREAD

**Issue by darwinsalinas** [spatie/laravel-permission#133]
Error using hasPermissionTo() method.
ErrorException in HasRoles.php line 215:
Call to a member function contains() on null 

I had change the hasDirectPermission($permission) method for this

if (is_string($permission)) {
            $permission = app(Permission::class)->findByName($permission);

```
        if (!$permission) {
            return false;
        }
    }

    $permissions = collect($this->permissions());
    return $permissions->contains('id', $permission->id);
```

**Comment by freekmurze** [comment]
[These tests](https://github.com/spatie/laravel-permission/blob/1cb77dfe2c8c7fff7bf6dc67e9ffb75ffc007743/tests/RoleTest.php#L18-L28) indicated that hasPermissionTo is working as intended.

Could you submit a failing test or give detailed instruction on how this error can be recreated in a vanilla Laravel app?

**Comment by darwinsalinas** [comment]
ok, I has been using a code like this in a controller:

$module='purchase.request';
        $this->permisos = [
            'create' => $module.'.create',
            'update' => $module.'.update'
        ];
        foreach ($this->permisos as $permiso) {
            Permission::create(['name' => "$permiso"]);
            $this->user->givePermissionTo(['name' => "$permiso"]);
        }
        dd($this->user->hasPermissionTo($this->permisos['create']));

// output
// FatalThrowableError in HasRoles.php line 217:
// Call to a member function contains() on null

**Comment by freekmurze** [comment]
You're passing in an array into `givePermissionTo`. It expects a string.

Make this change:
```php
$this->user->givePermissionTo($permiso);
```

**Comment by darwinsalinas** [comment]
I'am using Laravel 5.3

**Comment by yahiaAbdullah** [comment]
I am have the same problem when use can , @can directive and when I use hasPermissionTo() method

**Comment by kentlee87** [comment]
> 
> 
> I'am using Laravel 5.3

Im having the same issue. Is it because the permission name has a dot period in it?

In my case, my permission name is 'module_name.create'

If I use module_name_create it working fine.

**Comment by kentlee87** [comment]
I having the same problem in Laravel 5.8.
The exception thrown:
`Symfony\Component\Debug\Exception\FatalThrowableError  : Call to a member function contains() on array at ....\HasPermissions.php:258`

Checked on the source:
This is the line:
`return $this->permissions->contains('id', $permission->id);`

Use gettype on `gettype($this->permissions)`, return Array.

So I assume the author is trying to use Larave's collection method: contains.
Replace that line with:
`return collect($this->permissions)->contains('id', $permission->id);`

Everything work perfectly.
Question, why $this->permissions became array and in the code is trying to assume it is an collection object??

**Comment by drbyte** [comment]
> Use gettype on gettype($this->permissions), return Array.
> Question, why $this->permissions became array and in the code is trying to assume it is an collection object??

It would seem that perhaps something in your own application code is interfering with `$this->permissions`. The usual cause of this is creating a `permissions` property on the User object, which prevents the BelongsTo relationship from being used.
