### ISSUE TITLE
Auth0 Integration - Authorizable contract error  [help-wanted]

### ISSUE THREAD

**Issue by gitflash** [spatie/laravel-permission#1331]
Hello, I'm working on integrating auth0 into my project but I want to manage roles/perms at the DB level. so I've created a customRepository to store user profile in my local database. 

but when trying to use Spatie can middleware I have this error thrown 

```
Symfony\Component\Debug\Exception\FatalThrowableError
Argument 1 passed to Spatie\Permission\PermissionRegistrar::Spatie\Permission\{closure}() must implement interface Illuminate\Contracts\Auth\Access\Authorizable, instance of Auth0\Login\Auth0User given, called in /code/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 487
```

I understand that the auth0user model doesn't implement the authorizable contract.

Question is, how can I work around this limitation? my first instinct was to bind the authorizable contract to the auth0user model but that didn't work.

```
$this->app->bind(
            \Illuminate\Contracts\Auth\Access\Authorizable::class,
            \Auth0\Login\Auth0User::class
        );
```

Help would be greatly appreciated

**Comment by drbyte** [comment]
Can you extend `Auth0\Login\Auth0User` into your own app, and in there implement the Authorizable contract? And then use that class for your users instead of `Auth0\Login\Auth0User` ?

**Comment by gitflash** [comment]
I was able to do it, using a custom user repository that extends the auth0 user repository and returns an eloquent User model that extends authorizable instead of an instance of the auth0user class.

I'll try to document that and push in a blog post. it might help somebody in the future. 

Thanks for the help

**Comment by marshmeloo** [comment]
@gitflash can you help me, I'm facing the same issue with auth0.

**Comment by gitflash** [comment]
@marshmeloo yes sure, 

so, first of all, you have to implement the auth0 customUserRepository , you'll find direction on how to do that in the auth0 Laravel integration quick start tutorial ( towards the end ).

once you do that, you'll have to tweak that repository a little bit ( see below )

```php
 /**
     * Get a User from the database using Auth0 profile information
     *
     * @param array $userinfo
     *
     * @return User
     */
    public function getUserByUserInfo( $userinfo ) {
        $user = $this->upsertUser( $userinfo['profile'] );
        return $user;
    }
```

lastly, you'll have to add the authorizable interface to your User model.

```php
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Contracts\Auth\Access\Authorizable;

class User extends Authenticatable
{
    use HasRoles;
```
that should be enough to get the user to authenticate through auth0 and use Spatie as role/perm management. 

hope that helps, 
Cheers

**Comment by marshmeloo** [comment]
Thanks @gitflash -- appreciate your sharing this simple workaround!
