### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead

### ISSUE THREAD

**Issue by camboYY** [spatie/laravel-permission#1337]

**Comment by drbyte** [comment]
This package does not require either `zendframework/zend-diactoros` or `laminas/laminas-diactoros`.
The message is coming from some other dependency in your project.

You can test it out by running `composer why zendframework/zend-diactoros`

**Comment by camboYY** [comment]
thanks
