### ISSUE TITLE
Installation error in Laravel 6.*

### ISSUE THREAD

**Issue by josiahmann** [spatie/laravel-permission#1338]
When installing on a fairly new Laravel installation I'm receiving the following error.

Trying` to access array offset on value of type null

this is happening in the registerModelBindings method on /spatie/laravel-permission/src/PermissionServiceProvider.php:61.

I'm wondering if this is happening because I moved my models to a Model folder?

**Comment by drbyte** [comment]
Sounds like maybe you haven't published the config file? Or it's damaged and not returning correct values?

**Comment by josiahmann** [comment]
Correct. I have not published the config files, I just ran the initial composer install command.

**Comment by drbyte** [comment]
Line 61 of that file is trying to bind to the named permission contract, as read from the config file.

Installation instructions:
https://docs.spatie.be/laravel-permission/v3/installation-laravel/

**Comment by josiahmann** [comment]
I see that it is, I'm just confused why that line is running when all I did was ran composer require.

Maybe it's this post-install script that's causing that "@php artisan package:discover --ansi"...

**Comment by drbyte** [comment]
Oh, I see.

I've never run into that situation on a fresh install.

**Comment by josiahmann** [comment]
Yea, I use it on multiple projects and haven't seen this.

**Comment by drbyte** [comment]
A fresh install now doesn't do it.

Is there something about your app that's already got a `config/permission.php` file that might be interfering.

**Comment by josiahmann** [comment]
No, there isn't but I was just now able to fix this and install properly by manually deleting the files in my bootstrap/cache folder. Thank you
