### ISSUE TITLE
Creating persmissions throws error

### ISSUE THREAD

**Issue by MathiasWeisheit** [spatie/laravel-permission#1339]
Hi, I will use your persmission lib.
It seems to be great work.

But I have a problem, creating a permission.
Can you help me?

Spatie\Permission\Exceptions\PermissionAlreadyExists  : A `view contacts` permission already exists for guard `api`.
```

  at /app/vendor/spatie/laravel-permission/src/Exceptions/PermissionAlreadyExists.php:11
     7| class PermissionAlreadyExists extends InvalidArgumentException
     8| {
     9|     public static function create(string $permissionName, string $guardName)
    10|     {
  > 11|         return new static("A `{$permissionName}` permission already exists for guard `{$guardName}`.");
    12|     }
    13| }
    14|

  Exception trace:

  1   Spatie\Permission\Exceptions\PermissionAlreadyExists::create("view contacts", "api")
      /app/vendor/spatie/laravel-permission/src/Models/Permission.php:40

  2   Spatie\Permission\Models\Permission::create(["view contacts", "api"])
      /app/database/seeds/PermissionTableSeeder.php:25

  Please use the argument -v to see more details.
```

**Comment by MathiasWeisheit** [comment]
<?php

use Illuminate\Database\Seeder;
use App\Role;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $roleUser = Role::where('name', 'Nutzer');
        $roleManager = Role::where('name', 'Manager');
        $roleAdministrator = Role::where('name', 'Administrator');

        if (isset($roleUser) && isset($roleManager) && isset($roleAdministrator) ){
            /*
             * contatcs permissions
             */
            **$permission = Permission::create(['name' => 'view contacts']);**
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'create contacts']);
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'edit contacts']);
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'delete contacts']);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);
            /*
             * projects permissions
             */
            $permission = Permission::create(['name' => 'view projects']);
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'create projects']);
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'edit projects']);
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'delete projects']);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);
            /*
             * users permissions
             */
            $permission = Permission::create(['name' => 'view users']);
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'create users']);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'edit users']);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'delete users']);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            /*
             * keyword permissions
             */
            $permission = Permission::create(['name' => 'view keywords']);
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'create keywords']);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'edit keywords']);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'delete keywords']);
            $permission->assignRole($roleAdministrator);

            /*
             * log permissions
             */
            $permission = Permission::create(['name' => 'view logs']);
            $permission->assignRole($roleUser);
            $permission->assignRole($roleManager);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'create logs']);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'edit logs']);
            $permission->assignRole($roleAdministrator);

            $permission = Permission::create(['name' => 'delete logs']);
            $permission->assignRole($roleAdministrator);
            /*
             * settings permissions
             */
            $permission = Permission::create(['name' => 'edit settings']);
            $permission->assignRole($roleAdministrator);


        }
    }
}

**Comment by MathiasWeisheit** [comment]
Hi, this was an the first run of the seeder, but I will check it again. I will also add an check of existance, bevor new creation.

**Comment by MathiasWeisheit** [comment]
That was not the problem. I deletet all db records and seeded again.

 Symfony\Component\Debug\Exception\FatalThrowableError  : Return value of Spatie\Permission\Models\Permission::getStoredRole() must implement interface Spatie\Permission\Contracts\Role, instance of Illuminate\Database\Eloquent\Builder returned

But my permession model looks so: 
https://docs.spatie.be/laravel-permission/v3/advanced-usage/extending/

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\ControlExtensionTrait;

class Permission extends \Spatie\Permission\Models\Permission
{
    use ControlExtensionTrait;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [
        'id','created_at','updated_at','created_by_id','updated_by_id',
    ];

     /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

     /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];
}`

**Comment by drbyte** [comment]
In your prior code post your seeder is using `use Spatie\Permission\Models\Permission;` not `App\Permission`. Is that still the case?

Also, what's in `ControlExtensionTrait`?

**Comment by MathiasWeisheit** [comment]
Hi, I set it back to the original classes to determine the error
use Illuminate\Database\Seeder;
//use App\Role;
use Spatie\Permission\Models\Role;
//use App\Permission;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

But it still does not work

It tried also as alternative
$roleUser->givePermissionTo($permission);

Error function givePermissionTo not found.

But in my Controllers for user and Roles 
$role->syncPermissions($permissions);
works fine.

**Comment by drbyte** [comment]
> $roleUser->givePermissionTo($permission);
> 
> Error function givePermissionTo not found.

`$roleUser` must be an instance of a User model which also has the `hasRoles` trait applied, else the `givePermissionTo` function won't exist on it.

**Comment by MathiasWeisheit** [comment]
I found the problem:

$roleUser, $roleManager and $roleAdministrators were array instead of model-objects:
```
$roleUser = Role::where('name', 'Nutzer');
$roleManager = Role::where('name', 'Manager');
$roleAdministrator = Role::where('name', 'Administrator');
```
I changed it to

```
$roleUser = Role::where('name', 'Nutzer')->first();
$roleManager = Role::where('name', 'Manager')->first();
$roleAdministrator = Role::where('name', 'Administrator')->first();
```
and the check to
`if ($roleUser != null && $roleManager != null && $roleAdministrator != null )`

Thanks for your help!

**Comment by drbyte** [comment]
Yes, that makes sense.
I considered that when you posted that error about receiving `Illuminate\Database\Eloquent\Builder`, but forgot to mention it in my reply. 

Glad you got it sorted out!
