### ISSUE TITLE
check permissions assinged to role by can() method

### ISSUE THREAD

**Issue by khendrickx** [spatie/laravel-permission#134]
In the documentation I read that the can() method can be used to check a permission:
> Saved permissions will be registered with the Illuminate\Auth\Access\Gate-class. So you can test if a user has a permission with Laravel's default can-function.

This indeed works when checking permissions registered to the user, but does not seems to consider permissions given to roles. The hasPermissionTo method does consider these permissions, but am I able to use can() as an alias for this?

```
class User extends CustomModel implements CanResetPasswordContract,
                                    AuthenticatableContract,
                                    AuthorizableContract
{
    use Authenticatable, CanResetPassword, SoftDeletes, HasRoles, Authorizable;
// ...
}
```
The CustomModel is just a class extending the Eloquent Model class.

**Comment by freekmurze** [comment]
[This test](https://github.com/spatie/laravel-permission/blob/56e3cb1/tests/GateTest.php#L26-L35) proves that the `can` function does consider permissions given to the role of a user.

What are you doing differently from this test?

**Comment by khendrickx** [comment]
I am not doing anything differently in my opinion. Following piece of code creates the permission, role and assigns it to the user. When I check the database I can find the relations between the role, permission and the user, so that seems OK as well.

The HasRoles trait does not implement the can method, but I assume the usage of Authorizable does cover this?
`
$permission = new Permission(['name' => 'edit-articles']);
$permission->save();

$role = new Role(['name' => 'edit']);
$role->save();

$role->givePermissionTo($permission);
User::find(2)->assignRole($role);

if (User::find(2)->can('edit-articles')){
            return 'ok';
}`

**Comment by freekmurze** [comment]
The `can` function is part of Laravel itself. Because this package registers all permission at Laravel's `Gate` you may you use the `can` function to check permissions.

**Comment by khendrickx** [comment]
Ok, tracked back the issue. Seems that the cache file (storage/cache/) does not always update and the `Gate` therefore could not check the permission.

Any idea if the cache issue is related to this package?

**Comment by freekmurze** [comment]
I do not think this problem is related to the package. Could you please submit a failing test, if you find out that the problem is caused by our code?

**Comment by khendrickx** [comment]
Digging further in the code, I noticed this function in PermissionRegistrar.php
```php
protected function getPermissions()
    {
        return $this->cache->rememberForever($this->cacheKey, function () {
            return app(Permission::class)->with('roles')->get();
        });
    }
```
To my understanding, using the `rememberForever` might cause the cache issue? Checking a permission of a user, then updating his permissions and re-checking might cause the `can` function to return `false` instead of `true`, doesn't it?

**Comment by sebacruz** [comment]
I am having the same issue with the cached permissions.

If you change the permissions and don't clean the cache it will return false positives.
