### ISSUE TITLE
If Role is a model then why does it have its own permissions table? Is this to make the package more flexible?

### ISSUE THREAD

**Issue by Ghustavh97** [spatie/laravel-permission#1340]
I'm planning on making Role.php share the model_has_permissions.php table with other models. I want to make sure that I'm not missing something critical for why it was done this way, so is this a good idea?

**Comment by drbyte** [comment]
This was raised in #1102 and there's an open PR #1112 which will probably become part of the next major version release.
If you architect with that in mind then you're probably going in the right direction!
