### ISSUE TITLE
How to manage this roles, permissions and restrictions

### ISSUE THREAD

**Issue by uicabpatweyler** [spatie/laravel-permission#1343]
I have 2 user roles: Super Administrator and Administrator.

I have created my custom models extending from: 
Spatie\Permission\Models\Role for the management of my Roles, the name model is Role
Spatie\Permission\Models\Permission for the management of my Permissions, the name model is Permission

I have add an aditional field called 'display_name', so that the role name and permission are not modified, and the user sees and edits the value of this field. So far, everything has worked. 

However, I would like to know if what I propose next is possible, or advise me that each role has specific permissions

The rol Super Administrator (the value of field 'display_name'), with name 'super-admin' (the value of field 'name'), can

- View all roles
- Create a new role
- Edit a role
- Delete a role

With the following restrictions:

- Cannot delete its own role

The rol Administrator (the value of field 'display_name'), with name 'admin' (the value of field 'name'), can

- View all roles (cannot view the role 'super-admin', in the display list)
- Create a new role 
- Edit a role (as long as it is not a role of super-admin) 
- Delete a role (as long as it is not a role of super-admin)

I would like to know if this is recommended, or advise separating permissions for each role. I still can't find a way to handle these two roles, along with the permissions and restrictions of each one

I appreciate your help, comments and suggestions.

**Comment by drbyte** [comment]
All those restrictions are rules that are best implemented in your own application logic. I'd probably focus on doing it with the Policies feature in Laravel.

**Comment by musapinar** [comment]
RolePolicy.php
```
    public function view(User $user, Role $role): bool
    {
        if ($role->name === 'super-admin') {
            return $user->isSuperAdmin();
        }

        if ($user->can('view any role')) {
            return true;
        }

        return false;
    }
```

whatever.blade.php : 
```
@foreach($roles as $role)
    @if (optional(auth()->user())->can('view', $role))
	    {{ $role->name }}
    @endif
@endforeach
```


A more elegant/flexible way imo would be to filter out the roles you pull from your db, via a ```scope``` + ```when()```  (https://github.com/illuminate/database/blob/master/Concerns/BuildsQueries.php#L147) + ```whereNot()```

example in a very different context :
https://i.imgur.com/P3ipAX9.png
replace ```auth()->check()``` with anything that would return a boolean, in your case most probably a ```! auth()->user()->can('whatever')````.
replace ```where``` with ```whereNot('name', 'super-admin')```
you get the idea

**Comment by uicabpatweyler** [comment]
Thanks @drbyte and @musapinar, they have given me many ideas to solve it
