### ISSUE TITLE
Extending to check permissions from another pivot table

### ISSUE THREAD

**Issue by woottonn** [spatie/laravel-permission#1345]
I've had some great support in this group, thanks so much for the support so far!

I am wondering if this is supported in laravel-permission..

_______________
**Current setup:** 
I have laravel-permission working great now. I can assign users to "view-users", "create-centre", "delete-centre" etc. Brilliant! 
_______________
**Requirement:** 
I have a pivot table that lists which users have access to which centre's.

![image](https://user-images.githubusercontent.com/6769984/73055688-43f62a00-3e85-11ea-81d9-8f076039e7f0.png)

I have a need to do a permission check to see if a user can see a centre.. something like..

`$user->hasPermissionTo('view-centre', $centre_id)`
...and...
`@can('view-centre',$centre_id)`
...and...
`$user->givePermissionTo('view-centre', $centre_id)`

Is this possible out of the box or do I need to start tinkering?
_______________

**Comment by drbyte** [comment]
> Is this possible out of the box or do I need to start tinkering?

Given that you're talking about a pivot table managed by your own app, you'll need to code your own access logic to integrate the extra relationships layer. 

One approach would be Model Policies. Your `@can('view-centre`, $centre_id)` check would likely change to `@can('view', Model)` and then your `view()` method in the model policy would check something general like `hasPermissionTo('view-centres')` and also check the `centre_id` relationship. 
You'd need to write your own method to grant an entry in your pivot table, or remove entries.
