### ISSUE TITLE
permission migrate file error 1103 Incorrect table name ''

### ISSUE THREAD

**Issue by mathula2504** [spatie/laravel-permission#1347]
Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(191) not null, `guard_name` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by drbyte** [comment]
It seems as though your `config/permissions.php` file has invalid data, or maybe you haven't published the config file?
