### ISSUE TITLE
Insert intermediate pivot table

### ISSUE THREAD

**Issue by nemo3000** [spatie/laravel-permission#1348]
I would like to insert a table between  Users and  the roles/permissions.
I would like something like this:
user1->new_table1->role1
user1->new_table2->role1
user1->new_table3->role2
Can anyone help me?

**Comment by musapinar** [comment]
You probably need a ```HasManyThrough()```
https://github.com/illuminate/database/blob/master/Eloquent/Relations/HasManyThrough.php

**Comment by nemo3000** [comment]
I have already created relations, but after this how can I pass parameters to filter intermediate table using can()? Now I do somthing like this: 
auth()->user()->intermediateTable($filterParameter)->first()->can('edit') 
work fine but I think is not the best practice. 
In some other posts I see can('edit',$filterParameter) using Gate::before in AuthServiceProvider, I tried work but seem to be only a work around.
