### ISSUE TITLE
assignrole() to other guard alongside web and api guard problem

### ISSUE THREAD

**Issue by Dictator1999** [spatie/laravel-permission#1349]
I have another guard name **customer** 

Default guard guard **web** does not work if use property `$guard_name = "customer"` in User model.
I want to to keep both guards.

#error
There is no role named `manager`. 
#manager guard name web.

**Comment by drbyte** [comment]
You didn't explain how you are using this and specifically where you are testing against multiple guards.

There are several provided methods in this package which allow you to override the default `guard` lookup by passing your own.

For example, `hasPermissionTo()` allows you to pass the name of the guard you are checking against. So do the `blade` directives. And others.

**Comment by Ir00man** [comment]
Just wanna reference my comment from closed issue - https://github.com/spatie/laravel-permission/issues/1265#issuecomment-583300401
If `config('auth.defaults.guard')` would have more respect, then we could manage multi guards on same model via middleware and different routes.

**Comment by drbyte** [comment]
@Dictator1999 @Ir00man 
Will the changes proposed in #1384 provide the fix you were seeking? 
Will it create any problems in your app (ie: breaking changes)?

**Comment by Daniyal-Javani** [comment]
Same problem, I think this is the related test
```
diff --git a/tests/RoleTest.php b/tests/RoleTest.php
index 207a4c6..7f4cbb9 100644
--- a/tests/RoleTest.php
+++ b/tests/RoleTest.php
@@ -232,4 +232,14 @@ class RoleTest extends TestCase
     {
         $this->assertEquals($this->app['config']->get('auth.defaults.guard'), $this->testUserRole->guard_name);
     }
+
+    /** @test */
+    public function it_can_assign_an_api_role()
+    {
+        app(Role::class)->create(['name' => 'test-role', 'guard_name' => 'api']);
+
+        $this->testUser->assignRole('test-role');
+
+        $this->assertTrue($this->testUser->hasRole('test-role'));
+    }
 }
```

What about getting optional guard_name while assigning role?
