### ISSUE TITLE
Check did role has not existing permission

### ISSUE THREAD

**Issue by rakieta2015** [spatie/laravel-permission#1350]
The problem occurs when I check if the role has permission. And this permission does not exist. I do this because I want to delete a permission when I don't know did the permission exists.

> 
         if($role->hasPermissionTo('some-permission')){
              $role->revokePermissionTo('some-permission');
         }

The content of this error: "There is no permission named `some-permission` for guard `web`." 
Is there an alternative method to check did the permission is assigned to a role?

**Comment by drbyte** [comment]
I'm puzzled: how do you know to remove a permission if that permission isn't even defined in your system?
Wouldn't it make sense to ensure that any permissions your application supports are already defined? It feels like that should be something your app handles at a higher-priority layer, long before you ever try to read or revoke permissions for a specific user/role.

If you disagree with my suggestion, that's fine: in such case you'll need to catch the exception in your own code, and/or check for the permission's existence (Eloquent `findByName`) before testing whether it is assigned.
