### ISSUE TITLE
There is no permission named `viewAny` for guard `web`

### ISSUE THREAD

**Issue by wave-light** [spatie/laravel-permission#1351]
I have created a policy for my ArticleController called ArticlePolicy

In AuthServiceProvider, I have registered the policy:
```
    protected $policies = [
        Article::class => ArticlePolicy::class,
    ];
```
And in the ArticleController constructor I have `$this->authorizeResource(Article::class, 'article');`

But when I try to view an article, I get the following exception:
```
`Spatie\Permission\Exceptions\PermissionDoesNotExist: 
There is no permission named `view` for guard `web`.
```

**Comment by drbyte** [comment]
At the risk of sounding obvious, the exception is telling you exactly the problem: there's no permission named `view` for the `web` guard.

When using permissions, first you have to actually create the permissions that you wish to use. 

When you use `authorizeResource` and Policies, Laravel automatically assumes various permission names. If you're going to rely on those names, then you'll need to consult the Laravel documentation on Policies and go create the names that the `authorizeResource` approach depends on.

As to the guard, the `web` guard is the "default" default. If you want a different default, there are override approaches listed in the documentation.

**Comment by wave-light** [comment]
Thanks for the reply. I had all of the permissions defined in my policy file.
I turns out the problem was, that I was not injecting the models into my controller methods, so `authorizeResource` did not work.
Instead, I added `$this->authorize` calls to each of my controller methods, eg in `create` method, I added `$this->authorize('create', Article::class);` and it now works!

**Comment by drbyte** [comment]
> Instead, I added `$this->authorize` calls to each of my controller methods, eg in `create` method, I added `$this->authorize('create', Article::class);` and it now works!

That's a perfectly suitable approach. I use that approach way more often than `authorizeResource`.

Thanks for posting back with your solution.
