### ISSUE TITLE
Call to undefined method App\Role::syncPermissions()

### ISSUE THREAD

**Issue by SohaibKtb** [spatie/laravel-permission#1352]
After creating a new role I get this BadMethodCallException, please help

**Comment by drbyte** [comment]
It seems you haven’t extended the base class.

**Comment by SohaibKtb** [comment]
you meen Role model in Spatie? @drbyte

**Comment by drbyte** [comment]
https://docs.spatie.be/laravel-permission/v3/advanced-usage/extending/

**Comment by SohaibKtb** [comment]
thank you, the problem is in RoleController I used App/Role First but I should use Spatie\Permission\Models\Role;
it works :)

**Comment by Ali-Hassan-Ali** [comment]
try use 
use Spatie\Permission\Models\Role;
not 
use App\Models\Role;
