### ISSUE TITLE
Assign roles to User from multiple Models' roles

### ISSUE THREAD

**Issue by Leon0983X** [spatie/laravel-permission#1353]
Hi,
so I'm working on a small private project and I'm still relatively new to laravel and web development in general so please bare with me.

My current situation is that I have the standard laravel _User Model_ which can have a corresponding Staff Model which can have a corresponding _Position Model_ (Position as in hierarchical position) and a corresponding _Department Model_. The Staff can be retrieved with a function in the _User_ class, which finds the staff entry in my database by looking for a userID. Then the _Position_ and _Department_ can again be retrieved from the Staff Model with functions.

Now the problem I have is that I don't want to assign those roles manually to each User but to automatically assign specific roles to each user depending on what _Department_ and _Position_ they have.

I would really appreciate if anyone could explain to me how I could get this to work!

EDIT: I just realised what I wrote isn't quite what I meant ^^ What I really want to achieve is not to really assign those roles to the user, but to be able to check if the User has a permission even though the role with the permission is only assigned to the Users‘ _Department_/_Position_ Model and not the User directly.

Here is a diagramm, which I hope makes clear what I mean:

![Role Structure](https://user-images.githubusercontent.com/12875800/73788546-7cf3a000-479d-11ea-957f-74f8bf3d89d7.png)

**Comment by musapinar** [comment]
I don't think you can achieve that with this library's current state.
You probably are going to need a custom function in your User model or trait that would run through steps such as this:

```
public function getUserAllPermissionsFromEverywhere(): Collection 
{
    $userDepartment = $this->staff()->department()->first();
    $userPosition = $this->staff()->position()->first();

    $departmentRoles = $userDepartment->roles;
    $positionRoles = $userPosition->roles;

    $userRoles = $departmentRoles->merge($positionRoles);
    $userPermissions = \DB::table('model_has_permissions')
        ->select(['permission_id'])
        ->where('model_type', Role::class)->whereIn('model_id', $userRoles->modelKeys())
        ->pluck('permission_id');

    return $userPermissions;
}
```

and then your custom permission checking function which would verify something like:
```
public function isAllowedToSeeIfHasPermission(Permission $permission): bool 
{
    return $this->getUserAllPermissionsFromEverywhere()->contains($permission);
}
```

finally, in your controller/policy:
```
if (auth()->user()->isAllowedToSeeIfHasPermission($thisPermissionIsRequired)) {
    dd('You are allowed to see this message.');
}
```

That would probably be my starting point.


You can heavily refactor this to save some lines, make it flexible, and more performant. I made it verbose so you can follow my logic hopefully.
For example this could be greatly improved having just 1 function that would take permission(s) as a parameter and then run just 1 sql request with joins against the supplied parameter and return a boolean.

**Comment by Leon0983X** [comment]
Hi, unfortunately I haven't had much time to try out your approach, but as far as I can tell it looks like a good starting point. So thanks a lot!

What I am now wondering is if it would be possible to implement this so you can check for the permission with blade directives and middleware but without directly assigning the permission to the user (with something like `$user->assignRole('permission');`?
Maybe a way to achieve this was to dynamically "inject" those permissions into however the permissions are looked up using blade directives/middleware, but I don't know if this would be possible?
