### ISSUE TITLE
Check permission through role in middleware

### ISSUE THREAD

**Issue by vgutnar** [spatie/laravel-permission#1354]
Hi,
Been searching through similar subject posts, but haven't found a clear answer.
If I assign permissions to role and then later assign the role to user, 
in middleware, can I check if user has the permission to perform the action? I would alway prefer to check by permission not role. Role would be for grouping the permissions.
I have a middleware in my __constructor, but unfortunately it doesn't work, it doesn't find the permission which has been assigned to the user role.
```
$this->middleware('permission:create user', ['only' => ['create','store']]);
```
If I check by Role, it will work.

Is it possible to check permission through Role(s)?
If it is possible, any quick tips on how to set it up?
Thank you so much.

**Comment by musapinar** [comment]
what's your code to "check by Role"?

Yes, the code you posted does exactly that already. It checks for all direct permissions assigned to the user + all the permissions the user inherits from all his roles.

**Comment by vgutnar** [comment]
"check by Role" line was/is like this:
```
$this->middleware('Role:Administrator', ['only' => ['create','store']]);
```
User has an Administrator role, and that role has 'create user` permission assigned to it.

**Comment by vgutnar** [comment]
I do want to mention hat in the application I have two guards web and admin. That is just so I can maintain two different logging areas user and admin.
All roles are saved with `web` guard. User is also logging in and using application through/with default `web` guard.
Below is a snippet from config->auth.php
```
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],
```
I am not sure, is that's what is messing things up. I did commented out the `Admin` guard, but still get the same  `403 | User does not have the right permissions.`

**Comment by vgutnar** [comment]
@musapinar any tips on how I could troubleshoot/debug? I did created a middleware with the same code in it as Spoties `permissions` middleware , just so I can play/test. But it yields the same results.

**Comment by musapinar** [comment]
can you run ```php artisan permission:cache-reset``` ?

can you enable ```display_permission_in_exception``` to ```true``` in the config? What does the 403 says then?

**Comment by musapinar** [comment]
> 
> In `User` class, I noticed that the `HasPermissions` don't make any difference. Looks to me that Spatie is using only the `HasRoles` trait. I am not sure is that's how it should be that Spatie is using only `HasRoles`?

You only need ```HasRoles```. That's because trait ```HasRoles``` uses trait ```HasPermissions``` itself already.

```
trait HasRoles
{
    use HasPermissions;

...
```

**Comment by vgutnar** [comment]
Hmm...., I did ran the artisan command and enabled the `display_permission_in_exception `, but still I am getting:
```
403 | User does not have the right permissions. Necessary permissions are view user

```

**Comment by vgutnar** [comment]
Here is what I have in `UserController`
```
class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:view user');
        $this->middleware('permission:create user', ['only' => ['create','store']]);
        $this->middleware('permission:update user', ['only' => ['edit','update']]);
        $this->middleware('permission:delete user', ['only' => ['destroy']]);
```

**Comment by musapinar** [comment]
change ```$this->middleware('permission:view user');``` to ```$this->middleware('permission:view user', ['only' => ['index']]);```

**Comment by vgutnar** [comment]
Here is what I have in roles db table:
![image](https://user-images.githubusercontent.com/22861346/74073088-db976480-49bd-11ea-855e-94fc39043069.png)
And here is what I have in model_has_roles db table:
![image](https://user-images.githubusercontent.com/22861346/74073126-084b7c00-49be-11ea-9b89-99bcde49df1f.png)

**Comment by vgutnar** [comment]
> change `$this->middleware('permission:view user');` to `$this->middleware('permission:view user', ['only' => ['index']]);`

Bummer still the same `403`. Also did the catch clearing. 
Inside blade `@can('view user')`, it is not working.

**Comment by musapinar** [comment]
Well then your Administrator has the ```create user``` but not the ```view user``` permission yet. 
You must assign permission to ```view user``` for your Administrator. 

This code here: 
```$this->middleware('permission:view user');```
means: I require the user to have the permission ```view user``` for ALL my methods (```index()``` , ```create()```, ```store()```, ```edit()```, ```update()```, ```destroy()```, etc)  

Can you show what's inside your ```model_has_permissions``` or ```role_has_permissions``` table?

**Comment by vgutnar** [comment]
@musapinar , now I feel very embersed :), that was the mistake. 
I had a mess up in my `model_has_roles` table
It is working now. Thank you so much @musapinar
