### ISSUE TITLE
Psalm crashing on parsing HasRoles and HasPermissions traits

### ISSUE THREAD

**Issue by SiebeVE** [spatie/laravel-permission#1357]
When running the latest Psalm on my project, it crashes. See https://github.com/vimeo/psalm/issues/2784.

Although this isn't a problem with this package, it could easily be fixed by adding a doc block to:
- laravel-permission/src/Traits/HasPermissions.php:310
- laravel-permission/src/Traits/HasRoles.php:118

Is this something that could be merged, or do you rather want to wait and see if psalm can fix the issue?

**Comment by SiebeVE** [comment]
Psalm has fixed the issue 🎉

**Comment by stryaponoff** [comment]
The problem still exists for me.
I'm using Psalm 3.9.3 and laravel-permission 3.8.0.

**Comment by SiebeVE** [comment]
I can confirm the issue is still there.

**Comment by SiebeVE** [comment]
They have fixed it again 🎉🎉
