### ISSUE TITLE
base table or view already exists

### ISSUE THREAD

**Issue by qi891011** [spatie/laravel-permission#1359]
Executing PHP artisan migrate in laravel 6.14.0
Error reporting: sqlstate [42s01]: base table or view already exists:

What's the reason??
================================================
laravel中 执行 php artisan migrate
报错 Illuminate\Database\QueryException  : SQLSTATE[42S01]: Base table or view already exists:

请问这是什么原因？？

**Comment by drbyte** [comment]
The message `Base table or view already exists` means exactly what it says: whatever table your migration was trying to create is already present in your database.

Perhaps you have duplicate migrations for the same thing?

Or perhaps your app already has tables named the same as what a new migration is trying to add.
