### ISSUE TITLE
Blade directive does not work on Laravel 5.3

### ISSUE THREAD

**Issue by caleboki** [spatie/laravel-permission#136]
Blade directives is not parsed in my View when running Laravel 5.3. However it works fine on Laravel 5.2 This is the code:

```
@section('content')
<div class="container">
	
	<h1>{{ $post->title }}</h1>
	<hr>
	<p class="lead">{{ $post->body }} </p>
	<hr>
	{!! Form::open(['method' => 'DELETE', 'route' => ['posts.destroy', $post->id] ]) !!}
	<a href="{{ url()->previous() }}" class="btn btn-primary">Back</a>
	@haspermission('Edit Post')
	<a href="{{ route('posts.edit', $post->id) }}" class="btn btn-info" role="button">Edit</a>
	@endhaspermission
	@haspermission('Delete Post')
	{!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
	@endhaspermission
	{!! Form::close() !!}

</div>
 @endsection
```

And this is what I get when I run the application

![spatie](https://cloud.githubusercontent.com/assets/1192358/20181826/fcae3382-a75f-11e6-8f87-3b7a26ab3f64.jpg)

**Comment by warlord0** [comment]
`@can` and `@endcan` ?

**Comment by caleboki** [comment]
@warlord0 what do you mean?

**Comment by warlord0** [comment]
There is no `@haspermission`. it's `@can`

There's a `@hasrole` - see here https://github.com/spatie/laravel-permission#using-blade-directives
