### ISSUE TITLE
issue on php7.4

### ISSUE THREAD

**Issue by imedev** [spatie/laravel-permission#1360]
ErrorException  : Trying to access array offset on value of type null

**Comment by drbyte** [comment]
Not enough information to go on. 
Looks very much like an error in your app, not with this package.

**Comment by frknasir** [comment]
i think what you might do here is 

1. composer update
2. create `permission.php` file in config folder. copy and paste default contents from here https://github.com/spatie/laravel-permission/blob/master/config/permission.php
3. then run composer require spatie/laravel-permission

this did it for me!

**Comment by imedev** [comment]
Thanks @frknasir
