### ISSUE TITLE
Validation on Proper

### ISSUE THREAD

**Issue by tecbeast42** [spatie/laravel-permission#1361]
I would like to use validations like this:

```
 'field' => 'permission:p1,p2,p3', // needs to have all permissions
 'field' => 'any_permission:p1,p2,p3', // neds to have one of the permissions
 'field' => 'role:p1,p2,p3', // needs to have one role
 'field' => 'any_role:p1,p2,p3', // needs to have one of the roles
```

Would there be an interesset to add such feature/PR?

**Comment by drbyte** [comment]
I'm not sure I understand your use-case. Care to elaborate? 
How do you test whether a `field` has been assigned a role or permission, when to test them requires that they be representative of an Eloquent object?

**Comment by tecbeast42** [comment]
Lets say we have a Model that represents a blog post. 

To edit the model you would have permission or role abc.

```
[
  'body' => 'some text',
  'editable' => 'some boolean', // to change this i need to have permission or role xyz
]
```

In general it is for fields that are more restricted then the others.

**Comment by drbyte** [comment]
I'd probably create a custom validation rule that calls a method in the Model Policy where I've defined the business rules that determine whether the user has edit rights to that field. Those business rules might check against certain permissions on the Gate (`can()`) or unique to this package (`hasPermissionTo()`), perhaps along with other app-related criteria.

One could say that using a model policy might be overkill, but given the complexity of the examples you provided I imagine you've got lots of other gate-related checks to do so the Policy is a logical abstraction of those details.
But, if you wanted to just jump directly to a [custom Laravel validation rule](https://laravel.com/docs/validation#custom-validation-rules) that simply calls `can()` or `hasPermissionTo()` that would work also.

**Comment by sooxt98** [comment]
Awwww i need this too

**Comment by Mohamed1Gohar** [comment]
i need this also
