### ISSUE TITLE
Swoole and permissions

### ISSUE THREAD

**Issue by haught** [spatie/laravel-permission#1365]
Laravel version: 5.8.36
Package version: 3.6.0
PHP version: 7.4.0
laravel-swoole: 2.6.66

Part of swoole config:
```
'providers' => [
    Illuminate\Pagination\PaginationServiceProvider::class,
    Illuminate\Auth\AuthServiceProvider::class,
    App\Providers\AuthServiceProvider::class,
    Spatie\Permission\PermissionServiceProvider::class,
    Tymon\JWTAuth\Providers\LaravelServiceProvider::class,
],
```

When adding or removing a permission from a role, the permission is not reflected in the app for the user. The app has the permission set in the route. Restarting swoole after a permission change fixes things.

When debugging getPermissions() in src/PermissionRegistrar.php, it appears that $this->permissions is being reused between requests. The first request after a restart gets/puts the cache, but in all subsequent requests $this->permissions is not null and used. So even clearing the cache causes it to happily use the first copy of permissions it got.

When not running in swoole, getPermissions() hits the cache for each request.

Any idea how to remedy this?

**Comment by drbyte** [comment]
@codercms, @Beshelmek have you run into this problem?

**Comment by codercms** [comment]
@drbyte Yes, I faced a similar problem.
@haught You should to clean cache manually after the roles/permissions modification, try to call this method -  https://github.com/spatie/laravel-permission/blob/master/src/PermissionRegistrar.php#L100

**Comment by drbyte** [comment]
@codercms That's interesting, since after a role/permission modification this package already resets the cache:
https://github.com/spatie/laravel-permission/blob/3aff5437b3e66e877dcc3158f6cfaaced8e468ab/src/Traits/HasPermissions.php#L317
(unless you're editing the db tables directly)

**Comment by codercms** [comment]
@drbyte You are right, I can't reproduce this issue with a fresh installation of Laravel + LaravelSwoole + LaravelPermissions.

I created a simple controller to test this issue.
```php
declare(strict_types=1);

namespace App\Http\Controllers;

use Illuminate\Http\JsonResponse;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class TestController
{
    public function index(PermissionRegistrar $registrar)
    {
        return new JsonResponse(['permissions' => $registrar->getPermissions()]);
    }

    public function store(PermissionRegistrar $registrar)
    {
        $permission = Permission::findOrCreate('some_permission');

        /* @var Role $role */
        $role = Role::findOrCreate('some_role');
        $role->givePermissionTo($permission);

        return new JsonResponse(['permissions' => $registrar->getPermissions()]);
    }

    public function delete(PermissionRegistrar $registrar)
    {
        $role = Role::findByName('some_role');
        $permission = Permission::findByName('some_permission');

        $role->revokePermissionTo($permission);

        return new JsonResponse(['permissions' => $registrar->getPermissions()]);
    }
}
```

My test scenario:
0. Set swoole workers count to 1
1. Call the "index" action, permissions must be empty
2. Call the "store" action, permissions must NOT be empty and role MUST be assigned
3. Call the "index" action, response must match with previous response from the "store" action
4. Call the "delete" action, permissions must NOT be empty and role must disappear
5. Call the "index" action, response must match with previous response from the "delete" action

**Comment by drbyte** [comment]
Thanks @codercms

**Comment by haught** [comment]
So if Swoole runs multiple worker processes, a forgetCachedPermissions() only sets $this->permissions = null in that process that you run it in. I think that might be where the test case is not showing the problem. If I have already pulled the permissions in a second worker, it doesn't get cleared out.

I change the role's permission in a web route in a browser, while testing the api route permission  in postman. Now I understand the rare success I was seeing randomly.  I have confirmed this by setting worker_num = 1 in the swoole config.

**Comment by codercms** [comment]
@haught I see your point. This issue is related to the multi-process cache management.
@drbyte I can explain now what is going wrong. One of main benefits of Swoole is that the application is not restarted for every request, but instead it always persists in the memory.
So the case is: If we have 2 application processes running, and we are going to change the permissions, the request is handled by process A, but permission's cache is not going to be flushed in the process B if permissions were loaded at least once.

**Comment by codercms** [comment]
@drbyte The cache of permissions will not be changed because of - https://github.com/spatie/laravel-permission/blob/3aff5437b3e66e877dcc3158f6cfaaced8e468ab/src/PermissionRegistrar.php#L116

RAM cache is used, it means that every process has it's own cache.

**Comment by drbyte** [comment]
I'd entertain a tested PR that resolves this and remains backward compatible with apps not using Swoole.

The PermissionRegistrar is "doing a lot", and perhaps an intermediate step would be a refactor to extract the Cache features, which isn't necessarily specific to this issue. I'm mindful that some of the public methods might be affected, which could introduce breaking changes ... which I'd like to avoid.
