### ISSUE TITLE
Class 'Illuminate\Routing\Route' not found in backend/vendor/spatie/laravel-permission/src/PermissionServiceProvider.php:120

### ISSUE THREAD

**Issue by jekabsmilbrets** [spatie/laravel-permission#1372]
Just now updated Composer:
Package operations: 0 installs, 38 updates, 0 removals
  - Updating symfony/polyfill-ctype (v1.13.1 => v1.14.0): Downloading (100%)         
  - Updating symfony/polyfill-php72 (v1.13.1 => v1.14.0): Downloading (100%)         
  - Updating symfony/polyfill-mbstring (v1.13.1 => v1.14.0): Downloading (100%)         
  - Updating symfony/polyfill-intl-idn (v1.13.1 => v1.14.0): Downloading (100%)         
  - Updating symfony/polyfill-php73 (v1.13.1 => v1.14.0): Downloading (100%)         
  - Updating nesbot/carbon (2.29.1 => 2.30.0): Downloading (100%)         
  - Updating egulias/email-validator (2.1.15 => 2.1.17): Downloading (100%)         
  - Updating illuminate/contracts (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/support (v6.15.0 => v6.15.1): Downloading (100%)         
  - Updating illuminate/log (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/filesystem (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/container (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/events (v6.15.0 => v6.15.1): Downloading (100%)         
  - Updating illuminate/view (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/translation (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/validation (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/pipeline (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/database (v6.15.0 => v6.15.1): Downloading (100%)         
  - Updating illuminate/console (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/queue (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/pagination (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/session (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/http (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/hashing (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/encryption (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/config (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/cache (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/bus (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/broadcasting (v6.15.0 => v6.15.1): Loading from cache
  - Updating illuminate/auth (v6.15.0 => v6.15.1): Loading from cache
  **- Updating laravel/lumen-framework (v6.3.3 => v6.3.4): Downloading (100%)**         
  - Updating symfony/polyfill-php70 (v1.13.1 => v1.14.0): Downloading (100%)         
  - Updating illuminate/cookie (v6.15.0 => v6.15.1): Loading from cache
  - Updating laravel/passport (v8.3.1 => v8.4.0): Downloading (100%)         
  **- Updating spatie/laravel-permission (3.6.0 => 3.7.1): Downloading (100%)**         
  - Updating composer/spdx-licenses (1.5.2 => 1.5.3): Downloading (100%)         
  - Updating seld/phar-utils (1.0.2 => 1.1.0): Downloading (100%)         
  - Updating webmozart/assert (1.6.0 => 1.7.0): Downloading (100%)  

 and got this error when trying to run artisan

Class 'Illuminate\Routing\Route' not found in backend/vendor/spatie/laravel-permission/src/PermissionServiceProvider.php:120

**Comment by drbyte** [comment]
Looks like the simplification of testing for Lumen support got mixed up because you've added something else to your app that satisfies the test used.

v3.7.2 has been released to resolve this by being more explicit about the dependency.

**Comment by drbyte** [comment]
Closed by 777d027e750ecefb6e23995f4012ccfc82c81e9d
