### ISSUE TITLE
No migrations file

### ISSUE THREAD

**Issue by boutzamat** [spatie/laravel-permission#1374]
First of all, thanks for your great contributions to Laravel.

I just installed this package using Composer, but i don't get a migration file with it.
What's strange is that composer require, takes for ever with this package, as the only one. Every other composer require is fast as usual. I don't know if it has anything to do with it, and if it is only a local issue.

**Comment by drbyte** [comment]
> I just installed this package using Composer, but i don't get a migration file with it.

You are correct. The migration file gets created the same way most packages provide their migrations: by publishing the assets provided by the package, using the `artisan vendor:publish` command.

This is explained in the package documentation, for which there's a link in the README.

<img width="1063" alt="Screen Shot 2020-02-17 at 5 40 33 PM" src="https://user-images.githubusercontent.com/404472/74690379-e071ca80-51ac-11ea-812d-ac5db3660ac2.png">

**Comment by boutzamat** [comment]
I wasn't aware of this. The packages I used before came with migrations. I'm fairly new to Laravel. I apologize 😅

**Comment by drbyte** [comment]
No worries. You'll find this same pattern used with most packages.
