### ISSUE TITLE
A role How to revoke multiple permissions?

### ISSUE THREAD

**Issue by xlkit456852** [spatie/laravel-permission#1375]
I use syncPermissions() to sync permissions first ,but it 's  slow ,so I think may be I can use array_diff() to get the difference between the old permission and new permission . And then I can use givePermissionTo() and revokePermissionTo() to add new permission. and delete the unwanted perissions.

And then I find that I can use givePermissionTo([1,2,3...ids]) to add multiple permission ids ,but when I use revokePermissionTo([1,2,3...ids]) to delete multiple permission ids ,it doesn't work  ,no error but none of the the unwanted perissions was deleted. So currently I only can delete the role permission pivot table row directly .  Is there any idea to handle this ? Thanks~

**Comment by drbyte** [comment]
While `givePermissionTo()` accepts more than one, `revokePermissionTo()` does not.

Behind the scenes both use `syncPermissions` which also handles reloading the relationships and resetting the cache.
https://github.com/spatie/laravel-permission/blob/4407533a6cbf665be947d1f33d4490a35705a9fe/src/Traits/HasPermissions.php#L276-L352

I suppose if you wanted a fast way to delete all existing permissions for that relation you could call `detach()` first. And then follow that with `givePermissionTo()` to add what's needed and to set the cache and update the relationships.

**Comment by xlkit456852** [comment]
Thanks so much , now I use HasPermissions in my role model . And use the following code to update permissions:
```
if($need_delete_ids && count($need_delete_ids)>0){
    $role->permissions()->detach($need_delete_ids);
    $role->forgetCachedPermissions();
    $role->load('permissions');
}
if($need_add_ids && count($need_add_ids)>0){
    $role->permissions()->attach($need_add_ids);
    $role->forgetCachedPermissions();
    $role->load('permissions');
}
```
