### ISSUE TITLE
Middleware allowing multiple roles

### ISSUE THREAD

**Issue by notflip** [spatie/laravel-permission#138]
For some reason 

    'middleware' => ['role:admin', 'role:other']]

is returning "403" status, any ideas what I might be doing wrong?

Thanks

**Comment by freekmurze** [comment]
I'd try to set some `dd` statements in your middleware to see where exactly the 403 is generated and what value the middleware receives.

**Comment by notflip** [comment]
Well I'm using the middleware from the example in the README.md
But so the syntax I posted is correct? Then I'll look further. 

Thank you

**Comment by freekmurze** [comment]
Try this:

```php
... 'middleware' => ['role:admin,other'] ...
```

**Comment by notflip** [comment]
That's also not working, I guess because in the Middleware we're only expecting one role? 
Or am I wrong here?

![role](https://cloud.githubusercontent.com/assets/4146384/20622263/4be87a18-b302-11e6-97ca-d4b2fc8dd05b.jpg)


Thank you!

**Comment by notflip** [comment]
Solved by using: 

```
    public function handle($request, Closure $next, $role, $role2)
    {
        if(Auth::guest()) {
            return redirect()->route('login');
        }

        if(! $request->user()->hasRole($role) && ! $request->user()->hasRole($role2)) {
            abort(403);
        }

        return $next($request);
    }
```

Thanks!
