### ISSUE TITLE
What function should I use to create a new permission and sync it to a role??

### ISSUE THREAD

**Issue by raylucker** [spatie/laravel-permission#1380]
It's been a year and the only thing that works only to create a new database do a migration then seed the database with the new permissions added to the permission table seeder then run the syncpermission function with the new permission also.

Please help :(

**Comment by drbyte** [comment]
> What function should I use to create a new permission and sync it to a role??

Basic operations such as those are all explained in the documentation:
https://docs.spatie.be/laravel-permission/v3/basic-usage/basic-usage/
