### ISSUE TITLE
Update Permission In Role

### ISSUE THREAD

**Issue by perspolise** [spatie/laravel-permission#1382]
I add permission to role from admin form like this:

` 
        Permission::create(['name' => $request->input('name')]);

        foreach($request->roles as $role) {

            Role::findByid($role)->givePermissionTo($request->get('name'));

        }
`

this worked true and insert permission to role But Now I need to update method(edit form) for edit permission in role. How do can i update permission in role?!

**Comment by drbyte** [comment]
Permissions and Roles are regular Laravel Eloquent objects. So you can retrieve and rename them the same as any Eloquent object:

```php
$permission = Permission::where('name', $oldName)->first();
$permission->name = $newName;
$permission->save();
```

Or, if you want to remove a permission from a role, you can `revokePermissionTo($name)`;

Other related functions provided by this package are in the documentation: https://docs.spatie.be/laravel-permission/v3/basic-usage/basic-usage/

**Comment by perspolise** [comment]
@drbyte Thanks. for multiple select checkbox:

`
    foreach($request->roles as $role) {

        Role::findByid($role)->revokePermissionTo($request->get('name'));

    }
`

this code not work true and remove all input select box value in loop.

**Comment by drbyte** [comment]
It seems you have an error in your application. 
Perhaps your request variables are incorrect (ie: are you passing $role or $role->id).
Best to dump out the variables and try individual commands manually. Doing the debugging will help you identify the wrong values you're receiving or passing.

**Comment by perspolise** [comment]
@drbyte : I dont have any error. My problem when I need to update multiple roles for one permission. in example: for update multiple permission in one role i work with `syncPermission` and this function work  true. Now i think we need to any sync function for update multiple roles in permission Or first remove all role for permission then insert multiple checked value using `givePermissionTo` .

**Comment by drbyte** [comment]
>  for update multiple permission in one role i work with `syncPermission` and this function work true. Now i think we need to any sync function for update multiple roles in permission Or first remove all role for permission then insert new multiple checked value using `givePermissionTo`

I'm not sure I fully understand you. If you know which roles you want to sync to a permission, you can call `syncRoles()`.
