### ISSUE TITLE
How to retrieve users without any assigned role?

### ISSUE THREAD

**Issue by faizanshahid96** [spatie/laravel-permission#1383]
How to retrieve users without any assigned role?

**Comment by drbyte** [comment]
You can leverage the Eloquent relations to find the users without the relationship by querying the count of those who "do" have the relationship, where the count is 0:

```php
use \App\User;
use \Spatie\Permission\Models\Role;
$usersWithoutRoles = User::withCount('roles')->has('roles', 0)->get();
```

**Comment by musapinar** [comment]
```User::doesntHave('roles')->get();```
