### ISSUE TITLE
Add spatie / laravel-activitylog with log relational model activities 

### ISSUE THREAD

**Issue by Mahmoudjs** [spatie/laravel-permission#1385]
Hi, 
I am using spatie permission package and spatie activitylog package, 
I extend Role and Permission model and get activity logs for the changes makes directly on both,
but no luck with saving the relational model such ( role_has_permissions, model_has_roles & model_has_permissions).
any help in this case?
Thank's

**Comment by drbyte** [comment]
Some considerations for this were discussed at https://github.com/spatie/laravel-activitylog/issues/599
