### ISSUE TITLE
Check on user attribute for logged in user

### ISSUE THREAD

**Issue by iamniels** [spatie/laravel-permission#1388]
I have added the attribute `active` to the User model. I only want to allow Users where `active = true` to be able to login. What is the best approach in Laravel 6 with Spatie/ Laravel permissions?

**Comment by drbyte** [comment]
I wouldn't use this package for that at all. 

This package provides features related to `authorization`, specifically through storing polymorphic relations in pivot tables, not on the model itself.

What you're asking for is more related to `authentication`, even though it intersects slightly with an `authorization` "ability" feature.

I think the best approach would be to do something similar to Laravel's built-in email-validation feature, which blocks people from logging in where they don't have a verified email address.

It's implemented via the `MustVerifyEmail` trait and the `EnsureEmailIsVerified ` middleware:

https://github.com/laravel/framework/blob/346bfc2b0131a00395f8e35c41d4d7a252e07dea/src/Illuminate/Auth/MustVerifyEmail.php#L9-L17

https://github.com/laravel/framework/blob/346bfc2b0131a00395f8e35c41d4d7a252e07dea/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php#L23

You're doing pretty much the same thing.

Alternatively you might try protecting your routes with a `can:login_only_active_users` middleware rule, and then define the rule by adding this in a service provider:
```php
Gate::define('login_only_active_users', function ($user) {
    return $user->active == true;
});
```
See:
https://laravel.com/docs/master/authorization#writing-gates
https://laracasts.com/series/laravel-6-from-scratch/episodes/51

**Comment by iamniels** [comment]
@drbyte Thanks for pointing me in the right direction!
