### ISSUE TITLE
Wilcard Permission (There is no permission named `users.*` for guard `web` )

### ISSUE THREAD

**Issue by loicgeek** [spatie/laravel-permission#1389]
I'm trying to use wilcard permission, but i got permission 
``` 
$loic = User::find(1)->first();
$loic->givePermissionTo('users.*');
echo $loic->permissions;
error: There is no permission named `users.*` for guard `web` 
```
So do i need to create that permission first ? I could i do that please ?

**Comment by drbyte** [comment]
Yes, you must create the permission in order to grant it to someone.

**Comment by loicgeek** [comment]
Okay, i would like to add an observer when creating a new model, what do you think about? Basically, i would like to allow deleting  review by only the owner and super admin. So i must create a premission for each entry? Like review.*.id?

**Comment by drbyte** [comment]
> i would like to allow [some action] by only the owner and super admin.

The best way to do that is unrelated to this package.

For super-admins, do that in its own rule in a service-provider:
https://docs.spatie.be/laravel-permission/v3/basic-usage/super-admin/

For delete-only-by-owner, use model policies:
https://laravel.com/docs/authorization#creating-policies
https://docs.spatie.be/laravel-permission/v3/best-practices/using-policies/
https://laracasts.com/series/laravel-6-from-scratch/episodes/51

**Comment by loicgeek** [comment]
> do that in its own ru

Thanks a lot for your time sir
