### ISSUE TITLE
How to apply one Permission to array of Roles

### ISSUE THREAD

**Issue by whfamily2006** [spatie/laravel-permission#139]
is there any way/method exists like zizaco/entrust that we can assign array of roles to one permission...?

`$branch=Permission::create(['name' => 'branch_lock','display_name' => 'Batch Lock']);`
`$branch->roles()->attach(array(1,2,3,4,5));`

**Comment by freekmurze** [comment]
`roles` on `Permission` returns a `\Illuminate\Database\Eloquent\Relations\BelongsToMany` relation so you could probably just use that `attach` method in your example.
