### ISSUE TITLE
Add Title Slug description for each role & permission

### ISSUE THREAD

**Issue by Avinar** [spatie/laravel-permission#1390]
I think for better view(role and permission tasks) you need add (Title , Slug , Description) for each  role and permission like This:

Permission: 
title: `Add User`  Slug: `add-user`  Description: `User Can add ...`
Role:
title: `Administrator`  Slug: `administrator`  Description:` This Role Is High Level ...`

**Comment by drbyte** [comment]
Hi @Avinar 
Thanks for your suggestion.

There are no plans to force that complexity onto all users of this package.

However, you can certainly implement it inside your own app by extending the models to add those additional fields. You may find the documentation page helpful for that: https://docs.spatie.be/laravel-permission/v3/advanced-usage/extending/
