### ISSUE TITLE
Uses wrong database when a non-default $connection value is assigned to the \Auth\User model

### ISSUE THREAD

**Issue by leafling** [spatie/laravel-permission#1391]
I'm assigning a connection other than the default connection in my \Auth\User model, but laravel-permission appears to use the default connection for the following commands.

```
$user->can('do something');
$user->hasPermissionTo('do something')
```
Both of those will fail with:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.permissions' doesn't exist (SQL: select * from `permissions`)
```
When is should be using a different database...

The following all work correctly, and show the appropriate response based on the assigned (non-default) $connection in the \Auth\User model:
```
$user->permissions;
$user->roles;
$user->getConnectionName();
$user->getConnection()->getDatabaseName();
```
In my troubleshooting, I found that if I add a line to the config file and edit the file
/spatie/laravel-permission/src/Mode/Permission.php
and add a line to the constructor like this it will work
```
$this->setConnection(config('permission.connection'));
```
That works in a pinch, but I don't think that is the correct solution as it should use the $connection assigned within the \App\User model.

**Comment by drbyte** [comment]
I think the last time I needed to do that I simply extended the Permission model into my own App space, and set my connection there. Then in the permission.php config file tell it to use my permission model from my namespace.
