### ISSUE TITLE
Cache Role-Permission query cache

### ISSUE THREAD

**Issue by nasirkhan** [spatie/laravel-permission#1392]
On every page of the application the Laravel debugger shows that the follow two queries is running. Roles and Permissions have not changed so often and i want to cache these queries. Can you please let me know how can i do so?

```sql

select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = 1 and `model_has_roles`.`model_type` = 'App\Models\User'

select `permissions`.*, `model_has_permissions`.`model_id` as `pivot_model_id`, `model_has_permissions`.`permission_id` as `pivot_permission_id`, `model_has_permissions`.`model_type` as `pivot_model_type` from `permissions` inner join `model_has_permissions` on `permissions`.`id` = `model_has_permissions`.`permission_id` where `model_has_permissions`.`model_id` = 1 and `model_has_permissions`.`model_type` = 'App\Models\User'

```

**Comment by nasirkhan** [comment]
anyone have any solution for the issue i am facing here?

**Comment by serg1k312** [comment]
I used Eloquent [Accessors](https://laravel.com/docs/5.8/eloquent-mutators#accessors-and-mutators) which override this methods ( [roles ](https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L40) and [permissions ](https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasPermissions.php#L43) )
Maybe this is not the best solution, but I did not find another. :)

```php
// User.php

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class User {
  // Cache permissions and roles
  public function getPermissionsAttribute() {
    $permissions = Cache::rememberForever('permissions_cache', function() {
      return Permission::select('permissions.*', 'model_has_permissions.*')
        ->join('model_has_permissions', 'permissions.id', '=', 'model_has_permissions.permission_id')
        ->get();
    });

    return $permissions->where('model_id', $this->id);
  }

  public function getRolesAttribute() {
    $roles = Cache::rememberForever('roles_cache', function () {
        return Role::select('roles.*', 'model_has_roles.*')
        ->join('model_has_roles', 'roles.id', '=', 'model_has_roles.role_id')
        ->get();
    });

    return $roles->where('model_id', $this->id);
  }
}
```
Sorry for my English -_-

**Comment by nasirkhan** [comment]
Thank you for posting a solution. I home many other will be benefited by your code.

**Comment by jeanali** [comment]
Same issue!

**Comment by Crouxie** [comment]
I am using latest version of package 4.0.0 and issue is still there. Can you please check it?

**Comment by tonnerre33** [comment]
Hello, i am using v5.3.1 and i got the same issue. 
Do you have any tip for a correct use ?
I tried using 'with' in eloquent query but i got one request by can function
![image](https://user-images.githubusercontent.com/11009185/141679847-dea29600-8801-4046-bf47-8a35cd4454c0.png)

**Comment by CircleCurve** [comment]
Yeah in the latest version, It still happen this issue

**Comment by erikn69** [comment]
@CircleCurve it is not an issue, it is an expected behavior

Maybe this PR helps you to cache user roles/permissions https://github.com/spatie/laravel-permission/pull/1833#issuecomment-1021289525
