### ISSUE TITLE
Middleware for multiple guards

### ISSUE THREAD

**Issue by nanaaikinson24** [spatie/laravel-permission#1397]
Is there a way to use the permission middleware with multiple guards?

**Comment by drbyte** [comment]
Please explain more about what you're wanting to accomplish.

A user is only authenticated with a single guard at any given time.

**Comment by nanaaikinson24** [comment]
I have an app which utilizes a multi tenant architecture. I have three guards tenant - TenantModel, system - SystemModel and api.
I wanna know if I can use the permission middleware to handle permissions for each guard

**Comment by drbyte** [comment]
> I wanna know if I can use the permission middleware to handle permissions for each guard

Yes.

Keep in mind that a `permission` or `role` needs to have a `guard_name` declared when it is created.
