### ISSUE TITLE
add Group functionality like GitLab

### ISSUE THREAD

**Issue by whfamily2006** [spatie/laravel-permission#140]
Please add one more feature like gitlab....

https://docs.gitlab.com/ee/user/permissions.html#group

**Comment by freekmurze** [comment]
Currently groups are not supported, you'll need to do this in your own project.

**Comment by envision** [comment]
Apparently there is no such general solution for Laravel yet, nor any articles...haven't found yet yet atleast.

My needs are to have this kind of relation:
user <> permission/role <> group

One way would be to link _user <> group_, and check if user has proper permission/role...without linking _permission/role <> group_.

I would also need to have an organization structure...like groups, supergroups, organization...or just nested groups.
