### ISSUE TITLE
about "wildcard_permission" It's not worked for me.

### ISSUE THREAD

**Issue by ChenRuihua** [spatie/laravel-permission#1404]
I set 'enable_wildcard_permission' => true in the config file.
And here is my code:

>         Permission::create(['name' => 'projects.index']);
>         Permission::create(['name' => 'projects.show']);
>         Permission::create(['name' => 'projects.create']);
>         Permission::create(['name' => 'projects.edit']);
>         User::find(1)->givePermissionTo('projects.*');

but it does not worked.

```
Spatie \ Permission \ Exceptions \ PermissionDoesNotExist
There is no permission named `projects.*` for guard `web`.
```
what's the problem whit my code?
Thank you.

**Comment by drbyte** [comment]
> ```
>    User::find(1)->givePermissionTo('projects.*');
>
> There is no permission named `projects.*` for guard `web`.
> ```

Answer: you must first create the permission named `projects.*`
