### ISSUE TITLE
Example App documentation error

### ISSUE THREAD

**Issue by bellwood** [spatie/laravel-permission#1405]
In the example app seeder, it is stated that the default factory password is 'secret' however it is actually 'password'.

See: https://github.com/laravel/laravel/blob/master/database/factories/UserFactory.php

**Comment by drbyte** [comment]
Thanks @bellwood - I've removed the comment, since it's sensible to just base it on whatever is happening in the factory, without bothering to be specific.

**Comment by bellwood** [comment]
@drbyte would it be worth mentioning or referring to the factory so that new comers can still follow along? Not that I saw any "hey whats the password" issues in the repo to-date but it's always nice when you can log into an example sans-frustration =)

**Comment by drbyte** [comment]
> In the example app seeder, it is stated that the default factory password is 'secret' however it is actually 'password'.

Did you know? 
Laravel's default User password was `secret` for many years, until version 5.7, and the min pwd length was 6. Then in 5.8 they increased the default length to 8 so they also changed the default pwd in the factory to `password`.
