### ISSUE TITLE
Change in model_has_roles

### ISSUE THREAD

**Issue by MarcosRLeao** [spatie/laravel-permission#1406]
Please, in model_has_roles I need the user ID to change to the username field, is it possible?
![trade](https://user-images.githubusercontent.com/50677003/76472482-6a8c0800-63d4-11ea-9b4f-b2e9722f2b08.png)

**Comment by bambamboole** [comment]
You should be able to retrieve the users name if you have the model and the unique identifier.
Maybe I don't get your need exactly. Could you please describe this a bit more.

**Comment by MarcosRLeao** [comment]
In my system, the main camo is the username, because I will import a long list of users from an external bank, it would be easier to generate the lists based on this username
![username](https://user-images.githubusercontent.com/50677003/76670644-6a287400-6570-11ea-94d1-94ba9e478004.png)

**Comment by bambamboole** [comment]
Hmm there is also an id which seems to be unique. 
This also seems not a default Laravel use case. 
If you use a default Eloquent model everything will work.

**Comment by drbyte** [comment]
Yes, you're better off using normal Eloquent models, instead of unnecessarily hacking apart the built-in polymorphism.
