### ISSUE TITLE
Class App/User not found if property $guard_name add to the User model.

### ISSUE THREAD

**Issue by arafat1010** [spatie/laravel-permission#1407]
I have two project.
One, in i added the $guard_name property to User model and its works fine.

But,
In another project,  I did same thing but show an error
Class '\App\User' not found

Even I imported User model in the top 
`use App\User;
`
If i add other property in the User model its show no problem just with $guard_name property;

### Property $guard_name of App/User model.

`public $guard_name = 'customer';`

### Guards
`'guards' => [

        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],

        'customer' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        
    ],
`

### In my controller 
$user = User::find(5);`
$user->assignRole("customer");
`
**here i 'customer' is a role. Guard name is also "customer".**

![Screenshot from 2020-03-13 04-50-20](https://user-images.githubusercontent.com/62121364/76574798-859b6c80-64e7-11ea-9331-53adb5ff96e4.png)

### Another problem.
Another problem with $guard_name property.
if my host `http://127.0.0.1:8000/`
Every page lode properly without only when i assign role to a user.

But
If its `http://localhost:8000` with $guard_name in User model
No page lode and show screenshot Error.

**Comment by drbyte** [comment]
Seems like errors in your code. But you didn't share your code for review.

**Comment by arafat1010** [comment]
> Seems like errors in your code. But you didn't share your code for review.

Thank you for answer. Please apologize me for incompetence.  I edit my question please review and help me.

**Comment by drbyte** [comment]
> Another problem with $guard_name property.
if my host http://127.0.0.1:8000/
Every page lode properly without only when i assign role to a user.
But
If its http://localhost:8000 with $guard_name in User model
No page lode and show screenshot Error.

This package doesn't have anything to do with the URL used, so whatever is happening for `localhost` vs `127.0.0.1` is something in your application, and nothing to do with this package.

**Comment by drbyte** [comment]
> public $guard_name = 'customer';

Normally that should be a `protected` property. But, this is not likely the cause of your problems.

**Comment by drbyte** [comment]
> One, in i added the $guard_name property to User model and its works fine.
But,
In another project, I did same thing but show an error
Class '\App\User' not found

Again, this seems very much like there are other errors in your code, likely unrelated to this package. Perhaps you've mixed namespaces, or have syntax errors (even misplaced braces or parentheses) that are causing the PHP code to be interpreted incorrectly and resulting in strange errors.

You said things work properly in "one project, but not in another". This too is evidence that the problem you're encountering is specific to your own application code.

Specifically, this package has nothing to do with whether your `\App\User` class can be found. Only your application code could create that sort of error.
