### ISSUE TITLE
Request: Add support for wildcards in middleware

### ISSUE THREAD

**Issue by Savlon** [spatie/laravel-permission#1408]
Are there any future plans of adding the ability for wildcards in middlewares? 

For example:

permissions in database:
`guests.get`
`guests.add`
`guests.update`
`guests.delete`

routes:
```
Route::group(['middleware' => ['permission:guests.*']], function() {
     Route::get('guests', 'GuestController@index');
     ...
}
```

**Comment by drbyte** [comment]
It already does.

Simply create the `guests.*` permission so that it can be used in the middleware, and it will match `guests.get`, `guests.add`, etc.

**Comment by Savlon** [comment]
> It already does.
> 
> Simply create the `guests.*` permission so that it can be used in the middleware, and it will match `guests.get`, `guests.add`, etc.
> 
> (And of course enable wildcard permissions in the config/permissions.php file)

Ahh I see. Thanks!

**Comment by icarules** [comment]
This does not seem to work for me, or maybe I'm not understanding it correctly.

Permissions in database:
```
admin.role.*
admin.role.list
admin.role.edit
admin.role.delete
```

The user has been granted permission for: `admin.role.list`

In my controller I check for:
`$this->middleware('permission:admin.role.*');`

And this results in a 403. I thought checking for the wildcard meant that a user would be granted access if he has any of the permissions under `admin.role`.

**Comment by drbyte** [comment]
> I thought checking for the wildcard meant that a user would be granted access if he has any of the permissions under `admin.role`.

It does. You can see it operational in the package [tests](https://github.com/spatie/laravel-permission/blob/master/tests/WildcardHasPermissionsTest.php).
But you have to turn on wildcard support in the config file else the feature is disabled.

**Comment by icarules** [comment]
> It does. You can see it operational in the package [tests](https://github.com/spatie/laravel-permission/blob/master/tests/WildcardHasPermissionsTest.php).

I don't think the tests contain a similar case to what I described. I wrote a new testcase, which fails:

```
app('config')->set('permission.enable_wildcard_permission', true);

$user = User::create(['email' => 'user1@test.com']);

$permissionAll = Permission::create(['name' => 'news.*']);
$permissionShow = Permission::create(['name' => 'news.show']);

$user->givePermissionTo([$permissionShow]);

$this->assertTrue($user->hasPermissionTo('news.*'));

```

So the user was not given permission to `news.*`, but only to `news.show`.

**Comment by drbyte** [comment]
@stefanriehl what are your thoughts on this?

**Comment by stefanriehl** [comment]
@icarules @drbyte 

Well, the results are correct imo. Why? You give the user **only** the permission to show news:

```php
$permissionShow = Permission::create(['name' => 'news.show']);
$user->givePermissionTo([$permissionShow]);
```

But then you ask if the user has **any** permissions for news.

```php
$user->hasPermissionTo('news.*'); // false
```

And that is false, because the user has not these permissions. The user has only the permission `news.show`. When you compare these permissions, you'll see, that `news.*` is a much more powerful permission than `news.show`. 

Regarding to your use case:

You should check in your middleware the permission as specific as possible, i.e.

```php
// your check
$this->middleware('permission:admin.role.*');

// better is
$this->middleware('permission:admin.role.list,view');
```

Btw. 

```php
$permission = 'admin.role.*';

// is the same as
$permission = 'admin.role';
```

**Comment by drbyte** [comment]
@stefanriehl How would you recommend someone test for "a user has 'ANY of the possible permissions for `news`'", instead of testing for "`news.*` which implies 'has EVERY permission for news"? ... without having to list every one of them?

**Comment by stefanriehl** [comment]
Hmm, this special use case is not possible.

You should always check against specific permissions:

```
// user has the permission to create news
$user->hasPermissionTo('news.create');

// user can use this route if he has the permission to create news
$this->middleware('permission:news.create');
```

Otherwise I would recommend using roles.

**Comment by rappasoft** [comment]
I know this issue is aging but it is still open so i'm going to comment. I was searching the issues for literally this exact thing and wasn't surprised when I found the exact same scenario I was trying to accomplish. I built a large portion of my app based around wildcards all while having the wrong idea of how they worked.

I don't think the documentation does a good job at all explaining exactly how to use the wildcard feature.

Why cant I use a middleware like `permission:admin.auth.*`

And have it match any permissions inside that structure, for example `admin.auth.user.create`, `admin.auth.role.edit` would all pass.

i.e., I the user has the above two permissions without explicitly having `admin.auth.*`, but because it's a wildcard it should pass anyway.

@Savlon may I ask what your eventual implementation was? How did you get around this?

**Comment by Savlon** [comment]
> I know this issue is aging but it is still open so i'm going to comment. I was searching the issues for literally this exact thing and wasn't surprised when I found the exact same scenario I was trying to accomplish. I built a large portion of my app based around wildcards all while having the wrong idea of how they worked.
> 
> I don't think the documentation does a good job at all explaining exactly how to use the wildcard feature.
> 
> Why cant I use a middleware like `permission:admin.auth.*`
> 
> And have it match any permissions inside that structure, for example `admin.auth.user.create`, `admin.auth.role.edit` would all pass.
> 
> i.e., I the user has the above two permissions without explicitly having `admin.auth.*`, but because it's a wildcard it should pass anyway.
> 
> @Savlon may I ask what your eventual implementation was? How did you get around this?

I have scrapped the use of the wildcard because it wasn’t implemented the way I thought it was, as in the way I thought it was in my initial post. I have now micromanaged every link and created each permission individually.

Eg:
guests.add
guests.update
guests.delete

It would be so much better if I could use the wildcard in the same way you described, but it seems the devs have other plans.

**Comment by rappasoft** [comment]
> > I know this issue is aging but it is still open so i'm going to comment. I was searching the issues for literally this exact thing and wasn't surprised when I found the exact same scenario I was trying to accomplish. I built a large portion of my app based around wildcards all while having the wrong idea of how they worked.
> > I don't think the documentation does a good job at all explaining exactly how to use the wildcard feature.
> > Why cant I use a middleware like `permission:admin.auth.*`
> > And have it match any permissions inside that structure, for example `admin.auth.user.create`, `admin.auth.role.edit` would all pass.
> > i.e., I the user has the above two permissions without explicitly having `admin.auth.*`, but because it's a wildcard it should pass anyway.
> > @Savlon may I ask what your eventual implementation was? How did you get around this?
> 
> I have scrapped the use of the wildcard because it wasn’t implemented the way I thought it was, as in the way I thought it was in my initial post. I have now micromanaged every route and created each permission individually.
> 
> Eg:
> guests.add
> guests.update
> guests.delete
> 
> It would be so much better if I could use the wildcard in the same way you described, but it seems the devs have other plans.

Thanks a lot for the response, it looks like i'm going to have to take the same approach.

**Comment by anilkreddy** [comment]
I know this is closed but I tried the way described above and still doesn't work for middleware,

In my controller, I have this middleware which says if the user has any of users.list, users.create, users.edit, users.delete open index and store methods like `$this->middleware('permission:users.list,create,edit,delete', ['only' => ['index','store']]);`

And I have a user who is given permission **users.edit** and when trying to load the index method, I get 403 Forbidden.

Am I doing the middleware check correctly? Or my assumption is wrong! 

Note: without wildcard enabled, the old way of pipe still works,

`$this->middleware('permission:list-user|create-user|edit-user|delete-user', ['only' => ['index','store']]);` and giving only create-user will open my index page

**Comment by stefanriehl** [comment]
Your middleware permission requires the User to have ALL of these permissions (edit, create, delete and list) but he has only the edit permission.

**Comment by rappasoft** [comment]
Hmm that's weird, it's working the opposite for me. I.e. the middleware is `permission:access.users.list,deactivate,reactivate,clear-session,impersonate,change-password` and if my user has one or more, it allows them in. Which is how I expected, and wanted it to work.

**Comment by anilkreddy** [comment]
> Your middleware permission requires the User to have ALL of these permissions (edit, create, delete and list) but he has only the edit permission.

That's weird, `$this->middleware('permission:users.view,list', ['only' => ['show']]);` I tried this. I gave **users.list** permission. The above middleware doesn't work since I don't have **users.view** and gives 403. But when I interchange like `$this->middleware('permission:users.list,view', ['only' => ['show']]);` It works. As per your comment, this shouldn't work as well.

And it seems for @rappasoft it's working the way I expected. I enabled wildcard permissions too.

**Comment by rappasoft** [comment]
Even if it was working as intended (which for me it's not) what would be the correct way to do ANY instead of ALL just in case this gets patched in the future?

**Comment by stefanriehl** [comment]
Ok, that's all weird and I made several local tests.

```php
$this->testUser->givePermissionTo('users.edit');

$this->assertEquals(
    $this->runMiddleware(
        $this->permissionMiddleware, 'users.edit,list,delete'
    ), 403);
// returns 403 permission denied - like expected
// the user only has permission to edit users
// but the middleware expects that the user has the permission to edit, list and delete users
```

```php
$this->testUser->givePermissionTo('users.edit');

$this->assertEquals(
    $this->runMiddleware(
        $this->permissionMiddleware, 'users.edit|users.list|users.delete'
    ), 200);
// returns 200 - like expected
// the user only has permission to edit users
// because the middleware expects that the user has the permission to edit OR list OR delete users
```

Maybe that helps.

**Comment by rappasoft** [comment]
Hmm ok I guess that makes sense, oddly i'm not getting that behavior, but i'm going to switch it to your second example just to be safe. Either way, the tests don't lie.
