### ISSUE TITLE
Automatic giving permissions to user with assigned role

### ISSUE THREAD

**Issue by messi89** [spatie/laravel-permission#1409]
Hello guys;

Is there a way to give permissions automatically to a user with assigned role (the role have permissions)
`Artisan::call('permission:create-permission', ['name' =>'admin', 'guard' => 'web']);`
`Artisan::call('permission:create-role', ['name' =>'administrator', 'guard' => 'web', 'permissions' => 'admin']);`

assign role to our user
`$admin = User::create([
            'name' => 'Admin',
            'email' => 'admin@example.com',
            'password' => 'admin',
        ]); `
`$admin->assignRole("administrator");`

but when I try to get user permissions with 
`dd(auth()->user()->getPermissionNames())`

I get an empty array (getRoleNames() work fine)

so should I call givePermissionTo to each user ? in this case what is the use of assigning permission to a role ?
`$admin->assignRole("administrator")->givePermissionTo("admin")`

Thanks

**Comment by drbyte** [comment]
`givePermissionTo()` assigns a specific permission, regardless of roles.

Likewise, `getPermissionNames()` gets permissions DIRECTLY assigned to the user, not the ones inherited by the Roles they've been granted.

Try `getPermissionsViaRoles()`.
