### ISSUE TITLE
Split User model

### ISSUE THREAD

**Issue by b8ne** [spatie/laravel-permission#141]
I have a split user model, so each user has a master model which they use for auth, but then they may go to different subdomains. Each subdomain will have a secondary user model that references the main one. 
I want to be able to assign roles to this secondary model, however everything I have tried still pulls in what im assuming is the authenticated model to check roles.
Is there a way to assign exactly what model is used for permissions, and not just have it based off the standard laravel auth model?

**Comment by freekmurze** [comment]
There's a `permission` key in the config file where you can specify the model to be used.
