### ISSUE TITLE
Adding query scope to Permission and Role

### ISSUE THREAD

**Issue by suleodu** [spatie/laravel-permission#1410]
I have a project where users can belong to multiple schools within my app ... I am looking for a way to create a role with school_id and also when I need to get permission assign to a user it has to be for a specific school_id by default (a user can be a lecturer in school 1 with permission to add student result and also that same user can be a course adviser and not a lecturer in school 2 with permission to only view student course_from ) the current active school that the user is will be store in auth session ... 
How can i implement this without going into the vendor folder to twik this

**Comment by drbyte** [comment]
You can probably use the wildcard permission feature, along with laravel model policies.

**Comment by suleodu** [comment]
This is not what I am.looking for  I have a auth session school_id and I want a situation with I can call hasPermission and the query will automatically query with where school_id =

**Comment by drbyte** [comment]
> call hasPermission and the query will automatically query with where school_id = auth session school id
> without going into the vendor folder to twik this

You can override the trait method (or methods) by copying it/them into your model and customizing the logic that scopes the queries according to your application's unique requirements and unique database structure.
