### ISSUE TITLE
Windows - Error: config/permission.php not found

### ISSUE THREAD

**Issue by BeauvR** [spatie/laravel-permission#1411]
I'am trying to add this package to the new laravel version when i migrate the system i get:
![afbeelding](https://user-images.githubusercontent.com/55840090/76771158-32534380-679f-11ea-93ac-c143152a9672.png)

**Comment by drbyte** [comment]
I can't replicate these symptoms on Linux or Mac.

**Comment by BeauvR** [comment]
Yes it is on Windows.

**Comment by BeauvR** [comment]
Anyone can help me?

**Comment by drbyte** [comment]
A few things:
- Where exactly did it put the `config/permission.php` file? Is it *actually* in your app's /config/ dir?
- What are its contents? ie: is it blank, or does it actually contain a PHP array with config settings, specifically table_names and column_names entries?

Is it an issue with your Windows environment? You're using drive W: which is probably a networked drive ... does the same problem happen if you do it on your local physical C: drive ? I can't help you fix whatever would cause an issue with that, but it's worth checking into.

**Comment by BeauvR** [comment]
Nevermind i don't know how but i reinstalled the project and everything is working now. Thanks!

**Comment by thomasmoors** [comment]
The exact same problem occurred to me today. A very strange bug...

**Comment by thomasmoors** [comment]
A few things:

Where exactly did it put the config/permission.php file? Is it actually in your app's /config/ dir?
A: Yes

What are its contents? ie: is it blank, or does it actually contain a PHP array with config settings, specifically table_names and column_names entries?

A: Yes it contains all code to be expected when published.

Is it an issue with your Windows environment? You're using drive W: which is probably a networked drive ... does the same problem happen if you do it on your local physical C: drive ? I can't help you fix whatever would cause an issue with that, but it's worth checking into.

This time it's just a regular old C:\ drive, so it appears to have nothing to do with network shares.

**Comment by drbyte** [comment]
@thomasmoors That's really strange.
In version 3.10.0 and 3.10.1 there were some adjustments to the migration stub to try to mitigate odd cases where the config array is empty, which seems similar to this which you mention.
Are you using 3.10.1 or higher?

**Comment by netwons** [comment]
The exact same problem occurred to me today. A very strange bug
