### ISSUE TITLE
How to set these permissions?

### ISSUE THREAD

**Issue by KeironLowe** [spatie/laravel-permission#1414]
So I'm building a sort of dropbox style file manager, and by default, any files/folders that are uploaded, all users will have access to. But if needed, certain files/folders can be restricted so only specified users would have access to it.

Would that style of permissions work with this library? I was thinking I could use the wildcard permissions feature, so something like `$user->givePermissionTo('files.view');`, but it's the restricting I'm unsure about. We could assign the specified user permissions, like `$user->givePermissionsTo('files.view.10,20')` but all other users would still have access due to the original permissions. 

Hope that all made sense!

**Comment by drbyte** [comment]
I'm not sure if you even need this package, at least as far as that specific "default is public viewable, except when restricted to certain users" case goes. 

If you "do" decide to use this package, keep in mind that it's build around an "additive" approach to permissions: granting more as needed, never taking away or reducing or restricting what's already been given.

It strikes me that a normal Laravel Model Policy suits well in your use-case. Simply return true for all access methods, after first checking to see whether you've stored a restriction for that model, and check the per-user level if relevant. And then create a simple pivot relationship for restrictions for users of those models.

**Comment by KeironLowe** [comment]
Thanks that makes perfect sense and I agree, don't think this package would be necessary anymore. Thanks!
