### ISSUE TITLE
Get roles and permissions on nested set

### ISSUE THREAD

**Issue by Excelautomation** [spatie/laravel-permission#1418]
Hi.

I've a setup where Organizations have many Deparments. An Organization can have many Users and so can Departments. Each Organization and Department can have users with different roles and permissions.

My roles is bound to these two models (Organization and Department). Like this: https://ibb.co/wQtJbq1

All this works just fine. However, it seems like I'm receiving 0 permissions and roles on my user, when I'm calling the dashboard (listing all organizations and departments), which I think, is due to the fact, that my query dosen't include the permissions/roles. When I'm calling a specific department this works just fine - the roles and permissions are actually being added perfectly to my collection.

I've tried adding `users.permissions` to the query but this dosen't help. 

How can I retrieve the users roles and permissions? 

Here is my query:

`  'departments' => $this->departments()->where('organization_id', $organization->id)
                   ->with(
                        'ancestors.commodities',
                        'ancestors.recipes',
                        'ancestors.stocks',
                        'commodities',
                        'recipes',
                        'stocks'
                    )->get() `

**Comment by drbyte** [comment]
@Excelautomation depending on how you've built all the alterations to the original schema, I would expect that either adding the roles relation to the query or specifically querying for the roles upon retrieval of each object (yes, N+1 risk with that, but could be inconsequential in many cases) should provide the desired result.
