### ISSUE TITLE
How to translate error messages ?

### ISSUE THREAD

**Issue by iSpeeX** [spatie/laravel-permission#1419]
Hi everyone,
I'm using laravel-permission and I have to say that it's really great ! Thank you for your amazing work !
My question is, you guessed it, how to translate error messages ?

But before you answer this, I need to give you more details about my context. This library is installed via Composer and I found the files with the error messages under : vendor/spatie/laravel-permission/src/Exceptions
The fact is that we don't commit theses files (and everything under "vendor") in my project and I wonder if there is another way to translate these messages ?

Thank you !
Best regards,
Mathieu

**Comment by drbyte** [comment]
Hi @iSpeeX 
There's currently no built-in way in this package to translate error messages.
That would require refactoring to define all the messages in json and parameterize the rendering of each message.

Question: who is actually needing to see these messages? Normally these exceptions are only relevant to developers, and if you catch all these exceptions in your app then you can determine your own output message, which wouldn't require translations to exist in this package.

**Comment by iSpeeX** [comment]
Thank you very much. Well, I guess you are right on that point.
The standard user shouldn't even see these error pages anyway.

Sorry for taking your time and have a great day !

Best regards,
Mathieu

**Comment by salehasadi** [comment]
@iSpeeX I handled this by putting message text to my lang.json like this and that do the trick
![image](https://user-images.githubusercontent.com/14921568/106154941-635d1c80-6195-11eb-998e-b4da41dd1c90.png)
