### ISSUE TITLE
Unexpected behavior when testing on artisan

### ISSUE THREAD

**Issue by Punksolid** [spatie/laravel-permission#142]
When testing on artisan tinker the object needs to be reloaded, I don't know if its possible to fix it or at least specify on the documentation.

It happens when you add a permission to a user and then check the permission and then add another permission to the same user model, the second permission added it is not going to be updated when making $user->can('secondpermission')
To make the object reload it is useful making 
$user = $user->fresh();

![selecao_190](https://cloud.githubusercontent.com/assets/416409/20856061/f328faa2-b8c3-11e6-8c35-efcc947eabce.png)

**Comment by freekmurze** [comment]
I'd accept a PR that adds a little note on this in the readme.
