### ISSUE TITLE
Laravel-Permission Integration Where Auth0 is being used. [Assistance Request]

### ISSUE THREAD

**Issue by FullMe7alJacke7** [spatie/laravel-permission#1421]
Hey guys, I am trying to incorporate this package into my website where I am using Auth0 for authentication. 

I understand that the Auth0User replaces the Eloquent User model so I followed their optional setup [here](https://auth0.com/docs/quickstart/webapp/laravel/01-login#optional-custom-user-handling).

So I have a user table in my DB that I can do `User::SomeQuery()` and get the users from my local DB table, but currently, whenever I try to do @ role or @ can, etc I get this error.

> Argument 1 passed to Spatie\Permission\PermissionRegistrar::Spatie\Permission\{closure}() must implement interface Illuminate\Contracts\Auth\Access\Authorizable, instance of Auth0\Login\Auth0User given, called in /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 487 (View: /home/vagrant/code/resources/views/dashboard/administration/console.blade.php)`

I also tried the work-around located [here](https://github.com/spatie/laravel-permission/issues/1331) towards the bottom of the page. This causes an "invalid state" error, Auth0 SDK Exception upon login.

Relevant Stuff In Use:
Laravel "7.0"
auth0/login "master" (Only current working branch for Laravel v7 atm)
spatie/laravel-permission "3.11"
laravel/homestead "10.5"
PHP "7.2.5"

Any assistance would be tremendously appreciated!

**Comment by drbyte** [comment]
> This causes an "invalid state" error, Auth0 SDK Exception upon login.

You'll probably find value in exploring what about that package throws that exception from that package.

The only quick thing I found about it was a closed issue in their repository that suggested it had something to do with someone's `session` implementation. And I know Laravel 7 changed default session from files to cookies; did you make the same change? does reverting back to old approach solve the issue after clearing cache and cookies? Just a guess, but worth asking.

I feel like the posted resolution in #1331 appears to be correct. But of course your app may have differences in it compared to the apps built by the others who said #1331 worked fine for them.

**Comment by FullMe7alJacke7** [comment]
@drbyte I have not changed anything else outside of the Auth0 setup process defined [here](https://auth0.com/blog/build-a-laravel-6-app-with-authentication/). It was a fresh project before that and the only changes I made outside of that was using laravel 7 instead of 6 and making the pull from their master repo instead of a prior version so I was hoping I wouldn't run into any issues as when tested without alterations it appears to be working as expected. 

I will focus my search in the direction you mentioned about the change from session to cookies and see if there is something that needs changing elsewhere. Thank you for your time & the speedy reply!

**Comment by drbyte** [comment]
If you find that there's something specific to Laravel 7, be sure to post to their repo about it since it looks like they just tagged a new version for Laravel 7 support.
