### ISSUE TITLE
using permission with wildcard not working

### ISSUE THREAD

**Issue by jcherrabi** [spatie/laravel-permission#1423]
Hello there,
i followed the instructions here: https://docs.spatie.be/laravel-permission/v3/basic-usage/wildcard-permissions/ and set `// config/permission.php
'enable_wildcard_permission' => true,`

and when i call the following code:
`$permission = 'test.create.1';
  Permission::findOrCreate($permission);
   $user->givePermissionTo('test.*');`

i get the following error: `  There is no permission named "test.*" for guard "web".` and when i check the permissions table in the database i do see that i have a record with a permission name `test.create.1` with a `guard_name` set to `web` can someone point me to what i've missed please.

**Comment by drbyte** [comment]
You must also first create the `test.*` permission. 
It needs that in order to do the matching, even if you don't assign it to anyone.

**Comment by jcherrabi** [comment]
still the following test fails with the same error:  There is no permission named `test.create,update,view` for guard `web`.

`$permission = 'test.*';`

        Permission::findOrCreate($permission);

        $permission = 'test.create';

        Permission::findOrCreate($permission);

        $permission = 'test.update';
        Permission::findOrCreate($permission);
        $permission = 'test.view';
        Permission::findOrCreate($permission);

        $user->givePermissionTo('test.create,update,view');`

**Comment by drbyte** [comment]
Before you can do:
`$user->givePermissionTo('test,users.create,update,view');`
you must first:
`Permission::create(['name'=>'test,users.create,update,view']);`
otherwise you'll get
`There is no permission named 'test,users.create,update,view'`

**Comment by jcherrabi** [comment]
ahhh nope doesn't work:
`        Permission::create(['name'=>'test,users.create,update,view']);
        $user->givePermissionTo('test,partner.create,update,view');`

still same error. and i noticed a new entry like this was entered to the DB which  is wrong...

![image](https://user-images.githubusercontent.com/5914393/77859089-4ff0c600-71ff-11ea-833e-8843f25af067.png)

which is wrong... so either the concept is not well explained or something isn't working..
to my understanding of the wild card is that i do not have to assign individual permissions and instead i can create a permission as a wild card once and every subpart would have that permission. unlike what you have asked i do above... 

can you please at least test the code and let us know if it is working as per your desciption?

**Comment by drbyte** [comment]
> ahhh nope doesn't work:
> ` Permission::create(['name'=>'test,users.create,update,view']); $user->givePermissionTo('test,partner.create,update,view');`

Look at what you created vs what you gave permission for: `users` vs `partner`.

**Comment by jcherrabi** [comment]
Thank you for the quick reply:
First the documentation example must be fixed as `Permission::create` takes an array and not a string as shown in the docs:
![image](https://user-images.githubusercontent.com/5914393/77859609-474dbf00-7202-11ea-8a18-2e03304cde25.png)

next the below code works fine: it creates one permission with a wildcard * and all tests return true:
![image](https://user-images.githubusercontent.com/5914393/77859641-82e88900-7202-11ea-9b6d-0c5447c1ba44.png)

`        Permission::findOrCreate('posts.*');
        $user->givePermissionTo('posts.*');
        var_dump($user->can('posts.create'));
        var_dump($user->can('posts.update'));
        var_dump($user->can('posts.jay'));
        var_dump($user->can('posts.cool'));`

this code below on the other hand fails:
`    Permission::findOrCreate('posts.*');
        Permission::findOrCreate('users.*');
        $user->givePermissionTo('posts,users.create,update,view');
        var_dump($user->can('posts.create'));
        var_dump($user->can('posts.update'));
        var_dump($user->can('posts.action'));
        var_dump($user->can('users.cool'));`

![image](https://user-images.githubusercontent.com/5914393/77859787-410c1280-7203-11ea-900e-1d9b7efbce08.png)

**Comment by drbyte** [comment]
> First the documentation example must be fixed as `Permission::create` takes an array and not a string as shown in the docs:
> ![image](https://user-images.githubusercontent.com/5914393/77859609-474dbf00-7202-11ea-8a18-2e03304cde25.png)

Yes, that was done yesterday.

**Comment by drbyte** [comment]
> this code below on the other hand fails: as you can see both permissions are created but cannot assign them as shown in the docs:
> ![image](https://user-images.githubusercontent.com/5914393/77860032-b75d4480-7204-11ea-92e0-f35143d92792.png)
> 
> the permissions are created fine as shown below, but cannot assign the sub-parts individually using the wildcard concept as shown in the docs...
> 
> ![image](https://user-images.githubusercontent.com/5914393/77859829-73b60b00-7203-11ea-8a81-30064391ca66.png)
> 
> ` Permission::findOrCreate('posts.*'); Permission::findOrCreate('users.*'); $user->givePermissionTo('posts,users.create,update,view'); var_dump($user->can('posts.create')); var_dump($user->can('posts.update')); var_dump($user->can('posts.action')); var_dump($user->can('users.cool'));`
> 
> ![image](https://user-images.githubusercontent.com/5914393/77859787-410c1280-7203-11ea-900e-1d9b7efbce08.png)

Again, you have not created the `posts,users.create,update,view` permission that you're trying to `givePermissionTo`, hence the "There is no permission named `posts,users.create,update,view` error message.
As you can see, you only created 2 permissions, not the big long one.

#


The following works fine in Tinker/Tinkerwell:

```php
use Spatie\Permission\Models\Permission;

app('config')->set('permission.enable_wildcard_permission', true);

$user = factory(\App\User::class)->create();

Permission::findOrCreate('test.*');
$permission = 'test.create.1'; 
Permission::findOrCreate($permission); 
$user->givePermissionTo('test.*');
var_dump($user->hasPermissionTo('test.create.1')); // true


Permission::findOrCreate('posts.*');
$user->givePermissionTo('posts.*'); 
var_dump($user->hasPermissionTo('posts.create'));  // true
var_dump($user->hasPermissionTo('posts.update'));  // true
var_dump($user->hasPermissionTo('posts.jay'));  // true
var_dump($user->hasPermissionTo('posts.cool')); // true


Permission::findOrCreate('posts.*'); 
Permission::findOrCreate('users.*');
Permission::findOrCreate('posts,users.create,update,view');

$user->givePermissionTo('posts,users.create,update,view');
var_dump($user->hasPermissionTo('posts.create'));  // true
var_dump($user->hasPermissionTo('posts.update'));  // true
var_dump($user->hasPermissionTo('posts.action'));  // true
var_dump($user->hasPermissionTo('users.cool')); // false
```

**Comment by sammyaxe** [comment]
Weird this is closed, it really is confusing, cause it seems like what is the point of wildcard if you need to create specific variations anyways?
