### ISSUE TITLE
Cache not created when wildcard permissions enabled

### ISSUE THREAD

**Issue by houseoftech** [spatie/laravel-permission#1424]
When wildcard permissions are enabled in config, `'enable_wildcard_permission' => true,`, the permissions cache is no longer created.

Edit: It looks like this is the case only when checking permission by string.

**Comment by drbyte** [comment]
A PR with tests is welcome.

@stefanriehl have you any thoughts?

**Comment by stefanriehl** [comment]
> When wildcard permissions are enabled in config, `'enable_wildcard_permission' => true,`, the permissions cache is no longer created.
> 
> Edit: It looks like this is the case only when checking permission by string.

Enabling wildcard permissions actually does not touch the permissions cache. When I run tests with `CacheTest.php`and enable wildcard permissions, the cache will be created and everything is green.

```php
    /** @test */
    public function it_can_cache_the_permissions()
    {
        app('config')->set('permission.enable_wildcard_permission', true);

        $this->resetQueryCount();

        $this->registrar->getPermissions();

        $this->assertQueryCount($this->cache_init_count + $this->cache_load_count + $this->cache_run_count);
    }
``` 

So, maybe you could do a PR with tests?

**Comment by houseoftech** [comment]
@stefanriehl The `CacheTest.php` test seems flawed. It will work fine when the cache driver is set to `database` because it's producing queries, but when set to `default` (array), it's only asserting that the 2 select queries ran for retrieving roles and permissions.

The `has_permission_to_should_use_the_cache()` is a more realistic test method, as an app is more likely to use `hasPermissionTo()` than directly retrieving permissions via `getPermissions()`. If wildcard permissions are enabled here then `getPermissions()` is never called. That is because the `HasPermissions` trait `hasWildcardPermission()` method does not use the `Permission` model's `findByName()` method. That's why I said, when checking by id, it works.

This test fails with wildcard permissions enabled.

```php
/** @test */
public function has_permission_to_should_use_the_cache()
{
    app('config')->set('permission.enable_wildcard_permission', true);

    $this->testUserRole->givePermissionTo(['edit-articles', 'edit-news', 'Edit News']);
    $this->testUser->assignRole('testRole');

    $this->resetQueryCount();
    $this->assertTrue($this->testUser->hasPermissionTo('edit-articles'));

    $this->assertQueryCount($this->cache_init_count + $this->cache_load_count + $this->cache_run_count + $this->cache_relations_count);
}
```

**Comment by bagoesz21** [comment]
is this issue resolved?, i need to cache with wildcard permission ..
