### ISSUE TITLE
ldap integration

### ISSUE THREAD

**Issue by Pixy123** [spatie/laravel-permission#1425]
Hi,
I have try to add spatie permission on base installation laravel with ldaprecord.
Ldap configuration under config/auth.php have 
**'providers' => [
        'ldap' => [
            'driver' => 'ldap',
            'model' => LdapRecord\Models\ActiveDirectory\User::class,**

In your Guard.php line 41, you read Guard like this
**return config("auth.providers.{$guard['provider']}.model");**

And spatie permission role not work because spatie report this error
**The given role or permission should use guard `` instead of `web`**

This is a problem resolved in pull request #1384 ?
Thank you

**Comment by fefo-p** [comment]
Hi, for what it's worth,
I ran into this problem today, and my working solution was to add `protected $guard_name = "web";` to Laravel's User model.
BTW, I'm synching the LDAP info into Laravel's DB.

As I understand, you can instead add 
```
public function guardName()
{
        return "web";
}
```
which actually gets checked **before** the `$guard_name` property

**Comment by Tamas-hi** [comment]
I can confirm as well that a `protected $guard_name = "web";` to my User model solved the issue.

Took a while to find this issue, but happy I got it working. Thanks for your suggestions!
