### ISSUE TITLE
Different role for user to manage multiple account

### ISSUE THREAD

**Issue by salihanmridha** [spatie/laravel-permission#1428]
Hello guys,
I need a help. Currently I am developing a project where a user can manage multiple account and account has an owner. So user can have different role for manage each account. 

Example:
User X manage  Account A, Account B and Account D
So User X can have role "view" for Account A, role "moderator" for Account B and role "author" for Account D. So for same user it is need different role for manage different account.

How I can achieve this scenario with this package?

Thanks in advance

**Comment by mishbah** [comment]
create table that inform user X handle some user (for ex: user A, user B, user C), for example `user_relations`
with data in the table, you can use user [login programatically](https://laravel.com/docs/6.x/authentication#other-authentication-methods) to switch the user login

don't forget, set role for each user

**Comment by drbyte** [comment]
This isn't much different than a blog, where users can write posts and you want to control whether they have certain access to certain kinds of posts. Or limit them to posting in a certain category.

For this you can use policies to associate additional authorization levels to another model.
