### ISSUE TITLE
Can a user have many roles?

### ISSUE THREAD

**Issue by f7n** [spatie/laravel-permission#1430]
I have a table of `Accounts`, in which one user may be a manager of a `x` account but a operator of `y` account. So this user would have two roles, `manager` and `operator`. Is it possible out of the box to assign multiple roles to a single user entity? I know that the package uses a `Role` table and model.

If I create a end-to-end table `users_roles` with `user_id`, `role_id`, `role_name`, etc. can I integrate this with laravel-permissions?

**Comment by tomsix** [comment]
You kan insert an array.
`$model->assignRole(['manager', 'operator]);`
