### ISSUE TITLE
I would like to set a role for a newly created user but this role has a guard_name of API

### ISSUE THREAD

**Issue by danvfebra** [spatie/laravel-permission#1435]
I would like to ask for some help regarding my current scenario.

I have a backend system that takes control of the users, in this(project/app)I would like to create and update users.

Upon creating a user I would like to have an option that would say 

Using checkboxes:
"hey this user is a customer"
"hey, this user is an admin"
But when I try to do a `syncRoles()` for the user

```
$request->roles = [
    0 => 'Customer'
]
$user->syncRoles($request->only('roles'))
```

it would throw an exception and will say something like
Couldn't find role name of 'Customer'
This is because my 
The customer role has a guard_name of API.

To wrap everything up I would like to set a role for a newly created user but this role has a guard_name of API.

I hope you can help me.

Thank you!

**Comment by danvfebra** [comment]
```
_**View/Components/User/CseForm.php**_
**public function roles() : array {
       return DB::table('roles')->select(['name', 'guard_name'])->get()->toArray();
    }**

_**views/components/user/cse-form.blade.php**_
**@foreach($roles as $role)
    <input name="roles[]" type="checkbox" class="" value="{{ json_encode($role) }}">
    {{ $role->name }}
    <br>
@endforeach**


_**UserController @store & @update**_
**#If validation passed sync the roles first
        $roles = collect($request->roles)->map(function($role) use (&$roles){
            $role = json_decode($role);
            $roles = Role::findByName($role->name, $role->guard_name);
            return $roles;
        });

$user->update($request->except(['_token','roles']))->syncRoles($roles);**
```

**Comment by drbyte** [comment]
You can bypass the incorrect autodetection of guard_name by passing a collection of role objects or ids that are already linked to the desired guard_name, which can be obtained by `Role::findByName()` or other Eloquent methods on the Role object.
