### ISSUE TITLE
i have failed to add multiple guards successfully to my application

### ISSUE THREAD

**Issue by MATOVUJOELCLINTON** [spatie/laravel-permission#1436]
due to failing to add the multiple guards, my application throws errors like;

> delete method is not supported for this route. Supported methods: GET, HEAD...

> put method is not supported for this route. Supported methods: GET, HEAD...

what should i do? it seems these methods are ignored and it throws exceptions

**Comment by drbyte** [comment]
I don't see how this relates to this `laravel-permissions` package.

This package doesn't do anything with route methods such as delete/put/get/post.
