### ISSUE TITLE
Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by imamhsn195** [spatie/laravel-permission#1438]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `model_has_permissions` add index `model_has_permissions_model_id_model_type_index`(`model_id`, `model_type`))
 
## In Local machine (Migration Working)
Server version: 5.7.29-0ubuntu0.18.04.1 - (Ubuntu)

## In Cpanel (showing the above error)
Server version: 10.3.22-MariaDB-log-cll-lve - MariaDB Server

**Comment by imamhsn195** [comment]
Solved

**Comment by hypy13** [comment]
@imamhsn195  how did u solve that?

**Comment by Tharinducn** [comment]
> @imamhsn195 how did u solve that?

https://stackoverflow.com/a/65628140/8309464 
This solved my issue
