### ISSUE TITLE
Call to a member function contains() on array

### ISSUE THREAD

**Issue by Ucer** [spatie/laravel-permission#1439]
the is a error when i used `hasRole` or `hasAnyRole`  function 

```
        $user = Auth::user();
      $user->hasAnyRole('Founder');
```

```
    "require": {
        "laravel/framework": "^6.0",
        "spatie/laravel-permission": "^3.0",
    },
```

**Comment by drbyte** [comment]
Normally `Auth::user();` returns an instance of `\App\User`.
Evidently your application is returning an array. 
You need to fix that bug in your application.
