### ISSUE TITLE
Link in repo description should redirect to https://docs.spatie.be/laravel-permission/v3/introduction/

### ISSUE THREAD

**Issue by superbiche** [spatie/laravel-permission#1441]
Hey there,

First many thanks for this package and all the others you've delivered.

In this repo, the description link redirects to freek.dev's blog, but https://docs.spatie.be/laravel-permission/v3/introduction/ seems much more relevant as it's a full documentation.

Maybe you should change it? I guess it was forgotten there but maybe I'm guessing wrong.

Cheers

<img width="766" alt="Image 2020-04-19 at 2 07 20 PM" src="https://user-images.githubusercontent.com/404472/79695867-2ac40600-8247-11ea-9853-c76d04d4ddf7.png">

**Comment by freekmurze** [comment]
Thanks for the suggestions, I updated the URL.
