### ISSUE TITLE
use role e permission with larave rest api and token

### ISSUE THREAD

**Issue by alfonsocataldi** [spatie/laravel-permission#1442]
Hi,
Is it possible to use this package using Laravel as Rest API and a token?

AC

**Comment by drbyte** [comment]
Yes.
- "REST API" means you probably have only 1 guard: `api`.
- using "token" is merely a form of authentication. This package has nothing to do with authentication. 

This package provides "authorization", which is the granting of access based on roles/permissions, inside your app *after* authentication.
