### ISSUE TITLE
There is no role named 'whatever' 

### ISSUE THREAD

**Issue by neoacevedo** [spatie/laravel-permission#1445]
Hi all.

I get this issue just with `Role::findByName('whatever');`

Finding a role with 'whaterver' name in the default model mode `Role::where('name', 'whatever')->first();` works, but not with the trait mode.

I use the version 2.38.0 for laravel 5.5 but I think this issue could be present in the latest version.

**Comment by drbyte** [comment]
That's probably because you're not providing a guard name and your site is using more than one guard. You need to be specific about the guard if your site has more than one guard available.

`Role::findByName('whatever', 'guard name here');`

**Comment by robertnicjoo** [comment]
> 
> 
> That's probably because you're not providing a guard name and your site is using more than one guard. You need to be specific about the guard if your site has more than one guard available.
> 
> `Role::findByName('whatever', 'guard name here');`

 `Call to undefined method App\Role::findByName()`
