### ISSUE TITLE
\Spatie\Permission\Guard::getDefaultName auth guard not correct

### ISSUE THREAD

**Issue by timeshift92** [spatie/laravel-permission#1448]
Hello, I found a problem here, for example, I have guard api by default, but in your code here static :: 
```
getNames ($ class) -> first ()
```
and on the stack
```
Illuminate \ Support \ Collection {# 1154
   #items: array: 2 [
     0 => "web"
     1 => "api"
   ]
}
```
web always comes first

**Comment by shez1983** [comment]
i came to post exactly this.. your docs are incorrect or the code is.. if i remove web from auth as suggested api guard are not created by default... i had to manually add guard_name for now.

**Comment by drbyte** [comment]
This is documented behaviour.

There's an open PR to change that, which will probably be released as a new major version number.
