### ISSUE TITLE
Role permissions not working

### ISSUE THREAD

**Issue by EdozdeDandez** [spatie/laravel-permission#1451]
I have been using this package for roles and permissions but suddenly after updating I can't seem to access things using the @can directive.

I have a permission with the name "send sms" in the permissions database. And a role is assigned that permission. However, users with that role can't access things reserved for that permission.

The blade code

```blade
 @can('send sms')
          <a href="#" class="btn-export oval" data-toggle="modal" data-target="#sendSMS">SEND SMS <img src=""></a>
@endcan
```

Users model
```php
class Admin extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    protected $fillable = [
        'name', 'email', 'password', 'username', 'createdBy', 'modifiedBY'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'password_reset_token'
    ];
}
```

**Comment by drbyte** [comment]
> but suddenly after updating I can't

"Updating"?  What all did you update? From what to what? As much detail as possible.

**Comment by rbrostowiez** [comment]
Hey, just had this issue myself, and it is most likely cache-related as it's got a 24hr cache enabled by default, and assigning roles to users doesn't seem to clear/update it.

`php artisan permission:cache-reset`

**Comment by drbyte** [comment]
> cache enabled by default, and assigning roles to users doesn't seem to clear/update it.

It might be cache-related. 
But all the built-in methods of assigning roles and permissions automatically clears the cache. Unless you've got code changes that have altered the normal operation.

**Comment by ShaileshInfyom** [comment]
same issue to me

**Comment by drbyte** [comment]
We can't help you when you say "same issue". You need to provide as much detail as possible. 
Specifically: provide EXACT instructions on how to recreate the problem on a new install of Laravel. And show your code.

**Comment by ShaileshInfyom** [comment]
I set up a fresh Laravel 7 application with followed steps of installation of this package.
created one user and assign a role like this.

```
Route::get('/', function () {
    $role = Role::create(['name' => 'writer']);
    $permission = Permission::create(['name' => 'edit articles']);
    $role->givePermissionTo($permission);
    Auth::user()->assignRole('writer');
    return view('welcome');
});
```
I register middlware in kernal.php 

now I tried to set middleware and access articles. 
```
Route::group(['middleware' => ['can:edit articles']], function () {
    Route::resource('articles', 'ArticlesController');
});

```
But I getting this error.
![image](https://user-images.githubusercontent.com/28335166/82156558-544d6d00-9899-11ea-8022-70f216430683.png)

**Comment by Prince-Costa** [comment]
Returning empty.
 $user = auth()->user();
        dd($user->getAllPermissions());
        if (!auth()->user()->can('permission.view')) {
            abort(403, 'Unauthorized action.');
        }

Trying to reset cache by 'php artisan permission:cache-reset' and getting error 'Unable to flush cache'.

what to de?
