### ISSUE TITLE
Proposed PR: A new trait that allows only a single role

### ISSUE THREAD

**Issue by jbraband** [spatie/laravel-permission#1456]
Would Spatie be interested in merging in a PR that adds a HasSingleRole trait?

I have it added to my project and its slick!

Something like this:

```
namespace Spatie\Permission\Traits;

use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Exceptions\MoreThanOneRole;

trait HasSingleRole
{
    use HasRoles {
      HasRoles::assignRole as parentAssignRole;
    }

    /**
     * Assign the given role to the model.
     *
     * @param array|string|\Spatie\Permission\Contracts\Role ...$roles
     *
     * @return $this
     */
    public function assignRole(...$roles)
    {
      $roles = collect($roles)
                ->flatten();

      if ($roles->count() > 1) {
        throw MoreThanOneRole::create();
      }

      $model = $this->getModel();

      if ($model->exists) {
          if ($this->roles->count() > 0) {
            throw MoreThanOneRole::create();
          }
      }

      return $this->parentAssignRole($roles);
    }

}

```
and the exception 
```
namespace Spatie\Permission\Exceptions;

use InvalidArgumentException;
use Illuminate\Support\Collection;

class MoreThanOneRole extends InvalidArgumentException
{
    public static function create()
    {
        return new static("The given model is being assigned more than one role.");
    }
}
```
Let me know if that would be considered for merging and I'll prepare the PR. I found some Issues that referenced wanting a single role restriction, but no clear solution for it.

This idea would also be made into a trait named HasNRoles or something. The trait would add a property call $allowedRoleCount which would be used for counting if the assign call is valid.

**Comment by drbyte** [comment]
Hi @jbraband 
Thanks for your suggestion.
Would you please explain the use-case for this: what business problem do you see it aiming to solve?

**Comment by jbraband** [comment]
Specific to my project: the Laravel codebase that manages our users (a CRM platform) syncs information about the users to other systems. One of those things is role for our website. There is an intrinsic requirement on our website that requires a user only have a single role. Having that same constraint within our CRM system is beneficial for management and validation purposes.

Generally speaking, I would think that approach i mentioned at the end of the first comment about creating a HasNRoles trait would be the most flexible for multiple use cases. I suppose though that this change could just be implemented to the existing HasRoles trait, so long as the default number of allowed roles is infinity.

I am using the HasSingleRole trait posted above in QA at the moment and intend to deploy to my production environment soon. This post is just offering my enhancements to the community and the package. I'm willing to further refine the idea through a PR process, but did not want to take that step unless there was interest by the maintainers.

Thanks for thinking about this!

**Comment by drbyte** [comment]
@jbraband Thanks for sharing your code. 

While I'm satisfied that the approach you've taken is appropriate for the purpose you're using it, I probably wouldn't merge a PR for it because we're trying to keep the package as lean as possible. 

That said, anyone can easily use the code you've shared if they need to enforce a similar restriction (or alter it for N restrictions, as you suggested).

Thanks again for sharing your idea!

**Comment by ashek1412** [comment]
hi @jbraband . I used ur code but it didn't prevent user from assigning multiple roles

**Comment by jbraband** [comment]
> hi @jbraband . I used ur code but it didn't prevent user from assigning multiple roles

if you have a repository (even a minimal one) that demonstrates the problem, I'd be willing to take a look
