### ISSUE TITLE
Gate::before callback can't support custom guard name

### ISSUE THREAD

**Issue by git-liu** [spatie/laravel-permission#1459]
PermissionRegistrar register Gate::before callback can't set custom guard, check permission always use default guard. Can support custom guard name ?

**Comment by drbyte** [comment]
@git-liu if you manually make the changes to Guard.php as shown in PR #1384 (yes, by temporarily editing the file in your vendor directory), does that solve the problem you're facing? I realize it handles it in a different place, but I'm thinking that it's the same issue.
