### ISSUE TITLE
Keep user roles valid for the model it belongs to

### ISSUE THREAD

**Issue by 77media-creations** [spatie/laravel-permission#1461]
### Situation

I have a situation where a user hasMany (relation) to project model. 
I wanted user to have a role specific to the project model which checks for the permissions to manage this particular project.

### Example
For example a user has two projects. 
He created the first project so he owns it and acts as an admin for this project. `->role('project-admin')`.
The second project is assigned to him by another owner to manage it, means he is a manager for this second project `->role('project-manager')`.

### Issue
Now if this user visit to the second project he has the admin permissions there because of the check `can('project-admin')`.

### Possible Fix
So I was wondering, if we can have something like an extra column in 'model_has_roles' table where the related model id can be saved as well which means this role is applied on this particular model (project model) for this user.

**Comment by drbyte** [comment]
While this package does allow for polymorphic relations where objects can be assigned permissions relative to other objects, it doesn't provide multiple-dependency relationships outside of that structure. 
You are free to alter the schemas to suit your needs. Often combining with Model Policies simplifies this process.
