### ISSUE TITLE
Roles not being assigned to default user after migrations.

### ISSUE THREAD

**Issue by O-F-O** [spatie/laravel-permission#1462]
Hi, 
I have an issue with spatie laravel-permission. I edited the users table from name to username and also included extra fields (first_name and last_name).

The issue arises when I run a fresh migration. The default roles (Admin, User) are not assigned to the different users created. Is there a code that I should have edited as well? Probably model_has_role?

**Comment by drbyte** [comment]
> The default roles (Admin, User) are not assigned to the different users created.

This package doesn't have any "default roles' to assign.

>  Is there a code that I should have edited as well? Probably model_has_role?

Normally you shouldn't touch any of the tables used by this package. The only reason to make a change to this package's tables is if you've changed the name or type of the `id` field in your user models (which typically isn't necessary; sometimes people change it for uuid implementation but I personally don't recommend that).

>  I edited the users table from name to username and also included extra fields (first_name and last_name).

If those are the only changes you made, then that should not interfere with this package.

**Comment by O-F-O** [comment]
Thanks for the feedback. I got it working.
