### ISSUE TITLE
Permission Class and Role Class null in User instance...

### ISSUE THREAD

**Issue by NicoMachado** [spatie/laravel-permission#1463]
Hello, I'm a quite new to Laravel and Spatie.

And I have this question.
I have this method in UserController

    public function getPermissions()
    {
        $id = auth('api')->user()->id;
        $user = User::find($id);

        dd($user);
...
the idea is to get a collection of Permissions to the current User.

my dump shows that "roleClass" and "permissionClass" is null.

I only get data with:
$permissions = $user->getAllPermissions();

but not with :
$permissions = $user->permissions;
neither with ...
$permissionNames = $user->getPermissionNames();

![image](https://user-images.githubusercontent.com/23136927/80751492-4610fa00-8b00-11ea-86a0-bd2cb40e2fd3.png)

please can you tell me where I'm wrong...

Regards

**Comment by drbyte** [comment]
`$user->permissions` is a list of `permissions` directly assigned to the user, NOT permissions inherited by `roles` that the user is associated with. 

From https://docs.spatie.be/laravel-permission/v3/basic-usage/role-permissions/ :
```
// Direct permissions
$user->getDirectPermissions() // Or $user->permissions;

// Permissions inherited from the user's roles
$user->getPermissionsViaRoles();

// All permissions which apply on the user (inherited and direct)
$user->getAllPermissions();
```

**Comment by NicoMachado** [comment]
Great! I understand now what "direct" means!
Best Regards
