### ISSUE TITLE
error in php artisan migrate, on linux

### ISSUE THREAD

**Issue by netwons** [spatie/laravel-permission#1464]
run in php artisan migrate
**this show error:**
`config/permission.php not found and defaults could not be merged. Please publish the package configuration before proceeding.`

**Comment by drbyte** [comment]
A patch for this problem which rarely happens, and only on Windows, was made in release v3.10
In fact, that's what generates the "Please publish the package configuration" message.

It's telling you it can't find the `config/permission.php` file (and indirectly that it also couldn't merge the defaults provided by the package, which suggests a bigger issue with your environment or your app).

So, the first question is: did you publish the `config/permission.php` file? What's in it? 

Next question: how is your application different from a fresh `laravel new myproject` creation? ie: what other packages are conflicting? 

And also, what exactly is your "dev" environment? What does your unique environment have in common with the others in #1411 who had similar issues? Probably something environmental is causing this.

**Comment by netwons** [comment]
I changed version packages ۳.۹
Now it gives this error: 
`SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(191) not null, `guard_name` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

**Comment by drbyte** [comment]
> I changed version packages 3.9
> Now it gives this error:
> `` SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` ...

Yes, that's because the permissions config isn't available when the migration is trying to read the planned table names.

It's exactly why in 3.10.0 we intercepted the empty permissions config scenerio to display the message in your earlier post: `config/permission.php not found and defaults could not be merged. Please publish the package configuration before proceeding`

**Comment by netwons** [comment]
What should I do now?

**Comment by drbyte** [comment]
> What should I do now?

I asked earlier:

> So, the first question is: did you publish the `config/permission.php` file? What's in it?
> 
> Next question: how is your application different from a fresh `laravel new myproject` creation? ie: what other packages are conflicting?
> 
> And also, what exactly is your "dev" environment? What does your unique environment have in common with the others in #1411 who had similar issues? Probably something environmental is causing this.

**Comment by netwons** [comment]
1-yes config/permission.php file exiest
2-  "php": "^7.2",
        "barryvdh/laravel-debugbar": "^3.2",
        "doctrine/dbal": "^2.10",
        "fideloper/proxy": "^4.0",
        "google/cloud-vision": "^0.25.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0",
        "predis/predis": "^1.1",
        "ruflin/elastica": "^6.1",
        "shetabit/payment": "^2.4",
        "spatie/laravel-permission": "3.9.*"
3-yes

**Comment by drbyte** [comment]
I can't recreate the problem on a new project.

```sh
composer create-project laravel/laravel:"^6.2" permcfgtest
cd permcfgtest
composer require barryvdh/laravel-debugbar --dev
composer require doctrine/dbal google/cloud-vision predis/predis shetabit/payment ruflin/elastica
# (create database and configure .env accordingly)
php artisan migrate # (no errors)
composer require spatie/laravel-permission:"3.9.*"
php artisan vendor:publish   # (choose Spatie Permission ServiceProvider)
```
```
Copied File [/vendor/spatie/laravel-permission/config/permission.php] To [/config/permission.php]
Copied File [/vendor/spatie/laravel-permission/database/migrations/create_permission_tables.php.stub] To [/database/migrations/2020_05_01_163441_create_permission_tables.php]
Publishing complete.
```
```sh
php artisan migrate
```
```
Migrating: 2020_05_01_163441_create_permission_tables
Migrated:  2020_05_01_163441_create_permission_tables (0.01 seconds)
```
No errors about missing tablename.

Is there a step missing?

**Comment by Crasheng** [comment]
> run in php artisan migrate
> **this show error:**
> `config/permission.php not found and defaults could not be merged. Please publish the package configuration before proceeding.`

Just run

php artisan cache:clear
php artisan config:cache

**Comment by drbyte** [comment]
`php artisan config:clear` may be enough. So is `optimize:clear`.

But why are people caching config in dev?
