### ISSUE TITLE
Spatie permission with where role = ?

### ISSUE THREAD

**Issue by adeguntoro** [spatie/laravel-permission#1465]
I use this join on my project, but i just want to display user and all their data where user role is admin. 
```
$users = DB::table('users')
            ->join('contacts', 'users.id', '=', 'contacts.user_id')
            ->join('orders', 'users.id', '=', 'orders.user_id')
            ->select('users.*', 'contacts.phone', 'orders.price')
            ->where( user_role = "Admin" )
            ->get();
```
How can archive something like this ?

**Comment by drbyte** [comment]
If you set up Eloquent relationships amongst your tables, Laravel can do all the joins with an Eloquent call. Including the `role()` scope will leverage the roles functionality offered by this package.
```
$users = User::query()
        ->role('Admin')
        ->with(['contacts', 'orders'])
        ->get();
```

**Comment by rcvioleta** [comment]
This doesn't answer the question, so does it mean we need to create a eloquent relationship to display the user data including the spatie roles? Let's say there's no need to query which roles needs to be fetch, example we are joining tables and our goal is to include or append the user role to the end result?

**Comment by drbyte** [comment]
> with eloquent relationship you query most of the data that you won't need ...

You are certainly welcome to write your own join queries. You can reverse-engineer the query joins that Eloquent performs and match them up with your app-specific models to suit your needs.

**Comment by rcvioleta** [comment]
Not a problem, I found the answer here: https://laracasts.com/discuss/channels/laravel/get-spatie-roles-included-with-the-query-builder?page=1#reply=609463
