### ISSUE TITLE
The middleware does not work inside the controller method!

### ISSUE THREAD

**Issue by serkor** [spatie/laravel-permission#1469]
`public function create() {

       $this->middleware('permission:create appeals'); //does not work

		$appeals= Appeal::where( 'public', 1 )->get();

		return view( 'front.appeals.create', compact( 'appeals' ) );

	}`

**Comment by drbyte** [comment]
Correct. 

Use middleware in the controller's constructor, or else use Laravel's policy features within your controller methods.

**Comment by serkor** [comment]
If I specify all permissions in the constructor for this controller, they will be available in all methods. This is a hole.
It is good when the middleware for a certain resolution worked inside the desired controller method.
Using middleware in routes does not suit me, my routes have a resource method.

**Comment by serkor** [comment]
Please tell me how to correct the middleware so that it would work inside the controller method?

**Comment by drbyte** [comment]
Following the Laravel docs: use the `only` or `except` methods to restrict middleware to fire on certain methods:
https://laravel.com/docs/master/controllers#controller-middleware
