### ISSUE TITLE
Is there a correct way to delete a permission?

### ISSUE THREAD

**Issue by 1e4** [spatie/laravel-permission#1471]
I've read through the documentation and searched the issues, however I haven't seen an obvious way to delete a permission. 

Can I assume the correct way is;
Remove the permissions from the role
Remove the permissions from users
Delete the permission

Are there any other steps? Removing from cache or something? Use case is where permissions can be dynamically added and removed, and in some cases deleted. 

Thanks for package it really makes handling permissions simple.

**Comment by drbyte** [comment]
Roles and Permissions are Eloquent models, so you can simply call `->delete()` if you want them removed from everywhere. The migrations have foreign key relations, so it will remove them from anywhere they've been assigned.

For cache-clearing, if you are also assigning other roles/permissions at the same time using the built-in methods as documented at https://docs.spatie.be/laravel-permission/v3/advanced-usage/cache/ then the cache will be reset automatically. You can manually clear the cache if you need to as well.

**Comment by 1e4** [comment]
> Roles and Permissions are Eloquent models, so you can simply call `->delete()` if you want them removed from everywhere. The migrations have foreign key relations, so it will remove them from anywhere they've been assigned.
> 
> For cache-clearing, if you are also assigning other roles/permissions at the same time using the built-in methods as documented at https://docs.spatie.be/laravel-permission/v3/advanced-usage/cache/ then the cache will be reset automatically. You can manually clear the cache if you need to as well.

Thank you. I knew they were models, just wanted to be sure there wasn't any magic that would bite me. 

I'll manually clear the cache just to be safe

Thanks so much!

**Comment by drbyte** [comment]
Update: if you're using the built-in Role and Permission models, it will clear the cache automatically on delete. This is because the models use this trait:
```php
use Spatie\Permission\Traits\RefreshesPermissionCache;
```
If you've created your own models that don't extend the built-in models but instead only implement the contract, then you will want to add the trait to your models.

**Comment by 1e4** [comment]
Thanks Chris! Appreciate the extra info 👍

**Comment by Kendaichi** [comment]
Hello, when I was trying to delete a permission or even a role. Using this function

`    public function deletePermission($permissionId)
    {
        $permission = Permission::findById($permissionId);

        $permission->delete();

        return response()->json([
            'success' => true,
            'message' => 'Permission deleted successfully',
        ]);
    }`

I am getting an error:
Class name must be a valid object or a string. 

Can anybody here help me with this?

**Comment by abdelhak002** [comment]
> Hello, when I was trying to delete a permission or even a role. Using this function
> 
> ```
> `    public function deletePermission($permissionId)
>     {
>         $permission = Permission::findById($permissionId);
> 
>         $permission->delete();
> 
>         return response()->json([
>             'success' => true,
>             'message' => 'Permission deleted successfully',
>         ]);
>     }`
> ```
> 
> I am getting an error: Class name must be a valid object or a string.
> 
> Can anybody here help me with this?

I am having the same issue, but for the Role model, when I call `$role->delete()` I get that error **Class name must be a valid object or a string**

**Comment by SLarpea** [comment]
same problem here.

`$role->delete()`

generates error

`Class name must be a valid object or a string`

**Comment by aldinokemal** [comment]
still having same problem

<img width="766" alt="Image" src="https://github.com/user-attachments/assets/97a9e4b7-9814-453b-831c-db4384ed71c0" />

**Comment by itakwad** [comment]
Class name must be a valid object or a string
When I try $permission->delete(); even I confirmed it is Model

**Comment by rafeaaSaayfan** [comment]
@abdelhak002 @aldinokemal @SLarpea 
Class name must be a valid object or a string

this error because the guard_name (the col of this row that you want to delete) its not equal web 
you need to change the guard_name to web 

and if you want to create a new guard_name you need to put it in the config/auth.php
