### ISSUE TITLE
Using HasRoles trait on another Model

### ISSUE THREAD

**Issue by Smart-S-Max** [spatie/laravel-permission#1473]
Hello,

I’m trying to set up this package for our app and I was wondering if it is possible to use the `HasRoles` trait on another model which is not a `Illuminate\Foundation\Auth\User` ?

Everything seemed to work, I can assign permissions or roles to my model, check if it `hasPermissionTo`, but whenever I try to access the `permissions` property, via direct access or through the `getAllPermissions()` function (or similar), I get the following error : 

```
Undefined property: App/Team::$permissions
```

Is it possible to have it working with another model like this ?

Thank you for your time and work !

**Comment by drbyte** [comment]
In addition to `use HasRoles` trait, your model must implement the `Illuminate\Contracts\Auth\Access\Authorizable` contract, either by extending `User` or implementing the contract directly. 
See: https://docs.spatie.be/laravel-permission/v3/advanced-usage/extending/

**Comment by Smart-S-Max** [comment]
Thank you for your answer,

I implemented the contract directly, added the `can()` method to match the interface but I’m still having the same error.
I tried the following in Tinker : 

```
\App\Team::first()->permissions
```

But I’m still getting 

```
PHP Notice:  Undefined property: App/Team::$permissions in ./vendor/spatie/laravel-permission/src/Traits/HasPermissions.php on line 305
```

Any clue ?

Thanks in advance

**Comment by drbyte** [comment]
Line 305 is using Laravel's magic methods to access the relationship defined on line 43. Does your Team model have a `permissions()` method that's overriding the one in the trait?

**Comment by Smart-S-Max** [comment]
Ok I’m dumb.

I defined a `getPermissionsAttribute()` function inside my model, this is what caused the override...

Thank you very much for your help !

**Comment by aeadedoyin** [comment]
> Ok I’m dumb.
> 
> I defined a `getPermissionsAttribute()` function inside my model, this is what caused the override...
> 
> Thank you very much for your help !

For those having the same issue, in your user model:.
```
    public function __construct()
    {
        $this->getAllPermissions();
    }
```
