### ISSUE TITLE
How i give permission for according to clinic

### ISSUE THREAD

**Issue by nitiz143** [spatie/laravel-permission#1474]
I have the same role and same permission in a different company but how I give permission according to clinic

**Comment by nitiz143** [comment]
` "message": "SQLSTATE[HY000]: General error: 1364 Field 'clinic_id' doesn't have a default value (SQL: insert into `role_has_permissions` (`permission_id`, `role_id`) values (13, 1))",
    "exception": "Illuminate\\Database\\QueryException",`

Can you please help that issue

**Comment by nitiz143** [comment]
What I need 
I have 5 roles
1. Super admin that create the clinic
2. clinic admin  that will manage all the  permissions (Therapist, Receptionist, patient)
3.Therapist
4. Receptionist 
5. Patient

For now, only  Super admin manages the permissions.

**Comment by rlvillacarlos** [comment]
I am not sure if I understand your question. But as I see it you want to set permission per clinic but the set of permissions are the same across all clinics. Is that right? 

What is the reason for doing this? Is it because you have a single web app for different clinics and users must be able to perform actions based on their role and their assigned clinic? That is, you do not want Therapist 1 from Clinic A to be able to perform actions for a therapist for another Clinic B?

**Comment by nitiz143** [comment]
Yes I have the same roles and permission modules but I want to assign permission according to clinic. Every clinic have own permission module and clinic admin will manage the role's permission

**Comment by rlvillacarlos** [comment]
If you need to be able to prevent one user from performing an action for a clinic that he/she is not part of, using only this library, then you must have separate roles per clinic, even if they are essentially the same. Say you have a theraphist. If you only use a single theraphist role across all clinics then there is no way to determine if the assigned theraphist can perform an action for the given clinic. So maybe  you can create clinic specific role. That is, for each clinic, you create separate roles and then assign them to each users of the clinic. 

If you do not want to repeatedly create roles per clinic and you are sure that there will be no clinic specific permissions for each roles, then you can set up a User and Clinic models that are related, say BelongsTo. Then you can check first if the user belongs to the given clinic then apply the test for permission. Or maybe you can interchange the order of the checking. That is entirely up to you. The only problem I think with this approach is if you need to assign different permission for the same role in different clinics. For that you can maybe create a separate clinic specific role that you can add as additional role. Or maybe you can directly assign the clinic specific permission to the user. Again your choice. 

Maybe it would be nice if we can have role hierarchy? Where we can apply some form of inheritance. Although I am not sure of more use cases.

**Comment by kingashok29** [comment]
Hello @rlvillacarlos can you help me with one issue?
I have one master database where I store admin data so admin can manage the application. Each time new customers sign up for an account, the new database will be created for that customer. I am using this package to manage roles and permission, there are 3 roles for admin like cashier, support staff and admin, everything is working fine, I can assign role OR permissions to role, etc.

Now I want to implement the same thing for the customer as well, which means each customer after signup can create a staff with roles like an agent, reader, etc, I want to give the customer the option to assign role and permission to his staff only.

I tried by extending the Role and Permissions model, switching database connection, and updating the config file as well but still not working. You can view [this issue](https://github.com/spatie/laravel-permission/issues/1499) for more information

**Comment by gerardnll** [comment]
I made something similar. I your case, I would create a migration adding the 'clinic_id' (I had to drop the primary key) and overwrite the Role and Permissions models so you can overwrite the HasRoles trait and alter the roles() function. In that function I would add something like: ->wherePivot('clinic_id', App::getClinicID()) so all calls to the relation are scoped.

To be able to assign roles you would also have to overwrite the assignRole() function so when syncing roles you add the pivot information.

**Comment by nitiz143** [comment]
Thanks for the help

**Comment by jv-ak** [comment]
> I made something similar. I your case, I would create a migration adding the 'clinic_id' (I had to drop the primary key) to 'model_has_roles' and overwrite the Role and Permissions models so you can overwrite the HasRoles trait and alter the roles() function. In that function I would add something like: ->wherePivot('clinic_id', App::getClinicID()) so all calls to the relation are scoped.
> 
> To be able to assign roles you would also have to overwrite the assignRole() function so when syncing roles you add the pivot information.
> 
> My use case (applied to your context) was a table of Employees, shared over all Clinics. And Employees could have different roles depending on the Clinic.

Hi, sorry for replying this late, but I'm facing the exact same issue and apparently I'm too dumb to properly overwrite the Role and Permission models to add the suggested "wherePivot('clinic_id')" code.

Any help would be appreciated.
