### ISSUE TITLE
Call to a member function assignRole() on boolean

### ISSUE THREAD

**Issue by saadabdurrazaq** [spatie/laravel-permission#1479]
Can you guys please solve the problem? Detail problem here https://stackoverflow.com/questions/61944657/laravel-bulk-insert-to-another-table-from-selected-multiple-rows

**Comment by drbyte** [comment]
Copying/duplicating users is not something related to this package.

As far as assigning roles to a User object, once you have the object you can simply call assignRole on it.
But, you MUST first have the User object in memory: you can't have a boolean or a queryBuilder object.

In a fresh Laravel app this works fine:
```php
$user = User::create([
    'email'=>'foo@example.com', 
    'name' => 'Foo', 
    'password' => $cryptedpwd],
);
$user->assignRole('writer');
```

**Comment by saadabdurrazaq** [comment]
I need to copy bulk of data's and multiple records to another table. As far as I searched this way, it can be accomplished by `insert()`. I have no idea with `create()` in this situation. Can you bring me an answer with more specific? Yes, with `create()` it can add the data, but it only one row.

**Comment by saadabdurrazaq** [comment]
Also, I am trying with this approach, but show me result Call to undefined method Illuminate\Database\Query\Builder::assignRole()
```
$get_username = \App\Applicant::select('username')->whereIn('id', $ids);
        $updateUser = \App\User::whereIn('username', $get_username);
        $updateUser->assignRole('Applicant');
        $updateUser->save();
```

**Comment by drbyte** [comment]
You cannot call `assignRole()` on a query object. You must first run the query. Often this is done with `->get()` or `->first()`. In Laravel, calling `first()` will give you the actual object. If you use `get()` then you get a collection and need to iterate through the results.

```diff
-    $updateUser = \App\User::whereIn('username', $get_username);
+    $updateUser = \App\User::whereIn('username', $get_username)->first();
    $updateUser->assignRole('Applicant');
```
or 
```diff
-    $updateUser = \App\User::whereIn('username', $get_username);
+    $updateUser = \App\User::whereIn('username', $get_username)->get();
+    $updateUser->each(function ($u) {
+        $u->assignRole('Applicant');
+    });
```

**Comment by saadabdurrazaq** [comment]
I haven't tried your code, I just tried this code, and work!
https://stackoverflow.com/questions/61952222/laravel-spatie-call-to-undefined-method-illuminate-database-query-builderassig/61952622#61952622

**Comment by RafaelJP13** [comment]
I was with the error **Call to a member function assignRole() on int**

`  $userCreated = User::create([
       'name' => 'Rafael'      
])->id;`

Just remove the ->id
