### ISSUE TITLE
@role blade directive issue

### ISSUE THREAD

**Issue by AntonioGiangrave** [spatie/laravel-permission#148]
Config file (\config\laravel-permission.php ) still red in my IDE and @role directive not work in blade. 
@can work correctly.
I'm running on 5.2

What could be?

Thanks

**Comment by freekmurze** [comment]
Did you follow all [installation instructions](https://github.com/spatie/laravel-permission#install)? 

Are you getting a specific error?

**Comment by AntonioGiangrave** [comment]
Yes of course, i follow instruction and repeat N time.
In a new 5.2 installation work correctly, in my site appear @role @endrole plain in output

**Comment by freekmurze** [comment]
The tests seems to indicate that the `@role` directive is working as intended.

https://github.com/spatie/laravel-permission/blob/master/tests/BladeTest.php#L50

Could you try installing the package in a fresh copy of Laravel and see if that works? If not, send me over a copy of that application.

**Comment by AntonioGiangrave** [comment]
In a fresh copy of laravel working correctly, but in my project (https://github.com/AntonioGiangrave/kairosformazione) but in my project the @Role directives are ignored. I tried to take the test that you have shown me but apart from the "Integrity constraint violation" I can not see anything useful.

**Comment by freekmurze** [comment]
Try to find the differences between the fresh copy of Laravel you used and your actually project. Pretty sure the problem is caused by something specific to your project.

**Comment by AntonioGiangrave** [comment]
no way out, I had to use a new installation of L5.2 and move all my code on it. So Spatie-permission works properly.
Thank you
