### ISSUE TITLE
Create permission for newly created resource

### ISSUE THREAD

**Issue by asivaneswaran** [spatie/laravel-permission#1481]
Hi guys.

Quick question. I am using the wildcard permission to give access to different users different resources.

For example, let's say I have an author, I want that author to be able to only edit the articles he created.

So I set up the permissions like so:

```
articles.index
articles.create
articles.edit.1
articles.edit.2
```

But let's say he creates a new article, is there a way to create permission for that? I don't want to put it in the controller as that is a simple example but in my project, let's say a cronjob can create the article automatically or something. I am guessing I have to add a listener, but then let's say I have multiple resources, I need to create multiple listeners? Is there an easier/cleaner/faster way to do this or no?

**Comment by drbyte** [comment]
The roles/permissions facilities have NO idea whether the user is ALSO the author of a given record. That's something your app needs to code for, and is a perfect use of Laravel Policies. Inside your policy's methods for checking authorization around ownership you can also combine checks around roles/permissions. 
eg: 
```
if ($article->author_id == $user->id) return true;
if ($user->can('articles.edit.*')) return true;
```

**Comment by asivaneswaran** [comment]
I see. I thought it is not good practice to combine both, but I guess not. Thanks a lot!

**Comment by drbyte** [comment]
Definitely!

https://docs.spatie.be/laravel-permission/v3/best-practices/using-policies/
