### ISSUE TITLE
$this->permissions could be an empty string

### ISSUE THREAD

**Issue by wikirex** [spatie/laravel-permission#1486]
I'm just wondering where $this->permissions come from in trait HasPermissions.
I found $this->permission could be an empty string and this will cause some errors.
Call to a member function contains() on string

I add some scripts in line 285 to fix this problem for now
`if($this->permissions == false){
            return false;
}`

**Comment by drbyte** [comment]
No, it would only be a string if you have your own property for it, such as a `permissions` field in your `users` table.

**Comment by drbyte** [comment]
Normal operation:
```php
$user = factory(\App\User::class)->create();
$user->permissions;
```
output:
```
 Illuminate\Database\Eloquent\Collection {#1097
     all: [],
   }
```
