### ISSUE TITLE
Multi guard multi database support.

### ISSUE THREAD

**Issue by kingashok29** [spatie/laravel-permission#1490]
I'm using Laravel 7, I have two guards, 'admin' and 'client' and storing all admin related data in the Main database, as well using role/permissions on the main database with a different type of roles like staff, accounts, etc to manage route level access, everything working fine in admin side.

When new user signup, they will have their own database with specific tables and default data, now I want to store their own roles and permission on their own database so they can assign roles and permission.

So far, I have done these things to accomplish this on the client-side.

- Created permission and roles table.
- Create two new models ClientRole, ClientPermission and both extend Role and Permission model as specified in the document.
- Set the connection to the client database.
- On client model used 'client' guard, and use HasRoles.

Seeded default roles and permissions with guard name 'client', but later when I try to assign role or permissions, I get an error that Role/Permission with guard name 'client' does not exist, means the request is made on the Main database instead of client database. How can I resolve this?

**Comment by kingashok29** [comment]
`<?php

namespace App\Client;

use Spatie\Permission\Models\Permission as SpatiePermission;

class ClientPermission extends SpatiePermission
{
    protected $connection = 'client';
}
`

`<?php

namespace App\Client;

use Spatie\Permission\Models\Role as SpatieRole;

class ClientRole extends SpatieRole
{
    protected $connection = 'client';
}
`

When I try to access the permission assigned to the client.
`ErrorException
There is no permission named `manage properties` for guard `client`.`

**Comment by drbyte** [comment]
Sounds like your `config/permission.php` is still using the default Spatie models and not your App namespace models.

**Comment by kingashok29** [comment]
But to manage roles and permissions in admin dashboard, I use the default role and permissions model, and working as normal. So if I want to use custom role and permission model then updating the config is also required?

**Comment by drbyte** [comment]
Yes. Or use some other way to switch database connections in your app during runtime.

There are lots of online resources for doing multi-database multi-tenant which address switching databases in different contexts. You may find them a useful resource for inspiration in building your app.
