### ISSUE TITLE
Interaction between Guard and Policy for Permissions

### ISSUE THREAD

**Issue by lodzen** [spatie/laravel-permission#1491]
Hello,

I need some help to understand the interaction between gates and policies.
The problem I am facing is that I created a permission (start device) and I need to check in a policy that the currently logged in user owns the device.
I created a DevicesPolicy for Model Devices and registered it in the AuthServiceProvider.
When I call the `@can(start device, $device)` helper in the blade the policy is not called and I am able to start every device. 
The solution I found is to call the `@can(start-device`, $device) blade directive with a different name than the permission and in the policy is check for the actual permission.
Is this the correct way to implement such a use case?

**Comment by drbyte** [comment]
Correct: "namespacing" always removes any ambiguity. ie: Name the permission something different than the rule you wish to trigger in the Policy. 

As I recall, Laravel's fallback/precedence order for the `can()` helper is: first it resolves the Policy method, and then the Gate ability by that name. So `$user->can('update', $post)` will first check for `update` in the `PostPolicy` and if not found then checks for a `Gate` ability named `update`. To avoid any ambiguity or forcing yourself to remember the order when you look at the code 6 months from now, name them differently and then it will be clear.

**Comment by lodzen** [comment]
Thank you for the quick reply.
What i face is that the policy is not called first.
At least if i add a dd to stop the execution in the policy. I'am not 100% sure about the naming convention of the callbacks in the policy. If i have a permission start device, then i need to name the callback function startdevice in the policy?

**Comment by drbyte** [comment]
In my experience simply naming them differently from each other gives you the explicit control you're looking for.
