### ISSUE TITLE
Clarification on Guard::after, hasPermissionTo, and can when implemeting super admin

### ISSUE THREAD

**Issue by rlvillacarlos** [spatie/laravel-permission#1492]
I have created a model policy and set my super admin on Gate::after so that I will be able to prevent the super admin to do certain actions if they do not have a direct permission.

As it turns out, if I use the `can` method for the user in one of the method in my model policy, the Gate rule is being executed first, including the Gate::after. It means that `can` returns true when I test for user permission for a super admin in my model policy method, even if the user has no such permission. This is not the case if I instead use `hasPermissionTo`. 

Does this mean I should use `hasPermissionTo` instead of `can` in cases when I want to prevent even the super admin for doing certain actions? I have checked the documentation for laravel-permission on implementing super admin but was not able to see anything about this.

I hope to get some clarification. Thanks.

**Comment by drbyte** [comment]
I haven't implemented Super Admin using Gate::after inside policies the way you describe, so I can't offer much assistance in that specific case.
However, as you state, using `hasPermissionTo` gives the correct desired result, which does kinda make sense from within a Policy as opposed to direct calls to `can()` on the User object.

**Comment by rlvillacarlos** [comment]
I am not sure of other possible use case than what I have but maybe you can consider looking at this and including it in the documentation?
