### ISSUE TITLE
Chain blade directives

### ISSUE THREAD

**Issue by ClementN** [spatie/laravel-permission#1495]
Hello,

Probably this is a feature suggestion ...

Will it be possible to have a chain of @hasrole (or can) directives?

A kind of   "else hasrole"

Eg
```
@hasrole('writer') 
  I am a writer!
@else hasrole('editor') 
  I am an editor!
@else 
   I am not one of the above roles...
@endhasrole
```

**Comment by drbyte** [comment]
Hi, thanks for your suggestion.
I don't think we'll be adding a directive for that.

Other options include:
- Blade's `@switch` directive - https://laravel.com/docs/master/blade#switch-statements -- useful when you're getting into multiple nested if/else/else/else/else conditions such as you describe. This makes it easier to nest other Blade directives within each `@case` as well.
- Blade's `@php` directive - https://laravel.com/docs/master/blade#php
- Write your own custom Blade directive for `elseHasRole`, in your AppServiceProvider
- or just use Blade directly `@else(auth()->user()->hasrole('editor'))` (or some variation on that depending on your needs)
