### ISSUE TITLE
how to get the super-admin name from the roles

### ISSUE THREAD

**Issue by dele-corporate** [spatie/laravel-permission#1496]
the results displayed `$item->roles` like this `[{"id":1,"name":"super-admin","guard_name":"admin","created_at":"2020-06-11T09:37:06.000000Z","updated_at":"2020-06-11T09:37:06.000000Z","pivot":{"model_id":1,"role_id":1,"model_type":"App\\Admin"}}]`
how to take the name value from these results.

**Comment by drbyte** [comment]
```php
$super_admins = \App\Admin::role('super-admin')->get();
```
or
```php
$role_model = Role::find(1); // where 1 comes from the "id" in $item->roles as you posted
$super_admins = \App\Admin::role($role_model)->get();
```

More: https://docs.spatie.be/laravel-permission/v3/basic-usage/basic-usage/

**Comment by dele-corporate** [comment]
> ```
> $super_admins = \App\Admin::role('super-admin')->get();
> ```
> 
> or
> 
> ```
> $role_model = Role::find(1); // where 1 comes from the "id" in $item->roles as you posted
> $super_admins = \App\Admin::role($role_model)->get();
> ```
> 
> More: https://docs.spatie.be/laravel-permission/v3/basic-usage/basic-usage/

Thank you for replying, I got that value from `App\Admin::with('roles')->get()`

I can already get the value that I want by using Foreach.
