### ISSUE TITLE
Problem when trying to handle PermissionDoesNotExist Exception

### ISSUE THREAD

**Issue by IwanToTeW** [spatie/laravel-permission#1497]
Hello everyone !

I am building a UI, where an admin can create/delete permissions and also add/remove them from a Role. When a Role model is updated an array of permissions is passed. So I added my try catch to check if PermissionDoesNotExist exception is thrown if the permissions[] contains an invalid permission. But instead of catching this exception I am getting :

    "message": "Call to undefined function There is no permission named `blogs.read` for guard `staff`.()",. 

This is my update method in the RolesController

`    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param School $school
     * @param Role $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, School $school, Role $role)
    {
        $validated = $request->validate(
            [
                'permissions' => 'array|required'
            ]
        );
        try {
            $role->givePermissionTo($validated);

            return response()->json([
                'data' => $role->toArray(),
                'status' => 'success',
            ], 200);
        } catch (\Spatie\Permission\Exceptions\PermissionDoesNotExist $e) {
            Log::error('Unable to add permissions', [
                'message' => $e->getMessage()(),
                'trace' => $e->getTraceAsString(),
            ]);

            return response()->json([
                'status' => 'Permission does not exist, please try again ',
            ], 400);
        }
    }`

So my question is how to handle giving a role unexisting permissions correctly?

**Comment by drbyte** [comment]
I suppose if you're passing an array of permissions but you don't know that those permissions exist yet, you have two choices:
- create those permissions before submitting the form (maybe when the user adds new permission names in the browser)
- loop through the array of permission names and call `findOrCreate` on each, passing the resulting permission model/s to the `givePermissionTo` method.
