### ISSUE TITLE
Defining super admin when using multiple guard

### ISSUE THREAD

**Issue by amanvision** [spatie/laravel-permission#1503]
Hello,

I have a multiple guard authentication like admin and users.

How can i define super admin for admin guard.

I'm using following but it is not working 
Gate::before(function ($user, $ability) {
       return $user->hasRole(Admin::ROLE_ADMIN) ? true : null;
       // Also trie
      // return auth('admin')->user()->hasRole(Admin::ROLE_ADMIN) ? true : null
});

**Comment by drbyte** [comment]
`hasRole` accepts 2 parameters:
- `$roles` can be a string name, integer number, or a specific Role object already associated with a specific `guard_name`
- `$guard` is an optional string to be used to check when `$role` is also a string. It is not needed if you pass a Role object for `$role`
https://github.com/spatie/laravel-permission/blob/782af0045cf95ae9eaf8d96b338349e1572a4cd2/src/Traits/HasRoles.php#L168-L175

So, if you pass a role object, or the id number of the Role record in the db as `$role` parameter to `hasRole` then it will relate to the specific `role_name`+`guard_name` of the Role in the db.

**Comment by amanvision** [comment]
Hello,
Thanks for reverting.

I tried passing the guard name in second parameters, but still the role does not have access to all roles.
And to be more specific.
I have created new guard name "admin" and have for this guard i have role name 'Admin'.
I would like to make any user with role 'Admin' be a super admin so it can bypass all permissions.

As per the documentation:
I'm using following code in AuthServiceProvider.php

```
Gate::before(function ($user, $ability) {
    return $user->hasRole(Admin::ROLE_ADMIN) ? true : null;
     // Also tried following:
     // return $user->hasRole(Admin::ROLE_ADMIN, 'admin') ? true : null;
     // return auth('admin')->user()->hasRole(Admin::ROLE_ADMIN) ? true : null;
     // return auth()->user()->hasRole(Admin::ROLE_ADMIN, 'admin') ? true : null
});
```
`dd(auth(config('auth.guard.admin'))->user()->hasAnyPermission($permission));`
The above statement returning false, even after defining super admin.

**Comment by amanvision** [comment]
Hi, 

I found that, Super Admin is working, It is returning true for all permission when using can method like below
`dd(auth('admin')->user()->can('users_edit'));`

But returning false when using hasAnyPermission()

**Comment by amanvision** [comment]
Hello,

Just saw your comment here https://github.com/spatie/laravel-permission/issues/1062#issuecomment-472953165

So now using can() for checking permission, to support array of permission in can, i have created a helper function

```
function can($permissions) 
{
    foreach($permissions as $permission) {
        if(auth(config('auth.guard.admin'))->user()->can($permission)) {
            return true;
        }
    }
    return false;
}
```

**Comment by drbyte** [comment]
Since Laravel's `auth()` helper lets you pass the guard to it, you can probably be more accurate with:
```diff
-        if(auth(config('auth.guard.admin'))->user()->can($permission)) {
+        if(auth('admin')->check() && auth('admin')->user()->can($permission)) {
```
