### ISSUE TITLE
$user->can not working

### ISSUE THREAD

**Issue by MathiasWeisheit** [spatie/laravel-permission#1504]
Hi, I have a problem with determining the permission with $user->can('...').
For example $user->can('view contacts') returns always false;
Hi, great work!
But I have a problem.
If I dump $user->getPermissionsViaRoles(); ,I will get a large result. See file 
![permissions_via_roles](https://user-images.githubusercontent.com/4928100/84880581-fb861580-b08c-11ea-8500-210c2fb96376.JPG)
I have also attached a database query from ther permissions table. 
![permissions_table](https://user-images.githubusercontent.com/4928100/84880618-0b9df500-b08d-11ea-9666-d9f9835d235e.JPG)

What can I do?

Also attached: userController , Seeder
[ProjectPolicy.txt](https://github.com/spatie/laravel-permission/files/4791527/ProjectPolicy.txt)
[PermissionTableSeeder.txt](https://github.com/spatie/laravel-permission/files/4791530/PermissionTableSeeder.txt)

[UserController.txt](https://github.com/spatie/laravel-permission/files/4791521/UserController.txt)

**Comment by MathiasWeisheit** [comment]
I changed the config from
```
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```
to 
```
    'guards' => [
        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
            'hash' => false,
        ],
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],
```
How can I check the guard of the logged-in user?

**Comment by drbyte** [comment]
> How can I check the guard of the logged-in user?

`dd(config('auth.defaults.guard'))` usually gives you the current guard of the logged-in user.

**Comment by christhofer** [comment]
Also has this problem in my unit tests.
Here's my test.

```
<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\WithFaker;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class RoleTest extends TestCase
{
    use WithFaker;

    public function testRole()
    {
        $roleName = 'assistant';
        $permissions = ['do this', 'do that', 'do nothing'];
        $this->createPermissions($permissions);

        $insertedRole = Role::create(['name' => $roleName]);
        $insertedRole->givePermissionTo($permissions);

        $user1 = $this->createUser()->assignRole($insertedRole);
        $user2 = $this->createUser()->assignRole($insertedRole);

        $this->assertTrue($user1->hasRole($roleName)); // success
        $this->assertTrue($user2->hasRole($roleName)); // success

        $this->assertTrue($user1->hasPermissionTo('do this', 'api')); //success
        $this->assertTrue($user1->hasPermissionTo('do that', 'api')); //success
        $this->assertTrue($user1->hasPermissionTo('do nothing', 'api')); //success

        $this->assertTrue($user2->hasPermissionTo('do this', 'api')); // success
        $this->assertTrue($user2->hasPermissionTo('do that', 'api')); // success
        $this->assertTrue($user2->hasPermissionTo('do nothing', 'api')); // success

        $this->assertTrue($user1->can('do this')); // fails
        $this->assertTrue($user1->can('do that')); // fails
        $this->assertTrue($user1->can('do nothing')); // fails

        $this->assertTrue($user2->can('do this')); // fails
        $this->assertTrue($user2->can('do that')); // fails
        $this->assertTrue($user2->can('do nothing')); // fails
    }

    private function createUser()
    {
        return User::create([
            'name' => $this->faker->name,
            'email' => $this->faker->email,
            'password' => bcrypt('password'),
        ]);
    }

    private function createPermissions(array $permissions)
    {
        $permissions = array_map(function ($permission) {
            return ['name' => $permission, 'guard_name' => 'api'];
        }, $permissions);
        Permission::insert($permissions);
    }
}
```

**Comment by drbyte** [comment]
`$user->can()` assumes the $user->guard_name property else the first guard listed in your auth config file, which is probably web. If all your routes are using `api` for the guard, then set `$guard_name` to `api`.  Otherwise, use `hasPermissionTo` instead of `can`.
https://docs.spatie.be/laravel-permission/v3/basic-usage/multiple-guards/

**Comment by christhofer** [comment]
@drbyte I've set the guard_name to api in function createPermissions down there. Where else should I define guard name for `$user->can()`?

**Comment by drbyte** [comment]
If your app is always only using `api` guard, then set it as the first in the config array so that all the non-specified lookups use it.

Else, if $user is an instance of \App\User then in \App\User set the $guard_name property to `api` if that's the guard you want to use whenever authorizing users of that model.

**Comment by 1giba** [comment]
Hi guys, look for this:

![image](https://user-images.githubusercontent.com/4941544/87427253-e383b200-c5b6-11ea-9bb3-7a273a9af46a.png)

And I got:

![image](https://user-images.githubusercontent.com/4941544/87427364-0dd56f80-c5b7-11ea-8095-9f99b1b8113a.png)

Is it a bug?

**Comment by 1giba** [comment]
Sorry guys. I made a mistake.

This is the correct way:

```php
        dd(
            app('auth')->user()->getAllPermissions()->toArray(),
            app('auth')->user()->can('permissions.read'),
            app('auth')->user()->hasPermissionTo('permissions.read')
        );
```

But the result is the same.

**Comment by 1giba** [comment]
I set the api guard as the first config and works.

Sorry by that.

**Comment by th3markas** [comment]
Can someone help me, I'm having the same problem. I am using Laravel 8 with Vue Js and Spatie 3. I've set my guard to 'api' at first place, all permissions and roles have guard name 'api, but I still can't access permissions via $user->permission. $user->roles works fine, $user->getAllPermissions() works fine too. But I can't use permission middleware and I can't access permissions via $user model, is there anything else I've missed or is it something to do with Laravel version?

**Comment by shan016** [comment]
@th3markas create config-- **permission.php**

`<?php

return [

    'models' => [

        /*
         * When using the "HasPermissions" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your permissions. Of course, it
         * is often just the "Permission" model but you may use whatever you like.
         *
         * The model you want to use as a Permission model needs to implement the
         * `Spatie\Permission\Contracts\Permission` contract.
         */

        'permission' => Spatie\Permission\Models\Permission::class,

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your roles. Of course, it
         * is often just the "Role" model but you may use whatever you like.
         *
         * The model you want to use as a Role model needs to implement the
         * `Spatie\Permission\Contracts\Role` contract.
         */

        'role' => Spatie\Permission\Models\Role::class,

    ],

    'table_names' => [

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * table should be used to retrieve your roles. We have chosen a basic
         * default value but you may easily change it to any table you like.
         */

        'roles' => 'roles',

        /*
         * When using the "HasPermissions" trait from this package, we need to know which
         * table should be used to retrieve your permissions. We have chosen a basic
         * default value but you may easily change it to any table you like.
         */

        'permissions' => 'permissions',

        /*
         * When using the "HasPermissions" trait from this package, we need to know which
         * table should be used to retrieve your models permissions. We have chosen a
         * basic default value but you may easily change it to any table you like.
         */

        'model_has_permissions' => 'model_has_permissions',

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * table should be used to retrieve your models roles. We have chosen a
         * basic default value but you may easily change it to any table you like.
         */

        'model_has_roles' => 'model_has_roles',

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * table should be used to retrieve your roles permissions. We have chosen a
         * basic default value but you may easily change it to any table you like.
         */

        'role_has_permissions' => 'role_has_permissions',
    ],

    'column_names' => [

        /*
         * Change this if you want to name the related model primary key other than
         * `model_id`.
         *
         * For example, this would be nice if your primary keys are all UUIDs. In
         * that case, name this `model_uuid`.
         */

        'model_morph_key' => 'model_id',
    ],

    /*
     * When set to true, the required permission names are added to the exception
     * message. This could be considered an information leak in some contexts, so
     * the default setting is false here for optimum safety.
     */

    'display_permission_in_exception' => false,

    /*
     * When set to true, the required role names are added to the exception
     * message. This could be considered an information leak in some contexts, so
     * the default setting is false here for optimum safety.
     */

    'display_role_in_exception' => false,

    /*
     * By default wildcard permission lookups are disabled.
     */

    'enable_wildcard_permission' => false,

    'cache' => [

        /*
         * By default all permissions are cached for 24 hours to speed up performance.
         * When permissions or roles are updated the cache is flushed automatically.
         */

        'expiration_time' => \DateInterval::createFromDateString('24 hours'),

        /*
         * The cache key used to store all permissions.
         */

        'key' => 'spatie.permission.cache',

        /*
         * When checking for a permission against a model by passing a Permission
         * instance to the check, this key determines what attribute on the
         * Permissions model is used to cache against.
         *
         * Ideally, this should match your preferred way of checking permissions, eg:
         * `$user->can('view-posts')` would be 'name'.
         */

        'model_key' => 'name',

        /*
         * You may optionally indicate a specific cache driver to use for permission and
         * role caching using any of the `store` drivers listed in the cache.php config
         * file. Using 'default' here means to use the `default` set in cache.php.
         */

        'store' => 'default',
    ],
];
`
finally clear cache
php artisan cache:clear

**Comment by pls-kick-me** [comment]
The same problem here. In my case I should clear cache after setting permissions:
```
app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();
```

**Comment by Haris-Technical-Solutions** [comment]
In my case this statement worked 

$user->hasPermissionTo('location.'.$location->id,"web")
