### ISSUE TITLE
Question about adding permissions.

### ISSUE THREAD

**Issue by DriedSponge** [spatie/laravel-permission#1506]
Is it possible to assign permissions to other models, not just the user model? If so, how would I go about doing it?

**Comment by drbyte** [comment]
Yes. Just add the traits.
Your models need to implement the `Authorizable` contract in order to use Laravel's `can` helper. (see the docs https://docs.spatie.be/laravel-permission/v3/prerequisites/ )
Use model policies to enforce controls for the models.

**Comment by DriedSponge** [comment]
Thank you!
