### ISSUE TITLE
'testspatie.role_user' doesn't exist 

### ISSUE THREAD

**Issue by tzriqat** [spatie/laravel-permission#1507]
Hi guys,
I'm recieving this error when trying to assign roles to a user
 Base table or view not found: 1146 Table 'testspatie.role_user' doesn't exist (SQL: delete from `role_user` where `user_id` = 18)

DD for user id is correct, and checkbox values are returning roles id are correct as well.
```
    public function roleAssignToUsers(Request $request)
    {
        $user = User::find($request->user_id);
        //dd($user);
        //dd($request->input('roles'));

        $inputroles = $request->input('roles');
        $user->syncRoles($inputroles);
        
        return view('cp.roles.index'));
    }
```

**Comment by drbyte** [comment]
It seems like you have other relations coded into your app and Laravel is self-determining a table-name for those relationships. 
In short: your app's code conflicts with (is overriding) method names and relations and models that this package provides.

**Comment by tzriqat** [comment]
Yes indeed. thanks @drbyte It is resolved now.

**Comment by anuragyantra** [comment]
@drbyte 
**I need urgent Help, How do you resolved this issue ?**

**Comment by anuragyantra** [comment]
@drbyte
Can you please share, how you resolved this issue ?

**Comment by danti96** [comment]
como resolvió este problema

**Comment by mohitbabel** [comment]
Same problem faced please tell how to resolve that problem

**Comment by drbyte** [comment]
https://spatie.be/docs/laravel-permission/v6/prerequisites#content-must-not-have-a-role-or-roles-property-nor-a-roles-method
