### ISSUE TITLE
intelephense says Spatie HasRoles Undefined type 

### ISSUE THREAD

**Issue by NattananWs** [spatie/laravel-permission#1508]
![ภาพ](https://user-images.githubusercontent.com/66249635/85202815-432dcb00-b333-11ea-8aed-833c39c07468.png)

**Comment by drbyte** [comment]
It seems either your intelliphense/VSCode is not in sync with composer, or the package is not yet installed therefore the trait is not recognized.

**Comment by NattananWs** [comment]
![ภาพ](https://user-images.githubusercontent.com/66249635/85204027-d79c2b80-b33b-11ea-91fc-a38785e98c26.png)
i use "composer update" and restart vscode ,now i think it's ok (maybe 5555) but now problem is i can't use assignRole()
![ภาพ](https://user-images.githubusercontent.com/66249635/85204087-28ac1f80-b33c-11ea-9d93-109b7069fa12.png)
what should i do??

**Comment by drbyte** [comment]
I'm not sure why you're using `auth()->user()->assignRole()`.

Normally calling `auth()->user()` is used when checking information, not when assigning information.

It would be better practice, and easier to debug, if you first retrieve the object (eg: `$user = User::first();`) and then do your role assignment (eg: `$user->assignRole('something');`)

**Comment by NasrinAfrozKakoli** [comment]
Restart VS code .

**Comment by akshayknz** [comment]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>, then enter Restart Window.

**Comment by GhassanMg** [comment]
press ctrl + shift + p, then type Restart Extension Host

**Comment by Hussains3** [comment]
> Restart VS code . (incase anyone comes here)

That is working in my case. Thanks. @NasrinAfrozKakoli

**Comment by AXUSLK** [comment]
> Ctrl+Shift+P, then enter Reload Window.

this works for me. thanks

**Comment by khanakia** [comment]
I am having the same issue `auth()->user()->hasRole('super_admin')`
<img width="671" alt="Screenshot 2022-08-06 at 4 46 32 PM" src="https://user-images.githubusercontent.com/2174170/183246551-afb5d6ff-360f-4e22-a91b-02c65ba6a1e3.png">

Does anybody has solution ?

**Comment by ahmedmansoor** [comment]
Same issue here. Restarting VS Code or updating the composer didn't resolve this issue for me.

**Comment by khanakia** [comment]
@ahmedmansoor Only way to make it work at the moment is to use `Auth::user()->hasRole('super_admin')` and generate IDE helper using this https://github.com/barryvdh/laravel-ide-helper

**Comment by AUSCENCE** [comment]
thank you @NasrinAfrozKakoli. that working now

**Comment by mrsnax** [comment]
> @ahmedmansoor Only way to make it work at the moment is to use `Auth::user()->hasRole('super_admin')` and generate IDE helper using this https://github.com/barryvdh/laravel-ide-helper

Hi 

I've still got errors when generating IDE Helper. How to fix it?

**Comment by ahmedmansoor** [comment]
> > @ahmedmansoor Only way to make it work at the moment is to use `Auth::user()->hasRole('super_admin')` and generate IDE helper using this https://github.com/barryvdh/laravel-ide-helper
> 
> Hi 
> 
> I've still got errors when generating IDE Helper. How to fix it?

No idea. Following the installation and usage instructions of the helper, and restarting VS Code afterwards worked for me.

**Comment by mazacmartin** [comment]
Hey,

```php
$user = User::find(Auth::user()->id);

if ($user->hasRole('admin')) {
    return 'admin';
} else {
    return 'no admin';
}
```

**Comment by cheznousdevgroup** [comment]
> Hé,
> 
> @mrsnaxessaye ça:
> 
> ```
> $user = User::find(Auth::user()->id);
> 
> if ($user->hasRole('admin')) {
>     return 'admin';
> } else {
>     return 'no admin';
> }
> ```

Thank you it works

**Comment by hvsharma63** [comment]
Adding a php doc block helps and solves the error

```php
/** @var \App\Models\User */
$user = auth()->user();
$isSuperAdmin = $user->hasRole(RoleEnum::SUPER_ADMIN)
```
