### ISSUE TITLE
I cant install the package

### ISSUE THREAD

**Issue by Elvino12** [spatie/laravel-permission#1509]
I'm trying to install the package on my laravel 6 project, with composer require spatie/laravel-permission, i get the follow error
Content-Length mismatch, received 229113 bytes out of the expected 298332, and it wont install, please any help,

**Comment by drbyte** [comment]
When I google search for the message you posted it brings back many articles showing that it's a configuration problem with your `composer` installation.

**Comment by Elvino12** [comment]
I already done the configuration of my composer file in home directory and from my composer on laravel, and i steal receiving the same error

**Comment by Elvino12** [comment]
after all, i was able to resolve this issues, was my memory_limit in php.in

Thanks for your help
