### ISSUE TITLE
Same url route, different Controllers

### ISSUE THREAD

**Issue by pmercadocl** [spatie/laravel-permission#1510]
Hi, I'm looking for something like this:

```
Route::middleware(['role:customer'])->namespace('Customers')->group(function() {
        Route::prefix('orders')->group(function() {
            Route::get('/', 'OrdersController@index');
            Route::get('watch/{id}', 'OrdersController@watch');
        });
});

Route::middleware(['role:operator'])->namespace('Operators')->group(function() {
        Route::prefix('orders')->group(function() {
            Route::get('/', 'OrdersController@index');
            Route::get('watch/{id}', 'OrdersController@watch');
            Route::get(.....
        });
});
```
- Roles works as expected.
- Define 'Customers' and 'Operators' namespace.
- Under each namespace there is same business logic concept but treated different for each role.
- Those concepts are accessed with the same url.
Currently routing functionality is evaluated first because always "operator" role can access to "watch/..." path, but "customer" role can't, seems Laravel Routing use last defined routing rule.

What I want to know if library can evaluate which role is in session first and after that start laravel routing logic.

**Comment by redidizzy** [comment]
I personally would've taken a different approach, I always avoid having one route path linked to two different controllers...
In other words, there would be two OrdersController in each namespace but only one, then inside the controller's logic, i would check for the role of concerned user, then call a service/repository depending on that role(and on what you wish to do)
Your routes would look something like that

```
  Route::middleware(['role:operator|customer'])>group(function() {
        Route::prefix('orders')->group(function() {
            Route::get('/', 'OrdersController@index');
            Route::get('watch/{id}', 'OrdersController@watch');
            Route::get(.....
        });
      });

```
And you controller(watch method for instance) would look something like that

```
<?php
namespace <your_namespace>
use App\Services\OrderService;

class OrderController extends Controller{
  .
  .
  .
  public function watch(Order $order){
    $concernedUser = auth()->user();

    if($concernedUser->hasRole('customer'){
      $result = OrderService::watchCustomer($order);
    }else if($concernedUser->hasRole('operator){
      $result = OrderService::watchOperator($order);
    }

    //return response
  }
}

```
Then, all you have to do is write the service's logic.
Hope that helped
