### ISSUE TITLE
Default guardName resolution logic conflict with LDAPRecord/Laravel package

### ISSUE THREAD

**Issue by rognales** [spatie/laravel-permission#1511]
Hi There

I'm using this package along side with DirectoryTree/LdapRecord-Laravel.

However, the logic to determine the current guard is filtering the the custom guard introduced by DirectoryTree/LdapRecord-Laravel package.

Here's the working ````auth.php```` with that package

````php
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\User::class,
    ],

    'ldap' => [
        'driver' => 'ldap',
        'model' => App\Ldap\User::class,
        'rules' => [],
        'database' => [
            'model' => App\User::class,
            'sync_passwords' => true,
            'sync_attributes' => [
                'name' => 'displayname',
                'email' => 'mail',
                'uid' => 'uid',
            ],
        ],
    ],
],
````
However, your logic to determine the default guard in [Guard:::getNames()](https://github.com/spatie/laravel-permission/blob/782af0045cf95ae9eaf8d96b338349e1572a4cd2/src/Guard.php#L44) is filtering records that is not having the same model instance.

> ````App\User```` vs ````App\Ldap\User````

I have to explicitly mentioned the guard name. The @can helper also returns ````false``` which i believe have the same effect.
````php
// this works
return $user->hasPermissionTo('customer:create', config('auth.defaults.guard'));
// this does not
return $user->can('customer:create');
````

Any idea on how to proceed?

**Comment by drbyte** [comment]
Does your app actually need to control permissions separately for separate guards? Or do all your roles/permissions apply equally to all guards?

**Comment by rognales** [comment]
1.  Nope. All permissions control are the same for all guards
2.  I don't think the PR would solve the issue

Anyway, I managed to resolved this by setting the `````$model->guardName()````` to use ````config()```` helper and still have the flexibility.

**Comment by drbyte** [comment]
> * Nope. All permissions control are the same for all guards

You might consider the suggestions in this discussion if your app's permissions are actually guard-agnostic: https://github.com/spatie/laravel-permission/issues/1156

**Comment by dwain-lab** [comment]
@rognales I have a project where I want to use LDAP Records to sync with a database and then use the spatie permissions for authorization.  I wanted to know if you experience any issues implementing both?  Please let me know thanks.

**Comment by rognales** [comment]
@dwain-lab it works perfectly. both packages are working in harmony.

**Comment by leecheromerevilit** [comment]
> @dwain-lab it works perfectly. both packages are working in harmony.

Hi @rognales were you able to use withCount on your LdapRecord and Spatie Permission?

**Comment by rognales** [comment]
@leecheromerevilit my use case does not requires withCount. My primary usage of this library are for authentication, user import and record assignment.
