### ISSUE TITLE
Special Deny

### ISSUE THREAD

**Issue by philipnjuguna66** [spatie/laravel-permission#1513]
This is not an issue per se, but I was wondering how can I add a special deny permission to the user whose role has access to the permission.
Example: A group with the role of Manager, but you you want to deny one Manager from accessing a financial report. How can I go about that?

Thank You

**Comment by drbyte** [comment]
This package is "additive only" when it comes to granting roles/permissions. It doesn't "take away" anything once it's been granted.

Some options you could explore:
- split the role into smaller roles, where one of those other roles is related to that report, and re-assign roles to everyone accordingly
- don't grant the role in the first place; instead grant only certain other permissions
- grant it, but then in your code where you control access to that report hard-code something specific about that particular user ($user->`hasPermissionTo('run report') && $user->id != 33`)
- grant it, but create a specific Permission name that you use to enforce the denial (`hasPermissionTo && hasPermissionTo('is denied access to the report')`)
- explore registering a `Gate::after()` rule to do the denial ... either by user or the specific permission name
- if this is a big enough issue that you need `deny` features regularly, look at https://github.com/JosephSilber/bouncer
