### ISSUE TITLE
Duplicating Users and Permissions For Each Guard???

### ISSUE THREAD

**Issue by nikklass** [spatie/laravel-permission#1514]
Hi,
I wanted to migrate from Laratrust to Laravel Permission. 

I already have a running app with permissions(about 300) and users (about 30,000).

I read through your docs and I got a disclaimer that for me to use this package, I have to specify guard name for each permission and for each user that is created? This sounds weird for me.

So if I have two guards web and api, that means my users table will have to double to 60,000? and permissions to 600?  And if i add more guards later? Will it also increase exponentially?

I would like to use my existing setup without headache of duplicating records and future maintenance of the same records.

Please elaborate further if this is the case.

Thanks.

**Comment by drbyte** [comment]
Are your permissions actually "specific" to each guard? Or are they actually guard-agnostic? If guard-agnostic, then a small change may be enough: https://github.com/spatie/laravel-permission/issues/1156

Alternatively, if you're not actually using both `web` and `api` guards, then delete the unused one from your config until such time as you need something more.

**Comment by nikklass** [comment]
No. My permissions are not specific to each guard. I use the same permissions for both api and web guards. I use the web guard for my web site which uses sessions. And the 'api' guard for my android app and ussd  which use tokens.  So for my case, I need both guards.

**Comment by drbyte** [comment]
In that case the #1156 discussion is pertinent. You could make the suggested code changes in your app or you could just be explicit about always checking against `web` guard anytime you're checking for roles/permissions (instead of the package trying to match up against the guard the user is actually using)

**Comment by nikklass** [comment]
Thanks @drbyte . This looks like a nice workaround. Will give it a shot. Cheers.
