### ISSUE TITLE
Multiple guards are independent from the Auth::guard() which is used for login?

### ISSUE THREAD

**Issue by thoresuenert** [spatie/laravel-permission#1515]
I wrap my head around the multiple guard usage and I am confused.
I thought initially I have to duplicate all permissions for both guards, but as long as I use the Same Model for a Guard it doesn't matter.

When I have the base setup with multiple guards as follows:

```php
// config/auth.php
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```

```php
// App\User
class user extends Authenticated
{
  public $guard_name = 'web';
}
```

This package don't care which guard I used to login.
In this scenario the `web` guard is used for roles and permissions in both scenarios:

- logged in by api guard
- logged in by web guard

Am I right?

PS: that's feels a bit odd :D we use this package several years.

**Comment by drbyte** [comment]
Would the merge of #1384 solve your confusion? Would merging it break anything in your application?

**Comment by thoresuenert** [comment]
@drbyte I would argue that all of the automatism and magic does more harm than good.

Especially in the testing department:
We spend way to much time to work around all those guard issues.
Let me organise my permission and roles and give me full control.

In the #1384 the auth check is way to deep in the application code for my taste.
It would be enough to pass the logged in guard to the `checkPermissionTo` function at define time:

https://github.com/spatie/laravel-permission/blob/782af0045cf95ae9eaf8d96b338349e1572a4cd2/src/PermissionRegistrar.php#L88-L92

right now it would break my application because we had a bad understanding of the guard name.
We hardcoded everything to 'api' to work around error messages in tests, because we thought the gaurd_name is bound to the logged in guard etc.
