### ISSUE TITLE
Two laravel project using spatie paackage but database is same both projects is it possible because i have issue?

### ISSUE THREAD

**Issue by syedhassan25** [spatie/laravel-permission#1517]
hello hi guys laravel spatie package role base permission is very owsum but i am using in my project to different laravel projects
using database in both project single database but its not working problem is i am assign permission to user in first project its working fine ... but its user using in second project permissions not working... i see problem is ... please tell me what we do i am stuck in my both project have you any idea pleaase suggest me.
problem conclusion

assign permission to user first project is woking in same project...
but this user is not wrokign in second prject... but if you can assign user to permisssion in second he is working fine in second project but dosent work in first project please help me and sorry for poor englihs

NOte: please tell me is it possible single database using in laravel multiple project with laravel spatie role and permission

**Comment by drbyte** [comment]
> please tell me is it possible single database using in laravel multiple project with laravel spatie role and permission

Single-database multi-tenancy is possible when adding a tenant id to the necessary tables and using scopes to filter results based on tenant. Sometimes this also involves extending the models and overriding some trait methods. 

There are many multi-tenancy Laravel packages and articles online explaining single-database multitenancy in Laravel. Some specifically mention/discuss working with this permissions package.

**Comment by Khalad-shykh** [comment]
Two laravel project using spatie paackage but database is same both projects is it good to use like or not ?
