### ISSUE TITLE
Question : Super-admin AuthServiceProvider override not working for route middleware

### ISSUE THREAD

**Issue by TheFrankman** [spatie/laravel-permission#1518]
Hello There,

I'm trying to create a super-admin that bypasses all permissions but the suggested edit in your documentation to the AuthServiceProvider does not seem to take affect for the route middleware. I have 3 roles: super-admin, admin, and standard. In the below example I have a route, with a middleware of `role:admin` if i change to `role:super-admin|admin` then both super-admins and admins have access to the route, without it, my super-admin gets a 403.

Am i missing something here ? 

AuthServiceProvider

```
public function boot()
{
        Gate::before(function ($user, $ability) {

            return $user->hasRole('super-admin') ? true : null;
        });

        Gate::after(function ($user, $ability) {
            return $user->hasRole('super-admin'); // note this returns boolean
        });

```

Web.php

```
// Admin Routes
Route::group(['prefix' => 'admin', 'middleware' => ['role:admin']], function () {
    Route::get('', 'Admin\AdminController@index')->name('admin dashboard');
});
```

My user with super-admin role gets a 404 trying to access the admin

**Comment by drbyte** [comment]
This is by design.
Gate::before/after will respond to the `can()` helpers, `authorize()` calls, and model policy methods that leverage Laravel's Authorization features.

The `role` middleware isn't checking for any permissions or `can()` checks.

In the cases where I want my routes to be filtered through the `role` middleware, I'll add the `|Super-Admin` role to the list of other roles, as you mentioned.

**Comment by TheFrankman** [comment]
Ok, so sounds like i'm best off creating my own middleware that checks the combination of `admin|super-admin` instead. Thanks

**Comment by drbyte** [comment]
> Ok, so sounds like i'm best off creating my own middleware that checks the combination of `admin|super-admin` instead.

You might find that cloning the `role` middleware to add additional logic may be the easiest route, whether you use it as its own named middleware (maybe register it as `admins`?) or use it to replace the `role` middleware.
