### ISSUE TITLE
I want to offer extending functionality for this module.

### ISSUE THREAD

**Issue by nesh-ua** [spatie/laravel-permission#1520]
I think will be useful to have ability to add permissions and roles for some object. This is example:
tables:
projects
project_tickets

Permissions for project:
- projects.view
- projects.create
- projects.view
- projects.update
- projects.delete

Permissions for project tickets:
- projects.tickets.view
- projects.tickets.create
- projects.tickets.get
- projects.tickets.update
- projects.tickets.delete

Explanation: 
if I want to create some permissions for some project i have to fill model_type and model_id (we need to add this fields) in permissions table. When these fields are null - this is global permission.
Also if i want to add some groups for some project i have to fill model_type and model_id (we need to add this fields) in role table. When these fields are null - this is global group)

This means that we can create global permissions and groups, and also we can create permissions and groups for some object. I think Jira has similar permission system.

**Comment by drbyte** [comment]
Yes, you can do this sort of thing in your application.

**Comment by nesh-ua** [comment]
Do you mean that i can make this via extending models?
https://docs.spatie.be/laravel-permission/v3/advanced-usage/extending/
