### ISSUE TITLE
Documentation teach a bad-practice for super admin

### ISSUE THREAD

**Issue by paullaffitte** [spatie/laravel-permission#1522]
The [super admin documentation](https://docs.spatie.be/laravel-permission/v3/basic-usage/super-admin/) give the advice to add a `Gate::before` callback to handle the super admin role. But instead of following the [recommandation from Jeffrey Way](https://laracasts.com/series/laravel-6-from-scratch/episodes/51) stating that you should always wrap the `return` inside a `if`, it instantly returns a boolean, which cause the update method to never be called.

Actually it's quite fine, since the example returns a `null` value, but it could be misleading.

**Comment by drbyte** [comment]
The example in the documentation is correct. 

It combines the `if` using a PHP `ternary`:

```php
    return $user->hasRole('Super Admin') ? true : null;
```
