### ISSUE TITLE
hasAnyRoles or hasPermissionTo not working on constructor in a controller

### ISSUE THREAD

**Issue by safjammed** [spatie/laravel-permission#1524]
Here's My code that i want to run
```
public function __construct()
    {
        if (Auth::user()->hasAnyPermission(["Read Reports"])){
            $this->permitted = true;
        }
    }
```
But it is giving me this error:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function hasAnyPermission() on null in app/Http/Controllers/Admin/ReportController.php on line 18
```

Is there any workaround for this? I really need this to work.

**Comment by safjammed** [comment]
Found the workaround. It wasn't laravel-permission's fault... here's how you'll get the same results:
```
public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $user = \auth()->user();
            if ($user->hasAnyPermission(["Read Reports"])){
                $this->permitted = true;
            }
            return $next($request);
        });
    }
```
Its a bit messy but it works perfectly. You can also try making a specific middleware that will do the trick

**Comment by drbyte** [comment]
You could also use the package's `permission` middleware:

```php
public function __construct()
{
    $this->middleware(['permission:Read Reports']);
}
```

Ref: https://docs.spatie.be/laravel-permission/v3/basic-usage/middleware/

**Comment by safjammed** [comment]
@drbyte that wont work on my thing. Because i need to change a attribute of my class though this middleware.  this line:
```
$this->permitted = true;
```
I have already got a hack for that. If you need it, you could just use it
