### ISSUE TITLE
How to assign default role to User when they register?

### ISSUE THREAD

**Issue by MalteKiefer** [spatie/laravel-permission#1527]
Hello,

I have created a role "customer".
Is it possible to say, that every user that register himself automatically get the role "customer"?

Thanks

**Comment by drbyte** [comment]
There are a few options that Laravel provides:

When registering, the Laravel creates the user, then fires a Registered event, then logs them in, and then calls a registered() method if one exists.

If you need the role assigned before it logs them in then choose one of these:

- in your [`RegisterController` in the `create()` method](https://github.com/laravel/ui/blob/da9350533d0da60d5dc42fb7de9c561c72129bba/stubs/Auth/RegisterController.stub#L59-L72) you could add a line to make the assignment

- or you could register an event listener for [when `Illuminate\Auth\Events\Registered` is fired](https://github.com/laravel/ui/blob/da9350533d0da60d5dc42fb7de9c561c72129bba/auth-backend/RegistersUsers.php#L34)

If you want to assign it after they are logged in by the controller:

- you could override (copy the method into your own controller) the trait method for [`registered()`](https://github.com/laravel/ui/blob/da9350533d0da60d5dc42fb7de9c561c72129bba/auth-backend/RegistersUsers.php#L57-L67) and do the assignment there
