### ISSUE TITLE
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

### ISSUE THREAD

**Issue by fajar7xx** [spatie/laravel-permission#1530]
when i install this package. it shows a warning. 
before i installed it. i have installed laravel telescope

**Comment by drbyte** [comment]
This package doesn't require `moontoast/math`.

If you run `composer why moontoast/math` you'll see that it's a Telescope dependency. 
Over in the Telescope repo it looks like they have plans to change it after v3: https://github.com/laravel/telescope/issues/883

**Comment by fajar7xx** [comment]
thank for your info. it means my telescope conflict with it
