### ISSUE TITLE
Applying unique permissions per user

### ISSUE THREAD

**Issue by kristianharmer** [spatie/laravel-permission#1532]
Hi,

I am wondering if I am able to use this package with the requirements that I have.

Having created roles and associated default permissions to each role; I now have a requirement to toggle these permissions on and off for each user (of each role).

In a lot of cases, the default permissions for that role will be fine.

However, there are a few circumstances where I would need to toggle of a specific permission for a particular user.

For example, a generic 'user' role may have the ability to 'delete content'. But in some cases, we might turn that specific permission off for certain users!

That being the case, the typical "$user->can('delete content');" function would not work since it is only checking against permissions relevant to the users role and not their specific permissions on top of that!

Or am I missing something!?

Thanks,
Kris...

**Comment by drbyte** [comment]
This package doesn't offer "subtraction of permissions already granted".

However, one way around that is to create a new permission named `cannot delete content` (for example).
Then in your app write some specific code that checks for whether the user has been assigned that specific prohibition "permission", and act accordingly.

**Comment by kristianharmer** [comment]
Thanks for coming back to me so quickly.

So I could simply add prohibitions to a new column of the user table (or a new pivot table) and cross reference this when performing a "$user->can('delete content');"...!

That might work, actually. Although I have no experience of using such functions as "$user->can('delete content');", I am assuming I can use that as one arg and my custom check for prohibition as a second arg!

Does my logic seem sound to you?

Thanks for that...

**Comment by drbyte** [comment]
Yes, I was thinking something like:

```php
if ($user->can('delete content') && $user->cannot('cannot delete content')) {
  // process deletion here
}
```

I suppose you could also write the second part this way:
```diff
- ... && $user->cannot(
+ ... && !$user->can(
```
... depending on your style preference.

**Comment by kristianharmer** [comment]
OK, so I basically use seeders to create permissions and then roles and then associate permissions to each role.

I then assign users to a role (which assumes related permissions). I also assign related permissions for the users role, directly to each user and therefor can revoked (remove) permissions from the 'model_has_permisisons' table for each user where needed.

This is great!

However, I noticed that when I add to my controller methods [example my index method] '$this->authorize('view unit types', Unittype::class);' it ignores the users individual permissions and assumes those related to the role itself!

It is as if the check I am using is checking the permission against the users role and not the permission against the user itself!

What am I doing wrong?

Thanks again...

**Comment by kristianharmer** [comment]
Oddly, if I use : $user->hasPermissionTo('view unit types')
...it also appears to check permissions related to the users role and not the users permissions from the 'model_has_permisisons' table.

But if I dd($user->permissions); I can clearly see that user does not have this specific permission!

So, am I misunderstanding the use of hasPermissionTo() and it actually checks permissions against the role and not the user directly?

Do I need to add the ability to check a users permission myself?

Thanks,
Kris...

**Comment by drbyte** [comment]
It sounds like you're assigning the SAME permissions to both the role AND the user?
That's definitely going to cause you confusion. In most cases I'd even consider that an anti-pattern.

That said, if you wish to continue in that direction, there's a method `->hasDirectPermissionTo()` which you could use to check permissions assigned directly to the user regardless of what they're granted by the roles they've been assigned.

**Comment by kristianharmer** [comment]
Oh, I wasn't aware of that one: hasDirectPermissionTo()

However,  get a "Call to undefined method App\User::hasDirectPermissionTo()" error when trying to use it!

**Comment by drbyte** [comment]
> Oh, I wasn't aware of that one: hasDirectPermissionTo()
> 
> However, get a "Call to undefined method App\User::hasDirectPermissionTo()" error when trying to use it!
> 
> Can't see it in the package source code either

Apologies. Typo.  `hasDirectPermission()`

https://github.com/spatie/laravel-permission/blob/b005ab34b0d4c566cfd868781a81bef19b848524/src/Traits/HasPermissions.php#L261-L269

**Comment by kristianharmer** [comment]
OK, I see it.

Actually, that would be perfect, but it returns a false (when I expected it to) but not a 403, unfortunately. 

Is that by design, since other Spatie permission methods will throw a 403 when false?

Thanks again for your help...

**Comment by drbyte** [comment]
I'm not sure about the 403s you're talking about. Maybe they're coming from exceptions it throws in certain cases?

But you could always throw your own using Laravel's [`abort_unless` (or its sister) function/s](https://laravel.com/docs/master/helpers#method-abort):

`abort_unless($user->hasDirectPermission('foo'), 403, 'Sorry, not authorized')`

**Comment by drbyte** [comment]
Glad you've found a solution to your needs!
