### ISSUE TITLE
We need Authority column inside Roles table.

### ISSUE THREAD

**Issue by Mahmoud-Italy** [spatie/laravel-permission#1539]
Which's mean by example,
I've role name Author and i wanna make this role view his posts only, Then i'll give him authority = false
On other hand, I've another role name Editor, and i wanna let him views all posts even doesn't belong to him then authority = true

We can handle this situation with new boolean column name authority inside roles table.
Just new idea i'v thought while i using this package, i would love to let you know if u wanna added in new update

**Comment by drbyte** [comment]
Thanks for your suggestion.

We are not planning to add more columns to the Roles table. You are free to do that inside your own app if you really need it.

But with what you describe, it seems that you may not need it for your situation:
You can use Laravel Model Policies for handling authority rules which combine a role and something about the model.
https://docs.spatie.be/laravel-permission/v3/best-practices/using-policies/

**Comment by Mahmoud-Italy** [comment]
Thanks will do.
