### ISSUE TITLE
Email Verification stops After implements HasRole

### ISSUE THREAD

**Issue by magnokf** [spatie/laravel-permission#1553]
Please help me to find a way to fix it. Thx
In a Simple install
Laravel 7 --auth with MustVerfyEmail , after implements 
spatie/laravel-permission

Email Verification stops and user logs in automatilly

**Comment by drbyte** [comment]
Can you clarify more? 

What exactly "stops" it?  Is it just adding the `HasRoles` trait? or is it something else?

I'm unable to replicate the problem. Can you share a repository where your code can be seen?
