### ISSUE TITLE
$user->getPermissionsViaRoles() does not always return permissions 

### ISSUE THREAD

**Issue by briavers** [spatie/laravel-permission#1555]
For some reason 
```
@dump($user->getPermissionsViaRoles()->pluck('name'))
```
Returns an empty array but when I write 

```
@dump($user->roles->first()->permissions)
@dump($user->getPermissionsViaRoles()->pluck('name'))
```

I do get the expected array. Am I doing something wrong regarding lazy loading?

Running  laravel 7.25  with spatie/laravel-permission 3.16

**Comment by listermatrix** [comment]
i get the same issue.... where permssions seem to be revoked, but when i assign the roles again then it seems to be working now

**Comment by drbyte** [comment]
Can you show a demo app (pushed to a new github repo) with a fresh install of Laravel, without any other packages if possible, which contains only the code necessary to reproduce this symptom? The key is to isolate things so nothing else is interfering, and to be able to consistently recreate the problem. Even better if it can be demonstrated with tests.
