### ISSUE TITLE
A way to disable caching during development

### ISSUE THREAD

**Issue by lindo-llc** [spatie/laravel-permission#1558]
Right now I am working around the caching process, using the configuration below.
` 'expiration_time' => \DateInterval::createFromDateString('1 second'),`

Would be much cleaner if there would be an option to disable the cache, or if the system would use Laravel`s environment to decide if it needs to use cache or not.

**Comment by drbyte** [comment]
> if the system would use Laravel`s environment to decide if it needs to use cache or not

It already does: 
If your `.env` has `CACHE_DRIVER` set to `array` then that effectively disables caching, at least between requests.

This is the same as Laravel does for tests in the default `phpunit.xml`:
`        <server name="CACHE_DRIVER" value="array"/>`

**Comment by drbyte** [comment]
A note to this effect has been added to the docs.

**Comment by drbyte** [comment]
And ... I completely forgot that the `permission.php` config has a `cache.store` option which you could set to `array` to have this package use that for its caching operations. That would effectively disable the cache between requests, but not touch any other Laravel cache operations.
