### ISSUE TITLE
Not working with mongo DB and laravel 7.2

### ISSUE THREAD

**Issue by jacksfero** [spatie/laravel-permission#1559]
please help us how to use with mongo db
Error
Call to a member function compileColumnListing() on null

**Comment by drbyte** [comment]
This package doesn't provide official support for Mongo DB. But, it's just doing normal Laravel Eloquent calls.
Perhaps the problem you're encountering is in your Mongo DB driver implementation?

**Comment by jacksfero** [comment]
yes i have installed mongo DB driver, if i will use mongo db drivers then spatie functions will be work as like mysql db. please confirm

**Comment by mostafamaklad** [comment]
First, you have to install the [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) but it is, unfortunately, it is not supporting Laravel 7.x
