### ISSUE TITLE
Return first role

### ISSUE THREAD

**Issue by thiagoferreirape** [spatie/laravel-permission#1564]
hi guys , look , i'm with the spatie working amazing , but i 'm with a little problem to undestand what is happing here , look .

i have a file called 'HomeController' , inside i have a function called 'ControllerTest' , that have the follow code .

`       $user = auth()->user();
        $roles = $user->getRoleNames();
        return $roles;`

this return me '["User"] , that is correct .

but when i do the same logical on my file called 'MenuModel' and a function called 'child' , doing this :

    ` $user = auth()->user();
      $roles = $user->getRoleNames();
      $menu_child= MenuRoles::where('role',$roles)->pluck('menu_id');
      return $this->hasMany('App\Models\Menu','parent_id')->whereIn('id',$menu_child)->orderBy('name');`

this ever return me the first role , that is 'administrator' but must be 'user' because the $roles is 'User' , if i go into the database and change manually the role 'administrator' to 'administrator2' , the code above return me 'administrador2' , ever return the first element.

the funny is , work on controller , but on model is returning the first element .

**Comment by drbyte** [comment]
It seems like perhaps this is retrieving for the wrong user?
Or some unexpected data is being retrieved between the lines of code you've quoted. Sometimes it's best to `dd()` various values between lines to understand what's actually happening in your application's code.

Often it is helpful to create a simple new Laravel app, with only the least amount of code required to recreate the problem - preferably without any additional packages installed. The re-building of the code in the test app usually helps reveal what's wrong. Or clearly exposes where a bug exists. Once that information is clear then it's easier to fix.
