### ISSUE TITLE
Unable to access authenticated User's Roles and Permissions in global scope

### ISSUE THREAD

**Issue by sanghviyash** [spatie/laravel-permission#1566]
I am trying to access User's Roles in one of the Eloquent Models booted method to have restrictions based on User Role.
While fetching authenticated user, the user details from the Users table are available.
But when trying to fetch the Roles or Permissions, all possible values of Roles and Permissions are returned instead of the ones assigned to User.

Following is my anonymous global scope.

```
    protected static function booted()
    {
        if (auth()->check() && auth()->hasUser()) {

            // check for Admin and India Manager roles and don't add any restrictions
            if (!auth()->user()->hasAnyRole('developer|admin|india_manager1|india_manager2|tech_expert')) {
                // fetch all the configurations created by the user
                static::addGlobalScope('created_by_user', function (Builder $builder) {
                    $builder->where('created_by', auth()->user()->id);
                });

                // check if users are executives then restrict till other executives only
                if (auth()->user()->hasAnyRole('regional_manager1|regional_manager2|regional_manager3')) {
                    static::addGlobalScope('belongs_to_executives_only', function (Builder $builder) {
                        $executive_user_ids = User::role(['tech_executive', 'sales_executive'])->pluck('id');
                        $builder->whereIn('created_by', $executive_user_ids);
                    });
                }
            }
        }
    }
```
Took me days to figure this out, **please help** me solve this.

I am using 
Laravel: v8 (had issue on v7 as well, then updated)
Spatie: v3.16

Let me know if more details are required.

**Comment by drbyte** [comment]
Yes, `User::role(['tech_executive', 'sales_executive'])->pluck('id');` on  its own in a place like a controller will report only the user ids for Users with the named roles.
I don't think I've ever tried that in an anonymous global scope declaration like yours. But I'm puzzled as to why it would behave any differently there, unless you've got other overriding scopes, such as a `role()` method on your User model that's replacing what this package provides in its trait.

While this may or may not be helpful, is there any value in splitting both of those anonymous declarations into named scope classes which give you slightly more isolated control over things? 
Related, somewhat:
https://github.com/laravel/framework/issues/22316
https://stackoverflow.com/questions/47665819/model-filters-based-on-the-currently-authenticated-user
https://laracasts.com/discuss/channels/laravel/global-scope-for-user-model

Have you tried creating a new basic laravel app with "just this" functionality, and nothing more, for troubleshooting? Doing this sort of re-creation of things usually exposes where there's a problem in your application code.

**Comment by sanghviyash** [comment]
Thanks, @drbyte I understand I missed to mention some things in my original question.
_This is the only model where I am using the scope in my entire project._

Issue [#22316](laravel/framework#22316) suggests adding static global scopes on the Model itself OR add the logic in the apply method of the named scope which is what I have already done. 

Also, the scope works exceptionally well everywhere, except for just one place.
The only difference I found and I think because of which it doesn't work as expected is where I am eager loading the scoped Model. If I query the scoped Model directly it is working as expected.

**Comment by sanghviyash** [comment]
Update.

After writing the above comment it struck me where the actual problem lied and I tried to **lazy load** the scoped model instead of eager loading and everything worked fine.
But of course, performance is hit because of it.

Will add this on Laravel framework repo and try to understand the sequence of execution. I guess that should help me better understand the problem and have an even better solution to this problem.

Thanks @drbyte for your comment and lead me to exact cause of the problem.
Since this is not exactly related to this library I will close this issue.
