### ISSUE TITLE
Docs issue - UuidTrait can't work

### ISSUE THREAD

**Issue by fletch3555** [spatie/laravel-permission#1567]
The [UUID documentation page](https://spatie.be/docs/laravel-permission/v3/advanced-usage/uuid#models) suggests creating a trait to define common values needed for UUID primary keys.

Unfortunately, the trait shown can't possibly work.  Laravel's default value for the $incrementing property is true, while the trait defines it as false.   Per the [PHP docs on trait property conflict resolution](https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.interfaces.examples.ex1), this behavior simply isn't supported, and running it proves this.  I get the following error output when attempting to seed a user object:
```
  Whoops\Exception\ErrorException

  Illuminate\Database\Eloquent\Model and App\Traits\HasUuidKey define the same property ($incrementing) in the composition of App\Models\User. However, the definition differs and is considered incompatible. Class was composed
```

**Comment by fredchantp** [comment]
change 
public $incrementing = false;
to
protected $incrementing = false;

**Comment by drbyte** [comment]
Interesting. Back in April 2020 on Laravel 7 and PHP 7.2 it worked without triggering that error. (I do read that the doc you posted mentions 7.0, so I'm puzzled too.)

Question: `true` and `false` are both boolean. Why is it telling you yours is of a different type?

There's an alternative though: Use an override method instead:

```php
    public function getIncrementing()
    {
        return false;
    }
```

While I haven't used them myself, there are many uuid packages for Laravel:
https://github.com/JamesHemery/laravel-uuid
https://github.com/jamesmills/eloquent-uuid
https://github.com/goldspecdigital/laravel-eloquent-uuid
https://github.com/michaeldyrynda/laravel-model-uuid

**Comment by drbyte** [comment]
The trait in the documentation example has been updated to override the method instead of the property.

**Comment by fletch3555** [comment]
The PHP docs mentioning 7.0 that you referred to is talking about the SAME value being allowed as of 7.0.  DIFFERENT values (i.e. laravel's default of `true`, and this trait's value of `false` has always resulted in a fatal error (at least according to the docs).

Definitely good call on the method.  I hadn't thought of that.  `$keyType` has the same issue, but looks like there's a `getKeyType()` method as well.

I'd rather not add a package for something so simple.

Thanks for the quick reply and docs update @drbyte!

**Comment by drbyte** [comment]
Ya I agree: a trait is better than a complete package, if possible.

(In the docs update I replaced both properties with override methods.)

Do take a look at the JamesHemery trait: he adds another internal property for checking whether the uuid has been updated. I suppose in some cases such an override might be beneficial, although I wonder if it should apply to a different event.

**Comment by fletch3555** [comment]
Okay cool, just wanted to make sure you didn't get caught with tunnel vision haha

The JamesHemery one was the one that seemed simplest.  I did notice the extra check for uuid modification.  Something I hadn't considered (I'm not in the habit of manually setting IDs), but I agree, could be a beneficial safety net.

Thanks again!
