### ISSUE TITLE
Question: Query on information_schema, is this normal? 

### ISSUE THREAD

**Issue by getupkid** [spatie/laravel-permission#1569]
Hello,
Just a quick question.

I installed the latest version of the package v3, and when I use @can in my blade template I noticed that there is a query that gets run which I have never seen before with this package:
`select column_name as column_name from information_schema.columns where table_schema = 'network' and table_name = 'permissions'`

Is this something new? Just want to make sure I haven't stuffed up any configuration.

Cheers.

**Comment by drbyte** [comment]
While this package does not intentionally directly run that query, it appears that underlying application code (or Laravel itself, including whatever database driver is in use) is querying the table structure for your `'network'` database.

**Comment by getupkid** [comment]
Thanks @drbyte for your quick reply and for the clarification. That's very interesting. This happens from a fresh new install of Laravel 8 and this package. I'll have to do some more digging.

Thanks again.

**Comment by drbyte** [comment]
I wonder if it's a side-effect of Laravel's bugfix https://blog.laravel.com/security-release-laravel-61835-7240 (which does affect older than Laravel 8 too)

**Comment by getupkid** [comment]
Yeah, looks like it.

https://github.com/laravel/framework/commit/897d107775737a958dbd0b2f3ea37877c7526371#diff-17e37c1b4a410ed3d77fd43a28c094e2

**Comment by drbyte** [comment]
Ah, yes, that is indeed where I saw that.

Thanks for posting the link.

**Comment by getupkid** [comment]
Changed `protected $guarded = ['id'];` to `protected $guarded = [];` in Spatie\Permission\Models\Permission and boom! gone!

**Comment by drbyte** [comment]
Yes, that would do stop it.

Hopefully that won't leave it open to a coder to accidentally pass `id` via `request->all()` accidentally and mistakenly let users escalate their own privileges.

**Comment by getupkid** [comment]
Yeah, I'm gonna look for a workaround. But at least we located where and why it's happening.

Thanks for your help @drbyte

**Comment by drbyte** [comment]
Prior discussion: #1548, #1542

**Comment by Shhu** [comment]
Hi,
I'm still having this query in my logs.
laravel/framework (v8.36.2)
spatie/laravel-permission (4.0.1)
with postgres12

```sql
select
  column_name
from
  information_schema.columns
where
  table_schema = 'public'
  and table_name = 'permissions'
```

**Comment by Wit3** [comment]
> Changed `protected $guarded = ['id'];` to `protected $guarded = [];` in Spatie\Permission\Models\Permission and boom! gone!

This fix it seems resolve the problem. Anyone has investigated?

**Comment by mhyeganeh** [comment]
+1

Any solution...? It's so annoying to have one extra query in every request that most likely has no benefit.

Dummy question: 
According to @getupkid solution, how can we override `protected $guarded = ['id'];` for ourselves to prevent this extra query...?

**Comment by Wit3** [comment]
> +1
> 
> Any solution...? It's so annoying to have one extra query in every request that most likely has no benefit.
> 
> Dummy question:
> According to @getupkid solution, how can we override `protected $guarded = ['id'];` for ourselves to prevent this extra query...?

Create new Class Permission that extend Model and implements Spatie\Permission\Contracts\Permission like the original one.

Ex:
```
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Collection;

use Spatie\Permission\Contracts\Permission as PermissionContract;
use Spatie\Permission\Exceptions\PermissionAlreadyExists;
use Spatie\Permission\Exceptions\PermissionDoesNotExist;
use Spatie\Permission\Guard;
use Spatie\Permission\PermissionRegistrar;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Traits\RefreshesPermissionCache;

class Permission  extends Model implements PermissionContract
{
    use HasRoles;
    use RefreshesPermissionCache;

    protected $guarded = [];

    public function __construct(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? config('auth.defaults.guard');

        parent::__construct($attributes);
    }

    public function getTable()
    {
        return config('permission.table_names.permissions', parent::getTable());
    }

    public static function create(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? Guard::getDefaultName(static::class);

        $permission = static::getPermissions(['name' => $attributes['name'], 'guard_name' => $attributes['guard_name']])->first();

        if ($permission) {
            throw PermissionAlreadyExists::create($attributes['name'], $attributes['guard_name']);
        }

        return static::query()->create($attributes);
    }

    /**
     * A permission can be applied to roles.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(
            config('permission.models.role'),
            config('permission.table_names.role_has_permissions'),
            'permission_id',
            'role_id'
        );
    }

    /**
     * A permission belongs to some users of the model associated with its guard.
     */
    public function users(): BelongsToMany
    {
        return $this->morphedByMany(
            getModelForGuard($this->attributes['guard_name']),
            'model',
            config('permission.table_names.model_has_permissions'),
            'permission_id',
            config('permission.column_names.model_morph_key')
        );
    }

    /**
     * Find a permission by its name (and optionally guardName).
     *
     * @param string $name
     * @param string|null $guardName
     *
     * @throws \Spatie\Permission\Exceptions\PermissionDoesNotExist
     *
     * @return \Spatie\Permission\Contracts\Permission
     */
    public static function findByName(string $name, $guardName = null): PermissionContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);
        $permission = static::getPermissions(['name' => $name, 'guard_name' => $guardName])->first();
        if (!$permission) {
            throw PermissionDoesNotExist::create($name, $guardName);
        }

        return $permission;
    }

    /**
     * Find a permission by its id (and optionally guardName).
     *
     * @param int $id
     * @param string|null $guardName
     *
     * @throws \Spatie\Permission\Exceptions\PermissionDoesNotExist
     *
     * @return \Spatie\Permission\Contracts\Permission
     */
    public static function findById(int $id, $guardName = null): PermissionContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);
        $permission = static::getPermissions(['id' => $id, 'guard_name' => $guardName])->first();

        if (!$permission) {
            throw PermissionDoesNotExist::withId($id, $guardName);
        }

        return $permission;
    }

    /**
     * Find or create permission by its name (and optionally guardName).
     *
     * @param string $name
     * @param string|null $guardName
     *
     * @return \Spatie\Permission\Contracts\Permission
     */
    public static function findOrCreate(string $name, $guardName = null): PermissionContract
    {
        $guardName = $guardName ?? Guard::getDefaultName(static::class);
        $permission = static::getPermissions(['name' => $name, 'guard_name' => $guardName])->first();

        if (!$permission) {
            return static::query()->create(['name' => $name, 'guard_name' => $guardName]);
        }

        return $permission;
    }

    /**
     * Get the current cached permissions.
     */
    protected static function getPermissions(array $params = []): Collection
    {
        return app(PermissionRegistrar::class)
            ->setPermissionClass(static::class)
            ->getPermissions($params);
    }
}
```

**Comment by arun07as** [comment]
> > +1
> > Any solution...? It's so annoying to have one extra query in every request that most likely has no benefit.
> > Dummy question:
> > According to @getupkid solution, how can we override `protected $guarded = ['id'];` for ourselves to prevent this extra query...?
> 
> Create new Class Permission that extend Model and implements Spatie\Permission\Contracts\Permission like the original one.
> 
> Ex:
> 
> ```
> use Illuminate\Database\Eloquent\Model;
> use Illuminate\Database\Eloquent\Relations\BelongsToMany;
> use Illuminate\Database\Eloquent\Collection;
> 
> use Spatie\Permission\Contracts\Permission as PermissionContract;
> use Spatie\Permission\Exceptions\PermissionAlreadyExists;
> use Spatie\Permission\Exceptions\PermissionDoesNotExist;
> use Spatie\Permission\Guard;
> use Spatie\Permission\PermissionRegistrar;
> use Spatie\Permission\Traits\HasRoles;
> use Spatie\Permission\Traits\RefreshesPermissionCache;
> 
> class Permission  extends Model implements PermissionContract
> {
>     use HasRoles;
>     use RefreshesPermissionCache;
> 
>     protected $guarded = [];
> 
>     public function __construct(array $attributes = [])
>     {
>         $attributes['guard_name'] = $attributes['guard_name'] ?? config('auth.defaults.guard');
> 
>         parent::__construct($attributes);
>     }
> 
>     public function getTable()
>     {
>         return config('permission.table_names.permissions', parent::getTable());
>     }
> 
>     public static function create(array $attributes = [])
>     {
>         $attributes['guard_name'] = $attributes['guard_name'] ?? Guard::getDefaultName(static::class);
> 
>         $permission = static::getPermissions(['name' => $attributes['name'], 'guard_name' => $attributes['guard_name']])->first();
> 
>         if ($permission) {
>             throw PermissionAlreadyExists::create($attributes['name'], $attributes['guard_name']);
>         }
> 
>         return static::query()->create($attributes);
>     }
> 
>     /**
>      * A permission can be applied to roles.
>      */
>     public function roles(): BelongsToMany
>     {
>         return $this->belongsToMany(
>             config('permission.models.role'),
>             config('permission.table_names.role_has_permissions'),
>             'permission_id',
>             'role_id'
>         );
>     }
> 
>     /**
>      * A permission belongs to some users of the model associated with its guard.
>      */
>     public function users(): BelongsToMany
>     {
>         return $this->morphedByMany(
>             getModelForGuard($this->attributes['guard_name']),
>             'model',
>             config('permission.table_names.model_has_permissions'),
>             'permission_id',
>             config('permission.column_names.model_morph_key')
>         );
>     }
> 
>     /**
>      * Find a permission by its name (and optionally guardName).
>      *
>      * @param string $name
>      * @param string|null $guardName
>      *
>      * @throws \Spatie\Permission\Exceptions\PermissionDoesNotExist
>      *
>      * @return \Spatie\Permission\Contracts\Permission
>      */
>     public static function findByName(string $name, $guardName = null): PermissionContract
>     {
>         $guardName = $guardName ?? Guard::getDefaultName(static::class);
>         $permission = static::getPermissions(['name' => $name, 'guard_name' => $guardName])->first();
>         if (!$permission) {
>             throw PermissionDoesNotExist::create($name, $guardName);
>         }
> 
>         return $permission;
>     }
> 
>     /**
>      * Find a permission by its id (and optionally guardName).
>      *
>      * @param int $id
>      * @param string|null $guardName
>      *
>      * @throws \Spatie\Permission\Exceptions\PermissionDoesNotExist
>      *
>      * @return \Spatie\Permission\Contracts\Permission
>      */
>     public static function findById(int $id, $guardName = null): PermissionContract
>     {
>         $guardName = $guardName ?? Guard::getDefaultName(static::class);
>         $permission = static::getPermissions(['id' => $id, 'guard_name' => $guardName])->first();
> 
>         if (!$permission) {
>             throw PermissionDoesNotExist::withId($id, $guardName);
>         }
> 
>         return $permission;
>     }
> 
>     /**
>      * Find or create permission by its name (and optionally guardName).
>      *
>      * @param string $name
>      * @param string|null $guardName
>      *
>      * @return \Spatie\Permission\Contracts\Permission
>      */
>     public static function findOrCreate(string $name, $guardName = null): PermissionContract
>     {
>         $guardName = $guardName ?? Guard::getDefaultName(static::class);
>         $permission = static::getPermissions(['name' => $name, 'guard_name' => $guardName])->first();
> 
>         if (!$permission) {
>             return static::query()->create(['name' => $name, 'guard_name' => $guardName]);
>         }
> 
>         return $permission;
>     }
> 
>     /**
>      * Get the current cached permissions.
>      */
>     protected static function getPermissions(array $params = []): Collection
>     {
>         return app(PermissionRegistrar::class)
>             ->setPermissionClass(static::class)
>             ->getPermissions($params);
>     }
> }
> ```

It would be even better to just create a new model that extends the permission model like this

```
<?php

namespace App\Models;

use Spatie\Permission\Models\Permission as ModelsPermission;

class Permission extends ModelsPermission
{

    protected $fillable = [
        "name",
        "guard_name",
    ];

    // When using guarded, laravel runs a query to check if the columns are actually present in the db
    // The package uses guarded, so it was running unecessary queries on each request
    // so we will override it and use fillable instead
    // @link https://github.com/spatie/laravel-permission/issues/1569
    protected $guarded = [];
}
```
and then update the model being used in `config/permission.php`
```
    'models' => [

        /*
         * When using the "HasPermissions" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your permissions. Of course, it
         * is often just the "Permission" model but you may use whatever you like.
         *
         * The model you want to use as a Permission model needs to implement the
         * `Spatie\Permission\Contracts\Permission` contract.
         */

        // 'permission' => Spatie\Permission\Models\Permission::class,
        'permission' => \App\Models\Permission::class,
```

**Comment by adamczykpiotr** [comment]
The same rule applies to Role model. 

Fillable fields are the same as in Permission model so it's possible to just copy-paste the file and replace all occurrances of "Permission" to "Role"

**Comment by pokono** [comment]
I see 2 extra queries on my application for each call. Is it safe to remove the guarded id? On top of my head, I can't think of any, but if it's in the original package, I guess they deemed it worth making 2 extra queries?
