### ISSUE TITLE
Call to a member function contains() on null 

### ISSUE THREAD

**Issue by Aless55** [spatie/laravel-permission#1579]
Hello everyone

Suddenly my app throws the error `Call to a member function contains() on null ` and I don't even know why. 
It points to my call `$user->hasRole('admin')` and the stacktrace goes further into **line 184** of the HasRole Trait where `$this->roles->contains('name', $roles);` is called. To my surprise the call `$this->roles` is null in the Trait itself and even if I am calling it somewhere in my code like `$user->roles`. 
Even more surprisingly is that if I call somewhere in my app `$this->permissions` the correct permission collection is returned and if I call `$this->roles()->get()`the roles collection is returned. 

I am using the most recent version of this package, Laravel 7.28 and multi tenancy package hyn/multi-tenancy, but I also tried it out on a different branch with Stancl/tenancy, both with the most recent versions and in both with the same error. 

I did everything the installation guides said and for Stancl i simply added the code snippet in the boot() method as described [here](https://tenancyforlaravel.com/docs/v3/integrations/spatie/) and for hyn I tried it with the TenantAware Traits as written [here](https://tenancy.dev/docs/hyn/5.6/spatie-laravel-permission).

Does anyone have a clue where I could have done something wrong or what could raise this problem?

**Comment by drbyte** [comment]
> Suddenly my app throws the error...

"Suddenly" is the key word there. That means "something that you changed recently has introduced a problem".

What changed recently? 
- package updates? 
- code changes like new features, etc?

Most likely you've added a `$roles` property to user User model and that's overriding the trait. Maybe you did that in your model itself, or inside another trait that you recently added to the model, or to an existing trait that had new changes made to it.

**Comment by Aless55** [comment]
I did not think that far, thank you. I somehow added a cast for roles (I don't even know why and why I didn't see it earlier), that screwed everything up. I somehow searched at least for 5 hours, thinking the problem has to do with the tenancy package. But thanks to your hint I found it in like 2 mins.
Have a good one and thank you very much.
