### ISSUE TITLE
stdClass::getDirectPermissions() not working

### ISSUE THREAD

**Issue by bhattaxay** [spatie/laravel-permission#1581]
Hii there,

I have tried to fetch the user direct permission by this method as defined in Tutorial : ```$userpermission = $user->getDirectPermissions();```, but it throw me : ```Call to undefined method stdClass::getDirectPermissions()```. Kindly provide the solution. I have also used this method ```$user->getAllPermissions();```, but it gives me same error,

**Comment by drbyte** [comment]
> `$user->getDirectPermissions();`, but it throw me : `Call to undefined method stdClass::getDirectPermissions()`. 

The error message is revealing that your `$user` variable doesn't contain a `User` model object, but rather a `stdClass` object instead. You will need to fix this in your app.

**Comment by bhattaxay** [comment]
No I am getting user model while i print it ```dd($user);```

**Comment by bhattaxay** [comment]
ok i got your point. I have used DB query instead of using eloquent query that's why it was not work. Thank you so much.
