### ISSUE TITLE
Implementing UUIDs as a Primary Key has an Issue on Assigning User to a Certain Role

### ISSUE THREAD

**Issue by gieart87** [spatie/laravel-permission#1584]
Hi,
I've just tried to integrate this package into the Laravel 8 project using UUIDs implementation as a Primary Key. Everything looks fine until I try to assign a user to a certain role, e.g 'Admin'. My code:

`
$user = $request->user();
$assignUserToRole = $user->assignRole('Admin');
`

and I got the following error:
`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel8_bootstrapdb`.`model_has_roles`, CONSTRAINT `model_has_roles_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE) (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (91b57341-5e99-4057-9b94-826a76579d16, App\Models\User, 91))`

My own Role model that extends the Spatie's Role model:
`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Str;

use App\Models\Concerns\UsesUuid;

class Role extends \Spatie\Permission\Models\Role
{
    use HasFactory, UsesUuid;

    protected $fillable = [
        'id',
        'name',
        'guard_name',
    ];

    protected $primaryKey = 'id';
    public $incrementing = false;

    protected $casts = [
        'id' => 'string'
    ];
}
`

It looks like the String casting doesn't work like expected. Because the role id still an integer value. And when I tried to implement the String casting in the original Spatie's Role model, everything works fine then. But, I wonder why it works fine when assigning permission to a user which is I thought has a similar case.

So, if you guys know how to solve this issue without touching the original package please let me know. Thanks.

**Comment by drbyte** [comment]
See https://spatie.be/docs/laravel-permission/v3/advanced-usage/uuid

**Comment by rezadaulay** [comment]
Please check my comment here: https://github.com/spatie/laravel-permission/issues/1639#issuecomment-924603535
