### ISSUE TITLE
hasAnyPermission returns null

### ISSUE THREAD

**Issue by oliverwh** [spatie/laravel-permission#1586]
Hey guys,

I've been digging around but can't find the solution so far.

After updating lib somewhere in July I am bumping into a weird issue (did another update today as well).

My users, when called "hasAnyPermission" can return null time to time, however no changes to permissions were done. If I check in DB, the permissions are there, however it still returns null. If I go click save on my permission view - everything back to normal for sometime. But again, no changes are happening in DB in regards to permissions. Any advice would be highly appreciated.

**Comment by drbyte** [comment]
I wonder if there's something in your application that is referring to the wrong object or something? 

The code itself, as provided by this package anyway, always returns either `true` or `false`, never `null`:
https://github.com/spatie/laravel-permission/blob/53475abe5464ac722b3794af14cc316f7a77805e/src/Traits/HasPermissions.php#L215-L226
