### ISSUE TITLE
Add function/method and variable to my permission model extend spatie

### ISSUE THREAD

**Issue by RayhanYulanda** [spatie/laravel-permission#1587]
I have extend spatie but i want to add some function/method and variable to my permission. What should i do? and how to call it? Here is it my model
```
namespace App;

class Permission extends \Spatie\Permission\Models\Permission
{
      $var ='foo'; //i want to add this
      public static function defaultPermissions(){}//and this
}
```

**Comment by drbyte** [comment]
I don't understand your question.

You can add custom methods and fields as you like, including migrations for those fields.

**Comment by RayhanYulanda** [comment]
Thank you, i've solved it @drbyte
