### ISSUE TITLE
Role and permission

### ISSUE THREAD

**Issue by Eductiveo** [spatie/laravel-permission#159]
Can you just add the role instead of role and permission?
like: `Route::group(['middleware' => ['role:mod']], function () {`

Because I now use in my routes:
`Route::group(['middleware' => ['role:mod,modcp.index']], function () {`

But what if another role (designer) could have access to that, how can I do it?

**Comment by Eductiveo** [comment]
And if I want to add in my roles like: description, display_name,... Do I need to have some updates around my models? Or...

**Comment by freekmurze** [comment]
Out of the box the package doesn't contain a middleware to check roles, but there's an example in the docs on [how to create it yourself](X-My-Custom-Header).

`Role` and `Permission` are just regular Eloquent models. If you just need some extra fields, just add the to the db and you'll be able to use them. If you want to add some behaviour to the models, that you need to register your custom model. This too is [explained](https://github.com/spatie/laravel-permission#extending) in the docs.
