### ISSUE TITLE
model->assignRole('admin') not working for laravel-7.X

### ISSUE THREAD

**Issue by peter2796b** [spatie/laravel-permission#1592]
$user = User::create($validatedData);
 $user->assignRole('admin');

`{
    "message": "Illegal offset type in isset or empty",
    "exception": "ErrorException",
    "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php",
    "line": 285,
    "trace": [
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php",
            "line": 285,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
            "line": 595,
            "function": "match",
            "class": "Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
            "line": 564,
            "function": "eagerLoadRelation",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
            "line": 520,
            "function": "eagerLoadRelations",
            "class": "Illuminate\\Database\\Eloquent\\Builder",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/spatie/laravel-permission/src/Traits/HasRoles.php",
            "line": 117,
            "function": "load",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/app/Http/Controllers/AuthController.php",
            "line": 33,
            "function": "assignRole",
            "class": "App\\User",
            "type": "->"
        },
        {
            "function": "register",
            "class": "App\\Http\\Controllers\\AuthController",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 239,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 196,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 59,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/fruitcake/laravel-cors/src/HandleCors.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}`

**Comment by drbyte** [comment]
It seems like you've added a custom `roles()` method or `role` property on your `User` model and this is conflicting with the package's `hasRoles` trait logic which expects those to refer to relations and properties managed by this package and not in your own code.

**Comment by peter2796b** [comment]
I dont have any method or property named roles in my user model its a fresh project, when i debugged the code it was failing in the HasRole Trait at line (117) :    $model->load('roles');

when i changed it to $model->with('roles'); it worked.

**Comment by drbyte** [comment]
That's very odd.

I can't replicate the problem on a fresh Laravel install with nothing else other than this package and the creation of a permission.

Also, the tests for the HasRole Trait are all passing on all supported Laravel versions. 

This leads me to wonder what else is in your app. 

> { "file": "/home/peter/Documents/code_new/backend/laravel/laravel-boilerplate/vendor/laravel/framework/...",

What's the reference to `laravel-boilerplate` referring to? 
Particularly, how is this boilerplate you're using different from a fresh install of Laravel itself?

**Comment by peter2796b** [comment]
laravel-boilerplate is what i created a new repo from a fresh laravel project.
[https://github.com/peter2796b/laravel-vue-boilerplate](url).

could you try it on this may be.

**Comment by masterix21** [comment]
I have the same issue and confirm that changing `$model->load('roles');` with `$model->with('roles');` the problem disappear.

I'm using custom models for `Role` and `Permission`, but I have no `roles()` method or `role` property.

It is an example that throw the error:
```php
app()[PermissionRegistrar::class]->forgetCachedPermissions();

Permission::create(['name'=>'edit all']);

Role::create(['name' => User::ROLE_OWNERS, 'guard_name' => 'web'])->givePermissionTo('edit all');
```

What could be?

**Comment by drbyte** [comment]
> It is an example that throw the error:
> 
> ```
> app()[PermissionRegistrar::class]->forgetCachedPermissions();
> 
> Permission::create(['name'=>'edit all']);
> 
> Role::create(['name' => User::ROLE_OWNERS, 'guard_name' => 'web'])->givePermissionTo('edit all');
> ```
> 

I don't get any errors when doing that (after substituting User::ROLE_OWNERS with 'owners', of course).

> I have the same issue and confirm that changing `$model->load('roles');` with `$model->with('roles');` the problem disappear.
> 

But, `->with` creates a new model and does nothing with it. Thus, commenting out the line would probably accomplish the same. Does commenting-out the ->load line also "solve" it for you? 

That begs the question: do you have any global scopes or other relations set up?

**Comment by masterix21** [comment]
I've solved my issue using `$model->refresh()` before assigns roles/permissions. At the moment I have no time to dig inside, so I hope that this short suggestion will help someone in the future. Thanks.

**Comment by masterix21** [comment]
Today I had again the problem in another project. I can confirm that changing `$model->assignRole('your-role')` with `$model->refresh()->assignRole('your-role')` the issue disappear.

@drbyte, do you have any idea about the issue? I'm assigning the roles with a listener.
