### ISSUE TITLE
User model moved to the Models folder; now permissions is returning 0

### ISSUE THREAD

**Issue by divyamanchireddy19** [spatie/laravel-permission#1596]
The User model is moved to the Models folder and permissions is returning 0
```
$user = Auth::user(); 
$permissions = $user->getAllPermissions();
```
If the User model is moved to `app` directory and changed in `config/web.php`,  to `'model' => App\User::class,`  permissions are working fine

Anyone facing the same issue? Or any idea how to solve it?

**Comment by drbyte** [comment]
With Laravel Eloquent polymorphic relations, whenever you change the namespace of the objects whose relations are already stored in pivot tables you must update the tables to reflect the new namespace.

You will need to do this with all polymorphic relation pivot tables you have in your app.

In the case of this permissions package, the `model_type` field stores the name of the class, including its namespace.
in the following tables:
`model_has_permissions`
`model_has_roles`
