### ISSUE TITLE
There is no role with id `1`.

### ISSUE THREAD

**Issue by matinwd** [spatie/laravel-permission#1597]
i have some problems with package that appears sometimes and they solve with clearing the cache but in this case i noticed when i try to get role for update it, it says 
`There is no role with id `1`.`
this is my database:
![2020-10-25_14-28-57](https://user-images.githubusercontent.com/52950867/97105268-d0f93880-16ce-11eb-9549-8c03cd20ac60.png)
and i am totally sure i have role with number 1!

this is my config auth.php:

```
'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],
    ],
```

**Comment by drbyte** [comment]
Seems like a bug in your application code.
Without seeing your code and knowing where the message is being triggered, it's very difficult to assist.

It would be helpful if you build a demo app to show only this error situation. Preferably no other functionality  besides what is necessary to trigger the problem. Commit-by-commit will be helpful as well. No unnecessary other packages. Example: https://spatie.be/docs/laravel-permission/v3/basic-usage/new-app

**Comment by matinwd** [comment]
Yes sorry
Here is  my code in seeder:

```
public $permissions = [
        'roles' => 'نقش',
        'users' => 'کاربر',
        'admins' => 'مدیر',
        'categories' => 'دسته بندی',
        'products' => 'محصول',
        'brands' => 'برند',
        'stores' => 'فروشگاه',
        'orders' => 'سفارش',
        'departments' => 'دپارتمان',
        'tickets' => 'تیکت',
        'coupons' => 'کوپن',
        'wallet' => 'والت',
        'manage-owner' => 'موجودی فروشگاه ها',
    ];

    public $actions = [
        'create' => 'ساخت',
        'read' => 'مشاهده',
        'update' => 'ویرایش',
        'delete' => 'حذف'
    ];

foreach ($this->permissions as $permissionName => $permissionTitle) {
            foreach ($this->actions as $action => $title) {
                factory(\App\Models\Permission::create(['name' => $permissionName . '.' . $action, 'title' => $title . ' ' . $permissionTitle]));
            }
        }
```

Role Controller:
```
public function store(RoleRequest $request)
    {
        $res = Role::create(['name' => $request->get('name'),'title' => $request->get('title')]);
        $res->givePermissionTo($request->get('permissions'));
        setLog(auth()->user(),$res,'یک نقش افزوده شد');
        if ($res) {
            return response()->json(['data' => $res]);
        }
        return response()->json(['data' => $res], 402);
    }

public function update(RoleRequest  $request,$id)
    {
        $res = Role::findById($id);
        $res->givePermissionTo($request->get('permissions'));
        setLog(auth()->user(),$res,'یک نقش ویرایش شد');
        if ($res) {
            return response()->json(['data' => $res]);
        }
        return response()->json(['data' => $res], 402);
    }

```

please tell me which codes you need for assist and i'll send you.

**Comment by drbyte** [comment]
More questions:
- what guard is being used for calls to `RoleController::update` ?
- please share code for `App/Models/Role` and `RoleRequest`

**Comment by matinwd** [comment]
App\Models\Role:
```
<?php

namespace App\Models;


class Role extends \Spatie\Permission\Models\Role
{
    public  $guard_name = '*';

}

```

RoleRequest:
```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RoleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required',
            'title' => 'required'
        ];
    }
}

--------------
Default gaurd is web i used in config 
```

**Comment by drbyte** [comment]
> this is my config auth.php:
> 
> ```
> 'defaults' => [
>         'guard' => 'web',
>         'passwords' => 'users',
>     ],
>     'guards' => [
>         'web' => [
>             'driver' => 'session',
>             'provider' => 'users',
>         ],
>         'api' => [
>             'driver' => 'passport',
>             'provider' => 'users',
>         ],
>     ],
> ```


> App\Models\Role:
> 
> ```
> class Role extends \Spatie\Permission\Models\Role
> {
>     public  $guard_name = '*';
> 
> }
> ```

`$guard_name = '*'` does not match any of the guards in your config.
Change it to `$guard_name = 'web'` if you're going to use the `web` guard with these roles.

**Comment by matinwd** [comment]
i tried $guard_name = 'web'; 
but did not work...
and either i cleared application and package caches..

**Comment by drbyte** [comment]
`Role::findById($id);` can take a second parameter `guard_name`. If you don't specify one then it attempts to do a lookup based on model properties and configuration parameters.

If a match between id and guard_name cannot be found then the exception will be thrown saying your original message `There is no role with id 1`.

Here's the code:
https://github.com/spatie/laravel-permission/blob/78e8f95eaaf0fe0d395cea4a6f6b2cc675a7a9bb/src/Models/Role.php#L95-L106

**Comment by ntquangkk** [comment]
In my case, I have run RoleSeeder to create roles with guard_name = 'api' while my default variable of guard is 'web' (in 'config\auth.php' file). Then, when I run UserSeeder to create an initial admin account and assign it with role 'admin' created before, it throw "There is no role with id `1`" - RoleDoesNotExist exception.
That happened because Laravel search role 'admin' with guard_name = (defaults->guard =) 'web' which had not be created.
Solutions are:
1/ If your system is using API only: Changing default guard to 'api'. So, Laravel would search role 'admin' with guard_name = 'api'.
2/ If your system is using Webview only: Create roles with guard_name = 'web' (= defaults->guard too)
3/ If your system is using both API and Webview: Create each roles with both guard_name = 'web' and 'api'.
