### ISSUE TITLE
Integrate it with CAS

### ISSUE THREAD

**Issue by cod3r0k** [spatie/laravel-permission#1602]
Hi, I want to use CAS (https://github.com/subfission/cas)  and spatie/laravel-permission.

I want to use CAS for username and password and then I want to pass information into the spatie.

Could you help me?

**Comment by drbyte** [comment]
It appears that that package provides **authentication**.

This package provides **authorization**. Specifically it depends on interacting with an `Authorizable` object.
(See https://spatie.be/docs/laravel-permission/v3/prerequisites and the Laravel docs for details)

So, as long as your **authentication** package can provide your app with an object that implements the `Authorizable` interface, you can configure that object to use this package's features via the provided trait as per the installation instructions.

**Comment by cod3r0k** [comment]
> It appears that that package provides **authentication**.
> 
> This package provides **authorization**. Specifically it depends on interacting with an `Authorizable` object.
> (See https://spatie.be/docs/laravel-permission/v3/prerequisites and the Laravel docs for details)
> 
> So, as long as your **authentication** package can provide your app with an object that implements the `Authorizable` interface, you can configure that object to use this package's features via the provided trait as per the installation instructions.

Thank you so much for your comments.

I check your suggested link. It was useful for me. Thanks.


````
This package (spatie) uses Laravel's Gate layer to provide Authorization capabilities. The Gate/authorization layer requires that your User model implement the Illuminate\Contracts\Auth\Access\Authorizable contract. Otherwise the can() and authorize() methods will not work in your controllers, policies, templates, etc.
In the Installation instructions you'll see that the HasRoles trait must be added to the User model to enable this package's features.
Thus, a typical basic User model would have these basic minimum requirements:
````
It means that I must achieve the string of `role` of each user from CAS and set it in this section and then the spatie could work well like before for authorization. Isn't it? If you see any further notes or user guides, please send me. Thanks a lot.

**Comment by cod3r0k** [comment]
Dear @drbyte @tomschlick @djoudi 

Can I create a controller to handle CAS parameters and then set a predefined role for that user? I don't want to store these roles. Can I do it with nothing storing in database?

**Comment by drbyte** [comment]
>  I don't want to store these roles. Can I do it with nothing storing in database?

I don't think this package will suit your needs in this case.

**Comment by cod3r0k** [comment]
> > I don't want to store these roles. Can I do it with nothing storing in database?
> 
> I don't think this package will suit your needs in this case.

@drbyte 
I'm sorry, I think I make an ambiguation in your mind.  I mean that I don't want to store the role of each user in the database for ever, It doesn't mean that we can't store them during each login session.

If I want to assign a role during each session(session I mean, it is not cookies)  with checking of CAS's parameter, What should I do now?

**Comment by cod3r0k** [comment]
Can we get some attribute from CAS authentication step and check them and assign a role to that user during its login session ?
I mean that if we want to assign a role for each user during its login session with Spatie, What should we do now?

@drbyte @djoudi @mattdfloyd @tomschlick
