### ISSUE TITLE
Spatie/Permissions  It does not work in Laravel 8.12

### ISSUE THREAD

**Issue by mafalda2007** [spatie/laravel-permission#1603]
Hi, I install Spatie as the instructions say. At the time of adding in the Model it does not recognize the HasRole

**Comment by drbyte** [comment]
It seems you've not completed the steps correctly. 
A fresh install works fine for me. And all the tests of the package are passing properly.

**Comment by renatomaric** [comment]
If you migrated models to Models directory you need to update data in **model_type** (table **model_has_roles**) from **App\User** to  **App\Models\User**
