### ISSUE TITLE
Live role assignment

### ISSUE THREAD

**Issue by cod3r0k** [spatie/laravel-permission#1605]
Dear all, can we assign a live role to each user? 

I mean that, some users which comes and doesn't have a role before, We want to assign a role to them for that session. Can we?

**Comment by drbyte** [comment]
This package allows you to provide relationships between persisted users and your defined (persisted) roles and permissions.

If you want to grant authorization to features for only a single session, that's code you'll need to write within your application. You might consider doing that with specialized code in an AuthServiceProvider or Gate Policies.
