### ISSUE TITLE
Gate::before doesn't work for defining a super-admin!

### ISSUE THREAD

**Issue by MahbodHastam** [spatie/laravel-permission#1609]
![image](https://user-images.githubusercontent.com/17749373/98140756-0bd34b80-1edb-11eb-9d57-025e5914c508.png)

But when I use this role (with middleware) in my routes it works correctly!

**Comment by drbyte** [comment]
I don't understand your post.

Your title says "Gate::before doesn't work..." but then your code example shows Gate::before working fine.
