### ISSUE TITLE
[Suggestion] Inheritence

### ISSUE THREAD

**Issue by MrMashy** [spatie/laravel-permission#161]
I've added inheritance into my project, It could probably be optimized but here's how I did it:

In `Models/Role.php`

     /**
     * Get all the roles which the parent inherits
     *
     * @return \Illuminate\Support\Collection return a collection of roles
     **/
    public function childRoles()
    {
        return $this->belongsToMany(
            config('laravel-permission.models.role'),
            config('laravel-permission.table_names.role_inherits'),
            'parent_id',
            'child_id'
        )->get();
    }

In `HasRoles.php` some changes and new additions:

    private $checkedRoles = [];

    public function roles(){
        $roles = $this->belongsToMany(
            config('laravel-permission.models.role'),
            config('laravel-permission.table_names.user_has_roles')
        )->get();

        $roles = $this->loopRoles($roles);
        return $roles;
    }

    /**
     * Loop through Roles and find it's child roles
     * 
     * @var \Illuminate\Support\Collection $roles
     * @return \Illuminate\Support\Collection $roles
     */
    private function loopRoles($roles){
        foreach($roles as $role){
            if(! in_array($role->name, $this->checkedRoles)){
                array_push($this->checkedRoles, $role->name);
                $roles = $roles->merge($role->childRoles());
                $roles = $this->loopRoles($roles);
            }
        }
        return $roles;
    }

and in Migrations:

     Schema::create($config['role_inherits'], function(Blueprint $table) use ($config){
            $table->integer('id')->unsigned();
            $table->integer('parent_id')->unsigned();
            $table->integer('child_id')->unsigned();

            $table->foreign('parent_id')
                ->references('id')
                ->on($config['roles'])
                ->onDelete('cascade');

            $table->foreign('child_id')
                ->references('id')
                ->on($config['roles'])
                ->onDelete('cascade');

            $table->primary(['id']);
        });

and finally in config add:

        /*
        |--------------------------------------------------------------------------
        | Role Inherits Table
        |--------------------------------------------------------------------------
        |
        | When using the "HasRoles" trait from this package, we need to know which
        | table should be used to retrieve your roles permissions. We have chosen a
        | basic default value but you may easily change it to any table you like.
        |
        */

        'role_inherits' => 'role_inherits',

**Comment by MrMashy** [comment]
I could create a pull request if you want this to be a part of the project, currently no other role package allows inheritence, and I've seen many developers ask for one.

I haven't tested permissions but I believe they should work.

**Comment by freekmurze** [comment]
Thanks for your suggestion, but I probably won't merge such a PR. I'd like to keep this package simple and easy.

Of course you're free to fork the package and maintain your own copy with this feature implemented.

**Comment by ziming** [comment]
I was reading the 2 inheritance suggestions. Strangely in all my work so far that need me to do ACL, role inheritance is an often demanded feature no matter how hard I try to push it aside.

I especially like the way romanbican/roles handles role inheritance. He had a role_level value, roles with higher levels inherit the permissions of roles with lower level. If you do not wish to use it, just have every role use the default level of 0 and it will be your typical role based permission package.

Too bad he didn't update it for 2+ years now. It's fine if it's a no too, just sharing my thoughts.

https://github.com/romanbican/roles
