### ISSUE TITLE
Getting "Unable to flush cache" when trying do cache-reset

### ISSUE THREAD

**Issue by wmfairuz** [spatie/laravel-permission#1612]
Hi,

I'm getting "Unable to flush cache" error when I'm trying to run "php artisan permission:cache-reset" command.

Also tried to do "php artisan cache:clear" first before running this command, but still getting the same error.

Also tried to run this command as root, still the same.

Is there anyway to manually find this cache and remove them?

I'm using file as my cache driver.

**Comment by francoism90** [comment]
Did you check your `laravel.log`/logging?

**Comment by wmfairuz** [comment]
> Did you check your `laravel.log`/logging?

Nothing comeout in the log file after I run the command

**Comment by drbyte** [comment]
Two Questions:

1. Is this problem actually limited to just clearing cache for this package? Or does your entire application actually have the same issue? It could be a broader problem such as your environment. See https://github.com/spatie/laravel-permission/issues/1536

2. Does the problem continue if you switch your cache driver from `file` to something else?
    In looking at the code it appears as though it may be possible that the `file` cache thinks it has nothing to delete and thus the response back to the command appears as though the clearing request failed, when in fact it had nothing it needed to do.
Reference:
https://github.com/spatie/laravel-permission/blob/b5611570869263f670aa36fc2bcd2f3b2ff65b20/src/PermissionRegistrar.php#L119

    ... which in the case of the `file` driver calls:
https://github.com/laravel/framework/blob/8550bac5cf4d9e8d52296c1f6d93bbf7f4596002/src/Illuminate/Cache/FileStore.php#L161-L168

    ... which calls:
https://github.com/laravel/framework/blob/8550bac5cf4d9e8d52296c1f6d93bbf7f4596002/src/Illuminate/Filesystem/Filesystem.php#L262-L279

**Comment by wmfairuz** [comment]
@drbyte Thanks

> Two Questions:
> 
> 1. Is this problem actually limited to just clearing cache for this package? Or does your entire application actually have the same issue? It could be a broader problem such as your environment. See #1536

I can clear Laravel cache with no problem in this app. Since I also have different Laravel apps in the server that uses this package, I did try to run this command (php artisan permission:cache-reset) in them and they do not have this issue (even if I run them several times).

> 2. Does the problem continue if you switch your cache driver from `file` to something else?
>    In looking at the code it appears as though it may be possible that the `file` cache thinks it has nothing to delete and thus the response back to the command appears as though the clearing request failed, when in fact it had nothing it needed to do.
>    Reference:
>    https://github.com/spatie/laravel-permission/blob/b5611570869263f670aa36fc2bcd2f3b2ff65b20/src/PermissionRegistrar.php#L119
>    
>    ... which in the case of the `file` driver calls:
>    https://github.com/laravel/framework/blob/8550bac5cf4d9e8d52296c1f6d93bbf7f4596002/src/Illuminate/Cache/FileStore.php#L161-L168
>    ... which calls:
>    https://github.com/laravel/framework/blob/8550bac5cf4d9e8d52296c1f6d93bbf7f4596002/src/Illuminate/Filesystem/Filesystem.php#L262-L279

Interesting. I changed my driver to database and getting "Permission cache flushed." when running the command. But when I changed back to file driver, it still gives me "Unable to flush cache.".

**Comment by drbyte** [comment]
> Interesting. I changed my driver to database and getting "Permission cache flushed." when running the command. But when I changed back to file driver, it still gives me "Unable to flush cache.".

And if you check the actual cache, has it indeed been flushed ... ie: perhaps the error is a false-positive?

**Comment by cp-vrkansagara** [comment]
Simple hac for this issue is @wmfairuz  and @drbyte 
`php artisan cache:forget spatie.permission.cache`

**Comment by zamronypj** [comment]
@wmfairuz 
I have same problem "Unable to flush cache". I use file driver to store cache. It turns out that it failed because of file permission issue. I run `php artisan permission:cache-reset` from shell as current user while cache is owned by `www-data` user.

**Comment by cp-vrkansagara** [comment]
Who so ever want to stick with `www-data` user can use this 

#### sudo -u www-data  php artisan permission:cache-reset

**Comment by GempitaRizki** [comment]
> @wmfairuz I have same problem "Unable to flush cache". I use file driver to store cache. It turns out that it failed because of file permission issue. I run `php artisan permission:cache-reset` from shell as current user while cache is owned by `www-data` user. Fix permission of cache file and directory fix the problem.

if i run on this git bash are a still working ? but i run this `php artisan permission:cache-reset` and still not working, permission just still same
