### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by summea** [spatie/laravel-permission#1617]
Hello,

I just noticed from this recent change (https://github.com/spatie/laravel-permission/commit/65ee670baa8e7cf49c281dad12f74a221045f23b) that Laravel 5.8 might no longer be supported by laravel-permission.

Do you know what the latest version of laravel-permission is that would still work with Laravel 5.8?

I have a project that previously used entrust (https://github.com/zizaco/entrust), but I'm hoping to convert this project to use laravel-permission instead because entrust doesn't appear to be supported anymore. I'm currently using Laravel 5.8 for this project, however, and because entrust doesn't support higher than Laravel 5.8, I think I need to be able to use laravel-permission with my existing project state before being able to update the project to Laravel 6.

Thanks!

**Comment by drbyte** [comment]
3.17.0 still supports Laravel 5.8

**Comment by summea** [comment]
@drbyte Okay, thank you for letting me know!
