### ISSUE TITLE
How can I fetch all the permissions that a role have?

### ISSUE THREAD

**Issue by Aniket-IN** [spatie/laravel-permission#1618]
Suppose I have a role called "Admin"

and the Admin role has multiple Permissions, How can fetch all thoose Permissions?

I know how to fetch the the Permissions of a user, but I'm not able to do this with Roles.

**Comment by drbyte** [comment]
Each Role has a `permissions` attribute by way of polymorphic relations.

If `$role` is a `Role` model you've retrieved, then:
`$role->permissions` is a collection of permissions associated with the role.

Related:
https://github.com/spatie/laravel-permission/issues/523
