### ISSUE TITLE
Where are the guards defined?

### ISSUE THREAD

**Issue by takdw** [spatie/laravel-permission#1620]
Ok, I think I'm missing something big here. But it's my understanding that this package helps me create roles and permissions and associate them with a user (or another model that can be authenticated and with the `HasRoles` trait). The documentation says:

> Because all permissions will be registered on Laravel's gate, ...

So I assumed there would be some place where these gates are being defined. But I couldn't find any. My understanding at the moment is this. I simply create permissions and assign them to a role or to a user directly, but there is no way for me to actually define how that permission works. Traditionally, with gates I can do something like:

```php
Gate::define('update-post', function ($user, $post) {
    return $user->id === $post->user_id;
});
```

This gate will make sure that a user can only update their own post. Before jumping to conclusions, can this package help me achieve this? Because at the moment, all I can do is just assign a permission (such as `update-post`) to a user with out any underlying logic on how that permission is applied. Am I missing the concept of permissions entirely?

**Comment by drbyte** [comment]
In your title did you mean to use the word `guards`?

**Comment by drbyte** [comment]
This package lets you create roles/permissions in the database. Then when the application boots and a user logs in, this package reads all the permissions the user has access to and loops over each running `Gate::define('the permission name'), function {return true})`

Then in your app you check `$user->can('permission name here')` or `@can('permission name here')`.

And in Model Policies and in any custom Gate::defines you may create, you can also test `$user->can('permission name here')`. You may want to do those in combination with other rules. 
For example in your post above if you wanted to also allow any users with `moderate all posts` permission assigned to them, you could modify your `update-post` rule to something like:

```php
Gate::define('update-post', function ($user, $post) {
    return $user->can('moderate all posts') || $user->id === $post->user_id;
});
```

**Comment by takdw** [comment]
Thank you for the explanation. 

> this package reads all the permissions the user has access to and loops over each running Gate::define('the permission name'), function {return true})

This was the bit I missed. Thank you again.

**Comment by drbyte** [comment]
> this package reads all the permissions the user has access to and loops over each running `Gate::define('the permission name'), function {return true})`

I should clarify: it actually does it a little differently than that. It calls `$user->checkPermissionTo()` which checks the permission name against the list of permissions found in the database (a collection of polymorphic relations between user/roles/permissions), and returns true/false accordingly.

Just clarifying in case you went looking for defined Gates. :)

**Comment by takdw** [comment]
> Just clarifying in case you went looking for defined Gates. :)

I was doing just that. 😅 I thought I had the ability to modify how they were defined. Thanks for clearing that up. 👍
