### ISSUE TITLE
How can I fetch all users that a permission has? Multiple Guards

### ISSUE THREAD

**Issue by alibaba258** [spatie/laravel-permission#1622]
Hi all,

i am try to fetch all users who have a specific permission. In my case the user has roles and roles have permissions, An user has never a direct permission. I tried the following code but i get a null result. There should be at least 1 User:

public function show($id)
    {
        $Permission = Permission::findOrFail($id);

        $userPermissions = $Permission->users()->get();

        dd($userPermissions);

    }

This works perfect on a Standard Laravel Auth System with web guard. But I have multiple guards (customer, user). Anybody an idea how to solve that problem?

**Comment by drbyte** [comment]
Each permission record in the database has a specific `guard_name` associated with it. 
Thus, to aggregate all relations for all guards will require looping through each permission record for the name+guard_name, and collecting the results.

Something akin to:
- retrieve all permission records: `$permissions = Permission::where('name', 'the name of the permission')->get();`
- loop through all the resulting `$permissions` records, grabbing the `->users` relation
- merge those relations into a collection, excluding duplicates
- use that collection as your list of users
