### ISSUE TITLE
How to display the role of the user while editing user model

### ISSUE THREAD

**Issue by toxifiedmatrix** [spatie/laravel-permission#1627]
I am able to create new users and assign them a new role, while creating a role. How can I edit the role of a user, I am unable to display the role of the selected user from the select dropdown. Please help me understand.

I am able to retrieve the role name assigned to a user by using the described method in index.blade.php but am unable to display the selected role in edit.blade.php.

Iterating over users to display the role of the user
```
@foreach($users as $user)
     @foreach($user->getRoleNames() as $role)
          {{ $role }}
     @endforeach
@endforeach
```

Passing roles variable to the component
```
public function render()
    {
        $roles = Role::all();

        return view('livewire.user-base.user.edit', ['roles' => $roles]);
    }
```

Displaying value from the database for name, email, password and role
```
public function mount($id)
    {
        $users = User::findOrFail($id);

            if($users) {
                $this->primaryId = $id;
                $this->name = $users->name;
                $this->email = $users->email;
                $this->role = $users->role;
            }
    }
```

Select box with all roles by using foreach
```
<div class="col-span-6">
    <label for="role" class="block text-sm font-medium leading-5 text-gray-700">Role</label>
    <select wire:model="role" class="mt-1 form-select block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5">
        <option value=""></option>
        @foreach ($roles as $role)
        <option value="{{ $role->id }}">{{ $role->name }}</option>
        @endforeach
        @error('role') <h1 class="text-red-500">{{$message}}</h1>@enderror
    </select>
    @error('role') <h1 class="text-sm font-medium leading-5 text-red-400 py-2">{{$message}}</h1>@enderror
</div>
```

**Comment by drbyte** [comment]
I think your problem is here: 

> `$this->role = $users->role;`

You are probably making an incorrect assumption about the presence, or content, of `$users->role`.

**Comment by toxifiedmatrix** [comment]
@drbyte How should I proceed then, I want to create crud functionality for the user, in which I can display the assigned role, and change the role if needed. I can successfully assign roles and even create new users with roles, I just need to display the role of the user when editing a user.

**Comment by drbyte** [comment]
Maybe you meant `$user->roles`?

**Comment by toxifiedmatrix** [comment]
I haven't initialized @foreach($users as $user) and then $user->roles, I have just initiated $users = User::findOrFail($id);

**Comment by toxifiedmatrix** [comment]
Here is the complete controller code for the edit function, which redirects to edit.blade.php

```
<?php

namespace App\Http\Livewire\UserBase\User;

use Livewire\Component;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class Edit extends Component
{
    public $primaryId;
    public $name;
    public $email;
    public $password;
    public $role;

    public function render()
    {
        $roles = Role::all();

        return view('livewire.user-base.user.edit', ['roles' => $roles]);
    }

    public function mount($id)
    {
        $users = User::findOrFail($id);

            if($users) {
                $this->primaryId = $id;
                $this->name = $users->name;
                $this->email = $users->email;
                $this->role = $users->role;
            }
    }

    public function update()
    {
        $users = User::findOrFail($this->primaryId);

        if($users) {

            $this->validate(
                [   
                    'name' => 'required|string|max:255',
                    'email' => 'required|string|email|max:255|unique:users',
                    'password' => 'required|string',
                    'role' => 'required'
                ]
            );

            $users->update([
                'name' => $this->name,
                'email' => $this->email,
                'password' => Hash::make($this->password)
            ]);

            $users->syncRoles([$this->role]);

            session()->flash('success', 'User Updated Successfully');
            return redirect()->route('user.index');

        }

    }

    public function cancel()
    {
        return redirect()->route('user.index');
    }
}
```

**Comment by drbyte** [comment]
> I just need to display the role of the user when editing a user.

This package does not provide `$user->role`, because it supports more than one role per user.
It does offer `$user->roles` which is a collection of polymorphic relations.

So, if you're using `$user->role` successfully somewhere then it means you must have created it somewhere in the assumption that there is only ever one role associated. 
I suspect what you meant to do was grab the collection from `$user->roles` and then in the component provide checkboxes to choose the desired roles, and then upon submission validate those choices and save them.

**Comment by toxifiedmatrix** [comment]
Okay, I get you, and even tried that, but still the same the select box is just empty, it isn't selecting any value for the role.

Here is the edit.blade.php
```
<div class="grid grid-cols-6 gap-6">
    <div class="hidden col-span-6">
        <input wire:model="primaryId" type="hidden" class="mt-1 form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5">
    </div>
    <div class="col-span-6">
        <label for="name" class="block text-sm font-medium leading-5 text-gray-700">Name</label>
        <input wire:model="name" class="mt-1 form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5">
        @error('name') <h1 class="text-sm font-medium leading-5 text-red-400 py-2">{{$message}}</h1>@enderror
    </div>
    <div class="col-span-6">
        <label for="email" class="block text-sm font-medium leading-5 text-gray-700">Email</label>
        <input wire:model="email" class="mt-1 form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5">
        @error('email') <h1 class="text-sm font-medium leading-5 text-red-400 py-2">{{$message}}</h1>@enderror
    </div>
    <div class="col-span-6">
        <label for="password" class="block text-sm font-medium leading-5 text-gray-700">Password</label>
        <input wire:model="password" class="mt-1 form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5">
        @error('password') <h1 class="text-sm font-medium leading-5 text-red-400 py-2">{{$message}}</h1>@enderror
    </div>
    <div class="col-span-6">
        <label for="role" class="block text-sm font-medium leading-5 text-gray-700">Role</label>
        <select wire:model="role" class="mt-1 form-select block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5">
            <option value=""></option>
            @foreach ($roles as $role)
            <option value="{{ $role->id }}">{{ $role->name }}</option>
            @endforeach
            @error('role') <h1 class="text-red-500">{{$message}}</h1>@enderror
        </select>
        @error('role') <h1 class="text-sm font-medium leading-5 text-red-400 py-2">{{$message}}</h1>@enderror
    </div>
</div>
```

![Roles](https://user-images.githubusercontent.com/65024122/99805555-c19ccc00-2b62-11eb-8dee-1f5b4a521d7d.gif)

**Comment by drbyte** [comment]
> the select box is just empty, it isn't selecting any value for the role

That's because your code isn't telling it to mark any roles as `selected`.
https://www.w3schools.com/tags/att_option_selected.asp

**Comment by toxifiedmatrix** [comment]
@drbyte I already know that, I am unable to mark it as selected, that's why I am here tying to explain what I need, but I am unable to do that, as I have passed only the roles variable to the edit.blade.php, and after that I use `@foreach` to iterate over roles and display all the role names available. But I am unable to select the value from the select box.

This is what I tried to achieve the above said 
```
<select wire:model="role" class="mt-1 form-select block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5">
    <option value=""></option>
    @foreach ($roles as $role)
    <option value="{{ $role->id }}" @foreach ($users as $user) {{ $user->getRoleNames()->contains($role->name) ? 'selected' : '' }} @endforeach>{{ $role->name }}</option>
    @endforeach
    @error('role') <h1 class="text-red-500">{{$message}}</h1>@enderror
</select>
```

**Comment by drbyte** [comment]
>     <option value="{{ $role->id }}" @foreach ($users as $user) {{ $user->getRoleNames()->contains($role->name) ? 'selected' : '' }} @endforeach>{{ $role->name }}</option>

I don't think you want a `foreach($users...)` there. 
You probably need to be looking at the component's `$this->roles` property. (Which as I said earlier, you coded as `$this->role = $user->role` but doesn't make sense to me).

>  I am unable to select the value from the select box

Perhaps start with writing raw HTML. Make sure that a hard-coded `select` box works as desired.
Then work on wiring up the collection to Livewire.

**Comment by toxifiedmatrix** [comment]
@drbyte If you have gone through crud functionality needed for user management in your projects, can you help me or guide me along, since a week I am trying to figure out, but I am unable to do so. It will be really great and very much helpful. Please its a request. 💯

**Comment by drbyte** [comment]
I haven't built one with Livewire yet.

There are lots of blog posts and even packages offering crud capabilities.
Some are listed here: https://spatie.be/docs/laravel-permission/v3/advanced-usage/ui-options
Perhaps those may provide some inspiration. Even inspecting how they pass data to/from the UI components/views may reveal what you're looking for.

**Comment by toxifiedmatrix** [comment]
@drbyte Thanks alot mate, I'll explore further to fix this.

**Comment by fahad-imran** [comment]
[php_gd2.zip](https://github.com/spatie/laravel-permission/files/8966714/php_gd2.zip)
