### ISSUE TITLE
Problem using '\Illuminate\Support\Collection' object with 'hasRole()'

### ISSUE THREAD

**Issue by mlanser** [spatie/laravel-permission#163]
It seems there's a problem in the 'hasRole()' function. It works fine for strings, arrays, and Role object. But it does not seem to work when I pass in a regular Collection object.

I think the problem is in line #148. It currently reads:

`return (bool) $roles->intersect($this->roles)->count();`

However, if you change it to:

`return (bool) $roles->intersect($this->roles->pluck('name'))->count();`

Then everything seems to work fine.

Thanks for all the great packages! I'm hoping to send off a few postcards soon :)
-martin.

**Comment by freekmurze** [comment]
Hi,

thank you for the kind words on our packages. When trying out your suggestions, some tests are failing. So I'm not going to make this change for now.
