### ISSUE TITLE
Use This Package for Pivot Table

### ISSUE THREAD

**Issue by annis-souames** [spatie/laravel-permission#1634]
I have many-to-many relationship (user-team), so a user can join multiple teams and a team can have multiple users, at first I was  adding permissions only in team model, but I need to add it in team-user pivot table through this package, so a user can have different permissions for each team he has joined ? Any Ideas how can I achieve this.

**Comment by bhushan** [comment]
facing same kind of issue ..

**Comment by brandon-9** [comment]
Crude, and early, but I have the same situation. I created a "teamAccess" model/table to store the roles.
id | team_id | user_id

I check the active team (team ID 1) stored on the User table, then going through the team, I find the teamAccess where team_id = user_active_team_id

User Model:
public function teamAccess()
    {
        return $this->hasMany(TeamAccess::class);
    }
    
    
   Then I have a Policy with a condition:
   $user->teamAccess()->where('team_id', $user->team_id)->first()->hasPermissionTo('create')
   
   
Might get you somewhere...

**Comment by sys-auditing** [comment]
Hi @annis-souames, did you figure out the solution ?

**Comment by Hesesses** [comment]
I'm working on something similar deciding between this package or creating something custom...

Could this be handled with subparts?
https://spatie.be/docs/laravel-permission/v4/basic-usage/wildcard-permissions#subparts

`$user->givePermissionTo('posts.*.1,4,6');` 

You would specify the wanted team_ids
