### ISSUE TITLE
Direct permissions

### ISSUE THREAD

**Issue by kvovadis** [spatie/laravel-permission#1637]
Hello,
I was wondering if it is possible to use direct permission along with roles permissions at once. I am trying to achieve that if I set direct permissions, roles permissions will be overridden.
Thanks in advance.
Mark

**Comment by drbyte** [comment]
You can check direct permissions using various methods. Some of those include:

`hasDirectPermission`
`hasAllDirectPermissions`
`hasAnyDirectPermission`
`getDirectPermissions`
`getPermissionsViaRoles`
`getAllPermissions`

They are explained here: https://spatie.be/docs/laravel-permission/v3/basic-usage/role-permissions

**Comment by kvovadis** [comment]
Thank you for response. Yes of course i know how to get them but problem is that when i use @can in blade it is chcecking All permissions not just Direct or roles. I want to set which permissions should use for each user specificaly.

**Comment by drbyte** [comment]
The replacement for `@can` in Blade, when checking a **Direct** permission, would be:

```blade
@if(auth()->check() && auth()->user()->hasDirectPermission('permission-name or permission-object'))

@endif
```

**Comment by kvovadis** [comment]
Okay.. so it is not possible to use it with @can ?

**Comment by drbyte** [comment]
The `@can` directive operates in conjunction with all the user's permissions both direct and via roles.

If you want to only check Direct permissions, regardless of whether their role already includes it, then you'll need to use the approach above.
