### ISSUE TITLE
Potential problem in 'hasPermissionViaRole()'

### ISSUE THREAD

**Issue by mlanser** [spatie/laravel-permission#164]
It seems that there's a problem in '_hasPermissionViaRole()_' when one changes '_hasRole()_' to accept standard _Collection_ objects (see issue [#163](https://github.com/spatie/laravel-permission/issues/163) opened by me).

'_hasPermissionViaRole()_' currently reads as follows:

```
    protected function hasPermissionViaRole(Permission $permission)
    {
        return $this->hasRole($permission->roles);
    }
```
However, '_$permission->roles_' appears to be a collection of _Role_ objects and that won't work in '_hasRole()_' if we change it to accept standard _Collection_ objects. But this can be fixed as follows:

```
   protected function hasPermissionViaRole(Permission $permission)
    {
        return $this->hasRole($permission->roles->all());
    }
```

These are just suggestions and I have only done rudimentary testing. 

TIA,
-martin.

**Comment by freekmurze** [comment]
Thank you for your suggestion.

It seems that the current implementation is fine as it is. 

If you feel there is an error, please submit a failing test.
