### ISSUE TITLE
Same user with two roles act different depending on login endpoint?

### ISSUE THREAD

**Issue by Dredas** [spatie/laravel-permission#1641]
Hi, I have two options to log in to the same user - with a regular password and with a simple pin. I want to restrict the user who connects by the pin so he can't do a bunch of things. What would be the best solution?

**Comment by drbyte** [comment]
I'm not sure how this package applies to that situation. This package provides an api around role and permission objects associated with user model objects.

Your situation sounds like something where you simply need to determine what mode the user logged in with during authentication and maybe set some session flag or other value that the rest of your app can check as needed.
