### ISSUE TITLE
Cannot use @can or permission middleware with role permissions

### ISSUE THREAD

**Issue by gaghigogu** [spatie/laravel-permission#1642]
Hello,

I have some troubles using middleware to check user permissions on a given route or the @can blade directive.

Let's say user has role "writer" and this role has permission to "write post". Now, if I use the RoleMiddleware to check if user can use that route:

Route::view("/post/create", "my.view.here")->middleware('role:writer');

everything works as I understand it should.

But if I use the PermissionMiddleware:

Route::view("/post/create", "my.view.here")->middleware('permission:write post');

It redirects to 403 "User does not have any of the necessary rights"

Now, if I assign the permission "write post" directly to the user (as a direct permission):

$user->givePermissionTo('write post');

everything works

It seems like permission middleware and @can directive (or auth()->user()->can(..)) only checks direct permissions. As far as I understand reading the docs all permissions should be checked. 

Am I missing something? 

Thanks in advance for the great work.

**Comment by drbyte** [comment]
You are correct that it (both the middleware via `->can()`, and the `@can` directive) tests all permissions, not just direct permissions.

I just added a [test](https://github.com/spatie/laravel-permission/commit/3951ef5c362914a18323b6d9507faf859392186a) to the test suite to demonstrate and confirm this.
