### ISSUE TITLE
[Info] Can we integrate laravel-permission with some JWT login package?

### ISSUE THREAD

**Issue by realtebo** [spatie/laravel-permission#1644]
Context of this question is a Vue Spa app where we can have different profiles (roles) of logged users

Laravel server-side is an API ONLY project. We must handle login/registrations.

Having a vue spa we'd like to use jwt to handle login and your package to handle RBAC

Is there any package for jwt you can suggest use to use with this excellent package?

**Comment by drbyte** [comment]
While this package offers some view-related helpers, it is front-end agnostic.

In your app you can use this package's Authorization features once your jwt authentication is completed.
