### ISSUE TITLE
Get Role Id assingned to user

### ISSUE THREAD

**Issue by Tayyabshahzad** [spatie/laravel-permission#1645]
Hi,
I have a list of my all roles and a list of my users. When I use ($users->roles) it returns me all details but I just need role id when I use  $users->roles->pluck('id') this returns me user is too but this id is in curly braces like  [3]. just need an integer value like 3

**Comment by drbyte** [comment]
In one-to-many and many-to-many relations, the result of an Eloquent relation such as `$user->roles` is a collection.

A user can have **more than one** role.

If you want only the **first** role's ID as an integer, then you can simply access it as a property:

`$user->roles->first()->id`
