### ISSUE TITLE
Laravel Breez and Spatie Permissions set role while user registered

### ISSUE THREAD

**Issue by devhoussam** [spatie/laravel-permission#1648]
I'm using **laravel Breez** as Auth scaffolding package by laravel.

I have created two registration forms one for **"Writer"** and other for **"Publisher"** 
 all registration views are located in **RegisteredUserController**

**app\Http\Controllers\Auth\RegisteredUserController.php**

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\Frontend\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class RegisteredUserController extends Controller
{
    /**
     * Display the registration view for writer.
     *
     * @return \Illuminate\View\View
     */
    public function createWriter()
    {
        return view('auth.writer.writer-space');
    }
    
    /**
     * Display the registration view for publisher.
     *
     * @return \Illuminate\View\View
     */
    public function createPublisher()
    {
        return view('auth.publisher.publisher-space');
    }

    /**
     * Handle an incoming registration request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|confirmed|min:8',
        ]);

        Auth::login($user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]));

        event(new Registered($user));

        return redirect(RouteServiceProvider::HOME);
    }
}
```

as you can see in this controller I have two registration view for two type of users **"Writer"** and **"Publisher"**.

What I want to do is to Set the role of the users while registration based on this two types **"Writer"** and **"Publisher"** Roles.

**app\routes\auth.php**

```
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\RegisteredUserController;

Route::get('/publisher-space', [RegisteredUserController::class, 'createPublisher'])->middleware('guest')->name('publisher-space');

Route::get('/writer-space', [RegisteredUserController::class, 'createWriter'])->middleware('guest')->name('writer-space');
```

**Comment by drbyte** [comment]
I'm not sure what you're asking for.

Your `store()` method appears to be identical for both publishers and writers. There's nothing determining what kind of user you are creating.
That's logic you need to build into your application.

Then, after you've determined what kind of user you are creating in your `store()` method, you can assign the appropriate role. You might do that directly inside the `store()` method, or you might hook into the `Registered($user)` event to do the role assignment there.

**Comment by devhoussam** [comment]
> I'm not sure what you're asking for.
> 
> Your `store()` method appears to be identical for both publishers and writers. There's nothing determining what kind of user you are creating.
> That's logic you need to build into your application.
> 
> Then, after you've determined what kind of user you are creating in your `store()` method, you can assign the appropriate role. You might do that directly inside the `store()` method, or you might hook into the `Registered($user)` event to do the role assignment there.

Can you explain with example please

**Comment by drbyte** [comment]
First, start with picking ONE kind of user, and make THAT work:
- Pick the Student scenario
- ensure the form allows student user input and submission
- controller receives form submission and creates student user, and assigns student role, and redirects to desired view

Repeat for Instructor scenario, by cloning your views and controller, and updating your routes and form-actions to submit to the proper controller.  

With separate controllers/routes/views, you always know what kind of user-submission you have, and you can add additional security around each when needed.

You probably should set something in your forms to differentiate between the kind of user that is being registered, perhaps a hidden field of some sort. Be aware that the end-user could tamper with that value.

**Comment by devhoussam** [comment]
please read this well : 

<strong>*** Scenario 1 ***</strong>

<strong>let try that I visit Udemy E-learning platform and I prefer to Create an account as "INSTRUCTOR" after complete the registration with specified fields it should redirect me to specified dashboard made only for this type of users.</strong>

<strong>*** Scenario 2 ***</strong>

<strong>let try that I visit Udemy E-learning platform and I prefer to Create an account as "STUDENT" after complete the registration with specified fields it should redirect me to specified dashboard made only for this type of users.</strong>

<strong>*** Here is my updated code ***</strong>

<strong>*** RegisteredUserController ***</strong>

```
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|confirmed|min:8',
        ]);

        Auth::login($user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]));
		
		
		$studentRole = Role::create(['name' => 'student']);
		$instructorRole = Role::create(['name' => 'instructor']);
		
		
		$user->assignRole($studentRole);
		$user->assignRole($instructorRole);
		
		
		if(auth()->user()->getRoleNames() && auth()->user()->hasRole('student')) {
			return redirect()->intended('/student/dashboard');
		} else if (auth()->check() && !auth()->user()->hasRole('student')) {
			return redirect()->back();
		}
		
		if(auth()->user()->getRoleNames() && auth()->user()->hasRole('instructor')) {
			return redirect()->intended('/instructor/dashboard');
		} else if (auth()->check() && !auth()->user()->hasRole('instructor')) {
			return redirect()->back();
		}
		
		event(new Registered($user));
    }
```

<strong>*** AuthenticatedSessionController ***</strong>

```
    public function store(LoginRequest $request)
    {
        $request->authenticate();

        $request->session()->regenerate();
		
		if(auth()->check() && auth()->user()->hasRole('student')) {
			return redirect()->intended('/student/dashboard');
		}
		
		if(auth()->check() && auth()->user()->hasRole('instructor')) {
			return redirect()->intended('/instructor/dashboard');
		}
		
		return redirect(RouteServiceProvider::HOME);
    }
```

**Comment by drbyte** [comment]
Stop.

Go back and read my last post.

First, get it working for a Student user. 
Presently your app won't work for either user, because:
- your form isn't specifying which kind of user you are creating (whether via a user-specific controller action, or a hidden field)
- and your Controller isn't granting roles based on what kind of user submitted the form, because it isn't checking what kind of user is submitted

(It's creating new Roles every time, and granting both roles to every user.)

Deal with the "redirect to desired page" **after** you have it working to register a user and grant only the correct role.
