### ISSUE TITLE
Method saveMany does not exist.

### ISSUE THREAD

**Issue by seeya** [spatie/laravel-permission#165]
I'm trying to implement this with https://github.com/Parziphal/parse

When I do 
```
$user = Auth::user();
$user->givePermissionTo('create post');
```
I get an error 
`BadMethodCallException in Macroable.php line 74:
Method saveMany does not exist.`

I'm sure the $user is instantiated as it returns an object. The tables are also created in mysql database. 
Any ideas?

**Comment by drbyte** [comment]
Have you run the command to make the permission first? It must be in the db in order to be granted:

`Permission::create(['name' => 'create post']);`

**Comment by seeya** [comment]
Hey @drbyte,
Yes I have ran that function before. I've also double checked that the row was created in the db.
I also tried running the 2 commands together but it still gives the same error.
```
Permission::create(['name' => 'create post']);
$user->givePermissionTo('create post');
```

**Comment by drbyte** [comment]
Ya. In this case `$user` needs to  be of an object that extends the Eloquent relation features of BelongsToMany, etc, which shares things from collections too. Those are what provide the `saveMany` capability.

**Comment by seeya** [comment]
Thanks for pointing out that. If that is the case I would need to create my own custom way of handling roles and permission.
