### ISSUE TITLE
Empty roles and permissions for all Users after updating and running RolesAndPermissionsSeeder

### ISSUE THREAD

**Issue by ndethi** [spatie/laravel-permission#1650]
I updated `RolesAndPermissionsSeeder` after a change in req spec on how some users should interact with app. I ran `db:seed --class RolesAndPermissionsSeeder`

Now all users have empty `roles` and `permissions` arrays. There is no longer action authorisation in the app. How do i re-register users with their roles and permissions? 

I have tried `artisan cache clear`, `optimize`, `permissions cache-reset` to no avail.

**Comment by drbyte** [comment]
You didn't post code for your seeder. 
I'm guessing that your seeder deletes existing roles and permissions before recreating them?

When you delete roles and permissions from the database, all the relationships that were previously established are forever broken. That's how database foreign-key relationships work.

**Comment by ndethi** [comment]
@drbyte Yes the beginning of the seeder looks like this: 

       `Schema::disableForeignKeyConstraints();
        DB::table('permissions')->truncate();
        DB::table('roles')->truncate();
        DB::table('role_has_permissions')->truncate();
        DB::table('model_has_permissions')->truncate();
        DB::table('model_has_roles')->truncate()`

So true the existing roles and permissions tables are truncated. I overlooked the fact that the foreign key relations will now be forever broken. 

Having established this then, what would be the best course of action going forward to restore roles and permissions for all users?

Thank you.

**Comment by ndethi** [comment]
Thank  you, I reseeded the 5 roles and permissions tables and the users table too - since i am testing locally i just did a global `db:seed`. Now the foreign key relationships have been reestablished and the users have their roles and permissions back.

For production, i did a standalone seeder (intended for single use) that gets the guest role then givesPermissionsTo (new permissions) to that guest role. I removed the truncation of the tables and `disableForeignKeyConstraints`.

I can use a migration instead of a seeder for table data?

**Comment by drbyte** [comment]
> I can use a migration instead of a seeder for table data?

Yes, migrations can run PHP code, SQL queries, etc. Beyond just creating tables, you can insert data, rearrange table data, make updates, and more.

Migrations are the correct way to apply database updates to production.
