### ISSUE TITLE
Determine if gate is a permission search

### ISSUE THREAD

**Issue by Jefemy** [spatie/laravel-permission#1651]
I want to define a role that bypasses all existing permissions, but only for permissions and not the policies I have setup. Right now I am just checking if the Gate passes any arguments and assumes its a laravel-permission value if it doesn't but this would stop working if I ever used a policy that didn't want any arguments. Is there a proper way to do it?

**Comment by drbyte** [comment]
Hmmm...

If your "role that bypasses all existing permissions" is using a Gate::before rule then part of your logic where you define that Gate::before rule could check whether the permission string "is" a permission (eg: perhaps Permission::findByName).

Or maybe explore Laravel's Gate::after feature to append extra logic checking.

**Comment by Jefemy** [comment]
Realized that all policies pass at least one argument so I can just count that array and I can use `array_key_exists($ability, Gate::abilities())` to determine if it was defined as a gate. I can use both of those to reasonable determine if it should be counted as a permission. Thanks for the help.
