### ISSUE TITLE
Revoking all roles & or revoking all permissions

### ISSUE THREAD

**Issue by muh-hizbe** [spatie/laravel-permission#1653]
i have a case,
when updating user with **array** of roles or permissions, will be syncPermissions($array) or syncRoles($array),
but when updating user with **empty array** of roles or permissions, will be revoke all of them. How to solve it?

Sample code:
```php
$user->removeRoles();
$user->revokePermission()
```

Expectation result:
```php
$user->getAllPermissions();
// result;
// null or []

$user->getRoleNames();
// result;
// null or []
```

**Comment by drbyte** [comment]
I'm not sure I understand your question.

This package has no `$user->removeRoles()` or `$user->revokePermission()` methods.

Why are you syncing an empty array?

**Comment by muh-hizbe** [comment]
Okkay, solved with syncing an empty array. 
Thanks.
