### ISSUE TITLE
Problem with escaped backslash (\) in a mysql query (HasRoles)

### ISSUE THREAD

**Issue by Nino1976** [spatie/laravel-permission#1655]
Hi,
there is a problem with the following mysql query and escape backslash.
... `model_has_roles`.`model_type` = 'App\Models\User' (does not return anything)
... `model_has_roles`.`model_type` = 'App\\\Models\\\User' (correct return)

query (\vendor\spatie\laravel-permission\src\Traits\HasRoles.php:185):
select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = 1 and `model_has_roles`.`model_type` = 'App\Models\User'

system: PHP 7.4.1, laravel v8.21.0, spatie 3.17.0

hope you can solve this, thank you :-)

**Comment by drbyte** [comment]
That query is generated by Laravel Eloquent directly, not by code specific to this package.

This suggests something wrong in your app. 
Or perhaps you've manually inserted data into the database tables instead of letting Laravel do it itself?

**Comment by alinrzv** [comment]
Open 
/vendor/spatie/laravel-permission/src/Models/Role.php 

Change: 

```
        if (is_string($permission)) {
            $permission = $permissionClass->findByName($permission, $this->getDefaultGuardName());
        }
```

TO 

```
        if (is_string($permission)) {
            $permission = $permissionClass->findByName($permission, $this->getDefaultGuardName());
            if(preg_match('/\\/is',$permission)){
            $permission = str_replace('\\','\\\\',$permission);
            }
        }
```

If this saved your time , donate paypal , it took me 3 hours to find and fix issue : alin[dot]rzv@gmail[dot]com

Cheers !
