### ISSUE TITLE
Define DB Connection

### ISSUE THREAD

**Issue by sitesurfer** [spatie/laravel-permission#1657]
Apologies for the double post.
I note that there is no definition of database config available such as in the logging package.

At the moment I have placed a setConnection() into the package - but this would be deleted on a package update.

Not a bug - asking if possible to have it added. (Thank you)

**Comment by drbyte** [comment]
Years ago I explored that, but Freek pointed out that it's simpler to just extend the Models and set the `$connection` property.

That's worked great for the projects where I needed it (especially multi-db-multi-tenancy).

Is there a use-case where that wouldn't be sufficient?

**Comment by AColes** [comment]
Hope I'm not off-topic here, ... I'm finding the addition of $connection is not enough.

I have a multi-tenancy installation (custom built - not MT package)
I'm moving users from 'main' into tenant DB's - previously all users & permissions handled in 'main'.

Users, roles and permissions create OK in tenant (all have $connection set to 'tenant' and role & permissions config has alternate models ),  but assigning role throws 'RoleDoesNotExist' ... as it's looking in the 'main' DB.

Am I over-reaching, trying to manage roles and permissions in tenant DB's?

Any insight appreciated.

**Comment by drbyte** [comment]
Here is the code I had explored using back then. You can see that it ends up basically just re-creating the `$connection` stuff that Laravel provides already (and which I didn't understand well myself yet back then).
https://github.com/spatie/laravel-permission/pull/719

**Comment by sitesurfer** [comment]
Thank you- I have implemented this via class extension and it is perfect.
