### ISSUE TITLE
Table Key Length issue under utf8mb4/Mysql 5.5

### ISSUE THREAD

**Issue by BinaryKitten** [spatie/laravel-permission#1671]
During an upgrade/refresh of our database from utf8/latin fields to utf8mb4 (proper utf8) we encountered an error in the migration.

Laravel's default length for string based columns is 255 characters and under collation/charset utf8mb4 with mysql 5.5, there is a limit on key sizes to 767 bytes. 
With character length of 255 * 4 bytes per character > 767 bytes as such, migration fails with the errors:

```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `permissions` add unique `permissions_name_guard_name_unique`(`name`, `guard_name`))
```
```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `roles` add unique `roles_name_guard_name_unique`(`name`, `guard_name`))
``` 
```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `model_has_permissions` add primary key `model_has_permissions_permission_model_type_primary`(`permission_id`, `model_id`, `model_type`))
```
```
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `model_has_roles` add primary key `model_has_roles_role_model_type_primary`(`role_id`, `model_id`, `model_type`))
```

The `roles` and `permissions` tables have 2 string columns `name` and `guard_name`
and the `model_type` column on the `model_has_permissions` and `model_has_roles` tables both have no length, thus defaulting to 255 characters and triggering the above error at database layer.

Unsure of the correct method here to fix across multiple platforms, but in our system, we've imposed a character limit of 190 characters (190 * 4bytes = 760 bytes),

**Comment by drbyte** [comment]
Is there something forcing you to stay on MySQL 5.5 (which stopped being updated or supported in 2018)?

I haven't run into these errors on 5.7 or 8.0 and Laravel 7 or 8.

**Comment by BinaryKitten** [comment]
@drbyte - hi, 

yep, there is a something that is preventing us from jumping MySQL versions, though the work for that is planned and underway (legacy code, slow upgrade of site etc).

MySQL 5.7 does increase the key limit from 767bytes to 3072bytes - which does prevent the issue, but ultimately, since this package has no minimum MySQL requirements I'd thought to come share/report the issue I had.. 

I thought that maybe a documentation note could be added (the 190 column size) and limitations noted under MySQL 5.5 - and that it would be in best interests to update to MySQL 5.7 or 8.

**Comment by drbyte** [comment]
Laravel's docs already address this: 
https://laravel.com/docs/8.x/migrations#index-lengths-mysql-mariadb

You could use those suggestions, or you could manually update the migrations this package gave you to accommodate the limitations of your older dependencies.
