### ISSUE TITLE
How can to check permission in http test? 

### ISSUE THREAD

**Issue by Camelia2020** [spatie/laravel-permission#1672]
Hello. 
I'm writing the http test. In the case of middleware, my request is as follows:

`$response = $this->actingAs($user)->get('show/' . $class->id);` 

But I also want to check permission in the test. That means the user is not an admin. How can I change this line of code to check the user permission?

**Comment by drbyte** [comment]
There is nothing special about this package in terms of testing.

As with any test, you would have the test check for a certain expected or desired response.

Ask yourself these questions, and take appropriate action:

What is supposed to happen if the user has permission? Test for that. Perhaps certain text in the response? Or maybe a 403 status code triggered by middleware or by a model policy?

And if they do not have the required permission? Test also for that. Perhaps the object's name should be in the response?
