### ISSUE TITLE
1071 Specified key was too long

### ISSUE THREAD

**Issue by JustinRijsdijk** [spatie/laravel-permission#1689]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/laravel-persmission/issues) or in [the discussions](https://github.com/spatie/laravel-permission/discussions).

**Describe the bug**
After adding `Schema::defaultStringLength(191);` to ApServiceProvider I run into this error when migrating

`Migrating: 2021_02_23_202702_create_permission_tables

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `permissions` add unique `permissions_name_guard_name_unique`(`name`, `guard_name`))   

  at D:\PROJECT\vendor\laravel\framework\src\Illuminate\Database\Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

  1   D:\PROJECT\vendor\laravel\framework\src\Illuminate\Database\Connection.php:471
      PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes")
key length is 1000 bytes")

  2   D:\PROJECT\vendor\laravel\framework\src\Illuminate\Database\Connection.php:471
      PDOStatement::execute()
`
**Versions**
- spatie/laravel-permission 4.0.0   Permission handling for Laravel 6.0 and up
- laravel/framework v8.24.0 The Laravel Framework.

PHP version:
  PHP 7.3.21 (cli) (built: Aug  4 2020 11:21:19) ( ZTS MSVC15 (Visual C++ 2017) x64 )
  Copyright (c) 1997-2018 The PHP Group
  Zend Engine v3.3.21, Copyright (c) 1998-2018 Zend Technologies
**To Reproduce**
1. Install a new laravel 8 project
2. Change `Schema::defaultStringLength(191);` in AppServiceProvider
2. Follow the installation steps for this package
3. When trying to migrate (as following the docs) it errors out.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 1909 Build:18363.1379

**Comment by drbyte** [comment]
What database version?

You're encountering this in Windows on your local PC. 
What database version will the server be using for your production app?

**Comment by JustinRijsdijk** [comment]
at this moment it is Mysql 8.0.4 Production wil differ as clients will install it themselves on their own servers. I'll write some good docs for that tho, so they will use the right version.

**Comment by JustinRijsdijk** [comment]
changed to MariaDB 10.5.4 all works fine now, closing this issue

**Comment by InfiniteCoder96** [comment]
> changed to MariaDB 10.5.4 all works fine now, closing this issue

Why is this not working on MySQL?

**Comment by hernandoglobal** [comment]
I have the same problem, I could not find a solution.

**Comment by drbyte** [comment]
**Solution:**
- On MySQL 8.0 use `defaultStringLength(125)`
- On MariaDB you don't need to set anything special because it natively supports longer index keys automatically.

**Technical explanation:**
The Laravel docs suggest using an override of `defaultStringLength(191)`, but that was not accounting for multi-column indexes.

Laravel's `defaultStringLength` is 255 unless overridden in your AppServiceProvider:
https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Builder.php#L35-L70

The `string()` field type uses a length specified in the migration if present, or defaults to `defaultStringLength`:
https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Blueprint.php#L666-L678

MariaDB 10.5 allows index keys to be 3072 chars.
Your MySQL 8.0 appears to be allowing only 1000 chars.

By "characters" it means "storage bytes".

Each mb4 "character" requires 4 bytes to store it.

The Unique Indexes this package's [migration](https://github.com/spatie/laravel-permission/blob/6a66dea9af1712e9e457f1a38a98f2013d9f012d/database/migrations/create_permission_tables.php.stub#L25-L29) is creating are hybrid (multi-column) indexes on `name, guard_name`.
So if those fields are 125 characters long, using mb4 means 125*4 = 500,
and the combination of to columns in one index means 500+500=1000, which is MySQL 8.0's limit.
But if they're longer than 125 each then MySQL 8.0 will reject it. MariaDB is more versatile in this area.

Therefore on MySQL 8.0 using `defaultStringLength(125)` should solve it.

**Comment by imranemi143** [comment]
> **Solution:**
> 
> * On MySQL 8.0 use `defaultStringLength(125)`
> * On MariaDB you don't need to set anything special because it natively supports longer index keys automatically.
> 
> **Technical explanation:**
> The Laravel docs suggest using an override of `defaultStringLength(191)`, but that was not accounting for multi-column indexes.
> 
> Laravel's `defaultStringLength` is 255 unless overridden in your AppServiceProvider:
> https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Builder.php#L35-L70
> 
> The `string()` field type uses a length specified in the migration if present, or defaults to `defaultStringLength`:
> https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Blueprint.php#L666-L678
> 
> MariaDB 10.5 allows index keys to be 3072 chars.
> Your MySQL 8.0 appears to be allowing only 1000 chars.
> 
> By "characters" it means "storage bytes".
> 
> Each mb4 "character" requires 4 bytes to store it.
> 
> The Unique Indexes this package's [migration](https://github.com/spatie/laravel-permission/blob/6a66dea9af1712e9e457f1a38a98f2013d9f012d/database/migrations/create_permission_tables.php.stub#L25-L29) is creating are hybrid (multi-column) indexes on `name, guard_name`.
> So if those fields are 125 characters long, using mb4 means 125*4 = 500,
> and the combination of to columns in one index means 500+500=1000, which is MySQL 8.0's limit.
> But if they're longer than 125 each then MySQL 8.0 will reject it. MariaDB is more versatile in this area.
> 
> Therefore on MySQL 8.0 using `defaultStringLength(125)` should solve it.

Thank you ! working

**Comment by dbrax** [comment]
> **Solution:**
> 
> * On MySQL 8.0 use `defaultStringLength(125)`
> * On MariaDB you don't need to set anything special because it natively supports longer index keys automatically.
> 
> **Technical explanation:**
> The Laravel docs suggest using an override of `defaultStringLength(191)`, but that was not accounting for multi-column indexes.
> 
> Laravel's `defaultStringLength` is 255 unless overridden in your AppServiceProvider:
> https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Builder.php#L35-L70
> 
> The `string()` field type uses a length specified in the migration if present, or defaults to `defaultStringLength`:
> https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Blueprint.php#L666-L678
> 
> MariaDB 10.5 allows index keys to be 3072 chars.
> Your MySQL 8.0 appears to be allowing only 1000 chars.
> 
> By "characters" it means "storage bytes".
> 
> Each mb4 "character" requires 4 bytes to store it.
> 
> The Unique Indexes this package's [migration](https://github.com/spatie/laravel-permission/blob/6a66dea9af1712e9e457f1a38a98f2013d9f012d/database/migrations/create_permission_tables.php.stub#L25-L29) is creating are hybrid (multi-column) indexes on `name, guard_name`.
> So if those fields are 125 characters long, using mb4 means 125*4 = 500,
> and the combination of to columns in one index means 500+500=1000, which is MySQL 8.0's limit.
> But if they're longer than 125 each then MySQL 8.0 will reject it. MariaDB is more versatile in this area.
> 
> Therefore on MySQL 8.0 using `defaultStringLength(125)` should solve it.

Working fine thank you for this solution ! 🔥 💯

**Comment by arif98741** [comment]
> > **Solution:**
> > 
> > * On MySQL 8.0 use `defaultStringLength(125)`
> > * On MariaDB you don't need to set anything special because it natively supports longer index keys automatically.
> > 
> > **Technical explanation:**
> > The Laravel docs suggest using an override of `defaultStringLength(191)`, but that was not accounting for multi-column indexes.
> > Laravel's `defaultStringLength` is 255 unless overridden in your AppServiceProvider:
> > https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Builder.php#L35-L70
> > The `string()` field type uses a length specified in the migration if present, or defaults to `defaultStringLength`:
> > https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Blueprint.php#L666-L678
> > MariaDB 10.5 allows index keys to be 3072 chars.
> > Your MySQL 8.0 appears to be allowing only 1000 chars.
> > By "characters" it means "storage bytes".
> > Each mb4 "character" requires 4 bytes to store it.
> > The Unique Indexes this package's [migration](https://github.com/spatie/laravel-permission/blob/6a66dea9af1712e9e457f1a38a98f2013d9f012d/database/migrations/create_permission_tables.php.stub#L25-L29) is creating are hybrid (multi-column) indexes on `name, guard_name`.
> > So if those fields are 125 characters long, using mb4 means 125*4 = 500,
> > and the combination of to columns in one index means 500+500=1000, which is MySQL 8.0's limit.
> > But if they're longer than 125 each then MySQL 8.0 will reject it. MariaDB is more versatile in this area.
> > Therefore on MySQL 8.0 using `defaultStringLength(125)` should solve it.
> 
> Thank you ! working

Thanks for saving my time. I use 125 string length. And its finally working.

**Comment by aldyrifaldi** [comment]
> **Solution:**
> 
> * On MySQL 8.0 use `defaultStringLength(125)`
> * On MariaDB you don't need to set anything special because it natively supports longer index keys automatically.
> 
> **Technical explanation:** The Laravel docs suggest using an override of `defaultStringLength(191)`, but that was not accounting for multi-column indexes.
> 
> Laravel's `defaultStringLength` is 255 unless overridden in your AppServiceProvider: https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Builder.php#L35-L70
> 
> The `string()` field type uses a length specified in the migration if present, or defaults to `defaultStringLength`: https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Blueprint.php#L666-L678
> 
> MariaDB 10.5 allows index keys to be 3072 chars. Your MySQL 8.0 appears to be allowing only 1000 chars.
> 
> By "characters" it means "storage bytes".
> 
> Each mb4 "character" requires 4 bytes to store it.
> 
> The Unique Indexes this package's [migration](https://github.com/spatie/laravel-permission/blob/6a66dea9af1712e9e457f1a38a98f2013d9f012d/database/migrations/create_permission_tables.php.stub#L25-L29) is creating are hybrid (multi-column) indexes on `name, guard_name`. So if those fields are 125 characters long, using mb4 means 125*4 = 500, and the combination of two columns in one index means 500+500=1000, which is MySQL 8.0's limit. But if they're longer than 125 each then MySQL 8.0 will reject it. MariaDB is more versatile in this area.
> 
> Therefore on MySQL 8.0 using `defaultStringLength(125)` should solve it.

Thank you, it worked for me

**Comment by learnkitir** [comment]
> * 125

Thank You
This solution works

**Comment by minkaleno** [comment]
> **Solution:**
> 
> * Sur MySQL 8.0, utilisez`defaultStringLength(125)`
> * Sur MariaDB, vous n'avez pas besoin de définir quoi que ce soit de spécial car il prend automatiquement en charge de manière native les clés d'index plus longues.
> 
> **Explication technique :** la documentation Laravel suggère d'utiliser un remplacement de `defaultStringLength(191)`, mais cela ne tenait pas compte des index multi-colonnes.
> 
> Celui de Laravel `defaultStringLength`est 255, sauf remplacement dans votre AppServiceProvider : https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Builder.php#L35-L70
> 
> Le `string()`type de champ utilise une longueur spécifiée dans la migration si elle est présente, ou est par défaut`defaultStringLength` : https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Blueprint.php#L666-L678
> 
> MariaDB 10.5 autorise les clés d'index à 3072 caractères. Votre MySQL 8.0 semble autoriser seulement 1 000 caractères.
> 
> Par « caractères », cela signifie « octets de stockage ».
> 
> Chaque "caractère" mb4 nécessite 4 octets pour le stocker.
> 
> Les index uniques créés par [la migration](https://github.com/spatie/laravel-permission/blob/6a66dea9af1712e9e457f1a38a98f2013d9f012d/database/migrations/create_permission_tables.php.stub#L25-L29)`name, guard_name` de ce package sont des index hybrides (multi-colonnes) sur . Ainsi, si ces champs comportent 125 caractères, l'utilisation de mb4 signifie 125*4 = 500, et la combinaison de deux colonnes dans un index signifie 500+500=1000, ce qui est la limite de MySQL 8.0. Mais s'ils dépassent 125 chacun, MySQL 8.0 le rejettera. MariaDB est plus polyvalente dans ce domaine.
> 
> Par conséquent, sur MySQL 8.0, l'utilisation `defaultStringLength(125)`devrait le résoudre.



> **Solution:**
> 
> * On MySQL 8.0 use `defaultStringLength(125)`
> * On MariaDB you don't need to set anything special because it natively supports longer index keys automatically.
> 
> **Technical explanation:** The Laravel docs suggest using an override of `defaultStringLength(191)`, but that was not accounting for multi-column indexes.
> 
> Laravel's `defaultStringLength` is 255 unless overridden in your AppServiceProvider: https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Builder.php#L35-L70
> 
> The `string()` field type uses a length specified in the migration if present, or defaults to `defaultStringLength`: https://github.com/laravel/framework/blob/f4c0819d35d88c9ca900cfc07aa05b1179478a6c/src/Illuminate/Database/Schema/Blueprint.php#L666-L678
> 
> MariaDB 10.5 allows index keys to be 3072 chars. Your MySQL 8.0 appears to be allowing only 1000 chars.
> 
> By "characters" it means "storage bytes".
> 
> Each mb4 "character" requires 4 bytes to store it.
> 
> The Unique Indexes this package's [migration](https://github.com/spatie/laravel-permission/blob/6a66dea9af1712e9e457f1a38a98f2013d9f012d/database/migrations/create_permission_tables.php.stub#L25-L29) is creating are hybrid (multi-column) indexes on `name, guard_name`. So if those fields are 125 characters long, using mb4 means 125*4 = 500, and the combination of two columns in one index means 500+500=1000, which is MySQL 8.0's limit. But if they're longer than 125 each then MySQL 8.0 will reject it. MariaDB is more versatile in this area.
> 
> Therefore on MySQL 8.0 using `defaultStringLength(125)` should solve it.

Super, ça marche !

**Comment by kkraju4u** [comment]
This issue does not affect in MySQL 8.0 with Row format Dynamic or Compressed.

But as per the [prerequisites](https://spatie.be/docs/laravel-permission/v6/prerequisites#content-schema-limitation-in-mysql) in the official documentation, setting default length as 125 was a mandatory step for all MySQL 8.0 implementations. That conflicts with the Laravel's default string length and validations, which is 255. So either we have to update the validations to 125 or check for any alternate options such as using MariaDB. That seems unnecessary in the case if we are using dynamic or compressed row format in MySQL.

It would be better if you could update the documentation accordingly to avoid any further confusion.

**Comment by drbyte** [comment]
@kkraju4u wrote:
> That conflicts with the Laravel's default string length and validations

Please open a new issue/discussion so we can collaborate. Perhaps you've simply missed updating your migration:

https://github.com/spatie/laravel-permission/blob/c66c0de99a95a88288507fa96676b89625f54488/database/migrations/create_permission_tables.php.stub#L29-L30

Either way, let's discuss in a new Issue or Discussion.
