### ISSUE TITLE
Get a user resource with their roles and permissions.

### ISSUE THREAD

**Issue by kodewbit** [spatie/laravel-permission#1692]
Hello, I am writing to you because I have spent hours of testing looking for a solution to a problem and I still have not found how to solve it. It happens that I have 3 resources, one for ``user``, another for ``role`` and another for ``permissions``. I show the structure of the mentioned resources:

UserResource.php

```
class UserResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param Request $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'roles' => RoleResource::collection($this->whenLoaded('roles')),
            'permissions' => PermissionResource::collection($this->whenLoaded('permissions', $this->getAllPermissions())),
            'active' => $this->active,
        ];
    }
}
```

RoleResource.php

```
class RoleResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param Request $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'permissions' => PermissionResource::collection($this->whenLoaded('permissions'))
        ];
    }
}
```

PermissionResource.php

```
class PermissionResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param Request $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'name' => $this->name
        ];
    }
}
```

As you can see in my `` UserResource.php `` file, I am defining a structure to display user roles and permissions only when required. You can also see that in the ``permissions`` key, I am not returning only the permissions associated with the user, I am returning all the permissions directly associated with the user and associated with the roles they have ``getAllPermissions()``.

Now look at the ``RoleResource.php`` file, I am defining that the permissions associated with the role will be displayed only when necessary, and here is my problem. When I do the following:

```
public function index()
{
    return UserResource::make(User::with(['roles', 'permissions'])->find(1));
}
```

I am getting the following response:

![imagen](https://user-images.githubusercontent.com/70990619/109187144-9debb200-775f-11eb-84ae-0f66530b6737.png)

Look at the key: ``roles``, It is showing me the ``permissions`` relation, and that is not the expected result, I expect it to show me that result only when I do the following:

```
public function index()
{
    return UserResource::make(User::with(['roles.permissions', 'permissions'])->find(1));
}
```
I've been doing a lot of testing and everything seems to indicate that when I call the method `` getAllPermissions() `` also load the ``permissions`` relation and that is why this is happening. Please could you help me with this problem. Thank you very much in advance.

**Comment by krve** [comment]
A bit late to the party, but in case anyone runs into a similar issue.

This appears to be because the `getAllPermissions` function calls `getPermissionsViaRoles` which then continues to load all the permissions of the user's roles.

```php
/**
 * Return all the permissions the model has via roles.
 */
public function getPermissionsViaRoles(): Collection
{
    return $this->loadMissing('roles', 'roles.permissions')
        ->roles->flatMap(function ($role) {
            return $role->permissions;
        })->sort()->values();
}
```

This loads the relationship on every role attached to the user.

You can overwrite the `getPermissionsViaRoles` method to make it work as expected.

```php
/**
 * Return all the permissions the model has via roles.
 */
public function getPermissionsViaRoles(): Collection
{
    // Find the roles that are not eagerly loaded
    $rolesNotEagerLoaded = $this->roles
        ->filter(fn($role) => !$role->relationLoaded('permissions'))
        ->pluck('id');

    $eagerLoadedPermissions = collect();

    if ($rolesNotEagerLoaded->isNotEmpty()) {
        // Fetch all the permissions from the roles not eager loaded
        // This is kinda like eager-loading the permissions
        $eagerLoadedPermissions = $eagerLoadedPermissions->merge(
            config('permission.models.permission')::with('roles')
                ->whereHas('roles', fn ($query) => $query->whereIn('id', $rolesNotEagerLoaded))
                ->get()
        );
    }

    return $this->roles->flatMap(function ($role) use ($eagerLoadedPermissions) {
        if ($role->relationLoaded('permissions')) {
            return $role->permissions;
        }

        return $eagerLoadedPermissions->filter(function ($permission) use ($role) {
            return $permission->roles->pluck('id')->contains($role->id);
        });
    });
}
```

This seems like alot, but it takes into account if you have already eager-loaded the permissions relationship, and only loads the permissions that are not.
