### ISSUE TITLE
Undefined property: App\Models\User::$roles

### ISSUE THREAD

**Issue by zeyadsharo** [spatie/laravel-permission#1699]
when calling function isSuperAdmin 
![image](https://user-images.githubusercontent.com/33178745/110523911-cabaa480-8123-11eb-8d56-4582cf024c69.png)

![image](https://user-images.githubusercontent.com/33178745/110523505-3d775000-8123-11eb-91e4-883927f174f0.png)
error
![image](https://user-images.githubusercontent.com/33178745/110524159-166d4e00-8124-11eb-8649-fa5a26a5d3f0.png)
<h1>Full error deception </h1>
[https://flareapp.io/share/qm1r4NRP#F59](https://flareapp.io/share/qm1r4NRP#F59)

**Comment by zeyadsharo** [comment]
[https://flareapp.io/share/qm1r4NRP#F59](url)

**Comment by drbyte** [comment]
Without seeing the code for the entire app it's difficult to say exactly what part of your app is causing your error. While the Flare link is helpful, it doesn't give enough insight into your app code.

Given that the HasRoles trait, which provides BOTH the `$roles` property (via the `roles()` method declaring relationship) and the `hasRole()` method you're calling, something in your app is evidently replacing/redefining/overriding/removing the `$roles` property. 
Or perhaps your auth/guard configuration is causing it to refer to a different instance of a User model which doesn't have the trait applied.
