### ISSUE TITLE
$this->can() not working

### ISSUE THREAD

**Issue by haleybe** [spatie/laravel-permission#1705]
I have noticed using `$this->can` in controllers is producing error 

`Argument 1 passed to Spatie\Permission\PermissionRegistrar::Spatie\Permission\{closure}() must implement interface Illuminate\Contracts\Auth\Access\Authorizable, instance of App\Http\Controllers\SomeController given, called in /*******/api/vendor/laravel/framework/src/Illuminate/Auth/Access/Gate.php on line 495`

Is `$this->can` supposed to work at all or not? If it is what could be wrong? Am i missing to implement/use some class in controllers or somewhere?

Controllers have _Authorizable_, **`$user->can()`** **is** working, _policies_ are working, _authorize_ is working, everything except this one

**Comment by drbyte** [comment]
In a controller, `$this` refers to the controller, and no `$this->can()` will not work when it's referring to the controller.
A controller doesn't have an Eloquent relationship that can interact with roles/permissions. It must be a Model, not a Controller.
