### ISSUE TITLE
Document site is Broken

### ISSUE THREAD

**Issue by pkeogan** [spatie/laravel-permission#1707]
Document site is broken.

https://spatie.be/docs/laravel-permission/v3

![image](https://user-images.githubusercontent.com/30511153/112073908-3cd2b680-8b32-11eb-9d98-33257e3cc8d7.png)
![image](https://user-images.githubusercontent.com/30511153/112073933-46f4b500-8b32-11eb-85a2-7fb66087d662.png)

**Comment by adgower** [comment]
Down for me as well

**Comment by hydrokat** [comment]
Same. Maybe they are migrating to v4 docs?

**Comment by MohammedAlkutrani** [comment]
down for me as well even v4

**Comment by riasvdv** [comment]
Fixed! Sorry about that, a mishap in the docs update
