### ISSUE TITLE
Multiply roles and permission with different logic

### ISSUE THREAD

**Issue by VictorPullzz** [spatie/laravel-permission#1719]
Hi. I have a small question, is it possible to use your library to manage global and individual roles. For example:
let's say there is a tableusers and the "Add Tasks" global role, which determines whether the user can create tasks. But there is also a user role that depends on the board id, "Add tasks". Those. a user for a board cannot create a task. Something like this structure:
`users` `roles` `permissions` `user_role` `user_board_permission`.

I mean, the user has the global role "manager" (with the ability to create tasks), but for some board, he has the role "user" (without the ability to create tasks). This feature (https://spatie.be/docs/laravel-permission/v4/basic-usage/wildcard-permissions) can help, do you think ?
Please could you help me with this problem. Thank you very much in advance!

**Comment by drbyte** [comment]
Discussion at https://github.com/spatie/laravel-permission/discussions/1718
