### ISSUE TITLE
I can't able to install it getting errors

### ISSUE THREAD

**Issue by harpreet9629** [spatie/laravel-permission#1720]
Problem 1
    - Root composer.json requires spatie/laravel-permission 4.0.1 -> satisfiable by spatie/laravel-permission[4.0.1].
    - spatie/laravel-permission 4.0.1 requires illuminate/auth ^6.0|^7.0|^8.0 -> found illuminate/auth[v6.0.0, ..., v6.20.22, v7.0.0, ..., v7.30.4, v8.0.0, ..., v8.35.1] but these were not loaded, likely because it conflicts with another require.

**Comment by drbyte** [comment]
> because it conflicts with another require

Yes, it's evidently conflicting with other packages you have installed.

One way to eliminate some other conflicts is to do remove all cached composer information with:
`rm -rf composer.lock vendor`
and then re-run the `composer require ........` statement to install the package.

Another way is to run `composer outdated` and use that information to upgrade all your package versions since you probably have older packages installed that may have updates available. Be sure to read each package's upgrade instructions.

**Comment by harpreet9629** [comment]
I updated laravel and composer but still getting error

Problem 1
    - spatie/laravel-permission[4.0.0, ..., 4.0.1] require illuminate/auth ^6.0|^7.0|^8.0 -> found illuminate/auth[v6.0.0, ..., v6.20.22, v7.0.0, ..., v7.30.4, v8.0.0, ..., v8.35.1] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires spatie/laravel-permission ^4.0 -> satisfiable by spatie/laravel-permission[4.0.0, 4.0.1].

**Comment by drbyte** [comment]
There's not enough information here.

Post your composer.json, and the rest of the composer errors.
Better yet, push your app to a github repo to inspect all the code.

**Comment by harpreet9629** [comment]
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-dompdf": "^0.9.0",
        "intervention/image": "^2.4",
        "kunalvarma05/dropbox-php-sdk": "^0.2.1",
        "laravel/framework": "^5.8.0",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.4",
        "lavary/laravel-menu": "^1.6",
        "league/fractal": "^0.17.0"
    },
    "require-dev": {
        "composer/composer": "^2.0",
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "SQ\\Base\\": "app/Libraries/base/src/",
            "SQ\\Themes\\": "app/Libraries/themes/src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

**Comment by drbyte** [comment]
Oh. 

> `"laravel/framework": "^5.8.0",`

Your app is using Laravel 5.8 but you're trying to install a package that's designed for Laravel 6+

If you want an old version of the package for your old Laravel app, use `composer require spatie/laravel:"^3.0"`
