### ISSUE TITLE
about “Defining a Super-Admin” in AuthServiceProvider (关于定义超级管理员的问题)

### ISSUE THREAD

**Issue by pengxuxu** [spatie/laravel-permission#1721]
Hello.

Currently this package utilizes Gate::before() to check, if the model has specified permission. Since package's Gate::before() are called before Laravel's Gate::before(), we cannot actually use Gate::before() in our main app as it is supposed to (for example to give a user a "superadmin" access).

当前v4文档里指出可以在AuthServiceProvider 里用Gate::before()来定义超级管理员，但是该包里的 Gate::before() 是优先于AuthServiceProvider里的Gate::before()，导致即使在 laravel AuthServiceProvider里定义了超级管理员也没有意义。

**Comment by drbyte** [comment]
If you've run into a situation where it doesn't work, then post the code for an application which clearly demonstrates the problem.
