### ISSUE TITLE
I have a problem with the interface

### ISSUE THREAD

**Issue by EdwinMason15** [spatie/laravel-permission#1724]
Hello everyone. The truth is I am new to web programming, I did the installation as the documentation says but I do not know why this error is due, I hope for your help, thank you.
   
        "php": "^7.1.3",
        "barryvdh/laravel-dompdf": "^0.9.0",
        "fideloper/proxy": "^4.0",
        "jeremykenedy/laravel-logger": "^4.2",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "~5.0",
        "jaybizzle/laravel-crawler-detect": "1.*"

         Composer version 2.0.12

Error: 
![image](https://user-images.githubusercontent.com/57450626/113764611-70881180-96d8-11eb-94a6-2da00f3fd7d7.png)

![image](https://user-images.githubusercontent.com/57450626/113764713-91506700-96d8-11eb-881b-a29924aa1bc9.png)

![image](https://user-images.githubusercontent.com/57450626/113764810-afb66280-96d8-11eb-9cae-ea126a45a032.png)

**Comment by drbyte** [comment]
Looks like everything you're posting about is about a "laravel logger" package.

But here you've posted in the Spatie Laravel-Permissions package area.  We can't help you with that other package here.
