### ISSUE TITLE
Multiple vendor:publish problem?

### ISSUE THREAD

**Issue by tomaspribyl** [spatie/laravel-permission#1725]
Hi, this is my first use of this package. I go deep to code for inspiration how are published migrations and I have question.

https://github.com/spatie/laravel-permission/blob/f0fe2c879478f332b72633b14468c98a7f2c84c5/src/PermissionServiceProvider.php#L172

I think it should work as follows:

If migrations was published, then found existing (without timestamps) in apps database folder and don't publish again. If wasn't published, publish with current timestamp.
But now **it returns again and again only migration with current timestamp**, even if migration was published previously.

i have published migration  **2021_04_07_162816_create_permission_tables.php** in my projects database folder

dump of Collection before returning first item contain only migrations with current timestamp

```
Illuminate\Support\Collection {#288
  #items: array:1 [
    0 => "/Users/tomaspribyl/Work/webs/ea-webmin-dev/database/migrations/2021_04_07_164015_create_permission_tables.php"
  ]
}
```

dump of my dev test version is as I expect

```php
protected function getMigrationFileName($migrationFileName): string
{
    $timestamp = date('Y_m_d_His');

    $filesystem = $this->app->make(Filesystem::class);

    $c = Collection::make($this->app->databasePath().DIRECTORY_SEPARATOR.'migrations'.DIRECTORY_SEPARATOR)
        ->flatMap(function ($path) use ($filesystem) {
            return $filesystem->glob($path.'*_create_permission_tables.php');
        });
    $c->push($this->app->databasePath()."/migrations/{$timestamp}_create_permission_tables.php")
    ->flatMap(function ($path) use ($filesystem, $migrationFileName) {
        return $filesystem->glob($path.'*_'.$migrationFileName);
    });
    $c->push($this->app->databasePath()."/migrations/{$timestamp}_{$migrationFileName}")
    ;
    dd($c);
    //return $c->first();
}
```

```
Illuminate\Support\Collection {#292
  #items: array:3 [
    0 => "/Users/tomaspribyl/Work/webs/ea-webmin-dev/database/migrations/2021_04_07_162816_create_permission_tables.php"
    1 => "/Users/tomaspribyl/Work/webs/ea-webmin-dev/database/migrations/2021_04_07_163014_create_permission_tables.php"
    2 => "/Users/tomaspribyl/Work/webs/ea-webmin-dev/database/migrations/2021_04_07_163014_create_permission_tables.php"
  ]
}
```
method return first item of collection and it is my previously published version in project database dir

is function in this repo ok?
Thanks

**Comment by drbyte** [comment]
> But now it returns again and again only migration with current timestamp, even if migration was published previously.

In some respects this was intentional, so that people would take the time to compare the two migration files and adjust the new one to retain whatever has changed since the first migration was published. The package doesn't add new migration files: it always just updates the main migration file, and it's up to you to apply any changes to your own application.

**Comment by tomaspribyl** [comment]
Ok, so its ok. In this case, the logic of this function seems quite complicated to me.
