### ISSUE TITLE
Missing ID and timestamps in some tables.

### ISSUE THREAD

**Issue by colivinggit** [spatie/laravel-permission#1729]
It's good practice to always add ID in all tables.

ID is missing in:
role_has_permissions
model_has_permissions
model_has_roles

Timestamps should also be added.

**Comment by colivinggit** [comment]
Any reason why it was closed?

**Comment by drbyte** [comment]
These are pivot tables, managed by relationships. 
An id field just consumes more storage, and is never used by Eloquent or by this package.
If your own app needs to add id fields because you're writing application code that overrides normal Eloquent relationship interaction, you are free to add those fields for yourself.

**Comment by brlocky** [comment]
I would need to assign time stamps on `model_has_roles` table, but once this relation is implemented inside `HasRoles`. trait, I'm not able to overwrite it !
Any solution for this issue ?

```
    /**
     * A model may have multiple roles.
     */
    public function roles(): BelongsToMany
    {
        $relation = $this->morphToMany(
            config('permission.models.role'),
            'model',
            config('permission.table_names.model_has_roles'),
            config('permission.column_names.model_morph_key'),
            PermissionRegistrar::$pivotRole
        );

        if (! PermissionRegistrar::$teams) {
            return $relation;
        }

        return $relation->wherePivot(PermissionRegistrar::$teamsKey, getPermissionsTeamId())
            ->where(function ($q) {
                $teamField = config('permission.table_names.roles').'.'.PermissionRegistrar::$teamsKey;
                $q->whereNull($teamField)->orWhere($teamField, getPermissionsTeamId());
            });
    }
```

**Comment by erikn69** [comment]
@brlocky everything is overwritable
