### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [spatie/laravel-permission#173]
Hello. 

When do you plan to bump the Laravel version to 5.4?
For now - can't use your package with 5.4.

**Comment by freekmurze** [comment]
Currently busy updating all our package for L5.4. 

This one will be updated rather soonish.

**Comment by freekmurze** [comment]
Version `1.7.0` can be installed in Laravel 5.4

**Comment by Vasiliy-Bondarenko** [comment]
Thanx.
