### ISSUE TITLE
middleware method allowed not working

### ISSUE THREAD

**Issue by mgrWetales** [spatie/laravel-permission#1737]
I am trying to use spatie in the API resources but it seems it's not working.

My use case is just like the below demo of spatie:
https://github.com/drbyte/spatie-permissions-demo/blob/master/app/Http/Controllers/HomeController.php

In simple words I have assigned permission to the admin user and restricted his access to a single function only like below:
$this->middleware('permission:edit articles')->only('testmiddleware');
But when I test it, this user can access all the resource functions. 

OS: ubuntu 20.04
PHP version: 8
Mysql version: 8
Laravel version: 8
Spatie version: "spatie/laravel-permission": "^4.0"

**Comment by drbyte** [comment]
The `only()` method applies that middleware to "only" the specified function.  It has no effect on all other functions. To protect all other functions, you'll need to apply a different middleware to them, or apply Policies etc.

**Comment by mgrWetales** [comment]
Thanks, @drbyte for a quick reply.

Yes, I got it and resolved the issue. Actually, route clear and cache clear after each change in the constructor middleware application did the trick for me.
