### ISSUE TITLE
Defining a Super-Admin not working

### ISSUE THREAD

**Issue by mirkin1993** [spatie/laravel-permission#1746]
**Describe the bug**
I followed the manual on: [https://spatie.be/docs/laravel-permission/v4/basic-usage/super-admin](https://spatie.be/docs/laravel-permission/v4/basic-usage/super-admin) to create a Super Admin but I don't work. All pages are showing 403 | Forbidden.

**Versions**
- spatie/laravel-permission package version: 4.0.1
- laravel version: 8.38.0

PHP version: 8.0.1

**To Reproduce**
- Follow the manual on: [https://spatie.be/docs/laravel-permission/v4/basic-usage/super-admin](https://spatie.be/docs/laravel-permission/v4/basic-usage/super-admin)
- Assign the super admin to a user
- Test a page with a permission

**Comment by drbyte** [comment]
Create a new app to demonstrate the problem, and push it into a public github repo, and post the link to it here. Preferably make multiple commits, one for each step.
This will help us diagnose where the problem is in your app.

**Comment by kossa** [comment]
I'm facing the same error
