### ISSUE TITLE
FindByName does not follow extended Permission model's roles relationship.

### ISSUE THREAD

**Issue by WildEgo** [spatie/laravel-permission#1755]
**Describe the bug**
FindByName does not follow extended Permission model's roles relationship unless the relationship is loaded again by ``$permission->load('roles')``.

**Versions**
- spatie/laravel-permission package version: 4.2.0
- laravel/framework package: v8.45.1

PHP version: 8.0.0

Database version: MariaDB 10

**To Reproduce**
```
App\Models\Permission::findByName('view users');
```

**Expected behavior**
Use the extended model's roles relationship.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Ubuntu
 - Version [e.g. 22] 20.04.2
 
 **Additional context**
It's a multi tenant application with a single users table in the central database so I need it to follow the correct relationship.

**Comment by drbyte** [comment]
This seems to be app-specific.

Perhaps your multi-tenant app is re-defining the connection after it has been instantiated/loaded and/or cached, and thus you may need to instantiate things in a different load-order to match your app's workflow?

**Comment by WildEgo** [comment]
> This seems to be app-specific.
> 
> Perhaps your multi-tenant app is re-defining the connection after it has been instantiated/loaded and/or cached, and thus you may need to instantiate things in a different load-order to match your app's workflow?

Hey I just woke up and decided to test some ideas I had and it's cache related it looks like, is there any way I can possibly disable it? I'm sorry if it's documented I can't remember from the top of my head
