### ISSUE TITLE
Malfunction of HasRoles trait when applied to a User model with custom primary key

### ISSUE THREAD

**Issue by david-perez** [spatie/laravel-permission#178]
I have a custom user model (`Client.php`) with a custom primary key (which Eloquent uses to save my users into the database).

```
class Client extends Model
{
    use HasRoles;

    protected $primaryKey = 'my_primary_key';
    ...
}
```

I've set up correctly in the config file that I wish to use a different table name for my users.
```
'table_names' => [

        /*
        |--------------------------------------------------------------------------
        | Users Table
        |--------------------------------------------------------------------------
        |
        | The table that your application uses for users. This table's model will
        | be using the "HasRoles" and "HasPermissions" traits.
        |
        */
        'users' => 'Clients',
        ...
```

However, I cannot assign roles to my users. The reason why is how the `roles()` many-to-many relationship is defined in the `HasRoles` trait.

```
 /**
 * A user may have multiple roles.
 *
 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
 */
public function roles()
{
    return $this->belongsToMany(
        config('laravel-permission.models.role'),
        config('laravel-permission.table_names.user_has_roles')
    );
}
```

The table that joins the users to the roles is `user_has_roles` (by default). Now, Laravel will not use my custom primary key from `Client` to join the tables. Instead, what Laravel does is it attempts to deduce the key's name from the model's name. From [the documentation](https://laravel.com/docs/5.3/eloquent-relationships#one-to-many),

> Remember, Eloquent will automatically determine the proper foreign key column on the  Comment model. By convention, Eloquent will take the "snake case" name of the owning model and suffix it with _id.

So in my case, Laravel will attempt to join the tables using the key `client_id` instead of `my_primary_key`. Notice that changing the column name of the `user_has_roles` table from `user_id` to `my_primary_key` in the published migration will not do the trick, the only thing that would work is to change my `Client`'s primary key to be `user_id`, which I am not willing to do.

The workaround (which may be the library's expectation) is to override the `roles()` method in the custom user model, and tell Laravel explicitly the name of the foreign key on which to join.

```
public function roles()
{
    return $this->belongsToMany(
        config('laravel-permission.models.role'),
        config('laravel-permission.table_names.user_has_roles'),
        $this->primaryKey // or whatever else you want
    );
}
```

This would also have to be done in the `permissions()` method, in order to join to permissions via the `user_has_permissions` table.

Of course, all of this could be avoided if the config file allowed for a custom primary key of the user model to be specified. It could thus query the loaded config in these methods, and always pass the correct column name on which to join.

**Comment by freekmurze** [comment]
Not many users will override the name of the primary key. This specific use case doesn't warrant introducing a new key in the config file.

The best solution would indeed to override the `roles` method.
