### ISSUE TITLE
Checking for permissions checks for first auth guard in the list, rather than default or one that route 

### ISSUE THREAD

**Issue by Onekone** [spatie/laravel-permission#1793]
Checking if user `can:permission` through a middleware for some reason checks first known auth guard (which was `web` for me, rather than `sanctum` from `laravel/sanctum` package in my case), rather one that user was checked via `auth:guard` with.

**Versions**
- spatie/laravel-permission package version: 4.2.0
- Laravel framework: 8.47.0

PHP version: 8.0.3
Database version: 8.0.24

**To Reproduce**
* Create a user, a role and a permission, and award role to a user, and permission to a role
* Create a custom guard to auth with
* Create a routegroup that is protected with `auth:custom` middleware
* Create a route within that group that is protected with `can:%permission_name%`

**Expected behavior**
* Guard checked for permissions is one that was used in auth middleware.
* Working out of guard without fiddling with the order of guards in config and/or hardcoding it to the model

**Desktop (please complete the following information):**
 - OS: Linux Mint 18

**Comment by fredsal** [comment]
[Multiple guards](https://spatie.be/docs/laravel-permission/v4/basic-usage/multiple-guards)
[Wildcard guard for permissions and roles](https://github.com/spatie/laravel-permission/issues/1156)

**Comment by freekmurze** [comment]
@Onekone could you create a minimal Laravel app that demonstrates the issue? Or maybe create a failing tests for us to look at?

**Comment by Onekone** [comment]
@freekmurze 

I am incredibly sorry for being this late, life hit like a hurracane on the weekends

However, yes, [minimal Laravel app that demonstrates the issue](https://github.com/Onekone/spatie-issue-example). 

Hopefully useful enough to illustrate the behaviour I'm having troubles with

**Comment by fredsal** [comment]
Any news on this?

**Comment by drbyte** [comment]
@Onekone The following appears to resolve it, using your demo app:

`routes/api.php`
```diff
Route::group(['middleware' => 'auth:api', 'prefix' => 'tokens'], function () {
    Route::any('test-success', function () {
        return 'This must succeed within API guard with API permission';
-    })->middleware('can:nonweb');
+    })->middleware('permission:nonweb');
    Route::any('test-fail', function () {
        return 'This must NOT succeed within API guard with API permission';
-    })->middleware('can:nonapi');
+    })->middleware('permission:nonapi');
});
```

`\app\Http\Kernel.php`
```diff
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'cache.headers' => \Illuminate\Http\Middleware\SetCacheHeaders::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'password.confirm' => \Illuminate\Auth\Middleware\RequirePassword::class,
        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
+    'permission' => \App\Http\Middleware\PermissionMiddleware::class,
    ];
```

`/app/Http/Middleware/PermissionMiddleware.php` (cloned from spatie package, and edited as shown below):
```diff
<?php

-namespace Spatie\Permission\Middlewares;
+namespace App\Http\Middleware;

use Closure;
use Spatie\Permission\Exceptions\UnauthorizedException;

class PermissionMiddleware
{
    public function handle($request, Closure $next, $permission, $guard = null)
    {
+        $guard = $guard ?? config('auth.defaults.guard');

        $authGuard = app('auth')->guard($guard);

        if ($authGuard->guest()) {
            throw UnauthorizedException::notLoggedIn();
        }

        $permissions = is_array($permission)
            ? $permission
            : explode('|', $permission);

        foreach ($permissions as $permission) {
-            if ($authGuard->user()->can($permission)) {
+            if ($authGuard->user()->checkPermissionTo($permission, $guard)) {
                return $next($request);
            }
        }

        throw UnauthorizedException::forPermissions($permissions);
    }
}
```

**Comment by Onekone** [comment]
@drbyte 

Yes, I could use it (and in fact, went with it in live service I've encountered this issue in) but it defeats the point of using Laravel gates that this package extends

**Comment by drbyte** [comment]
How about:

`Guard.php`:
```diff
    public static function getDefaultName($class): string
    {
        $default = config('auth.defaults.guard');

+        $possible_guards = static::getNames($class);
+
+        if ($possible_guards->contains($default)) {
+            return $default;
+        }
+
-        return static::getNames($class)->first() ?: $default;
+        return $possible_guards->first() ?: $default;
    }
```

**Comment by erikn69** [comment]
>How about:
>
>Guard.php:
>
>return $possible_guards->first() ?: $default;

@drbyte that works on test file, but if you use browser 
`http://127.0.0.1:8000/tokens/test-fail` 
gets 
`This must NOT succeed within WEB guard with WEB permission` 
and i guess it must be `503`

**Comment by erikn69** [comment]
>$possible_guards = static::getNames($class);
>        if ($possible_guards->contains($default)) {
>            return $default;
>        }
>return $possible_guards->first() ?: $default;

@drbyte i made some test with that, it works, and i need this too

**Comment by drbyte** [comment]
> i made some test with that, it works, and i need it too, actually i'm using a `Middleware` for that bug

It causes some breaking changes, but I suspect they're all in a way that everyone *wants*, so ... I make a PR with it along with some other related updates.
