### ISSUE TITLE
Allow extension of Role and Permission

### ISSUE THREAD

**Issue by Propaganistas** [spatie/laravel-permission#18]
Hi

I've ran into the case that I need to be able to assign a description to the Permission model.
Normally, one would extend the Permission class and proceed, however this won't work with this package since both Role and Permission classes are quite a lot hard-coded using class imports.

Some suggestions:
- use the IoC to bind an Eloquent model to Role and Permission to allow developers to override when necessary.
- use a config value like Laravel's built-in `auth.model`

**Comment by arcanedev-maroc** [comment]
@Propaganistas Yeah, there is no config file for this package to customize or extend it.

**Comment by freekmurze** [comment]
Using a config file to specify the model classes and removing the hardcoded imports seems like an excellent idea. I'll try to make this happen in the near future. If you need this quick, feel free to submit a PR.

**Comment by freekmurze** [comment]
Solved in v1.2.0 of the package
