### ISSUE TITLE
canAny: Allow is any of the permissions is set

### ISSUE THREAD

**Issue by amenk** [spatie/laravel-permission#180]
We are using Laravel's built-in middleware `can:something` and want to allow a a route if *any* of a set of permission as set. Is there something like `canAny:something,somethingelse` we are overseeing or is it a new feature? Can it be easily added?

PS: Did you receive our postcard :post_office:  ?

**Comment by freekmurze** [comment]
Hi, 

what does your postcard look like, then I'll check if we got it 😄  Thanks for sending it 👍 

This seems something specific for your project. I'd create `canAny ` method on your user model that leverages the built in `can`method.

**Comment by amenk** [comment]
There is hasAnyRole so I think it would fit ... do you know if different middlewares can be OR-combined (instead of AND) ?
The postcard was a christmas card from iMi, reqesting the license to use the module :-)

**Comment by drbyte** [comment]
Update: `@canany` has been available within Blade since Laravel 5.6.23
https://github.com/laravel/framework/releases/tag/v5.6.23

Just posting this here since someone was asking about it.
