### ISSUE TITLE
IDE not recognizing `Auth::user()->can();` ?

### ISSUE THREAD

**Issue by richoandika** [spatie/laravel-permission#1806]
Can we calling using `Auth::user()->can();` ?
its works, but i have a little problem on my text editor `Undefined method 'can'.`

_Originally posted by @richoandika in https://github.com/spatie/laravel-permission/issues/1287#issuecomment-894073702_

**Comment by richoandika** [comment]
I found a little idea to get rid of the error.

I added a new function in the User model:
`
    public function mySelf()
    {
        $user = Auth::user();

        if ($user) {
            return User::find($user->id);
        }
    }
`
So i can use `(new User)->mySelf()->can();` on Controllers and that's to cover the mistakes that exist.

**Comment by erikn69** [comment]
`User::find` executes a sql
> on my text editor

Try
```php
/** @var \App\Models\User $user */
$user = Auth::user();
$user->can('dfdf')
```
