### ISSUE TITLE
PHP Version in composer.json bug

### ISSUE THREAD

**Issue by ricocrivelli** [spatie/laravel-permission#1811]
I'm trying to install the latest version of this package in my sail docker image, but I'm getting this message:

`Using version ^4.2 for spatie/laravel-permission
./composer.json has been updated
Running composer update spatie/laravel-permission
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php 8.0 but your php version (8.0.7) does not satisfy that requirement.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

I think we should change the composer.json to ^8.0.x maybe?

My system info:
Package Version: 4.2
PHP Version: 8.0.7
Laravel Sail Docker Image
Windows 10

**Comment by erikn69** [comment]
I have 8.0.7 on docker and it works, everyone uses older versions of 8.0.0

**Comment by ricocrivelli** [comment]
> 
> 
> I have 8.0.7 on docker and it works, everyone uses older versions of 8.0.0, maybe you need to upgrade composer, try `composer install --ignore-platform-reqs`

Yes, this was the only way I could install the package.

**Comment by erikn69** [comment]
https://github.com/laravel/laravel/blob/226d1bfc3c774e24a79e68e9f1264b5ca359551f/composer.json#L7-L8
Every package uses `"php": "^8.0"`, if `composer.json` was the problem you could not even install laravel

**Comment by ricocrivelli** [comment]
> 
> 
> https://github.com/laravel/laravel/blob/226d1bfc3c774e24a79e68e9f1264b5ca359551f/composer.json#L7-L8
> Every package uses `"php": "^8.0"`, if `composer.json` was the problem you could not even install laravel
> The problem is your `composer.json`, you forget `^` before `8.0`

My composer? I'm running ` composer require spatie/laravel-permission ` just like https://spatie.be/docs/laravel-permission/v4/installation-laravel says.

But if you insist this is a problem with me, you've won. I just tried to help other people who are facing the same problem.

**Comment by erikn69** [comment]
composer always looks your `composer.json`, Root composer.json means your `composer.json`
