### ISSUE TITLE
[Bug? 4.3.0] Checking Permission via can() return PermissionDoesNotExists

### ISSUE THREAD

**Issue by shadowbane** [spatie/laravel-permission#1816]
Hi. First, thanks for this great packages. I've been using this packages since version 1.

I have user with Role 'System Administrator', and this roles has permission named 'dashboard', 'logs', etc. When I'm checking the user's permission via `can`, it throws `Spatie\Permission\Exceptions\PermissionDoesNotExist`.

- spatie/laravel-permission package version: 4.3.0
- illuminate/framework package: v8.55.0

PHP version: 8.0.7
Database version: MySQL 8.0.25

This is not happening prior to version 4.3.0. We have traced this issue, and found that `getPermissions` on `Spatie\Permission\PermissionRegistrar` is the culprit here.

This is how we resolve this problem:
```php
        $permissions = $this->permissions->$method(static function ($permission) use ($params) {
            foreach ($params as $attr => $value) {
                if ($permission->getAttribute($attr) == $value) {
                    return true;
                }
            }

            return false;
        });
```

I think the return value are swapped? If I swap the 'true' and 'false' value like above, it behaves normally, and I only get `PermissionDoesNotExists` exception only when I'm supplying it with wrong / invalid permission.

Thanks

**Comment by drbyte** [comment]
@shadowbane can you provide more detail? 
Example code to simulate the exact scenario would be helpful.
A failing test for this package would be even better!

**Comment by shadowbane** [comment]
**1. Permissions Table Data**

| id | name | shortname | guard_name |
|----|---------|----------------|------------------|
|185|App\Http\Controllers\Admin\LogDetailCrudController@view | Log Detail | backpack |
|186|App\Http\Controllers\Admin\LogDetailCrudController@create | Log Detail | backpack |
|187|App\Http\Controllers\Admin\LogDetailCrudController@update | Log Detail | backpack |
|188|App\Http\Controllers\Admin\LogDetailCrudController@delete | Log Detail | backpack |

**2. First user's Roles**
![image](https://user-images.githubusercontent.com/6396154/129847126-fe68fb4f-535a-4bc3-87df-d4d000eb8e71.png)

**3. Behaviour on 4.2.0**
  - User has valid permission
    ![image](https://user-images.githubusercontent.com/6396154/129847213-80b058f9-8c3d-4866-a076-4625e6adb631.png)
  - Wrong permission supplied
    ![image](https://user-images.githubusercontent.com/6396154/129847347-34c592f8-19db-4ed3-aff4-427822e5d5c7.png)
  - Using `hasPermissionTo` - Valid permission
    ![image](https://user-images.githubusercontent.com/6396154/129847595-a47eb903-8d39-48e6-9a4d-d4a8f2c1c8a9.png)
  - Using `hasPermissionTo` - Wrong permission supplied
    ![image](https://user-images.githubusercontent.com/6396154/129847652-17c732b6-5eee-4898-a090-6260008793e4.png)
  - Using `hasPermissionTo` with user that has no permission
    ![image](https://user-images.githubusercontent.com/6396154/129847869-97cd0626-7653-4ecd-9f70-c408455ce86a.png)

**4. Behaviour on 4.3.0**
  - User has valid permission -  should return true. But on 4.3.0 it return false.
    ![image](https://user-images.githubusercontent.com/6396154/129848249-df416d93-59cc-4116-afce-ee33714cc5c5.png)
  - Wrong permission supplied
    ![image](https://user-images.githubusercontent.com/6396154/129848443-54ecdba6-2f29-4c5c-bc96-122ae5a04d45.png)
  - Using `hasPermissionTo` - Valid permission. It throws error, but permission should exists. Please compare with result on 4.2.0
    ![image](https://user-images.githubusercontent.com/6396154/129848542-c7fcee1c-237c-49d6-87cc-4d79e5e3c848.png)
  - Using `hasPermissionTo` - Wrong permission supplied. This is correct result.
    ![image](https://user-images.githubusercontent.com/6396154/129848718-54ac5a6e-61d2-43df-b407-a4f98dd6eb31.png)
  - Using `hasPermissionTo` with user that has no permission. It should return false, but it returns `PermissionDoesNotExists`
    ![image](https://user-images.githubusercontent.com/6396154/129848842-9ab0b163-1780-4d32-8653-55c71cd4221f.png)

**Comment by shadowbane** [comment]
Modifying `PermissionRegistrar`

```php

/**
 * Get the permissions based on the passed params.
 *
 * @param array $params
 * @param bool $onlyOne
 *
 * @return \Illuminate\Database\Eloquent\Collection
 */
public function getPermissions(array $params = [], bool $onlyOne = false): Collection
{
    $this->loadPermissions();

    $method = $onlyOne ? 'first' : 'filter';

    $permissions = $this->permissions->$method(static function ($permission) use ($params) {
        foreach ($params as $attr => $value) {
            if ($permission->getAttribute($attr) == $value) {
                return true;
            }
        }

        return false;
    });

    if ($onlyOne) {
        $permissions = new Collection($permissions ? [$permissions] : []);
    }

    return $permissions;
}
```

Result:
- User has valid permission
  ![image](https://user-images.githubusercontent.com/6396154/129849354-a8730f12-f23e-4df0-95a4-d3df15ea65fe.png)

- Wrong permission supplied
  ![image](https://user-images.githubusercontent.com/6396154/129849400-58f021f8-8359-4734-8fea-c289efdda546.png)

- Using hasPermissionTo - Valid permission
  ![image](https://user-images.githubusercontent.com/6396154/129849458-efe100db-8062-4271-92f0-cf7604caa110.png)

- Using hasPermissionTo - Wrong permission supplied
  ![image](https://user-images.githubusercontent.com/6396154/129849487-975330ca-e5ff-4b58-bfb6-0d70e6cc8cba.png)

- Using hasPermissionTo with user that has no permission
  ![image](https://user-images.githubusercontent.com/6396154/129849550-b9fac73f-3ec9-4ff9-9259-7ef9935fc9b6.png)


As you can see, it behaves just like version 4.2.0. Sorry that we can't show failed test result. But I hope it helps.
FYI: I have cleared the cache before every test shown in those pictures.

**Comment by shadowbane** [comment]
For those who are confused, we are implementing dynamic permission by controller. We are checking if user has permission to access the controller and the underlying functions at middleware level, and throws 403 if they has no valid roles / permission.

![image](https://user-images.githubusercontent.com/6396154/129850815-c8ad9820-d802-48f9-b6ee-c3b286bb963a.png)

**Comment by erikn69** [comment]
>swap the 'true' and 'false'

If you do that, it means that it will choose the first attribute that matches, ignoring if the next one does not match
```php
foreach ($params as $attr => $value) {
      if ($permission->getAttribute($attr) == $value) {
          return true;
      }
  }
  return false;
});
```
`guard_name` is the second attribute to evaluate
Can you look your `guard_name`?

**Comment by shadowbane** [comment]
> **1. Permissions Table Data**
> 
> | id | name | shortname | guard_name |
> |----|---------|----------------|------------------|
> |185|App\Http\Controllers\Admin\LogDetailCrudController@view | Log Detail | backpack |
> |186|App\Http\Controllers\Admin\LogDetailCrudController@create | Log Detail | backpack |
> |187|App\Http\Controllers\Admin\LogDetailCrudController@update | Log Detail | backpack |
> |188|App\Http\Controllers\Admin\LogDetailCrudController@delete | Log Detail | backpack |
> 

@erikn69 here's the sample of my permissions table. We are using `backpack` as the guard name.

You can see my previous comment. When using v4.3, it throws `PermissionDoesNotExists`.

What if we append it to an array first instead of returning true?

**Comment by erikn69** [comment]
> What if we append it to an array first instead of returning true?

That means that the permissions of different guards will be available to each other.

**Comment by erikn69** [comment]
Try 
```php
User::first()->hasPermissionTo('your_permission','backpack');
```
https://github.com/spatie/laravel-permission/blob/5b3ea6b0e3ed08a0efc8d9b016fb0750fda7ccac/src/Traits/HasPermissions.php#L113

**Comment by erikn69** [comment]
You get `PermissionDoesNotExists` because the permission's `guard_name` is not the same as user's `guard_name`, so it is diferent permissions for the method `filter`/`first`

**Comment by shadowbane** [comment]
Hi @erikn69 

No, we're using 'backpack' as the user's default and only guard.

**Comment by shadowbane** [comment]
@erikn69 here's the information for `hasPermissionTo` with guard name

Here's the result with 4.2.0:
![image](https://user-images.githubusercontent.com/6396154/129923818-5eb9a193-0d9b-4fa8-ae25-7922b5000ab2.png)

And here's with 4.3.0:
![image](https://user-images.githubusercontent.com/6396154/129924108-538453ad-67dd-4a8d-982f-78e17c482754.png)

Here's the snapshot of user's guard name:
![image](https://user-images.githubusercontent.com/6396154/129924480-a888d985-4b49-4f01-b178-fca15e6a82b4.png)

**Comment by shadowbane** [comment]
@erikn69 pardon me for this crude debugging, but here's some more debug result with ray on 4.3.0:

![image](https://user-images.githubusercontent.com/6396154/129925629-9d5314e1-8352-485e-b6f5-4a6eb1930fb3.png)

**Comment by erikn69** [comment]
I thinking that maybe backslash is the problem

**Comment by shadowbane** [comment]
@erikn69 here's more crude debugging result. As you can see, it should return the dump-and-die with value 'should return'.
But it never called. 
![image](https://user-images.githubusercontent.com/6396154/129929951-6bc4efc7-6966-4aef-94f3-83db2b82d713.png)

> Breaks all the tests with PermissionAlreadyExists
Have you change the comparison from `!=` to `==`?

**Comment by shadowbane** [comment]
```
Time: 00:00.205, Memory: 22.00 MB

OK (1 test, 3 assertions)
```

I've got some result on freshly cloned repo. Weird, in my other projects that also using this package, it also throwing the same error 😭

**Comment by erikn69** [comment]
Did you `php artisan config:clear` and `php artisan permission:cache-reset` on console?

**Comment by shadowbane** [comment]
Yeah, cleared the caches between every test. We will to check it thoroughly tomorrow.

**Comment by erikn69** [comment]
>edit: other project behaves normally.. I guess this bug is from our implementation..

That's is because we make unit tests, sometimes is a local config, server, etc. I will still be attentive

**Comment by syssi** [comment]
We've the same issue since upgrading to `4.3.0`:

```
Seeding: Database\Seeders\RolesAndPermissionsSeeder

   Spatie\Permission\Exceptions\PermissionDoesNotExist 

  There is no permission named `add user` for guard `web`.

  at vendor/spatie/laravel-permission/src/Exceptions/PermissionDoesNotExist.php:11
      7▕ class PermissionDoesNotExist extends InvalidArgumentException
      8▕ {
      9▕     public static function create(string $permissionName, string $guardName = '')
     10▕     {
  ➜  11▕         return new static("There is no permission named `{$permissionName}` for guard `{$guardName}`.");
     12▕     }
     13▕ 
     14▕     public static function withId(int $permissionId, string $guardName = '')
     15▕     {

      +3 vendor frames 
  4   [internal]:0
      Spatie\Permission\Models\Role::Spatie\Permission\Traits\{closure}("add user")

      +2 vendor frames 
  7   database/seeders/RolesAndPermissionsSeeder.php:33
      Spatie\Permission\Models\Role::givePermissionTo()

```

**Comment by drbyte** [comment]
@syssi can you post your application code that is triggering the error?

**Comment by erikn69** [comment]
`RolesAndPermissionsSeeder` example?
@syssi , is  `web` your default and ony guard?

**Comment by syssi** [comment]
I will provide the file later the day!

**Comment by syssi** [comment]
```
<?php

namespace Database\Seeders;

use App\Domains\UserManagement\Models\Permission;
use App\Domains\UserManagement\Models\Role;
use Exception;
use Illuminate\Database\Seeder;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    public function run()
    {
        // reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        // create permissions
        foreach ($this->getPermissions() as $key => $permission) {
            if (is_array($permission)) {
                foreach ($permission as $specificPermission) {
                    Permission::create(['name' => $specificPermission . ' ' . $key]);
                }
            } else {
                Permission::create(['name' => $permission]);
            }
        }

        // create roles and assign created permissions
        $role = Role::create(['name' => 'Super-Admin'])->givePermissionTo(Permission::all());

        foreach ($this->getPreparedRoles() as $roleName => $rolePermissions) {
            $role = Role::create(['name' => $roleName])->givePermissionTo($rolePermissions); // <-- LINE 33
        }

        $this->generateConstFiles();
    }

    private function getPermissions(): array
    {
        $apiPermissions = ['add', 'show', 'showAll', 'edit', 'delete'];

        // please notice: an permission array key must be a single word at the first level if there are sub permissions!
        return [
            'user' => array_merge($apiPermissions, [
                'edit roles of'
            ]),
            'tenant' => array_merge($apiPermissions, [
                'edit users of',
            ]),
            'landingpage' => $apiPermissions
        ];
    }

    private function getPreparedRoles(): array
    {
        $roleDefinitions = $this->getRoles();

        $permissions = $this->getPermissions();

        $roles = [];

        foreach ($roleDefinitions as $roleName => $rolePermissions) {
            $roles[$roleName] = [];
            foreach ($rolePermissions as $permission) {
                if (array_key_exists($permission, $permissions)) {
                    if (is_array($permissions[$permission])) {
                        foreach ($permissions[$permission] as $specificPermission) {
                            $roles[$roleName][] = $specificPermission . ' ' . $permission;
                        }
                    } else {
                        $roles[$roleName][] = $permission;
                    }
                } else {
                    if (array_key_exists(substr($permission, 0, strrpos($permission, " ")), $permissions)) {
                        $roles[$roleName][] = $permission;
                    } else {
                        throw new Exception('Permission does not exists: ' . $permission);
                    }
                }
            }
        }

        return $roles;
    }

[...]
```

**Comment by syssi** [comment]
There are two guards:

```
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ],
    ],
```

**Comment by erikn69** [comment]
@syssi 'users' has two guards, maybe related #1793, i gonna try to test

**Comment by erikn69** [comment]
@syssi please try repeat again `forgetCachedPermissions` after permission creation

```php
         // reset cached roles and permissions
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        // create roles and assign created permissions
        $role = Role::create(['name' => 'Super-Admin'])->givePermissionTo(Permission::all());
```

**Comment by syssi** [comment]
Doesn't help:

```
diff --git a/backend/database/seeders/RolesAndPermissionsSeeder.php b/backend/database/seeders/RolesAndPermissionsSeeder.php
index dda440db..5c010f5f 100644
--- a/backend/database/seeders/RolesAndPermissionsSeeder.php
+++ b/backend/database/seeders/RolesAndPermissionsSeeder.php
@@ -31,8 +31,11 @@ class RolesAndPermissionsSeeder extends Seeder
 
         foreach ($this->getPreparedRoles() as $roleName => $rolePermissions) {
             $role = Role::create(['name' => $roleName])->givePermissionTo($rolePermissions);
+            app()[PermissionRegistrar::class]->forgetCachedPermissions();
         }
 
+        app()[PermissionRegistrar::class]->forgetCachedPermissions();
+
         $this->generateConstFiles();
     }
```

**Comment by erikn69** [comment]
@syssi `Call to undefined method Database\Seeders\DatabaseSeeder::getRoles()`

you miss one `getRoles`

**Comment by erikn69** [comment]
I finally deduced `getRoles`
```php
private function getRoles(): array
{
    return [
        'role1' => ['user', 'tenant', 'landingpage']
    ];
}
```
After `php artisan migrate --seed` i got
```
Nothing to migrate.
Database seeding completed successfully.
```
![image](https://user-images.githubusercontent.com/4933954/130301181-d46c22e4-2af5-4747-a1f6-ef769e68f608.png)

I can find a way to replicate your bug, seriously, i'm baffled

**Comment by erikn69** [comment]
@syssi please tell me more about your environment, 
php version, laravel version, laradock, vapor, docker, OS

**Comment by shadowbane** [comment]
Hi @erikn69 

Sorry for late reply. Found the problem, and it's on our side. We are hiding the 'guard_name' in the extended model, so the permission cannot compare the `guard_name` with user's guard. I'm sorry for taking your time for this, and thanks for the speedy response.

@syssi I've seen your code that you also extend the permission model. Maybe, just maybe, you hide the `guard_name` too?

**Comment by syssi** [comment]
@shadowbane Good catch! Indeed! We extended the permission model:

```
<?php

namespace App\Domains\UserManagement\Models;

use Spatie\Multitenancy\Models\Concerns\UsesLandlordConnection;

class Permission extends \Spatie\Permission\Models\Permission
{
    use UsesLandlordConnection;

    protected $visible = [
      'id', 
      'name',
    ];
}
```

This fixes the issue:

```
<?php

namespace App\Domains\UserManagement\Models;

use Spatie\Multitenancy\Models\Concerns\UsesLandlordConnection;

class Permission extends \Spatie\Permission\Models\Permission
{
    use UsesLandlordConnection;

    protected $visible = [
      'id', 
      'name',
      'guard_name',
    ];
}
```

**Comment by erikn69** [comment]
@shadowbane thanks for you reply, i gonna try to handle that
