### ISSUE TITLE
Requesting Permission or a Role?

### ISSUE THREAD

**Issue by andrewhood125** [spatie/laravel-permission#183]
Is there a way to have a user request a permission or a role? 

In my application I have a model and I would like for a user to be able to request _access_ to that via a role or permission. Then have another user with an elevated permission come and approve (or possibly deny) it. 

Is that already supported it a way I'm not thinking about it? If not would it be a feature you would be open to have a patch for?

Perhaps in the form of an `approver_id` on `user_has_permissions` and `user_has_roles`? I'm only vaguely familiar with the codebase but looking to replace what I have with a package 🙂

**Comment by drbyte** [comment]
What you're describing is more application-level logic than what this package does. 

This package lets you specify roles and permissions, assign them to users, and later query whether a given user has a specified permission.

In your case you might add a role for `Approves Permissions` or a permission to `grant permission requests`, and then anyone who has that privilege could perform changes for others. Lots of directions one can take the application from there.

**Comment by andrewhood125** [comment]
Hmm.. I see what you're saying. I suppose determining who would be _authorized_to approve such a request is opening a can of worms. 

I'll leave this open in case anyone wants to continue the conversation but maintainers feel free to close it.

**Comment by freekmurze** [comment]
Agree with @drbyte on this. Do this in your own application. Or, if you want to make the community happy, create your own wrapper package around this one where you add the functionality.
