### ISSUE TITLE
hasRole() -> multiple roles

### ISSUE THREAD

**Issue by ScooterSam** [spatie/laravel-permission#184]
I could be wrong, but I'm pretty sure I'm not..

in the hasRole function, I just saw this as I was about to use it:

```
if (is_array($roles)) {
            foreach ($roles as $role) {
                if ($this->hasRole($role)) {
                    return true;
                }
            }

            return false;
        }
```

Lets say i pass ['user', 'staff', 'admin']

If user is a valid rank, but not staff, it will never reach the check for admin, since it returns true in the loop?
The return true, will break out of the loop and end it, if the first role passed, is true.

Thus meaning.. anything after staff(admin) true or not, will not be checked?

**Comment by freekmurze** [comment]
Use `hasAllRoles` to check if a user has all given roles.
