### ISSUE TITLE
Is it possible to make hasDirectPermission in HasRoles.php public function?

### ISSUE THREAD

**Issue by bakhtiyor** [spatie/laravel-permission#185]
I need to check if user has direct permission or no. Right now, afaik there is no way to do it, but if the function of hasDirectPermission is made public one can use it to check it. What do you think?

**Comment by freekmurze** [comment]
What's your use case where you need to call `hasDirectPermission` directly?

**Comment by bakhtiyor** [comment]
Thank you for the quick reply. I have a form where permissions are set for various operations for users and roles. As permissions of roles are inherited to the user automatically additional permissions also can be added particularly to this user. But inherited permissions shouldn't be changed. That is why we need to check whether its a direct permission of the user or inherited one. Hope I could explain the situation. If you have further questions I am happy to answer. Thank you!

**Comment by freekmurze** [comment]
Ok, I'll accept a PR that makes the method public + adds tests for that method + updates the readme with an example.

**Comment by bakhtiyor** [comment]
Thank you so much. Do you want me to do it or there is somebody else who is responsible for that?

**Comment by freekmurze** [comment]
You can do it 👍

**Comment by bakhtiyor** [comment]
OK thanks. Made changes and created a pull request.
