### ISSUE TITLE
Assign role without team id

### ISSUE THREAD

**Issue by webmastervinay** [spatie/laravel-permission#1855]
I went through your documentation and found that a role without team id will be treated as global role. However, it is throwing error in a fresh Laravel 8.0 Project.

![image](https://user-images.githubusercontent.com/5024049/132984428-6722b165-3748-4922-8d58-dc618052fdc6.png)

**Versions**
- spatie/laravel-permission package version: 5.1.x
- illuminate/framework package: 8.x

- PHP version: 8.0
- Database version: 8.0 (MySQL)

**To Reproduce**
In a fresh Laravel 8 project:

![image](https://user-images.githubusercontent.com/5024049/132984435-2b66f633-92cf-4bcd-9468-ef9f526d3204.png)

![image](https://user-images.githubusercontent.com/5024049/132984438-6a28a679-077f-4287-80de-87f355ff8b78.png)

**Expected behavior**
One should be able to create and assign role without team id

**Environment**
 - OS: MacOS
 - Version BigSur
 - Laravel Valet

**Comment by erikn69** [comment]
This is not a bug, stop duplicates of this

**Comment by webmastervinay** [comment]
Ok. Thanks.
