### ISSUE TITLE
syncRoles() detaches all the roles using the team feature

### ISSUE THREAD

**Issue by cstriuli** [spatie/laravel-permission#1888]
**Describe the bug**
Using the method `syncRoles()` on a user with multiple teams it removes ALL roles from all teams when should remove the roles from the _current team_.

**Versions**
- spatie/laravel-permission package version: 5.1.1
- Laravel version: 8.60.0
- PHP version: 8.0.10
- Database version: MariaDB / 10.6.4 

**To Reproduce**

First create user with the role "**Admin**" for **team 1**
```php
<?php
app(\Spatie\Permission\PermissionRegistrar::class)->setPermissionsTeamId(1);
$user = User::factory()->create();
$user->syncRoles('Admin');
$user->getRoleNames()->toArray(); // returns ['Admin'] ✅
```

Then attach another team and role to the same user
```php
<?php
// #team 2,  assign "Admin" role to the same user
app(\Spatie\Permission\PermissionRegistrar::class)->setPermissionsTeamId(2);
$user = \App\Models\User::latest()->first(); // same user as before
$user->syncRoles('Admin');
$user->getRoleNames()->toArray(); // returns ['Admin'] ✅
```

Finally try to dump the user roles from team 1
```php
<?php
app(\Spatie\Permission\PermissionRegistrar::class)->setPermissionsTeamId(1);
$user = \App\Models\User::latest()->first(); // same user as before
$user->getRoleNames()->toArray(); // returns [] ❌, it should returns the ['Admin'] from team_id 1
```

**Expected behavior**

Synchronization with roles should not affect roles in other teams, only the roles from the current team. 

 **Additional context**
I think the issue comes from the `syncRoles()` method because it detaches all the roles ignoring if the teams feature it's enabled so should filter which roles detach based on the current **team_id**

https://github.com/spatie/laravel-permission/blob/2512d5a22aaae0bab8d62a02e502a603776da9da/src/Traits/HasRoles.php#L187

**Comment by cstriuli** [comment]
> laravel-permission/src/helpers.php

Oh, I didn't know it! Thank you!

**Comment by rossjump24** [comment]
@freekmurze @erikn69  I think there might be a similar issue still when using `assignRole()`. 
```php
setPermissionsTeamId($teamA);
$user->assignRole('admin');

// Change team
setPermissionsTeamId($teamA);
$user->assignRole('editor');

// $user no long has the admin role for $teamA
```

As above you would expect the user to have 2 roles; `admin` for team A, `editor` for team B

I'm on version 5.7.0.

**Comment by erikn69** [comment]
@rossjump24 Hi

Well on your example there is not $teamB, only $teamA, try fixing that first, please

**Comment by rossjump24** [comment]
> @rossjump24 Hi
> 
> Well on your example there is not $teamB, only $teamA, try fixing that first, please

Apologies, fixed

**Comment by erikn69** [comment]
If that doesn't work, try this

```php
setPermissionsTeamId($teamA);
$user->assignRole('admin');

// Change team
$user->unsetRelation('roles');
setPermissionsTeamId($teamB);
$user->assignRole('editor');
```
If it still persist make failing test for try to fix it, or if you know how to fix it make a PR

**Comment by rossjump24** [comment]
Those tests helped me figure it out thanks; in-between checking the roles for team A and team B I had to make sure I switched back to `setPermissionsTeamId($teamA)` and reload the roles relationship on the user with `$user->load('roles')` as it was only checking against the roles assigned for the latest team ($teamB)
