### ISSUE TITLE
Do you Have  a More Detailed way of Using this?

### ISSUE THREAD

**Issue by masterpowers** [spatie/laravel-permission#19]
It would be really best if you can provide an example usage of your package
A wiki perhaps? 
Ive been able to require it in the package and migrate
dont know if i will create a Model App\Permission , App\Roles
to set the database so far i see it is all in the vendor package
Dont really wanna messed up your code
by adding protected $table = 'roles'; etc.
Or can it be extended , or implements 
inside controller or model.
Sorry hope you can really give a detailed set up and usage
:+1:

**Comment by freekmurze** [comment]
I think that most developers with a bit of experience developing Laravel 5 apps will understand how to use the package. 

Currently there is no way to use your own model. Other users have requested this as well and I'm open for merging PR that adds this (see #18)

You're also free to sumit a PR to improve the docs with more clear examples.
