### ISSUE TITLE
Why 'exists' function from Permission Model has been removed?

### ISSUE THREAD

**Issue by bakhtiyor** [spatie/laravel-permission#190]
Why `exists` function from Permission Model has been removed?
I know that there is a function called `findByName`, but it throws an exception, but `exists` function returned `false` if a permission didn't exist. This functionality is needed in a view to check whether a given permission exists or no.

**Comment by freekmurze** [comment]
I don't think there every was and `exists` method provided by this package. I'd accept a fully tested PR (with updates to the readme) that adds this.
