### ISSUE TITLE
How to update the model_has_roles table with a new column and still use the syncRoles method?

### ISSUE THREAD

**Issue by alexv96** [spatie/laravel-permission#1907]
I have a multi tenant system with SPATIE/MULTITENANCY, where the roles and permissions are in the LANDLORD table (DB MULTITENANCYV5) and not in the tenants (DB Tenant).

```
Database LANDLORD
```
![image](https://user-images.githubusercontent.com/33232796/139921051-775d7115-4c84-4ec0-8c05-010566f48e40.png)
![image](https://user-images.githubusercontent.com/33232796/139921151-2432112c-443b-4abb-9dd8-9cbbab6dc757.png)

As you can see in the image, the model_has_roles table has a column called tenant_id, so the question is how could I use the assignRole or async functions with the new column?

Since being a multi-tenant system where a user can be in a company or more with different roles keeping the same email, then that's why I left the roles and permissions in the external landlord database, and so I need to know how I can keep the SYNCROLES, ASSYGNCROLE and SYNC methods with the new column that I added.

**Comment by erikn69** [comment]
Read teams feature documentation
