### ISSUE TITLE
It does not detect the model guard if you use it from the constructor

### ISSUE THREAD

**Issue by mcolominas** [spatie/laravel-permission#1923]
I was doing several tests, and I have discovered if you use multiple guards and try to tell it to be a specific guard from the constructor it doesn't work, but it does work if it is set as an attribute.

This does not work:
```php
class YourCustomPermission extends SpatiePermission
{
    public function __construct(array $attributes = [])
    {
        $this->guard_name = config('xxx.guard');
        parent::__construct($attributes);
    }
}

```

This works:
```php
class YourCustomPermission extends SpatiePermission
{
    public $guard_name = 'custom_guard';

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }
}

```

Reviewing the project code, I have seen that in this line comes the problem, it only obtains the attributes of the class, but not those that are initialized in the constructor:
https://github.com/spatie/laravel-permission/blob/193e50e44dce7b289f475a7df8782c9be0467e39/src/Guard.php#L30

Therefore, if you have the default web guard, and another that is admin, everything you create will be created with the web guard, and when you try to assign it to someone from the admin guard, it will tell you that the permission or role does not exist

**Comment by erikn69** [comment]
Maybe related #1793

could you create a minimal Laravel app that demonstrates the issue? Or maybe create a failing tests for us to look at? [example](https://github.com/Onekone/spatie-issue-example/blob/main/tests/Feature/IssueTest.php)

**Comment by mcolominas** [comment]
The user class is a standard one, making use of the traits
```php
use Spatie\Permission\Traits\HasPermissions;
use Spatie\Permission\Traits\HasRoles;
```
The guards that I have are web and admin.
In the path I use as middleware auth:admin
And I use the classes mentioned above to create the admin roles and permissions

**Comment by mcolominas** [comment]
Yes, this would work, but I had it on, it is that the guard admin is put if or if without passing it by parameter

**Comment by mcolominas** [comment]
If you want to close this bug, or mark it as an improvement, but ideally, it is to obtain the guard, either by attribute or constructor

**Comment by mcolominas** [comment]
Ideally this code will work, since config cannot be used in an attribute.
```php
class AdminPermission extends SpatiePermission
{
    public function __construct(array $attributes = [])
    {
        $this->guard_name = $attributes['guard_name '] ?? config('xxx.guard');
         parent::__construct($attributes);
    }
```
What I want to use, is this class, to create the admin permissions, without passing any additional parameters.

**Comment by erikn69** [comment]
There is
```php
class YourCustomPermission extends SpatiePermission
{
    public function __construct(array $attributes = [])
    {
         $attributes['guard_name'] = config('xxx.guard');
         parent::__construct($attributes);         
    }
    public static function create(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? config('xxx.guard');;

        $permission = static::getPermission(['name' => $attributes['name'], 'guard_name' => $attributes['guard_name']]);

        if ($permission) {
            throw PermissionAlreadyExists::create($attributes['name'], $attributes['guard_name']);
        }

        return static::query()->create($attributes);
    }
}
```

**Comment by mcolominas** [comment]
1.- In this line, `$attributes['guard_name']` not exists, so it gets the guard name of 'Guard::getDefaultName(static::class)'
https://github.com/spatie/laravel-permission/blob/193e50e44dce7b289f475a7df8782c9be0467e39/src/Models/Permission.php#L37

2.- In `Guard::getDefaultName(static::class)` call this, where in model, is a string of the class
https://github.com/spatie/laravel-permission/blob/193e50e44dce7b289f475a7df8782c9be0467e39/src/Guard.php#L17

3.- Therefore execute this line, but since the `guard_name ` has not been defined in the class, but in the constructor, this returns empty collection
https://github.com/spatie/laravel-permission/blob/193e50e44dce7b289f475a7df8782c9be0467e39/src/Guard.php#L30

4.- Since the collection is empty, it returns the default guard that is usually web `config('auth.defaults.guard')`
https://github.com/spatie/laravel-permission/blob/193e50e44dce7b289f475a7df8782c9be0467e39/src/Guard.php#L74

So, wouldn't it be possible for it to also take into account what is initialized in the constructor?

If it is not possible, close the ticket or mark it as an improvement for some later update of the package.

While following your advice, I have added this method and works.
```php
class YourCustomPermission extends SpatiePermission
{
    public static function create(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? config('xxx.guard');
        return parent::create($attributes);
    }
}    
```

**Comment by fredsal** [comment]
Bad idea and you are very confused about how this package works 

This part gets `guard_name` from `Users` model, not from `YourCustomPermission`, so `protected $guard_name = 'custom_guard';` must be on `Users` model only
https://github.com/spatie/laravel-permission/blob/193e50e44dce7b289f475a7df8782c9be0467e39/src/Guard.php#L30

@erikn69 answer is the right solution according laravel documentation

```php
class YourCustomPermission extends SpatiePermission 
{
    public function __construct(array $attributes = [])
    {
         $attributes['guard_name'] = $attributes['guard_name'] ?? config('xxx.guard');
         parent::__construct($attributes);         
    }
    public static function create(array $attributes = [])
    {
        $attributes['guard_name'] = $attributes['guard_name'] ?? config('xxx.guard');
        return parent::create($attributes);
    }
} 
```  
Close this, has no sense

**Comment by erikn69** [comment]
>$guardName = (new \ReflectionClass($class))->getDefaultProperties()['guard_name'] ?? null; 
>$guardName = (new \ReflectionClass($class))->getDefaultProperties()['guard_name'] ?? (new $class)->guard_name ?? null;

It's the same

**Comment by mcolominas** [comment]
It's not the same, with `(new $class)->guard_name ?? null;` I instantiate the class and I can get the attributes that are started from the constructor, with `(new \ReflectionClass($class))->getDefaultProperties()['guard_name']` you only get the attributes defined in the class, ignoring the constructor.

I'm going to close this, if you want to add it or do something else, go ahead, at the moment I have the code that works, although it is duplicated (constructor and create method)

I put what I was doing:
I have 2 guards, web and admin, the web would not have to use any permission or role, only the admin, therefore, create the class mentioned above, where the guard admin was assigned by the builder, once created, just modify ` config/permission.php` to change the Role and Permission class to my own.

**Comment by erikn69** [comment]
I test it
```php
class YourCustomPermission extends SpatiePermission
{
    public $guard_name = 'custom_guard';
}

dd(\Spatie\Permission\Guard::getDefaultName(\App\Models\YourCustomPermission ::class));
// displays "custom_guard"

**Comment by mcolominas** [comment]
The code that you have given me that works, because the attribute is in the class, but I use the `config()` to obtain the guard, therefore I cannot do what you use, I have to do:
```php
class YourCustomPermission  extends Permission
{
    public function __construct()
    {
        $this->guard_name = 'custom_guard';
    }
}

dd(\Spatie\Permission\Guard::getDefaultName(\App\Models\YourCustomPermission ::class));
// displays "web"
```

**Comment by andrekutianski** [comment]
In my scenario I need that User Model can be associate with roles for multiple guards, to accomplish that I just define `$guard_name` on Model as array with all _guard_names_ that can this can be associated.

```php

namespace App\Models;

Class User extends UserModel
{

// ...

protected array $guard_name = ['api', 'web'];

// ...

}

```
