### ISSUE TITLE
Is it possible to set the role of a user that isn't logged in?

### ISSUE THREAD

**Issue by Naishaline** [spatie/laravel-permission#1925]
I'm trying to create a Laravel command that will manage roles based on certain parameters, but I can't seem to find a way to get an object that can use ->syncRoles without being logged in. The only way I've seen to syncRoles is through Auth::user() which I can't access without being logged in. Is there some way with a user ID perhaps?

**Comment by erikn69** [comment]
Not an issue, 
`User::find(id_of_user)->syncRoles([]);`

**Comment by Naishaline** [comment]
When I use that method, I still get `"Call to undefined method Illuminate\Foundation\Auth\User::syncRoles()"`

**Comment by Naishaline** [comment]
I got it to work! I was using the wrong user model. The code you suggested works like a charm! Thank you for your help!
I'm using `App\Models\User` for anyone who may encounter this : )
