### ISSUE TITLE
Not up to date docs in official docs page

### ISSUE THREAD

**Issue by geocfu** [spatie/laravel-permission#1933]
Hello,

The docs in https://spatie.be/docs/laravel-permission/v3/introduction only display the docs for versions v2 and v3, but the latest version is v5.

Why is that?

**Comment by erikn69** [comment]
https://spatie.be/docs/laravel-permission/v5/introduction

**Comment by geocfu** [comment]
I swear, it was not working for the whole afternoon, I even tried with incognito mode. It must be a bug or somebody fixed it after the issue creation.

**Comment by geocfu** [comment]
Seems quite stable since it still allows for selection up to v5. Closing the issue.
