### ISSUE TITLE
Exception when trying to delete permission

### ISSUE THREAD

**Issue by ptifloflo** [spatie/laravel-permission#1937]
Hello,

I'm trying to delete permission with
`$permission->delete()`

but I've got an exception : 
`Illuminate\Database\ClassMorphViolationException
No morph map defined for model [Spatie\Permission\Models\Permission].`

I tried to define `Relation::morphMap` or to call `Relation::requireMorphmap` as I saw on internet but nothing change

My config : 
```
"laravel/fortify": "^1.8",
"laravel/framework": "^8.54",
"spatie/laravel-permission": "5.*",

php version : 7.4.18
```

**Comment by erikn69** [comment]
Upgrade your Laravel Permission

**Comment by ptifloflo** [comment]
I'm sorry, installed versions :

- laravel/fortify : 1.8.4
- laravel/framework : 8.73.2
- spatie/laravel-permission : 5.4.0

I ran an update and only laravel/framework was outdated (8.73.0 => 8.73.2).

Everything's ok. Thanks
