### ISSUE TITLE
How to use with more than one "Users" table?

### ISSUE THREAD

**Issue by kabeda** [spatie/laravel-permission#194]
Hi,
I didn't try this package yet. I'll do it right now.
I wonder how it could be possible to use it with my needs.
I have 
- users table for the administration of my application.
- clients table for the users of my application (they have different url and functionnalities from the administration part).
How should be it possible for the administrator to assign (in different parts of the application) roles & permissions for the users and for the clients?

My question : Is there any way to work with two configs, one for users and the other for clients?

**Comment by freekmurze** [comment]
That package does not provide that out of the box. If you need it to work with multiple user tables, you'll have to write your own glue code.
