### ISSUE TITLE
Permission already exists for guard 'api' and 'name'

### ISSUE THREAD

**Issue by Skynzor** [spatie/laravel-permission#1951]
**Describe the bug**
I am trying to seed Permissions table through my PermissionSeeder but I keep getting the error that guard_name && name are unique. So I can't have multiple first party products using the same permissions but with a different product_id set.

I did comment the `$table->unique(['name', 'guard_name']);` from the permission_table migration, but deeper in the code it still checks if it's unique or not, thus probably calling the 'PermissionAlreadyExists.php' exception. But I don't want to change the package due to future complications if there's going to be a new version.

**Versions**
- spatie/laravel-permission package version: 5.4.0
- PHP version: 7.4.10
- Database version: MariaDB 10.4.14

Here is my example code and/or tests showing the problem in my app:

#### Product 1
` $permissions = array(
            array('guard_name' => 'api', 'product_id' => '1',  'name' => 'role-list',  'created_at' => now(),  'updated_at' => now(),  'deleted_at' => null),`

 #### Product 2
` $permissions = array(
            array('guard_name' => 'api', 'product_id' => '2',  'name' => 'role-list',  'created_at' => now(),  'updated_at' => now(),  'deleted_at' => null),`

`foreach ($permissions as $permission) {
            Permission::create($permission);
        };`

**Expected behavior**
I expected to happen that I could have multiple permissions with the same name for each first party product that check's permissions through the API if I commented out $table->unique in the migration file.

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: Windows 10
 - Version 21H1

**Comment by erikn69** [comment]
That is not an issue, you are doing all wrong, you can't add `product_id` and expect that the package use it as pivot

**Comment by pls-kick-me** [comment]
In my case the code was ok because the problem was in the cache.
