### ISSUE TITLE
@can and auth()->user()->can('permission name') not working

### ISSUE THREAD

**Issue by mehdiii97** [spatie/laravel-permission#1956]
hi guys,
@can directive and can() method not working permission via role,
user has role and role has permissions in my app and i want check permissions via roles not roles.
Does not check the direct permissions and permissions via role.
but $user->hasAnyPermmission() method is working good.

what i can do to fix it?!

**Comment by awebartisan** [comment]
@mehdiii97 how did you manage to solve it? Using **@can** directive to check permissions via a `role` ?
I don't have direct permissions to the User so I keep getting `call to a member function contains() on null`.

**Comment by masiorama** [comment]
I am wondering that too.

**Comment by david34corbalan** [comment]
Hi, I have the same problem as can be verified with Laravel's can() helper, since I don't use direct permissions for the user.
