### ISSUE TITLE
Teams permission setup migration fails after upgrading from 4.*

### ISSUE THREAD

**Issue by saulens22** [spatie/laravel-permission#1957]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/laravel-permission/issues) or in [the discussions](https://github.com/spatie/laravel-permission/discussions).

**Describe the bug**
After upgrading to 5.* and setting up Teams functionality, migration created by `php artisan permission:setup-teams` fails to rename two primary keys.
On first run of `artisan migrate` I get
```SQLSTATE[HY000]: General error: 1025 Error on rename of './forge/#sql-alter-1-643' to './forge/model_has_permissions' (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `model_has_permissions` drop primary key)```

On second run it doesn't try to rename same key, as required columns are there, but it fails on another one:
```SQLSTATE[HY000]: General error: 1025 Error on rename of './forge/#sql-alter-1-659' to './forge/model_has_roles' (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `model_has_roles` drop primary key)```.

On third run migration is successful, but primary keys keys in database are unchanged. This might cause reduced performance as pre-migration primary keys are in the database and they don't contain `team_id` column.

Adding `Schema::disableForeignKeyConstraints();` to migration fixes this issue.

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: 5.4.0
- **laravel**/framework package: v8.76.1

PHP version: 8.1

Database version: MariaDB 10.6.5

**To Reproduce**

- Upgrade from 4.* to 5.*
- Update config to use Teams
- Run `php artisan permission:setup-teams`
- Run `php artisan migrate`

Here is my example code and/or tests showing the problem in my app:
Migration created by `php artisan permission:setup-teams` :
```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddTeamsFields extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $teams = config('permission.teams');
        $tableNames = config('permission.table_names');
        $columnNames = config('permission.column_names');

        if (! $teams) {
            return;
        }
        if (empty($tableNames)) {
            throw new \Exception('Error: config/permission.php not loaded. Run [php artisan config:clear] and try again.');
        }
        if (empty($columnNames['team_foreign_key'] ?? null)) {
            throw new \Exception('Error: team_foreign_key on config/permission.php not loaded. Run [php artisan config:clear] and try again.');
        }

        Schema::table($tableNames['roles'], function (Blueprint $table) use ($tableNames, $columnNames) {
            if (! Schema::hasColumn($tableNames['roles'], $columnNames['team_foreign_key'])) {
                $table->unsignedBigInteger($columnNames['team_foreign_key'])->nullable();
                $table->index($columnNames['team_foreign_key'], 'roles_team_foreign_key_index');
            }
        });

        Schema::table($tableNames['model_has_permissions'], function (Blueprint $table) use ($tableNames, $columnNames) {
            if (! Schema::hasColumn($tableNames['model_has_permissions'], $columnNames['team_foreign_key'])) {
                $table->unsignedBigInteger($columnNames['team_foreign_key'])->default('1');;
                $table->index($columnNames['team_foreign_key'], 'model_has_permissions_team_foreign_key_index');

                $table->dropPrimary();
                $table->primary([$columnNames['team_foreign_key'], 'permission_id', $columnNames['model_morph_key'], 'model_type'],
                    'model_has_permissions_permission_model_type_primary');
            }
        });

        Schema::table($tableNames['model_has_roles'], function (Blueprint $table) use ($tableNames, $columnNames) {
            if (! Schema::hasColumn($tableNames['model_has_roles'], $columnNames['team_foreign_key'])) {
                $table->unsignedBigInteger($columnNames['team_foreign_key'])->default('1');;
                $table->index($columnNames['team_foreign_key'], 'model_has_roles_team_foreign_key_index');

                $table->dropPrimary();
                $table->primary([$columnNames['team_foreign_key'], 'role_id', $columnNames['model_morph_key'], 'model_type'],
                    'model_has_roles_role_model_type_primary');
            }
        });

        app('cache')
            ->store(config('permission.cache.store') != 'default' ? config('permission.cache.store') : null)
            ->forget(config('permission.cache.key'));
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {

    }
}
```

**Example Application**
Will create if needed. 

**Expected behavior**
Migration should be successful.

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: WSL2 Debian + Laravel Sail

**Comment by systemsolutionweb** [comment]
Maybe if you `Update config to use Teams`, you only have to upgrade your migration with the last [create_permission_tables.php](https://github.com/spatie/laravel-permission/blob/main/database/migrations/create_permission_tables.php.stub), also i upgrade to v5 with teams without problems

**Comment by erikn69** [comment]
Not only on upgrade

**To Reproduce**
Steps to reproduce the behavior:

- Delete `xxxx_xx_xx_xxxxxx_add_teams_fields.php` from `database/migrations`
- Update config to disable Teams `'teams' => false,`
- Run `php artisan migrate:fresh`
- Update config to enable Teams `'teams' => true,`
- Run `php artisan permission:setup-teams`
- Run `php artisan migrate`
