### ISSUE TITLE
Integrity constraint violation on creating role with team id

### ISSUE THREAD

**Issue by Jaydeep7248** [spatie/laravel-permission#1966]
When I try to create role with same name but different team id, it doesn't allow to do it and throws the error.

1062 - Duplicate entry 'admin-web' for key 'roles_name_guard_name_unique'

Can you please help in the same?

Thanks.

**Comment by angeljqv** [comment]
If you did use `php artisan permission:setup-teams`(you give almost no information) and get this, it is a bug
https://github.com/spatie/laravel-permission/blob/79f7dbf2b6b21d81209774f5726a0e9f4222dd92/database/migrations/create_permission_tables.php.stub#L46-L50
Solution for you , drop `unique` constraint on db and create a new one with `team_id,name,guard_name`, 
do it directly on db, on migration maybe must be:
```php
$table->dropUnique('roles_name_guard_name_unique');
$table->unique([$columnNames['team_foreign_key'], 'name', 'guard_name']); 
```

**Comment by erikn69** [comment]
If you did use `php artisan permission:setup-teams`(you give almost no information) and get this, it is a bug
https://github.com/spatie/laravel-permission/blob/79f7dbf2b6b21d81209774f5726a0e9f4222dd92/database/migrations/create_permission_tables.php.stub#L46-L50
Solution for you , drop `unique` constraint on db and create a new one with `team_id,name,guard_name`, 
do it directly on db, on migration maybe must be:
```php
$table->dropUnique('roles_name_guard_name_unique');
$table->unique([$columnNames['team_foreign_key'], 'name', 'guard_name']); 
```

**Comment by Jaydeep7248** [comment]
Hello,

Thanks for the reply.

I have used php artisan permission:setup-teams.

I have tried above solution and it worked.

Thanks.
