### ISSUE TITLE
HasPermissions namespace missing from HasRoles trait

### ISSUE THREAD

**Issue by aneetkukreja1** [spatie/laravel-permission#1977]
Installed package in laravel 8, but was unable to add HasRoles trait in User model, because namespace for HasPermissions was missing from HasRoles trait.

So, I added Spatie\Permission\Traits\HasPermissions in HasRoles trait file, and it worked perfectly.

**Comment by erikn69** [comment]
https://github.com/spatie/laravel-permission/blob/94443e59d64c90186c65000ac0859c8120f76379/src/Traits/HasPermissions.php#L3
https://github.com/spatie/laravel-permission/blob/94443e59d64c90186c65000ac0859c8120f76379/src/Traits/HasRoles.php#L3
Not mising, everything is working according to the expected, on `User` models is so obvious that the `namespace` needs to be added, it doesn't even need to be mentioned, but there is on documentation([basic-usage](https://spatie.be/index.php/docs/laravel-permission/v5/basic-usage/basic-usage))
