### ISSUE TITLE
findByName method doesn't work with teams

### ISSUE THREAD

**Issue by grimxd** [spatie/laravel-permission#1992]
When teams are active `Role::findByName('admin')` is creating the following query:
`select * from 'roles' where ('team_id' is null or 'team_id' is null) and 'name' = 'admin' and 'guard_name' = 'web' limit 1`
And if the role was created using  `Role::create(['name' => 'admin', 'team_id' => 1]);` the above query returns 0 results so the package throws: `There is no role named admin`.
I think the `findByName` method should have a third optional parameter for team_id.

**Versions**
```
spatie/laravel-permission   5.5.0 
laravel\framework 8.78
```

PHP version:
7.4

**Comment by erikn69** [comment]
Not a bug, it is a expected behaivor, you always have to set team_id first
