### ISSUE TITLE
ide @hasanyrole() throws error if multiple values exist

### ISSUE THREAD

**Issue by berdjabrahamian** [spatie/laravel-permission#1997]
In my blade template im trying to see if any of the roles a user has access too

`@hasanyrole('admin', 'super-admin')`

`super-admin` exists and the user logged in is assigned that role

`admin` also exists in the db but the logged in user is not assigned that role

When loading the page the following exception is thrown

```
InvalidArgumentException
Auth guard [super-admin] is not defined. (View: ....../src/resources/views/index.blade.php) 
```

Decided to try `dd'ing` without a blade directive
```
Auth()->user()->hasAnyRole('admin', 'super-admin')`
return true
```

removed the `dd` returns true and it works without error;

even tested it by adding a role that isnt in the database and still works as expected.

its clear that the blade directive is throwing the error.

```
prefix
<?php if(auth()->check() && auth()->user()->hasAnyRole(

suffix
)); ?>
```

Versions
- spatie/laravel-permission package version: 5.5.0
- laravel/framework package version: 8.80.0 
- PHP: 8.0.14
- Database: PGSQL 14 
- IDE: PhpStorm 2021.3.1

**To Reproduce**
- Create a user -> assign it a super-admin role
- In phpstorm add a new blade directive following the instructions on the site (https://spatie.be/docs/laravel-permission/v5/advanced-usage/phpstorm)
  - Use the @hasanyrole directive
- in your blade template add:
```
@hasanyrole('admin','super-admin')
something
@endhasanyrole
```
- refresh the page

**Expected behavior**
To return either true or false, based on the user having one of the roles assigned to it.
It should work the same way as doing the following in php or in blade

```
@if( auth()->check() && auth()->user()->hasAnyRole('admin', 'super-admin'))
something
@endif
```

**Environment (please complete the following information, because it helps us investigate better):**
Mac OS 12.1 (21C52) Monteray
M1 Pro 14 Inch

PHP 8.0.14 via homebrew using shivammathur/php/php@8.0
Pgqsql 14 via Postgres App
web server via Caddy server

**Comment by erikn69** [comment]
It is not a bug, you are using it wrong
read documentation: https://spatie.be/docs/laravel-permission/v5/basic-usage/blade-directives#roles

**Comment by berdjabrahamian** [comment]
Ahhhhh, multiple values need to be separated by a pipe.

For the record needs to be

@hasanyrole('role1|role2|role3');
@endhasanyrole


Thanks

**Comment by erikn69** [comment]
maybe also with array `@hasanyrole(['role1','role2','role3']);`

**Comment by berdjabrahamian** [comment]
> maybe also with array `@hasanyrole(['role1','role2','role3']);`

This was throwing the same error.
