### ISSUE TITLE
 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list'

### ISSUE THREAD

**Issue by vrkansagara** [spatie/laravel-permission#2016]
### Code

$administratorRole = **OBJECT**;
$permissions = **ARRAY OF PERMISSIONS**;
$administratorRole->syncPermissions($permissions);

~~~sql
 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: select `id`, `id` as `i`, `name` as `n`, `guard_name` as `g` from `permissions`)
~~~

![image](https://user-images.githubusercontent.com/12006483/153721484-24c41d93-1dba-4f4e-8107-de346a141758.png)
![image](https://user-images.githubusercontent.com/12006483/153721501-1ef06512-6d7a-48bc-85b4-6cefaa302756.png)

#### Composer 
"spatie/laravel-permission": "^5.5",

#### PHP
PHP 7.4.27 (cli) (built: Dec 20 2021 21:28:15) ( NTS )

Can any one help on this !Thanks in advance

**Comment by erikn69** [comment]
You don't have field name on db, maybe you change that on migration file

**Comment by vrkansagara** [comment]
> You don't have field name on db, maybe you change that on migration file

As I have renamed name field to dispy_name still t generating error that's is the question

**Comment by erikn69** [comment]
You can't change the default field names, always must be name, guard_name and id

**Comment by vrkansagara** [comment]
@erikn69  this is something about custom usage of role and permission so it should allow to change.

**Comment by erikn69** [comment]
Not allowed, maybe other package fits better on your application
This is not a bug, it is a expected behaivor

**Comment by erikn69** [comment]
There is information for this on documentation

**Comment by sgtcoder** [comment]
I am having this issue too. I never had this issue in the past. Now they want us to use "name"? I have first_name and last_name.

**Comment by erikn69** [comment]
Look at V2, `id,name,guard_name` have been there from the start, it's not a new thing
https://github.com/spatie/laravel-permission/blob/ec72e41bd084e5acac807fff540f8772b21b17d3/src/Traits/HasRoles.php#L179-L187
https://github.com/spatie/laravel-permission/blob/ec72e41bd084e5acac807fff540f8772b21b17d3/src/Models/Role.php#L84-L88

**Comment by vrkansagara** [comment]
@erikn69  I checked one of my project which is using
~~~bash
"spatie/laravel-permission": "^3.17",
~~~

It is working fine with the `display_name`

**Comment by fredsal** [comment]
In v3 `'name'` was used too, but make a PR if you need it
https://github.com/spatie/laravel-permission/blob/b4d3184b67b974c3053085e7d7762ea88b9215ca/src/Traits/HasRoles.php#L184-L185
https://github.com/spatie/laravel-permission/blob/b4d3184b67b974c3053085e7d7762ea88b9215ca/src/Traits/HasRoles.php#L240-L241
https://github.com/spatie/laravel-permission/blob/b4d3184b67b974c3053085e7d7762ea88b9215ca/src/Traits/HasRoles.php#L254
https://github.com/spatie/laravel-permission/blob/b4d3184b67b974c3053085e7d7762ea88b9215ca/src/Traits/HasRoles.php#L267-L270

**Comment by erikn69** [comment]
I make a PR for this on when V4 was created, but was no merge, maybe you can use the idea to guide you and make a PR
#1837

**Comment by fredsal** [comment]
Just add `name` field in database with null as default, and everything works the same

**Comment by vrkansagara** [comment]
![image](https://user-images.githubusercontent.com/12006483/156811083-b24170d3-6705-4141-8a74-4aa8932af0db.png)


Still this issue is not resolved.

**Comment by fredsal** [comment]
>Still this issue is not resolved.

I don't find the PR where you fix that for review it

**Comment by vrkansagara** [comment]
The issue was regarding the array index into my use case so closing it.
