### ISSUE TITLE
can this package support this scenario?

### ISSUE THREAD

**Issue by yehximin** [spatie/laravel-permission#202]
hi, I am new to laravel and am not sure if this package can do something like this:

restaurant owner role -> only grant edit access ( no delete or create ) to their own restaurant data

restaurant owner will only be able to access the restaurant data after super admin granted access to specific restaurant

**Comment by freekmurze** [comment]
Yup, this package can help you with that use case.

`laravel-permission` allows you store those roles and permissions in the database. It will register those permissions at [Laravel's gate](https://laravel.com/docs/5.4/authorization#gates).
