### ISSUE TITLE
Cannot getting the permissions

### ISSUE THREAD

**Issue by faisalfaiz64** [spatie/laravel-permission#2037]
### Discussed in https://github.com/spatie/laravel-permission/discussions/2036

<div type='discussions-op-text'>

<sup>Originally posted by **faisalfaiz64** March  1, 2022</sup>
when I add permission middleware every time I hit the route it says you don't have permission. I created a role and assigned permission to that role. but it still cannot giving me assess </div>

**Comment by faisalfaiz64** [comment]
solved

**Comment by faisalfaiz64** [comment]
solved

**Comment by syn6UK** [comment]
How was this solved? I'm having the same issue!

**Comment by alikdb** [comment]
how was this solved?

**Comment by parallels999** [comment]
It was solved reading again documentation

**Comment by alikdb** [comment]
Why don't you share your solution? Interesting and funny.

**Comment by parallels999** [comment]
Here is the [solution](https://spatie.be/docs/laravel-permission/v5/basic-usage/basic-usage)

**Comment by alikdb** [comment]
lol, okay

**Comment by alikdb** [comment]
I can't control the permission in the role over the middleware and it's not in the documentation, it's very simple.

**Comment by parallels999** [comment]
Well, every implementation are distinct, don't expect someone to magically know what you did wrong, you should share an [example application](https://spatie.be/docs/laravel-permission/v5/basic-usage/new-app) demonstrating the problem

if you make ambiguous questions, you got ambiguous answers

**Comment by alikdb** [comment]
this is my routes, 
![image](https://user-images.githubusercontent.com/44875945/203634103-1206b17e-94a2-4f95-8af1-d6f90daa2fdb.png)

this my permission access_admin in super-admin roles and journalist
![image](https://user-images.githubusercontent.com/44875945/203634177-cfa634aa-2fdb-492a-b998-0b7b360aab8e.png)

not working is return 403 frobidden

**Comment by parallels999** [comment]
> you should share an [example application](https://spatie.be/docs/laravel-permission/v5/basic-usage/new-app) demonstrating the problem

**Comment by alikdb** [comment]
Is the api `guard_name` controller also used?

**Comment by parallels999** [comment]
[multiple guards](https://spatie.be/docs/laravel-permission/v5/basic-usage/multiple-guards)
