### ISSUE TITLE
@role displaying on page when spatie/markdown in use

### ISSUE THREAD

**Issue by kaptk2** [spatie/laravel-permission#2038]
**Describe the bug**
When spatie/laravel-markdown and spatie/laravel-permission are installed the @role type directives are displayed as part of the HTML.

**Versions**
- spatie/laravel-permission package version: 5.5.0
- spatie/laravel-markdown: 2.2.1
- illuminate/framework package: v8.83.2

PHP version: 8.0.16

Database version: mysql  v 8.0.28

**To Reproduce**
Have both laravel-markdown and laravel-permission installed and inside a blade view include both <x-markdown> and an @role type directive. When the page is rendered the @role is output as text

Here is my example code and/or tests showing the problem in my app:
`<x-markdown>{{ $markdown }}</x-markdown> @role('admin')<a href='/admin'>Admin Panel</a>@endrole`

**Example Application**
Here is a link to my Github repo containing a minimal Laravel application which shows my problem: https://github.com/kaptk2/permission-issue

**Expected behavior**
I expected the custom blade directives to be honored and not displayed to the end user.

 **Additional context**
This issue also exists with Laravel 9, the example repository above is using Laravel 9.

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: Ubuntu
 - Version 20.04

**Comment by erikn69** [comment]
> Here is a link to my Github repo containing a minimal Laravel application which shows my problem: https://github.com/kaptk2/permission-issue

Where is the issue on that repo??
https://github.com/kaptk2/permission-issue/blob/49335c5c6e3d5519a63d31116da827612ff9a3c5/composer.json#L7-L13
you don't even have this package as a requirement on that repo

Looks like markdown problem, not problem on spatie/laravel-permission

**Comment by kaptk2** [comment]
Whoops, I forgot to push my changes. I have corrected now. You might be right that this is an issue with the markdown package.

**Comment by erikn69** [comment]
@kaptk2 try #2039

**Comment by kaptk2** [comment]
@erikn69 that seems to be working me both in the example app and my production one.

**Comment by erikn69** [comment]
@kaptk2 let your comment on the PR(more chances to get merged)

**Comment by tabacitu** [comment]
Hey guys,

I think that's a bug in `laravel-markdown`, NOT in `laravel-permission`. 

To fix this, I believe `laravel-markdown` should use `afterResolving` to load its directives. I think that's the safest way to go, since that has 25k downloads and `laravel-permission` has 7M downloads. Details in https://github.com/spatie/laravel-permission/pull/2047 but that's the TLDR.

Cheers!
