### ISSUE TITLE
Target class [blade.compiler] does not exist.

### ISSUE THREAD

**Issue by dencygb** [spatie/laravel-permission#2044]
While using with `"laravel/lumen-framework": "^8.3.1"`, it gives the following error.

![image](https://user-images.githubusercontent.com/6583127/156634177-49a87b14-eb95-40fe-b9ec-86bb6b9765f6.png)

**Comment by erikn69** [comment]
I think that moving `registerBladeExtensions` from register to boot method fix this, give a try and tell me(I'm not using lumen)
https://github.com/spatie/laravel-permission/blob/677903c69460a1867da833979a0dfdffd163767d/src/PermissionServiceProvider.php#L42

**Comment by tabacitu** [comment]
Hey there! PR https://github.com/spatie/laravel-permission/pull/2047 will solve this. This is such a deep rabbit hole... but we can do this! 💪😅

**Comment by angeljqv** [comment]
@freekmurze must be closed after https://github.com/spatie/laravel-permission/pull/2048
