### ISSUE TITLE
Getting Forbidden error when not set APP_ENV variable 

### ISSUE THREAD

**Issue by parth-ka-patel** [spatie/laravel-permission#2052]
**Describe the bug**
**Is it required to compulsory to set APP_ENV in .env file ?**
I am getting error when login through some limited permission user credential and not set the APP_ENV variable value in .env file 
is there any way to figure out the problem and run the project successfully ?

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: 3.18.8
- illuminate/framework package : 8.54.0

PHP version:  7.4.28

Database version:  

**To Reproduce**
Not Set the APP_ENV variable and try to login through some specific permission allowed user credentials

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: Ubuntu 
 - Version 20.04.4 LTS

**Comment by erikn69** [comment]
> spatie/laravel-permission package version: 3.18.8

V3 is not supported, but it seems that the exception is for the logged in user
