### ISSUE TITLE
Get all user permissions.

### ISSUE THREAD

**Issue by gcphost** [spatie/laravel-permission#207]
Looking at the `$user->permissions` it seems to only return the related permissions and not any permissions inherited from roles.

In my case I need the all users permissions, including those  from roles.

I ended up doing this in my `User` model:

```
public function allPermissions()
{
    return $this->roles()->with('permissions')->get()->map(function ($item) {
        return $item->permissions->pluck('name');
    })->flatten()->merge($this->permissions->pluck('name'));
}
```

Then I can get all permissions, including those from roles:
```
$user->allPermissions();
```

Thought I'd share here to see if you were interested in this.

Thanks for another great package :D

**Comment by freekmurze** [comment]
`v1.11.0` introduces these new methods: `getDirectPermissions`, `getPermissionsViaRoles`, `getAllPermissions`.

**Comment by gcphost** [comment]
> freekmurze released this 2 minutes ago

Nice :D

**Comment by MirilTerolli** [comment]
@freekmurze , I am trying to use the method **getPermissionsViaRoles** but for me returns an empty array. 
I am at the user model, I am using the *HasRoles* trait, and proceed as following:    
```dd(Auth::user()->getPermissionsViaRoles());```
It returns an empty array. I have checked the *HasRoles* trait, and it uses the *HasPermissions* trait where the *getPermissionsViaRoles* method is declared.     
What am I doing wrong?

**Comment by drbyte** [comment]
What is the output of
dd(Auth::user()->roles)
and
dd(Auth::user()->permissions)

**Comment by MirilTerolli** [comment]
The output would be:    
```
Collection {#1164
  #items: []
}
````

**Comment by MirilTerolli** [comment]
@drbyte , @freekmurze , please ignore my comments. The problem with Auth::user() was on my hand due to a bug. The methods works just fine. 
:Thanks.

**Comment by dgtlslave** [comment]
@MirilTerolli Hi, What about problem with Auth::user(), what you mean. I have the same issue. Thanks

**Comment by drbyte** [comment]
@dgtlslave Most likely you have declared methods in your User model that are overriding the methods in the traits.

**Comment by MirilTerolli** [comment]
@dgtlslave the issue for me was that, due to some other reasons, no Spatie related, I have overwritten the "User", pointing to another table, other than the "users" table.  At that point, my Auth::user() was looking at 'users' table, while that was empty. I had to modify my config/auth.php file as following:
`'providers' => [
        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],     
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
    ]`
Unfortunately It was not Spatie-related issue.
