### ISSUE TITLE
Specified key was too long

### ISSUE THREAD

**Issue by learnkitir** [spatie/laravel-permission#2082]
When I try to install this package in Laravel 9, I get the following error when executing the Migrate command:

 SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `permissions` add unique `permissions_name_guard_name_unique`(`name`, `guard_name`))

I have used the following command in my serviceprovider, but the problem was not solved
Schema::defaultStringLength(191);

**Comment by learnkitir** [comment]
> When I try to install this package in Laravel 9, I get the following error when executing the Migrate command:
> 
> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `permissions` add unique `permissions_name_guard_name_unique`(`name`, `guard_name`))
> 
> I have used the following command in my serviceprovider, but the problem was not solved Schema::defaultStringLength(191);

I found my answer in this thread
https://github.com/spatie/laravel-permission/issues/1689

**Comment by erikn69** [comment]
Close this
