### ISSUE TITLE
typeError Illegal offset type

### ISSUE THREAD

**Issue by CaileanJoij** [spatie/laravel-permission#2083]
I get an typeError illegal offset type when trying to assignRole to a user in the seeder. I have changed the default migrations up a bit to support UUID's Is this something I have wrote incorrectly? The roles and permissions do have a uuid in them when i seed them.

Error i get when i try to seed
![Screenshot_26](https://user-images.githubusercontent.com/99649121/166705438-a6ae0f57-a235-4307-8302-80b64b1977bb.png)
Seeder
![Screenshot_27](https://user-images.githubusercontent.com/99649121/166705442-c7d53200-a3e1-4b8c-a3ca-cd8e5af5b2db.png)
Migrations
![Screenshot_28](https://user-images.githubusercontent.com/99649121/166705444-28c52682-6a30-419e-84c1-0c3213dc9184.png)
![Screenshot_29](https://user-images.githubusercontent.com/99649121/166705446-3c424e07-e2cf-4d90-8168-412398375088.png)
![Screenshot_30](https://user-images.githubusercontent.com/99649121/166705450-e8ef04dc-1182-4c75-95ea-4cf6c408229b.png)
User model
![Screenshot_31](https://user-images.githubusercontent.com/99649121/166705451-ec711172-7236-4651-8467-954f4a6abe8d.png)

**Comment by erikn69** [comment]
It is not a bug
https://spatie.be/docs/laravel-permission/v5/advanced-usage/uuid#content-models

**Comment by CaileanJoij** [comment]
Thank you, i changed the uuid format to one we are already using(same as in the user model). but that ofcourse fucked up the model. Thanks for the guidance
