### ISSUE TITLE
New Laravel 5.3.* installation. vendor publish throws error

### ISSUE THREAD

**Issue by scottmcdhome** [spatie/laravel-permission#212]
Scott@mainpc /cygdrive/c/wamp/www/scaffold2
$ php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to a member function connection() on null

I am trying to follow steps for scaffold-interface which uses your package. When I run the php artisan vendor:publish command I receive the error above. If I comment out your package in app.php providers the publish works without error.
[](http://amranidev.github.io/blog/site/scaffold-interface/#laravel-supported-versions)

**Comment by AlexVanderbist** [comment]
Hi @scottmcdhome !

I've tried to reproduce your issue but I everything seemed to work for me using Laravel 5.3.30 and `scaffold-interface` 1.7.1 (on PHP 7.1).

However I did find out the error occurs when you put the 4 providers at the top of the providers array. Could you make sure you've placed the providers bellow the `Illuminate` providers in `config/app.php`? The correct place is bellow the following comment: 
```php
/*
 * Package Service Providers...
 */
```

If this doesn't solve your issue please let us know which Laravel, scaffold-interface and PHP versions you are using. Thanks!

**Comment by scottmcdhome** [comment]
That is what I ended up figuring out on my own. Glad it wasn't just me. 
Thanks for responding.
