### ISSUE TITLE
Swoole and permissions (5.5.4) + JWT still having problems

### ISSUE THREAD

**Issue by avlima** [spatie/laravel-permission#2120]
Laravel version: 8.5.22
PHP version: 8.1
Swoole: 4.8.9
Cache driver: default (file)
Package version: 5.5.4 (latest)

Hello friends!

I'm still having problems with permission using swoole, I saw that in the current version `5.5.4 (latest)` it should already be working, but I still have the same problem.

**Bug**
I noticed that when clearing the cache, my first request returns the correct data with permission, but if I then make a new request they will no longer exist, as in the example:

**Example**
First request after clear all caches:
```
{
	"data": {
		"access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU1OTA1MTAwLCJleHAiOjY4Mzk5MDUxMDAsIm5iZiI6MTY1NTkwNTEwMCwianRpIjoiUTJ0WnpSZkdEc2ZUb2ZjbyIsInN1YiI6IjMzY2U2ZDAwLTM3YWMtMTFlYS1iMzNkLWZkZGVjMDIzZTZiMSIsInBydiI6ImEzNTY4ZGZmMWFjYWYyOWQ3ZGJiNmNlOTU5YmE0NGU1ZmViOGMxMjkiLCJuYW1lIjoiSU5GT1ZJU1QiLCJlbWFpbCI6ImRldkBpbmZvdmlzdC5jb20uYnIifQ.W9IpNCFPi_EP2V9MkW-plRevFK1b9fZHP60TFTv09Nc",
		"token_type": "bearer",
		"expires_in": 6839905100,
		"created_at": 1655905100,
                // User permission is super admin
		"user": {
			"id": "12345",
			"email": "dev@email.com.br",
			"is_super_admin": true
		}
	},
	"status_code": 200
}
```

Second request:
```
{
	"data": {
		"access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL2xvZ2luIiwiaWF0IjoxNjU1OTA1MTAwLCJleHAiOjY4Mzk5MDUxMDAsIm5iZiI6MTY1NTkwNTEwMCwianRpIjoiUTJ0WnpSZkdEc2ZUb2ZjbyIsInN1YiI6IjMzY2U2ZDAwLTM3YWMtMTFlYS1iMzNkLWZkZGVjMDIzZTZiMSIsInBydiI6ImEzNTY4ZGZmMWFjYWYyOWQ3ZGJiNmNlOTU5YmE0NGU1ZmViOGMxMjkiLCJuYW1lIjoiSU5GT1ZJU1QiLCJlbWFpbCI6ImRldkBpbmZvdmlzdC5jb20uYnIifQ.W9IpNCFPi_EP2V9MkW-plRevFK1b9fZHP60TFTv09Nc",
		"token_type": "bearer",
		"expires_in": 6839905100,
		"created_at": 1655905100,
                // Auth::user() or getPermissions return empty
		"user": {
			"id": null,
			"email": null
			"is_super_admin": null
		}
	},
	"status_code": 200
}
```

If i try anywhere other route return:
```
{
	"message": "User does not have the right permissions."
}
```

My app run with:
```
php /var/www/app/artisan octane:start --server=swoole --max-requests=1000 --workers=4 --task-workers=12
```

This environment already runs on an ECS with two tasks, we are scaling the application.
Would it be a problem to be running 4 workers and my cache is file?
Any idea how to remedy this?

**Environment**
 - OS: Linux (Ubuntu)

**Comment by avlima** [comment]
> Are you using teams?
> 
> > Auth::user() or getPermissions return empty
> 
> Maybe you are using another guard `Auth::guard('api')->user()`
> 
> it not seems a bug from this package

Hey
Anyway, it was just an example that brings the `super admin` even taking the user authenticated by the token it returns the error for lack of permissions permission, so much so that in public routes I can access normally, only those that require role or permission that do not access.

**Comment by erikn69** [comment]
Sorry i am not using Swoole, and to me is impossible to know without the code or at least a failing test on a laravel minimal application on a fresh installation

**Comment by avlima** [comment]
I configured the cache using Redis and it didn't work either.
I configured the permission.php `'store' => 'array',` and it didn't work either

**Comment by erikn69** [comment]
>Sorry i am not using Swoole, and for to me is impossible to know without the code, or at least a failing test or a laravel minimal application on a fresh installation
Feel free to make a PR to fix that

**Comment by avlima** [comment]
@drbyte help me!

**Comment by avlima** [comment]
Hi,

I discovered a problem, actually Auth::user() doesn't keep up to date in swoole, even the cache and session in Redis.
I tried:
```
\Auth::user()
\Auth::guard('web')->user()
\Auth::guard('api')->user()
```

It is only fed on the first request when the cache and sessions are clean, a second call it returns null

**Comment by avlima** [comment]
Hi,

I solved with:
``
`
Auth::setUser(JWTAuth::user());
``
`

Thaks!!!

**Comment by erikn69** [comment]
If it was solved, close it

**Comment by avlima** [comment]
I had already put this and even so I needed to use the set using JWT to work.

Thank you for everything!
