### ISSUE TITLE
Minor sed issue with the example app

### ISSUE THREAD

**Issue by acharseth** [spatie/laravel-permission#2132]
Hi!

I just started creating a new Laravel app and followed your instructions on [https://spatie.be/docs/laravel-permission/v5/basic-usage/new-app]() for using Spatie for RBAC role handling. When using [Example App](https://spatie.be/docs/laravel-permission/v5/basic-usage/new-app#content-creating-a-demo-app) as a template in creating an app using Foritfy, Jetstream and Livewire, I got an issue with the sed commands. It seems to me like the instructions are assuming a comma separated use list while after installing Livewirel this is not comma separated but one use statement pr line. So I seem to have fixed this by replacing:

	sed -i '' $'s/use HasApiTokens, HasFactory, Notifiable;/use HasApiTokens, HasFactory, Notifiable;\\\n    use \\\\Spatie\\\\Permission\\\\Traits\\\\HasRoles;/' app/Models/User.php

with:

	sed -i '' $'s/use Notifiable;/use Notifiable;\\\n    use \\\\Spatie\\\\Permission\\\\Traits\\\\HasRoles;/' app/Models/User.php

This addes the Spatie use statement after `use Notifiable;` (not after the last use statement if that was the purpose, but I guess it does not matter).

PS: Please let me know if I should report documentation bugs in some other Way.

Arne

**Comment by acharseth** [comment]
> https://github.com/laravel/laravel/blob/master/app/Models/User.php https://github.com/laravel/laravel/blob/b331e10aca58d771511cd3f03e762ca4dea9183e/app/Models/User.php#L11-L13
> 
> ```
> class User extends Authenticatable
> {
>     use HasApiTokens, HasFactory, Notifiable;
> ```

Looking into this I realize I had not invested this good enough before posting this issue and should have provided more information about my installation. I have followed the instructions just as an example, not litarally. What I have done in adition is to install Fortify, Jetstream and Livewire and it is Livewire which changes the User.php. More spesifically this command on the Livewire installation: `php artisan jetstream:install livewire`. This changes the User.php to this:

	<?php
	
  	  namespace App\Models;
  
  	  use Illuminate\Contracts\Auth\MustVerifyEmail;
  	  use Illuminate\Database\Eloquent\Factories\HasFactory;
  	  use Illuminate\Foundation\Auth\User as Authenticatable;
	  use Illuminate\Notifications\Notifiable;
	  use Laravel\Fortify\TwoFactorAuthenticatable;
	  use Laravel\Jetstream\HasProfilePhoto;
	  use Laravel\Sanctum\HasApiTokens;
	  
	  class User extends Authenticatable
	  {
	      use HasApiTokens;
	      use HasFactory;
	      use HasProfilePhoto;
	      use Notifiable;
	      use TwoFactorAuthenticatable;
	...

So may be the Spatie instructions for the exampel app should include a note that if Livewire is installed then the sed command should be changed?

**Comment by acharseth** [comment]
Another issue:
The command `php artisan migrate:fresh --seed --seeder=PermissionsDemoSeeder` drops all tables! When setting up a complete new environment this is fine but if you use the example as a template, which I do, then it was unfortunate to drop all tables. Is this necessary or could the command be run without `:fresh`which I assume is the issue here.
Anyway I think it would be nice to add a note that this command drops all tables.

**Comment by erikn69** [comment]
Please read all the page first https://spatie.be/docs/laravel-permission/v5/basic-usage/new-app#content-creating-a-demo-app
It is not to much to read, you can do it
>The examples on this page are primarily added for assistance in creating a quick demo app for troubleshooting purposes, to post the repo on github for convenient sharing to collaborate or get support.

**Comment by acharseth** [comment]
OK, thanks for the information.
Could be worth putting a note on these though in case others make the same mistakes. I will close the issue.
