### ISSUE TITLE
User foreign key issue when changing the User model name

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-permission#214]
Hi,
I'm using 5.4, and I set 'admins' instead users table.
So when I try this :
```
if (! $request->user()->hasRole($role)) {
       abort(403);
    }
```
An error occurs :

> Unknown column 'admin_has_roles.admin_id' in 'field list'

So I resolved this issue by adding an entry in **laravel-permission.table_names** config file, lets call it **user_foreignkey**

Here my updates :
**laravel-permission** config file :

  ```
 'table_names' => [

        'user_foreignkey' => 'admin_id', // by default : 'user_id'

        /*
        * The table that your application uses for users. This table's model will
        * be using the "HasRoles" and "HasPermissions" traits.
        */

        'users' => 'admins', 

```

**create_permission_tables.php.stub** migration file :

       ``` 
       Schema::create($config['user_has_permissions'], function (Blueprint $table) use ($config) {
            $table->integer($config['user_foreignkey'])->unsigned();
            $table->integer('permission_id')->unsigned();

            $table->foreign($config['user_foreignkey'])
                ->references('id')
                ->on($config['users'])
                ->onDelete('cascade');

            $table->foreign('permission_id')
                ->references('id')
                ->on($config['permissions'])
                ->onDelete('cascade');

            $table->primary([$config['user_foreignkey'], 'permission_id']);
        });

        Schema::create($config['user_has_roles'], function (Blueprint $table) use ($config) {
            $table->integer('role_id')->unsigned();
            $table->integer($config['user_foreignkey'])->unsigned();

            $table->foreign('role_id')
                ->references('id')
                ->on($config['roles'])
                ->onDelete('cascade');

            $table->foreign($config['user_foreignkey'])
                ->references('id')
                ->on($config['users'])
                ->onDelete('cascade');

            $table->primary(['role_id', $config['user_foreignkey']]);
        });

```

Thank you so much for this nice package :)

**Comment by AEK-BKF** [comment]
Please could you add that attribute 'user_foreignkey' in the config file ? 
What did you say about my proposition ? thanks.

**Comment by freekmurze** [comment]
Sorry, I did not see a question in your original issue. I thought that you were simply sharing your solution.

I think it's a good solution if you're using a table that is not called `users`. I'm not going to include this in the package itself because probably most people will just have a table called `users`.

**Comment by AEK-BKF** [comment]
Thanks for quick answer,
I think it's recommended since multi-auth,
Also, since you set possibility to change 'users' table name, this update should be added ! otherwise people who change users table name, will get that error ! 
Thanks.

**Comment by freekmurze** [comment]
You're right, for multi auth this is needed. Reopening...

**Comment by freekmurze** [comment]
Tagged as `1.12.0`
