### ISSUE TITLE
getAllPermissions() does not inherit role permissions

### ISSUE THREAD

**Issue by inodesrl** [spatie/laravel-permission#2155]
**Describe the bug**
Hello,
Using $user->getAllPermissions() , return only the direct permission of the user, and not all the permissions (roles + user)
And also using $user->hasPermissionTo('name') on permission attached to a role of the user, return always "false"
I followed exactly the instructions for use
All the permission are in the table "model_has_permissions" (for user model and role model, see attacched file)
Thanks.

**Expected behavior**
I expect that the method "$user->getAllPermissions()" return permissions of the user and also of the roles attacched to the user.

-------------------------------------

**Version**

Laravel  Framework 9.24.0
PHP ver. 8.1
spatie/laravel-permission  ver. 5.5.5 

---------------------------------------------

**To Reproduce**

**DB:**
![Cattura](https://user-images.githubusercontent.com/21054404/184997761-e18e133a-f64e-4550-bc8f-8e71b194b886.PNG)

**Here is my code**

$user = User::find(5);
$permissions = $user->getAllPermissions();
dd($permissions);

![Cattura1](https://user-images.githubusercontent.com/21054404/185053236-ad190526-4f83-4d26-bddb-03e0dcf161ed.PNG)

$roles = $user->getRoleNames();
dd($roles);
![Cattura3](https://user-images.githubusercontent.com/21054404/185056759-2f03ff93-e803-4b63-935e-0af2d79a0974.PNG)

$role = Role::find(8);
dd($role->permissions);
![Cattura2](https://user-images.githubusercontent.com/21054404/185053857-fb5c5f41-9078-48cd-870b-9208f565c716.PNG)

**Comment by cesarreyes3** [comment]
Not knowing how to use it is not a bug or an issue
Read documentation

**Comment by inodesrl** [comment]
I solved the problem.

In the RoleController.php 
before:
use App\Models\Role;
after:
use Spatie\Permission\Models\Role;

This work fine!
sorry for the inconvenience.

**Comment by vijay-torani** [comment]
> 

i have same error but this not work for me any other chnages that you made to your code.
