### ISSUE TITLE
@can and hasAnyPermission don't they have the same function?

### ISSUE THREAD

**Issue by Askancy** [spatie/laravel-permission#2156]
**Describe the bug**
@can and hasAnyPermission don't they have the same function?
**Versions**
- spatie/laravel-permission          5.5.5
- laravel/framework                  v9.17.0
PHP version: 8.1.6
Database version: MariaDB 10.3.34

**To Reproduce**
I was trying to use a permission check in the blade using @can, with the @can I needed to check multiple permissions, but the gate result is "null" 
I expected that:
`@can('Compagnia|Eventi|Slide|Console')`
Was the equivalent of:
`@if(Auth::user()->hasAnyPermission(['Compagnia', 'Eventi', 'Slide', 'Console']))`

 **Additional context**

Ecco il gate usando il @can

```
array:4 [
  "ability" => "Articoli|Recensioni|Anteprime|Video|Gallery|Trofei"
  "result" => null
  "user" => 2
  "arguments" => "[]"
]
```

**Comment by cesarreyes3** [comment]
>`@can('Compagnia|Eventi|Slide|Console')`

that does not exist, read laravel documentation
