### ISSUE TITLE
Multiple connections are not work with scopes User::permission() and User::role()

### ISSUE THREAD

**Issue by zoibana** [spatie/laravel-permission#2158]
I have two databases

users table stores in database1
and all other tables (including roles/permissions) - stores in database2

Using scopes `User::permission('PERMISSION_NAME')->first()`  or `User::role('ROLE_NAME')->first()` cause sql error:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database1.permissions' doesn't exist (SQL: select count(*) as aggregate from `users` where (exists (select * from `permissions` inner join `model_has_permissions` on `permissions`.`id` = `model_has_permissions`.`permission_id` where `users`.`id` = `model_has_permissions`.`model_id` and `model_has_permissions`.`model_type` = App\Models\User and `permissions`.`id` in (1)) or exists (select * from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `users`.`id` = `model_has_roles`.`model_id` and `model_has_roles`.`model_type` = App\Models\User and `roles`.`id` in (1))))`

Model User has property $connection = 'database1';
Extended model Permission has property $connection = 'database2';
Extended model Role has property $connection = 'database2';

**Versions**
- spatie/laravel-permission package version: 5.5.5   
- illuminate/framework package - 8.83.23

PHP version: PHP 7.4.30

Database version:
8.0.22 - MySQL Community Server - GPL

**To Reproduce**

1. Create user table in database1, specify connection to database1
2. Apply permmission migration on database2
3. Extend models Permission and Roles and specify connection to database2
4. Call User::permission('ANY PERMISSION NAME')->first();

**Expected behavior**
Query must return User models with specified permission

**Comment by angeljqv** [comment]
Not knowing how to use it is not a bug or an issue, read other issues and discussions about this

**Comment by scaabel** [comment]
@zoibana The tables are in separate databases, to make it work you will need to create a users table in database2 and a new user model that connects to the database2.

**Comment by zoibana** [comment]
@scaabel but all other methods and relations are work.
So it's definitely not a problem of different databases.

**Comment by erikn69** [comment]
You have to set the database2 on config

**Comment by zoibana** [comment]
@erikn69 thank you so much! 
It works!
