### ISSUE TITLE
Blade directive `@hasanyrole` does not work with array of role names

### ISSUE THREAD

**Issue by boryn** [spatie/laravel-permission#2165]
Using blade templates this works:
```blade
@hasanyrole('admin|manager')
        It works
@endhasanyrole
```

Unfortunately this piece of code raises an error:
```blade
@hasanyrole(['admin', 'manager'])
        This should work, too
@endhasanyrole
```

The error points to the line with `@hasanyrole` and says: `ParseError syntax error, unexpected ']', expecting ')'`

According to documentation at https://spatie.be/docs/laravel-permission/v5/basic-usage/blade-directives we should be able to pass `$collectionOfRoles`

PS. This works as well:
```blade
@if(auth()->user()->hasAnyRole(['admin', 'manager']))
        This works as well
@endif
```

**Versions**
- spatie/laravel-permission package version: 5.5.5
- laravel: 8.79.0
- PHP version: 7.4.19
- Database version: 10.6.4-MariaDB-log

**Expected behavior**
`@hasanyrole` should accept arrays

**Comment by erikn69** [comment]
Hi, test my last PR

**Comment by boryn** [comment]
@erikn69 thank you! Seems to be working for me :)

PS. I wonder if this should be valid as well? I mean using Laravel collection (`Illuminate\Support\Collection` or `Illuminate\Database\Eloquent\Collection`)
```blade
@hasanyrole(collect(['admin', 'manager']))
    Collection should work as well?
@endhasanyrole
```

**Comment by erikn69** [comment]
>PS. I wonder if this should be valid as well? I mean using Laravel collection

I don't think so, but test it

**Comment by boryn** [comment]
> > PS. I wonder if this should be valid as well? I mean using Laravel collection
> 
> I don't think so, but test it

I just checked - it does not work. IMHO it's not necessary to support collections, but wording of "$collectionOfRoles" in the documentation may be misleading. Maybe the example should say about "$arrayOfRoles"?

**Comment by erikn69** [comment]
collection  of roles are supported, collection of strings(only name) are not supported
