### ISSUE TITLE
Users table with non-standard primary key causes unexpected behavior

### ISSUE THREAD

**Issue by androidacy-user** [spatie/laravel-permission#2178]
**Before creating a new bug report**
[x] I was the one who created the discussion originally

**Describe the bug**
Our `Users` model didn't use a standard auto-incrementing `id` column, but rather a unique (but not auto incrementing) `token` column (which was the api token of the user)

**Versions**
- spatie/laravel-permission package version: 5.5.5
- illuminate/framework package 9.27.x - 9.30.1

PHP version:
8.1.9

Database version:
mysql  Ver 15.1 Distrib 10.9.2-MariaDB

**To Reproduce**
- Create Users table but ensure non-default primary key without auto-incrementing attribute
- Assign roles/permissions
- Notice the roles randomly get "forgotten" and permissions "reset"

Here is my example code and/or tests showing the problem in my app:
App is proprietary. However, our example is a call to `/auth/me` returns user data, and after a random interval of time the admin user would start showing as Guest role.

**Example Application**
n/a

**Expected behavior**
Either this behavior is documented or the package handles non-standard Users models correctly.

 **Additional context**
n/a

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: Ubuntu
 - Version 22.04

**Comment by erikn69** [comment]
**This is not a bug or an issue**
First of all this package does not offer support for unconventional primary keys, you could try by your own responsibility

https://spatie.be/docs/laravel-permission/v5/advanced-usage/uuid#content-reminder
>Again, since each UUID implementation approach is different, some of these may or may not benefit you. As always, your implementation may vary.

If you think that there is an issue, make a failing test or a laravel minimal application on fresh installation demonstrating the bug
[laravel-permission/example-app](https://spatie.be/docs/laravel-permission/v5/basic-usage/new-app)

> App is proprietary.

that doesn't mean you can't create a sample app on clean installation just demonstrating the problem
