### ISSUE TITLE
Problem using first artisan migrate in Laravel 5.4

### ISSUE THREAD

**Issue by strikermdd** [spatie/laravel-permission#218]
Hi, i´m trying to install this package in a clean laravel 5.4 install and using utf8-mb4 database, and it gives me this error: 

 [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter tabl
  e `roles` add unique `roles_name_unique`(`name`))

 [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Its necessary to change something to be able to work with this database collation in Laravel 5.4 and your package migration?

**Comment by drbyte** [comment]
Ref: https://laravel-news.com/laravel-5-4-key-too-long-error
