### ISSUE TITLE
Problem with sync role to user when param teams is true

### ISSUE THREAD

**Issue by lunuzzerin** [spatie/laravel-permission#2188]
Hello, have a little problem when try sync role and the value of the param `teams` in config is `true`.

The way i use to for sync role with is the next:

```php
        $user = User::create([
            'first_name'        => 'Administrador',
            'last_name'         => 'Sistema',
            'number_document'   => '1088348388',
            'id_type_document'  => '1',
            'email'             => 'root@cetrujillo.com',
            'password'          => '123',
        ]);

        $user->companies()->sync('1');

        $role = Role::create(['name' => 'Super Admin', 'guard_name' => 'api', "company_id" => '1']);
        $user->assignRole([$role]);
```

i can see the next with view the code the method for `assignRole` in the trait `HasRoles`

```php
$array[$role->getKey()] = PermissionRegistrar::$teams && !is_a($this, Permission::class) ?
                [PermissionRegistrar::$teamsKey => getPermissionsTeamId()] : [];
```

when call the method `getPermissionsTeamId` return `null`, then at moment to the execute query generate error because the field indicate in the param `team_foreign_key` value is `null`.

Note: sorry for my english, but i don't speak english, i speak spanish.

Thanks.

**Comment by erikn69** [comment]
You forget `setPermissionId`
