### ISSUE TITLE
auth:user()->roles returning every role instead of just the assigned ones

### ISSUE THREAD

**Issue by IGedeon** [spatie/laravel-permission#2190]
Hi,

Thank you for this great package and all other open-source packages you provide. I would love to do a PR about this myself but I just couldn't figure out the fix.

I really appreciate the time you take to reply every issue.

I have found that under certain conditions where a relationship is retrieved in a controller before loading the roles 'auth:user()->roles' returns every role not just the assigned ones.

Some people have found the same problem but could not be reproduced so far. Related issues: #2161, #1829

**Versions**
- spatie/laravel-permission package version: 5.5.5
- laravel/framework package: 9.32.0

PHP version: 8.1.1

Database version: sqlite

**To Reproduce**
This behavior occurs when a controller requires a model with a relationship before loading the roles and the relationship uses the hasRole function

web.php
```php
Route::get('/test', function(){
    
    $var = MyParent::withCount('limitedView')->get(); //not used but creates the issue
    
    return[ Auth::user()->roles, App\Models\User::find(Auth::id())->roles ];
});
```

MyParent.php
```php
class MyParent extends Model
{
    use HasFactory;

    public function children(): HasMany
    {
        return $this->hasMany(Child::class);
    }

    public function limitedView(){
        $query = $this->children();

        if(!Auth::user()->hasRole('Super-Admin')){
            $query->orWhere('age', '>=', 18);
        }

        return $query;
    }
}
```

**Basic Test**
```php
public function test_example()
    {
        app(DatabaseSeeder::class)->call(PermissionsDemoSeeder::class);

        $user = User::find(1); //Role: writer
        
        $this->be($user);

        list($rolesBefore, $rolesAfter) = $this->get('/test')->json();

        $this->assertCount(1,$rolesBefore);
        $this->assertCount(1,$rolesAfter);
        $this->assertEquals($rolesBefore[0]["name"], "writer");
        $this->assertEquals($rolesAfter[0]["name"], "writer");

    }
```
**Example Application**
A minimal repo with a test implemented can be found at: https://github.com/SIDESO/issue_demo_spatie_permissions

**Expected behavior**
Only the assigned roles should be returned.

 **Additional context**
The problem disappears adding to the user model:

```php
protected $with=['roles'];
```

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: Windows10
 - Version: 21H2

**Comment by parallels999** [comment]
>**Example Application**
A minimal repo with a test implemented can be found at: https://github.com/SIDESO/issue_demo_spatie_permissions

I couldn't get it to work, sorry
![image](https://user-images.githubusercontent.com/109294935/193287464-ef80b559-45a7-475f-b8d7-71834bced19d.png)
Feel free to make a PR with the fix

**Comment by IGedeon** [comment]
Hi, thank you for your quick response.

I did follow the demo app example but the current Laravel version uses Vite by default please execute:

```
npm run build
```

[Please note that Node v16 and npm are required](https://laravel.com/docs/9.x/vite#installing-node)

![image](https://user-images.githubusercontent.com/694313/193293849-12994a92-4442-4e60-b58e-7c956dfbde7c.png)

**Comment by erikn69** [comment]
@IGedeon try my last PR please

**Comment by IGedeon** [comment]
Hi @erikn69,  it solves the issue. Thank you
