### ISSUE TITLE
Role and permissions

### ISSUE THREAD

**Issue by Eductiveo** [spatie/laravel-permission#220]
Hello,

I'm having a question. Can you check in your view if the assigned role has a permission (but only a permission assigned to the role), so something like: "If Administrator has admin-access perm" then access to that else not

Kind regards,

**Comment by freekmurze** [comment]
I'm assuming that you can if the `user` in your view has a permission. You can use the blade directive `@can` for that. 

If you want to test if a role itself has a certain permission your can use the `hasPermissionTo` on a role.

```php
$role->hasPermissionTo($permissionName); // returns boolean
```
