### ISSUE TITLE
findByName() broken?

### ISSUE THREAD

**Issue by SparkyRih** [spatie/laravel-permission#2209]
So I'm trying to so something very simple:

```php
ollect(RolesEnum::all())->each(function ($role) {
    Role::create(['name' => $role, 'team_id' => 1]);
});
dump(Role::findByName('admin')); // results in:   There is no role named `admin`.
``` 

The query it appears to create: `"select * from "roles" where ("team_id" is null or "team_id" = ?) and "name" = ? and "guard_name" = ?"`

spatie/laravel-permission          5.5.5

Even when trying to get the role by Id, it gives the same erorr (however, complaiging about the ID not existing instead of the name).

Any help?

**Comment by erikn69** [comment]
Did you set global `team_id` before `findByName`?

**Comment by erikn69** [comment]
https://spatie.be/docs/laravel-permission/v5/basic-usage/teams-permissions
`setPermissionsTeamId`

**Comment by SparkyRih** [comment]
Got it, thanks!
