### ISSUE TITLE
Setting Model::shouldBeStrict() on Laravel 9.35 breaks app

### ISSUE THREAD

**Issue by neoighodaro** [spatie/laravel-permission#2215]
**Describe the bug**
When using the new `Model::shouldBeStrict()` feature on Laravel, the application is entirely broken.

```
The attribute [guard_name] either does not exist or was not retrieved for model [App\Models\User].
```

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: 5.5.5
- illuminate/framework package: 9.35

PHP version: 8.1

Database version: Irrelevant

**To Reproduce**
Add strict mode to an application running this package.

**Expected behavior**
Package should not break when using Eloquent strict mode.

**Comment by neoighodaro** [comment]
A temporary workaround is setting `guardName()` on your `User` (or applicable) model to `null` or to the actual guard name

The line that causes this error is in `\Spatie\Permission\Guard:25` where `$model->guard_name` is accessed but may not exist.

**Comment by fredsal** [comment]
Feel free to make a PR fixing that
