### ISSUE TITLE
Undefined index: guard_name

### ISSUE THREAD

**Issue by JonPurvis** [spatie/laravel-permission#2218]
**Describe the bug**
This afternoon I upgraded the version of this package we're using to [5.5.10](https://github.com/spatie/laravel-permission/releases/tag/5.5.10) and then started seeing an error to do with guard_name being undefined:

```
ErrorException
Undefined index: guard_name

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/spatie/laravel-permission/src/Models/Role.php:73
```

That line consists of 
```
getModelForGuard($this->attributes['guard_name']),
```

I've downgraded back to 5.5.9 for now which no longer causes the error. It would be good if someone could take a look into this though!

**Versions**
- spatie/laravel-permission package version: **5.5.10**
- illuminate/framework package version: **8.83.25**
- PHP version: **7.4**
- Database version: **MySQL 5.7**

**To Reproduce**
Here is my example code and/or tests showing the problem in my app:
```
Role::with('users')->get();
```
causes the error, however
```
Role::with('permissions')->get();
````
works fine

**Expected behavior**
I'd expect roles to be returned with users that have the role

**Comment by JonPurvis** [comment]
Small update, as I see version [5.5.11](https://github.com/spatie/laravel-permission/releases/tag/5.5.11) was also released today so I upgraded to that in hopes it would fix this issue, no such luck unfortunately!

Downgraded back to [5.5.9[(https://github.com/spatie/laravel-permission/releases/tag/5.5.9) for now 😄

**Comment by erikn69** [comment]
Hi, try changing for 
```php
getModelForGuard($this->attributes['guard_name'] ?? null),
```

**Comment by JonPurvis** [comment]
`getModelForGuard()` doesn't allow null

**Comment by erikn69** [comment]
Ok, i'm going to try a fix

**Comment by drbyte** [comment]
@JonPurvis Thanks for the detailed report.

**Comment by JonPurvis** [comment]
No problem @drbyte 👍 

Thanks to @erikn69 for fixing 😄 

I've just deployed the latest release and can confirm it's now working as intended 🥳
