### ISSUE TITLE
Call to undefined method Model::hasRole() when using permissions without roles

### ISSUE THREAD

**Issue by jedlikowski** [spatie/laravel-permission#2223]
**Describe the bug**
Hi,

I use the package without any problems in my User models, but a need has arised to have a different model which will only have direct permissions, no roles. To achieve this, I added the HasPermissions trait to the model as well as this code to avoid creating a guard for the model (it's not a user-like model):
```php
    protected function getDefaultGuardName(): string
    {
        return array_keys(config("auth.guards"))[0];
    }

    protected function getGuardNames(): Collection
    {
        return collect([$this->getDefaultGuardName()]);
    }
```
Now, when checking if my new model has a permission, a bug appeared in HasPermissions trait, `hasPermissionViaRole` method. This method assumes the Model has the HasRoles trait, which defines the hasRole() method. I will overload the method and return a hardcoded `false`, but nonetheless might be useful to first check if Model has the `hasRole` method before calling it. 
```php
    protected function hasPermissionViaRole(Permission $permission): bool
    {
        return $this->hasRole($permission->roles);
    }
```

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: 5.5.12
- laravel/framework version: 9.36.3

PHP version: 8.1.11

Database version: irrelevant

**To Reproduce**
Create a model with just the `HasPermissions` trait and try to check for a permission which is not directly attached to that model.

**Comment by jedlikowski** [comment]
So it’s not possible to use this package to only allow permissions for a model without allowing roles? Might be cool to support this usecase and I believe this part of code might be the only place which needs to be changed to achieve that :)

**Comment by erikn69** [comment]
Read again

> But on user model you could add function `hasPermissionViaRole`

**Comment by jedlikowski** [comment]
> I will overload the method and return a hardcoded `false`

Haha yeah I mentioned this approach in my initial message too :) Just thought I would suggest a simple change to support the usecase :)

**Comment by erikn69** [comment]
with that change it could work, but since it is not the established use, you should test

**Comment by parallels999** [comment]
This is not a bug, use discussions section on the future
