### ISSUE TITLE
hasPermissionTo cache issue with latest update

### ISSUE THREAD

**Issue by cbloss** [spatie/laravel-permission#224]
Hey guys!

I just upgraded the package to the most recent that was pushed a day ago that included the caching capabilities with the Permission model. Is there a way to turn this off? It's causing issue when I do a permission update. I have to run a `php artisan cache:clear` every time I change a role's permission.

Thanks!

P.S. This package has saved me. Thanks! :D

**Comment by freekmurze** [comment]
You can run

```php
app(\Spatie\PermissionPermissionRegistrar::class)->forgetCachedPermissions();
```

to forget all cached permissions.

**Comment by donnygunawan93** [comment]
How to disable cache by default?
Should we run that code everytime we want to check our permissions?
