### ISSUE TITLE
pidop

### ISSUE THREAD

**Issue by sergiomarotco** [spatie/laravel-permission#2244]
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/laravel-permission/issues) or in [the discussions](https://github.com/spatie/laravel-permission/discussions).

**Describe the bug**

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version:
- illuminate/framework package

PHP version:

Database version:

**To Reproduce**

Here is my example code and/or tests showing the problem in my app:

**Example Application**
Here is a link to my Github repo containing a minimal Laravel application which shows my problem:

**Expected behavior**

 **Additional context**

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: [e.g. macOS]

**Comment by erikn69** [comment]
Spam??
