### ISSUE TITLE
conflicts in composer

### ISSUE THREAD

**Issue by whfamily2006** [spatie/laravel-permission#226]
In my composer required array `"spatie/laravel-permission": "1.6.*"` but when I try to update the composer it's returned with problem 

> The requested package spatie/laravel-permission (locked at 1.5.3, required as 1.6.*) is satisfiable by spatie/laravel-permission[1.5.3] but these conflict with your requirement
s or minimum-stability.

its mean I can't use greater than 1.5.3?

**Comment by freekmurze** [comment]
I can pull in that version without any problems. So it must be something in your specific project that is holding you back. To make sure, try installing the package in a vanilla Laravel app.

A better constraint would be `^1.0.0`, so you always get the latest and greatest stable version.
