### ISSUE TITLE
Env based permission caching

### ISSUE THREAD

**Issue by raiyanihiren** [spatie/laravel-permission#2275]
**Describe the bug**
How can I save cache based on the environment (.env) of Laravel?
I am handling multiple environments; in one environment, everything is working properly.

But after changing the environment, I have to clear the cache.
So, can I save the permission cache based on the environment file in Laravel?

Is there any provision for this, to handle permission caching based on environment?

**For Example:**
I am handling a Laravel project based on a subdomain, and the user's environment is selected based on that subdomain. Also,  every subdomain uses a different database, which is specified in the env file.
But now the problem is that my permission only allows me to cache one file, and I need multiple caching options based on the environment.
1. abc.example.com will access .abc environment file.
2. xyz.example.com will access .xyz environment file.
This is all dynamic; the question now is whether I am working on the abc.example.com site and whether all permissions are functioning properly.
However, because both sites are hosted on the same server panel, when I login to xyz.example.com, it will also access the permissions of abc.example.com; that's why I am not getting any permissions from xyz because permissions are already cached. The only difference is in .env file.

Thank you for reading.

Please advise on how to deal with permission plugins when users have dynamic and multiple env files.If she still needs any information from my side, then let me know.

**Thank You**

**Comment by parallels999** [comment]
This is not an issue or a bug, 
if you have questions use the correct section(discussions) or read documentation, there is all the information about cache

**Comment by raiyanihiren** [comment]
We can handled it by dynamic file name based on cache.

Thank You
