### ISSUE TITLE
Installing on Lumen removes lots of native packages!

### ISSUE THREAD

**Issue by meNESS** [spatie/laravel-permission#229]
Hi,

I want to use this package on Lumen but it removes lots of native packages from `illuminate`

**Comment by freekmurze** [comment]
This package does not support Lumen.

**Comment by meNESS** [comment]
@freekmurze I'm going to make this package support Lumen as well, but it keep saying
> Target [Illuminate\Contracts\Logging\Log] is not instantiable

Do you know how to fix this?
