### ISSUE TITLE
Unable to create new company (team) roles "A role `super_admin` already exists for guard `api`."

### ISSUE THREAD

**Issue by sts-ryan-holton** [spatie/laravel-permission#2296]
**Describe the bug**

In my Laravel application, I have Users and Companies. A Company is effectively the Teams integration. When a user is created, they can create a company, and the company belongs to them. Then, other users can be assigned to a company based on their role & company ID. Despite having a `company_id` column in the roles table and trying to seed roles for this company, an error is thrown:

> A role `super_admin` already exists for guard `api`.

**Versions**

- spatie/laravel-permission package version: 5.7.0
- illuminate/framework package 9.46.0

PHP version: 8.1.0

Database version: MySQL

 **Additional context**

In my application, I need to assign users to companies based on a role. I do have a global roles for my companies, and a set of roles that have no company ID (see screenshot), this is fine, but now, my seeder I need to create roles for the company so that a user can be assigned this role in the company.

When I attempt to run it an error is thrown:

> A role `super_admin` already exists for guard `api`.

I know that a role `super_admin` exists, it does for the guard `api`, but that role has no company ID, I now need to create a `super_admin` specifically for a my company, along with the other roles, so this error shouldn't be thrown.

How can I get resolve this?

Not sure why there's a `company_id` column in roles if I can't use it for this purpose.

Here's my code:

```php
<?php

namespace Database\Seeders\Production;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Company;
use Spatie\Permission\Models\Role;
use Carbon\Carbon;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [[
            'user' => [
                'timezone' => 'UTC',
                'first_name' => 'John',
                'last_name' => 'Doe',
                'email' => 'john.doe@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password')
            ],
            'company' => [
                'contact_first_name' => 'John',
                'contact_last_name' => 'Doe',
                'company_name' => 'My company'
            ],
            'company_roles' => [
                'super_admin',
                'admin',
                'affiliate',
                'role'
            ]
        ], [
            'user' => [
                'timezone' => 'UTC',
                'first_name' => 'Smith',
                'last_name' => 'Jones',
                'email' => 'smith.jones@gmail.com',
                'email_verified_at' => Carbon::now(),
                'password' => Hash::make('password')
            ],
        ]];

        foreach ($users as $key => $user) {
            $createdUser = User::firstOrCreate($user['user']);

            // if user has a company, create it
            if ($user['company']) {
                $createdCompany = Company::firstOrCreate(array_merge([
                    'user_id' => $createdUser->id
                ], $user['company']));

                // if roles exist for the company, we need to create
                // these and assign the company to them
                if ($user['company_roles'] && $createdCompany) {
                    foreach ($user['company_roles'] as $role) {
                        if (Role::where('name', $role)->where('company_id', $createdCompany->id)->first()) {
                            continue;
                        }

                        Role::create([
                            'name' => $role,
                            'company_id' => $createdCompany->id,
                            'guard_name' => 'api'
                        ]);
                    }
                }
            }
        }
    }
}
```

![Screenshot 2023-01-10 at 13 47 46](https://user-images.githubusercontent.com/25177538/211568169-d072ac9e-6346-4784-b766-19bc9388efa3.png)

**Comment by parallels999** [comment]
Stop opening new issues, use discussions for this
This is not a bug, you are not using the package correctly
Read documentation, this is an expected behavior

https://spatie.be/docs/laravel-permission/v5/basic-usage/teams-permissions
> with null team_id it creates a global role, global roles can be assigned to any team and they are **unique**, 

unique means that there cannot be another role with the same name and guard on any other team

This is the last answer from me
