### ISSUE TITLE
getRoleNames returns empty array for user

### ISSUE THREAD

**Issue by sts-ryan-holton** [spatie/laravel-permission#2297]
**Describe the bug**

I have roles in my database which are linked to my companies. A user has been assigned a role through a company, but when querying the user's roles, nothing is returned other than an empty array.

I've read the documentation on this one, surely this is a bug?

**Versions**

- spatie/laravel-permission package version: 8.7.0
- illuminate/framework package 9.46.0

PHP version: 8.1.0

Database version: MySQL

 **Additional context**

```php
$roles = User::find(Auth::id())->getRoleNames();

return response()->json([
    'roles' => $roles
], 200);
```

Roles table:

![Screenshot 2023-01-10 at 15 14 07](https://user-images.githubusercontent.com/25177538/211589060-ee2de2f0-2930-4322-9b78-3db67419c71b.png)

Model has roles table

![Screenshot 2023-01-10 at 15 14 29](https://user-images.githubusercontent.com/25177538/211589104-2c1c05f8-12a9-4bc1-91af-cc297ba16a04.png)

**Comment by parallels999** [comment]
Another problem? #2296 is still open

**Comment by parallels999** [comment]
It don't looks like a bug, looks like you don't understand the basics for using team_id feature

https://github.com/spatie/laravel-permission/issues/1992#issuecomment-1013104967
https://github.com/spatie/laravel-permission/issues/2209#issuecomment-1277659263
