### ISSUE TITLE
[5.9.0] Artisan migrate throwing QueryException

### ISSUE THREAD

**Issue by jure-knezovic** [spatie/laravel-permission#2318]
After latest update to 5.9.0, php artisan migrate / migrate:fresh is throwing Query Exception. 

SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name '' (SQL: create table `model_has_permissions` (`` bigint unsigned not null, `model_type` varchar(255) not null, `model_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

Laravel:  9.50.2
Permission package: 5.9.0
PHP: 8.1
DB: mariadb 10.5

1. Create fresh Laravel App
2. composer require spatie/laravel-permission
3. Add HasRoles to User
4. php artisan migrate -> Query Exception

When permissions package is locked to 5.8.0, no QueryException is thrown.

**Comment by mrtorks** [comment]
I can also confirm I am getting the same error. I discovered this when one of my deploy jobs failed doing the migration stage.

**Comment by ArnoldNicole** [comment]
Pull request fix: Lazily bind dependencies #2316 seems to have started the issue.

**Comment by mrtorks** [comment]
One thing that comes to mind is the possibility of requiring a cache reset/refresh.

**Comment by ahoiroman** [comment]
Same here. Clearing cache and performing a fresh migration does not solve the issue.

**Comment by daniel-cintra** [comment]
I confirm the same error here. Can't run the package migration for 5.9.0.

**Comment by AhmedMub** [comment]
I can confirm the same error for Laravel 9 and 8 fresh installation, after clearing the config cache and fresh migration does not solve the problem

**Comment by erikn69** [comment]
Maybe related
https://github.com/spatie/laravel-permission/issues/2319#issuecomment-1419648393

**Comment by ashvin-php** [comment]
Same issue noticed. There is nothing to clear in cache for permissions.

In migration file, the "PermissionRegistrar" class is not instantiated and hence its constructor is not being called & no value set for its static variable $pivotPermission. Hence the migration query showing a blank column name while creating table "model_has_permissions"

**Comment by erikn69** [comment]
@ashvin-php so, https://github.com/spatie/laravel-permission/pull/2309 is the problem?

**Comment by ashvin-php** [comment]
@erikn69 At the moment I am not 100% sure about #2309 , but it looks like PermissionRegistrar class is not instantiated. I just looked at the migration file and PermissionRegistrar.php file for v5.9.0 in my machine.

**Comment by Icemont** [comment]
Confirming the problem.
Now updated dependencies on one of the projects on Laravel 9, and the tests failed with an exception in the migration.
In migration `2023_02_06_235146_create_permission_tables.php:78` `\Spatie\Permission\PermissionRegistrar::$pivotRole` returns empty value, which causes error in creating table "model_has_permissions":
`... syntax error (SQL: create table "model_has_permissions" ("" integer not null, ...`

**Comment by erikn69** [comment]
@ashvin-php try without that change, change it on vendor if it necessary, and give us a feedback

**Comment by gmlo89** [comment]
Same error here!
`  SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name '' (SQL: create table `model_has_permissions` ...`

**Comment by alfinauzikri** [comment]
I have the same problem too..

Laravel: 9.50.2
Permission package: 5.9.0
PHP: 8.2.2
![image](https://user-images.githubusercontent.com/14070303/217072607-400d371b-2b4f-4a8a-abec-3785692c5116.png)

The current alternative that can be done is downgrade to version 5.8.

Hopefully this issue is quickly resolved.. :)

**Comment by mrtorks** [comment]
Hey All. I appreciate all those who tested the reset/refresh cache option and I can personally also confirm it does not work. A @ahoiroman specified, lock your version to ```5.8.0``` until this is resolved.

**Comment by AhmedMub** [comment]
> Hey All. I appreciate all those who tested the reset/refresh cache option and I can personally also confirm it does not work. As @ahoiroman specified, lock your version to `5.8.0` until this is resolved. In my case I did the following in my composer.json file
> 
> `"spatie/laravel-permission": "<5.7",`

@mrtorks Unfortunately did not work for me, still have the same issue  for `5.7` and `5.8`

**Comment by erikn69** [comment]
Hi, can somebody test this commit on 5.9.0 https://github.com/erikn69/laravel-permission/commit/e357bc0aaa4be6549fa67a1ab7bf39339ce50978, maybe that fix it

**Comment by alfinauzikri** [comment]
@erikn69 it works!
![image](https://user-images.githubusercontent.com/14070303/217082259-8bb3642c-c33b-4b77-9d95-173cfa19cf31.png)

I did a manual change in the vendor according to this reference "https://github.com/erikn69/laravel-permission/commit/09088c00756bfd2d71bea3f4d6f67fccba895ba5" and tested it in a new project.

![image](https://user-images.githubusercontent.com/14070303/217082892-18528a0f-e58e-44dc-ab9d-9d8aa56dd38f.png)

![image](https://user-images.githubusercontent.com/14070303/217082936-3d746b85-20bc-466e-ad6e-f289f2ee6af7.png)

**Comment by mrtorks** [comment]
I can confirm alongside @alfinauzikri  That @erikn69 's solution works. I TESTED IT ON A FRESH PROJECT WITH ```5.9.0```. Great Job all around

**Comment by mrtorks** [comment]
> > Hey All. I appreciate all those who tested the reset/refresh cache option and I can personally also confirm it does not work. As @ahoiroman specified, lock your version to `5.8.0` until this is resolved. In my case I did the following in my composer.json file
> > `"spatie/laravel-permission": "<5.7",`
> 
> @mrtorks Unfortunately did not work for me, still have the same issue for `5.7` and `5.8`

@AhmedMub perhaps @erikn69 solution might work for you.

**Comment by drbyte** [comment]
v5.9.1 reverted the change.
