### ISSUE TITLE
v5.9.0 breaks user()->can() verification

### ISSUE THREAD

**Issue by MrWeb** [spatie/laravel-permission#2319]
**Describe the bug**
I upgraded from 5.7.0 to 5.9.0 and inside blade `can()` returns `false` when before it was returning `true`

**Versions**
- spatie/laravel-permission package version: 5.9.0
- illuminate/framework package

PHP version: 8.1

Database version: MySQL 8.0.27

**To Reproduce**
Assign a user a permission 'view-CoWorking'
Inside blade check:

```
@if(auth()->user()->can('view-CoWorking'))
Can
@else
Cannot
@endif
```

In v 5.9.0: should return "Can" but "Cannot" is returned
In v 5.7.0: should return "Can" and "Can" is correctly returned

**Comment by rodrigopaggue** [comment]
i have a similar problem but with permission middleware,
It's always returning me "User does not have the right permissions."

**Comment by ramonMontanhes** [comment]
I'm have the same issue on a dev server with version 5.4

"spatie/laravel-permission": "^5.4",
PHP 8.2.1 (cli) (built: Jan 13 2023 10:42:44) (NTS)

Also I'm using a middleware to check the permission on route groups.

**Comment by erikn69** [comment]
https://github.com/spatie/laravel-permission/releases/tag/5.9.0
Please look wich of that PRs makes the problem, maybe could be this `https://github.com/spatie/laravel-permission/pull/2309`

**Comment by danilopinotti** [comment]
This issue is potentially caused by: https://github.com/spatie/laravel-permission/commit/298736569d2f43cc799aa8267d3c6ade0667f770#diff-86d7657433d757572a7a11c80097e5343108ac788ae1de495b56a27491f1d9cbR26

**Comment by danilopinotti** [comment]
> https://github.com/spatie/laravel-permission/releases/tag/5.9.0 Please look which of that PRs makes the problem?, maybe could be this #2309

It worked for me after reverting these changes locally

**Comment by erikn69** [comment]
ok, thanks for the feedback

**Comment by erikn69** [comment]
Hi, can somebody test this commit on 5.9.0 https://github.com/erikn69/laravel-permission/commit/e357bc0aaa4be6549fa67a1ab7bf39339ce50978, maybe that fix it

**Comment by danilopinotti** [comment]
> Hi, can somebody test this commit on 5.9.0 [erikn69@e357bc0](https://github.com/erikn69/laravel-permission/commit/e357bc0aaa4be6549fa67a1ab7bf39339ce50978), maybe that fix it

It doesn't work here

**Comment by erikn69** [comment]
So PR must be reverted

**Comment by erikn69** [comment]
Hi, can somebody test this commit on 5.9.0 https://github.com/erikn69/laravel-permission/commit/09088c00756bfd2d71bea3f4d6f67fccba895ba5, what about these

**Comment by danilopinotti** [comment]
> Hi, can somebody test this commit on 5.9.0 [erikn69@09088c0](https://github.com/erikn69/laravel-permission/commit/09088c00756bfd2d71bea3f4d6f67fccba895ba5), what about these

In my tests, these changes fix the issue

**Comment by drbyte** [comment]
v5.9.1 reverted the change.
