### ISSUE TITLE
Call to a member function contains() on string error with middleware at routing 'role:roleName'

### ISSUE THREAD

**Issue by mryassera** [spatie/laravel-permission#2328]
**Describe the bug**
When using middleware at routing 'role:roleName' an error message appears:
 `Call to a member function contains() on string`
Conversely, middleware with only auth working well

![call to a member function contains() on string](https://user-images.githubusercontent.com/45864194/218606849-5f68a22d-0761-4e82-8641-9c90fd17101b.jpg)

**To Reproduce**
routes/web.php:
```
Route::group(['middleware' => ['auth', 'role:eventAdmin']], function () {
    Route::get('super-admin/event/create', [EventInfoController::class, 'create'])
        ->name('event.create');
});
```
App/Http/Kernel.php:
```
protected $routeMiddleware = [
     // Spatie Roles
        'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,
        'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,
        'role_or_permission' => \Spatie\Permission\Middlewares\RoleOrPermissionMiddleware::class,
 ];
```
UserController.php:
```
public function login(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'email' => 'required|email',
            'password' => 'required|string',
        ]);
        $credentials = $request->only('email', 'password');

        if (Auth::attempt($credentials)) {
            $user = Auth::user();

            if ($user->roles == 'eventAdmin') {
                // dd($user->roles);
                return redirect()->intended('admin/event-info')
                    ->withSuccess('Signed in');
            }
        }
        $msg = $validator->errors();
        if (!$validator->fails()) {
            $msg = 'The email or password is incorrect';
            return back()->withErrors(['msg' => $msg]);
        }
        return back()->withErrors($msg);
    }
```
App/Http/Models/User.php:
```
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

```

![tables](https://user-images.githubusercontent.com/45864194/218606997-8a93b1d6-d582-4d12-afe5-8e8a24844040.jpg)

![role table](https://user-images.githubusercontent.com/45864194/218607024-808e66e1-ef8b-4ea0-9f78-20be40d7a4ee.jpg)

https://user-images.githubusercontent.com/45864194/218609540-3030c029-77ef-4787-a3b2-a56b4aeb4fa2.mp4

**Versions**
- spatie/laravel-permission package version: 5.7.0
- spatie/laravel-ignition: 1.5.1
- Laravel : v9.34.0
- PHP version: 8.1.8
- inertiajs/inertia-laravel: v0.6.3
- Database version: MariaDB 10.6.10
- nginx/1.14.0

**Environment:**
 - OS: Win10 64x, Laragon v3.5.0, php artisan.

**Comment by erikn69** [comment]
It don't seems like a bug, seems like you overwrite something on roles
Read this: [must-not-have-a-role-or-roles-property](https://spatie.be/docs/laravel-permission/v5/prerequisites#content-must-not-have-a-role-or-roles-property-nor-a-roles-method)

**Comment by mryassera** [comment]
Still same issue..

I tried to following many courses, and upgraded version to "spatie/laravel-permission": "^5.9" however the same issue

Could you check the video
https://user-images.githubusercontent.com/45864194/220793793-93b27267-c380-4b4f-b557-517a673fe243.mp4
 
Could anyone tell me where the problem.

When I set middleware to only auth working well, but the problem with 'role:roleName'


> It don't seems like a bug, seems like you overwrite something on roles
> 
> > if ($user->roles == 'eventAdmin') {
> 
> Read this: [must-not-have-a-role-or-roles-property](https://spatie.be/docs/laravel-permission/v5/prerequisites#content-must-not-have-a-role-or-roles-property-nor-a-roles-method)

**Comment by parallels999** [comment]
> It don't seems like a bug, seems like you overwrite something on roles
> 
> > if ($user->roles == 'eventAdmin') {
> 
> Read this: [must-not-have-a-role-or-roles-property](https://spatie.be/docs/laravel-permission/v5/prerequisites#content-must-not-have-a-role-or-roles-property-nor-a-roles-method)

That is the correct answer because this functionality is fully tested. [HasRolesTests](https://github.com/spatie/laravel-permission/blob/main/tests/HasRolesTest.php)
But if you still thinks that there is a bug, make a failing test or a minimal app with the [example showing the problem,](https://spatie.be/docs/laravel-permission/v5/basic-usage/new-app) i'm sure when you try it on a fresh instalation you will find the problem on your implementation
