### ISSUE TITLE
hasPermissionTo never checks roles (because HasRoles trait does not work with Collection)

### ISSUE THREAD

**Issue by top-master** [spatie/laravel-permission#2332]
https://github.com/spatie/laravel-permission/blob/0c497767227d19eff395789e65262fb95068aec3/src/Traits/HasRoles.php#L217

Above may be a bug, because Laravel's query results to collection, not an array.

I mean, Currently `hasPermissionTo` is just an alias for `hasDirectPermission`,
because `hasPermissionViaRole` always returns `false`.
And that, because `$permission->roles` returns Collection, never raw-array.

**Comment by parallels999** [comment]
I think that you are wrong, if $roles is not an array it continues to collection handler
https://github.com/spatie/laravel-permission/blob/0c497767227d19eff395789e65262fb95068aec3/src/Traits/HasRoles.php#L227
Also there is many tests for hasRoles
https://github.com/spatie/laravel-permission/blob/main/tests/HasRolesTest.php

**Comment by top-master** [comment]
Seems my `$this->roles` is empty,
I expected that to be loaded, because the permission is loaded based on a simple string.

Throwing something like "roles relation not-loaded" seems reasonable, instead of just returning `false`.

Basically, `false` is a lie.

**Comment by parallels999** [comment]
> After debugging for few hours

 Many hours of debugging can save you 5 minutes of reading documentation

**Comment by parallels999** [comment]
> It simply uses $this->roles, even if "roles" relation is never loaded.

roles as always loaded with `$this->loadMissing('roles'); `

https://github.com/spatie/laravel-permission/blob/0c497767227d19eff395789e65262fb95068aec3/src/Traits/HasRoles.php#L190-L192

>Which basically was hidding it from my review, I mean, you're lucky I don't review your code,
I would reject that instantly, because instanceof Collection check is missing.

😄😄😄😄 Just because you can't understand how things work doesn't mean they're badly done.
As you say(before you deleted), this package is so many years old, it is because it is very tested
Also, why do you delete your comments and their changes history, shame on nonsense?

**Comment by top-master** [comment]
>"can't understand ... doesn't mean they're badly done"

### Human-readability is important, you're basically saying:

* readers are forced to understand,
* without any `insteanceof` check,
* and **even without any comment**.

But there are multiple other things badly done in that line, beside **not** being human-readable:
* if we pass to that method a custom class,
* which has a custom `intersect` method,
* said method is called, and maybe drops all tables, or something like that.
* it's a custom method, and it's allowed to do whatever it wants.
* it's your fault for calling that method without checking ;-)

**Comment by PaolaRuby** [comment]
>> It simply uses $this->roles, even if "roles" relation is never loaded.
>roles are always loaded with $this->loadMissing('roles'); 

Hello, if you think there is a bug, do a failing test to prove it, 
from my point of view the problem is that you can't understand the code(apparently you are the only one), because there are many tests 
https://github.com/spatie/laravel-permission/tree/main/tests

**Comment by top-master** [comment]
### Finally there it is, the old saying of "we accept pull requests".

Also, you seem to point again and again to:
```
$this->loadMissing('roles');
```
Well, that line **does not even exist**, for example, on version `3` and `4` branchs,
I will try updating to version `5` (current latest) once possible ;-)

However, that is history by now, what about the second issue, don't try to change the subject.

**Comment by parallels999** [comment]
>Well, that line does not even exist, for example, on version 3 and 4 branches,
I will try updating to version 5 (current latest) once possible ;-)

So much reputation and it seems that you have to explain the basics, first when you start a new issue report you must specify the **package's version**,  **laravel's version** and **PHP version**, otherwise everyone will assume that they are in the current versions, 
For example, several here have reviewed what you say, and apparently you use an outdated version of the package and everything you report has probably already been fixed according to the tests, you only wasted the time of people with the intention of helping

Second, old versions reaches they end of life and they are without support, current is 5, and in a short time they will go to 6

You also arrive with your attitude that "everything is badly done and full of bugs" (without showing any failing tests), and "that I  have a super reputation and I'm better than everyone"

stackoverflow reputation don't prove something here, better show how many PHP contributions you have made to open source in this month at least, stackoverflow mostly it is to answer basic questions of the noobs

>please don't spam this thread until the day you beat my reputation

😄😄😄😄😄 This is a public thread, It is also necessary to explain how this works

**Comment by top-master** [comment]
>"stackoverflow mostly it is to answer basic questions of the noobs"

@parallels999 If you can't even answer a noob's question, what does that make you? right, even worst noob.

Secondly, there are many pro questions, go answer those.

>"So much reputation ... specify the package's version"

First of all, this thread is about current-latest version, hence no need to specify;
the version on which I am is only related to the issue(s) which I said I should open,
I did not even open such issue(s) yet, hence you wasted your and my time by answering here instead of waiting for said issues to be openned.

Secondly, learn english.

---

@PaolaRuby I hope no one wastes time reading a spammer's excuses, most of which did not make sense.

**Comment by top-master** [comment]
Okay, let's colse this, only noobs here ;-)

**Comment by parallels999** [comment]
> If you can't even answer a noob's question, what does that make you? right, even worst noob ;-)

If you can't understand three simple lines of code, what does that make you? right, even worst noob ;-)

> Lastly, learn english.

Yes, I'm learning at nights, no one is born knowing a different language, I don't know if you say it for lack of arguments or simply some kind of racism on your wall

> First of all, this thread is about current-latest version, hence no need to specify version,
> I will try updating to version 5 (current latest) once possible ;-)

you contradict yourself apparently you are in a previous version

Lastly, learn coding.

**Comment by top-master** [comment]
>"the version is only related to the **first** of the issues which I said I should open,
all other issues are about current-latest version."

Can not even read?

**Comment by parallels999** [comment]
> If all supported checks passed, the main one supported remains by elimination, It's called early returns, read about it, also if you check `instanceof  Collection`, still might not be a collection of roles, human error can be more extensive and you won't finish the checks, you will only increase the cost of performance

Can not even read? Your question was already answered by an contributor

**Comment by top-master** [comment]
I read that already, and no, 1 micro second performance is no excuse for badly done code.

**Comment by parallels999** [comment]
> I read that already, and no, 1 micro second performance is no excuse for badly done code.

Still, that is not a bug

Make a failing test, that would prove you right and the members would correct it.
That you have made a bad implementation is not a problem of the package

**Comment by top-master** [comment]
>"is not a problem of the package"

The package's function accepts multiple types, and checks most, except `Collection`.

No need to unit-test the obvious mistake, but try something like:
```
class MyHasRolesTest extends TestCase
{
    use HasRoles;

    function it_should_be_type_safe_for_collection()
    {
        $this->assertFalse($this->testUser->hasRole(new class {
            public function intersect()
            {
                Assert::fail('Should only be called on Collection.');
            }
        }));
    }
}
```

**Comment by parallels999** [comment]
Use markdown correctly, ` ```php `
https://github.com/spatie/laravel-permission/blob/6e0f9574d26d4d7ea16d63508db5b0a44424a862/src/Traits/HasRoles.php#L186
Sending unexpected datatypes would be your bug, not the package's bug

Assumption, it is as if you did
```php
\App\Models\MyModel::create([
    [
       'field'=>'value1'
    ],
   [
       'field'=>'value2'
    ]
]);
```
On that example, laravel just create one empty db row without any exception, because it receives an array, but doesn't check that it's not an array of arrays(unexpected value)

**Comment by top-master** [comment]
Go report that to Laravel, others making same mistake is no excuse ;-)

Also, at least Laravel does nothing, you call that wrong instance's method.

**Comment by parallels999** [comment]
> at least Laravel does nothing
> laravel just create one empty db row without any exception

Lol, you didn't read, laravel creates an invalid row

>Go report that to Laravel, others making same mistake is no excuse

Exactly, others making mistakes is no excuse, you mistakes are not bugs

**Comment by parallels999** [comment]
> Good joke, or good spam.

No one has spammed you, check the meaning of spam, so far everyone has answered your questions, despite your behavior

> "Use markdown correctly,` ```php `

Apparently you don't know how markdown works, I'll show you
if you use it correctly you can use hightlight, and that does help the readability

` ```php `
```php
array(
   'test' => 'test'
)
```
` ```js `
```js
{
   test : "test"
}
```

**Comment by top-master** [comment]
Here:
![read-test](https://user-images.githubusercontent.com/31405473/221994242-c8c24071-eca8-4da6-bf25-c49ba215e023.jpg)

**Comment by parallels999** [comment]
Lol, looks like you are the only spammer here
But you maybe you need that, that could help you understand how the source code works.
You still have a lot to learn and a lot to grow up.

**Comment by top-master** [comment]
>"answered your questions, despite your behavior"

Right back to you, there was no question,
only me pointing out an issue, and you spamming excuses.

Despite your behavior, this was fun.

**Comment by angeljqv** [comment]
@drbyte @freekmurze spam here
> Here: ![read-test](https://user-images.githubusercontent.com/31405473/221994242-c8c24071-eca8-4da6-bf25-c49ba215e023.jpg)

**Comment by parallels999** [comment]
> Despite your behavior, this was fun.

It's just that you deleted all the crazy things you wrote, that no one who doesn't equal your stackoverflow reputation should answer you, 
>please don't spam this thread until the day you beat my reputation
>don't try to change the subject

this was really fun,  from your behavior I imagine that you are between 15 and 18 years old

**Comment by top-master** [comment]
It's not removed, it's not crazy, it's just edited:

>"don't spam this thread until you have at least same:"

**Comment by top-master** [comment]
See above image, people can read that, and you complain about coloring.

Just because that's what you do, we report issue and you spam excuses.

**Comment by parallels999** [comment]
> See above image, people can read that, and you complain about coloring.
> Human-readability is important

Yes, you are complaing about human-readability when people can read and understand everything except you

>>"Use markdown correctly, ```php"
>
>Good joke, or good spam.

It seems that you only complain about readability when it suits you, or you just can't manage that you didn't know how to use markdown

**Comment by parallels999** [comment]
> It's not removed, it's not crazy, it's just edited

history removed, I imagine it must be very embarrassing for someone to read what you wrote
![image](https://user-images.githubusercontent.com/109294935/222000305-787ff97a-cf7c-4a2b-b67b-689cbb88d8b3.png)

**Comment by top-master** [comment]
Yes, that's called edit, go complain to GitHub if you want the old version.

>"only complain about readability when it suits"

That's not code, but if it was, it would contain `instanceof` check, lol.

**Comment by parallels999** [comment]
> history removed, I imagine it must be very embarrassing for someone to read what you wrote

Still

**Comment by top-master** [comment]
Spammer.

**Comment by angeljqv** [comment]
@top-master if you don't like this package, there is other alternatives, no one forces you to use this package, and yes, grow up
https://github.com/spatie/laravel-permission/blob/490fa00b0c8286659a534d822f7e74c684c86d27/README.md?plain=1#L92-L97

**Comment by top-master** [comment]
I like the package, I don't like excuses and/or spams.

**Comment by angeljqv** [comment]
> keep the package as simple as it can be
> _Freek Van der Herten_

No one has spammed you or given you excuses, most of the responses you received from sporadic collaborators are correct

> They're badly done

This is software from Spatie, reviewed by Freek Van der Herten, whose reputation is comparable to Taylor's. He has created many plugins for Laravel and is one of his regular collaborators. Any "bad code" complaints with the actual author, not the contributors

This is a belgium package for everyone, not all speak english, it is used as a standard to facilitate communication.

>finally there it is, the old saying of "we accept pull requests", which's basically just dodging work.

Everyone is invited to collaborate, the nationality or reputation of any page is not taken into account for the reviews, answers, or issues reports

no one is "dodging work", if that was the case you wouldn't have even gotten all your questions answered


To avoid incorrect answers or confusion, specify all the information required in [ISSUE_TEMPLATE/bug_report.md](https://github.com/spatie/laravel-permission/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

Have a nice day

**Comment by top-master** [comment]
>"all your questions answered"

**Wrong**, most of if not all your responses were excuses and/or spams, 
**as proof**, a simple search for "`?`" sign, and what you find in my comments is **only**:

* Firstly, my response to a spammer:
    >"How much is even your StackOverflow reputation?"

* Secondly, my other response to some other spammer who tried twisting my words:
    >"Can not even read?"

It's common sense that as long as **there was no question, there is no answer either**, only excuses.

## Basically, your entire comments come down to:
* "We have doc-comment"
* "We don't need to check input type, which has 1 micro second performance penality,"
* "Whatever happens, our doc-comment means it's your fault, check yourselves each time you call the function/method"

## My answer:
* PHP ignores your doc-comments, and is not type-safe in this case.
* Each such mixed input function/method is responsible to check it's input types.
* Don't make bad excuses, it's your fault, because both PHP and most IDEs silently ignore doc-comments.

**Comment by angeljqv** [comment]
> Don't make bad excuses, it's your fault

Why would it be my fault? i am not the author of the package, send your complaints to Spatie members and grow up

> and is not type-safe in this case

It still can't be because it maintains compatibility with old versions of laravel and php

>Firstly, my response to a spammer:
>>"How much is even your StackOverflow reputation?"

You have no contribution to any spatie package on your profile, to me you are the spammer here

**Comment by angeljqv** [comment]
well, it is a public thread on a public repo, grow up and stop complaining about the free work you receive from spatie

**Comment by top-master** [comment]
>"grow up, both"

@angeljqv Look who is talking, take your own advice, and stop spamming.

**Comment by parallels999** [comment]
You're tagging me, bye

**Comment by parallels999** [comment]
I think that github needs an option to block users, I have many unwanted notifications

**Comment by top-master** [comment]
@GitHub

Check these contributor's accounts, we see almost zero commitment to anything, but yet they are pretty **active on spatie packages only**.

Maybe those are fake accounts created by members,
which allows them to comment whatever they want, without damaging their reputation.

Unfortunately, seems GitHub has **not* any check present to prevent said matter, and even reporting them didn't do anything.

**Comment by top-master** [comment]
>"no one tagged you"
>"to be seen by members"
>"Everyone else ... Silence is golden."
