### ISSUE TITLE
403 login page error

### ISSUE THREAD

**Issue by exshapoval** [spatie/laravel-permission#2344]
I use Laravel 10.1.5 and Nova 4.22.1 When in .env APP_ENV=local all ok But when APP_ENV=production I see error 403 on my admin/login page

How I can fix it for production with laravel permissions?

**Comment by parallels999** [comment]
reset laravel permission cache

**Comment by exshapoval** [comment]
> reset laravel permission cache

still not work

**Comment by parallels999** [comment]
Make a debug to find the problem, and them make a PR if there is a fix

**Comment by exshapoval** [comment]
> Make a debug to find the problem, and them make a PR if there is a fix

Hi, how to make debug?

**Comment by parallels999** [comment]
ask on nova how to do it, or make a [demo app repository](https://spatie.be/docs/laravel-permission/v5/basic-usage/new-app#content-creating-a-demo-app) based on a laravel fresh installation

**Comment by drbyte** [comment]
Closing as application-specific. Need demo app in order to support. Probably unrelated to this package.
