### ISSUE TITLE
There is no guard named <whatever> in sanctum error... but there is 

### ISSUE THREAD

**Issue by ODelibalta** [spatie/laravel-permission#2345]
**Before creating a new bug report**
I have done that. Most replies to that topic are from 2018. I've tried the suggested things from there but it did not work. Please see the attached image. I don't understand why it is trying to sync via the `display_name` column instead of the `name` column

**Describe the bug**
When I try send a put request to `UserController::update`, the package responds with "There is no permission named ..." error. 
```
public function update(Request $request, string $id)
    {
        try {
            $user = User::find($id);

            $this->authorize('update', $user);

            $validate = Validator::make(
                $request->all(),
                [
                    'name' => 'required',
                    'email' => 'required|email|unique:users,email,'.$user->id,
                ]
            );

            if ($validate->fails()) {
                return response()->json([
                    'status' => false,
                    'message' => 'Validation error',
                    'errors' => $validate->errors()
                ], 401);
            }

            if ($request->has('password') && $request->filled('password')) {
                $password = Hash::make($request->input('password'));
                $user->update([...$request->all(), 'password' => $password]);
            } else {
                $user->update($request->except(['password']));
            }

             ////////////////////
            // this is where it errors
            ///////////////////
            $user->syncPermissions($request->input('permissions')); 

            return response()->json([
                            'status' => true,
                            'data' => $user
                        ], 200);
        } catch (\Throwable $t) {
            return response()->json([
                            'status' => false,
                            'message' => 'Update failed',
                            'errors' => $t->getMessage()
                        ], 401);
        }
    }

``` 

**Versions**
composer show | grep 'laravel'
laravel/framework                  v9.42.0 The Laravel Framework.
laravel/pint                       v1.2.1  An opinionated code formatter for PHP.
laravel/sail                       v1.16.3 Docker files for running a basic Laravel application.
laravel/sanctum                    v3.0.1  Laravel Sanctum provides a featherweight authentication system for SPAs and simpl...
laravel/serializable-closure       v1.2.2  Laravel Serializable Closure provides an easy and secure way to serialize closure...
laravel/tinker                     v2.7.3  Powerful REPL for the Laravel framework.
spatie/laravel-ignition            1.6.1   A beautiful error page for Laravel applications.
spatie/laravel-permission          5.8.0   Permission handling for Laravel 6.0 and up

PHP version:
PHP 8.1.12 (cli) (built: Oct 28 2022 17:39:37) (NTS)

 
![Screenshot 2023-03-04 at 3 03 06 PM](https://user-images.githubusercontent.com/4956550/222928737-557ec201-4df6-40f2-8050-3bb9b9a2d0d5.png)

**Comment by ODelibalta** [comment]
Request headers screen shot
![Screenshot 2023-03-04 at 3 10 07 PM](https://user-images.githubusercontent.com/4956550/222928810-3fdb5f5f-02ad-4672-83a1-8081e538f6f0.png)

**Comment by drbyte** [comment]
This package uses the `name` field for testing whether a permission exists.
In your case there is indeed no permission `name` named `Administrator`. Instead, it's named `can_admin`.
Thus the error message is correct.

**Comment by ODelibalta** [comment]
@drbyte Thank you for taking your time to help out. I am confused though. In my second screen shot, which shows the request headers, there is a permission with `name:"can_admin"` so I am still confused.

**Comment by drbyte** [comment]
When you created your custom model to add the extra fields, did you also change some lookup functions that may be causing this different behaviour?

**Comment by drbyte** [comment]
Given the wording of the error message, the exception being thrown is `PermissionDoesNotExist::create()`, which is called by the `Permission` model. 
Thus I'm pretty sure that your custom `Permission` model has overridden the `findByName()` method and is no longer doing its lookup correctly. 
Here's the original:
https://github.com/spatie/laravel-permission/blob/490fa00b0c8286659a534d822f7e74c684c86d27/src/Models/Permission.php#L93-L102

**Comment by ODelibalta** [comment]
@drbyte thank you for your help. This is my model 
```php
<?php

namespace App\Models;

use Spatie\Permission\Models\Permission as SpatiePermission;

class Permission extends SpatiePermission
{
    protected $guard_name = 'sanctum';

    /**
    * The attributes that should be hidden for serialization.
    *
    * @var array<int, string>
    */
    protected $hidden = [
        'pivot'
    ];
}

```

I was under the impression that because I am extending `SpatiePermission`, it should have the functions from that class available for itself. 

I am also using the tenancyforlaravel package for sub-domain based tenancy management. I am beginning to think that might be the issue because the following code works which I resorted to using instead of calling the sync function from the package. It has been working without any issues so far, that is why I did not think about it at the beginning. I did follow the [instructions here](https://tenancyforlaravel.com/docs/v3/integrations/spatie) 

```php
public function setPermissionsTo(string $id, array $permissions): void
    {
        $user = User::find($id);

        foreach ($permissions as $permission) {
            if (isset($permission['is_enabled']) && $permission['is_enabled'] * 1 === 1) {
                $user->givePermissionTo($permission['name']);
            } else {
                $user->revokePermissionTo($permission['name']);
            }
        };
    }
```

@drbyte I really appreciate your time, thank you. If preferred, the code above works and I am using that already so this can be closed. I'd still would like to know why it is happening but it is not critical at this point

**Comment by drbyte** [comment]
@ODelibalta Yes, looping through with some custom logic can certainly be a replacement for the `syncPermissions` call. I see that your function does additional checking of a custom field `is_enabled` ... and that's the benefit of a custom function.

The suggestion @erikn69 offered may be helpful too, since it converts the input data to only pass an array of permission-names to set, dropping the other elements. It forces a little different lookup logic, but may suffice if you're only using the the one guard (sanctum in your case).
