### ISSUE TITLE
How to integrate package data with my existing backpack laravel project?

### ISSUE THREAD

**Issue by Almadi777** [spatie/laravel-permission#2350]

**Comment by parallels999** [comment]
Sorry, no idea what is backpack or how integrate it, maybe this
[Laravel-Backpack/PermissionManager](https://github.com/Laravel-Backpack/PermissionManager)
[laravel permission backpack](https://www.google.com/search?q=laravel+permission+backpack&oq=laravel+permission+backpack)

**Comment by drbyte** [comment]
@Almadi777 what do you mean by "integrate"? 
If you've got Backpack installed, then this package is also installed. You simply code your application to respond to permissions/roles according to whatever permissions/roles your users have created.

**Comment by parallels999** [comment]
> If you've got Backpack installed, then this package is also installed.

So, there should be notes about this in the backpack documentation.
It is not an issue

**Comment by Almadi777** [comment]
Hello everyone, thanks for responding.  I meant that I have a project on laravel-backpack, where there are already ready-made controllers, where there are rights for certain roles, at the moment the task is to remove these rights, so that it would be possible to give these rights through the admin panel.  But for some reason, after installing and initializing my controllers in the AppProvider, I did not have such sections with checkboxes as roles and rights, inside users when editing.

**Comment by parallels999** [comment]
> I did not have such sections with checkboxes as roles and rights, inside users when editing.
> Is it possible to rewrite the controller from the vendor, under your own controller? Since my controller has a lot of data related to users

Everything seems like questios for laravel backpack, not for this package, this package has no sections, checkboxes neither GUI

**Comment by systemsolutionweb** [comment]
must be closed
