### ISSUE TITLE
Laravel 10 - php 8.0 in composer requirements?

### ISSUE THREAD

**Issue by masiorama** [spatie/laravel-permission#2352]
Hello, probably I don't get it, but I prefer to ask.
In composer.json I see this configuration:

```
 "require": {
        "php": "^7.4|^8.0",
        "illuminate/contracts": "^7 || ^8 || ^9 || ^10",
        "illuminate/support": "^7 || ^8 || ^9 || ^10",
        "illuminate/auth": "^7 || ^8 || ^9 || ^10"
    },
```
So it seems that laravel 10 is supported, while the php requirement doesn't mention php 8.1 which is minimum requirement for laravel 10.
Am I wrong?
Thanks in advance!

**Comment by SuperDJ** [comment]
`^8.0` includes all minor versions of PHP 8.0 and higher. Also see https://getcomposer.org/doc/articles/versions.md#version-range

**Comment by masiorama** [comment]
Thanks!
