### ISSUE TITLE
There is no role named `administrator`.

### ISSUE THREAD

**Issue by CaReS0107** [spatie/laravel-permission#2356]
**Describe the bug**
When try to seed a user and attach a role to the new user I got  `There is no role named `administrator`.`

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: "^5.9.1"
- illuminate/framework package
- Laravel 10.2
PHP version: 8.1

Issue:
Before assigning role
Role & Permission are created at the DB level and attached to each other. guard name on both are sanctum
If I directly query the model with the name `administrator` I can get the correct result.

Here is my example code and/or tests showing the problem in my app:
![image](https://user-images.githubusercontent.com/32643188/224484828-211c74d3-ca94-4c27-8178-bd3e512c3717.png)
![image](https://user-images.githubusercontent.com/32643188/224484860-fe6d3a28-cbc4-444e-8fc0-481f9f5748f4.png)
<img width="729" alt="image" src="https://user-images.githubusercontent.com/32643188/224484949-c29f2ed6-9454-4ad9-abe4-f5352992b216.png">
<img width="705" alt="image" src="https://user-images.githubusercontent.com/32643188/224484955-07f61ef6-3f29-4602-b055-f7e40219b598.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/32643188/224484968-388975b7-d21f-4573-ab46-1e90bf03bff9.png">

**Comment by vesper8** [comment]
@CaReS0107 what was the issue in the end? I'm also having this problem.. the role clearly exists and yet I get this error when trying to assign it inside of an event listener.

**Comment by drbyte** [comment]
@vesper8 wrote:

> I'm also having this problem.. the role clearly exists and yet I get this error when trying to assign it inside of an event listener.

If this is still an issue for you, can you set up a small demo app that replicates this problem, so we can collaborate on a fix?
