### ISSUE TITLE
can i use this package for two different models in same laravel application

### ISSUE THREAD

**Issue by anandsiddharth** [spatie/laravel-permission#237]
I have two different Guards they are admin and user.
I have 3 different types of users which are all in user model, to manage those users I am about to use this package.
The ony thing I wanted to know that can I use this package in other model i.e. Admins model on the same laravel application.

**Comment by freekmurze** [comment]
In `v1` this is not possible. @AlexVanderbist has started work on `v2`where this use case will be supported. ETA: a few weeks.
