### ISSUE TITLE
The users morphedByMany relation is not working as expected

### ISSUE THREAD

**Issue by NielsKok87** [spatie/laravel-permission#2387]
The morphedByMany relation is not working as expected

$role = Role::with('users')->first();
dd($role);

"Class name must be a valid object or a string"

**Comment by NielsKok87** [comment]
Sorry!
Error on my end

**Comment by sruthitechfriar** [comment]
@NielsKok87 How did you solve this issue? I'm getting the same error

**Comment by WillieOng-HK** [comment]
me too, any helps?
