### ISSUE TITLE
Is there a $role->hasPermissionTo ?

### ISSUE THREAD

**Issue by billbostick** [spatie/laravel-permission#24]
Thanks for sharing this... it's awesome. I need to obtain a list of permissions granted to a role. It appears that the hasPermissionTo method is for the user model only. Is there a means that I've overlooked to get a list of permissions granted to a role? At the moment, I'm getting by with:

```
in_array($permission->name, $role->permissions->pluck('name')->all())
```

**Comment by freekmurze** [comment]
`$role->permissions` is indeed the easiest way to get the permissions of a role.

A function to get the names of all permissions of a role could be handy. . The usage of `pluck` in your example seems fine. I'd accept a PR that adds this to the package.
