### ISSUE TITLE
Wrong permissions on refresh (Vapor/Octane)

### ISSUE THREAD

**Issue by sweebee** [spatie/laravel-permission#2401]
When creating a new role with permissions and assign it to a user, the user randomly gets a 403 message.

The issue seems that i'm using Octane on Laravel Vapor. When you refresh your screen or navigate to another screen you might end up on a different lambda server which still has old cached permissions. after a re-deploy it works fine. So a lamba server must have the permissions still in the memory.

Laravel version: v10.7.1
Permission version: v5.10.0
PHP version: 8.1
Database version: MySQL 8.0.32

**To Reproduce**
Create a new role with permissions and assign it to a user, login as that user.

**Comment by erikn69** [comment]
https://github.com/spatie/laravel-permission/issues/2322#issuecomment-1468410419

**Comment by parallels999** [comment]
On https://github.com/spatie/laravel-permission/issues/2322#issuecomment-1468515838 everything was tested in octane, It would be good to do a test with a minimal installation
