### ISSUE TITLE
Permission only updated after Logout + Login

### ISSUE THREAD

**Issue by Scarwolf** [spatie/laravel-permission#242]
Whenever I remove or add a permission relation to a role I need to logout and in again before it takes effect. Is there a way to tell it to always check the permissions?

**Comment by Scarwolf** [comment]
Ok, found out this is also related to the caching mentioned in #231

**Comment by AlexVanderbist** [comment]
Hey @Scarwolf 

Did clearing the cache solve the issue for you or does it still occur when adding/removing permissions to a role?

Thanks

**Comment by Scarwolf** [comment]
Clearung the cache using `php artisan cache:clear` solves it.

**Comment by drbyte** [comment]
Hmmm ... normally the cache should flush itself every time a new permission or role is added or updated.
