### ISSUE TITLE
Type error: Too few arguments to function App\Http\Middleware\RoleMiddleware::handle(), 3 passed in and exactly 4 expected

### ISSUE THREAD

**Issue by shinokada** [spatie/laravel-permission#243]
I created a middleware [following readme](https://github.com/spatie/laravel-permission#using-a-middleware). 

```
namespace App\Http\Middleware;

use Illuminate\Support\Facades\Auth;
use Closure;

class RoleMiddleware
{
    public function handle($request, Closure $next, $role, $permission)
    {
        if (Auth::guest()) {
            return redirect($urlOfYourLoginPage);
        }

        if (! $request->user()->hasRole($role)) {
            abort(403);
        }

        if (! $request->user()->can($permission)) {
            abort(403);
        }

        return $next($request);
    }
}

```

However I get the following error.

> Type error: Too few arguments to function App\Http\Middleware\RoleMiddleware::handle(), 3 passed in /.../.../vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php on line 148 and exactly 4 expected.

I have another middleware called RedirectIfAuthenticated.php

It has only three arguments.

```
public function handle($request, Closure $next, $guard = null)
    {
        if (Auth::guard($guard)->check()) {
            return redirect('admin/dashboard');
        }

        return $next($request);
    }
```

What am I doing wrong here?

**Comment by drbyte** [comment]
I'm guessing you're not passing all the parameters in your route definition.
