### ISSUE TITLE
permission:show command fails with preventAccessingMissingAttributes enabled

### ISSUE THREAD

**Issue by Cbrad24** [spatie/laravel-permission#2454]
**Describe the bug**
Laravel 9.35 introduced [Eloquent Strictness](https://laravel.com/docs/10.x/eloquent#configuring-eloquent-strictness) parameters. Unfortunately, with strictness enabled, when running `php artisan permission:show` it throws an error due to the command trying to access the team_id property on the Role model.

![Screenshot 2023-06-30 164754](https://github.com/spatie/laravel-permission/assets/2669153/ee64fa2a-e406-423f-a823-bcee9f195e05)

**Versions**
- spatie/laravel-permission package version: 5.10.1
- illuminate/framework package: v10.14.1

PHP version: 8.2.7

Database version: Postgres 15

**To Reproduce**
Steps to reproduce the behaviour:

1. Spin up a Laravel app using `laravel/framework` >= 9.35.
1. Place `Model::preventAccessingMissingAttributes();` in `AppServiceProvider::boot()` method.
1. Install Laravel Permission package.
1. Ensure teams support is disabled.
1. Run migrations.
1. Run `php artisan permission:show`.

**Expected behaviour**
The command should run however it throws an error.

 **Additional context**
Obviously as a workaround you can disable Eloquent Strictness to get the command to run, however this is not a great forever solution.

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: WSL Ubuntu
 - Version: 20.04

**Comment by drbyte** [comment]
@erikn69 I believe this is due to `$team_key => $role->$team_key` in the end of the mapping array on line 41:

https://github.com/spatie/laravel-permission/blob/d8f46bea1d43607829d229e75e661da084089d85/src/Commands/Show.php#L37-L42

`($role->$team_key ?: '')` is used earlier, but doesn't scale to that array...

**Comment by erikn69** [comment]
@Cbrad24 could you test #2457? thanks

**Comment by Cbrad24** [comment]
@erikn69 appears to be working on your branch with `Model::preventAccessingMissingAttributes()` enabled, nice work 👍🏼

**Comment by drbyte** [comment]
Thanks guys!

**Comment by drbyte** [comment]
Closed by Pull Request #2457

**Comment by drbyte** [comment]
Fix released as v`5.10.2`
