### ISSUE TITLE
hasAnyRole method has problem

### ISSUE THREAD

**Issue by raSooolSh** [spatie/laravel-permission#2504]
hasAnyRole() method dosent true work when array pass to this and return false always

**Comment by drbyte** [comment]
The test suite shows that it does work with arrays: https://github.com/spatie/laravel-permission/blob/2cc536247cad8a2bebbad114a389d9af02612f97/tests/HasRolesTest.php#L675-L700

The problem must be in your code somewhere. Please post your code.

**Comment by germanio7** [comment]
I have the same problem. It only works by passing a string as a parameter

**Comment by drbyte** [comment]
Actually, I always just use `hasRole([array])` because hasAnyRole is essentially an alias to hasRole, but without processing guards.

**Comment by drbyte** [comment]
@germanio7 wrote:
> I have the same problem. It only works by passing a string as a parameter

What did you pass as an array? Was it just an array of strings? or a collection? or objects? 
And how many guards do you have in your application? Did it fail because it checked against a different guard?
