### ISSUE TITLE
Documentation has namespace typo.

### ISSUE THREAD

**Issue by superuser-me** [spatie/laravel-permission#2520]
This is my first issue & i'm a beginner and naive, who's learning programming!

On This page,
[https://spatie.be/docs/laravel-permission/v5/basic-usage/middleware#content-package-middleware](https://spatie.be/docs/laravel-permission/v5/basic-usage/middleware#content-package-middleware)

` 'role' => \Spatie\Permission\Middleware\RoleMiddleware::class,`

when i tried registering package middleware inside kernel file it threw error

> Target class [Spatie\Permission\Middleware\RoleMiddleware] does not exist.

i resolved it by replacing it to

`'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,`

The first set uses `Middleware` as the namespace, while the second set uses `Middlewares`.

Changing it to Middlewares solved my issue.

i think docs has this typo so creating this issue!

I'm on 
PHP 8.1.24
Laravel 10.28.0

**Comment by erikn69** [comment]
- https://github.com/spatie/laravel-permission/pull/2499

**Comment by drbyte** [comment]
Thanks for pointing it out. Will be releasing v6 this week, so the docs will be back in sync again then! 
Apologies for any confusion!
