### ISSUE TITLE
[v6] Possible bug on $user->syncRoles($array)

### ISSUE THREAD

**Issue by helderneves91** [spatie/laravel-permission#2530]
**Describe the bug**
Hello, after upgrading to v6, I can't sync an array of role ids to an user.
As far I know, the v6 doesn't break the sync() method right? Am I missing something?

**Versions**
PHP 8.2
laravel , permissions, etc -- latest to date

**Here is my example code and/or tests showing the problem in my app:**
[#2529](https://github.com/spatie/laravel-permission/discussions/2529)

**Comment by helderneves91** [comment]
I think the [#2423 ](https://github.com/spatie/laravel-permission/pull/2423) has something to do with this error.

Let me say it again, the role exists.

**Comment by helderneves91** [comment]
Well, resolved the problem by using ```$user->roles()->sync($validated_data['roles']);``` discarding ```$user->syncRoles($validated_data['roles']);```.

The same logic can be applied to ```$user->syncPermissions()```.

**Comment by erikn69** [comment]
> I think the PR https://github.com/spatie/laravel-permission/pull/2423 has something to do with this error.

No, 
I think the problem is your array, the package needs and int array, like `[42, 43, 44]`, but you have a string array, like `["42", "43", "44"]`, check it that

**Comment by drbyte** [comment]
Is there something we should add to the upgrade docs to clarify this?

**Comment by erikn69** [comment]
> Is there something we should add to the upgrade docs to clarify this?

If my memory serves me right, this was always how it worked.

**Comment by mohammedALhakmy** [comment]
Don't sea the answer my question

**Comment by erikn69** [comment]
@mohammedALhakmy what question?? I don't see any comments from you

**Comment by mohammedALhakmy** [comment]
There is no permission named 1 for guard web.

this is error

**Comment by mohammedALhakmy** [comment]
There is no permission named `4` for guard `web`.
i have this error with the in edit or store the users and roles why can
help me because 2 days with the error 😭😭😭😭

‫في الاثنين، 6 نوفمبر 2023 في 11:08 م تمت كتابة ما يلي بواسطة ‪erikn69‬‏ <‪
***@***.***‬‏>:‬

**Comment by drbyte** [comment]
It appears that your application is sending `"1"` as a string, instead of as an integer when querying a permission. Thus it is searching the name instead of the record ID.

Either pass an `int` for the permission record number, or a `Permission Model instance`, or a `string` of the permission `name`.

**Comment by drbyte** [comment]
It's always helpful when you provide actual code from your application. Without seeing your code it is much more difficult to give specific answers.

**Comment by drbyte** [comment]
> i have this error with the in edit or store the users and roles why can

If you are assigning permissions based on end-user selection in a form, I am guessing that you are sending the permission ID to the form as a checkbox or dropdown, but when you receive the Request data you are not converting those Permission IDs back to `int` (all HTTP Requests from POSTs come as `strings`) before assigning the permission to the user.
If you're always using the record ID in the form, then always convert it back to `int` before using that ID in the assign/sync/remove/etc function calls.

**Comment by mohammedALhakmy** [comment]
this function with store roles  and seam error with store ,edit users olsa store and edit rolse but this function store roles
=========================
    public function store(RoleRequest $request){
        $check_Role = Role::where(['name'=>$request->name])->first();
        if (!empty($check_Role)){
            session()->flash('before_before');
            return  redirect()->route('roles.index');
        }else{
            $role = Role::create(['name' => $request->input('name')]);
            $role->syncPermissions($request->input('permission'));
            session()->flash('add_data');
            return redirect()->route('roles.users');
        }

    }

**Comment by drbyte** [comment]
> `$role->syncPermissions($request->input('permission'));`

If you `dd($request->input('permission'))` you will see that it is a string (numeric yes, but as a string, not an integer) or an array of strings.
Convert `$request->input('permission')` to `int` before calling `syncPermissions()`.

**Comment by mohammedALhakmy** [comment]
this answer 
dd($request->input('permission'))
array:3 [▼ // app\Http\Controllers\Admin\RoleController.php:50
  0 => "1"
  1 => "2"
  2 => "3"
]

**Comment by drbyte** [comment]
Notice that `"1"` and `"2"` and `"3"` are strings.
Convert them to integers before passing them to sync

**Comment by mohammedALhakmy** [comment]
don't show error but not insert any check role just insert name role not check roles why    
$check_Role = Role::where(['name'=>$request->name])->first();
        if (!empty($check_Role)){
            session()->flash('before_before');
            return  redirect()->route('roles.index');
        }else{
            $role = Role::create(['name' => $request->input('name')]);
            $role->syncPermissions();
            session()->flash('add_data');
            return redirect()->route('roles.index');
        }

**Comment by drbyte** [comment]
> $role->syncPermissions();

Calling $role->syncPermissions() without any permission parameters will simply remove all permissions from the $role.

**Comment by mohammedALhakmy** [comment]
what is the correct solution and code

**Comment by drbyte** [comment]
Question: `$request->input('permission')` comes from your Form, right?
How does the `'permission'` field get populated into your form? Where does that data come from? 
Does it come from a database query, and you extract the **numeric `id`'s** to put into the form? 
And then the user ticks checkboxes to select some of those `id`'s?

When those numeric `id`'s come back into `$request->input('permission')`, they arrive as an array of **strings**.
Take that array of strings and **convert it to integers**. Perhaps with something like `array_map`:

```php
$role->syncPermissions(array_map(fn($val)=>(int)$val, $request->input('permission')));
```
or
```php
$role->syncPermissions(collect($request->input('permission')->map(fn($val)=>(int)$val)));
```

**Comment by mohammedALhakmy** [comment]
thank you so much,it is the correct is very good🤩🤩🤩🤩
$role->syncPermissions(collect($request->input('permission')->map(fn($val)=>(int)$val)));

**Comment by webdevmahabub** [comment]
> Question: `$request->input('permission')` comes from your Form, right? How does the `'permission'` field get populated into your form? Where does that data come from? Does it come from a database query, and you extract the **numeric `id`'s** to put into the form? And then the user ticks checkboxes to select some of those `id`'s?
> 
> When those numeric `id`'s come back into `$request->input('permission')`, they arrive as an array of **strings**. Take that array of strings and **convert it to integers**. Perhaps with something like `array_map`:
> 
> ```
> $role->syncPermissions(array_map(fn($val)=>(int)$val, $request->input('permission')));
> ```
> 
> or
> 
> ```
> $role->syncPermissions(collect($request->input('permission')->map(fn($val)=>(int)$val)));
> ```

THANKS my issue solved :  $permissionIds = collect($request->input('permission'))->map(fn($val) => (int)$val)->all();

**Comment by webdevmahabub** [comment]
Or step two   Open your Laravel project's composer.json file.

Find the "require" section in your composer.json file, and change the "  "spatie/laravel-permission": "5.11.*"  like this:   


Save the composer.json file. 

Open your terminal or command prompt and navigate to your Laravel project's root directory.

Run the following command to update your project's dependencies and install the specified version:
composer update spatie/laravel-permission

**Comment by tesseractT** [comment]
> Question: `$request->input('permission')` comes from your Form, right? How does the `'permission'` field get populated into your form? Where does that data come from? Does it come from a database query, and you extract the **numeric `id`'s** to put into the form? And then the user ticks checkboxes to select some of those `id`'s?
> 
> When those numeric `id`'s come back into `$request->input('permission')`, they arrive as an array of **strings**. Take that array of strings and **convert it to integers**. Perhaps with something like `array_map`:
> 
> ```
> $role->syncPermissions(array_map(fn($val)=>(int)$val, $request->input('permission')));
> ```
> 
> or
> 
> ```
> $role->syncPermissions(collect($request->input('permission')->map(fn($val)=>(int)$val)));
> ```

thank you this worked for me!!

**Comment by liamoreilly** [comment]
Hi,

I just ran into this. Indeed I have an array of strings (that are ints). The main issue here is that the behaviour is changed. I am happy to update my code so that I map the array of strings to an array of ints before passing them to syncRoles, but the point is that something has changed this behaviour. Previously syncRoles['1', '2', '3'] worked fine and would find the roles as IDs.

Best,
Liam
