### ISSUE TITLE
Middleware Package installation causing Target class [Spatie\Permission\Middlewares\RoleMiddleware] does not exist.

### ISSUE THREAD

**Issue by emekach** [spatie/laravel-permission#2533]
This is what is on the documentation in v5 https://spatie.be/docs/laravel-permission/v5/basic-usage/middleware
 gives this error [Spatie\Permission\Middlewares\RoleMiddleware] does not exist.

LARAVEL 9 (AND OLDER)

protected $routeMiddleware = [
    // ...
    'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,
    'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,
    'role_or_permission' => \Spatie\Permission\Middlewares\RoleOrPermissionMiddleware::class,
];

LARAVEL 10
protected $middlewareAliases = [
    // ...
    'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,
    'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,
    'role_or_permission' => \Spatie\Permission\Middlewares\RoleOrPermissionMiddleware::class,
];

corrected code should be

LARAVEL 9 (AND OLDER)

protected $routeMiddleware = [
    // ...
    'role' => \Spatie\Permission\Middleware\RoleMiddleware::class,
        'permission' => \Spatie\Permission\Middleware\PermissionMiddleware::class,
        'role_or_permission' => \Spatie\Permission\Middleware\RoleOrPermissionMiddleware::class,
];

LARAVEL 10
protected $middlewareAliases = [
    // ...
  'role' => \Spatie\Permission\Middleware\RoleMiddleware::class,
        'permission' => \Spatie\Permission\Middleware\PermissionMiddleware::class,
        'role_or_permission' => \Spatie\Permission\Middleware\RoleOrPermissionMiddleware::class,
];

**Comment by drbyte** [comment]
No. In v5 and older the namespace was plural Middlewares.
In v6 is was updated to singular: Middleware.

Looks like the docs site is showing v5 as "latest", instead of v6. Will investigate that.

**Comment by drbyte** [comment]
The v5 docs site has been updated. Should be correct now. 

Apologies for the confusion!
