### ISSUE TITLE
[v6] There is no permission named '1' for guard 'web'.

### ISSUE THREAD

**Issue by falkonerX72** [spatie/laravel-permission#2543]
**Describe the bug**
I'm using basic spatie settings  for controlling roles&permissions in my laravel 10 project.

The issue is that I keep facing :
```
**Spatie \ Permission \ Exceptions \ PermissionDoesNotExist
PHP 8.2.4 10.30.0
There is no permission named `whatever***` for guard `web`.** 
```

which happened since upgrading to v6-6.0.1  while using standard commands such as 

  1.  $role->syncPermissions($permissions); and  2. $user->assignRole($request->roles);
  
also I'm using default laravel 'web' guard.

When I'm downgrading to V5.11 or 5.8 I get no error and everything works perfectly !

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version:  _6 - 6.0.1_ 
- illuminate/framework package:       _v10.30.0 Laravel Framework._

PHP version:
_8.2.4_

Database version:

_MariaDB 10.4.28_

**To Reproduce**

Here is my example code and/or tests showing the problem in my app:
```
 $role = Role::findOrFail($id);
        $permissions = $request->permission;

        if (!empty($permissions)) {
            $role->syncPermissions($permissions);
        }
```
&
```
   if ($request->roles) {
            $user->assignRole($request->roles);
        }
```

**Example Application**
Here is a link to my Github repo containing a minimal Laravel application which shows my problem:

https://github.com/falkonerX72/L.estate

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: windows
 - Version 11

**Comment by parallels999** [comment]
Seems like the same https://github.com/spatie/laravel-permission/issues/2530#issuecomment-1779319899 (_again_)

https://github.com/spatie/laravel-permission/blob/bd077c853670c290b69870ee089220e2657480ed/docs/upgrading.md?plain=1#L35
> 1. Due to the improved ULID/UUID/GUID support, any package methods which accept a Permission or Role `id` must pass that `id` as an `integer`. If you pass it as a numeric string, the functions will attempt to lookup the role/permission as a string. In such cases you may see errors such as `There is no permission named '123' for guard 'web'.` (where `'123'` is being treated as a string because it was passed as a string instead of as an integer). This also applies to arrays of id's: if it's an array of strings we will do a lookup on the name instead of on the id. **This will mostly only affect UI pages** because an HTML Request is received as string data. **The solution is simple:** if you're passing integers to a form field, then convert them back to integers when using that field's data for calling functions to grant/assign/sync/remove/revoke permissions and roles.

**Comment by asaph-glea** [comment]
Try this  
public function RolePermissionUpdate(Request $request, $id)
    {
        $role = Role::find($id);
        $permissions = $request->permission;
    
        if (!empty($permissions)) {
            // Fetch permission names by IDs
            $permissionNames = Permission::whereIn('id', $permissions)->pluck('name')->toArray();
            $role->syncPermissions($permissionNames);
        } else {
            // If no permissions are provided, remove all permissions from the role
            $role->syncPermissions([]);
        }
    
        $notification = array(
            'message' => 'Role Permission Updated Successfully',
            'alert-type' => 'success'
        );
        return redirect()->route('all.roles.permission')->with($notification);
    }
    // End Method

**Comment by DeveloperKanwilJabar** [comment]
Try this:

```php
    /**
     * Assign permission to role.
     */
    public function assignPermission(Request $request, Role $role)
    {
        $permissions = $role->permissions()->get();
        $role->revokePermissionTo($permissions);
        $role->givePermissionTo(array_map('intval', $request->permissions));

        return redirect()->back()->with('success',  __('Permissions assigned to role successfully.'));
    }
```

**Comment by greenviewsoft** [comment]
Try This :  https://gstopup.com/there-is-no-permission-named-4-for-guard-web-bug-fixed/
