### ISSUE TITLE
[v5/v6] permission cache not cleared when giving permission

### ISSUE THREAD

**Issue by lk77** [spatie/laravel-permission#2544]
The permission cache is not cleared when giving permissions with givePermissionTo,
it's due to this check :

```
if (is_a($this, get_class(app(PermissionRegistrar::class)->getRoleClass()))) {
    $this->forgetCachedPermissions();
}
```
it's always false,

we can test this in tinker :

```
is_a(User::first(), get_class(app(Spatie\Permission\PermissionRegistrar::class)->getRoleClass()))
[!] Aliasing 'User' to 'App\Models\User' for this Tinker session.
= false
```

**Versions**
- spatie/laravel-permission: 5.11.1
- illuminate/framework: 10.29.0
- php: 8.1.11
- mariadb: 10.9.4

**To Reproduce**

Simply call givePermissionTo and see that the cache is not cleared

**Expected behavior**

The cache is correctly cleared when giving permissions

it's seems to me that v6 has the same type of issue, the code has changed :

```
if (is_a($this, Role::class)) {
    $this->forgetCachedPermissions();
}
```

thanks.

**Comment by parallels999** [comment]
It is not necessary to clear the cache when assigning permissions to an user, because this action does not change anything in the cache, the cache is only cleared when permissions are created/deleted/modified, or when permissions are assigned/removed to a role.

**Comment by lk77** [comment]
@parallels999 it is, i have failing tests because of this issue, i had to manually clear the cache

**Comment by parallels999** [comment]
It is an expected behavior, not an issue

**Comment by parallels999** [comment]
😄😄😄

**Comment by lk77** [comment]
There is an impact, because i can see the permissions of the user when calling `getPermissions` yet calling `can('mypermission')` fail

**Comment by parallels999** [comment]
Maybe 
https://github.com/spatie/laravel-permission/blob/62f22e192711fe56fb55b57b586001f8674b4396/tests/TestCase.php#L86

**Comment by lk77** [comment]
the issue is solved now, and i can reproduce it anymore, perhaps an issue with redis i don't know

**Comment by lk77** [comment]
I found out why :

there is a new key in the config : `register_permission_check_method`

not having that key cause the permissions to not be registered within laravel Gate

**Comment by herpaderpaldent** [comment]
I can reproduce the issue. Today i tried to update from v5 to v6.

```
 expect(test()->test_user->hasPermissionTo('administrate access control groups'))->toBeTrue() // this is true
        ->and(test()->test_user->can('administrate access control groups'))->toBeTrue(); // this is false
```

using 

- cache Redis (same result with array)
- Laravel v10.48.22
- php v8.2
- mariadb 10.7 

How did you get around this issue @lk77?

**Comment by lk77** [comment]
@herpaderpaldent i don't know, the issue disappeared
