### ISSUE TITLE
[Octane] Potential security issue by not resetting teamId?

### ISSUE THREAD

**Issue by jameshulse** [spatie/laravel-permission#2545]
_Sorry, I haven't reproduced this as an issue, but spotted a potential security issue while reading through the code._

In the context of Octane where the `PermissionRegistrar` is a singleton I believe that the `protected $teamId` field should be set to `null` on every Octane tick.

In most cases it wouldn't be an issue as a middleware should set the `teamId` to the correct team, but in certain circumstances this might not be the case and the teamId would persist between requests. This could be a serious security issue as an admin in one team may get admin permission to another team.

As the `OctaneReloadPermissions` listener is optional, I believe a second listener could be created to **always** reset the field with e.g `setPermissionsTeamId(null);`.

**Comment by drbyte** [comment]
Good point. Thanks! Will do some digging...

/cc @erikn69

**Comment by parallels999** [comment]
https://github.com/spatie/laravel-permission/blob/62f22e192711fe56fb55b57b586001f8674b4396/src/Listeners/OctaneReloadPermissions.php#L11
why not just add the following
```php
$event->sandbox->make(PermissionRegistrar::class)->setPermissionsTeamId(null); 
```

**Comment by erikn69** [comment]
@jameshulse hi, try #2547

**Comment by jameshulse** [comment]
That looks like what I would expect @erikn69. Nice work.

**Comment by jameshulse** [comment]
That looks like what I would expect @erikn69. Nice work.
