### ISSUE TITLE
Testing - 500 status code

### ISSUE THREAD

**Issue by davidavz** [spatie/laravel-permission#255]
Hi,

I have a problem when i run a simple test like 
````
$this->get('/')->assertStatus(200);
````
I receive a `500` status code because I use @can on views on a permission that is not yet created.

So I run `$this->artisan("db:seed", ['--class' => 'PermissionsTableSeeder']);` in my `setUp` method.

My question is : Is this the best way to deal with this issue? Any other person had to deal with it?

**Comment by AlexVanderbist** [comment]
Hi @davidavz 

If you're gonna be doing integration tests (like your example) you'll want the application to be completely functional. That includes doing the migrations and seeding any necessary entries to make the application work.

So I'd say yes, definitely the way to deal with the issue.
