### ISSUE TITLE
Error: Call to a member function merge() on array in src\Traits\HasPermissions.php on line 348

### ISSUE THREAD

**Issue by abo-habeba** [spatie/laravel-permission#2551]
When using
// All permissions which apply to the user (inherited and direct)
$user->getAllPermissions();
I get this error

Error: Call to a member function merge() on array in file C:\laragon\www\ecommerce\vendor\spatie\laravel-permission\src\Traits\HasPermissions.php on line 348
![image](https://github.com/spatie/laravel-permission/assets/94226077/e619106f-d3b3-44a4-b5e8-bd9532fc1ee6)

**Comment by drbyte** [comment]
https://github.com/spatie/laravel-permission/blob/641bc2f10d7d5db62f8463a5fc011eb6ce24d3df/src/Traits/HasPermissions.php#L342-L352

It looks like your User model probably has a `$permissions` property that you've added to it, which is conflicting with this package.

See https://spatie.be/docs/laravel-permission/v6/prerequisites#content-must-not-have-a-permission-or-permissions-property-nor-a-permissions-method
