### ISSUE TITLE
How I can return Roles and Permissions of a user with API JSON?

### ISSUE THREAD

**Issue by GamlielMX** [spatie/laravel-permission#256]
I'm writing an API and I need to return the user with all Roles and Permissions he has, but, I don't find the correct way of do that, can anyone help me?

My controller:

`return User::find(1);`

That returns an JSON Object but without Roles and Permissions
When I add "roles" to my model $with property, throws me some errors, same when I try to create a loader like:

`public function allRoles()
{
return $this->roles()->pluck('name');
}`

Thanks in advance

**Comment by freekmurze** [comment]
In your `User` model you can get all role names with:

```php
$this->roles->pluck('name');
```

Notice that we're using `roles` as a property, not as a function.

**Comment by bambamboole** [comment]
I've got the same problem.

i wrote this in User Model:
```
	protected $appends = [ 'roles' ];

	public function getRolesAttribute() {
		$this->roles;
	}
```

but get this error:

```Undefined property: App\User::$roles```

What's my failure?

**Comment by anupamsahoo** [comment]
Here is the solution:

` $roles = Role::all();
  $roles->load('permissions');
   if ($request->ajax()) {
       return response()->json([
       'data' => $roles
       ]);
   }`
Hope this will help.

**Comment by aeadedoyin** [comment]
> I've got the same problem with getting roles and permissions in json.
> 
> i wrote this in User Model:
> 
> ```
> 	protected $appends = [ 'roles' ];
> 
> 	public function getRolesAttribute() {
> 		$this->roles;
> 	}
> ```
> 
> but get this error:
> 
> `Undefined property: App\User::$roles`
> 
> What's my failure?

For those having the same issue, in your user model:.
```
    public function __construct()
    {
        $this->getAllPermissions();
    }
```
So you don't have to add permissions or roles to your append array. For every $user call they both get appended.

**Comment by Derricknjoroge** [comment]
Try

protected $appends = [ 'roles' ];

public function getRolesAttribute() {
    return $this->roles()->pluck('name');
}

**Comment by Derricknjoroge** [comment]
Try

`protected $appends = [ 'roles' ];

public function getRolesAttribute() {
return $this->roles()->pluck('name');
}`

**Comment by Derricknjoroge** [comment]
Try

```
protected $appends = [ 'roles' ];


public function getRolesAttribute() { 

        return $this->roles()->pluck('name'); 

}
```
