### ISSUE TITLE
Relation model_has_roles not found error on Role deletion

### ISSUE THREAD

**Issue by Ivan3008** [spatie/laravel-permission#2572]
My application uses two database connections. First connection is for general database and users table (tenants), second is for tenant databases. 
After upgrading to laravel-permission 6.x i started getting errors when deleting roles, as HasPermissions trait now detaches users from Role model on force deletion.
`Undefined table: 7 ERROR:  relation "model_has_roles" does not exist`

The problem is that Role model uses tenant connection but User model uses central connection , therefore i can't call methods like sync, detach or attach.

Isn't calling detach inside boot method of HasPermissions trait too strict? i'd like to handle data deletion in more flexible way

**Commit where detach was added to boot**
https://github.com/spatie/laravel-permission/commit/25cb3a14faf5311e9344bd7b2e3d9a09bf6fd893#diff-414318d551d45206e27857bc76671901b48cab8630221188f4160c44e8b2cadaR41

**Versions**
spatie/laravel-permission 6.1
PHP version: 8.2
Laravel 10
Database version: postgresql 14

**Comment by parallels999** [comment]
Ok, add a custom Role/Permission model, and overwrite `users` relation, set the real db name on the pivot tables
https://github.com/spatie/laravel-permission/blob/b6b9f4f1120cb5cfbebfc2dc9bf59ef1191cfe38/src/Models/Permission.php#L71-L80
https://github.com/spatie/laravel-permission/blob/b6b9f4f1120cb5cfbebfc2dc9bf59ef1191cfe38/src/Models/Role.php#L80-L89

**Comment by Ivan3008** [comment]
unfortunately it didn't work. also, i tried method setConnection(CONNECTION_NAME) for users relationship, it didn't help either

`Undefined table: 7 ERROR:  relation "tenant_bcc6d892-a4db-40db-b271-fcc6eaaa1276.model_has_roles" does not exist`
`Connection: pgsql, SQL: delete from "tenant_bcc6d892-a4db-40db-b271-fcc6eaaa1276"."model_has_roles" where "tenant_bcc6d892-a4db-40db-b271-fcc6eaaa1276"."model_has_roles"."role_id" = 5`

**Comment by Ivan3008** [comment]
tenant_bcc6d892-a4db-40db-b271-fcc6eaaa1276 is db name.

$connection property for User is 'pgsql', $connection property for Role is 'tenant'

**Comment by parallels999** [comment]
I don't have any experience with postgres, sorry

I don't know if it will be possible to override the boot methods, try that and remove the lines that give you problems
Another option would be to use `softDeletes` trait (which I prefer), so those lines would never be called

**Comment by parallels999** [comment]
**Question:**
can you use the scopes functionality?
because it uses relationships in the same way as users

[https://spatie.be/laravel-permission/basic-usage#content-scopes](https://spatie.be/docs/laravel-permission/v6/basic-usage/basic-usage#content-scopes)

**Comment by parallels999** [comment]
[https://laravel.com/eloquent-relationships#defining-custom-intermediate-table-models](https://laravel.com/docs/10.x/eloquent-relationships#defining-custom-intermediate-table-models)

**Comment by Ivan3008** [comment]
i'll try to overwrite boot method of the trait, if laravel allows overwrite such type of methods

**Comment by Ivan3008** [comment]
thank you @parallels999 for help, finally i overwrote bootHasPermissions method and error's gone. other possible solutions didn't work out in my situation.

anyway, overwriting boot method is not the perfect solution, because any time i'll update app dependencies, i'll need to check if any important changes in package boot method were added, and copy them to my boot

**Comment by Ivan3008** [comment]
also, schemas of model_has_roles and model_has_permissions tables use onDelete('cascade') method, that do the same as detach. that's why i'm not sure we really need to do the same on deletion

https://github.com/spatie/laravel-permission/blob/b6b9f4f1120cb5cfbebfc2dc9bf59ef1191cfe38/database/migrations/create_permission_tables.php.stub#L86

**Comment by parallels999** [comment]
>  use onDelete('cascade') method, that do the same as detach

Normally `softDelete` is used, it's not the same

**Comment by Ivan3008** [comment]
that's right, i missed it
