### ISSUE TITLE
Base table or view not found: 1146 Table 'role_user' doesn't exist

### ISSUE THREAD

**Issue by mohitbabel** [spatie/laravel-permission#2590]
I am using spatie version 5. Whenever I assign new role using this function $user->assignRole('Admin') but I am getting an exception that 
 
Base table or view not found: 1146 Table 'cryo_renewal.role_user' doesn't exist (Connection: mysql, SQL: delete from `role_user` where `role_user`.`user_id` = 1) in spatie laravel problem. What is that error can anyone explain.

**Comment by parallels999** [comment]
https://github.com/spatie/laravel-permission/issues/1507#issuecomment-646829549

**Comment by drbyte** [comment]
https://spatie.be/docs/laravel-permission/v6/prerequisites#content-must-not-have-a-role-or-roles-property-nor-a-roles-method

**Comment by SaifullahAkhtar-001** [comment]
on my side i simply run
"php artisan migrate:fresh --seed"
and it works

**Comment by R00TR41Z** [comment]
Hello everyone!!!. I have problem with laravel permission on migrating , how you can see in the picture
![spatie-permission](https://github.com/spatie/laravel-permission/assets/136341278/b7549010-ffe2-4048-9133-0f35e82bc7c6)
 I need your help friends

**Comment by drbyte** [comment]
> Hello everyone!!!. I have problem with laravel permission on migrating , how you can see in the picture !

Duplicate of #2650

**Comment by xyznaveen** [comment]
Potential FIX: 

If you have `roles()` or `permissions()` defined inside `User` remove it. It's conflicting with the `HasRoles`.

**Comment by sosmongare** [comment]
> Potential FIX:
> 
> If you have `roles()` or `permissions()` defined inside `User` remove it. It's conflicting with the `HasRoles`.

This worked for me
