### ISSUE TITLE
team_id doesn't have a default value

### ISSUE THREAD

**Issue by mauritskorse** [spatie/laravel-permission#2592]
**Describe the bug**
SQL error when creating a new role using the teams functionality: the field `team_id`  has no default value defined.

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: 6.3.0
- laravel/framework package: 10.41

PHP version: 8.2.3

Database version: mariadb 10.11.6

**To Reproduce**
When using the teams function right from the beginning (so not from by using `php artisan permission:setup-teams` afterwards I have a migration that causes an error when trying to create a new global role using:

```php
// with null team_id it creates a global role; global roles can be assigned to any team and they are unique
Role::create(['name' => 'writer', 'organisation_id' => null]);
```
The error I get is
```
QLSTATE[HY000]: General error: 1364 Field 'organisation_id' doesn't have a default value (Connection: mysql, SQL: insert into `roles_user_has_roles` (`model_id`, `model_type`, `role_id`) values (1, User, 1))
```
(i have changed the default team_id to organisation_id in the config, and the user model has an organisation_id field)

When looking at the stub for the migration when adding the teams functionality afterwards ([add_teams_fields.php.stub]()), there are some differences:
On `model_has_permissions` and `model_has_roles` table the `team_foreign_key` gets a default value of 1, while the main stub I had installed did not provide this:
```diff
- $table->unsignedBigInteger($columnNames['team_foreign_key']);
+ $table->unsignedBigInteger($columnNames['team_foreign_key'])->default('1');
```
When applying this change to my migration file, I stop getting the error, however, the role is set to an organisation and not globally.

Another way I got this to work is to set these columns to be nullable, and remove the column from the primary keys:
```php
$table->unsignedBigInteger($columnNames['team_foreign_key'])->nullable(); //->default(1);

$table->primary(
    [
        // $columnNames['team_foreign_key'], // this column is nullable and cannot be a primary key
        $pivotPermission,
        $columnNames['model_morph_key'],
        'model_type'
    ],
    'model_has_permissions_permission_model_type_primary'
);
```

For now I go with the last fix. 
Since I am just starting with this package, I am not sure whether this is the best way.

**Comment by parallels999** [comment]
`team_foreign_key` is nullable
https://github.com/spatie/laravel-permission/blob/9b02e54c2b3aa009128b0df3099fb808fa36b85c/database/migrations/create_permission_tables.php.stub#L36-L39

**Comment by parallels999** [comment]
> insert into `roles_user_has_roles`

`roles_user_has_roles`?

**Comment by mauritskorse** [comment]
Yes, that is on the roles table.
But on the other two tables (model_has_permissions and model_has_roles), it was not defined in the stub:
https://github.com/spatie/laravel-permission/blob/9b02e54c2b3aa009128b0df3099fb808fa36b85c/database/migrations/create_permission_tables.php.stub#L64C58-L64C74

https://github.com/spatie/laravel-permission/blob/9b02e54c2b3aa009128b0df3099fb808fa36b85c/database/migrations/create_permission_tables.php.stub#L88C58-L88C74

And in the other stub a default was set:
https://github.com/spatie/laravel-permission/blob/9b02e54c2b3aa009128b0df3099fb808fa36b85c/database/migrations/add_teams_fields.php.stub#L43

https://github.com/spatie/laravel-permission/blob/9b02e54c2b3aa009128b0df3099fb808fa36b85c/database/migrations/add_teams_fields.php.stub#L62

**Comment by mauritskorse** [comment]
> > insert into `roles_user_has_roles`
> 
> `roles_user_has_roles`?

Ah, yes, I had my tables prefixed ;) Wit default config it is `user_has_roles`

**Comment by parallels999** [comment]
That is the expected behavior, global roles must be assigned by organization, that means the same role could be assigned to many organizations, but not in all automatically
This is so that a group of permissions can be reused across multiple organizations.

**Comment by parallels999** [comment]
#2088
