### ISSUE TITLE
Documentation for v6/main unaccessible at spatie.be

### ISSUE THREAD

**Issue by vlasscontreras** [spatie/laravel-permission#2594]
The docs for v6 cannot be accessed at spatie.be because every _non-existing_ link gets redirected to v5.

Examples:
https://spatie.be/docs/laravel-permission/v6/introduction
https://spatie.be/docs/laravel-permission/v6/advanced-usage/uuid

Additionally, `v6 (main)` is not an option on the top left dropdown.

**Comment by drbyte** [comment]
@freekmurze There is indeed something strange going on.
The docs site is only showing v5 and older:
<img width="439" alt="Screen Shot 2024-01-21 at 3 18 58 PM" src="https://github.com/spatie/laravel-permission/assets/404472/c56b45bf-e8e7-48f1-a6e7-e3c582b1ba4a">
... despite the config specifying v6:
https://github.com/spatie/spatie.be/blob/main/config/docs.php#L253-L263
https://github.com/spatie/spatie.be/blob/7cd2fcc51fe6326a5ac703caaeee43813119d3d8/config/docs.php#L253-L263

However, the laravel-backup and laravel-media-library packages seem to be fine:
<img width="1128" alt="Screen Shot 2024-01-21 at 3 22 53 PM" src="https://github.com/spatie/laravel-permission/assets/404472/4c969ad1-8e64-4eb6-b231-c2e8c9945bfb">

**Comment by parallels999** [comment]
@l2aelba here: https://github.com/spatie/laravel-permission/tree/main/docs

**Comment by drbyte** [comment]
Docs site is restored back to normal operation. 
https://github.com/spatie/spatie.be/issues/290
