### ISSUE TITLE
Wrong octane event listener

### ISSUE THREAD

**Issue by giunashvili** [spatie/laravel-permission#2599]
https://github.com/spatie/laravel-permission/blob/0e593bb9e6808cc55c67f150878b0847f20b9036/src/PermissionServiceProvider.php#L108-L112

In octane there is no \Laravel\Octane\Events\OperationTerminated event. there is Laravel\Octane\Contracts\OperationTerminated event.

![image](https://github.com/spatie/laravel-permission/assets/39676079/e9ce3802-bb76-4455-acc9-137305a7bb2d)

Permissions cleanup won't work like this.

**Comment by erikn69** [comment]
You are right, first was `Events\RequestTerminated`, then it was changed to `OperationTerminated`, but `events` remained
