### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by XavRsl** [spatie/laravel-permission#26]
Hi,
The auth configuration file in Laravel 5.2 changed :
https://github.com/laravel/laravel/blob/develop/config/auth.php
So  ```\Config::get( 'auth.table' )``` in the migration file will no longer get the auth related table. 
Not sure how to get that table name with the new Laravel version...

Thanks,

Xavier

**Comment by freekmurze** [comment]
I hardcoded the value to `users` in the migration. I left a little note in the readme for people who are using a differently named users table.
