### ISSUE TITLE
Enums shouldn't be casted in the model

### ISSUE THREAD

**Issue by schnetzi** [spatie/laravel-permission#2609]
**Describe the bug**
I am using an enum for my roles. It is called `UserRoleEnum`. I somehow thought that I need to cast the enum when saving in the database. So I added the following to my `Role`-Model
```php
    protected $casts = [
        'name' => UserRoleEnum::class,
    ];
```
I know now that this was not needed/causes the package to not work correctly anymore.

**Versions**
- spatie/laravel-permission package version: 6.3.0
- laravel/framework package: v10.43.0

PHP version: 8.3.1

Database version: MySQL 8.2.0

**To Reproduce**
* Setup Laravel and the permission package
* Use an enum for the Role
* Cast the enum in the Model
* Assign a user any role
* Use `hasRole(UserRoleEnum::<ROLE>)` and it will always return false

Here is my example code and/or tests showing the problem in my app:
<img width="564" alt="image" src="https://github.com/spatie/laravel-permission/assets/5382986/c88cadac-7eb4-4902-a768-7e0c6a560169">
The first output are the user roles, the second one the name of the first role and the third one the `hasRole`-check
<img width="708" alt="image" src="https://github.com/spatie/laravel-permission/assets/5382986/8f7f96a7-cb48-4fa3-86ea-6451c8145d5d">

**Example Application**
I didn't create one so far. If you prefer to have one I can set one up. 

**Expected behavior**
I am not sure if it is a bug or a missing information in the documentation (I know that it should say not to cast but it would have saved me a few hours). Both would be valid fixes for me.

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: macOS
 - Version 14.2.1

**Comment by drbyte** [comment]
Instead of `$users[0]->hasRole(UserRoleEnum::ADMIN->value)`, does it work if you remove the `-value` part? (because it does that internally)

**Comment by schnetzi** [comment]
> Instead of `$users[0]->hasRole(UserRoleEnum::ADMIN->value)`, does it work if you remove the `-value` part? (because it does that internally)

Thanks for your quick response. Unfortunately both options do not work. I am ending up in the `HasRole.php::242`-Trait. Where the code is
```php
        if (is_string($roles)) {
            return $guard
                ? $this->roles->where('guard_name', $guard)->contains('name', $roles)
                : $this->roles->contains('name', $roles);
        }
```
and my values are
```php
$roles = "admin";
$guard = null;
```
`$this->roles` is an array with the correct role model. So I didn't understand in the beginning why it didn't work. But my guess is that the contains checks the `string` value and probably compares it to the enum which it gets when casting it.

**Comment by gajosadrian** [comment]
Hi,

did a fix for this. It more like a new feature than a bug 🙂

**Comment by gajosadrian** [comment]
@lucacastelnuovo I didn't code such a feature directly but you can give a try. Comment here if it doesn't work with link to a new feature request. I will manage to code it.

**Comment by gajosadrian** [comment]
@lucacastelnuovo this probably refers to the situation where permissions are not cast to enums and we want to use an enum with the same string key as the permissions key. There was a casting issue in this thread because the roles were mapped from string to enum.
```php
    protected $casts = [
        'name' => UserRoleEnum::class,
    ];
```
So probably permissions won't work the same way.
