### ISSUE TITLE
assignRole is swapping the model_id with role_id

### ISSUE THREAD

**Issue by mohd-isa** [spatie/laravel-permission#263]
Let's assume I've one role as following:

```php
Role::create([
   'name' => 'admin'
]);
```

and one user with this role

```php
$user = User::create([
   'name' => 'John Doe'
]);

$user->assignRole('admin')
```

This would work fine.. as both model_id, and role_id are 1

But when I create the second user, and try to assign it to the role admin, it fails

```php
$user2 = User::create([
   'name' => 'Another user'
]);

$user2->assignRole('admin')
```

It causes this error

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`starter`.`model_has_roles`, CONSTRAINT `model_has_roles_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE) (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (1, Spatie\Permission\Models\Role, 2))
```

By looking at the error, it tries to assign value 2 as a role_id, and that' supposed to be the model_id

**Comment by AlexVanderbist** [comment]
I seem to have mixed up the `foreignKey` and `relatedKey` in the relation. Not sure how that didn't surface during testing... I'll fix it in a couple of minutes

**Comment by mohd-isa** [comment]
Thanks
