### ISSUE TITLE
DOCS - Side menu dissapeared

### ISSUE THREAD

**Issue by wizzymore** [spatie/laravel-permission#2635]
**Before creating a new bug report**
Please check that there isn't already a similar issue on [the issue tracker](https://github.com/spatie/laravel-permission/issues) or in [the discussions](https://github.com/spatie/laravel-permission/discussions).

**Describe the bug**
The side menu of the documentation doesn't have anything above Basic Usage

<img width="291" alt="image" src="https://github.com/spatie/laravel-permission/assets/25827787/ecb232af-b4f0-4d53-a57a-1a59a87bbd7f">

**Expected behavior**
<img width="284" alt="image" src="https://github.com/spatie/laravel-permission/assets/25827787/2730740e-a2ed-4844-bd08-b5d020136e50">

 **Additional context**
It was there yesterday when i wanted to update my app to LV11, today when i entered it's gone and i can't access the upgrade guide.

**Comment by GunniBusch** [comment]
same for me

**Comment by drbyte** [comment]
Ping @freekmurze

**Comment by drbyte** [comment]
Docs site appears to be working correctly again.
