### ISSUE TITLE
Cannot save the user model twice in the same request

### ISSUE THREAD

**Issue by Moundlen** [spatie/laravel-permission#2638]
**Describe the bug**
Hi,
Sorry if this has already been asked but I'm using Laravel fortify to register new users, once user is registered I automatically log him in but I have a listener that listens for Login and automatically edits the user IP and last login and saves the user again. When the user is saved again I get an error Duplicate entry '7-153-User' for key 'model_has_roles.PRIMARY'. 
I fixed the issue by saving quietly but is this expected behavior ?
Now everytime I save a user in the same lifetime cycle it just crashes.
It seems to come from the use of attach instead of sync in the HasRoles trait line 168. see #2420 
Did not have this issue before because I migrated from v4 to v6.

**Versions**
- spatie/laravel-permission package version: 6.4.0
- laravel/framework package: 10.48.3

PHP version: 8.2.16

Database version: mysql 8.0.32

**To Reproduce**

- Create a new User
- Sync or Assign role to the user
- Save the User
- Save the User again

My listener:
```php
public function login(Login $event): void
    {
        try {
            /** @var User $user */
            $user = $event->user;
            activity('Auth')->by($user)
                ->withProperty('IP', request()->getClientIp())
                ->log('Login');

            $user->last_login = Carbon::now();
            $user->last_ip = request()->getClientIp();
            $user->saveQuietly();
        } catch (\Exception $exception) {
            report($exception);
        }
    }
```

**Expected behavior**
I would expect the save to not throw an error if I save the User twice.

**Environment (please complete the following information, because it helps us investigate better):**
 - OS: ubuntu
 - Version: 22.04

**Comment by drbyte** [comment]
1. How are you registering roles to the model? It would be helpful to see what your code is for that, since it should have already finished persisting things and letting go of what was specified to be attached. Seeing your code would help.
2. In your listener, perhaps you can call `$user->fresh()` to have a clean unique instance before updating its properties and saving?

**Comment by Moundlen** [comment]
Hi, here is a simple code to reproduce created a new empty laravel 11 project.
```php
<?php

use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

Route::get('/', function () {
    $user = new \App\Models\User([
        'name' => \Illuminate\Support\Str::random(),
        'password' => \Illuminate\Support\Str::random(),
        'email' => \Illuminate\Support\Str::random() . '@example.com',
    ]);
    if (Role::where('name', 'writer')->doesntExist()) {
        $role = Role::create(['name' => 'writer']);
        $permission = Permission::create(['name' => 'edit articles']);
        $role->givePermissionTo($permission);
    }
    $user->assignRole('writer');

    $user->save();
    $user->fresh();
    $user->save();
});
```

**Comment by drbyte** [comment]
Thanks for the code sample.

Yes, if you're creating a User with `new`, then it is not yet persisted into the database, and attached pivots are getting duplicated when calling `save()`.

However, if you first `->save()` that unpersisted User before calling `assignRole()`/etc, subsequent saves will not be problematic.

Also, if you use `User::create()` instead of `new User`, none of these problems occur.

**Comment by drbyte** [comment]
@erikn69 I'm interested in your thoughts about how to avoid these "Duplicate entry" errors when attaching to an un-persisted model.

Ref: #2419 #2420 #2574 
Ref: https://github.com/laravel/framework/blob/master/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php

**Comment by erikn69** [comment]
I think it is a problem that has always been present.
A validation could be added, 
I would have to do tests, I think that adding `wasRecentlyCreated` would solve it
https://github.com/spatie/laravel-permission/blob/ce67a8b0b08c9c54659984cdfd9ea7bac07920b3/src/Traits/HasPermissions.php#L405-L414

**Comment by parallels999** [comment]
@ue-shuston hi, did you test #2658? does it work?

**Comment by ue-shuston** [comment]
Yes, for our use case the changes made in https://github.com/spatie/laravel-permission/pull/2658 worked.

Alternatively, changing `->attach(` to `->sync(` on:
https://github.com/spatie/laravel-permission/blob/c99dca701d60e1a2d1f839c9bfd102b8098432fe/src/Traits/HasPermissions.php#L410
https://github.com/spatie/laravel-permission/blob/c99dca701d60e1a2d1f839c9bfd102b8098432fe/src/Traits/HasRoles.php#L168
also resolved the problem.

**Comment by parallels999** [comment]
>Alternatively, changing `->attach(` to `->sync(` on:

That would return an old problem: https://github.com/spatie/laravel-permission/discussions/2419#discussioncomment-5773209

**Comment by ue-shuston** [comment]
@parallels999 Understood, we had assumed that using `->sync(` was too obvious of a fix, and that there had been some reason to not utilize it. But https://github.com/spatie/laravel-permission/pull/2658 does resolve this issue. Is there a schedule for it to be merged?
