### ISSUE TITLE
RoleDoesNotExist while the role is already exist.

### ISSUE THREAD

**Issue by mohd-isa** [spatie/laravel-permission#264]
By simply assigning the user to some specific role. It throws RoleDoesNotExist exception.

The role is already created.

By debugging the cause of this issue, it seems that this function fails to fetch the role by name

```php
// Role.php
public static function findByName(string $name, $guardName = null): RoleContract
{
    $guardName = $guardName ?? config('auth.defaults.guard');

    $role = static::where('name', $name)->where('guard_name', $guardName)->first();

    if (! $role) {
        throw RoleDoesNotExist::create($name);
    }

    return $role;
}
```

the value of $guardName is always null which causes to the query to fail to retrieve the role.

**Comment by AlexVanderbist** [comment]
Hi! 

Do you have a default guard set in your authentication config file?

**Comment by mohd-isa** [comment]
Yes, it's "web"

**Comment by AlexVanderbist** [comment]
Can you `dump` the `$guardName` bellow the following line?
```php
$guardName = $guardName ?? config('auth.defaults.guard');
dump($guardName); // add this
```
At that point $guardName should never be `null` if your config file is set correctly...

**Comment by mohd-isa** [comment]
Yes, I've already did that and it's giving me an empty string.


even though I never touched auth.php and the value of guard is set to "web"
there

**Comment by mohd-isa** [comment]
this check ```$guardName = $guardName ?? config('auth.defaults.guard');``` fails because of the empty string.

**Comment by AlexVanderbist** [comment]
Did you by any chance move the `User` model to another namespace and forgot to update the `auth.php` file accordingly? (I saw that this is the case in the `laravel-starter` project: https://github.com/arados-io/laravel-starter/blob/master/config/auth.php#L70)

**Comment by mohd-isa** [comment]
Yea, that's right.. this fixed the issue.. Thanks.

**Comment by connor11528** [comment]
I am getting this same error. What was the update to the auth.php file?

I am using this starter package: https://github.com/LaravelDaily/laravel-roles-permissions-manager

**Comment by mohd-isa** [comment]
@connor11528  If you changed User model namespace, make sure you update it in auth.php as well

**Comment by connor11528** [comment]
Clearing out the cache and reseeding the database helped me out with this (#359)

For the namespaces you changed I'm a bit unfamiliar with how they work in PHP. This is my **User.php** file

```
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Hash;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    ....
```

And my **auth.php** file:

```
<?php

return [

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

I think the namespaces are all good so maybe it was something to do with the cached data that cleared it out
