### ISSUE TITLE
Docs are not uptodate with current implementation

### ISSUE THREAD

**Issue by func0der** [spatie/laravel-permission#2654]
https://github.com/spatie/laravel-permission/blob/536d41d0c82e8fdbeeb2917ef9225b8059d1d96b/docs/advanced-usage/uuid.md?plain=1#L68

~I am just migrating from v5 to v6 and stumbled upon the migrations.~ (unrelated information)
In v6 you migrated away from static properties on `PermissionRegistrar` and towards using the config in the migration directly.

Yet this change is not reflected in the docs advanced docs for UUID usage mentioned above. There `PermissionRegistrar` is still used.

Bug or better missed documentation, right?

**Comment by parallels999** [comment]
https://github.com/spatie/laravel-permission/blob/536d41d0c82e8fdbeeb2917ef9225b8059d1d96b/docs/upgrading.md?plain=1#L14

**Comment by func0der** [comment]
@parallels999 I don't know what a reference to a line without any comment or context should add to this issue, so I have to guess.

That line does not concern the case I have described above.
The case I described is out of the advanced use case documentation, which tells you how you would use UUID columns on **first** install of this library.
So it needs to be up to date with the **current** version of the migrations.

**Comment by parallels999** [comment]
Feel free to make a PR updating docs

**Comment by parallels999** [comment]
There was a major release, and there was also a  Laravel 11 release  without much difference in time, the documentation was outdated in many aspects

**Comment by drbyte** [comment]
> So this is a confirmed bug in the documentation?

Yes. I'm committing a fix now. Thanks for drawing this to our attention!

**Comment by drbyte** [comment]
Fixed in 1890d8b

**Comment by func0der** [comment]
> Fixed in https://github.com/spatie/laravel-permission/commit/1890d8b49516d84accb8ad8595f596612e135ce3

Awesome. Would have also done this, just wanted to confirm that it is really a bug.
