### ISSUE TITLE
Diffs are not properly displayed in generated docs

### ISSUE THREAD

**Issue by func0der** [spatie/laravel-permission#2655]
Compare: 

https://github.com/spatie/laravel-permission/blob/536d41d0c82e8fdbeeb2917ef9225b8059d1d96b/docs/advanced-usage/uuid.md?plain=1#L68
![image](https://github.com/spatie/laravel-permission/assets/529819/25432507-d9bd-436e-90fc-3890a90c4185)

to: https://spatie.be/docs/laravel-permission/v6/advanced-usage/uuid

![image](https://github.com/spatie/laravel-permission/assets/529819/856fafd8-0b0e-47de-a6c6-de759710bbbe)

**Comment by parallels999** [comment]
https://github.com/spatie/laravel-permission/blob/536d41d0c82e8fdbeeb2917ef9225b8059d1d96b/docs/upgrading.md?plain=1#L14

**Comment by drbyte** [comment]
@freekmurze

**Comment by freekmurze** [comment]
We'll have a look!

**Comment by timvandijck** [comment]
This should be resolved!

**Comment by drbyte** [comment]
Thanks @timvandijck Can you please also kick off a rebuild of this project's docs? There are updates that are missing from the docs site (mostly on this same page).
