### ISSUE TITLE
Bug @can OR $user->can OR $user->hasAnyPermission($permission)

### ISSUE THREAD

**Issue by trungnhan0436** [spatie/laravel-permission#2669]
Bug @can OR $user->can OR $user->hasAnyPermission($permission)

Version 6.7

![image](https://github.com/spatie/laravel-permission/assets/58317021/d844cfc8-d4ce-4a18-969f-1ef86822cc3f)

**Comment by drbyte** [comment]
Yes it's a bug.
But not in this package.

The bug is in your application.
