### ISSUE TITLE
Problems giving permissions to a role when the id field is a uuid type

### ISSUE THREAD

**Issue by Aldamar** [spatie/laravel-permission#2673]
### Description

After updating the migration file according to this [guide ](https://spatie.be/docs/laravel-permission/v6/advanced-usage/uuid), I configure my seeder to assign the default roles and permissions, so when I try to assign the permission to the role with the function `$role->givePermissionTo($permission);` it shows this error:
![image](https://github.com/spatie/laravel-permission/assets/50327786/b79a4af1-e3e5-4cf6-8ebd-7226bb00e1b3)

First I think it was a problem of UUID casting, so extended the model and indicate that the field must be cast to a string, but the problem reamins the same.

### Steps To Reproduce

1. Set the DB driver to `mariadb`.
2. Update the migrations file according to this [guide ](https://spatie.be/docs/laravel-permission/v6/advanced-usage/uuid).
3. 4. Modify the migration on the primary id to get the default value from the Maria DB UUID function `$table->uuid('id')->primary()->unique()->default(DB::raw('UUID()'))` for the permissions and roles tables.
5. Execute the migrations (with the seeder in the example)
6. Try to assign a permission to a role

### Example Application

https://github.com/Aldamar/laravel-permission-problems

### Version of spatie/laravel-permission package:

6.7.0

### Version of laravel/framework package:

v11.8.0

### PHP version:

8.2

### Database engine and version:

MariaDB LTS

### OS: Windows/Mac/Linux version:

Debian in WSL2

**Comment by erikn69** [comment]
It seems to me that you are not adding your custom models to the configuration.
https://github.com/spatie/laravel-permission/blob/c99dca701d60e1a2d1f839c9bfd102b8098432fe/config/permission.php#L16-L27

**Comment by Aldamar** [comment]
Hi @erikn69 
Even changing de models in the permission file the error remains
![image](https://github.com/spatie/laravel-permission/assets/50327786/3469dbe6-bd3e-45cb-8bf5-0d8f4edbc07c)

**Comment by erikn69** [comment]
On your repo https://github.com/Aldamar/laravel-permission-problems/tree/main/app/Models, i didn't found any UUID model
UUID models are tested
https://github.com/spatie/laravel-permission/blob/c99dca701d60e1a2d1f839c9bfd102b8098432fe/tests/TestModels/Permission.php#L18-L36
https://github.com/spatie/laravel-permission/blob/c99dca701d60e1a2d1f839c9bfd102b8098432fe/tests/TestModels/Role.php#L58-L77

**Comment by Aldamar** [comment]
Ty @erikn69 
Now I see my error 😅, sorry for taking your time 🙇🏻‍♂️.
