### ISSUE TITLE
Not working while Bugsnag installed

### ISSUE THREAD

**Issue by meNESS** [spatie/laravel-permission#268]
Hi,

> Argument 3 passed to Spatie\Permission\PermissionRegistrar::__construct() must implement interface Illu  
  minate\Contracts\Logging\Log, instance of Bugsnag\PsrLogger\MultiLogger given

This exception is thrown because I installed Bugsnag package and I bound the Bugsnag PSR logger in the `register()` method of my application service provider `app/Providers/AppServiceProvider.php`

```php
$this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
$this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
```

**Note:** If I comment above lines, everything would work fine, but they're needed while using Bugsnag

How can I fix this?

**Comment by sebastiandedeyne** [comment]
If I understand correctly, you bound a class that doesn't adhere to the `Illuminate\Contracts\Logging\Log` interface to that interface. The correct solution here would be to write your own `Log` implementation that calls Bugsnag under the hood, instead of directly binding `Log` to Bugsnag in the IoC container.

**Comment by timgavin** [comment]
@meNESS I was having a similar issue; publishing the bugsnag config file and flushing the cache fixed it.

```
php artisan vendor:publish
php artisan cache:clear
```

**Comment by meNESS** [comment]
@timgavin It didn't help

**Comment by GrahamCampbell** [comment]
> If I understand correctly, you bound a class that doesn't adhere to the Illuminate\Contracts\Logging\Log interface to that interface.

Bugsnag does provide a class that does though: https://github.com/bugsnag/bugsnag-laravel/blob/master/src/MultiLogger.php.
