### ISSUE TITLE
How to count users with role?

### ISSUE THREAD

**Issue by Nationalcat** [spatie/laravel-permission#269]
I update this package to v2, and I found a question.

 v1 (can work) :
```
//RoleController
$roles = Role ::withCount('users') -> paginate(20);
return view('Role')->with(compact('roles'));

//Role.blade.php
@foreach($roles as $role)
{{$role->users_count}}
@endforeach
```

I update to v2, and show this "Call to undefined method Illuminate\Database\Query\Builder::users()"

I think it's model_has_roles is not related to users table.Can somebody help?

**Comment by freekmurze** [comment]
This is fixed in `v2.1.3`.

**Comment by DubStepMad** [comment]
Would be a great idea if this was mentioned in the docs, thank you for sharing as this has helped me.

**Comment by drbyte** [comment]
Counting records from an Eloquent query is covered in the Laravel docs:
https://laravel.com/docs/master/eloquent-relationships#counting-related-models

**Comment by kevin4dhd** [comment]
I have searched all over the internet and I have not found the correct way to count, for example, how many administrators I have

**Comment by Scemist** [comment]
Unfortunately, I didn't find out a short way. To avoid fixed tables and columns names, the best option is use the built in 'roles' relation to get Users and then the Collection to count;

```php
$superAdminCount = User::with('roles')->get()->filter(
    fn ($user) => $user->roles->where('name', 'Super Admin')->toArray()
)->count();
```

Is huge databases is not ideal, but it's a start point. Please let me know your solutions.

**Comment by aliakel** [comment]
You can create your custom Role model which extends spatie role, then you can use MorphToMany:

use Illuminate\Database\Eloquent\Relations\MorphToMany;

class Role extends \Spatie\Permission\Models\Role
{

  
    public function users(): MorphToMany
    {
        return $this->morphedByMany(
            User::class,
            'model',
            config('permission.table_names.model_has_roles'),
            'role_id',
            config('permission.column_names.model_morph_key')
        );
    }
}

then you can use Role::withCount('users')->where ....
