### ISSUE TITLE
Issue while using Cache+SQlite Laravel 11

### ISSUE THREAD

**Issue by emadha** [spatie/laravel-permission#2691]
### Description

I'm getting this error with this package.

'SQLSTATE[HY000]: General error: 1 near "on": syntax error (Connection: sqlite, SQL: insert into "cache" ("key", "value", "expiration") values (spatie.permission.cache, a:3:{s:5:"alias";a:0:{}s:11:"permissions";a:0:{}s:5:"roles";a:0:{}}, 1720714599) on conflict ("key") do update set "key" = "excluded"."key", "value" = "excluded"."value", 

Solution was to disable cache / set cache to `null` from [config/permission.php](https://github.com/spatie/laravel-permission/blob/80a32a10f7439fe381a5684e78e72cadd8fbd170/config/permission.php#L184)

### Steps To Reproduce

1. Laravel 11
2. sqlite Database Engine
3. try to access a route that may return a role object e.g. /api/user with HasRoles trait;

### Example Application

...

### Version of spatie/laravel-permission package:

6

### Version of laravel/framework package:

11

### PHP version:

8.2.21

### Database engine and version:

SQLite 3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668

### OS: Windows/Mac/Linux version:

3.10.0-1062.1.2.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by parallels999** [comment]
Cache+SQlite+Laravel 11 is tested, look: https://github.com/spatie/laravel-permission/actions/runs/9629009291/job/26557876997

https://github.com/spatie/laravel-permission/blob/80a32a10f7439fe381a5684e78e72cadd8fbd170/.github/workflows/test-cache-drivers.yml#L51-L55

**Comment by emadha** [comment]
i can confirm that on my local machine it works fine, but not on the server running the specs mentioned in the issue body

**Comment by parallels999** [comment]
Tested on my server, it works as expected

**Comment by emadha** [comment]
did you test with the versions mentioned? it was an easy fix and as i mentioned it worked on my local pc, with updated version, just wanted to mention that issue with the config i sent.

**Comment by drbyte** [comment]
Today in 2024, this package makes no effort to support SQLite versions released in 2013.

**Comment by aroon9002ahmed** [comment]
i suggest to change this code in config/permission.php

```
'cache' => [

        /*
         * By default all permissions are cached for 24 hours to speed up performance.
         * When permissions or roles are updated the cache is flushed automatically.
         *
         * Dynamic configuration based on database type:
         * - SQLite: 0 seconds (no cache)
         * - MySQL/Others: 24 hours
         */
        'expiration_time' => \DateInterval::createFromDateString(
            config('database.connections.'.config('database.default').'.driver') === 'sqlite'
                ? '0 seconds'
                : '24 hours'
        ),

        /*
         * The cache key used to store all permissions.
         */
        'key' => 'spatie.permission.cache',

        /*
         * You may optionally indicate a specific cache driver to use for permission and
         * role caching using any of the `store` drivers listed in the cache.php config
         * file. Using 'default' here means to use the `default` set in cache.php.
         *
         * Dynamic store configuration based on database type:
         * - SQLite: 'null' driver (disables caching completely)
         * - MySQL/Others: 'default' driver (uses Laravel's default cache configuration)
         */
        'store' => config('database.connections.'.config('database.default').'.driver') === 'sqlite'
            ? 'null'
            : 'default',
    ],
```
