### ISSUE TITLE
model_has_roles model_type Role in stead of User

### ISSUE THREAD

**Issue by dducro** [spatie/laravel-permission#270]
Hey,

I upgraded to v2.
Made a migration to migrate existing permissions to the new model_has_roles table.
However when calling assignRole on the user the model type is "Spatie\Permission\Models\Role" in stead of User. This prevents the reverse of the relation. You can't find the models associated with a given role.

Any thoughts on this are appreciated!

**Comment by dducro** [comment]
This issue is probably related: #269

**Comment by AlexVanderbist** [comment]
Thanks for reporting this, there appears to be an issue with the `roles()`/`permissions()` relation to the user model. I'm currently looking into it and will push a fix later today!
