### ISSUE TITLE
Migrating to new nova-permissions package, noticed that permissions are hardwired to always have an uppercase first letter?

### ISSUE THREAD

**Issue by Diamundo** [spatie/laravel-permission#2703]
### Description

Hi all, I was previously using [pktharindu/nova-permissions](https://github.com/pktharindu/nova-permissions) and am now migrating to [serenysoft/nova-permissions](https://github.com/serenysoft/nova-permissions). I've written the following migration to move all of the permissions over. I've noticed that in the Permissions table, I need to search for the name with an `ucfirst()`, because otherwise it won't return the permission. I can't find exactly where the permission name is transformed into an uppercase string, so I was hoping you can help with that. Searching the issues/discussions also didn't lead to any tips...

Migration:
```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

use Pktharindu\NovaPermissions\Role as OldRole;
use Pktharindu\NovaPermissions\Permission as OldPermission;

use Sereny\NovaPermissions\Models\Role as NewRole;
use Spatie\Permission\Models\Permission as NewPermission;


/**
 * After the new tables from serenysoft/nova-permissions have been installed, this migration moves all the installed data over to the new tables.
 */
return new class extends Migration
{
    
    public function up()
    {
		// Move roles
		foreach(OldRole::all()->sortBy('id') as $oldRole) {
			$newRole = new NewRole([
				'name' => $oldRole->name,
				'guard_name' => 'web',
				'created_at' => $oldRole->created_at,
				'updated_at' => $oldRole->updated_at,
			]);
			$newRole->save();

			// Assign new role to user.
			foreach($oldRole->users()->get() as $user) {
				$user->assignRole($newRole->name);
			}
		}

		// Move permissions to database.
	    // Permissions themselves are now stored in the database, instead of in the config.
		$config = config('nova-permissions.permissions');
		foreach($config as $permission) {
			$newPermission = new NewPermission([
				'name' => $permission['display_name'], // this contains e.g. "view users" but is stored as "View users"
				'group' => $permission['group'],
				'guard_name' => 'web',
			]);
			$newPermission->save();
		}

	    // Move role_permissions to role_has_permission
		foreach(OldPermission::all()->sortBy('role_id') as $oldRolePermission) {

			// here i need to search by "View users"
			if($newPermission = NewPermission::findByName(ucfirst($oldRolePermission->permission_slug))) {
				/* @var OldRole $oldRole */
				$oldRole = $oldRolePermission->roles()->whereKey($oldRolePermission->role_id)->first();

				/* @var NewRole $newRole */
				if($newRole = NewRole::findByName($oldRole->name)) {
					$newRole->givePermissionTo($newPermission);
				}
			}
		}

    }
    
    public function down()
    {
		dump('reverting this migration is not supported.');
    }
};
```

### Steps To Reproduce

1. Use package [pktharindu/nova-permissions](https://github.com/pktharindu/nova-permissions) mostly succesful. Use permissions written in all lowercase.
2. Decide to migrate to package [serenysoft/nova-permissions](https://github.com/serenysoft/nova-permissions).
3. Write the above migration to transfer all permissions.
4. Notice that for Role 2 (Admin), which has 90% of the same permissions as Role 1 (Super admin), the first permission to be linked fails. It can't find "view users" permission (example) which is stored in the database as "View users".
5. Notice that the new package doesn't do any permission handling, and decide to ask here for advice/help.

Ideally the permission name won't be changed between where it is called in my migration and the point where it's actually stored in the database. This would save a lot of work manually rewriting all of the permissions to uppercase in code which are now coded in lowercase.

### Version of spatie/laravel-permission package:

6.9.0

### Version of laravel/framework package:

9.52.9

### PHP version:

8.0.30

### Database engine and version:

MySQL v8.2.0 Homebrew

### OS: Windows/Mac/Linux version:

macOS Sonoma 14.1

**Comment by parallels999** [comment]
`permission_slug`??

It seems that the problem is with one of those packages, it is not a issue on this
