### ISSUE TITLE
Error migration if Gate::before() added in AppServiceProvider.

### ISSUE THREAD

**Issue by 4andrisbriedis** [spatie/laravel-permission#2712]
### Description

Laravel 11. Runing migration if Super Admin Gate::before() already indicated in AppServiceProvider boot() method.

  ```
0000_00_00_000200_create_permission_tables ......................................................................................... 546.77ms FAIL

   Error 

  Call to a member function prepare() on null

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:592
    588▕ 
    589▕             // For update or delete statements, we want to get the number of rows affected
    590▕             // by the statement and return that back to the developer. We'll first need
    591▕             // to execute the statement and then we'll use PDO to fetch the affected.
  ➜ 592▕             $statement = $this->getPdo()->prepare($query);
    593▕ 
    594▕             $this->bindValues($statement, $this->prepareBindings($bindings));
    595▕ 
    596▕             $statement->execute();

      +8 vendor frames 

  9   database/migrations/0000_00_00_000200_create_permission_tables.php:120
      Illuminate\Cache\Repository::forget("spatie.permission.cache")
      +26 vendor frames 

  36  artisan:13
```

### Steps To Reproduce

1. Install Laravel 11.
2. Add this package.
3. publish, migration, .... 
4. Create "super admin" role.
5. From documentation add Gate::before code in AppServiceProvider boot method.
6. Works.
7. Set new database in .env
8. run php artisan migrate.
9. get error. In description.
...

### Version of spatie/laravel-permission package:

6.9.0 current

### Version of laravel/framework package:

11.21.9

### PHP version:

8.2

### Database engine and version:

Mysql 8

### OS: Windows/Mac/Linux version:

Debian 12 in ddev.

**Comment by parallels999** [comment]
- Maybe related #2704

**Comment by drbyte** [comment]
Yes, it's the same issue as #2704 ... if you're gonna use `CACHE_STORE=database`, you've gotta install the database migration for the cache tables before making calls to the cache system.
