### ISSUE TITLE
Custom permission contract for model not working

### ISSUE THREAD

**Issue by Jeordy** [spatie/laravel-permission#2726]
### Description

I want to switch to UUIDs and have followed the steps for implementing them. I also created the Role and Permission models accordingly. But, when using the HasUuids trait, I get an error:

`  SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (Connection: mysql, SQL: insert into `permissions` (`guard_name`, `name`, `description`, `updated_at`, `created_at`) values (web, users.view, {"en":"View Users","nl":"Toon Gebruikers"}, 2024-09-26 12:35:57, 2024-09-26 12:35:57))
`
So, the trait is not triggered.

Then I added a custom boot function to the model, like so:

`protected static function boot()
    {
        parent::boot();
        static::creating(function ($model) {
            if (empty($model->{$model->getKeyName()})) {
                $model->{$model->getKeyName()} = Str::uuid()->toString();
            }
        });
    }`

But it's not going through this model, even a dump in the boot function does not appear...

In permission config I added:

`'models' => [
        /*
         * When using the "HasPermissions" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your permissions. Of course, it
         * is often just the "Permission" model but you may use whatever you like.
         *
         * The model you want to use as a Permission model needs to implement the
         * `Spatie\Permission\Contracts\Permission` contract.
         */
        'permission' => App\Models\Permission::class,

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your roles. Of course, it
         * is often just the "Role" model but you may use whatever you like.
         *
         * The model you want to use as a Role model needs to implement the
         * `App\Models\Role` contract.
         */
        'role' => App\Models\Role::class,
    ],`

The correct custom models are configured.

Does anyone have the same issue? 

### Steps To Reproduce

Follow the documentation on changing to UUID's.

### Version of spatie/laravel-permission package:

6.9.0

### Version of laravel/framework package:

11.16.0

### PHP version:

8.3.11

### Database engine and version:

Mysql 8.0.36

### OS: Windows/Mac/Linux version:

Mac/Windows

**Comment by Jeordy** [comment]
Sorry, it seems that the model is skipped when using seeders.

**Comment by drbyte** [comment]
> Sorry, it seems that the model is skipped when using seeders.

If you specify ('`use`') the intended model in your seeder, it will use it.
