### ISSUE TITLE
check permission given by the plugin and ownership permission

### ISSUE THREAD

**Issue by stefanocurnis** [spatie/laravel-permission#274]
Hey guys!

Imagine a **Blog** where every admin can edit all the **Posts**. Post author can edit his own posts even if he's not an admin.
I store all my roles and permissions via spatie/laravel-permission and a simple CRUD backend.
Now i have to check for the "edit post" permission at the Gate. This plugin **automatically define Gates** but what if i need to add other controls to the gates, like ownership check? (post.user_id==user.id)
How can i define a duplicate gate with the same name "edit-post" in AuthServiceProvider which checks post.user_id==user.id as well as "edit-post"  permission assigned with this plugin?

Thanks a lot for your packages! :)

**Comment by freekmurze** [comment]
I don't get what you mean with duplicate gates. I'd have only one `edit-post` check that first checks if a user is and admin and then if the user is the owner of the post.
