### ISSUE TITLE
Setting Admin role to always have all permissions

### ISSUE THREAD

**Issue by kjdion84** [spatie/laravel-permission#275]
Currently I'm finding myself having to do the following:

`@if (Auth::user()->hasRole('Admin') || Auth::user()->can('Edit User Roles'))`

Instead of just:

`@can('Edit User Roles')`

I don't want to have to update the Admin role every single time I add new permissions. What is the best way of ensuring an admin always `can()`?

I've already put logic in my middleware for this, e.g.:

```
if (!Auth::user()->hasRole('Admin') && !Auth::user()->can($permission)) {
    abort(403);
}
```

Would be great if the config file included some type of admin role name you could specify which would always give the user with that role every permission.

**Comment by sebastiandedeyne** [comment]
You can use a policy filter to return `true` or `false` for any `can` call (scroll a bit down in this link)

https://laravel.com/docs/5.4/authorization#gates

**Comment by sebastiandedeyne** [comment]
Half-ignore the last comment, it's not a policy filter, but the `Gate` facade allows you to define a `before` closure.

```php
Gate::before(function ($user) {
    if ($user->hasRole('Admin')) {
        return true;
    }
});
```

**Comment by kjdion84** [comment]
Thank you!
