### ISSUE TITLE
Can no longer delete permissions returned by "findByName"

### ISSUE THREAD

**Issue by Sfonxs** [spatie/laravel-permission#2758]
### Description

Before when doing:
$permission = Permission::findByName($name, $guardName);

And then calling:
$permission->delete()

The permission would be correct deleted.

Now this no longer happens because the "$exists" property on the permission model being false instead of true.

This behavior has changed since version 6.10.0, worked fine in 6.9.0.

### Steps To Reproduce

1. $permission = Permission::findByName($name, $guardName);
2. $permission->delete()
3. Notice the permission is not deleted.

### Version of spatie/laravel-permission package:

6.10.0

### Version of laravel/framework package:

11.30.0

### PHP version:

8.3

### Database engine and version:

singlestore

### OS: Windows/Mac/Linux version:

Ubuntu

**Comment by erikn69** [comment]
Hi, try #2759
