### ISSUE TITLE
Using different guards

### ISSUE THREAD

**Issue by waygou** [spatie/laravel-permission#283]
Hi,

I'm trying to pass a guard on the assignRole but I don't understand how to do it following the documentation (suggest putting an example there).

`

        $role = Role::create(['guard_name' => 'backoffice', 'name' => 'admin']);
        $user = User::create(['name'     => config('backoffice.admin_user.name'),
                              'email'    => config('backoffice.admin_user.email'),
                              'password' => bcrypt(config('backoffice.admin_user.password')),
                              'status'   => 'active']);

        //Assign admin role
        $user->assignRole('admin'); <- Here is the issue. How do I pass the guard?
`

Thanks in advance!

**Comment by freekmurze** [comment]
You don't need to pass a guard name. The package will handle this behind the screens.

When using `assignRole` on a `user` it will automatically search for a `Role` with the given name that has the same `guard_name` as the `user` it being called upon.
