### ISSUE TITLE
[1.3]: php artisan vendor:publish does nothing.

### ISSUE THREAD

**Issue by Tjoosten** [spatie/laravel-permission#284]
Hi i'm working on a app (production server: php 5.6.23) and i install v1.3 from this package. 

**Laravel version: 5.4.20**

But the publish command does nothing. 

```php 
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"
Publishing complete.
``` 

But the files are not loaded and i also registered the service provider

**Comment by freekmurze** [comment]
Could you try clearing the your cache with `config:clear`, and maybe `cache:clear` and try again?

Reopen this issue of you can recreate it in a vanilla version of Laravel.

**Comment by Talmon** [comment]
Run this command :
php artisan cache:forget spatie.permission.cache
Then try running your vendor:publish commands,it should work.
