### ISSUE TITLE
How to add multiple roles in Route::group ?

### ISSUE THREAD

**Issue by DiakosavvasN** [spatie/laravel-permission#287]
Im trying to add more that one role in the Route::group. 

`Route::group(['middleware' => ['role:[admin,editor]']], function () {
    Route::get('admin/general', 'AdminController@general');
});`

Is this possible ?

**Comment by freekmurze** [comment]
There's an example on how to do this [in the readme](https://github.com/spatie/laravel-permission#using-a-middleware).

**Comment by carlosrgzm** [comment]
In the readme file example, you are setting ['middleware' => ['role:admin,access_backend']], but access_backend is a passed as a permission when it comes to the middleware, not as a role param. So is that possible add more than one role ?

**Comment by CarlosPovedaBarragan** [comment]
The solution is ['middleware' => ['role:admin,access backend']] put between roles ",".

**Comment by pcfreak** [comment]
Try Route::group(['middleware' => ['role:admin|editor']]

**Comment by soringabriel** [comment]
> Try Route::group(['middleware' => ['role:admin|editor']]

This worked for me 👍

**Comment by OrtizDroguett** [comment]
> ayisha

Thank you, muchas gracias.
