### ISSUE TITLE
hasPermissionTo and can methods not in sync in same HTTP request

### ISSUE THREAD

**Issue by acacha** [spatie/laravel-permission#288]
If I understand correctly the code registerPermissions method at PermissionRegistrar:

https://github.com/spatie/laravel-permission/blob/master/src/PermissionRegistrar.php

is the method responsible of registering Gates for al permissions created with spatie/laravel-permission package. This method is executed i every request at boot method in PermissionServiceProvider.

The problem is that I can't create (in the same HTTP request)  a permission, assign the permission to a user and then use can to check de permission in the same request.

For example in a test:

```php

 /**
     * Authorized user can browse users managment.
     *
     * @test
     * @group failing
     * @return void
     */
    public function authorized_user_can_browse_users_management()
    {
        $user = factory($class)->create();
        Permission::firstOrCreate(['name' => 'manage users']);
        $user->givePermissionTo('manage users');
        $this->signIn($user);
        $this->get('/management/users');

        $response->assertStatus(200);
    }
```

```php
The controller for /management/users URL:

/**
     * Show the application dashboard.
     *
     * @return Response
     */
    public function index()
    {
        dump(Auth::user()->hasPermissionTo('manage-users'));
        dump(Auth::user()->can('manage-users'));
        $this->authorize('manage-users');
        return view('acacha_users::managment');
    }
```
The problem is that (see dumps in code):
- Auth::user()->hasPermissionTo('manage-users') returns true
- Auth::user()->can('manage-users') returns false

I can solve the problem executing:

```php
        app(PermissionRegistrar::class)->registerPermissions();
```
Just after the creation of the new permission...

Maybe a solution could be use event models like in RefreshesPermissionCache:

https://github.com/spatie/laravel-permission/blob/master/src/Traits/RefreshesPermissionCache.php

To force execution of registerPermissions when a new model is created/edited or deleted?

**Comment by acacha** [comment]
What do you think? I could propose a PR if you think the solution could be using event models...

**Comment by freekmurze** [comment]
Although I like the solution, I'm afraid of performance problems. 

But if you create a fully tested, backward compatible PR, I'd consider pulling it in.
