### ISSUE TITLE
Confused? Role does not exist?

### ISSUE THREAD

**Issue by SeoRoman** [spatie/laravel-permission#289]
I created 3 basic roles to test with...

    Role::create(['guard_name' => 'super-admin', 'name' => 'superadmin']);
    Role::create(['guard_name' => 'admin', 'name' => 'admin']);
    Role::create(['guard_name' => 'user', 'name' => 'user']);

I assigned the role during a debug test...

auth()->loginUsingId(1);

auth()->user()->assignRole('admin');

// Error retrieved...
RoleDoesNotExist in RoleDoesNotExist.php line 11:
There is no role named `admin`.

There is clearly a role named 'admin' and the 'guard-name' is also 'admin'

Why can't I find it? 

<img width="516" alt="screen shot 2017-05-05 at 12 56 45 pm" src="https://cloud.githubusercontent.com/assets/4356085/25757979/535d8216-3192-11e7-8afe-2802ed5e0d96.png">

**Comment by SeoRoman** [comment]
Additional Comment: I have already gone through and performed the clear cache as it stated as well... just in case :D

**Comment by SeoRoman** [comment]
From what I can gather...

it's using the guard 'web' in my whoops debugger: 
Role::findByName('admin', 'web')

oh, I think I see what the reasoning is for this... testing in a second and I will delete if I figured it out :D

**Comment by wyudong** [comment]
@SeoRoman Have you resolved your issue?

**Comment by ChiefScript** [comment]
@SeoRoman What have you set as your guard_name? I was facing the same issue until I set it as 'web'. I believe it's beacuse that is the default guard set on 'auth.php'

**Comment by wyudong** [comment]
@ChiefScript Check latest comments in issue #276

**Comment by sushantDev** [comment]
I had the same issue and have figured out the solution and i.e.

First add "protected $guard_name = 'api';" in User.php (Model file).
![image](https://user-images.githubusercontent.com/22152364/41336658-9f843938-6f0c-11e8-8ac1-2b7c8f55ddbf.png)

Then, Change your field guard_name to "api" in your roles table as shown in screenshot below.
![image](https://user-images.githubusercontent.com/22152364/41336774-e90cec44-6f0c-11e8-96af-17d04bc36858.png)

Enjoy Coding :)
Feel Free to Reply for any issues regarding this.

**Comment by rustwayne** [comment]
> I had the same issue and have figured out the solution and i.e.
> 
> First add "protected $guard_name = 'api';" in User.php (Model file).
> ![image](https://user-images.githubusercontent.com/22152364/41336658-9f843938-6f0c-11e8-8ac1-2b7c8f55ddbf.png)
> 
> Then, Change your field guard_name to "api" in your roles table as shown in screenshot below.
> ![image](https://user-images.githubusercontent.com/22152364/41336774-e90cec44-6f0c-11e8-96af-17d04bc36858.png)
> 
> Enjoy Coding :)
> Feel Free to Reply for any issues regarding this.

I love you

**Comment by jiahong96** [comment]
> I had the same issue and have figured out the solution and i.e.
> 
> First add "protected $guard_name = 'api';" in User.php (Model file).
> ![image](https://user-images.githubusercontent.com/22152364/41336658-9f843938-6f0c-11e8-8ac1-2b7c8f55ddbf.png)
> 
> Then, Change your field guard_name to "api" in your roles table as shown in screenshot below.
> ![image](https://user-images.githubusercontent.com/22152364/41336774-e90cec44-6f0c-11e8-96af-17d04bc36858.png)
> 
> Enjoy Coding :)
> Feel Free to Reply for any issues regarding this.

Hi.. I got there is no permission named `some permission` for guard `api, any idea?

**Comment by shahraza-stack** [comment]
Thanks for your help :)
