### ISSUE TITLE
Primary index should be composed by the 3 columns

### ISSUE THREAD

**Issue by waygou** [spatie/laravel-permission#291]
Hi,

If I have the same role_id and model_id but a different model_type, it gives a integrity constraint violation.

In my case I am using 2 different Models (User and MenuLink) where I am assigning the same role id and the same model ids but different Model types.

To correct this, you can change:
```
$table->primary(['permission_id', 'model_id']);
```
to
```
$table->primary(['permission_id', 'model_id', 'model_type']);
```
in the migration file, for the table model_has_roles and model_has_types.

After that change in the migration file, I can then have this:

![capture](https://cloud.githubusercontent.com/assets/5596403/25865383/0580f83e-34f3-11e7-8761-f6860d3de605.JPG)

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention.

I've just tagged a new release that fixes this.
