### ISSUE TITLE
New feature: possibility to "scope" roles and permissions to a particular resource.

### ISSUE THREAD

**Issue by IlCallo** [spatie/laravel-permission#292]
Hey guys, for a project of mine I needed a system like yours, but with more flexibility.
In particular, I needed the possibility to bind permissions and roles to certain resources.

[I modded your project to add that functionality](https://github.com/IlCallo/laravel-permission/tree/feature/restrictable-roles-and-permissions)

The previous usage is nearly unchanged (it's no more possible to provide ...$roles and ...$permissions in some methods) and works as usual.
On the other hand, providing as second parameter a resource implementing the Restrictable interface will "scope" the added/removed/synced permission/role to that resource.

I tryed to follow your Pull Request rules, but I'm unsure about the versioning one: ...$roles and ...$permissions removal DOES break a little the previous API, but it just don't feel right to increment a major version. Any thoughts about this?

If you are interested, take a look to my code and, if you like the enhancement, I can send a pull request.

Cya!

**Comment by freekmurze** [comment]
Hi,

thanks for this proposal, but as we don't need this functionality ourselves, we're probably not going to add it to the package.

So keep on using your modded version 👍
