### ISSUE TITLE
Authentication drivers & Naming convention of pivot tables

### ISSUE THREAD

**Issue by hiendv** [spatie/laravel-permission#30]
Since Laravel 5.2 has already supported Mupltiple Authentication, configurations like User Permissions Table (`user_has_permissions`) and User Roles Table (`user_has_roles`) should be attached to drives (array? maybe). Creating a branch for Laravel 5.2.* and higher is a great idea, I think.

Moreover, I think we should keep the naming convention of pivot tables of default configurations between these entities:
User - Permission table : `permission_user`
User - Role table: `role_user`
Permission - Role table: `permission_role`

**Comment by djallits** [comment]
I believe you can rename the pivot tables via the provided config file.

**Comment by hiendv** [comment]
@djallits It's not that simple I afraid. For example, you have 2 drivers: frontend and backend. Configuring twice, publishing twice and being forced to edit the later configuration is painful ! Imagine `n` drivers?
@freekmurze Ping ! Let me hear your thought !

**Comment by freekmurze** [comment]
We're planning on changing our [Laravel template](https://github.com/spatie-custom/blender) so it'll use backend users en frontend users. When that happens I'll take a look at adding support for multi auth to this package. 

ETA a few months. If you need support for multi auth quick, I'll be happy to pull a PR that adds this to package.

**Comment by hiendv** [comment]
You're busy on other projects so please create a branch for laravel 5.2.* so that I can make PRs to.

**Comment by freekmurze** [comment]
If your changes are good, I'll merge and tag them.
