### ISSUE TITLE
$user->permissions() and $user->roles()->permissions() not in sync

### ISSUE THREAD

**Issue by acacha** [spatie/laravel-permission#300]
I don't know if this is a bug or an intended behaviour....

But IMHO te permissions obtained through $user->permissions() relationships will be the same as all the permissions obtained though roles.

I have a user with and assigned role and this role have 9 related permissions but user->permissions() relationship return a void collection.

**Comment by freekmurze** [comment]
A user can have direct permissions and permissions via the roles. These permissions do not have to be the same. That why `$user->permissions()` and `$user->roles()->permissions() ` do not return the same result.

You can get all permissions with `$user->getAllPermissions()`.

**Comment by acacha** [comment]
Thanks I will use $user->getAllPermissions()!
