### ISSUE TITLE
Laravel 5.5 branch

### ISSUE THREAD

**Issue by flick36** [spatie/laravel-permission#301]
Since Laravel 5.5 will be the next LTS version of Laravel, is there a branch of the package that we can use to start developing on the 5.5 dev version of Laravel, since well it's almost around the corner 😋 ?

![Laravel 5.5 error](http://i.imgur.com/H08jwck.png)

**Comment by freekmurze** [comment]
We'll probably tag new releases with L5.5 compatibilty as soon as it is released. We have a good track record on that.

Having a seperate branch for all our repo's now is just too much overhead.

Fork the package and update the constrait there.
