### ISSUE TITLE
Remove Pivot From Json

### ISSUE THREAD

**Issue by bambamboole** [spatie/laravel-permission#302]
When return Json with this code:

```
		$users = User::with('roles')->latest()->paginate();

		if($request->wantsJson()){
			return response()->json($users, 200);
		}
```

then it returns json like this:

```
	{
id: 1,
name: "Magdalena Bednar",
email: "admin@admin.com",
avatar: "/storage/avatar/default.svg",
created_at: "2017-05-20 14:07:17",
updated_at: "2017-05-20 14:07:17",
roles: [
{
id: 1,
name: "Admin",
created_at: "2017-05-20 14:07:16",
updated_at: "2017-05-20 14:07:16",
pivot: {
user_id: 1,
role_id: 1
}
}
]
},
{
id: 2,
name: "Lurline Muller Sr.",
email: "user@user.com",
avatar: "/storage/avatar/default.svg",
created_at: "2017-05-20 14:07:17",
updated_at: "2017-05-20 14:07:17",
roles: [
{
id: 2,
name: "User",
created_at: "2017-05-20 14:07:17",
updated_at: "2017-05-20 14:07:17",
pivot: {
user_id: 2,
role_id: 2
}
}
]
},
```

It set on the User and the Role Model `protected $hidden = ['pivot'];` but that doesn't works...
Any suggestion why I can't remove it ?

**Comment by freekmurze** [comment]
This problem is not related to this package. Not sure why adding it to `hidden` doesn't work.

Best to open up an issue at [Laravel framework](https://github.com/laravel/framework).

**Comment by omarjebari** [comment]
Setting $hidden = ['pivot'] on the Spatie Role and Permission models does fix this problem but they are a part of the vendor packages so shouldn't be changed. The only existing solution is to extend these models but this seems excessive given that it's often only to accomplish this.
I think it is a good idea for the package to be modified to remove 'pivot' from the data returned as i can't imagine a scenario where users want this in the returned data.
The alternative is to add extra functions like 'getAllPermssionsWithoutPivot'.
Please implement a fix for this.

**Comment by drbyte** [comment]
> @omarjebari wrote: 
> remove 'pivot' from the data returned as i can't imagine a scenario where users want this in the returned data.

Let's discuss: what are the negative side-effects of setting `$hidden = ['pivot']` on the role and permission models? What breaking changes could that introduce?

**Comment by omarjebari** [comment]
Thanks for your quick response.
Is there a scenario where the pivot fields are useful? The data in them (user_id/role_id/permission_id) are all available anyway so why is this relationship required?
In most cases the developer wants to pass the models to the frontend where the pivots are redundant.
It seems excessive to have to extend the Spatie Role and Permission models simply to set the $hidden variable. I think if you can think of a single use case where they are needed then it makes sense to leave them as they are. Currently i'm using a vuex package that allows you to map backend data directly to frontend models and i have to remove the pivot field to do so as i don't need it in the frontend. Going forward i think that there is a trend where more js packages will encourage the mapping of models between backend and frontend and the 'pivot' field just gets in the way. It serves no purpose, purely an Eloquent hangover.

**Comment by drbyte** [comment]
I fully understand the desire and reason to remove the pivot data. 

I'm just trying to make sure we're not creating a backward-compatibility break.

**Comment by omarjebari** [comment]
Yep fair enough

**Comment by drbyte** [comment]
Have you considered pointing your vuex package to a ResourceCollection response, where you can customize the output?
https://laravel.com/docs/5.7/eloquent-resources
https://scotch.io/tutorials/laravel-eloquent-api-resources

**Comment by omarjebari** [comment]
Ok i can do this, happy for you to close this ticket.
Bear in mind that i have to do this on every project though so it almost feels a bit like a bug ;)

**Comment by drbyte** [comment]
I hear you ;)

**Comment by Loown** [comment]
This is still a bug

**Comment by drbyte** [comment]
@Loown wrote:
> This is still a bug

Care to elaborate? 

"Bug" implies that something is broken.
"Undesired behavior" is something else. 

What's the use-case you're running into?

**Comment by MattLoyeD** [comment]
Kudos to some random guys on the internet : https://stackoverflow.com/a/79402726

Solution might be to just add a hook in you AppServiceProvider boot method :
```
Role::retrieved(function ($role) {
     $role->makeHidden(['pivot']);
});
```
