### ISSUE TITLE
(Question) How do you expose Laravel permissions to Vue.js

### ISSUE THREAD

**Issue by acacha** [spatie/laravel-permission#303]
I write an article of how I expose Laravel permissions to Vue.js at:

https://medium.com/@sergiturbadenas/how-i-expose-laravel-permissions-in-vue-js-49dd05bedfce

Any better idea or suggestion? Do you think it could be useful to add the Trait ExposePermissions (or something similar) to this package? 

Feel free to close the issue this is only for archive/discussion I think maybe somebody could fint that useful...

**Comment by freekmurze** [comment]
Setting a `roles` property on the `window` object (like you did in the article) seems like a nice way to go about this.

I feel an `ExposePermissions` is out of scope for this package.
