### ISSUE TITLE
BadMethodCallException assignRole()

### ISSUE THREAD

**Issue by behzadev** [spatie/laravel-permission#305]
Hello, thanks for this package but I can't get it to work, here is what i've done so far, and I can't see what I am missing, I spend 4 hours to fix this but no chance yet.

so first I installed using:
`composer require spatie/laravel-permission`

then added the provider in config/app.php:
`Spatie\Permission\PermissionServiceProvider::class,`

then:
`php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"`
`php artisan migrate`
`php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"`

all the above commands go well.

then in my User.php model class, I defined the namespace and also used the trait, so my User.php looks like:

`<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    
}
`

but still I can not use `assignRole()` method and I get `BadMethodCallException`:
`  [BadMethodCallException]
  Call to undefined method Illuminate\Database\Query\Builder::assignRole()`

I can use `Role::create` and `Permission::create` and it's working just fine, but it seems that I can't access the `HasRoles` trait! so what I have done wrong or what I am missing?

P.S: I am using laravel 5.4.23

Thanks

**Comment by behzadev** [comment]
I needed to `use App\User`, but I was doing `use Illuminate\Foundation\Auth\User`

**Comment by Omazon** [comment]
Hi, could you explain how you solved the problem, I have problem too, thanks

**Comment by Omazon** [comment]
I tried that and it still does not work

**Comment by Omazon** [comment]
I finally managed to make it work, was that you said, problem solved at last.

**Comment by nemo3000** [comment]
I have same proble, what is the solution?

**Comment by drbyte** [comment]
> I have same proble, what is the solution?

Retrieve the User object first (ie: `->first()` or `->get()` since you must have an actual User, not just a Query Builder object designed for retrieving the User.
Or, make sure you're calling the method on an object that has the HasRoles trait loaded on it.
These are in the documentation.
