### ISSUE TITLE
Description for Roles and Permissions

### ISSUE THREAD

**Issue by jaminscript** [spatie/laravel-permission#306]
I am creating an interface that allows people with certain roles / permissions to create new user accounts that also have roles / permissions.

Depending on how complex the name of the role / permission is, the reader of them could be confused.

I've already created my own "description" columns for each role and permission, but do you think this would be appropriate as a default for the `spatie/laravel-permission` project?

**Comment by freekmurze** [comment]
Thanks for you suggestion. I'd like to keep this package a simple as it can be. Like you discovered, a `description` column can easily be added by those who need it.
