### ISSUE TITLE
The given role or permission should use guard `` instead of `web`.

### ISSUE THREAD

**Issue by MrEldin** [spatie/laravel-permission#307]
When I have User model in some different namespace than \App\User assignRole function crush with GuardDoesNotMatch Exception. That is because in my config('auth.providers.users.model) is App\User if you change that in namespace where is you model placed. Everything work fine. But maybe better solution will be to place this in permission.php file.

I mention this just if someone will have the same problem.

**Comment by jefhar** [comment]
I had the same problem. Thanks for your solution.
