### ISSUE TITLE
@role is not accepting an array

### ISSUE THREAD

**Issue by CreativeKoen** [spatie/laravel-permission#309]
He, I'm check on multiple gaurds but is not working. If I just pass through 'admin' it works.

```php
@role('superadmin', 'admin')
# you may edit this stuff
@else # this is error some times
# you may not edit this stuff
@endrole

```
In the readme [here](https://github.com/spatie/laravel-permission#using-blade-directives-with-multiple-guards) it says that it should work. But it does not.

**Comment by drbyte** [comment]
In the example you quoted (and unfortunately also in the readme), technically you're not passing an array. You're actually passing 2 string params as separate arguments to the hasRole() function, which only accepts 1 param. The 2nd param is being ignored. 

Insert the array notation and it should be fine:

```diff
-@role('superadmin', 'admin')
+@role(['superadmin', 'admin'])
```

**Comment by CreativeKoen** [comment]
I have tried it like that, can't access my code right now, but I believe that was not working either. I will give an update when I can access my code.

**Comment by CreativeKoen** [comment]
found a workaround like this
```php
                        @php
                            $admins = array("superadmin", "admin");
                        @endphp
                        @role( $admins )
```

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that fixes this.

**Comment by freekmurze** [comment]
It seems like there already is a test that seems to confirm that 

```php
@role($role, $guard)
    has role for guard
@else
    does not have role for guard
@endrole
```

is working.

Test: https://github.com/spatie/laravel-permission/blob/af3f6b7/tests/BladeTest.php#L90-L95
Blade view: https://github.com/spatie/laravel-permission/blob/1c7964a/tests/resources/views/guardRole.blade.php

If this is still causing problems, please PR a failing test for me to fix.
