### ISSUE TITLE
Exception when assignRole

### ISSUE THREAD

**Issue by mohamedsabil83** [spatie/laravel-permission#312]
When creating a model and  use `$model->assignRole(['role_name'])` it's throw **"The given role or permission should use guard `` instead of `web`."**

I need to use same roles with two tables or at least inherit roles and permission as I have those tables:
**user**->**accounts**->**roles/permission**

user hasMany accounts and every account has many roles and permission by roles.

**Comment by FourStacks** [comment]
@mohamedsabil83 - your use case sounds similar to mine (#310)

If you are adding roles to a model that is not authenticable (e.g. like the default User model) then there are no guards associated with that model.  You'll need to set the role on the account model and explicitly set the guard_name to '' when creating the role and when assigning the role

I don't know the structure of your app but you might want to consider an intermediate model to store the users role for a given account account e.g.

User > hasMany > AccountProfiles (new model) > belongsTo > Account

When you think about it the Account model shouldn't be assigned a Role, the User should.  But as a User can have many Accounts there needs to be some model/s owned by the User that store info associated with that account for the user.

If each Account need to have a unique set of roles then that's a bit of a larger architecture question relating to multi-tenancy but I don't want to assume too much about your app at this stage

**Comment by freekmurze** [comment]
@mohamedsabil83 The solution proposed by @FourStacks seems like the way to go. Reopen if you have further questions.
