### ISSUE TITLE
assignRole doesn't work in RegisterController

### ISSUE THREAD

**Issue by Sjoerrdd** [spatie/laravel-permission#313]
I want to give my users a standard role.
My Registry Controller looks like this

```  $create = User::create([
         'name' => $data['name'],
         'email' => $data['email'],
         'password' => bcrypt($data['password']),
     ]);
			
     $create->assignRole('gebruiker');
     return $create;
```

But I get the error "There is no role named `gebruiker` "

**Comment by freekmurze** [comment]
Seems like your code snippet does not paint the full picture. Where are you checking on a role named `gebruiker`?

**Comment by Sjoerrdd** [comment]
I'm sorry.
I updated the snippet.

**Comment by freekmurze** [comment]
Next question: did you create a role named `gebruiker` in the db?

**Comment by Sjoerrdd** [comment]
Yes, the name and guard_name are "gebruiker".

**Comment by freekmurze** [comment]
Do you have a guard named `gebruiker` in `config/auth.php`?

**Comment by Sjoerrdd** [comment]
Yes, I have.
It looks like this:

```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
			
				'lid' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
```

**Comment by freekmurze** [comment]
is `gebruiker` your default provider?

**Comment by Sjoerrdd** [comment]
Where can I set `gebruiker` as default driver?

**Comment by freekmurze** [comment]
Sorry I meant default guard. You can set that in `config/auth.php`, key: `defaults`

**Comment by Sjoerrdd** [comment]
Yes, I have.

**Comment by Sjoerrdd** [comment]
Solved!
I had a typo overlooked, thanks for the help!

**Comment by xerod** [comment]
@Sjoerrdd i have the same problem, could you tell me how to solve this? i don't understand why this isn't working. I have `use HasRole` on my User model from the beginning but the code still didn't work for me.

**Comment by drbyte** [comment]
@xerod Please create another issue for your situation, and explain exactly what your goal is and what problem you're encountering. Even better, please share your app code too. The more code you share the better.
