### ISSUE TITLE
PermissionDoesNotExist error thrown when trying to seed a role with permissions

### ISSUE THREAD

**Issue by nekromoff** [spatie/laravel-permission#314]
e.g. RoleSeeder has some basic stuff in it:
```
$admin = Role::findByName('admin');
        $admin->givePermissionTo('invoices.reinvoicing');
```
php artisan db:seed --class=RoleSeeder
                                                                       
  [Spatie\Permission\Exceptions\PermissionDoesNotExist]                 
  There is no permission named `invoices.reinvoicing` for guard `web`. 

Only `web` guard is used.

permissions table:
`1	invoices.reinvoicing	web	2017-06-09 01:27:13	2017-06-09 01:27:13`

**Comment by nekromoff** [comment]
I just want to add that clearing cache via artisan does not help at all. Even clearing cache just for this module does not help.

**Comment by francisco-gamonal** [comment]
I have same problem, but searching the method getPermissions in the class Spatie\Permission\PermissionRegistrar:

```sh

public function getPermissions(): Collection
{
    return app(Permission::class)->with('roles')->get(); // <- don't use the cache

    return $this->cache->remember($this->cacheKey, config('permission.cache_expiration_time'), function () {
        return app(Permission::class)->with('roles')->get();
    });
}

```
It works now, but it is a terrible idea to do this.

**Comment by aliworkshop** [comment]
https://github.com/spatie/laravel-permission/issues/231#issuecomment-314103176

**Comment by cbloss** [comment]
We are having the same problem here. Clearing the cache didn't help. 

`foreach ($this->permissions as $p) {
            Permission::firstOrCreate($p);
        }
        $role = Role::firstOrCreate([ 'name' => $this->adminRole ]);
        $permissions = Permission::all()->pluck('name')->toArray();

        $role->givePermissionTo($permissions);`

And it only fails on one that was newly created called admin.oauth. We tried changing the name, but get the same error.

**Comment by cbloss** [comment]
Note: We discovered that if you pass in a collection and not an array of names, it works. So weird.

**Comment by gijsjanr** [comment]
I have the same issue. Seems to be a caching issue. Everything works fine when I set my cache expire time to 0 in the permission config file.

`'cache_expiration_time' => 0,`

**Comment by montyclt** [comment]
It's possible disable cache?

**Comment by gijsjanr** [comment]
@montyclt yes, publish the config file and set "cache_expiration_time" to 0

**Comment by freekmurze** [comment]
The readme of the package now contains [a section on database seeding](https://github.com/spatie/laravel-permission#database-seeding).

**Comment by murtazasultani** [comment]
There is no permission named `Administer roles & permissions` for guard `web`.

**Comment by RoobieBoobieee** [comment]
Same for me. `php artisan cache:clear` didn't work. Removing the cache folder in `storage/framework` did.

**Comment by developermwangimuthui** [comment]
This worked for me 
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();

$role->permissions()->sync($request->input('permission'));
