### ISSUE TITLE
cannot assign roles to users

### ISSUE THREAD

**Issue by romangutkin** [spatie/laravel-permission#317]
hi, im trying to assign a role to a user but im getting this error:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (, App\User, 3))

this is my controller:
$user = new User;
        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->title = $request->title;
        $user->assignRole($request->roles);
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->save();

**Comment by freekmurze** [comment]
Save the user first before assigning roles to it.
