### ISSUE TITLE
Wrong fqn in docblock

### ISSUE THREAD

**Issue by diazemiliano** [spatie/laravel-permission#318]
A small one...
```    /** @var Illuminate\Contracts\Logging\Log */```
instead of
```    /** @var \Illuminate\Contracts\Logging\Log */```

https://github.com/spatie/laravel-permission/blob/master/src/PermissionRegistrar.php#L20

😄

**Comment by freekmurze** [comment]
Could you send a PR to fix this?

**Comment by freekmurze** [comment]
Thanks!

**Comment by diazemiliano** [comment]
Youre welcome. 😄
