### ISSUE TITLE
Question on migrations file.

### ISSUE THREAD

**Issue by diazemiliano** [spatie/laravel-permission#320]
Hi, why you prefer to use a ```.php.stub``` file instead of a standard named migration file i.e. ```2017_06_13_152035_create_permission_tables.php```?

It would be nice if we could auto load the migrations out of the box instead of having to publish them, and optionally add a config option.
``` php
// laravel-permission/src/PermissionServiceProvider.php

if ($this->app->runningInConsole() && config('permission.runsMigrations')) {
    $this->loadMigrationsFrom(__DIR__.'/../database/migrations');
}
```

``` php
// laravel-permission/config/permission.php

/* Run Migrations Automatically */
...
    'runsMigrations' => false;
...
```
Thanks in advance. 😉

**Comment by freekmurze** [comment]
> why you prefer to use a .php.stub file instead of a standard named migration file

I don't have  reason for using `.stub`. When I was creating the package it seems like a nice way to mark the file as a stub.

> It would be nice if we could auto load the migrations out of the box instead of having to publish them, and optionally add a config option.

I'm not a fan our autoloading migrations in this way. The added value of maintaining this custom solution is just to low versus the well known practice of publishing migrations.

**Comment by diazemiliano** [comment]
Ok, Thanks for the reply. 👍
