### ISSUE TITLE
Unable to publish migration and config

### ISSUE THREAD

**Issue by limvus** [spatie/laravel-permission#321]
These command are not working:
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"

However this is working:
php artisan vendor:publish 
But it is publishing other unwanted migrations as well. 

I have cleared the cache and dump the autoload as well. But no luck. 
Did I miss something.

**Comment by diazemiliano** [comment]
Hi @limvus ,
You have to remove the quotes like...
``` bash
php artisan vendor:publish --provider=Spatie\Permission\PermissionServiceProvider --tag=migrations
php artisan vendor:publish --provider=Spatie\Permission\PermissionServiceProvider" --tag=config
```

**Comment by limvus** [comment]
Thanks @diazemiliano 
That solved the issue.
Also, I think the ReadMe section should be updated with correct script - without quotes.

**Comment by freekmurze** [comment]
Could you send a PR to the readme? Thanks!





Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be

**Comment by sl-georgejimenez** [comment]
I tried with no quotes but it is not working for me.
I am using Laravel 5.4.34
When I try php artisan migrate, there is no new migration.

**Comment by JoranSchipper** [comment]
I'm experiencing the same issue on Laravel v5.4.32. Any news on this one?

**Comment by JoranSchipper** [comment]
@sl-georgejimenez You might want to clear your configuration cache before publishing

`php artisan config:clear`

This solved my problem.

**Comment by xadrijo** [comment]
Thanks, @JoranSchipper, that works for me.

**Comment by nscherneck** [comment]
Just want to add that I was having the same issue with publishing the migration, tried to omit the quotes (didn't work), did a `php artisan config:clear`, tried to publish the migration again without quotes (didn't work), tried again with quotes (worked).
