### ISSUE TITLE
syncPermissions 100's of single queries

### ISSUE THREAD

**Issue by madsem** [spatie/laravel-permission#323]
Hey,

first off thanks for this great package, very much appreciated.

Now to my issue, syncPermissions() generates tons of single inserts, would it be possible to make that bulk updates somehow?

I have 13 roles, each role can have 48 permissions, right now when I do a role update (I have all roles and permissions on a single page, for easy checking/unchecking) the query takes almost 1 minute.

Of course I could easily change that and make them have an edit page so I only update one role/permission set at a time, but it still seems slow.

I am doing it like this:

```
public function update(Request $request)
    {
        // loop over roles
        foreach ($request->get('roles') as $id => $permissions) {

            if ($role = Role::findOrFail($id)) {
                // admin role always has all permissions
                if ($role->name === 'superadmin') {
                    $role->syncPermissions(Permission::all());
                    continue;
                }

                $role->syncPermissions($permissions);
            }
        }

        return redirect()->route('roles.index')
                         ->with('message', 'All Permissions Successfully updated.');
    }
```

**Comment by freekmurze** [comment]
Syncing permission can indeed generate quite some queries. I'd accept a fully tests PR that improves this. Closing this for now. If you have any more questions around this feel free to reopen.

**Comment by madsem** [comment]
ok thanks @freekmurze. Wasn't sure if I'm doing it right, still learning. Will try to submit a PR with tests once I learned how to ;)
