### ISSUE TITLE
Error with publish the migration

### ISSUE THREAD

**Issue by cschoeni** [spatie/laravel-permission#324]
This command came for the instruction in spatie/laravel-permission this dont create a file in the migration:
php artisan vendor:publish --provider=Spatie\Permission\PermissionServiceProvider --tag=migrations

This command it works:
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"

Regards
Christoph

**Comment by freekmurze** [comment]
You're right. I've fixed this in the readme.
