### ISSUE TITLE
Assign permission for particular model

### ISSUE THREAD

**Issue by anantaramdas** [spatie/laravel-permission#330]
Is it possible (or if it is not then any chance to have it in future) to assign permissions to particular model i.e. 
`$role->givePermissionTo('edit', Article:class);`?

Thanks!

**Comment by freekmurze** [comment]
Currently this is not supported, and I'm not planning on adding this soon. You can solve this in your own project by adding a table that holds user ids or role ids that can edit your model. You could then use [Laravel's Authorization policies](https://laravel.com/docs/5.4/authorization#writing-policies) to check if a user `can` edit the model.
