### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by kickthemooon** [spatie/laravel-permission#332]
I know its not directly related to this package but I wanted to ask if you have tip on how to generate the ide helper for the methods of this package like "assignRole()" and similar...

I have the laravel ide helper package but not sure how to make it support the traits...

I am open for tips

**Comment by drbyte** [comment]
Mine offers the tips for assignRole() and hasPermissionTo() etc.
Maybe you need to just run `php artisan ide-helper:generate`?

**Comment by freekmurze** [comment]
☝️👍
