### ISSUE TITLE
Does it Automatically Uses the Correct Auth Guard When You Do Something at your Model?

### ISSUE THREAD

**Issue by codeitlikemiley** [spatie/laravel-permission#333]
I Understand that this can be use for Multiple Auth Guard cause the causeBy
is polymorph...

Is there any Extra Instruction if i Have multi auth?

Lets say I Logged in at other guard other than the default users guard...

Will it automatically pick up lets say i use admin guard

Will it automatically pick up the correct Model use in the config/auth.php for the admin providers model

Also if im going to retrive the Activity of the Current User?

is Using Auth::user() will retrive the proper guard?

or i will explicitly use Auth::guard(''admin')->user()

Hope you can answer my question thanks for this repo

**Comment by freekmurze** [comment]
> Is there any Extra Instruction if i Have multi auth?

https://github.com/spatie/laravel-permission#using-multiple-guards

To all other questions, I believe the answer is yes. If you have any problems, with this open up a new issue or PR a failing tests if you think something is off with this package.
