### ISSUE TITLE
Field 'guard_name' doesn't have a default value

### ISSUE THREAD

**Issue by kjdion84** [spatie/laravel-permission#335]
Getting this error simply trying to create a role.

My models:

	namespace App;

	class Role extends \Spatie\Permission\Models\Role
	{
	    protected $fillable = ['name'];
	    protected $hidden = ['guard_name', 'pivot'];
	}

	class Permission extends \Spatie\Permission\Models\Permission
	{
	    protected $hidden = ['guard_name', 'pivot'];
	}

I have updated the permission config to use these models.

My controller methods:

    public function createForm()
    {
        $permissions = Permission::all();

        return view('roles.create', compact('permissions'));
    }

    public function create()
    {
        $this->validate(request(), [
            'name' => 'required|unique:roles',
        ]);

        $role = Role::create(request()->all());
        $role->syncPermissions(request()->input('permissions', []));
        activity()->by(auth()->user())->withProperties($role->fresh('permissions'))->log('Created Role');
        request()->session()->flash('status', 'Role created!');

        return redirect()->route('roles');
    }

And my form:

    <form class="form-horizontal" role="form" method="POST" action="{{ route('roles.create') }}">
        {{ csrf_field() }}

        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            <label for="name" class="col-md-3 control-label">Name</label>
            <div class="col-md-6">
                <input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-3 control-label">Permissions</label>
            <div class="col-md-6">
                @foreach ($permissions as $permission)
                    <div class="checkbox">
                        <label>
                            @php $checked = in_array($permission->name, old('permissions', [])) @endphp
                            <input type="checkbox" name="permissions[]" value="{{ $permission->name }}"{{ $checked ? ' checked' : '' }}> {{ $permission->name }}
                        </label>
                    </div>
                @endforeach
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>

This makes no sense. It should work should it not? Yet I get error:

	SQLSTATE[HY000]: General error: 1364 Field 'guard_name' doesn't have a default value (SQL: insert into `roles` (`name`, `updated_at`, `created_at`) values (Test Role, 2017-06-25 19:03:26, 2017-06-25 19:03:26))

I thought, based on the code, the package sets the guard name automatically?

**Comment by kjdion84** [comment]
Well I figured it out by adding an additional array value to the create() and update() methods, a bit hacky but it works:

`$role = Role::create(array_add(request()->all(), 'guard_name', config('auth.defaults.guard')));`

**Comment by vaughany** [comment]
I am very new to this so this might not be the best solution, but I simply added `nullable` to the field definition within the migration, changing this:

`$table->string('guard_name');`

...to this:

`$table->string('guard_name')->nullable();`

...twice: once for the roles definition, and one for permissions.

**Comment by kjdion84** [comment]
Use the  ->default() method in your migration and set it to the config value I mentioned.

**Comment by massiws** [comment]
Sorry for reopening this issue, but I'm facing the same problem and I'm a bit confused.

Reading the documentation there is no clear explanation on how to configure migrations and/or models for Roles and Permissions, maybe only when `roles` and `permissions` models are extended.
 
Based on the last comment by @kjdion84 I found two solutions:

1. add a default on the `guard_name` field in the migrations:
```php

Schema::create($tableNames['roles'], function (Blueprint $table) use ($teams, $columnNames) {
    // ...
    $table->string('name', 125);
    $table->string('guard_name', 125)->default(config('auth.defaults.guard'));
```

  But this is the same code already present in your [Spatie\Permission\Models\Role](https://github.com/spatie/laravel-permission/blob/main/src/Models/Role.php#LC23).

2. add `guard_name` to `$fillable` property of the model:

```php
    
  use \Spatie\Permission\Models\Permission as BasePermission;

  class Permission extends BasePermission
  {
      protected $fillable = [
          'name',
          'guard_name',
      ];
```

Both these solutions works: are they equivalent or there is a best practice?

**Comment by dvxgit-jsoriano** [comment]
![image](https://github.com/spatie/laravel-permission/assets/39609704/90db775c-525f-49d0-9dc2-cea89461d508)

Why do we need to update this when using MySQL database as the DB connection?

**Comment by drbyte** [comment]
> ![image](https://github.com/spatie/laravel-permission/assets/39609704/90db775c-525f-49d0-9dc2-cea89461d508)
> 
> 
> 
> Why do we need to update this when using MySQL database as the DB connection?

You shouldn't need to. 
It's never intended to be blank. 
If it's blank then your app code that's creating the record isn't specifying the guard. Fix that part of your app instead.

**Comment by dvxgit-jsoriano** [comment]
I followed the example from the installation and basic creation of Role::create(['name'=>'writer']); without specifying the guars_name that's why it is weird it didn't work by following the basic usage from documentation.

But thanks! I got it and fixed that part.

**Comment by drbyte** [comment]
Here's the code for `Role::create()`: 
https://github.com/spatie/laravel-permission/blob/51e3a7552896333ca5afd0ef44e006556cd52a54/src/Models/Role.php#L43-L45
You can see how it automatically does a lookup for the guard_name if one is not provided, and that lookup also does some validity checks etc:
https://github.com/spatie/laravel-permission/blob/51e3a7552896333ca5afd0ef44e006556cd52a54/src/Guard.php#L58-L76
So it should never end up needing to be "nullable", nor specifying a "default" in the migration.
It's possible that the available guards may not be passing the lookup due to misconfiguration. 
Sometimes people have guards configured that they're not using and it's finding those instead. But it still should only fallback to a usable guard.

**Comment by sandy2196** [comment]
I don't understand one thing here. When I try to create a Role or Permission using DatabaseSeeder then, no error. and When I try to create it inside the Controller, it gives an error. Why?
