### ISSUE TITLE
caching not working?

### ISSUE THREAD

**Issue by rdgout** [spatie/laravel-permission#336]
Hi guys,

I noticed that the caching of the permissions doesn't seem to be working.
I'm using the package with an API and I see all roles and permissions are fetched from the database on each request.
Upon doing a test with the debugbar I see the same thing. It always fetches the roles and permissions. Is there something I'm missing or doing wrong?

Using the latest version of the package (2.1.6).

Would be great if someone could tell me why it happens, maybe it's just a case of wrong expectations.

The only thing I'm doing is using a middleware, but I assume it should use the cache the package exposes.

My middleware is below:

```
class PermissionMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     * @param $permission
     * @return mixed
     */
    public function handle($request, Closure $next, $permission)
    {
        if (auth()->guest() || ($request->user() && ! $request->user()->can($permission) && ! $request->user()->admin)) {
            abort(403);
        }

        return $next($request);
    }
}
```

**Comment by rdgout** [comment]
Okay, I just noticed there is a whole new major package. Going to test it there first.

**Comment by AlexVanderbist** [comment]
Hi, the package only caches permissions and roles internally, not their relation to users or queries on the `Permission` or `Role` models directly (e.g. `Permission::all()`).

This means that every time you check if a _user_ has a role or permission a DB query will still be executed.

Hopefully this clears some things up.

**Comment by ctf0** [comment]
@AlexVanderbist actually we only have caching for permissions https://github.com/spatie/laravel-permission/blob/master/src/PermissionRegistrar.php#L63

but yes, caching relations is sadly not available

**Comment by Frondor** [comment]
@AlexVanderbist 
What about conditionally adding support for `$user->roles`, `$role->permissions` relationship caching? This way, if `$config['laravel-permission]['cache_relationships']` is `true` both methods `assignRole` and `givePermissionTo` shall flush that relationship cache (parent model usually). 
I hope I explained myself.

**Comment by ttomdewit** [comment]
I think I agree with @Frondor. Looking at the queries in Laravel Debugbar I _always_ see the the following queries:

```sql
select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` in ('4') and `model_has_roles`.`model_type` = 'App\Models\User'
```

```sql
select `permissions`.*, `model_has_permissions`.`model_id` as `pivot_model_id`, `model_has_permissions`.`permission_id` as `pivot_permission_id` from `permissions` inner join `model_has_permissions` on `permissions`.`id` = `model_has_permissions`.`permission_id` where `model_has_permissions`.`model_id` in ('4') and `model_has_permissions`.`model_type` = 'App\Models\User'
```

I tried adding the following snippet to the `User` class, but that did not work as I'd expected:

```php
/**
 * The relations to eager load on every query.
 *
 * @var array
 */
protected $with = [
    'roles',
    'permissions',
];
```

I'd love to give it a go this weekend and try and get caching integrated (backwards compatible). Would you consider merging such PR?

The way I'd try and implement it is update the `HasRoles` trait and wrap the `roles()` and `permissions()` content in a call to Laravel's caching facade. Given some configuration flag it either caches the results or skips caching (by default, backwards compatibility).

**Comment by drbyte** [comment]
@ttomdewit wrote:
> I'd love to give it a go this weekend and try and get caching integrated (backwards compatible). Would you consider merging such PR?
> 
> The way I'd try and implement it is update the `HasRoles` trait and wrap the `roles()` and `permissions()` content in a call to Laravel's caching facade. Given some configuration flag it either caches the results or skips caching (by default, backwards compatibility).

I'd be interested in seeing what you come up with!

**Comment by ttomdewit** [comment]
@drbyte Thank you for reminding me of this, I haven't actually worked on it (forgot to write it down).

**Comment by Nowi5** [comment]
Do we have now a final solution for this?

**Comment by Nowi5** [comment]
Hi, why is the closed even if there is no solution in place? I ALWAYS have the calls at debugbar:
```select `permissions`.*, `model_has_permissions`.`model_id` as `pivot_model_id`, `model_has_permissions`.`permission_id` as `pivot_permission_id`, `model_has_permissions`.`model_type` as `pivot_model_type` from `permissions` inner join `model_has_permissions` on `permissions`.`id` = `model_has_permissions`.`permission_id` where `model_has_permissions`.`model_id` = '1' and `model_has_permissions`.`model_type` = 'App\Models\User' and `permissions`.`deleted_at` is null`

`select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id`, `model_has_roles`.`model_type` as `pivot_model_type` from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = '1' and `model_has_roles`.`model_type` = 'App\Models\User' and `roles`.`deleted_at` is null
`

**Comment by phoenixg** [comment]
How to cache this SQL triggered by `vendor/spatie/laravel-permission/src/Traits/HasPermissions.php:345`

```sql
select
  `nova_permissions`.*,
  `nova_model_has_permissions`.`model_id` as `pivot_model_id`,
  `nova_model_has_permissions`.`permission_id` as `pivot_permission_id`,
  `nova_model_has_permissions`.`model_type` as `pivot_model_type`
from
  `nova_permissions`
  inner join `nova_model_has_permissions` on `nova_permissions`.`id` = `nova_model_has_permissions`.`permission_id`
where
  `nova_model_has_permissions`.`model_id` = "07166164102339"
  and `nova_model_has_permissions`.`model_type` = "App\Model\NovaUser"
```

**Comment by drbyte** [comment]
@ttomdewit  @rdgout @ctf0 @Nowi5 the https://github.com/GeneaLabs/laravel-model-caching package might work for this, if you also add to your User model(s) the following:
```php
use \GeneaLabs\LaravelModelCaching\Traits\Cachable;
protected $with = ['roles.permissions', 'permissions'];
```
I haven't tested this extensively to be sure no undesired cache results are obtained, but it does appear to reduce the queries because the data is cached.

**Comment by nasirkhan** [comment]
Is there any progress regarding caching the relationships?

**Comment by nezaboravi** [comment]
> @drbyte Thank you for reminding me of this, I haven't actually worked on it (forgot to write it down).

and i suppose 3 years later, you did not work on it? :)

**Comment by ttomdewit** [comment]
> > @drbyte Thank you for reminding me of this, I haven't actually worked on it (forgot to write it down).
> 
> and i suppose 3 years later, you did not work on it? :)

 Sadly no and I don’t plan on it at the moment since time is better spent with my 1 year old now 😅
