### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by akteur13** [spatie/laravel-permission#337]
I have one api for manage the users for all our resources (ala SSO) with Passport installed. I really like this project but I want the roles to be assigned with resources. Something like guards you provide: I want resources "act like namespaces for your permissions and roles". I guess I should extend the models Role and Permission but I don't know how exactly, should I then redefine every method to search roles with another parameter (system id), I am a little bit stuck. Could you provide some hint for such situation?

**Comment by freekmurze** [comment]
I don't know exactly what you're trying to build and I can't give you advice for your specific app, but you can let the package use custom models by specifying their class names in [the config file](https://github.com/spatie/laravel-permission/blob/master/config/permission.php).

**Comment by akteur13** [comment]
I just want to add extra column in roles table (system id) and then have a possibility to create role and then check the user with two parameters 
$role = Role::create(['system_id' => '3', 'name' => 'superadmin']); 
$user->hasRole($roleName, $sysyemId);

**Comment by freekmurze** [comment]
For that to work I don't think it necessary to use custom model. But you'll have to override the `hasRole` method on your user mode and add your own logic to check that `systemId`.
