### ISSUE TITLE
Target [Spatie\Permission\Contracts\Permission] is not instantiable.

### ISSUE THREAD

**Issue by knox2** [spatie/laravel-permission#339]
I get the following error:

`Illuminate\Contracts\Container\BindingResolutionException with message 'Target [Spatie\Permission\Contracts\Permission] is not instantiable.' `

when I try to run

`Permission::create(['name' => 'approve trip']);
`

Though it does end up creating the permission in the DB

and the error

`Illuminate\Contracts\Container\BindingResolutionException with message 'Target [Spatie\Permission\Contracts\Role] is not instantiable.`

when I try to assign a user a role.

`$user->assignRole('admin')
`

**Comment by sehgal10** [comment]
@knox2 What was the issue and the resolution?
I'm facing the same.

Thanks in Advance,
Sukhwinder

**Comment by knox2** [comment]
@sehgal10 Make sure you use the correct namespaces to both Permission and Roles

**Comment by drbyte** [comment]
@sehgal10 make sure when you're calling the models you actually call the models, not their contracts:

Spatie\Permission\Models\Permission
not
Spatie\Permission\Contracts\Permission
