### ISSUE TITLE
Add hasPermission Blade directive

### ISSUE THREAD

**Issue by n1smo** [spatie/laravel-permission#34]
I guess this would be really usefull.

Lets say we have 3 rolls: admin, editiors, and readers.

And we have the permission: create posts. This one is given to admins and editors.

Now i would be able to show the create post button only for admins and editors with something like 

@hasPermission('create posts')

Think that would be really helpful for a future release.

Regards
Michael

**Comment by sebastiandedeyne** [comment]
Laravel already has this built in! The directive is `@can` though, not `@hasPermission`.

More info: https://laravel.com/docs/5.2/authorization#within-blade-templates

**Comment by JiberBoom** [comment]
@can it does't work in laravel5.4 ,why?
