### ISSUE TITLE
ReflectionException: Class App\Http\Middleware\ClearanceMiddleware does not exist

### ISSUE THREAD

**Issue by BAKTETE** [spatie/laravel-permission#343]
this error get displayed from time to time not all time don't know why could you please clarify this 
`ReflectionException: Class App\Http\Middleware\ClearanceMiddleware does not exist in C:\wamp64\www\blog\vendor\laravel\framework\src\Illuminate\Container\Container.php:729`

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;


class ClearanceMiddleware {
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next) {        
        if (Auth::user()->hasPermissionTo('Administer roles & permissions')) //If user has this //permission
        {
            return $next($request);
        }
    }
}
```

**Comment by freekmurze** [comment]
This problem is not related to this package. 

Is the name of your file correct? Try dumping the autoloader.

**Comment by BAKTETE** [comment]
i did the following and it's working

- `composer dump-autoload` to pop up the error 

- renamed the file `clearance` under  `app\Http\Middleware` to ClearanceMiddleware

Sorry for the intrusion i know it's not a package related

by the way thank you so much for this great package really helped me a lot in my project

**Comment by luancmenezes** [comment]
e

**Comment by MichaelMarkos** [comment]
What solved this problem I encountered the same problem

**Comment by VoidZA** [comment]
For me I had to add the middleware to Kernel.php and then it worked.
In:  app/Http/Kernel.php ->
```
protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        ........
        'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,
        **'admin' => \App\Http\Middleware\Admin::class,**
    ];
```

**Comment by rust-x** [comment]
In your file, `app/Http/Kernel.php`  your should have these two following line regarding laravel-permission in the `$routeMiddleware` array

```
// Role & Permission
'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,
'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,
```
