### ISSUE TITLE
@hasanyrole('Admin|Owner') not working

### ISSUE THREAD

**Issue by BAKTETE** [spatie/laravel-permission#345]
I have created those two rules `Admin` and `Owner` when i try to use them both at the same time on blade they don't work if i use only `Admin` it works 
```
@hasanyrole('Admin|Owner')
  <th class="all" width="5%"> Actions </th>
@else
   I have none of these roles...
@endhasanyrole
```

**Comment by freekmurze** [comment]
So you're seeing ` I have none of these roles...` right?

**Comment by coderkk** [comment]
I have composer update my spatie/laravel-permission to 2.2.0. And it working with my application. I also interest what happen with your application.

**Comment by freekmurze** [comment]
@BAKTETE are you using the latest version of the package?

**Comment by BAKTETE** [comment]
I was running composer update everyday but the package ain't updating until last night it's on the latest version and it's working now thank u
