### ISSUE TITLE
found new thing! :) (Just sharing)

### ISSUE THREAD

**Issue by qeifar** [spatie/laravel-permission#346]
We tried and error on syncPermission rather than syncRoles.. and, BOTH wORKs!! :D

**Comment by ctf0** [comment]
`syncPermissions` should be added to the docs

**Comment by freekmurze** [comment]
I'd accept a PR that adds an example of that method to the docs.

**Comment by ctf0** [comment]
@freekmurze can we also add `protected $guard_name = 'web';` to the docs
https://github.com/spatie/laravel-permission/issues/358#issuecomment-315971019

**Comment by freekmurze** [comment]
@ctf0 Sure, send a PR that adds this to the docs.
