### ISSUE TITLE
I want to change validation on Role name . It is limited to 10 characters.

### ISSUE THREAD

**Issue by SamFondler** [spatie/laravel-permission#347]

**Comment by freekmurze** [comment]
You should do that in your own project with the standard validation capibilities of Laravel.

**Comment by SamFondler** [comment]
Hi Sir,
Actually I am very new to Laravel . Can you tell me which file I need to edit to edit validation for Role Model.

**Comment by freekmurze** [comment]
Models are not self validating by default. The most common way would be to validate the http request that will change the Role name.

More on Laravel's validation here: https://laravel.com/docs/5.4/validation

**Comment by SamFondler** [comment]
Thanks Its very helpful.
