### ISSUE TITLE
Versioning migrations

### ISSUE THREAD

**Issue by Frondor** [spatie/laravel-permission#349]
Every time I update laravel-permission its a real pain to deal with migrations. Why are you using stubs instead of real migrations?

If I want to automate the update, I can't because even if I do something like 
```
Artisan::call('vendor:publish', [
	'--provider' => 'Spatie\Permission\PermissionServiceProvider',
	'--tag' => 'migrations',
	'--force' => true]
);
```
It just won't work because it says the class is already in use (by the stub process). If I remove the `--force` flag then it gets published every time, because it uses a timestamp instead of a single date, which should be the real migration's release date.

How can we handle this in a better and easier way?

**Comment by freekmurze** [comment]
We consider modifying the migration file as a breaking change. So inside a major version it won't get modified. If you just publish the migration the first time you install the package, you should be fine.

**Comment by Frondor** [comment]
That means I have to manually uninstall previous migration, delete it and publish the new one every time a major version comes out. That doesn't make any sense to me to be honest.

If you are always using the same file, you should be loading it already from the service provider with `loadMigrationsFrom()` (you can even control it using a config key, so those who for some weird reason have to edit the migration -which in my opinion should never happen, fork this repo instead- can do it) in my opinion. Or just stop calculating the file timestamp at the moment publishing it.

**Comment by freekmurze** [comment]
To me this makes perfect sense. It's kinda best practice to, in your `composer.json` file, to require the package in such a way that you stay in a major version. 

In case we release a new major version (which we don't often do), there will be probably be more breaking changes than just a changed migration.

I'm not really a fan of those automatic publishing of migrations.
