### ISSUE TITLE
Helper function to check if a role name or permission name exist in the table

### ISSUE THREAD

**Issue by razikallayi** [spatie/laravel-permission#35]
Please add a  function to check if a role name or permission name exist in the table before creating a role and permission. Otherwise same entry can exist in role table and permission table.

**Comment by razikallayi** [comment]
Or please let me know if there is any better solution

**Comment by freekmurze** [comment]
I think adding a helper for this in the package would be overkill. You can easily check wether a permission exists in your application logic.

**Comment by razikallayi** [comment]
Ok.Thank you.

And a big thanks for the project.

**Comment by naimurhasan** [comment]
Create the below function
```
function isRoleExist($role_name){
        return Count(Role::findByName($role_name)->get()) > 0;
 }
```

Then use it like
```
if(!isRoleExist('manager'){
       $role = Role::create(['name' => 'Admin']);
}
````

**Comment by saghian** [comment]
Hi developer
how can check role is exist ?

**Comment by realtebo** [comment]
Any news about this?

We too think that is usefull !

**Comment by DanielLlanes** [comment]
@naimurhasan 

¡Esta solución me funciono perfecto, solo lo adapté a mis necesidades gracias!!

**Comment by wahyunurarizky** [comment]
still waiting haha

**Comment by magarciav** [comment]
Crea una función y adicional debes hacer una consulta.

`
function roleExist($role) {
    return \Spatie\Permission\Models\Role::where('name', '=', $role)->count() > 0;
}
`

Despues la puedes usar de esta forma

`
if (roleExist('super-admin') {
       # code...
}
`

**Comment by Kultura100** [comment]
Role it's just a simple model with data. 
So, use it like that.

```
$rolename= "writer";
if(Post::where('name', $rolename)->exists()) // if exists return true
{
 //if exists
} else //if not exists
```
