### ISSUE TITLE
Laravel 5.2 version

### ISSUE THREAD

**Issue by Arkanius** [spatie/laravel-permission#350]
Can I use it with Laravel 5.2 version ? I took a look at v1 branch but it says that was designed to 5.1 version

**Comment by johanleroux** [comment]
Yes you can

Also 

> If you are using a Laravel version lower than 5.2.28, and want a drop-in middleware to check permissions, check out our authorize package.

**Comment by sebastiandedeyne** [comment]
This package is indeed compatible with 5.2. You might get an older version though, but it will work!
