### ISSUE TITLE
Extend \Eloquent instead of Model for PHPSTORM

### ISSUE THREAD

**Issue by kjdion84** [spatie/laravel-permission#351]
This is just a suggestion. Have the classes extend \Eloquent instead of Model so that the Laravel IDE helper for PHPSTORM picks up the methods.

Or create a new config option allowing us to set what we want the classes to extend.

**Comment by sebastiandedeyne** [comment]
I don't see what this has to do with IDE support, PhpStorm is perfectly capable of determining the available methods extending the `Model` class. `Eloquent` is simply an alias for `Model`.
