### ISSUE TITLE
Landlord and Laravel Permission

### ISSUE THREAD

**Issue by S43534** [spatie/laravel-permission#354]
Just putting this here because it took me some time to solve it and I didn't find anything here when I searched for "Landlord" (and vice versa).

If you have any trouble using [Landlord](https://github.com/HipsterJazzbo/Landlord/) and Laravel Permission together:

Short version: `\Illuminate\Database\Eloquent\Model::clearBootedModels();`
Long version: [https://github.com/HipsterJazzbo/Landlord/issues/64#issuecomment-314527967](https://github.com/HipsterJazzbo/Landlord/issues/64#issuecomment-314527967)

Sebastian

**Comment by freekmurze** [comment]
Thanks for adding the problem/solution here.
