### ISSUE TITLE
Getting List of Users By Role or Permission

### ISSUE THREAD

**Issue by abishekrsrikaanth** [spatie/laravel-permission#357]
How do I go about retrieving a list of users by specific roles or specific permissions? Are there shorthand methods to do that?

**Comment by freekmurze** [comment]
All models in this package are just plain Eloquent models, so you can use Laravel's regular query builder methods to query the models in any way you want.

For getting users with a specific role a scope is included in the package.

```php
$users = User::role('writer')->get(); 
```

**Comment by xDestinatioNx** [comment]
I think it would be cool if the package gets an build in scope for `permissions` like the `role` scope

    $users = User::permission('edit-post')->get();

to get each user with a specific permission

**Comment by drbyte** [comment]
@Julian wrote:
> 
> I think it would be cool if the package gets an build in scope for permissions like the role scope
> 
> $users = User::permission('edit-post')->get();
> to get each user with a specific permission
> 


As you say, for roles, a scope is built-in.

For permissions, you could add your own to your User model. 

For v1 of this package something like the following will work.

```php
    /**
     * Scope the user query to certain permissions only.
     *
     * @param string|array|Permission|\Illuminate\Support\Collection $permissions
     *
     * @return bool
     */
    public function scopePermission($query, $permissions)
    {
        if ($permissions instanceof Collection) {
            $permissions = $permissions->toArray();
        }

        if (! is_array($permissions)) {
            $permissions = [$permissions];
        }

        $permissions = array_map(function ($permission) {
            if ($permission instanceof Permission) {
                return $permission;
            }

            return app(Permission::class)->findByName($permission);
        }, $permissions);

        return $query->whereHas('permissions', function ($query) use ($permissions) {
            $query->where(function ($query) use ($permissions) {
                foreach ($permissions as $permission) {
                    $query->orWhere(config('laravel-permission.table_names.permission').'.id', $permission->id);
                }
            });
        });
    }
```
Note: The above doesn't catch the exception if the specified permission doesn't exist.

For v2, you can do similarly by cloning the scopeRole() method from the HasRoles trait and adapting to permissions accordingly.
