### ISSUE TITLE
PermissionAlreadyExists - A `users_manage` permission already exists for guard `web`.  

### ISSUE THREAD

**Issue by connor11528** [spatie/laravel-permission#359]
I reset my database and deleted all the tables. When I rerun the migration with the seeders I get an error that a permission already exists. `php artisan migrate:reset` runs fine but does not fix the error. How can I reseed the database and start fresh? Thank you

```
php artisan migrate --seed
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2017_07_12_145959_create_permission_tables
Migrated:  2017_07_12_145959_create_permission_tables
Migrating: 2017_07_12_230054_create_products_table
Migrated:  2017_07_12_230054_create_products_table
Seeding: PermissionSeed

                                                               
  [Spatie\Permission\Exceptions\PermissionAlreadyExists]       
  A `users_manage` permission already exists for guard `web`.
```

**Comment by belzaaron** [comment]
Try `php artisan migrate:refresh --seed`.
Also ensure in your `PermissionSeed` that you are ONLY defining one instance of `users_manage`.
Let me know how it goes!

**Comment by connor11528** [comment]
Same error with `php artisan migrate:refresh --seed`

My PermissionSeed file looks like this:

```
<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Permission::create(['name' => 'users_manage']);
    }
}
```

If I comment out the Permission::create seed it moves onto the RoleSeed and I get an error: `There is no permission named `users_manage` for guard `web`. `

The RoleSeed looks like this:

```
<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class RoleSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $role = Role::create(['name' => 'administrator']);
        $role->givePermissionTo('users_manage');
    }
}
```

**Comment by connor11528** [comment]
I had to clear the permission cache!

Running:

```
php artisan cache:forget spatie.permission.cache
php artisan cache:clear  
```

Got me going again! Thank you

https://github.com/spatie/laravel-permission/issues/231

**Comment by pablofior** [comment]
Same problem here.
Exact same problem.
Your solution worked, thats great.
Hope the devs find a solution, 'cause its not so cool to clear the cache every :refresh --seed
Anyway, thank you for the fix.

**Comment by st-bobb** [comment]
php artisan cache:forget spatie.role.cache is also needed

**Comment by fede90** [comment]
It didn't worked for me :( 
I created the permissions in the DB, not using seed.

**Comment by oxbadwolf** [comment]
Besides the clearing of the cache and all that, try to check if permissions and roles already exist. This way you can run your seeder as often as you like without errors ... even extend it and rerun it, if you forgot something ;)

```
$a_role = Role::findByName('my_role');
if (!$a_role) {
	$a_role = Role::create(['name' => 'my_role']);
}
```

and

```
try {
	$a_permission = Permission::create(['name' => 'my_permission']);
} catch (Exception $e) {
	$a_permission = 'my_permission';
}
```

and

```
if (!$a_role->hasPermissionTo($a_permission)) {
	$a_role->givePermissionTo($a_permission);
}
```

**Comment by MichaelViturino** [comment]
sudo chmod 777 -R /home/michael/Workspace/fptg-admin/storage/

**Comment by MichaelViturino** [comment]
sudo chmod 777 -R /var/www/html/project/storage/

**Comment by VoroninWD** [comment]
Help for me:

`
sudo php artisan cache:forget spatie.permission.cache && sudo php artisan cache:clear  
`

**Comment by SuperlativeEntity** [comment]
Cache::flush('spatie.permission.cache');
Cache::flush('spatie.role.cache');

**Comment by drbyte** [comment]
Better to use `php artisan permission:cache-reset` as documented 
https://docs.spatie.be/laravel-permission/v3/advanced-usage/cache/

**Comment by nidheesh-eglobeits** [comment]
This worked for me:

```
sudo chmod 777 -R /var/www/project/storage/
php artisan cache:forget spatie.permission.cache
php artisan cache:clear
php artisan db:seed --class=YourSeederClass
```

**Comment by naimurhasan** [comment]
Create the below function
```
function isRoleExist($role_name){
        return Count(Role::findByName($role_name)->get()) > 0;
 }
```

Then use it like
```
if(!isRoleExist('manager'){
       $role = Role::create(['name' => 'Admin']);
}
````

**Comment by mohitvisions1** [comment]
> 
php artisan cache:forget spatie.permission.cache
php artisan cache:clear

**Comment by hendisantika** [comment]
> I had to clear the permission cache!
> 
> Running:
> 
> ```
> php artisan cache:forget spatie.permission.cache
> php artisan cache:clear  
> ```
> 
> Got me going again! Thank you
> 
> #231

It works for me again....

Thanks everyone
