### ISSUE TITLE
forgetCachedPermissions() error 

### ISSUE THREAD

**Issue by widlturk** [spatie/laravel-permission#36]
$role->givePermissionTo('edit');

Call to undefined method Illuminate\Database\Query\Builder::forgetCachedPermissions()  error

HasPermissions.php   file

public function givePermissionTo($permission)
    {
        $this->permissions()->save($this->getStoredPermission($permission));

        $this->forgetCachedPermissions();

        return $this;
    }

It does not have this function forgetCachedPermissions()

**Comment by freekmurze** [comment]
Could you please give a little bit more context on the error you're getting?

Have you add the `Spatie\Permission\Traits\HasRoles`-trait to your model?

**Comment by widlturk** [comment]
HasRoles add model file  yes

I used incorrectly. sorry .
