### ISSUE TITLE
WHITE text laravel and view js

### ISSUE THREAD

**Issue by ibtissambth** [spatie/laravel-permission#360]
hello,i m new in vue js and i want to use it on laravel but when i run the 2 commands(npm install and nmp run dev) the second one doesnt work and the file Example.vue have a white test ( without any color)
please help me
my laravel version 5.4
npm version 3.10.10
node version v6.10.3

**Comment by ibtissambth** [comment]
![whitetext](https://user-images.githubusercontent.com/29801262/28232881-9ab88e9e-68e2-11e7-936a-03aef2c779de.JPG)

**Comment by freekmurze** [comment]
Closing because this issue has nothing to do with this repo.

For general help on Laravel and/or Vue try posting your question on one of these channels:

https://laracasts.com/discuss
https://laravel.io/
https://larachat.co/
