### ISSUE TITLE
Array in @can

### ISSUE THREAD

**Issue by Doublemedia** [spatie/laravel-permission#361]
Hi,

Is there a way for @can like @hasanyrole(['callcenter', 'admin']) ?
I want to check if a user has 1 or more permissions like:
@can(['list companies', 'list users'])

Is there a workaround for this?

Raymond

**Comment by freekmurze** [comment]
Thanks for answering this one @drbyte

**Comment by rkranjith79** [comment]
There is no permission named `permission-name` for guard `web`.

Not Omit wrong permission, Showing Errror

kindly help....

**Comment by philharmonie** [comment]
Would be cool to be able to pass an array to @can

**Comment by drbyte** [comment]
> Would be cool to be able to pass an array to `@can`

That's what `@canAny` is for.
