### ISSUE TITLE
add FK for `model_id`

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-permission#362]
atm the delete cascade if we removed the `permissions` or `roles` model but if we removed the other end model ex.`page, user, etc...` it wont be removed, 
which causes issues if we added an item then removed it cuz now the `model_has_permissions` & `model_has_roles` will already have a `model_id` equal to the newly created model.

a way around to fix this is, inside the controller delete method
```php
DB::table('model_has_roles')->where('model_id', $id)->delete();
DB::table('model_has_permissions')->where('model_id', $id)->delete();
```

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that fixes this.

**Comment by ctf0** [comment]
i can make a PR, bu sadly dont know anything about writing tests 😢

**Comment by freekmurze** [comment]
> but sadly dont know anything about writing tests

Research the subject a bit, your future self will be thankful

Take a look around in the code in the `tests` directory of this package. You can run `vendor/bin/phpunit` to run them.

**Comment by bhill77** [comment]
may I make PR for this? or you will do it @ctf0?

**Comment by ctf0** [comment]
@bhill77 its okay, you can make it 👍

**Comment by bhill77** [comment]
sorry @ctf0, I don't really understand what you mean by deleting model. Do you mean delete model class? or what?

**Comment by ctf0** [comment]
@bhill77  what i meant is if u tried to delete ex.`user` that have a permission or role, the user will be removed but the record in the pivot table will remain which may cuz issues if u tried to add a new user with the same permissions and roles to the db as the pivot records will be already in the table.
