### ISSUE TITLE
@hasanyrole works only with array, not with pipe separated string

### ISSUE THREAD

**Issue by mazedlx** [spatie/laravel-permission#364]
First, thanks for the great package!

Second, I think there's an error in the docs

> `@hasanyrole('writer|admin')`

doesn't work, at least for me (Laravel 5.4, laravel-permission 1.12). I think it should be

`@hasanyrole(['writer', 'admin'])`

I'll gladly create a PR for this if needed.

**Comment by freekmurze** [comment]
I'd accept a fully tested PR that fixes this.

**Comment by mazedlx** [comment]
@freekmurze this should be closed. I had an old version of your package installed, everything works as expected with the current release (2.2.0) Thanks!
