### ISSUE TITLE
Permissions not registered with Laravel gate

### ISSUE THREAD

**Issue by matbeard** [spatie/laravel-permission#366]
I've created a couple of roles, each with a single permission, but they don't appear to be registered with Laravel's gate, or there's some other problem.

If I use the `@can` Blade directive, I don't get an error, but I don't see the output that I should have access to. Same problem if I use `can:admin` in a route group middleware... no errors, but no permission to the routes.

If I try using `@if (auth()->user()->hasAnyPermission(['admin']))` I get a `Trying to get property of non-object` error in HasRoles.php (line 261)

Any ideas?

EDIT: Oops! Clearing the cache with `php artisan cache:forget spatie.permission.cache` seems to have fixed the issue, even though I've not manipulated the database?

The `hasAnyPermission` problem persistes though.

Laravel 5.4
PHP 7.1
Laravel-permission ^2.2

**Comment by cesargb** [comment]
Hi,

Watching the code, the argument of function hasAnyPermission, must be a string, try with:

`@if (auth()->user()->hasAnyPermission('admin'))`

**Comment by kmcluckie** [comment]
I had the `hasAnyPermission` issue to. I looked at the method signature and noticed it uses argument unpacking. So I just removed the array square brackets and it worked:

`auth()->user()->hasAnyPermission('admin')`

If you want to pass an array of permissions:

`auth()->user()->hasAnyPermission(...$permission_array)`

**Comment by freekmurze** [comment]
I've just tagged `v2.3.2` that fixes this bug.
