### ISSUE TITLE
Support for Laravel 5.2

### ISSUE THREAD

**Issue by webpixels** [spatie/laravel-permission#37]
When editing the migration file to add some more columns in the table and try to migrate it it says: "Class CreatePermissionTables" not found. Do you have any hint for that?

**Comment by sebastiandedeyne** [comment]
Could you run `composer dump-autoload` and try again?

**Comment by webpixels** [comment]
Just did it. It worked. Thanks!

**Comment by webpixels** [comment]
Do you know if I could meet any issues with Laravel 5.2. I used another package before I found yours and it wasn't fully updated for 5.2.

**Comment by sebastiandedeyne** [comment]
Did you add the `Spatie\Permission\Traits\HasRoles` trait to your user model?

**Comment by webpixels** [comment]
Yes. I added that. Also in my controller I added 
`
      use Spatie\Permission\Models\Role;
       use Spatie\Permission\Models\Permission;

        $user_id = User::create([
            'first_name' => $request['first_name'],
            'last_name' => $request['last_name'],
            'username' => $request['username'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
            'is_admin' => true,
            'is_public' => true
        ])->id;

        $user = User::find($user_id);

        $user->assignRole('admin');
`

Also, instead of assigning a role by name, I would like to do it by ID. Is it possible?

**Comment by webpixels** [comment]
I solved it.

**Comment by sebastiandedeyne** [comment]
Cool :+1:

**Comment by caleboki** [comment]
Hello @webpixels please could you share how you solved it? As I am having a similar challenge with the role and permission relationship

**Comment by webpixels** [comment]
@caleboki Could you specify the issue exactly? It passed some time since I met that problem and don't remember exactly which was the problem so I can help you.

**Comment by vexsolutions** [comment]
@webpixels would be nice if you included how you "solved" it for those coming to this thread with a similar issue.
