### ISSUE TITLE
Roles being duplicated

### ISSUE THREAD

**Issue by liran-co** [spatie/laravel-permission#370]
I'm not sure if this is intended, but if I do the following:

$role = Role::create(['name' => 'super admin']);
$role = Role::create(['name' => 'superadmin']);
$role = Role::create(['name' => 'super-admin']);

I'll have three separate entries in the roles table. Wouldn't it make sense to strip out characters like dashes for checking to see if a role exists?

**Comment by freekmurze** [comment]
I'd like to keep this package unopinionated on which permission names to allow. If you like to implement some rules around the naming, do it in your own project.
