### ISSUE TITLE
commands are not using the models set in the config

### ISSUE THREAD

**Issue by ronnievisser** [spatie/laravel-permission#374]
I want to overwrite the Role and permission model so I can use a different database connection but the commands don't keep this into account.

is there a reason for this?

**Comment by freekmurze** [comment]
You can manually set the `connection` property on a model to specify which connection to use.

I don't know what how you expect the commands to do this.

**Comment by ronnievisser** [comment]
I believe you haven't actually read the issue...

the commands are not using the models specified in config. i have overriden the config with custom models which extends yours. on my custom model I have set the connection property.

**Comment by freekmurze** [comment]
Ok, got it now. We'll fix this soon.

**Comment by Vimiso** [comment]
I believe the `php artisan permission:show` command has been forgotten about.

**Comment by drbyte** [comment]
@Vimiso Fixed in 3.12.0
