### ISSUE TITLE
Role update permissions not taking effect 

### ISSUE THREAD

**Issue by BAKTETE** [spatie/laravel-permission#378]
whenever i update the role permissions under ubuntu nothing happens the update was successful but it doesn't take any effect (on blade)
in windows environnement all working fine

i was wondering is it a cache problem on ubuntu or something else because i tries `php artisan cache:clear` and nothing happend

**Comment by wasitmirani** [comment]
`$this->authorize('UsersList');`  this method not working on ubuntu
