### ISSUE TITLE
Blade @hasanyrole('writer|admin') wrong result

### ISSUE THREAD

**Issue by UriLucioWald** [spatie/laravel-permission#380]
Hi,
When I am trying the following code with a user having an admin role set
`
@hasanyrole('writer|admin')
  can do it
@else
  can't do it 
@endhasanyrole
`
I get "can't do it" but if I change to
`@hasanyrole('admin')`
I get "can do it"
I expected the same result
The way I solve it for now is passing an array like this
`@hasanyrole(['admin', 'teacher'])`

**Comment by freekmurze** [comment]
The tests seem to indicate that `hasanyrole` is working as intended when you passing it some roles seperated by a `|`.

https://github.com/spatie/laravel-permission/blob/master/tests/BladeTest.php#L145-L152
https://github.com/spatie/laravel-permission/blob/master/tests/resources/views/guardHasAnyRolePipe.blade.php

Could you PR a failing test for me to look at?

**Comment by UriLucioWald** [comment]
Hi,
Thanks for the reply , The test was with user admin (Laravel 5.4)
the following fail
`@hasanyrole('admin|teacher')
success
@else
failed
@endhasanyrole
`
Will output failed
The following
`@hasanyrole('admin')
success
@else
failed
@endhasanyrole
`
Will output success

**Comment by freekmurze** [comment]
Could you add a test to the testsuite of the package to prove that there is indeed a problem?

**Comment by pmestre-pt** [comment]
Hi,
I am exactly with the same problem. When it is added to both roles not applied in the filter. Have you found a solution yet?

Testing in Laravel 5.4

**Comment by pmestre-pt** [comment]
Hi, 
So I checked the problem is that each role is not being validated separately, but rather as a complete string. To solve the problem I added the code on top of the `hasRole` method in the `HasRoles.php` file.
        

        if(stripos($roles, '|') !== false){
            $roles = explode('|', $roles);

            foreach ($roles as $role) {
                if($this->roles->contains('name', $role) !== false) {
                    return true;
                }
            }

            return false;
        }

**Comment by emielmolenaar** [comment]
> Could you add a test to the testsuite of the package to prove that there is indeed a problem?
https://github.com/spatie/laravel-permission/pull/389

> To solve the problem I added the code on top of the hasRole method in the HasRoles.php file.
A bit hacky if you ask me. Be nice and create a PR with a decent fix :wink:

**Comment by freekmurze** [comment]
There seems indeed to be a problem when you use a pipe operator in a blade view. View #389 for more info. I'd highly appreciate a PR that fixes this.

**Comment by freekmurze** [comment]
This is fixed by @drbyte in the latest version of the package.
