### ISSUE TITLE
$exitCode = Artisan::call('cache:forget spatie.permission.cache'); not working

### ISSUE THREAD

**Issue by BAKTETE** [spatie/laravel-permission#381]
Command "`cache:forget spatie.permission.cache`" is not defined.
Did you mean one of these?
```
cache:clear
cache:forget
cache:table
```
when i run `php artisan cache:forget spatie.permission.cache` it works fine 
but using `Artisan::call` it's not working is there any solution for this ?

**Comment by cesargb** [comment]
@BAKTETE try this:

```php
Artisan::call('cache:forget', ['spatie.permission.cache' => true]);
```

**Comment by BAKTETE** [comment]
i'm getting this : 
```
(1/1) InvalidArgumentException
The "spatie.permission.cache" argument does not exist.
```

**Comment by cesargb** [comment]
@BAKTETE Im sorry, when i was answer, i dont testing the code. The problem was that argument name is `key`. Try this: 

```php
Artisan::call('cache:forget', ['key' => 'spatie.permission.cache'])
```

Now, must work fine.

**Comment by BAKTETE** [comment]
@cesargb thank you i appreciate ur help i've tried the documentation but i was unsuccessful it's working now 👍
