### ISSUE TITLE
(Improvement) Wildcard Permission.

### ISSUE THREAD

**Issue by twf-nikhila** [spatie/laravel-permission#382]
What do you think about having a wild card permission, something like:

- If a user/role is assigned star (*) Permission, he will have all permission with him? 
It will be useful for assigning to admin.

Your thoughts? If you find useful I can send a PR.

**Comment by freekmurze** [comment]
You can already give admins all permission by leveraging the `before` method of the `Gate`. You could use that to return `true` for all admins.

More info: https://laravel.com/docs/5.4/authorization

**Comment by benyanke** [comment]
I would also find wildcard permission, but with string checks.

For example, if I have the following permissions:

- sales.emailClient
- sales.emailInternal
- sales.viewClients
- marketing.viewJobs
- marketing.makeAd
- marketing.viewJobs

And the following roles:

- MarketingUser
- SalesUser

I could apply all marketing permissions to a marketing user by running 

```php
$role->givePermissionTo('marketing.*');
```

This would be extremely valuable for my workflow. Any chance this might get added?

**Comment by drbyte** [comment]
To accomplish similarly, in one of my projects I have separate collections for the grouped permissions, and then I just assign (or sync) those collections to the role.
(Using this approach means the "department" prefixes "may" be redundant, depending on the implementation. Of course, the examples given are simple, so prefixes may serve a larger purpose than just visual cues.)

ie: using your example above, would go something like:
```php
$marketingRole->givePermissionTo($marketingPermissions);

$salesRole->givePermissionTo($salesPermissions);

$managerRole->givePermissionTo($marketingPermissions);
$managerRole->givePermissionTo($salesPermissions);

...
```

**Comment by benyanke** [comment]
Not quite as flexible as I'd hoped, but great idea @drbyte - that'll help me move along with this project much quicker! I'll probably be having hundreds of permissions in this app, so this will be a major time saver.

**Comment by drbyte** [comment]
Somewhat related: Awhile back someone posted an alternate middleware to handle some cascading levels, which might also be of interest: https://github.com/spatie/laravel-permission/issues/440

**Comment by drbyte** [comment]
@benyanke Would the permissions wildcard code referenced in #440 do what you were looking for ?
Or were you really more interested in doing Role assignment using wildcard patterns?

**Comment by benyanke** [comment]
Yes, that would cover every use case I am using wildcards for.

Currently I've hacked things into place with a preprocessor which loops though all available permissions and assigns them one at a time, selecting via the wildcard and LDAP group membership. 

Having cascading permissions would allow me to scrap all that.

**Comment by eduardoarandah** [comment]
Hello! 

My middleware lets you organize permissions as you would with a domain. 

The code is simple, about 30 lines:

https://github.com/eduardoarandah/spatie-laravel-permission-permission-middleware/blob/master/PermissionMiddleware.php
