### ISSUE TITLE
Give User Permission or Role

### ISSUE THREAD

**Issue by cschoeni** [spatie/laravel-permission#383]
Hy Guys
With the functions below I get only error messages.

### My Test szenario

This is my Test function.
`php
Route::get('/test', function() {
	$user = User::where('id', 3)->firstOrFail();
	dd($user);
});
`

The Result is as expected

```json
User {#298 ▼
  #fillable: array:14 [▶]
  #hidden: array:2 [▶]
  #connection: "sqlite"
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:16 [▶]
  #original: array:16 [▶]
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #events: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▶]
  #rememberTokenName: "remember_token"
  #accessToken: null
}
```

In my table roles i have 5 posts. 
```php
// Roles
'name' => 'User', 'guard_name' => 'user'
'name' => 'Web', 'guard_name' => 'web'
'name' => 'Workers', 'guard_name' => 'workers'
'name' => 'Moderator', 'guard_name' => 'moderator'

// Permissions
'name' => 'Edit Users', 'guard_name' => 'edit_users'
'name' => 'Show Users', 'guard_name' => 'show_users'
```

### This functions it not works
```php
$user->givePermissionTo('edit articles');
$user->givePermissionTo('edit articles', 'delete articles');

$user->assignRole('writer');
$user->assignRole('writer', 'admin');
```

### 1. Test with function givePermissionTo()
```php
Route::get('/test', function() {
	$user = User::where('id', 3)->firstOrFail();
	$user->givePermissionTo('user');
});
```
The Result is:
**(1/1) PermissionDoesNotExist
There is no permission named `edit_users` for guard `web`.**

### 2. Test with function 
```php
Route::get('/test', function() {
	$user = User::where('id', 3)->firstOrFail();
	$user->assignRole('user');
});

// OR Try with that
Route::get('/test', function() {
	$user = User::where('id', 3)->firstOrFail();
	$user->assignRole('user', 'workers');
});
```

**(1/1) RoleDoesNotExist
There is no role named `user`.**

You see neither the permission as the role function to give rights from User it not works. 
Thanks for show this Error.

**Comment by freekmurze** [comment]
Is `web` your default guard?

What is the contents of the roles and permission tables?

```php
$user->givePermissionTo('edit articles');
$user->givePermissionTo('edit articles', 'delete articles');

$user->assignRole('writer');
$user->assignRole('writer', 'admin');
```

The `guard_name` should be set in those tables. If not, fill it manually and see if that works.

**Comment by abishekrsrikaanth** [comment]
@freekmurze I seem to have the same issue when the role has a guard defined and is different from `web`.

**Comment by freekmurze** [comment]
Could you PR a failing test for me to look at?

**Comment by ctf0** [comment]
@cschoeni why use different guard names ? , why not simply assign roles & perms to users and let the middleware do the rest ?

**Comment by liran-co** [comment]
I'm having the same issue.

**Comment by jurgenbosch** [comment]
Same issue here @freekmurze I'm running on the laravel-55 branch on Laravel 5.5 dev. 
My user model contains the HasRoles trait but it does not work. 

Also the $user->roles property is not working. 
"Property [roles] does not exist on this collection instance."

Web is my default guard and just to be sure I specified it in my User model.

**Comment by freekmurze** [comment]
@jurgenbosch 

> "Method assignRole does not exist."

That's probably not the same issue. If you applied the `HasRoles` trait correctly on your model, you should have the `assignRole` function.

It's clearly defined in the trait: https://github.com/spatie/laravel-permission/blob/laravel-55/src/Traits/HasRoles.php#L93

**Comment by bovisp** [comment]
I'm getting this error as well. I am not using the "out of the box" `User` model, but I have added the `HasRoles` trait and `protected $guard_name = 'web';` property. Like so:

```
namespace App;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasRoles;

    protected $guard_name = 'web';

    ...
}
```

The `guard_name` column in my `roles` table for all of the records has the value of `web`, as it should be.

I am using Laravel 5.5.

**Comment by drbyte** [comment]
1. The scenario posted by @cschoeni is a result of using misspelled permission names against the wrong guard, and mismatched role vs guard names.

2. @abishekrsrikaanth didn't reply with further details. If there is still an issue, please post a new issue with more detail, or preferably a PR with failing tests.

3. @liran-co didn't post any details. If there's actually an issue, please create a new Issue ticket with specific details.

4. The scenario by @jurgenbosch was answered by @freekmurze .

Closing this issue, since it's becoming a catch-all but people aren't posting enough data for help to be offered.

**Comment by ultrasamad** [comment]
@freekmurze I keep hearing people always asking whether the default guard is web. Does it mean it can't work with the api guard, because I'm also facing the issue of no role named `writer` when in actual sense I have one. My guard is api and it's registered in the roles and permissions table columns.

**Comment by drbyte** [comment]
@ultrasamad please open a new issue for your Lumen-specific role issues. It would be helpful if you included code samples, or a link to a github repo where we can look at your code.

**Comment by TitoxDboss** [comment]
Same issue

**Comment by Jado99kc** [comment]
currently at the same problem even though all other methods from spatie work
