### ISSUE TITLE
List all roles?

### ISSUE THREAD

**Issue by MichalKrakow** [spatie/laravel-permission#385]
Am i missing something?
Why there's no mention of this in docs.

The functionality to list roles in order to apply one to the user is something so obvious that i suspect there must be a reason not to provide it.

**Comment by pmestre-pt** [comment]
Hi,
Please check the code below to see if the help.

Get all roles:
`$roles = \Spatie\Permission\Models\Role::all();`

Get all users with relations:
`$users = \App\User::with('roles')->get();`

**Comment by freekmurze** [comment]
Thank for answering this one @pmestre-pt 👍

**Comment by johana57** [comment]
Thanks a lot :dancer:

**Comment by saimzishan** [comment]
use App\Role;


Role::get(),

**Comment by nickforbizz** [comment]
but how can you get all roles for a specific user?

**Comment by nickforbizz** [comment]
> but how can you get all roles for a specific user?

solved `$user->roles;`
