### ISSUE TITLE
Suggestion : Automatically Add permission/role if doesn't exist

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/laravel-permission#387]
Hi,
I wonder if it's a good idea to add a method which allows us adding permission if doesn't exist automatically, something like this :
`$user->hasDirectPermission('perm1'); // this will add 'perm1' if doesn't exist.`

Why this suggestion ? 
As a programmer, I don't want to check whether a permission exists in table or not, just code and assign the permission to user, in execution the permission will be added and the user wont get permission by default, so just go to permissions management space and assign it to user. 

What's your opinion ? ^^'

**Comment by freekmurze** [comment]
I like that this package is kinda strict about it and does not automatically create permissions.
