### ISSUE TITLE
How To Permit to view in specifiq model

### ISSUE THREAD

**Issue by sparkosis** [spatie/laravel-permission#390]
Hello, i have a little question.

Im creating a forum system and i would like to use laravel-permission to allow / disallow spécifique role to look or not look a specific post stored in my posts table does i have to use trait hasrole only in my model ?

**Comment by freekmurze** [comment]
I don't get your question. 

Look in the readme of the package to get some good examples. Reading the Laravel docs on authorization could also be helpful: https://laravel.com/docs/5.4/authorization

Feel free to reopen this issue if you have a more concrete question.
