### ISSUE TITLE
What if my user have string Ids instead of integers?

### ISSUE THREAD

**Issue by GDanielRG** [spatie/laravel-permission#391]
Could there be support to have any other primary key type instead of just integer? if not, I really want to use this package, so can somebody help me or point me what should be modified so I can leverage from this already-awesome package?

**Comment by GDanielRG** [comment]
I got it to work! 
Basically, I changed the:

`$table->morphs('model');`

for:

`$table->string('model_id');`
`$table->string('model_type');`

in both occurrences of the migration.

I also had to add:

`public $incrementing = false;`

to the models using the string ID, so the Id is correctly saved on the 'model_id' columns.

I don't know if this should be added to the package, my guess is that most people go with integer Ids and maybe doing it this way will use a lot of space because of the string columns, but anyways feel free to consider it. I believe it will work with both string and integers.

**Comment by freekmurze** [comment]
Thanks for the suggesion, but going to leave it as it is for now.
