### ISSUE TITLE
Roles for different user groups

### ISSUE THREAD

**Issue by CrixuAMG** [spatie/laravel-permission#394]
In the app I'm working on we have users in different groups. These groups have their own set of permissions and roles.
When I try to create a new group, I call a permissionseeder in which I seed the database with the group ID.
When this process is executing I get a RoleAlreadyExists exception (because the guard name is always the same).
Exception: ` [Spatie\Permission\Exceptions\RoleAlreadyExists]  
  A role 'admin' already exists for guard 'web'.   `
Can this functionality be added?

And what is the use for guard names? And would anything break if we would use a random generated string to fill this value?

**Comment by freekmurze** [comment]
In my mind a role name should remain unique. I don't plan on adding the functionality you described. I'd like to keep this package simple. Maybe it's possible in [Bouncer](https://github.com/JosephSilber/bouncer), check there.

The guard name is used to check if the permission is valid for the currently active guard. I haven't tested it out, but I guess things will break if you fill that up with a random value;

**Comment by twf-nikhila** [comment]
I need a functionality similar to as @CrixuAMG described. Maybe we can add a setting in permissions.php to enable/disable Duplicate role check.

What are your thoughts?

**Comment by drbyte** [comment]
Since `RoleAlreadyExists` extends `InvalidArgumentException`, can't you just add your wanted behaviour in Laravel's (your app's) exception handler?

**Comment by CrixuAMG** [comment]
Which basically means creating a try-catch (like) functionality, which I am not not planning on doing since it just sounds ridiculous.
We solved it back then by adding a `organisation_id` column to the table, which is required for the application we are working on.

Since this is such an integral part of the system (the permissions and roles that are connected to organisations and users) it needs to be streamlined and logical, which would not be achieved by adding error dodging of any kind to it.

Either the package needs to change to allow for this basic functionality, or people need to use the solution we came up with to get around this issue.

**Comment by drbyte** [comment]
> We solved it back then by adding a organisation_id column to the table, which is required for the application we are working on.

So that means you basically adapted things to be multi-tenant (multi-organization), allowing each organization to have its own set of named Roles, right? And thus it won't fire a RoleAlreadyExists because it's unique per organization.  
That feels like the best approach for your application. (Insomuch as the amount of detail you've supplied here so far.)
