### ISSUE TITLE
Dependencies versions

### ISSUE THREAD

**Issue by lucabartoli** [spatie/laravel-permission#398]
Hi all,
Package description says "... for Laravel 5.4 and up".
Unfortunately, packages in composer.json have tilde semver, so composer can't resolve dependencies with laravel 5.5.
Is there another way to make it work? (Aliases?)

**Comment by drbyte** [comment]
I read that the Spatie team are working on upgrading their packages to support Laravel 5.5 ... but some are not ready yet, including this one. 

In the meantime, you could fork it and make your updates, and point your composer.json to your own fork instead.

**Comment by freekmurze** [comment]
Haven't got around creating a L5.5 compatible version yet for this package.

I really want to have #389 solved first, so the blade directives work in both L5.4 and 5.5.

If anybody has some time to fix the issue presented in that PR, I'd be very grateful.

**Comment by freekmurze** [comment]
Now that #389 has been resolved, I've created a branch called `laravel-55`. My intention is to not make breaking changes so that the package stays compatible with L5.4 en L5.5.
