### ISSUE TITLE
Just a suggestion for the Readme - Show Documentation for $user->roles

### ISSUE THREAD

**Issue by bakerstreetsystems** [spatie/laravel-permission#40]
I'm using this packaged and it's **very** helpful, so thank you! It's the right balance of simple, yet fully functional. You've done great work.

I just have a minor suggestion to put on your README:

It doesn't say anywhere that you can directly access the associated roles and permissions for a user. For example, it would be nice for people to know that you can loop through all of a user's roles by doing something like this:

`foreach ($user->roles as $role)
{

}
`

I found this useful while creating an administration page with a list of all the users and their role(s).

**Comment by ghermans** [comment]
:+1:

**Comment by bh-rat** [comment]
Same goes for $role->users.

**Comment by sebastiandedeyne** [comment]
I added a quick mention that the `HasRoles` trait adds standard eloquent relationships.

https://github.com/spatie/laravel-permission/commit/7020a7b403d4acaeaa99bbb3a9aeb559fa4fc2de
