### ISSUE TITLE
Doesn't show role or permissions

### ISSUE THREAD

**Issue by RobinH12** [spatie/laravel-permission#405]
Hello,

I've installed this package and if I try to check the role or permission, then it doesn't give me the role or permission. I've created a role and then I assigned it to a user.

Database tables:
- Roles
- Permissions
- roles_has_permissions
- model_has_permissions
- model_has_roles

Also what do you need to insert at guard?
For the roles table I have:
- id: 1
- name: Admin
- guard_name: 

Hope you can help me. 
(I used the previous package and then it worked for me, but now...)

**Comment by ankurk91** [comment]
If you don't specify any guard then it will default to "web".
```php
Role::create(['name' => 'admin']);
```
Always use provided methods to insert. Don't insert by other means.

Read the [docs](https://github.com/spatie/laravel-permission#using-permissions-and-roles-with-multiple-guards)

**Comment by RobinH12** [comment]
So I can just add the "web" guard for a role? Or can I also add my own guard like Admin and all the admin users are in there?

But if I make a new guard "Admin", then do I need to do something else with it or just add in roles table guard-type: "Admin"?

**Comment by drbyte** [comment]
You should never manually insert ANY records into the roles/permissions table. ALWAYS use the provided methods as documented.

Additionally, the README contains a section which mentions the commands that support custom guards if you need them: https://github.com/spatie/laravel-permission/blob/master/README.md#using-multiple-guards
