### ISSUE TITLE
Get role name from user.

### ISSUE THREAD

**Issue by devgowa** [spatie/laravel-permission#406]
Can you tell me how to get roles name from users model?

Thanks before.

**Comment by sebastiandedeyne** [comment]
You can `pluck` them from the roles.

```php
$user->roles->pluck('name');
```

**Comment by Fatih90** [comment]
@sebastiandedeyne but the result is like this
["admin"]

["writer"]

["vip"]

**Comment by drbyte** [comment]
Since v2.5.1 you can use `$user->getRoleNames()`, which returns a collection of role names associated with that user. 
And then you can access that collection using all the normal collection methods.

**Comment by Fatih90** [comment]
i like this project but i will stay with [laratrust](https://github.com/santigarcor/laratrust)

**Comment by amitprasad2007** [comment]
Can you tell me how to get roles name from  Auth User while loing 

Thanks before.

**Comment by Parterdev** [comment]
Hi guys! 
Another way to render "one" role name in a blade view is:
**Remember that users could have multiple assigned roles.**

@forelse ($user->roles->take(1) as $role)
        <td>{{$role->name}}</td>	
@empty
	<td>Not assigned</td>	
@endforelse
