### ISSUE TITLE
add cache for roles

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-permission#407]
atm we have cache for `app(Permission::class)->with('roles')->get()` but shouldn't we have the inverse as well, from the docs
> Every role is associated with multiple permissions

and 

> $user->getPermissionsViaRoles();

so the normal would be `app(Role::class)->with('permissions')->get()`

**Comment by drbyte** [comment]
Would you submit a fully tested PR for this?

**Comment by ctf0** [comment]
> There might be some guard limitations there.

can u elaborate more ?

**Comment by drbyte** [comment]
My sense is that the implementation of roles+guards could use some expansion. Merely caching the roles->withPermissions relationship won't also cache the associated guards, and the lookups for the role+guard relationships would need some additional helpers.

Feel free to submit a PR with tests.
