### ISSUE TITLE
Class Spatie\Permission\Middlewares\RoleMiddleware does not exist

### ISSUE THREAD

**Issue by bbdangar** [spatie/laravel-permission#408]
I just installed package successfully! Gives exception while using 'middleware' => ['role:admin'],
There is no middleware folder in vendor/spatie/laravel-permission/src/

`
Class Spatie\Permission\Middlewares\RoleMiddleware does not exist
--
in Container.php (line 729)
at ReflectionClass->__construct('Spatie\\Permission\\Middlewares\\RoleMiddleware')in Container.php (line 729)
at Container->build('Spatie\\Permission\\Middlewares\\RoleMiddleware')in Container.php (line 608)
at Container->resolve('Spatie\\Permission\\Middlewares\\RoleMiddleware')in Container.php (line 575)
at Container->make('Spatie\\Permission\\Middlewares\\RoleMiddleware')in Application.php (line 728)
at Application->make('Spatie\\Permission\\Middlewares\\RoleMiddleware')in Pipeline.php (line 138)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)

`

**Comment by cesargb** [comment]
@bbdangar Hi! I suspect that you have the version v1.* of this package. This middleware is supported since version 2.4.

You can run this command to get your current version:

```bash
composer info spatie/laravel-permission
```

The v2 require php 7.x. If you already have php 7, perhaps this issue was in the file `composer.json` of your project.

Edit the `composer.json` and find this part:

```php
        "platform": {
            "php": "5.6.4"
        }
```

If exists, then replace this part:

```php
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "5.6.4"
        }
    }
```

for this other:

```php
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
```

then run this command for upgrade the package at v2:

```bash
composer require spatie/laravel-permission
```

Please, let me known if this resolve this issue. I think that this issue occur when start a new project laravel with command `laravel new ...`

**Comment by bbdangar** [comment]
True, this is the issue of PHP version, thanks @cesargb

**Comment by nille** [comment]
I did this as well but now instead I get this error message when running composer require spatie/laravel-permission:

`Using version ^2.4 for spatie/laravel-permission
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - backpack/permissionmanager 2.1.18 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.9.0, v1.x-dev] but these conflict with your requirements or minimum-stability.
    - backpack/permissionmanager 2.1.18 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.9.0, v1.x-dev] but these conflict with your requirements or minimum-stability.
    - backpack/permissionmanager 2.1.18 requires spatie/laravel-permission ^1.4 -> satisfiable by spatie/laravel-permission[1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.9.0, v1.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for backpack/permissionmanager (locked at 2.1.18, required as ^2.1) -> satisfiable by backpack/permissionmanager[2.1.18].


Installation failed, reverting ./composer.json to its original content.`

**Comment by drbyte** [comment]
@nille Those errors are because of the `backpack/permissionmanager` package's limitations which make it work only with v1.x of this package.

If you want to use the backpack package, you'll need to specify the old 1.x version of spatie/laravel-permission:

`composer require spatie/laravel-permission:^1`

**Comment by mohammedALhakmy** [comment]
@nille this code of error with use splite laravel permission , laravel 10 and site the three class in the kernal.php
but show the error in the open page roles why i don't  know. i am install splite laravel permission 
can help me please

this errors


Target class [Spatie\Permission\Middlewares\PermissionMiddleware] does not exist.

**Comment by jpro123** [comment]
> @nille this code of error with use splite laravel permission , laravel 10 and site the three class in the kernal.php but show the error in the open page roles why i don't know. i am install splite laravel permission can help me please
> 
> this errors
> 
> Target class [Spatie\Permission\Middlewares\PermissionMiddleware] does not exist.




for laravel-permission version 6 

    'role' => \Spatie\Permission\Middleware\RoleMiddleware::class,
        'permission' => \Spatie\Permission\Middleware\PermissionMiddleware::class,
        'role_or_permission' => \Spatie\Permission\Middleware\RoleOrPermissionMiddleware::class,

(s)  is remove this
(\Middlewares\)=>Middleware

**Comment by drbyte** [comment]
Described in https://spatie.be/docs/laravel-permission/v6/upgrading

**Comment by mohammedALhakmy** [comment]
@nille  this code of error with use splite laravel permission , laravel 10 and site the three class in the 
add roles insert show the error why 

There is no permission named `1` for guard `web`.

this is error is show in the function store
can help me 

thank yos so much for you❤️❤️❤️❤️❤️💕

**Comment by drbyte** [comment]
@mohammedALhakmy I've moved your question to a new location: https://github.com/spatie/laravel-permission/discussions/2541

**Comment by sergiolira** [comment]
Hola tnego el mismo error al ejecutar: composer info spatie/laravel/permision me salio esto: 

name     : spatie/laravel-permission
descrip. : Permission handling for Laravel 8.0 and up
keywords : acl, laravel, permission, permissions, rbac, roles, security, spatie
versions : * 6.1.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://github.com/spatie/laravel-permission
source   : [git] https://github.com/spatie/laravel-permission.git 8e584d3ac09856e106f989741a2d82b094278e58
dist     : [zip] https://api.github.com/repos/spatie/laravel-permission/zipball/8e584d3ac09856e106f989741a2d82b094278e58 8e584d3ac09856e106f989741a2d82b094278e58
path     : /home/proyect/public_html/dev.proyect.com/vendor/spatie/laravel-permission
names    : spatie/laravel-permission

support
issues : https://github.com/spatie/laravel-permission/issues
source : https://github.com/spatie/laravel-permission/tree/6.1.0

autoload
files
psr-4
Spatie\Permission\ => src

requires
illuminate/auth ^8.12|^9.0|^10.0
illuminate/container ^8.12|^9.0|^10.0
illuminate/contracts ^8.12|^9.0|^10.0
illuminate/database ^8.12|^9.0|^10.0
php ^8.0

requires (dev)
laravel/passport ^11.0
orchestra/testbench ^6.23|^7.0|^8.0
phpunit/phpunit ^9.4

**Comment by drbyte** [comment]
> name : spatie/laravel-permission
> versions : * 6.1.0

Yes: in version 5 the namespace was "Middlewares", but in version 6 it is "Middleware".

Please read the upgrade documentation!
