### ISSUE TITLE
DB prefix on User model is also added to permissions table

### ISSUE THREAD

**Issue by wfeller** [spatie/laravel-permission#409]
My users model is using a database connection that uses a prefix.

When I (try to) add a role to one of these users :

`\App\User::find(1)->assignRole('admin');`

It fails and I see that the tables (permissions and model_has_permissions) are using the database prefix of the user's database connection (instead of being used without prefixes).

`dd(\Spatie\Permission\Models\Role::all());` works fine when called alone.

I don't think that's the expected behaviour...

**Comment by freekmurze** [comment]
Could you PR a failing test (and a fix 😬) for this?
