### ISSUE TITLE
Global Scope for Models of Various Roles

### ISSUE THREAD

**Issue by bh-rat** [spatie/laravel-permission#41]
I want to make models for various roles that I make. So E.g., I'd be making  a role called admin, and then for the Admin model, so that it'd be really easy to do things like `Admin::all` and so on.

I think that it can be done with [Global Scopes](https://laravel.com/docs/5.2/eloquent#global-scopes).

**Test (THIS WORKS)**
```
$role = Role::where('name', "admin")->first();
User::whereHas('roles', function($query) use ($role){
            $query->where('roles.id', $role->id);
        })->get());
```
But this does not work.

**Admin.php**
```
class Admin extends Model
{
    use HasRoles;

    protected $role = "admin";

    protected $table = "users";

    public static function boot()
    {
        static::addGlobalScope(new AdminScope());
    }
}
```

**AdminScope.php**

```
public function apply(Builder $builder, Model $model)
    {
        $role = Role::where('name', "admin")->first();
        return $builder->whereHas('roles', function($query) use ($role){
            $query->where('roles.id', $role->id);
        });
    }
```

I get 
```
QueryException in Connection.php line 651:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_has_roles.admin_id' in 'where clause' (SQL: select * from `users` where exists (select * from `roles` inner join `user_has_roles` on `roles`.`id` = `user_has_roles`.`role_id` where `user_has_roles`.`admin_id` = `users`.`id` and `roles`.`id` = 2))
```

Let me know if you need any other code. Thanks!

**Comment by sebastiandedeyne** [comment]
Hi, sorry for the late reply.

It's not related to #42, I think it's due to how Laravel determines foreign key names. Since you're probably calling the scope via `User::admin()`, Laravel thinks `admin` is the relationship name, and not `user` (it bases the name on the function you're calling):

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Eloquent/Model.php#L1094-L1105

I'd suggest implementing your own relations, and provide the correct keys so Laravel doesn't try to determine them for you (just overwrite these methods, the rest of the trait should be ok).

```php
/**
 * A user may have multiple roles.
 *
 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
 */
public function roles()
{
    return $this->belongsToMany(
        config('laravel-permission.models.role'),
        config('laravel-permission.table_names.user_has_roles'),
        'user_id',
        'role_id',
        'user'
    );
}
/**
 * A user may have multiple direct permissions.
 *
 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
 */
public function permissions()
{
    return $this->belongsToMany(
        config('laravel-permission.models.permission'),
        config('laravel-permission.table_names.user_has_permissions'),
        'user_id',
        'permission_id',
        'user'
    );
}
```

**Comment by bh-rat** [comment]
Thanks for the solution @sebastiandedeyne . I'll soon try and update here for future reference.

**Comment by alirzayev** [comment]
@bh-rat put it in your User Model.
```
    public function roles()
    {
            return $this->belongsToMany(
                config('permission.models.role'),
                config('permission.table_names.model_has_roles'),
                'model_id',
                'role_id'
            );
    }
```

**Comment by yeftaw** [comment]
Try like this on the AdminScope.php

`public function apply(Builder $builder, Model $model)
{
    // just a single role, you can select multiple roles too by pluck the name
    $role = Role::where('name', "admin")->first()->name;

    $builder->role($role);
}`
