### ISSUE TITLE
Roles/Permissions and record ownership

### ISSUE THREAD

**Issue by ekstro** [spatie/laravel-permission#410]
I know that this library don't support ownership check but I want to make sure there's no other option. I need to use custom gate for this case? How to do it right?

**Comment by BTeodorWork** [comment]
Maybe https://laravel.com/docs/5.4/authorization#creating-policies

**Comment by ekstro** [comment]
I know that but want to know that it is only way to do it:

```
public function view(Request $request)
{
    $this->authorize('view_enquiries'); // from library
    $this->authorize(Enquiry::class); // my policy
}
```

**Comment by drbyte** [comment]
Yes that is probably the most effective approach.
