### ISSUE TITLE
Sync without detaching

### ISSUE THREAD

**Issue by mehrdaad** [spatie/laravel-permission#412]
It would be nice to add functionality to sync permissions and roles without detaching just like Laravel many to many relationship offers.  
You could define method signature like:  

    /**
     * Remove all current roles and set the given ones.
     *
     * @param array $roles
     * @param bool $detaching
     *
     * @return $this
     */
    public function syncRoles($roles,$detaching=false)
    {
    }  

Or you could add another method like ``syncRolesWithoutDetaching``.  
The way I sync roles without detaching is as follows:  

        public function syncRoles(User $user, $roles, $detaching = false): void
     {
        if ($detaching)
        {
            $user->syncRoles($roles);
        }
        else
        {
            if (is_array($roles))
            {
                foreach ($roles as $role)
                {
                    $this->syncRoleWithoutDetaching($user, $role);
                }
            }
            else
            {
                $this->syncRoleWithoutDetaching($user, $roles);
            }
        }
    }

    private function syncRoleWithoutDetaching(User $user, $role): void
    {
        if (!$user->hasRole($role))
        {
            $user->assignRole($role);
        }
    }

Is this a correct way to handle the required logic? Also, is there any performance problems with this code  block?  
Tnx

**Comment by freekmurze** [comment]
The current behaviour of `sycnRoles` is what most users would expect. If you need a `syncRoleWithoutDetaching`, add it to your own project.

**Comment by mehrdaad** [comment]
@freekmurze does the provided snippet suffice?
