### ISSUE TITLE
Duplicate migration file

### ISSUE THREAD

**Issue by xBitsSec** [spatie/laravel-permission#417]
The extension is great and i like it 👍   

I hope, you will change two things:  
 - no dynamic generated filename for the migration file  
- a check in the migration file before the action 'Schema::create' will called with 'Schema::hasTable('xxx'))'  

In my case will this break the migration after an 'php artisan vendor:publish --tag=migrations --force'. And i have something todo manual in the database.

I have done the changes in the package manually, but on a package update will the changes lost and i have to made the changes again, this is not so funny ;)

THX

My problem:
<img width="1276" alt="bildschirmfoto 2017-08-14 um 09 23 42" src="https://user-images.githubusercontent.com/27640321/29261963-9906e8c2-80d2-11e7-9c5b-fb27712cfb31.png">

The migration table hold multiple entries for the same file:
<img width="294" alt="bildschirmfoto 2017-08-14 um 09 27 03" src="https://user-images.githubusercontent.com/27640321/29262076-27a21df4-80d3-11e7-859a-c8badaad3773.png">

I resolved it so as example:
<img width="1417" alt="bildschirmfoto 2017-08-14 um 09 16 57" src="https://user-images.githubusercontent.com/27640321/29261880-2ce4222c-80d2-11e7-8c4f-d170637cc8bc.png">

<img width="951" alt="bildschirmfoto 2017-08-14 um 09 20 13" src="https://user-images.githubusercontent.com/27640321/29261888-3aed6068-80d2-11e7-9a25-65c3415a5792.png">

**Comment by ankurk91** [comment]
I think there should be an upgrade guide; what steps to follow when a developer wants to update this package.

I believe each time we publish migration; will create new migration file but with different time-stamp.

**Comment by freekmurze** [comment]
I'm going to leave this as it is for now. I'm thinking you should never run ` vendor:publish` without using the `--provider` option.

Concerning the upgrade guide, there really are too many steps to follow to type out a whole guide that works for everyone. To upgrade, It's best to remove the previous version, install the new version and migrate the data.
