### ISSUE TITLE
Existence of permissions in development and production

### ISSUE THREAD

**Issue by casperboone** [spatie/laravel-permission#420]
I am considering using this (as always, excellent) package, but there is one thing that hasn't really 'clicked' yet: the existence of permissions in different environments. 

What is your approach on making sure that the permissions you check for in your code actually exist in your production database? I have some ideas on how to do this, but all feel a bit clumsy, so I would love to hear some different approaches on this.

**Comment by drbyte** [comment]
Why would you have different permissions in different environments?

This package throws various exceptions if assignments are attempted on permissions/roles that don't exist: https://github.com/spatie/laravel-permission/tree/master/src/Exceptions 
and returns false when checking for permissions not associated with the model. 

The package expects a relatively tight coupling of code with the permissions which the code creates and supports. 

But from your question it's not really clear what you're asking.

**Comment by faustbrian** [comment]
In most projects you will just have one `PermissionSeeder` that you will run after deploying application and for local development. The package will throw an exception if the permission is missing.

If you want to have a test for that just assert that the permissions the seeder creates are the ones you expect to be created.

**Comment by freekmurze** [comment]
What @faustbrian said. If you try to use a permission that doesn't exist the package will throw a `PermissionDoesNotExist`  exception.  You can catch that exception in Laravel's exception handler to do something custom, like aborting with a 403.
