### ISSUE TITLE
Why laravel 5.4 'composer require' install the lower version of this package?

### ISSUE THREAD

**Issue by Reegan01** [spatie/laravel-permission#421]
Just now I tried to install this package using this comment `composer require spatie/laravel-permission`. This install the lowest version of this package v 1.12.0. I have the fresh laravel project version of 5.4. I can't understand what happen? how I can get the latest update of this package?

**Comment by Reegan01** [comment]
Problem 1
    - spatie/laravel-permission 2.4.2 requires php >=7.0 -> your PHP version (7.1.8) overridden by "config.platform.php" version (5.6.4) does not satisfy that requirement.
    - spatie/laravel-permission 2.4.1 requires php >=7.0 -> your PHP version (7.1.8) overridden by "config.platform.php" version (5.6.4) does not satisfy that requirement.
    - spatie/laravel-permission 2.4.0 requires php >=7.0 -> your PHP version (7.1.8) overridden by "config.platform.php" version (5.6.4) does not satisfy that requirement.
    - Installation request for spatie/laravel-permission ^2.4 -> satisfiable by spatie/laravel-permission[2.4.0, 2.4.1, 2.4.2]

I got this error when I manually add this line `"spatie/laravel-permission": "^2.4"` inside the composer.json file

**Comment by drbyte** [comment]
That's probably because you've got this in your `composer.json`:

```json
        "platform": {
            "php": "5.6.4"
        }
```

**Comment by freekmurze** [comment]
Remove the platform key mentioned by @drbyte and try again.
