### ISSUE TITLE
Question: How to add permissions to all guards?

### ISSUE THREAD

**Issue by edmandiesamonte** [spatie/laravel-permission#422]
Hi,

I have multi-auth on my app and would like to know what's the simplest way to add permissions to all guards without duplicating the permission? Or am I left with adding multiple permission to every guard (i.e. permission for web and permission for api guards)?

Thanks.

**Comment by drbyte** [comment]
Are you talking about 3 permissions? or 3000?
Are you using roles too? or just permissions?

**Comment by edmandiesamonte** [comment]
I have around 105 permissions, and I have 3 different auth guards. In an Internet-of-Things platform, I have the User, the Customer and the Device, all accessing the API endpoint (note: different endpoints for each). The maker which is the User, can give permissions to both Customer and Device which actions can be done by them. I find it messy having 315 permissions in the database. And if we expand, it would be tedious to always create multiple copies of a permission for each auth guard.

**Comment by drbyte** [comment]
If you need to control each combination separately, then you'll need to have copies of each configurable permission on each guard, as you're doing today.

To speed the process, `App\User::getGuardNames()` will give you a Collection of configured guards, which you could loop through when creating new permissions (with some caveats depending on your configuration, model and model property overrides).
