### ISSUE TITLE
Register Blade Extensions in boot() method, not in register()

### ISSUE THREAD

**Issue by m-lotze-7o7** [spatie/laravel-permission#427]
Hi,

please change the ServiceProvider to register the blade extensions in the boot() method, not in register().

https://laravel.com/docs/5.4/blade#extending-blade

The current version does not work with packages like HTMLMin\HTMLMin because of that. When i use both packages, your blade extensions are not registered and output as text, e.g. `@hasanyrole...`

Best regards

**Comment by drbyte** [comment]
This may be a good idea.

@freekmurze was there an intention behind the choice to register the blade extensions in `register` instead of `boot` which fires after all registration/setup is prepped and ready?

**Comment by freekmurze** [comment]
If the tests still pass when the blade extensions are registered in `register`, I'm fine with it.
