### ISSUE TITLE
Struggling with @can

### ISSUE THREAD

**Issue by Failcookie** [spatie/laravel-permission#43]
I have been trying to get @can to work for the past hour.. 

I have a permission setup for the role "President" with the permission "full-access". All have been assigned and my test user has been assigned the role of president.

When I do 

`@can('full-access')`
`<p>See This</p>`
`@endcan`

I can't actually see that. Am I doing something wrong in this setup?

**Comment by freekmurze** [comment]
Are you sure you are logged in with a user that has the President role?

On Wednesday, 10 February 2016, Caleb Smith <notifications@github.com>
wrote:

> I have been trying to get @can <https://github.com/can> to work for the
> past hour..
>
> I have a permission setup for the role "President" with the permission
> "full-access". All have been assigned and my test user has been assigned
> the role of president.
>
> When I do
>
> @can('full-access')
> <p>See This</p>
> @endcan
>
> I can't actually see that. Am I doing something wrong in this setup?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-permission/issues/43>.
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91

**Comment by Failcookie** [comment]
Yes - I had to double check to make sure. This is coming from a fairly fresh install, so I should be good to go... I just can't figure out what I could be missing. Once I assign the permissions to roles in the system, I should be good to go right?

**Comment by Failcookie** [comment]
I can do `@if(count($user->permissions->where('name', 'full-access')) >= 1)` as a work around - so that's good at least! I'll continue to investigate why '@can' is failing and then give it another shot later.
