### ISSUE TITLE
How to change users table to another name while using multiauth ? 

### ISSUE THREAD

**Issue by shankhadevpadam** [spatie/laravel-permission#432]
I have created my project with multiple authorization for users and admin user (users for front page login and admin for backend) so i have created two table for this purpose admins and users, so i need to configure this package with admins table. I  view this issue [https://github.com/spatie/laravel-permission/issues/214](214) but in this ticket the another developer create another migration which is different one from the default one which i have generated through this command
```
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"

```
so how i configure this package with admins table. And i have the custom guard admin also. And how to use @can laravel directive with this new guard.

**Comment by AlexVanderbist** [comment]
Hi! 

Make sure you've got your `User` and `Admin` models set up correctly in your `auth.php` providers. It should look something like this:

```php
 'providers' => [
        'user' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
        'admin' => [
            'driver' => 'eloquent',
            'model' => App\Admin::class,
        ],
    ],
```

After that you can start creating roles and adding permissions as described in the readme. (More specifically here for multi-guard stuff: https://github.com/spatie/laravel-permission#using-multiple-guards).

Finally, if I'm not mistaken, the `@can` directive uses the currently authenticated user. Which in your case is probably based on your `auth` middleware. 

For example if you use `@can('edit_articles')` on a route with middleware `auth:admin`, `@can` will check if the current logged in admin can edit articles.

If you have both an `Admin` and a `User` logged in at the same time on an `auth` route you can use something like `auth('admin')->can('edit_articles')` or `auth('user')->can('edit_articles')`.

Hopefully this helps you to get started! 👍

**Comment by shankhadevpadam** [comment]
i configure mention above but didn't work, so i have configure own my ways like this. In every admin controller.

```
public function __construct()
{
      config()->set('auth.defaults.guard', 'admin');
}
```
Now it's work fine for me.

**Comment by irfan88** [comment]
i have same issue. after follow above not work't for me.  
on debug gate have error 
array:4 [▼
  "ability" => "view_product-list"
  "result" => false
  "user" => 1
  "arguments" => "[]"
]
What i do?
