### ISSUE TITLE
Why PHP-version is not same with Laravel 5.4?

### ISSUE THREAD

**Issue by Anlamas** [spatie/laravel-permission#436]
Hi. I wanna use latest version of your package. But i cant. Why you wrote it supports Laravel 5.4 if yuor package needs PHP >=7.0 when Laravel 5.4 needs PHP >= 5.6.4? Can you help me? Thanks!
P.S. there is some reason why i cant upgrade php

**Comment by sebastiandedeyne** [comment]
Laravel's version constraints don't mean that packages need to follow the same requirements. All of our packages require php 7.0, here's our reasoning on that subject: https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/
