### ISSUE TITLE
migration re-creation on publish

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-permission#437]
is there a reason why using 
https://github.com/spatie/laravel-permission/blob/e36ddb9fa6a68e4da4ce93078256e3dab782bd24/src/PermissionServiceProvider.php#L22

is better than having a single constant date ?

**Comment by freekmurze** [comment]
Not really outside from the fact that you now can easily see when the migration was published.

**Comment by ctf0** [comment]
yes u r correct, but this also duplicate the migration on each publish

**Comment by freekmurze** [comment]
If you dump your autoloader the class will exist and this check will not be `true`.

https://github.com/spatie/laravel-permission/blob/e36ddb9fa6a68e4da4ce93078256e3dab782bd24/src/PermissionServiceProvider.php#L18

**Comment by ctf0** [comment]
i can make a gif to prove that doesnt work if you would like, both this package and https://github.com/spatie/laravel-medialibrary/issues/739

**Comment by ctf0** [comment]
@freekmurze the check depends on `/vendor/composer/autoload_classmap.php` array, correct ?, if yes, the check will always fail because the class is never added.

**Comment by freekmurze** [comment]
After dumping the autoloader it will exist, right?

**Comment by ctf0** [comment]
sadly no 😞
