### ISSUE TITLE
Permission blade not extends user role

### ISSUE THREAD

**Issue by blacktrue** [spatie/laravel-permission#438]
Hi

I'm trying in blade template:

```
@can('ver roles')
...
@endcan
```
The "ver roles" permission is not directly on the user if not on the role, the gate returns false.

<img width="740" alt="captura de pantalla 2017-08-31 a la s 13 58 32" src="https://user-images.githubusercontent.com/15004512/29940354-908b8740-8e54-11e7-9e8e-af13d9ccb9e8.png">

**Comment by freekmurze** [comment]
The tests seem to indicate that this should be working, could you provide a failing test?

Maybe it's cache related at your end. You could try running `php artisan cache:forget spatie.permission.cache` and see if it works after that.

**Comment by drbyte** [comment]
@blacktrue I can't recreate this scenario.

As @freekmurze suggested, perhaps it's a cache issue in your site.

**Comment by freekmurze** [comment]
Closing this for now. Reopen if you're still having troubles.
