### ISSUE TITLE
caching issue

### ISSUE THREAD

**Issue by stephenbennett-uk** [spatie/laravel-permission#439]
I have two sites which are effectively identical. They are both using spatie/laravel-permission with a similar role/permission structure.

The two sites sit within their own hosting accounts under cPanel

Both sites have a 'user' role, one of the permissions is 'create_subscription'. This is one field that can be different on each site (most of the other permissions that 'user' has are identical on both sites).

I've just realised that toggling 'create_subscription' on one site affects the behaviour on both! Both sites have their own completely separate databases. Indeed, the database records are correct.

It appears to be a caching issue. One site change is having an effect on the cache of both sites.

I've now been able to prove that this is the case. Originally, both sites were using the servers memcached facility (as enabled through the config/cache.php file.

I changed both sites over to redis - the problem persisted.

I now have one site using redis, the other using memcached (not exactly ideal!) but it has at least resolved the issue!

Any idea to the solution?

**Comment by drbyte** [comment]
You said they're both on the same server, correct?

It's probably appropriate to give each site its own unique cache `prefix` in `/config/cache.php` ... the default prefix is "laravel", but that doesn't differentiate between apps. Always prudent to customize this for each site.

**Comment by stephenbennett-uk** [comment]
Ah! Thank-you so much :)

I was starting to come to the conclusion it must be something like that and was wondering how that might be configured. I'm a bit of a caching novice. So thank-you very much for this. The problem is solved!
