### ISSUE TITLE
how to use middleware role in route?

### ISSUE THREAD

**Issue by acitjazz** [spatie/laravel-permission#44]
can i use role in route?
i try to use 
`Route::group(['middleware' => 'role:admin'], function () {
  Route::get('/admin', 'adminController@view');
});
`

but im gettin error

Class hasRole does not exist

**Comment by freekmurze** [comment]
This package does not provide a middleware to check roles.

[Our authorization package](https://github.com/spatie/laravel-authorize) provides a middleware to check permissions.
