### ISSUE TITLE
I wrote an improved version of PermissionMiddleware with hierarchical capabilities

### ISSUE THREAD

**Issue by eduardoarandah** [spatie/laravel-permission#440]
I wrote an improved version of PermissionMiddleware with hierarchical capabilities, might be of your interest

TLDR; checks permissions in a hierarchical structure, this permission **admin.auth.user.modify.create** will check:

- admin
- admin.auth
- admin.auth.user
- admin.auth.user.modify
- admin.auth.user.modify.create

[https://github.com/eduardoarandah/spatie-laravel-permission-permission-middleware](https://github.com/eduardoarandah/spatie-laravel-permission-permission-middleware)

**Comment by freekmurze** [comment]
Kinda interesting, but holding off on this for now.
