### ISSUE TITLE
sync events

### ISSUE THREAD

**Issue by kjdion84** [spatie/laravel-permission#445]
I'm currently using your package for some scaffolding I created: https://github.com/kjdion84/owl

I am using a trait in order to stop model events if `config('owl.demo')` is set to `true`. See https://github.com/kjdion84/owl/blob/master/app/Traits/Owl.php for the code.

The problem is that this does not appear to be working for the `sync*` methods in your package. Even if  `config('owl.demo')` is set to `true` it is still completing the syncs.

How do I handle these events so that I can stop them in demo mode? I've already tried using event handlers on the `Pivot` class, which had no effect.

Also a postcard for Toronto is on its way :)

**Comment by freekmurze** [comment]
I don't think you can stop those by leveraging events. Put the calls to the sync methods inside a  `if config('owl.demo') { ... }` block.
