### ISSUE TITLE
Fetch all users that have a permission

### ISSUE THREAD

**Issue by amirshawn** [spatie/laravel-permission#446]
Hi,

I'm wondering if there's anything built in to fetch all users that have a permission or role. I added this code  to my  User model to make it work but  I feel like there's a better way.
`   public static function havePermissionTo($permission) {
        $permission = Permission::whereName($permission)->with('roles', 'roles.users', 'users')->first();
        $users = collect();
        foreach ($permission->roles as $role) {
            foreach($role->users as $user){
                $users->push($user);
            }
        }
        foreach ($permission->users as $user){
            $users->push($user);
        }
        return $users->unique('id');
    }`

**Comment by drbyte** [comment]
What's your use-case for this?  ie: "why?"

**Comment by amirshawn** [comment]
Hi @drbyte 
I have a review form and when it's submitted I'm sending an email to all the admins who have permission to review  it.   It would be nice if we could do something like this:
`$permission = Permission::withName('approve_reviews`)->first();
return $permission->users;`
and have that return all users who either have direct permission or pemission through roles.
 BTW, I've been a long time Zen Cart user  and it's exciting to see you involved  in the Laravel community!

**Comment by drbyte** [comment]
That makes sense. I see your point. 

The changes in closed PR #426 could be used to lookup (only) "direct" permissions.
Or, you could write a custom lookup.  

I'm working on something to expand #426 a bit in hopes of it accommodating what you're after. Working on getting the tests to pass properly first though :|

The quickest solution, although it might not fit your current approach to Roles and Permissions is to just create and assign a specific Role, and use `App\User::role('Approve Reviews')->get()`

**Comment by inet123** [comment]
Just opened a PR #454 to deals with this

**Comment by amirshawn** [comment]
Thank you, I  really appreciate it :)  I'm camping for the weekend but when I get home I'll try it out.  Have a great weekend!

**Comment by freekmurze** [comment]
We'll handle this further in #454
