### ISSUE TITLE
List all permissions

### ISSUE THREAD

**Issue by hakimihamdan88** [spatie/laravel-permission#448]
How do I get all permission based on roles?

```
foreach (Role::all() as $role) {
$role->getAllPermissions();
}
```

**Comment by drbyte** [comment]
Your question is unclear. 
Please explain "why" you want this. 

You can list all roles with `Role:all()` and you can list all permissions with `Permission:all()`
You can list all permissions assigned to a role with `$permission->roles` and all roles assigned to permissions with `$role->permissions`.
You can list all permissions assigned to all users using `App\User::with('roles')->get()`
Some of these are listed in the README.

It would help to know the "why" behind your question.

**Comment by holymp2006** [comment]
I have a route to show all permissions assigned to a role. I'm currently getting the role by name. I want to get the permissions assigned to that role.

```
public function show(Role $role, $role_name)
    {
        try {
            if ($role = $role->findByName($role_name)) {
                $permissions = $role->getAllPermissions(); #trying to get permissions here
                
                return $this->response->array(compact('role', 'permissions'));
            }
        } catch (Exception $e) {
            throw new NotFoundHttpException('Role not found');
        }
    }
```
this currently doesn't work.

**Comment by Aniket-IN** [comment]
Hi, I also have a similer question.

How can I fetch all the permissions that a role have?
