### ISSUE TITLE
Use id instead of name

### ISSUE THREAD

**Issue by hakimihamdan88** [spatie/laravel-permission#450]
Can give permission using id?

```
$role->givePermissionTo(1);
$role->givePermissionTo([1, 2, 3]);
```

**Comment by VictorAvelar** [comment]
I will say that is not convenient, how are you supposed to remember after a while the ids of all your permissions? Would that represent an extra query each time you like to give someone a new permission?

If you use semantic and convenient names as suggested in the README file it is pretty easy to keep things going, but hey that is just me.

If all my assumptions are wrong please provide some insights into your specific use case.

Regards.

**Comment by drbyte** [comment]
This package doesn't support giving permissions by `id` number. 
You can pass permission `name`, an `array of names`, a `collection of names`, or a `Permission object` or a `collection of Permission objects`.

**Comment by benyanke** [comment]
@VictorAvelar : I believe he is talking about the User ID, not the permission ID.

To the potential implementer of this feature:

I'd also note that please be aware not every laravel app uses the default ID column, so please be aware it may be a string, or in my case, a GUID.

**Comment by drbyte** [comment]
Update: back in February 2018, v2.9.1 was released to allow the ability to pass (integer) model `id`s to `givePermissionTo()` and `hasPermissionTo()`, which I believe is what @hakimihamdan88 was looking for.

The code tests for `is_int()` to perform this, so will not work by passing something like a UUID which typically contains hyphens.

**Comment by benyanke** [comment]
While my guids are stored without hyphens, just as pure he, you are correct that this would still break.

Feature request: a method for allowing alternate datatype keys

**Comment by Shadowsm29** [comment]
This would be really useful in case, when you use Laravel as API and you get the IDs from the front end. In my implementation all dropdowns on the front end send array of IDs of selected items, which are UUIDs, so not integers. I guess there is no other way, then fetch the items from the DB before syncing.
