### ISSUE TITLE
blade not working

### ISSUE THREAD

**Issue by BAKTETE** [spatie/laravel-permission#456]
Problem on rendering
![scrrenshot](https://user-images.githubusercontent.com/27772375/30242553-4ae9a0f8-9590-11e7-9277-770b4faeb0a6.png)

**Comment by freekmurze** [comment]
This screenshot provides almost no information on your problem and expected output.  

The tests of this package seem to indicate that the Blade directives are working as intended. 

Please make sure that you installed the package correctly.

**Comment by BAKTETE** [comment]
i had no problem on laravel 5.4
i upgraded my app to  5.5 now the blade directive is not working
