### ISSUE TITLE
Blade extensions are not registered and output as text in boot

### ISSUE THREAD

**Issue by BAKTETE** [spatie/laravel-permission#458]
register the blade directives in the boot method of the service provider output as text
when using :
@ROLE('Admin')
@endrole
it's not working
![scrrenshot](https://user-images.githubusercontent.com/27772375/30242875-00fcf9d4-9597-11e7-9b29-1de11cea5f4c.png)

but when using
@can('')
@endcan
it works

**Comment by BAKTETE** [comment]
i managed to solve the problem
in `PermissionServiceProvider.php`
i found that the `public function register()` is not returning `$this->registerBladeExtensions()`;
```
public function register()
    {
        $this->mergeConfigFrom(
            __DIR__.'/../config/permission.php',
            'permission'
        );
        
    }
```
Could you please confirm this

**Comment by mostafamaklad** [comment]
@BAKTETE 
`$this->registerBladeExtensions();` now in the boot

**Comment by BAKTETE** [comment]
@mostafamaklad 
but it's not rendrenig the blade of @role('') @endrole

**Comment by mostafamaklad** [comment]
@BAKTETE it is working in the test cases could you check the composer update

**Comment by BAKTETE** [comment]
i did but still didn't work 
i've tried to return `$this->registerBladeExtensions();` inside `public function register()` and it worked

**Comment by drbyte** [comment]
All the tests are passing.
The package is working fine on several sites I've witnessed.

Perhaps the problem is a result of a conflict with other packages you are using or other boot directives? What are all the packages in your composer.json?

**Comment by freekmurze** [comment]
Just to be on the save side i've just tagged `v2.5.4` which moves the registration of the blade directives back to the `register` method. Does that solve your problem?

**Comment by BAKTETE** [comment]
@drbyte 
this is my `composer.json` of `laravel 5.5`
```
"require": {
        "php": ">=7.0.0",
        "albertcht/invisible-recaptcha": "^1.6",
        "fideloper/proxy": "~3.3",
        "intervention/image": "^2.4",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.5",
        "laravelista/ekko": "^1.3",
        "spatie/laravel-permission": "^2.5"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },
```
@freekmurze 
yes that change solved my problem

**Comment by drbyte** [comment]
Using v2.5.3 of this package, blade directives are properly registered and function correctly when located in the `boot` method.

Here's a demo app to specifically demonstrate this point:
https://github.com/drbyte/spatie-permissions-demo

I suspect something else in your app is creating conflicts.

Here's the output:
<img width="324" alt="screen shot 2017-09-10 at 3 45 00 pm" src="https://user-images.githubusercontent.com/404472/30252356-0a24dbf0-963f-11e7-809b-ae2d706ae77c.png">

Here's the view code:
<img width="435" alt="screen shot 2017-09-10 at 3 47 03 pm" src="https://user-images.githubusercontent.com/404472/30252378-584548ba-963f-11e7-9b50-9a5b2510abe6.png">

**Comment by BAKTETE** [comment]
i guess i found what's causing the conflict a package called `albertcht/invisible-recaptcha`
in `InvisibleReCaptchaServiceProvider.php` i removed the following 
```
public function boot()
    {
        $this->bootConfig();
        $this->app['validator']->extend('captcha', function ($attribute, $value) {
            return $this->app['captcha']->verifyResponse($value, $this->app['request']->getClientIp());
        });
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('captcha', function ($app) {
            return new InvisibleReCaptcha(
                $app['config']['captcha.siteKey'],
                $app['config']['captcha.secretKey'],
                $app['config']['captcha.hideBadge'],
                $app['config']['captcha.dataBadge'],
                $app['config']['captcha.debug']
            );
        });

        $this->app->resolving('view', function () {
            $this->addBladeDirective($this->app['blade.compiler']);
        });
    }

```
after that blade directives are properly registered and function correctly when located in the `boot `method
so my question is should i notify the owner of this package `albertcht/invisible-recaptcha` about that conflict he is causing

**Comment by drbyte** [comment]
Can you try a test? 
In that package's `register()` method:

```diff
-        $this->app->resolving('view', function () {
+        $this->app->resolving('blade.compiler', function () {
```

https://github.com/LaravelCollective/html/issues/330

**Comment by BAKTETE** [comment]
@drbyte 
after making the changes you have mentioned blade directives are properly registered and function correctly when located in the `boot ` method.

**Comment by drbyte** [comment]
Great! Probably a good idea to make the suggestion to them over there.
