### ISSUE TITLE
Edit/update to role or permission name

### ISSUE THREAD

**Issue by wapshekhar** [spatie/laravel-permission#459]
What if we change a permission or role name after it to assign to a user 
.
user get error.....

**Comment by freekmurze** [comment]
How can we reproduce your issue?

**Comment by drbyte** [comment]
This package does not offer a "rename" command. Therefore, if you're renaming a role or permission, that means you've been editing the database contents directly. If you're going to do direct edits to database data, then you'll also need to manually clear the cache as described in the README.
