### ISSUE TITLE
spatie permission & authorize

### ISSUE THREAD

**Issue by cschoeni** [spatie/laravel-permission#46]
If I spatie / laravel-permission and spatie / laravel-authorize install, I can not authorize use.

I get an error message in route.php. The normal Routes will no longer work. What am I doing wrong?

**Comment by freekmurze** [comment]
This is too little information to determine what's going one. What is the error? Please go over the installation instructions in detail. Probably you've missed a small step.

Try installing the package one by one and determine when the error does occur.
