### ISSUE TITLE
Can't get all users with same role

### ISSUE THREAD

**Issue by Ravensborn** [spatie/laravel-permission#460]
have one user with 'administrator' role created using [https://github.com/LaravelDaily/laravel-roles-permissions-manager](url)
this is what i used:

    public function test() {

       return  $users = User::role('administrator')->get();

    }

returns this error
Non-static method App\User::role() should not be called statically

**Comment by drbyte** [comment]
That's a bug in that Manager application. They've overridden the spatie `role` relationship with their own:

https://github.com/LaravelDaily/laravel-roles-permissions-manager/blob/master/app/User.php#L37

**Comment by Ravensborn** [comment]
@drbyte is there any kind of solution?

**Comment by drbyte** [comment]
I suppose you could create your own additional scope on your `User` model, which essentially defers to the actual real scope:

```php
    /**
     * defer to the Spatie package for role scope
     */
    public function scopeHasRoles(\Illuminate\Database\Eloquent\Builder $query, $roles)
    {
        return $this->scopeRole($query, $roles);
    }
```

And then use the new scope like: `User::hasRoles('administrator')->get()`
