### ISSUE TITLE
Collection of Permissions for a selected Role

### ISSUE THREAD

**Issue by tysonlist** [spatie/laravel-permission#461]
I don't see a way to return a collection of permissions for a selected role. Am I missing something or is this not possible?

**Comment by drbyte** [comment]
`Role::findByName('role_name_here')->permissions` will return a collection of permissions associated with that role.

**Comment by tysonlist** [comment]
Awesome! Did i just miss it or is this in the documentation?

**Comment by drbyte** [comment]
Nah, I don't see it in the documentation.  It's fairly clear in the code though.

**Comment by tysonlist** [comment]
Thanks
