### ISSUE TITLE
User permission overwrite role permission

### ISSUE THREAD

**Issue by ruverd** [spatie/laravel-permission#464]
Hi how can I make an user permission overwrite a role permission.
For example, if I have a role ADM and this role has the permission to delete users, but one user that belongs to ADM role doesn't has permission to delete users.
I've tried revoke the user's permission but this is a role permission so if I revoke the role permission the others users wouldn't delete too.
Please how do that?

**Comment by drbyte** [comment]
This package supports "additive" permissions only. 
It doesn't have features to "take away permissions already-granted by roles".

One workaround would be to create two separate roles: one with, and one without, the delete permission you're trying to control.

**Comment by ruverd** [comment]
I have more than 30 pages where this could happen so it is really hard to create N roles.
Do you know another packed where can I do that?

**Comment by drbyte** [comment]
I suppose the `ultraware/roles` package (which also adds a numeric 'level') might help you consider an alternate structure for your roles and permissions.
