### ISSUE TITLE
user_has_roles & user_has_permissions

### ISSUE THREAD

**Issue by scottjo** [spatie/laravel-permission#465]
Hi

Am I being dense and missing something? When I run the migrations I seem to be missing the user_has_roles and user_has_permissions table that is mentioned in a number of tutorials. Please set me straight!

Thanks in advance

Jon

**Comment by AlexVanderbist** [comment]
Hi,

The `user_has_roles` and `user_has_permissions` tables were used in v1 of the package. They've been replaced by `model_has_permissions` and `model_has_roles` to support permissions for multiple guards.

Hopefully this clears some things up! Let me know if you need any more help :)

**Comment by ttjordan81** [comment]
Hi, 

Thanks for the explanations. We're upgrading our app and packages and we want to keep the naming convention somewhat the same, especially with database names as they're linked to other sources. I've tried renaming the table names inside migration file that was created, however, I'm seeing an error. " ErrorException  : Undefined index: user_has_permissions". 

I know renaming this goes against the logic/wisdom for the v2 updates, but we wanted to see if there is a simpler way for those wanting to migrate. 

So my question: Is there a way to rename the table from model_has_roles and model_has_premission back to ser_has_roles and user_has_permissions?

Thanks,

Tim

**Comment by drbyte** [comment]
@ttjordan81 You may find the guides/comments listed in this discussion to be beneficial if you're wanting to upgrade from v1 to v2:
https://github.com/spatie/laravel-permission/issues/771#issuecomment-443470948
