### ISSUE TITLE
@role and @hasrole blade directives suddenly stopped working.

### ISSUE THREAD

**Issue by PilloryBarnDesign** [spatie/laravel-permission#467]
I'm currently using PHP 7.1.6, Laravel 5.5.8 with Laravel-Permission version 2.6.0. Suddenly my blade directives for roles fail to work, however using `@can` to check if someone has a permission to do something works totally fine.

I have tried rolling back to different versions of the package and seemingly the issue remains, however I know that this did work when I originally installed it (the day Laravel 5.5 was released).

I've checked the case I wrote the name of the role in and everything is correct.

I've tried totally uninstalling the package, clearing all caches etc and re installing and the issue remains

Any help on this is greatly appreciated, only issue I've got :)

**Comment by drbyte** [comment]
Please list all the packages you've added in `composer.json`

Which packages have you added recently? It's likely that one of them is interfering.

**Comment by PilloryBarnDesign** [comment]
These are my packages.

All have been installed since the day 5.5 was released as that's when I started this app, the only one that wasn't was Ramsey's UUID which I've just this minute installed.

```
"require": {
    "php": ">=5.6.4",
    "lab404/laravel-impersonate": "^1.2",
    "laravel/framework": "5.5.*",
    "laravel/tinker": "~1.0",
    "ramsey/uuid": "^3.7",
    "spatie/laravel-permission": "^2.6",
    "uxweb/sweet-alert": "^1.4"
},
"require-dev": {
    "fzaninotto/faker": "~1.4",
    "laravel/dusk": "^2.0",
    "mockery/mockery": "0.9.*",
    "phpunit/phpunit": "~6.0"
},
````

**Comment by drbyte** [comment]
I wonder if it's caused by the impersonate package.  
You can test this by making their service provider not load (lots of ways to do that: most common is to simply uninstall the package, and remove code that invokes it)
Or you could apply the proposed fix posted here: https://github.com/404labfr/laravel-impersonate/pull/25/files

**Comment by PilloryBarnDesign** [comment]
@drbyte Interesting, I'll take a look. Thank you :)

**Comment by PilloryBarnDesign** [comment]
@drbyte tried the fix but no luck (assuming I did it correctly). Still have the same issues

**Comment by drbyte** [comment]
Puzzling.

**Comment by drbyte** [comment]
Package history: 
- v2.5.3 moved blade registration into the ServiceProvider `boot` method, per Laravel Docs
- v2.5.4 returned it back to the `register` method (where it was in v2.5.2 and earlier)

You said earlier that you
> tried rolling back to different versions of the package

I apologize if the following is a repeat of what you tried when "rolling back". I'm posting it here for two purposes:  1) to ask you to confirm that this is what you tried, and 2) to aid others in the future who might follow this discussion.

To test using the package with the Blade directive registration relocated to `boot`, change the line in `composer.json` to:

`    "spatie/laravel-permission": "2.5.3",`

then run `composer update`

Does the problem persist?

**Comment by PilloryBarnDesign** [comment]
@drbyte doing that and changing the @role to @hasrole in my layout has worked. I also tried setting it back to 2.6.0 and that's worked too

**Comment by PilloryBarnDesign** [comment]
Okay weirdly switching it back to @role is working now too 🤔 Laravel just updated to 5.5.9 as well

**Comment by PilloryBarnDesign** [comment]
And now the whole thing is back working again, even with rolling the impersonate package back to what it was. Madness. Thanks for your help!

**Comment by drbyte** [comment]
Puzzling for sure!

Thanks for posting back with the update.
