### ISSUE TITLE
Error when rename "roles" table and "role_id" column

### ISSUE THREAD

**Issue by vmartins** [spatie/laravel-permission#468]
I renamed the table "roles" to "groups" (in `config/permission.php`) and all references in the migration file (`role_id` to `group_id`). So, when run:

```
$user = \Auth::user();
$roles = $user->getRoleNames();
```
Throw QueryException:
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'model_has_roles.role_id' in 'field list'

Possible solution:

https://github.com/spatie/laravel-permission/blob/bf7bdc0ba53ab334c7c9ae20ac08b51df9afe3bd/src/Traits/HasRoles.php#L33

To:
```
str_singular(config('permission.table_names.roles')) . '_id'
```

**Comment by drbyte** [comment]
A quick way to handle this in your own code is to override the trait method by redefining the method in your model: 
- copy the method code into your model: https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L23-L35
- adjust as necessary, such as the change you proposed above.

Granted, this is slightly more complicated if you're applying it to dozens of models.

**Comment by bloggervista** [comment]
hmm are you running on production or development. I guess changing config on production creates such problem.

**Comment by freekmurze** [comment]
Reopen if this is still a problem.
