### ISSUE TITLE
[QUESTION] - permissions added to role are not verified by user->can

### ISSUE THREAD

**Issue by joselfonseca** [spatie/laravel-permission#469]
Hello there!,

First of all thanks for this great package, i've come to a problem using the permissions via role and the middleware to check on permissions. 

Scenario
I have a role named Editor and I created a permission Edit Article, the permission was assigned to the role and then a user was given the Editor role.

If I check the permission using the middleware provided by the package over the user it trows a 403 even when the role has that permission assigned. If I check the permission on the user via hasPermissionTo method it returns true. 

My question is, Is this by design? could this be a bug? I can actually create a different middleware and use the hasPermissionTo method but i just wanted to ask here to hear your opinion.

Thanks

**Comment by drbyte** [comment]
Usually when someone runs into this situation it is a result of:
a) cache infrastructure problems
b) problems with custom gate
c) package conflicts preventing things from registering properly in the Service Provider
d) customizations that have resulted in an order-of-operations conflict

Here's a demo app where your same scenario works properly: https://github.com/drbyte/spatie-permissions-demo

**Comment by joselfonseca** [comment]
Thank for the reply, I encounter the problem after upgrading to 2.6.0 in the tests for a starter kit i maintain (https://github.com/joselfonseca/laravel-api/) . it was not giving any issues before and when i started working on the 5.5 upgrade i also upgraded to permissions 2.6.0, I was in 2.4

a) Is running the tests so the cache is basically an array
b) No custom gate is being used, only the API provided by Passport and Laravel.
c) The only extra package updated is Permissions besides Laravel.
d) I can't recall any customizations to the package, in fact we use what it offers out of the box.

Looking at the example you sent me i can't find the scenario I posted here in that repo, if you can point me to a branch or release where i can see that i will be able to compare. However the only thing done is add the permissions middleware to the controller like this:

```php
/**
     * UsersController constructor.
     *
     * @param User $model
     */
    public function __construct(User $model)
    {
        $this->model = $model;
        $this->middleware('permission:List users')->only('index');
        $this->middleware('permission:List users')->only('show');
        $this->middleware('permission:Create users')->only('store');
        $this->middleware('permission:Update users')->only('update');
        $this->middleware('permission:Delete users')->only('destroy');
    }
```
And the Kernel.php is like this
```php
/**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,
        'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,
    ];
```

if you want to replicate, you can clone the master branch on my starter kit and run `vendor/bin/phpunit --filter test_it_can_list_permissions` you will see that the test fails for a 403 when it is expecting 200 as the user running the test has the permission for that endpoint via the role. If I add a new middleware and use `$user->hasPermissionTo($permission)` instead of `$user->can($permission)` it will pass. 

I can understand if you can't take a look, and i can just use another middleware. I just want to bring this to the radar in case is a bug.

Thanks again.

**Comment by joselfonseca** [comment]
Also worth mention that if this is by design as the permission by role is not really being registered in the gate but as a relationship (as far as i can tell) then it is fine, I just have to use a different middleware.

**Comment by joselfonseca** [comment]
I found a solution here https://github.com/spatie/laravel-permission/issues/457

I added this to the set up `$this->app->make(PermissionRegistrar::class)->registerPermissions();` and now it works. Thanks!
