### ISSUE TITLE
Content author permission

### ISSUE THREAD

**Issue by dinajpuri** [spatie/laravel-permission#471]
Hello,
I've 3 user roles- user, moderator and admin. Admins and moderators have permission to "can edit".

But how do I give same permission to the content owner user (author of the content) ?

Regards

**Comment by AlexVanderbist** [comment]
Hi! 

This package doesn't handle user specific permissions. I'd suggest you use [Laravel's policies](https://laravel.com/docs/5.4/authorization#creating-policies) in combination with this package to get the required functionality.

Something like this should do the trick (untested):
```php
class ContentPolicy
{
    public function update(User $user, Content $content)
    {
        // Allow updates from any user with `can edit` permission or the content author
        return $user->can('can edit') || $user->id === $content->author_id;
    }
}
```

Hopefully this points you in the right direction. Let me know if you need any help!
