### ISSUE TITLE
Target [Spatie\Permission\Contracts\Permission] is not instantiable

### ISSUE THREAD

**Issue by dinajpuri** [spatie/laravel-permission#473]
Hello,
I tried to check if logged in user has permission like this
`auth()->user()->hasPermissionTo('edit_any_post')`

and it gave me the error. What did I miss?

**Comment by AlexVanderbist** [comment]
Hi! 

What version of Laravel are you using? If it's < 5.5 you'll have to add the serviceprovider in `config/app.php`:

```php
Spatie\Permission\PermissionServiceProvider::class,
```
