### ISSUE TITLE
@hasanyrole(Role::all()) example does not work

### ISSUE THREAD

**Issue by deathkillz** [spatie/laravel-permission#474]
as per instruction in the readme i tried:

```
@hasanyrole(Role::all())
```

but this throws an error:

> Class 'Role' not found (View: /home/vagrant/Code/project/resources/views/admin/settings.blade.php)

are the instructions wrong or should i do an extra step to make this work?

for example, this works perfectly in the same file:
```
 @hasanyrole('admin|editor')
```

the controller uses:
```
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
```

using: laravel 5.5

**Comment by AlexVanderbist** [comment]
You're correct, for any of the the example code to work you would need to import the `Role` and `Permission` namespaces into the controller/view you're using.

In practice however namespaces are rarely imported in blade views. The readme just hints at the possibility of passing a collection of roles to the `@hasanyrole` directive.

For example something like this: 
```php
// In your controller
use Spatie\Permission\Models\Role;
public function index() {
    $roles = Role::all();

    return view('anyView', compact('roles'));
}
```
```blade
{{-- in anyView.blade.php --}}
@hasanyrole($roles)
    We have at least one of the roles.
@endhasanyrole
```
