### ISSUE TITLE
Using givePermisionTo() with a custom guard

### ISSUE THREAD

**Issue by barryvanveen** [spatie/laravel-permission#476]
Hi! 

My application uses 2 guards: "web" and "api". At this moment I try to test that "web" users can successfully login and "api" users cannot. 

What works is:
```php
$user = new User();
// ...
$user->givePermissionTo("my_web_permission_name");
```

This works because the user has the "web" guard and the given permission has a guard_name of "web". No problem there.

What doesn't work:
```php
$user = new User();
// ...
$user->givePermissionTo("my_api_permission_name");
```

My user has the "api" guard and the given permission has the "api" guard_name as well. But, before assigning the permission, HasPermissions.php searches for the stored permission using the default guard name "web". This cannot be found and a PermissionDoesNotExist exception is thrown: There is no permission named `use_api` for guard `web`.

Am I overlooking something or is it not possible to use `$user->givePermission()` with a non-default guard?

The relevant code seems to be:
https://github.com/spatie/laravel-permission/blob/ed4f2180bf93ea948bc9e9ff1878713cb2459d4d/src/Traits/HasPermissions.php#L73-L87

Thanks in advance for any help!

Cheers,

Barry

**Comment by drbyte** [comment]
Quick thought, without doing any simulating yet:
Judging from line 79, perhaps passing your api permission name as an array (instead of as a string like in your example) might bypass the use of only the default(`web`) guard used on line 76.

**Comment by barryvanveen** [comment]
Thanks for thinking with me @drbyte and you're close to an answer. The `givePermissionTo()` method iterates over all permissions and calls `getStoredPermission()` individually as you can see in the relevant code:
https://github.com/spatie/laravel-permission/blob/ed4f2180bf93ea948bc9e9ff1878713cb2459d4d/src/Traits/HasPermissions.php#L19-L36

This is exactly what struck me as odd, the different behavior for retrieving stored permissions. When you retrieve a single permission it checks for the default guard. If however you retrieve an array of permissions it checks for all guards related to the model.

**Comment by drbyte** [comment]
@barryvanveen agreed. Something's incomplete there. Seems like it's putting the cart before the horse a bit.

Pinging @AlexVanderbist to take a peek ;)

**Comment by AlexVanderbist** [comment]
Hi! I finally took some time to look into this and if I understand correctly you've got two guards set up (`api` and `web`) that both use the same `User` model.

If this is the case I'm afraid `$user->givePermissionTo("my_api_permission_name");` is gonna be difficult to achieve as a `User` instance doesn't know to which guard it belongs to.

As a solution I would simply propose passing `Permission` instances (instead of strings) to `$user->givePermissionTo()`:
```php
$myWebPermission = Permission::findByName('my_web_permission_name', 'web');
$user->givePermissionTo($myWebPermission);
```

Another option is adding a `guard_name` property to your `User` models. Maybe even adding a `ApiUser` class that simply extends the `User` class and overwrites `guard_name` with `api`. This way `getDefaultGuardName()` will return the correct guard.

Hopefully this all makes sense. If you need any help let us know 👍

**Comment by AlexVanderbist** [comment]
On a side note: the code for retrieving multiple permissions using `getStoredPermission` contains a typo and is completely broken. However it looks like it's never used so I think we can safely remove that `is_array` section and change the `HasPermissions` interface in the next major version.

To fix this thread's issue we could try to do something like this in `getStoredPermission`: 
```php
return app(Permission::class)
    ->where('name', $permissions) 
    ->whereIn('guard_name', $this->getGuardNames()) 
    ->first(); 
```
But that will cause problems when the same permission exists for multiple guards... So I'm not sure how to fix this without explicitly specifying the `guard_name` on the model you're trying to give permissions.

**Comment by drbyte** [comment]
> contains a typo and is completely broken

Wow -- can't believe I missed that `whereId` too! (blush)

**Comment by barryvanveen** [comment]
> Maybe even adding a ApiUser class that simply extends the User class and overwrites guard_name with api. This way getDefaultGuardName() will return the correct guard.

This, I think, is the best solution and it works well for me. So, having a seperate Model for each guard is a best practice and makes it easier to use this package. 

As I re-read the documentation now, it does mention using multiple models and adding the `guard_name` attribute. But, I think it could be written down in a more direct way, maybe even using a simple example. I'll add my input to #479.

Thank you @drbyte and @AlexVanderbist!
