### ISSUE TITLE
Service Provider shouldn't access the DB

### ISSUE THREAD

**Issue by hackel** [spatie/laravel-permission#480]
When PermissionServiceProvider calls PermissionRegistrar::registerPermissions, it creates a delay if a database is not defined or the server times out, etc.  I noticed this because artisan commands were taking forever—even if just calling --help.  I believe that a Service Provider should only register functions and never perform any actual work or connect to external resources.

Perhaps instead of doing it this way, we could use a before hook on the gate like this:
```php
$this->gate->before(function () {
    if (!static::$permissionsRegistered) {
        try {
            $this->getPermissions()->map(function (Permission $permission) {
                $this->gate->define($permission->name, function ($user) use ($permission) {
                    return $user->hasPermissionTo($permission);
                });
            });

            static::$permissionsRegistered = true;
        } catch (Exception $exception) {
            if ($this->shouldLogException()) {
                $this->logger->alert(
                    "Could not register permissions because {$exception->getMessage()}" . PHP_EOL .
                    $exception->getTraceAsString()
                );
            }
        }
    }
});
```
This way, it will only load the permissions once, the first time a Gate check is performed.

**Comment by drbyte** [comment]
@hackel wrote:
> I believe that a Service Provider should only register functions and never perform any actual work or connect to external resources.

I tend to agree.

Your proposed code change introduces 2 main differences (in addition to altering the (bool) return type):
1. Wrapping the whole thing in the`before` hook of the gate.
2. Setting and checking a static property to force single execution.

Dropping it in and running the test suite fails badly ... caching, blade, middleware, gate, logging tests.

I think making this change will require some significant reworking.

**Comment by bloggervista** [comment]
@drbyte  I guess this package implements wordpress way. But if we implement drupal way than we don't need to worry about database connection for permissions. We store all permissions in a file. As it is in file i guess it will be cached using config:cache artisan command. But the downside is it will change api too much right? 

And i guess permissions will not change that much in production.

**Comment by drbyte** [comment]
@bloggervista wrote:
> We store all permissions in a file.

If all your permissions are in a file, and always/only used directly from that file, then you don't need this package.

This package ties permissions with models, using Eloquent. By nature that uses the database
This Issue ticket is not related to "store all permissions in a file". Instead, it is proposing a logic change so that the actual database access "step" happens "after" the ServiceProvider fires, not "during" the registration/boot of the ServiceProvider.

**Comment by viteksafronov** [comment]
It is a very important issue. Our application is running in Docker and we do `artisan optimize` on docker image build. We obviously don't have a database connection on building machine so there are frustrating errors at this step. Maybe we may not register the permissions service provider in console mode? Is it really needed?

**Comment by drbyte** [comment]
#505 looks to resolve this.

**Comment by drbyte** [comment]
@viteksafronov wrote:
> we do `artisan optimize` on docker image build

Note: `artisan optimize` does nothing in Laravel 5.5, and will be removed in Laravel 5.6 (so running that command will trigger an error, and will break automated builds starting in 5.6)
