### ISSUE TITLE
Why roles are not assigned in Unit test

### ISSUE THREAD

**Issue by saqueib** [spatie/laravel-permission#482]
I am trying to Unit test role assignment on user but Its always returning false, no roles are getting assigned

```php
namespace Tests\Unit;

use App\User;
use Tests\TestCase;
use Spatie\Permission\Models\Role;
use Illuminate\Foundation\Testing\RefreshDatabase;

class RoleTest extends TestCase
{
    use RefreshDatabase;

    /**
    * user can have roles assigned
    *
    * @test
    */
    function user_can_have_roles_assigned()
    {
        $roleAdmin = Role::create(['name' => 'Admin']);
        $roleUser = Role::create(['name' => 'User']);

        $user = factory(User::class)->create();

        $this->assertFalse($user->hasRole('Admin'));
        $user->assignRole($roleAdmin);
        $this->assertTrue($user->hasRole('Admin'));

        $this->assertFalse($user->hasRole('User'));
        $user->assignRole($roleUser);
        $this->assertTrue($user->hasRole('User'));

        $this->assertTrue($user->hasAllRoles('User', 'Admin'));
    }
}
```

> For testing I am using in memory sqlite db

I am planning to use it with Laravel Spark with Laravel 5.5, is it possible? 
Whats wrong in this test i am getting `$user->hasRole('Admin')` fasle.

**Comment by drbyte** [comment]
This package registers its permissions by reading them from the database, when the ServiceProvider is booted.

Since your unit tests don't create the permissions until *after* that registration is done, you need to manually re-register them. 

**This is explained in the README** :

```php
 public function setUp()
    {
        parent::setUp();

        $this->app->make(PermissionRegistrar::class)->registerPermissions();
    }
```

**Comment by drbyte** [comment]
Example in demo app: https://github.com/drbyte/spatie-permissions-demo/blob/master/tests/Unit/RolePermissionGrantTest.php#L24

**Comment by saqueib** [comment]
Thanks for pointing this out, I will keep it in mind for permission testing, 
But I am only testing for user roles. I have added above `setUp` code but it still doesn't work.

**Comment by saqueib** [comment]
@drbyte Issue was with $user already loaded so it was unable to fetch the assigned role, calling `fresh()` on eloquent model before assertion fixed it.  

```php
function user_can_have_roles_assigned()
    {
        $user = factory(User::class)->create();

        $this->assertFalse($user->fresh()->hasRole('Admin'));
        $user->assignRole('Admin');
        $this->assertTrue($user->hasRole('Admin'));

        $this->assertFalse($user->fresh()->hasRole('User'));
        $user->assignRole('User');
        $this->assertTrue($user->fresh()->hasRole('User'));

        $this->assertTrue($user->fresh()->hasAllRoles('User', 'Admin'));
    }
```
