### ISSUE TITLE
add roles to searchable array

### ISSUE THREAD

**Issue by Lawrence-Dawson** [spatie/laravel-permission#485]
I'm attempting to make Users searchable via roles using Laravel scout.

To do this I have to add the Users roles to an array thats returned by a function `toSearchableArray()`.

See "Configuring Searchable Data" here https://laravel.com/docs/5.4/scout

The issue I'm having is that when i attempt to access the Users roles from within the User class like so 

`$roles = $this->roles`

I always get an empty collection.

However if I attempt to get all the roles that user has elsewhere, say in a test, like so

`dd($user1->roles)`

I get a collection containing the Users roles.

Is it possible to access the Users roles from within its own class?

Any help would be greatly appreciated,

Thank you

**Comment by introwit** [comment]
@Lawrence-Dawson Hi :) We need to set the $user right? I mean when we do things like `$user = Auth::user()` we say that use the properties of that authenticated user, so in `$user->roles` roles will have some user to go and ask to, but in the class when you say $this->roles, it looks for a property/variable called `roles` on the class. Let me know if this isn't the answer you were looking for :)
