### ISSUE TITLE
tables user_has_roles and user_has_persmissions

### ISSUE THREAD

**Issue by Gonzalo2324** [spatie/laravel-permission#486]

**Comment by drbyte** [comment]
In v2 they are called `model_has_roles` and `model_has_permissions`, as described in your `/config/permissions.php`: https://github.com/spatie/laravel-permission/blob/master/config/permission.php#L49-L63

In v1 they were formerly called `user_has_roles` and `user_has_permissions`. But that's only applicable to v1.

**Comment by Gonzalo2324** [comment]
Thanks @drbyte but how could I make relations with the user model?

**Comment by drbyte** [comment]
I don't understand your question.  This package already manages that if you use its built-in functions as described in the readme.

Your question suggests that you're trying to do direct database manipulation separately?

What are you doing that led you to post this issue?
