### ISSUE TITLE
Multi auth

### ISSUE THREAD

**Issue by lithstud** [spatie/laravel-permission#49]
Hi, quick and simple question - it doesn't seem that it supports multi auth at the moment, I was wondering whether you are going to add support for it?

**Comment by freekmurze** [comment]
I'll add support for it, when I need the functionality myself. So it could be a few months. If you need this quick, feel free to submit a PR.

**Comment by AEK-BKF** [comment]
Hi @freekmurze 
Any news about multi-auth ? I'm using L5.4 and I've two Auths : User and Admin.

**Comment by freekmurze** [comment]
v2 of the package has support for multiple guards.
