### ISSUE TITLE
How can I delete a role/permission?

### ISSUE THREAD

**Issue by phamngocson1988** [spatie/laravel-permission#491]
Sorry but I can't find out how to delete a role/permission. Please show me how to do it correctly. I can delete it by the code "$role->delete()" but I'm not sure that is a good idea.
Thanks.

**Comment by AlexVanderbist** [comment]
Hi! `$role->delete()` should delete the role without any issues. There's a foreign key constraint on the `model_has_roles` table that will delete any related rows to avoid issues.

Let me know if you need any more help :)
