### ISSUE TITLE
Package autodiscovery tries to access roles table

### ISSUE THREAD

**Issue by fsavina** [spatie/laravel-permission#492]
If you try to install an application (that uses this package) in a different environment before creating and migrating the database you will get an error from the `package:discover` artisan command, because it tries to access the `roles` table which is obviously non existent.

The service provider shouldn't access the database during the registration process.

The recreate the problem, just change the name of the database in your .env file with a fake name and run `php artisan package:discover`.

**Comment by pauls6832** [comment]
How did you fix this? I have the same problem. The database exists but I have not created the tables. When I try to run any artisan commands I get an error that the permissions table does not exist.

```
$ artisan

[Illuminate\Database\QueryException]                                                                                                      
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testdb.permissions' doesn't exist (SQL: select `name` from `permissions`   
  order by `name` asc)                                                                                                                      
```

**Comment by drbyte** [comment]
Guessing you're using an older version of the package that did permission caching during the `register` stage, instead of in the `boot` stage.

**Comment by mrimran** [comment]
The solution that works is here https://spatie.be/docs/laravel-permission/v2/installation-laravel

```
composer require spatie/laravel-permission
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"
php artisan migrate
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"
```
