### ISSUE TITLE
Remove morphToMany return type for users() method at least?

### ISSUE THREAD

**Issue by ziming** [spatie/laravel-permission#495]
A project I'm currently working on had each user's username as their primary key field in their users table instead of an integer id. I tried to override the users().etc method but because a return type is specified (morphToMany), I couldn't return something else. I don't have the authority to modify the users table either.

So here's a suggestion to either remove the strict return type or upgrade the return type to belongsToMany at least, which is a superclass of morphToMany (I don't think you used any methods specific to morphToMany). Removing the return type would make things much more flexible too.

My current way is to create my own role/permission classes and wrap yours like an adapter for all the other methods. But it could be simpler. I could just extend your class if the morphToMany return type is not specified. Sure I could specify a method called myUsers() too but that also means I have a non working users() method I must always remember not to call.

**Comment by AlexVanderbist** [comment]
Hi, what exactly is stopping you from changing the migration to allows strings as the `model_id` in all tables and extending the `users()`, `permsissions()` and `roles()` methods to use `username` as the `relatedKey`? 

For example when extending the `Permission` class and overwriting the `users()` method:
```php
    public function users(): MorphToMany
    {
        return $this->morphedByMany(
            getModelForGuard($this->attributes['guard_name']),
            'model',
            config('permission.table_names.model_has_permissions'),
            'permission_id',
            'model_id',
            'id',
            'username'
        );
    }
```

**Comment by AlexVanderbist** [comment]
Closing this to due to inactivity. I'll update the return type to something sensible in v3 of the package.

**Comment by ziming** [comment]
Ah, the project uses posgreSQL. Comparing an integer and a string will result in an error so if model_id is of string type and another table id field is an auto increment integer type. Trying to do comparison or joins will get error (model_id = something.id). It doesn't do loose comparison.

I settled the issue in the end currently by adding a separate field called username. Then since I can't override users() as it defined MorphToMany, I create my own model class and wrap around Spatie Role and Permission class like an adapter. then write my own users method but return type set to BelongsToMany. so model_type is App\User and username is the user's username while model_id is null for that record.

The methods on BelongsToMany and MorphToMany are the same I believe except that when you call attach(), save() on a MorphToMany, it fills in model_id and model_type. But that should be transparent behind the scene as MorphToMany is a sub class of BelongsToMany.

Of course I could just not name that method users() too and leave a note on the project not to call $role/permission->users().
