### ISSUE TITLE
want to install on php 5.6

### ISSUE THREAD

**Issue by umefarooq** [spatie/laravel-permission#496]
is there any possibility i can install this package on my production server running php 5.6. laravel version 5.4

**Comment by drbyte** [comment]
v1 supports PHP 5.6

`composer require spatie/laravel-permission:^1`

... but be mindful that v1 is no longer being actively developed.

**Comment by introwit** [comment]
Thanks @drbyte :)

**Comment by umefarooq** [comment]
one more question, if i want to update laravel/permission from old to latest version how will be relation migration.

**Comment by AlexVanderbist** [comment]
There's no automated migration. You'll have to manually go over the related tables and update the column names/rows accordingly. Have a look at the current migrations to get an idea what the schema looks like. Good luck!
