### ISSUE TITLE
Field model_type doesn't have a default value

### ISSUE THREAD

**Issue by enghelewa** [spatie/laravel-permission#498]
I am trying to assign role to a user when seeding the database
`$user->assignRole('master');`
But I'v got this error
`Field 'model_type' doesn't have a default value`

Is there any thing I'v missed?

**Comment by AlexVanderbist** [comment]
Hi, I can't seem to replicate this issue. The `model_type` field should be filled in by Laravel's `morphToMany` relationship. 

Are you by any chance using morph maps or any other packages that might influence this? What version of the Laravel and the package are you using?

**Comment by enghelewa** [comment]
I am using laravel 5.5 without any extra packages other that "laravel-permission".
I only changes the term "model" to "user" but it still give me the same error with "user_type" instead of "model_type"

**Comment by enghelewa** [comment]
I found the problem, its because I have this function in my User model. I thought that the trait `HasRoles` will take care of this relation. So I removed it and it worked fin. But still the model_id stored as 0

**Comment by enghelewa** [comment]
The zero problem was solved by `public $incrementing = false;` for User model.
I think all these problems are made by me 🥇

**Comment by mnoquiao** [comment]
> I found the problem, its because I have this function in my User model.
> 
> ```
> public function roles(){
>         return $this->belongsToMany(Role::class,'role_users','user_id','role_id');
>     }
> ```
> 
> I thought that the trait `HasRoles` will take care of this relation. So I removed it and it worked fin. But still the model_id stored as 0

this fixed my issue. I have to rename my method roles().

**Comment by KodokMagang** [comment]
SQLSTATE[HY000]: General error: 1364 Field 'model_type' doesn't have a default value (Connection: mysql, SQL: insert into `model_has_roles` (`model_id`, `role_id`) values (1, 1))

help me guys, how to fix this error?

**Comment by drbyte** [comment]
> `insert into model_has_roles (model_id, role_id) values (1, 1)`

That query comes from custom code you have written. Laravel's polymorphic handling would provide `model_type` automatically. Therefore your query must be coming from your own custom code. Probably a `roles()` function in your model which is overriding the `roles()` method in this package. Rename your `roles()` function to something else.
