### ISSUE TITLE
Soft deleting

### ISSUE THREAD

**Issue by JonasLod** [spatie/laravel-permission#501]
I'm using soft deletes to lock out users but attached roles get deleted too. Is there a way to keep the roles attached and still be able to use soft deletes?

**Comment by AlexVanderbist** [comment]
You can quickly fix this by overwriting the `bootHasRoles` method in your `User` class: 
```php
    public static function bootHasRoles()
    {
        static::deleting(function ($model) {
            if (! $model->isForceDeleting()) {
                // don't do anything if we're only soft deleting the model
                return;
            }

            $model->roles()->detach();
            $model->permissions()->detach();
        });
    }
```

However I'm not sure what the expected behaviour would be in this case. I'll check and might tag a fix later today.

**Comment by JonasLod** [comment]
I tested the code and it seems to be working fine. Thanks a lot!

**Comment by AlexVanderbist** [comment]
Added to the package in v2.7.1!
