### ISSUE TITLE
Is there dot notation support with wildcard?

### ISSUE THREAD

**Issue by neyaoz** [spatie/laravel-permission#508]
All the examples about the naming of permissions are like `edit articles`. Is it possible to define as `articles.edit` or `articles.tags.edit`. And what about the checking it like `$user->can('articles.*')` or `$user->can('articles.tags.*')`? I have come from Sentinel and it is quite hard to get used to it. :)

**Comment by drbyte** [comment]
Not at this time. 
Presently all permission names are unrelated strings, with no inheritances/heirarchies based on patterns used in your naming conventions.
