### ISSUE TITLE
assign role to user on register

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-permission#511]
Hi,
How can I assign role on user while he/she register? and if that role doesn't exist create it?

here is my register controller

```php
<?php

namespace App\Http\Controllers\Auth;

use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;

class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */

    use RegistersUsers;

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = '/home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest');
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'firstname' => 'required|string|max:255',
            'lastname' => 'required|string|max:255',
            'username' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return \App\User
     */
    protected function create(array $data)
    {
        return User::create([
            'firstname' => $data['firstname'],
            'lastname' => $data['lastname'],
            'username' => $data['username'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }
}
```

**Comment by andyjh07** [comment]
You could create a `UserObserver` and do something like:

```
public function created(User $user)
    {
        $user->assignRole('Partner');
    }
```

**Comment by AlexVanderbist** [comment]
I agree with @andyjh07. Here's some more information about model observers: https://laravel.com/docs/5.5/eloquent#observers

**Comment by robertnicjoo** [comment]
@andyjh07 No I just needed to create the role for first time in case admin forget to create and be checked for next time, but is of i just assign existing one.

- Thank you for respond.

**Comment by pschilly** [comment]
Hate to open this up - but, I am trying to do exactly this and the Observer, although it is being fired (I have been able to log a message from the created() event), does not assign the role as expected?

This is in the UserObserver.php
`public function created(User $user): void
    {
        // Assign Default User Role of "Guest"
        $user->assignRole('guest');
    }`

And the EventServiceProvider.php
`public function boot(): void
    {
        User::observe(UserObserver::class);
    }`


Am I missing something somewhere? I am getting no errors at all - just simply isn't assigning the role.

**Comment by andyjh07** [comment]
@pschilly Is the role named `Guest` or `guest`? That'd be the first thing to check

**Comment by pschilly** [comment]
That was my first thought as well - it's in system as "guest" all lower case

**Comment by andyjh07** [comment]
@pschilly Bit of a different way to debug it but have you tried running `php artisan tinker`, grabbing a random user, then trying `$user->assignRole('guest')` and seeing if it attaches? This would help narrow down if the problem is the role, or the observer. Perhaps share your observer file?

**Comment by drbyte** [comment]
Not sure if your code is exactly as you posted, or if you just didn't use github's markdown formatting for code.
The code you posted is all on one line:
> `public function created(User $user): void { // Assign Default User Role of "Guest" $user->assignRole('guest'); }`

If that's actually how it is in your real PHP file, then it's not working because you have the comment `// Assign...` on the same line as the command `$user->assign...`, and the comment blocks the code from running.

**Comment by pschilly** [comment]
No its not like that - just didnt use githubs thing properly lol

To make matters more strange - it seems to be magically working now?

I am using Filament - and through the "Add User" bit - it does not seem to work, but when someone created a user with the registration page it did? Very strange.

**Comment by andyjh07** [comment]
@pschilly That might be a different method for adding a user compared to registration form. Have you tried any other methods like `creating()` or anything along those lines?
