### ISSUE TITLE
Test User has more than one roles ?

### ISSUE THREAD

**Issue by JFOC** [spatie/laravel-permission#52]
How to test if user has one or more roles ?
Example:
There is 3 roles: admin, support, staff
User A is assigned for roles admin

If I want to know if user A has roles admin or staff.

Trying to use hasAnyRoles but no luck

Is this bug ?

When hasAnyRole('admin','staff') will return true
When hasAnyRole('staff','admin') will return false

Thanks

**Comment by arcanedev-maroc** [comment]
The `hasAnyRole()` method except only string, Collection object or Role Model.

Is it a bug ? **Yes**.

You can check the source code https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L90.

**Comment by freekmurze** [comment]
This is indeed bug, and I'm working on a fix. Thanks for letting me know.

**Comment by freekmurze** [comment]
Fixed in version 1.3.4
