### ISSUE TITLE
Unknown column 'role_has_permissions.roles_id'

### ISSUE THREAD

**Issue by xcarlos** [spatie/laravel-permission#521]
For some reason when I'm trying to get a role permissions, an "s" is being added to the field "role_id" and I can't figure out what is causing that.

I can fix it by renaming the column from `role_has_permissions.role_id` to `role_has_permissions.roles_id`, but I prefer to use the field name as singular.

This is the complete error:

`Column not found: 1054 Unknown column 'role_has_permissions.roles_id' in 'field list' (SQL: select 'permissions'.*, 'role_has_permissions'.'roles_id' as 'pivot_roles_id', 'role_has_permissions'.'permission_id' as 'pivot_permission_id' from 'permissions' inner join 'role_has_permissions' on 'permissions'.'id' = 'role_has_permissions'.'permission_id' where 'role_has_permissions'.'roles_id' = 1)`

Any clue?

**Comment by drbyte** [comment]
Looks like you're using v1 of this package.

What's the output of `composer show | grep laravel` ?  (looking for both the Laravel and Spatie versions, so all the output of that will be useful)

What's the content of your `/config/laravel-permission.php` file? What changes have you made to it and why? 

Do you have any other packages providing role/permission functionality installed?

Can you post your User model? Maybe you've got some overridden methods/properties that are interfering?

**Comment by xcarlos** [comment]
I'm using version 2.7 of this package and laravel 5.4.

I didn't change anything from the configuration file:

`<?php

return [

    'models' => [

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your permissions. Of course, it
         * is often just the "Permission" model but you may use whatever you like.
         *
         * The model you want to use as a Permission model needs to implement the
         * `Spatie\Permission\Contracts\Permission` contract.
         */

        'permission' => Spatie\Permission\Models\Permission::class,

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your roles. Of course, it
         * is often just the "Role" model but you may use whatever you like.
         *
         * The model you want to use as a Role model needs to implement the
         * `Spatie\Permission\Contracts\Role` contract.
         */

        'role' => Spatie\Permission\Models\Role::class,

    ],

    'table_names' => [

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * table should be used to retrieve your roles. We have chosen a basic
         * default value but you may easily change it to any table you like.
         */

        'roles' => 'roles',

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * table should be used to retrieve your permissions. We have chosen a basic
         * default value but you may easily change it to any table you like.
         */

        'permissions' => 'permissions',

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * table should be used to retrieve your models permissions. We have chosen a
         * basic default value but you may easily change it to any table you like.
         */

        'model_has_permissions' => 'model_has_permissions',

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * table should be used to retrieve your models roles. We have chosen a
         * basic default value but you may easily change it to any table you like.
         */

        'model_has_roles' => 'model_has_roles',

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * table should be used to retrieve your roles permissions. We have chosen a
         * basic default value but you may easily change it to any table you like.
         */

        'role_has_permissions' => 'role_has_permissions',
    ],

    /*
     * By default all permissions will be cached for 24 hours unless a permission or
     * role is updated. Then the cache will be flushed immediately.
     */

    'cache_expiration_time' => 60 * 24,

    /*
     * By default we'll make an entry in the application log when the permissions
     * could not be loaded. Normally this only occurs while installing the packages.
     *
     * If for some reason you want to disable that logging, set this value to false.
     */

    'log_registration_exception' => true,
];
`
I'm not using any other package to provide this functionality.

This is my User model:
`<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
	use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function branch()
	{
		return $this->belongsTo('App\Models\Branches');
	}
}
`

**Comment by drbyte** [comment]
> when I'm trying to get a role permissions

Can you show code where you're trying to get role permissions?

**Comment by xcarlos** [comment]
This is the line that is causing the problem `$per_found = $role->hasPermissionTo($perm->name);`

**Comment by xcarlos** [comment]
Hey drbyte, thank you for you time. I was able to trace the issue.

The problem was that my model is called "Roles" which is extending the package's "Role" model, it that model the relationship with the permission table is set using:

public function permissions(): BelongsToMany
    {
        return $this->belongsToMany(
            config('permission.models.permission'),
            config('permission.table_names.role_has_permissions')
        );
    }

The belongsToMany function tries to figure out the name of the foreign key by using the name of the model, and since the model is "Roles" that is why uses roles_id as the foreign key.

The solution is just to pass the name of the foreign key:

public function permissions(): BelongsToMany
    {
        return $this->belongsToMany(
            config('permission.models.permission'),
            config('permission.table_names.role_has_permissions'),
	    'role_id'
        );
    }
