### ISSUE TITLE
The given role or permission should use guard `` instead of `api`.

### ISSUE THREAD

**Issue by blancomaberino** [spatie/laravel-permission#524]
Hello,

I am trying to assign a role to a user and I am getting the problem mentioned on the subject. I am not sure if I am doing something wrong or if it's a problem with the package.

My code:

```
$superadmin = User::create([
            'first_name' => 'Super',
            'last_name' => 'Admin',
            'email' => 'super@admin.com',
            'password'  => 'password',
            'active'    => 1
 ]);
 $superadmin->assignRole(Role::findByName('superadmin', 'api'));
//I also tried by doing $superadmin->assignRole('superadmin');
```

Actual roles are created on a different migration that runs previously. Role `superadmin` does exist because when I dump its value `dd(Role::findByName('superadmin', 'api'))` it dumps the correct information.

```
Role::create(['name' => 'superadmin']); // (in the database it creates for the guard `api` since it's the default one.
```

At the top of my seeder, I also have the piece of code `app()['cache']->forget('spatie.permission.cache');`.

My `config/auth.php` file contains the following code:

```
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt-auth',
            'provider' => 'users',
        ],
    ],
```

Thanks in advance,

Regards,

Marcelo

**Comment by blancomaberino** [comment]
It seems it was an issue with config cache. It was caching User Model and, because of that, it was throwing the error.

**Comment by dajoeberlei** [comment]
Im having the same issue. I deep dived a little into the package and found out that `$this->getGuardNames()` within the  ensureModelSharesGuard() method returns an empty array in my application. I cleared my cache and my config but still having the issue unfortunately.

```
protected function ensureModelSharesGuard($roleOrPermission)
    {
        if (! $this->getGuardNames()->contains($roleOrPermission->guard_name)) {
            throw GuardDoesNotMatch::create($roleOrPermission->guard_name, $this->getGuardNames());
        }
    }
```
