### ISSUE TITLE
Permissions are not found on server

### ISSUE THREAD

**Issue by roblesterjr04** [spatie/laravel-permission#527]
The package works exactly as designed in my development environment (running homestead)

But when I deploy the code, none of the permissions can be found. Creating them works fine, and they are on the database, and even if I clear the cache, the permission not found exception is thrown. Both environments meet the requirements of the package. Any ideas of what I can look for?

**Comment by ctf0** [comment]
@roblesterjr04 are u using `Cache::get('spatie.permission.cache')` ? 

if so something went wrong with the package and for some reason its not creating this key anymore.

**Comment by roblesterjr04** [comment]
It looks like it was a permissions issue on my server. The errors in the console are not helpful enough. Thanks. We can close this.
