### ISSUE TITLE
Extend for Multi-Tenant Multi-Database

### ISSUE THREAD

**Issue by tflowers3** [spatie/laravel-permission#532]
Can this easily be extended for a multi-tenant, multi-database setup?  Ideally, all roles and permissions would be defined in a shared database, but assigned within the tenant databases.  I'm currently using Tenanti for multi-tenancy although considering handling it myself, fwiw.

**Comment by AlexVanderbist** [comment]
There was an interesting thread regarding multi-tenancy here: #280. Personally I've never thought about how to implement multi-tenancy in this package however I might look into it for v3. 

Joseph Silber's Bouncer looks promising for multi-tenancy. You might want to look into that as well: https://github.com/JosephSilber/bouncer/issues/217
