### ISSUE TITLE
Package cannot run in lumen 5.5

### ISSUE THREAD

**Issue by reishou** [spatie/laravel-permission#533]
I get errror when implement package to lumen 5.5:
vendor/spatie/laravel-permission/src/PermissionServiceProvider.php
Call to undefined method Laravel\Lumen\Application::configPath()
Can change it to config_path helper, and I can make a custom helper file to implement.

**Comment by omar10594** [comment]
I'm having the same problem.

Change to config_path i think is a good idea.

And if you are using lumen, you could use https://github.com/irazasyed/larasupport

you should change databasePath to database_path too.

**Comment by AlexVanderbist** [comment]
Hi, thanks for letting us know. Feel free to PR this change and we'll merge it in!
