### ISSUE TITLE
How to use givePermissionTo method ？

### ISSUE THREAD

**Issue by swat199538** [spatie/laravel-permission#535]
when i use givePermissionTo method laravel say have a error

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `model_has_permissions` (`model_id`, `model_type`, `permission_id`) values (, App\User, 2))

what is the `model_id` column?

**Comment by swat199538** [comment]
sorry i use Collection

**Comment by omenejoseph** [comment]
how as this issue resolved?
