### ISSUE TITLE
about the Gate::before issue

### ISSUE THREAD

**Issue by stevenyangecho** [spatie/laravel-permission#536]
#505 this issue,changed the way to use `Gate::before()`
but this will has problem 

via  this laravel gate `before()` callback invoke code
https://github.com/laravel/framework/blob/ac7eee2a13beb53b4806d1fb830f49dbf40df30c/src/Illuminate/Auth/Access/Gate.php#L290
it means although  the  added closure is a list of closures.but onces ths closure return not null value ,just like return true or false,it will immediately return the result and ignore the other closures.

and I looked the order regist of `Gate::before()`.this  spatie/laravel-permission alwasy before my `App\Providers\AuthServiceProvider` so the `Gate::before()` in `AuthServiceProvider` will not be invoked

do u have any idea? @AlexVanderbist

**Comment by drbyte** [comment]
> and I looked the order regist of Gate::before().this spatie/laravel-permission alwasy before my App\Providers\AuthServiceProvider so the Gate::before() in AuthServiceProvider will not be invoked

Perhaps disabling auto-discovery for this package, and manually registering the ServiceProvider in your config/app.php will control the order of loading for your specific situation?

**Comment by drbyte** [comment]
The pending PR at #538 appears to resolve this problem.

**Comment by AlexVanderbist** [comment]
Fixed in v2.7.5!
