### ISSUE TITLE
Do you support permissions and roles to add alias features?

### ISSUE THREAD

**Issue by swat199538** [spatie/laravel-permission#537]
I think this is useful features.

**Comment by drbyte** [comment]
Can you explain in more detail?

**Comment by swat199538** [comment]
Because of my background to the management of these rights and role, but I was using Chinese, I can not directly show these permissions and role values, the user will feel strange, so I had to create a new table to do these permissions and roles of the Chinese show that if you can support the alias native so tell me about the demand will be easier to use.

**Comment by ankurk91** [comment]
I have faced similar issue in past.
Right now both role and permission tables have a single database column `name` that is being used as unique slug.
For example the permission name is `create_post` and i want to show `Ability to create posts` on UI.
Same goes with role.
I would like to have a new column to hold `display_name` that we can allow our customer to change without the need of changing the slug (name).

**Comment by AlexVanderbist** [comment]
I can see how this is a problem. However you can really easily update the permissions table migration to include a `display_name` column. The `Permission` class is an eloquent model so you can set that display name property like this: 
```php
Permission::create(['name' => 'articles.edit', 'display_name' => "Edit articles"]);
```

I'm not sure if we want to include this in the actual package as it's something you can easily do yourself. Maybe we can include a section in the readme about custom properties? (mentioning #479 so I don't forget)

**Comment by bjuppa** [comment]
I'm not sure this solves your problem, but to display permission and role names in a more user friendly way in the interface, perhaps you could pass names through the Laravel translation functions, like
```php
__($role->name)
```
and define the display string you want in the language files?

https://laravel.com/docs/5.5/localization#using-translation-strings-as-keys

**Comment by akongnwi02** [comment]
@bjuppa This makes more sense to me

**Comment by top-master** [comment]
Because there are many languages, adding a `display_name` column for each is wrong.

Simply use translation (the `__(...)` method).

**But** if `display_name` needs to be editable by users (admins or managers), then create a custom translation-override table, with columns like:
* id
* lang
* name (keyword)
* display_name

Where if the `name` was **not** in table for current `lang`,
then logic should fallback to `__(...)` method's result.
