### ISSUE TITLE
Allowing all permissions to super user

### ISSUE THREAD

**Issue by ehsanquddusi** [spatie/laravel-permission#54]
How can a super user have access to all permissions automatically without manually granting each one.

**Comment by freekmurze** [comment]
This package does not have functionality to define a super user, but you can intercept authorization checks in Laravel.

```php
$gate->before(function ($user, $ability) {
    if ($user->isSuperAdmin()) {
        return true;
    }
});
```

Take a look at [the documentation on authorization](https://laravel.com/docs/5.2/authorization)
