### ISSUE TITLE
Remove pivot from getAllPermissions function

### ISSUE THREAD

**Issue by enghelewa** [spatie/laravel-permission#543]
Hi I am using `$user->getAllPermissions()` to retrieve all permissions. But the result contains `pivot` properties that brakes comparison with same permission result from other sources inside `vuejs`.
to remove `pivot` you must add protected `$hidden = ['pivot'];` inside `Models\Permission.php`
I am using my own `Permission` model that inherits from `spatie` `Permission`. but `getAllPermissions()` uses `spatie's` one.
Is there a simple way to remove it?
thanks

**Comment by AlexVanderbist** [comment]
I'd suggest only comparing the permissions' name properties, not the entire object. This will be more performant and avoid your issue with the `pivot` property altogether.

Feel free to PR a fix as well to make `getAllPermissions()` return the right (custom) models.

Thanks!
