### ISSUE TITLE
Allow use of Laravel Scout with Role

### ISSUE THREAD

**Issue by alexbowers** [spatie/laravel-permission#547]
It'd be great to be able to combine Laravel Scout with Permission

```
$users = User::role('admin')->search('...')->paginate(10);
```

To search all `admin` users

**Comment by AlexVanderbist** [comment]
Hi, I totally agree. I'll look into this for v3 of the package, for now I think you should be able to use local query scopes to do this.

**Comment by alexbowers** [comment]
Yeah i've done it with local query scopes, but unfortunately, that doesn't let me use Scout to search (that im aware of).

Thanks though. Any idea when V3 will be worked on, and is there a feature list?

I'd like to contribute to that if able.

**Comment by AlexVanderbist** [comment]
Hm, I'll have to look into the way scout works then...

For v3 there's an issue going here: https://github.com/spatie/laravel-permission/issues/479 👍

**Comment by Ojsholly** [comment]
Please was this ever revisited? @drbyte

**Comment by drbyte** [comment]
> Please was this ever revisited? @drbyte

As far as I know, no this has not been directly revisited.
Keeping the Scout index up-to-date could prove complicated insomuch as risking performance penalties when the cache must be updated. And of course, then it'll be important to ensure it's pulling from the correct cache when querying.

**Comment by MuluhGodson** [comment]
I recently came accross this problem. Here is how I solved it using [Scout Query customization](https://laravel.com/docs/10.x/scout#customizing-the-eloquent-results-query). We can get the query and use the `whereHas` method to filter out the specific users we want.

```php
use Illuminate\Database\Eloquent\Builder;


$role = "admin";
$users = User::search($search_query)->query(function (Builder $query) use ($role){
                           $query->whereHas('roles', function (Builder $query) use ($role){
                                 $query->where('name', $role);
                           });
               })->paginate(10)
```

hope this helps.

**Comment by drbyte** [comment]
@MuluhGodson Thanks for the update!
