### ISSUE TITLE
syncRoles should accept id's too.

### ISSUE THREAD

**Issue by arakash92** [spatie/laravel-permission#548]
There's a package (kristijanhusak/laravel-form-builder) I'm using which integrates with laravels models to provide dropdown/select fields for relationships.

The problem is that it uses the 'id' as the keys. In other words, I'm trying to do `$user->syncRoles([]3, 4, 7])` and it doesn't work that way obviously.

I think it ought to since it's common for data to be in that way.

**Comment by AlexVanderbist** [comment]
I totally agree, let's continue this issue in your PR.
