### ISSUE TITLE
User with multiple roles per team

### ISSUE THREAD

**Issue by nuclearsam** [spatie/laravel-permission#551]
Hi,

My user can be part of multiple teams and can have different roles for each team. I have set a many-to-many relationship between team and user model with `user_team` pivot table. Is there any option to add roles to this `user_team` table so that user can have different roles in each team?

Any guidance in this respect is welcome. 

Regards
Sam

**Comment by AlexVanderbist** [comment]
Hi,

Sadly there's no (easy) way to do that right now. That's definitely something I'm looking at for v3. 

The best way to go at this with the current state of the package is probably to use events to give the user the appropriate roles when he's associated with a team... but this is not ideal.

**Comment by erikn69** [comment]
@AlexVanderbist this feature does not exist yet?
Are you accepting PR for this?
