### ISSUE TITLE
Viewing certain DB Entries

### ISSUE THREAD

**Issue by naknode** [spatie/laravel-permission#553]
Let's say I have  three models:

- User
- Company
- Report

A `User` can only belong to one `Company` . Each `Company` has different roles that a `User` can go into.

A `Report` belongs to one `Company`. And a `Company` has many `User`.

Refer to this image:

<img width="384" alt="permissions" src="https://user-images.githubusercontent.com/616320/32385007-b8657bfa-c08a-11e7-848a-4e5523a214bc.PNG">

Is it possible, or would it be feasible, to make it so only certain roles inside a `Company` can view only certain DB entries of `Report`? Because I want only the CEOs of a `Company` to only view `Report` ID `2`, `5` and `7` and I want  Sr. Devs of `Company` to only view `Report` ID `10` and `15` and etc.

I know I can do `$user->givePermissionTo('view articles', 'delete articles');` but that seems to apply to all IDs in `articles`.

**Comment by cosecantt** [comment]
I think you need a report_role table between them with report_id and role_id fields as many to many relationship. Which means report may belong to many roles or a role may have many reports. Once you know the role_id or name (e.g id of CEO) you can retreive those reports that belongs to CEO:
$role = App\Role::where('name', 'CEO')->get();
foreach ($role->reports as $report) {
    //
}
That way you can only retrieve and show the corresponding data to the related roles.

**Comment by naknode** [comment]
Yeah, a pivot table. Exactly what I was thinking. Roles can have many reports to view and reports can have many roles to allow it.

**Comment by AlexVanderbist** [comment]
Pivot table to support a many-to-many relationship between roles and reports sounds about right. [Laravel docs](https://laravel.com/docs/5.5/eloquent-relationships#many-to-many) are pretty good at explaining this as well as this [cheat sheet](https://hackernoon.com/eloquent-relationships-cheat-sheet-5155498c209#4204).

If you need any more help, let us know. Good luck!

**Comment by naknode** [comment]
I was able to get it once I did a full read-through the documents you just listed hours after I posted that comment! Thank you nonetheless. Great library!
