### ISSUE TITLE
Check for existing relations before assigning roles or giving permissions

### ISSUE THREAD

**Issue by curtisblackwell** [spatie/laravel-permission#558]
I run into errors about duplicates frequently enough to annoy me.

Would a PR that checks for existing relations before attempting to create one be welcome, or is that something better handled in my app?

**Comment by drbyte** [comment]
PR #545 is attempting to avoid errors for already-assigned roles/permissions.

In the case of errors creating duplicate permissions/roles, you could catch `PermissionAlreadyExists` and `RoleAlreadyExists` in your code.

**Comment by curtisblackwell** [comment]
Ah, right. Duh. Thanks.
