### ISSUE TITLE
Check if a role has a permission

### ISSUE THREAD

**Issue by baaskoen** [spatie/laravel-permission#56]
Is it possible to check if a role has a specific permission?

For example, I want to display all roles and all its permissions. What I'm doing now is just:

```
        foreach (Role::all() as $role) {
           $permissions = $role->permissions);
           // Etc..
        }
```

But I'm looking for something like:

```
        foreach (Role::all() as $role) {
            dd($role->can('view-user')); // Example
        }
```

**Comment by freekmurze** [comment]
As it stands that's the only way to do this. I'd accept a PR that adds a `hasPermission`-function to the `Role` model.
