### ISSUE TITLE
User tables not created

### ISSUE THREAD

**Issue by calder12** [spatie/laravel-permission#561]
Excuse me if I'm just missing something. After installing this in a test project and checking my tables it isn't creating the join tables. This tutorial, quoted in the read me, suggests it should https://scotch.io/tutorials/user-authorization-in-laravel-54-with-spatie-laravel-permission

When I check the code that creates the tables there is no mention of user join tables there either.

What am I missing here?

For the record I ran artisan make:auth before running the migrations for laravel-permission, but I can't see how that is the issue because there is no migration code that I can find to make those join tables.

**Comment by AlexVanderbist** [comment]
Hi,

The `user_has_roles` and `user_has_permissions` tables were used in v1 of the package. They've been replaced in v2 by `model_has_permissions` and `model_has_roles` to support permissions for multiple guards.

Hopefully this clears some things up! Let me know if you need any more help :)

**Comment by piep14** [comment]
Bonjour,

J'ai le même souci et je ne sais pas ce que je dois modifier. Dans mon fichier de config/permission.php, j'ai bien les nouvelles données : 

'model_has_roles' => 'model_has_roles',
'model_has_permissions' => 'model_has_permissions',
'role_has_permissions' => 'role_has_permissions',

L'erreur est la suivante : 

Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hps_bdd.user_has_roles' doesn't exist (SQL: select `name` from `roles` inner join `user_has_roles` on `roles`.`id` = `user_has_roles`.`role_id` where `user_has_roles`.`user_id` = 302) in ..../vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

Merci de votre aide.

**Comment by drbyte** [comment]
The tables mentioned in the error message are from v1.

You are using a v2 `config/permission.php` 
I'm guessing you also have a v1 `config/laravel-permission.php`

This package has 2 versions: v1 for older Laravel. v2 for latest Laravel

v1 and v2 are not compatible with each other. And there is no "upgrade" path from v1 to v2.

**Comment by piep14** [comment]
Pourtant ça marche sur mon local. Je ne comprend pas ce que je dois faire pour que ça fonctionne correctement :(
