### ISSUE TITLE
Exceptions don't set the correct status code when requesting JSON

### ISSUE THREAD

**Issue by benjamincrozat** [spatie/laravel-permission#563]
Hello,

For instance, in the context of testing, on a route that is protected with the "permission" middleware. When making a classic HTTP request, everything's fine. But when I request JSON, the status code isn't correctly sent. I don't really understand how all this work, so if somebody could help me figure out why, that'll be awesome! (I'm using laravel-permission on Lumen.)

```php
// routes/web.php

$router->get('/products', 'ProductsController@index');
```

```php
// ProductsController.php

class ProductsController extends \App\Http\Controllers\Controller
{
    function __construct()
    {
        $this->middleware('permission:manage products');
    }
}
```

```php
// ProductsControllerTest.php

$this->json('GET', '/api/v1/products')
    ->seeStatusCode(403); // Red, I'm getting 200, even if the JSON contains the proper error.

$this->call('GET', '/api/v1/products');
$this->assertResponseStatus(403); // Green!
```

**Comment by benjamincrozat** [comment]
Ok nevermind, I messed up my Exceptions Handler.

```php
// app/Exceptions/Handler.php

/**
 * Render an exception into an HTTP response.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  \Exception  $e
 * @return \Illuminate\Http\Response
 */
public function render($request, Exception $e)
{
    if (!method_exists($e, 'getStatusCode') || !$request->wantsJson()) {
        return parent::render($request, $e);
    }

    return response()->json([
        'error' => $e->getStatusCode(),
        'message' => $e->getMessage(),
    ], $e->getStatusCode());
}
```

**Comment by harish444** [comment]
/ app/Exceptions/Handler.php

/**
 * Render an exception into an HTTP response.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  \Exception  $e
 * @return \Illuminate\Http\Response
 */
public function render($request, Exception $e)
{

// retrive error code from exception object
     $errorcode=$e->status;
    ......................  
   ......................
}
