### ISSUE TITLE
Return type does not allow Collection, and 'guard_name' condition uses "whereId" instead of "whereIn"

### ISSUE THREAD

**Issue by artissant** [spatie/laravel-permission#572]
https://github.com/spatie/laravel-permission/blob/03eb748141432b5d94eb1613b99f818aac1f5070/src/Traits/HasPermissions.php#L73

HasPermissions::getStoredPermission supports multiple permissions as an input, but is tied to a single permission for the return type.

Also, if $permissions is an array, there's a call to "whereId" instead of "whereIn", which I'm pretty sure is generating an invalid query:

Original query:
```sql
select * from `permissions` where `name` in ("test-permission") and `id` = "guard_name";`
```

Updated query:
```sql
select * from `permissions` where `name` in ("test-permission") and `guard_name` in ("web");
```

I've prepared [a fix](https://github.com/artissant/laravel-permission/tree/feature/give-and-revoke-multi-permissions) but thought I'd create an issue before making a pull request. This _shouldn't_ introduce any breaking changes because passing an array/Collection to revokePermissionTo would currently trigger an error.

**Comment by AlexVanderbist** [comment]
Thanks for the PR! Let's continue this issue in there
