### ISSUE TITLE
how to get all users belong to same role?

### ISSUE THREAD

**Issue by phpforlan** [spatie/laravel-permission#575]
hi,
   i meet some trouble, now i want to query all users of superAdmin, 

roleName = 'superAdmin', so what should I do ?

**Comment by hrabbit** [comment]
Not directly in the document but is in the source.

```
$superAdmin = Role::findByName('superAdmin');
dd($superAdmin->users);
```

Of course, that's a Collection so things like...
```
$superAdmin->users->each(function($user)
{
    dd($user->name);
});
```

Behave nicely too. :)

**Comment by jhourlad** [comment]
Anything Eloquent instead of Collection?
