### ISSUE TITLE
[Request] Customized permissions callbacks

### ISSUE THREAD

**Issue by syedabuthahirm** [spatie/laravel-permission#578]
I Would like to extend my permission to do specific things.

Example
I have Admin and Client role.
Admin and Client has create_projects,edit_projects,delete_projects permissions.
Now client has permission to edit all projects but i would like to gave permission to edit their own projects not everyone.

Now i had two steps verification in my controller like below
```php
function edit(Project $project) {
  $project->load('client');
  $user = request()->user();
  if(  $user->can('edit_projects') && ( $user->hasRole('Admin') || ( $project->client->id === $user->id ) ) {
    // code to show edit form
  }
}
```
and really i hate this approach. Now i came up with idea to solve this problem. But, I don't know how to implement.

This package build on top on [Laravel Gate](https://laravel.com/docs/5.5/authorization#writing-gates) i browsed this source code and found [Permission Register Function](https://github.com/spatie/laravel-permission/blob/master/src/PermissionRegistrar.php#L29) this gate callback.

i would like to implement this callback with my custom class like `PermissionPolicy.php`
if i have method in `PermissionPolicy@edit_projects` i would like to attach this functionality rather then default callback. It's Possible..??

**Comment by syedabuthahirm** [comment]
Here is my implementation.
```php
    /**
     * Check the permission has corresponding policy callback
     *
     * @param string $ability
     * @return mixed
     */
    public function checkPolicyMethod($ability) {
        foreach( $this->gate->policies() as $model => $policy ) {
            if( method_exists( $policy,$ability ) ) {
                return $policy;
            }
        }
        return false;
    }

    public function registerPermissions(): bool
    {
       // new one 
       // it uses the Gate core define method to register all of my permissoins to respective policies.
        foreach($this->getPermissions() as $permission) {
            $ability = $permission->name;
            // here we check the policy method 
            if( $policy = $this->checkPolicyMethod( $ability ) ) {
                $this->gate->define( $ability, $policy . '@' . $ability );
            } else { // default callback 
                $this->gate->define( $ability, function(Authenticatable $user) use($ability){
                    return $user->hasPermissionTo($ability) ?: null;
                });
            }
        }

       // old code
        // $this->gate->before(function (Authenticatable $user, string $ability) {
        //     try {
        //         if (method_exists($user, 'hasPermissionTo')) {
        //             return $user->hasPermissionTo($ability) ?: null;
        //         }
        //     } catch (PermissionDoesNotExist $e) {
        //     }
        // });

        return true;
    }
```

**Comment by AlexVanderbist** [comment]
Hi @syedabuthahirm 

If I recall correctly you can simply call `$this->gate->before()` a second time in your own service provider to chain on your own callback. 

Check out the comment and the implementation in Laravel's code [here](https://github.com/laravel/framework/blob/ac7eee2a13beb53b4806d1fb830f49dbf40df30c/src/Illuminate/Auth/Access/Gate.php#L290).

Let me know if this is what you're after :)

**Comment by syedabuthahirm** [comment]
After creating a separate service provider for my own callbacks everything works great. but i am not sure this is best solution. please take a look my code @AlexVanderbist. if you have any suggestion please let me know :)

CustomAuthorizationCallbacks.Php
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Spatie\Permission\Models\Permission;
use Illuminate\Contracts\Auth\Access\Gate;

class CustomAuthorizationCallbacks extends ServiceProvider
{
    /** @var \Illuminate\Contracts\Auth\Access\Gate */
    protected $gate;

    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot(Gate $gate)
    {
        $this->gate = $gate;
        $this->registerCustomCallbacks();
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        
    }

    /**
     * Check the permission has corresponding policy callback
     *
     * @param string $ability
     * @return mixed
     */
    public function checkPolicyMethod($ability) {
        foreach( $this->gate->policies() as $model => $policy ) {
            if( method_exists( $policy,$ability ) ) {
                return $policy;
            }
        }
        return false;
    }

    public function registerCustomCallbacks()
    {
        $permissions = app(Permission::class)->all();
        foreach($permissions as $permission) {
            $ability = $permission->name;
            try {
                if( $policy = $this->checkPolicyMethod( $ability ) ) {
                    $this->gate->define( $ability, $policy . '@' . $ability );
                }
            } catch (PermissionDoesNotExist $e) {
            }
        }
    }
}

```

**Comment by AlexVanderbist** [comment]
Hm, I see.

Would it be possible to create standard Laravel policy called `ProjectPolicy` that does something like this?

```php
class ProjectPolicy
{    
    public function update(User $user, Project $project)
    {
        return $user->can('edit_projects') || $project->client->id === $user->id;
    }
}
```

In your controller you could then simply do `$this->authorize('update', $project)`.

That feels like the easiest laravel-way to solve this issue...

**Comment by LastDragon-ru** [comment]
For laravel 5.5.*, but it has one difference from current behavior:
* Current: If `hasPermissionTo() == false`, callback will return `null`
* New: If `hasPermissionTo() == false` callback will return `false`

```php
    public function registerPermissions(): bool {
        $this->gate->before(function (Authenticatable $user, string $ability, array $arguments) {
            try {
                if (method_exists($user, 'hasPermissionTo')) {
                    $hasGate       = $this->gate->has($ability);
                    $hasPolicy     = isset($arguments[0])
                        && $this->gate->getPolicyFor($arguments[0]);
                    $hasPermission = $user->hasPermissionTo($ability);

                    return $hasGate || $hasPolicy
                        ? ($hasPermission ? null : false)
                        : true;
                }
            } catch (PermissionDoesNotExist $e) {
            }
        });

        return true;
    }
```

**Comment by drbyte** [comment]
Thanks to Joseph Silber Laravel 5.7 will allow registering as a Gate `after` callback, which will resolve much of this complication.

That said, for 5.5 and 5.6, I like the proposed code posted by @LastDragon-ru because it links up well with Laravel conventions for Policy method names and retains normal Gate behavior.

However, with it the [Spatie\Permission\Test\GateTest::it_allows_other_gate_before_callbacks_to_run ... test](https://github.com/spatie/laravel-permission/blame/master/tests/GateTest.php#L15-L26) is failing.

**Comment by drbyte** [comment]
Update: for v3 we are leaning towards `Gate::after` for L5.7
