### ISSUE TITLE
Please Add Additional Method...

### ISSUE THREAD

**Issue by santiagazo** [spatie/laravel-permission#58]
I love this package!!! We use it all through out our sites. Having said that, there is one functionality that I haven't been able to find but desperately needed... so I added it to my files but would greatly appreciate if any new releases included this in the HasPermissions.php file...

    /**
     * Determine if the role has (one of) the given permission(s).
     *
     * @param string|array|Permission|\Illuminate\Support\Collection $roles
     *
     * @return bool
     */
    public function hasPermission($permissions)
    {
        if (is_string($permissions)) {
            return $this->permissions->contains('name', $permissions);
        }

        if ($permissions instanceof Permission) {
            return $this->permissions->contains('id', $permissions->id);
        }

        if (is_array($permissions)) {
            foreach ($permissions as $permission) {
                if ($this->hasPermission($permission)) {
                    return true;
                }
            }

            return false;
        }

        return (bool) $permissions->intersect($this->permissions)->count();
    }

PS. If this functionality exists and I just haven't found it please let me know so that I can use this better.

Cheers,
Jay

**Comment by freekmurze** [comment]
I'm glad you like the package! :smile: 

I'm thinking that you should always check if a user has a certain permission. This can be done with Laravel's native `can` function. If you want to loop through the permissions a certain role has, just use the  relation on the model.
