### ISSUE TITLE
Cache not working?

### ISSUE THREAD

**Issue by Develeapment** [spatie/laravel-permission#580]
Hi there,

I am using this lib for a while, but noticed today cache doesn't seem to be working on both development and production. On every page load it runs the query: 

```sql
select `roles`.*, `model_has_roles`.`model_id` as `pivot_model_id`, `model_has_roles`.`role_id` as `pivot_role_id` 
from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` 
where `model_has_roles`.`model_id` = '17' 
and `model_has_roles`.`model_type` = 'App\User'
```

What is it, i could be doing wrong?
I have set the app/config prefix as well as the app_name is unique from other projects.

Thanks in advance,
Robbert

**Comment by AlexVanderbist** [comment]
Hi @Develeapment 

This is actually working as intended. The query you've posted retrieves the permissions for a specific user. We only cache a collection of all permissions – not their related models.

Hopefully this answers your question. If you need any more help, let me know :)

**Comment by Develeapment** [comment]
Ok that might be my misinterpretation, thanks for clarifying!

**Comment by samfrjn11** [comment]
@AlexVanderbist what's the purpose of only caching a collection of all permissions? Could you give me an example where it shows the advantage of the caching you're talking about?

**Comment by Audit-a-la-Carte** [comment]
Hi @AlexVanderbist no specific reason, just noticed a request for every call. If your website has heavy load, you'd like to reduce the amount of queries in general. Caching the permissions per user for just 1 min could save a lot ;)

**Comment by Nowi5** [comment]
I agree, users permission does not change such often and can be cached, sometimes for longer time. Is there any development ongoing to improve that behavior. I have for each page load 2 sql queries which run both for ~480μs. Not such bad but can be still improved by total caching.
