### ISSUE TITLE
Add scopeWithoutPermission scope to the HasRoles trait

### ISSUE THREAD

**Issue by Mechazawa** [spatie/laravel-permission#581]
Allowing to filter on users that do not have a certain permission allows us to filter out users with a certain permission. This could be achieved by adding the scope `scopeWithoutPermission` to the trait `HasRoles`.

**Comment by AlexVanderbist** [comment]
Thanks for the suggestion! Feel free to make a PR for this. 

For now you could also do something like this:

```php
$usersWithoutPermission = User::whereDoesntHave('permissions', function ($query) {
    $query->where('name', 'permission name');
})->get();
```
