### ISSUE TITLE
Lumen install issue

### ISSUE THREAD

**Issue by RostyslavSh** [spatie/laravel-permission#585]
Please swap those lines 
`$app->register(Spatie\Permission\PermissionServiceProvider::class);`
`$app->configure('permission');`
in documentation for Lumen because it won`t resolve interfaces.

**Comment by ultrasamad** [comment]
In the installation instructions for lumen, when I tried running the `php artisan migrate` I get back this error.
```
In Migrator.php line 417:

  Class '' not found
```

Swapping the lines didn't solve it.

**Comment by drbyte** [comment]
Question from @ultrasamad answered in #602.

**Comment by drbyte** [comment]
@benjamincrozat any thoughts on this?

**Comment by benjamincrozat** [comment]
Yep, that's fixed in my PR. You should always register config files before the provider.

**Comment by drbyte** [comment]
👍
