### ISSUE TITLE
Define model based on role

### ISSUE THREAD

**Issue by jacobsyentl** [spatie/laravel-permission#588]
Love this package, but I have a question about using this package in the boot() of a model.

I have a table where I save users. Users can either be a student, teacher, headmaster or a combination of this, I make use of roles to achieve this.

I provide specific models for students, teachers and headmasters with their own queries and so on, but I don't have specific tables for these models.

Currently I determine if a user is a teacher by using the boot() function in the Teacher model:

```php
protected static function boot()
    {
        parent::boot();

        //Todo: make use of role package to determine if model is teacher or not.
        static::addGlobalScope('teacher', function (Builder $builder) {
            $builder->whereExists(function ($query) {
                $query->select(DB::raw(1))
                    ->from('teacher_offering')
                    ->whereRaw('teacher_offering.user_id = users.id');
            });
        });
    }
```

My questions is if I can replace the query inside the boot() function by checking if the teacher role is assigned to the user?

Can I achieve this with this package or should I stay with this query?

**Comment by drbyte** [comment]
Assuming the Teacher model extends the User model and the User model has the HasRoles trait applied, then the `role('rolename')` scope already exists, which you could leverage, even if your query needs to also still join to another table to match teacher with a specific class, etc.

You'd then also have additional available methods like `$user->hasRole('teacher')`.

**Comment by blogui91** [comment]
@drbyte It makes sense, but not working :/

I have a Progenitor which extends User, Progenitor has the following code:

```
/**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('parent', function (Builder $builder) {
             // Option 1
            $builder->role('parent');
             // Option 2
            $builder->whereHas('roles', function ($query) {
                $query->where('name', 'parent');
            });
        });
    }
```
this is the sql generated:

```
select * from `users` 
where exists (
select * from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `users`.`id
` = `model_has_roles`.`model_id` and `model_has_roles`.`model_type` = ? and (`roles`.`id` = ?))
```
`Progenitor`
It seems to be working correctly but it returns an empty collection [], 
I did the query in User model using `User::role('parent')` and it works :s 

Do you have any idea about this issue? 

Thank you :)
