### ISSUE TITLE
How to do get user collection together with roles?

### ISSUE THREAD

**Issue by exzib** [spatie/laravel-permission#589]
I am currently creating a user list for my admin panel and I get the current user list this:

`      $users = User::where('username', 'like', "%$search%")->orWhere('email', 'like', "%$search%")->selectRaw($selects)->orderBy($field, $sort)->paginate($perpage, ['*'], 'page', $page);
`

How can I pass along the users roles to the collection I get returned?

Appreciate any help.

**Comment by syedabuthahirm** [comment]
Add `with('roles')` in your code like below

$users = User::with('roles')->where('username', 'like', "%$search%")->orWhere('email', 'like', "%$search%")->selectRaw($selects)->orderBy($field, $sort)->paginate($perpage, ['*'], 'page', $page);
