### ISSUE TITLE
Slugs

### ISSUE THREAD

**Issue by santiagazo** [spatie/laravel-permission#59]
Also, If you made it so that we have slugs that would be awesome! I have found a few situations where I've been using ajax requests with these and slugs are mandatory for me. Not a massive pain to convert these to slugs and then back out of slug every time but, it's an extra step that could be quite automated.

Thanks again for the awesome package!

**Comment by freekmurze** [comment]
I don't see generating slugs as a core responsability of the package. So if you need this, implement it in your application logic.
