### ISSUE TITLE
There is no permission named `edit articles` for guard `web`.

### ISSUE THREAD

**Issue by jacktyler2318** [spatie/laravel-permission#590]
I am having issue when seeding the roles and permissions. I even copy their sample on database seeding here https://github.com/spatie/laravel-permission#database-seeding. I even clear and removed cache before seeding and still I get that error as you can see on this screenshot https://www.screencast.com/t/PAMOsZjS

Anyone could help?

Thank you.

**Comment by kwen8** [comment]
maybe you are using different guard, can you show your config/auth.php?

**Comment by jacktyler2318** [comment]
Hi kwen8,

Thank you for your response. I am only using web guard. Anyway, I have fixed by reinstalling laravel again. It looks like a cache issue that does not clear even if I cleared it. 

We can close this thread now and thanks again for your time.

**Comment by kwen8** [comment]
I have read the source code, i found that in HasPermission.php in line 117

```php
protected function getDefaultGuardName(): string
    {
        $default = config('auth.defaults.guard');

        return $this->getGuardNames()->first() ?: $default;
    }
```
I think it's a bug because when i use Role('admin') which guard is api, it always use web guard

so i see auth.php 

```php
    'guards' => [
		'web' => [
			'driver' => 'session',
			'provider' => 'users',
		],
		'api' => [
			'driver' => 'jwt',
			'provider' => 'users',
		],
    ],
```
so when i try getDefaultGuardName, i will always get web guard because it's in first position, so i try 

```php
    'guards' => [
		'api' => [
			'driver' => 'jwt',
			'provider' => 'users',
		],
		'web' => [
			'driver' => 'session',
			'provider' => 'users',
		],
    ],
```
then it fix my problem.

i think it's a bug

**Comment by luckyrabbitllc** [comment]
I too just ran into this issue on Laravel 5.5. Trying to use this package on both api and web guards, but the check always returns results for the web guard, even when 'api' is specified like so:

`$role->hasPermissionTo('browse feeds', 'web')`

**Comment by drbyte** [comment]
Mind trying this code edit, and posting your results?
https://github.com/spatie/laravel-permission/pull/587/files

**Comment by agrove91** [comment]
adding Artisan::call('cache:clear'); didn't seem to work for me.

**Comment by drbyte** [comment]
@agrove91 wrote:
> adding Artisan::call('cache:clear'); didn't seem to work for me.

Sorry, your post doesn't contain any of the information needed in order to be of assistance to you. 
If you're having a problem, please post your code for your model, your seeders, and your routes ... in a NEW issue.

**Comment by agrove91** [comment]
Apologies. I realize that wasn't very helpful. I found it was due to manipulation of the database so doing `php artisan cache:forget spatie.permission.cache` then `php artisan cache:clear` worked

**Comment by drbyte** [comment]
Ok.

Tip: The `cache:clear` is equivalent to `forget` on all keys ... so you only need one or the other, not both.

**Comment by steveleblanc** [comment]
I was able to fix mine by deleting the users in the database then registering a new admin user again

**Comment by javiertoledos** [comment]
I got the same bug as @kwen8. I'm using laravel 5.6 with JWT and api guard.

**Comment by lithium-li** [comment]
i got the same bug as @kwen8 too. i set guard name in App/User then it fix my problem.

```php
class User extends Authenticatable
{
    protected $guard_name = 'api';
    ...
}
```

**Comment by eyaylagul** [comment]
i change guard_name to 'api' for role and permission model, but role always insert with 'web' value.

**Comment by drbyte** [comment]
> i change guard_name to 'api' for role and permission model, but role always insert with 'web' value.

You need to set it on your user model ... ie: the one you are assigning the role/permission "to".

**Comment by imajkumar** [comment]
`php artisan cache:clear`
`php artisan config:clear`
works for me 
great!!

**Comment by eyaylagul** [comment]
i tried clear commands but not work. Then i decided use v3 branch. Thanks for replies.

**Comment by drbyte** [comment]
@eyaylagul the `v3` branch isn't stable yet. Its goal is to remove these guard-related problems, but it's not ready for use yet.
You could use `v1` if you have only a single User model.

**Comment by lastrafda** [comment]
I had the same problem running tests (using V3), Calling `\Artisan::call("cache:clear");` on my setUp() method did the trick for me. I'm sure there is a better way to solve this :thinking:

**Comment by drbyte** [comment]
> I had the same problem running tests (using V3), Calling `\Artisan::call("cache:clear");` on my setUp() method did the trick for me. I'm sure there is a better way to solve this 🤔

Yes. It's explained in the docs:
https://docs.spatie.be/laravel-permission/v3/advanced-usage/unit-testing/
https://docs.spatie.be/laravel-permission/v3/advanced-usage/seeding/

**Comment by lastrafda** [comment]
I already tried those

**Comment by drbyte** [comment]
You said using the generic `cache:clear` works. 
You didn't mention whether calling `permission:cache-reset` worked. It calls ` app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions()` internally, which is what the doc links I mentioned above refer to. If that's not working, then it would seem your app isn't resolving the registrar properly, or somehow has a mismatch with cache key configurations, or is using a caching system that this package doesn't support.

But posting "I had the same problem" to an issue thread started 3 years ago, and not providing any context really isn't a useful way to ask for support. 

If you want assistance with this post the exact steps required to create your problem on a brand new Laravel app with this package installed, using one of Laravel's default caching drivers. With those steps I'm sure we can identify where the problem is for your situation.

**Comment by seongbae** [comment]
Tried everything in this thread but the only thing that worked for me was also \Artisan::call("cache:clear");

**Comment by myckhel** [comment]
Restarting the queue solved my problem.

**Comment by vicentemachado** [comment]
running "php artisan permission:cache-reset" solved my problem.

**Comment by matinwd** [comment]
I am facing same problem but in my case when i set default guard name to api and when i try to give permissions to a user it says
`There is no [permission] with id `100` for guard `web`.`
and when i set default guard name to web and when i try to give permissions to a role it says
`There is no [permission] with id `100` for guard `api`.`

any idea?

**Comment by Kenneth94ms** [comment]
In my case, i work in a laravel project and I create a new permissions and roles, but artisan don´t recognize new user, then you need use php artisan cache:clear

**Comment by developermwangimuthui** [comment]
This worked for me 
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();

$role->permissions()->sync($request->input('permission'));

**Comment by saeid13623** [comment]
Empty the role and permission tables in the database and then fill in the tables again. I had this error and I fixed it this way

**Comment by Farouz** [comment]
i'm using spatie for admin table and jwt for  users table and the spatie read from web not its guard admin how to fix that so also jwt works to users

**Comment by rodrigorhas** [comment]
Double check if have created the permission before assign it to a role, that was my case

**Comment by kanarskyiartem93** [comment]
Have a same problem, resolve when remove trait WithoutModelEvents in Seeder

**Comment by qzmenko** [comment]
You can just add:
`app()[PermissionRegistrar::class]->forgetCachedPermissions();`
after creating permissions.

It will work even if trait WithoutModelEvents used.

**Comment by sosmongare** [comment]
> This worked for me $role = Role::find($id); $role->name = $request->input('name'); $role->save();
> 
> $role->permissions()->sync($request->input('permission'));

This worked for me

**Comment by andraryandra** [comment]
> This worked for me $role = Role::find($id); $role->name = $request->input('name'); $role->save();
> 
> $role->permissions()->sync($request->input('permission'));

Thanks dude, this worked.
