### ISSUE TITLE
Roles WhereHas Permissions endpoint

### ISSUE THREAD

**Issue by ayimdomnic** [spatie/laravel-permission#592]
Hey Thanks for this amazing package!
I am building an API with a Complex ACL implementation, ah enough. the question
How best would you advise I implement a simple "normal" Eloquent Implementation of  ``$roles->whereHas('permissions');``

Thank you

**Comment by drbyte** [comment]
The `Role` model has a `permissions` property/relationship.

So you could retrieve `Role::with('permissions')->all()`, which gives you a collection, and then iterate through each role and its permissions (also a collection) to reduce down to just the combinations you're seeking.

**Comment by introwit** [comment]
I would do what @drbyte said :) I think that solves your issue. Reopen if it's still not what you were looking for.
