### ISSUE TITLE
Why send through permission array and discard it

### ISSUE THREAD

**Issue by Jigsaw5279** [spatie/laravel-permission#593]
When an UnauthorizedException is raised, the array of requested permissions or roles is sent trough.

However, in the Exception class itself that parameter is discarded completely.
Is there any specific reason for that?

    public static function forPermissions(array $permissions): self
    {
        return new static(403, 'User does not have the right permissions.', null, []);
    }

**Comment by drbyte** [comment]
I think that's a question for @AlexVanderbist 

Alex, was this intentional?

**Comment by drbyte** [comment]
Ref #526 and #517

**Comment by flashadvocate** [comment]
Seems like it'd be useful for debugging if it was included in the output

**Comment by drbyte** [comment]
A PR is welcome.

**Comment by AlexVanderbist** [comment]
>Seems like it'd be useful for debugging if it was included in the output

That was the case. The exception message used to be something along the lines of "User does not have the right permissions. Necessary permissions are ..." but I left that out because it felt like it was exposing too much information.

Wouldn't mind having that in there again tho :)

**Comment by benyanke** [comment]
That seems like a feature that would be useful `if(config('app.debug'))`. Or perhaps as it's own config.

**Comment by benyanke** [comment]
PR written above.

**Comment by Jigsaw5279** [comment]
Resolved in #629
