### ISSUE TITLE
Why table did not set auto increment id 

### ISSUE THREAD

**Issue by maxca** [spatie/laravel-permission#596]

**Comment by drbyte** [comment]
The tables created by this package's [migration](https://github.com/spatie/laravel-permission/blob/master/database/migrations/create_permission_tables.php.stub) do have auto-increment id fields where needed. Other tables have a hybrid primary key across multiple fields, so there is no added value in having an auto-increment field in those cases.

**Comment by maxca** [comment]
Thank you.
