### ISSUE TITLE
Installation issue with Lumen

### ISSUE THREAD

**Issue by ultrasamad** [spatie/laravel-permission#602]
In the installation instructions for lumen, when I tried running the `php artisan migrate` I get back this error.
```
In Migrator.php line 417:

  Class '' not found
```

**Comment by drbyte** [comment]
Judging from your other posts  that you added to #383 and #591 I'm guessing you resolved this matter?

**Comment by drbyte** [comment]
Okay, I found the issue: just need to rename the migration file to have the date/time prefix. For example: `2017_12_26_020418_create_permission_tables.php`
