### ISSUE TITLE
Lumen 5.5: Class role does not exist (line 109) in Container.php (line 752)

### ISSUE THREAD

**Issue by ultrasamad** [spatie/laravel-permission#607]
When I add a middleware to my route, I get `Class role does not exist (line 109) in Container.php (line 752)` anytime I tried executing that route.

This is how I added the middleware `[ 'middleware' => ['role:writer']` just from the docs.
My `bootstrap/app.php` has these lines
```
$app->configure('permission');
$app->register(Spatie\Permission\PermissionServiceProvider::class);
```

**Comment by drbyte** [comment]
@benjamincrozat curious if you have any comment for this situation.

**Comment by benjamincrozat** [comment]
Just updated the documentation. Indeed, I forgot to mention to register the middlewares. My bad.

**Comment by drbyte** [comment]
Thanks!
