### ISSUE TITLE
Role doesn't exist when doing phpunit tests

### ISSUE THREAD

**Issue by readergirltracey** [spatie/laravel-permission#608]
I'm using laravel - 5.5 and laravel-permission - ^2.7

```php
use DatabaseMigrations;

	public function setUp()
	{
		parent::setUp();

		$this->artisan("db:seed", ['--class' => 'PermissionSeeder']);

		$this->app->make(PermissionRegistrar::class)->registerPermissions();
	}

	/** @test*/
    public function it_can_retrieve_roles_and_permissions()
    {
		$user = factory(User::class)->create();
    	$user->assignRole("Admin");
...
```

See my code above when i run this I get Spatie\Permission\Exceptions\RoleDoesNotExist : There is no role named `Admin`.
If i do ```dd(Role::all)``` i see all the roles

Any suggestions for fixing this?
Thanks in advanced

**Comment by drbyte** [comment]
Per the README: https://github.com/spatie/laravel-permission#database-seeding you'll want to reset the cached data when seeding your tests using `app()['cache']->forget('spatie.permission.cache')`

**Comment by readergirltracey** [comment]
@drbyte That does not work

**Comment by drbyte** [comment]
Some examples:

https://github.com/drbyte/spatie-permissions-demo/blob/master/tests/Feature/PostsTest.php

https://github.com/drbyte/spatie-permissions-demo/blob/master/tests/Feature/ExamplesTest.php

**Comment by readergirltracey** [comment]
when i download and run this test i get author does not exist
https://github.com/drbyte/spatie-permissions-demo/blob/master/tests/Feature/PostsTest.php

**Comment by readergirltracey** [comment]
I fixed it on my user class i added this line `protected $guard_name = 'api';`
I was using it in an api so it was created under **api** but when i was calling it is was calling it under **web**

Thanks for the help guys

**Comment by readergirltracey** [comment]
@drbyte is there anyway to set the guard to be api by default so i don't need to specify it?

**Comment by drbyte** [comment]
Are you using multiple guards in your application?

We're working on a possible update, based on how the default guard is calculated.  In the meantime you may find my description of "OLD BEHAVIOR" here to be helpful: https://github.com/spatie/laravel-permission/pull/587#issuecomment-353913215

**Comment by readergirltracey** [comment]
I fixed the authorization issue by setting my default auth guard to api

**Comment by eskiesirius** [comment]
im having this kind of problem in a_user_can_register_an_account function.. i created my own role but it cant find the role
