### ISSUE TITLE
method users doesn't exists.

### ISSUE THREAD

**Issue by yeligoth** [spatie/laravel-permission#609]
When I use the blade directives for check roles, an exception is fired.
"Method users doesn't exists"

My solution was check manually auth()->user()->hasRole('admin')

**Comment by drbyte** [comment]
`"Method users doesn't exists"` sounds like an application error, not something caused by this package.

**Comment by yeligoth** [comment]
I only use the package directives, the transpilation from @role is "auth()->users()"

**Comment by drbyte** [comment]
No, it's `auth()->user()->hasRole()`:
https://github.com/spatie/laravel-permission/blob/master/src/PermissionServiceProvider.php#L66

**Comment by yeligoth** [comment]
The solution was upgrade the package. In the version 2.0 the transpilation is bad.

Thanks...

**Comment by drbyte** [comment]
Thanks for confirming that the issue is resolved.
