### ISSUE TITLE
Names are not unique

### ISSUE THREAD

**Issue by danielsdeboer** [spatie/laravel-permission#61]
I'm wondering if there's a design rationale for the "name" columns to be non-unique? It doesn't really seem like you'd want multiple permissions & roles with the same name.

**Comment by freekmurze** [comment]
Nope, no rationale behind that. And you're right that permissions/roles should have unique names. I'd accept a PR that modifies the migration so that the names will be unique.

**Comment by danielsdeboer** [comment]
Thanks, done.

**Comment by eternalBlast** [comment]
Hello @danielsdeboer. The role name still can't be unique? I tested on my side because of same guard it causes an Exception.

**Comment by eternalBlast** [comment]
Is there any solution to override the function other than edit the Role model file because the library is in vendor folder. Thanks!

**Comment by drbyte** [comment]
> Is there any solution to override the function other than edit the Role model file because the library is in vendor folder? 

You can extend the original model in your app's namespace and override methods there.
