### ISSUE TITLE
Incomplete migration

### ISSUE THREAD

**Issue by otisz** [spatie/laravel-permission#610]
`use Illuminate\Support\Facades\Schema;` is missing from the published migration file.

**Comment by drbyte** [comment]
Thanks for pointing that out.

Did you run into actual PHP errors because of it? Or just an IDE complaint?

**Comment by otisz** [comment]
This is just a PhpStorm complaint, but I think it would be good if you would use it because the hints are useful.

**Comment by drbyte** [comment]
Agreed. 
I've updated the package. It will be included in the next tagged release.
Thanks for reaching out!

TIP: When creating Github Issues, please be sure your "Title" clearly explains what needs fixing. In this case "Incomplete Migration" isn't very descriptive. 
(You can click the Edit button to update it)

**Comment by otisz** [comment]
I agree with you about the title.
I'm sorry, but that was my first issue.
Updated title.

**Comment by drbyte** [comment]
No worries. Thanks for updating it!
And thanks for contributing!
