### ISSUE TITLE
[v1] Permissions randomly not working, works after logout and login

### ISSUE THREAD

**Issue by i906** [spatie/laravel-permission#617]
laravel: 5.3.31
laravel-permission: 1.14.1

After some digging, I discovered that after a user logs out, the `remember_token` in the User model is updated.

This would trigger the updated event (for the User model) and `forgetCachedPermissions` in the `RefreshesPermissionCache` trait would executed.

Since we have a lot of users logging in and out, perhaps the cache here would be unreliable and causing this issue.

**Comment by drbyte** [comment]
Can you please explain in more detail what the symptoms are with "permissions randomly not working", including specific error messages, etc.

**Comment by i906** [comment]
In my Blade views, I have several links to menus that appear according to permission granted to the user. E.g.:

```blade
<a>Dashboard</a>
@can(Permission::MANAGE_ITEM)
    <a>Items</a>
@endcan
@can(Permission::VIEW_REPORT)
    <a>Report</a>
@endcan
```

When a user with all permissions logs in, the Dashboard, Items, and Report should appear. Occasionally, they'll only see Dashboard. After logging out and relogin, the issue would go away for a while.

I made a workaround, and the users have not reported of this issue yet:

```php
// in AppServiceProvider
$this->app->bind(\Spatie\Permission\PermissionRegistrar::class, PermissionRegistrar::class);
```

```php
class PermissionRegistrar extends BaseRegistrar
{
    public function forgetCachedPermissions()
    {
        // Instead of clearing the cache, we just update the cache with a newer value
        $permissions = app(Permission::class)->with('roles')->get();
        $this->cache->forever($this->cacheKey, $permissions);
    }
}
```

I am using Redis as the cache driver.

**Comment by drbyte** [comment]
You're correct that the `remember_token` triggers the `saved` or `updated` event, which then triggers the cache flush ... which is thrashes the cache more than necessary. 

However, I'm not sure that we'll make changes to the v1 branch of this package to address that.

If one were to address it, one way could be to intercept the booted `updated` event and check for  `$user->timestamps == false` and skip the cache-flush in that isolated scenario.
