### ISSUE TITLE
There is no role named `admin` with 'api' guard.

### ISSUE THREAD

**Issue by webmasterdro** [spatie/laravel-permission#621]
Hello,

I decide to use your package for Roles & Permissions. But for some reason, it's not working here. When I try to assignRole to an user, turns out an Exception: `There is no role named `admin`.
`
- Laravel 5.5
- I added "HasRoles" trait in to User model
- $request->user()->assignRole('admin'); 

![xhq7oa16tcqo-wee713xiw](https://user-images.githubusercontent.com/16580745/34797223-e39e844e-f63e-11e7-91be-cd9ffec12f38.png)

I really don't understand why I'm getting this error. =/

**Comment by drbyte** [comment]
Your screenshot shows that you created those roles using guard_name of `api`.

What does your `config/auth.php` list as your default guard? If you're not using the `web` guard, does switching the order of guards (move `api` before `web`, or remove `web` altogether) in the config file resolve your problem?  See: https://github.com/laravel/laravel/blob/master/config/auth.php#L16-L48

**Comment by webmasterdro** [comment]
Hi,

Default guard is `api`.

**Comment by webmasterdro** [comment]
Hi again @drbyte

I follow your tip and comment the web guard. 

I got a new error: ``SQLSTATE[01000]: Warning: 1265 Data truncated for column 'model_id' at row 1 (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (931d5f40-f600-11e7-ad4d-bfb47746a32a, App\User, 1)) `
`

But this errors appears because I use uuid instead of sequencial IDs for users. I change `model_id` column to varchar(36) instead of int. Can I use without problems or will appears unexpected effects?

**Comment by drbyte** [comment]
This package hasn't been built to use UUIDs for the `model_id` relationship.

But, as you say, manually changing your schema to support the alternate field type will probably be enough.

**Comment by webmasterdro** [comment]
Sure.

Thanks!

**Comment by mfaisaltanveer** [comment]
```
class User extends Authenticatable 
{
//declare your guard name
    protected $guard_name = 'web';
```

**Comment by 0xcrypto** [comment]
Maybe this is old but if someone's using uuid and faces this error, here is the solution https://spatie.be/docs/laravel-permission/v3/advanced-usage/uuid
