### ISSUE TITLE
Default guard returns the wrong value

### ISSUE THREAD

**Issue by rwngallego** [spatie/laravel-permission#623]
If I use something like this in my **auth.php** config file:

```
    'defaults' => [
        'guard' => 'myguard',
        ...
    ],
...
    'guards' => [
        'web' => [
            'driver' => 'otherdriver',
            'provider' => 'users',
        ],

        'myguard' => [
            'driver' => 'mydriver',
            'provider' => 'users',
        ],
    ],
```

I expect that if I don't specify the guard, it's going to use the value from **config('auth.defaults.guard')** as the documentation states:

> By default the default guard (config('auth.defaults.guard')) will be used as the guard for new permissions and roles.

However this line of code is problematic because it's bringing the very first result from a collection without any criteria: https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasPermissions.php#L121

For the config above in the collection we have: **['web', 'myguard']** as both providers are set to the **'users'** provider, and the **HasPermissions::getGuardNames()** method returns **'web'**, which shall be **'myguard'** instead.

We should keep the **HasPermissions::getDefaultGuardName()** independent from the **HasPermissions::getGuardNames()** method in order to be consistent.

**Comment by drbyte** [comment]
PRs #587 and #622 propose to solve this. Which of those PRs works best to solve the problem with your application?

**Comment by drbyte** [comment]
Does today's 2.8.0 release help resolve this?

**Comment by drbyte** [comment]
Closing due to no response.
