### ISSUE TITLE
MongoDB compatible?

### ISSUE THREAD

**Issue by rkgarcia** [spatie/laravel-permission#624]
I try without success implemeting this using mongodb, somebody have information about that?

**Comment by mostafamaklad** [comment]
you could use this package [laravel-permission-mongodb](https://github.com/mostafamaklad/laravel-permission-mongodb/) if you are using [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) package.

**Comment by rkgarcia** [comment]
Thanks @mostafamaklad

**Comment by YahyaQandel** [comment]
@mostafamaklad i tried to use your package i got that error despite 
`   BadMethodCallException  Call to undefined method Jenssegers\Mongodb\Eloquent\Builder::hasRole().
`
my user model 

`
namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Jenssegers\Mongodb\Auth\User as Authable;
use Illuminate\Auth\Authenticatable;

use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Maklad\Permission\Traits\HasRoles;

class User extends Authable implements AuthenticatableContract, AuthorizableContract
{
    use HasApiTokens, HasFactory, Notifiable, Authorizable, HasRoles, Authenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guard_name = 'web'; // or whatever guard you want to use
    protected $connection = 'mongodb';
    protected $collection = 'users';
    `

**Comment by drbyte** [comment]
@YahyaQandel probably best to ask your questions directly in that package's github issues area.
(You didn't indicate what line of code was triggering the error you mentioned. It would help if you provided that detail.)

But in the meantime, a question for you. In the code you posted I see:
`use Jenssegers\Mongodb\Auth\User as Authable;`

Why not this instead?
`use Jenssegers\Mongodb\Eloquent\Model as Authable;`
