### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by kabelo38** [spatie/laravel-permission#625]
$ sudo composer require spatie/laravel-permission

                                                                                                                                                
  [Composer\Repository\RepositorySecurityException]                                                                                             
  The contents of http://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match   
  its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.      
                                                                                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by freekmurze** [comment]
This is not really an issue with this package but with Composer. Try again, and if it should fail again open up an issue at their repo.
