### ISSUE TITLE
Weird behavoiur with hasanyrole and else

### ISSUE THREAD

**Issue by Doublemedia** [spatie/laravel-permission#626]
Hello,

I have updated to the latest version.
We have the following check in an view:

    @hasanyrole(['mod', 'admin'])
        Hello admin
    @else
        Hello other people
    @endhasanyrole

This results in:

Parse error: syntax error, unexpected 'else' (T_ELSE), expecting end of file

When I look at the cached file I see this result:

    @hasanyrole(['mod', 'admin'])
        Hello admin
    <?php else: ?>
        Hello other people
    @endhasanyrole

When I change it in:

    @hasanyrole(['mod', 'admin'])
        Hello admin
    @endhasanyrole

It works fine.

Any other people that have experience with this?

Erwin

**Comment by drbyte** [comment]
In your example without the `@else`, what is the generated PHP in the cached/compiled view file?
And, does it actually "show nothing" for "other people"? Or does it output the `@hasanyrole...` literally?

**Comment by Doublemedia** [comment]
I can see the @hasanyrole tags in the source code. So it's not parsed by the PermissionServiceProvider blade compiler.

**Comment by AlexVanderbist** [comment]
Hi @Doublemedia 

I just gave this a test and it seems like you can't create the array inside of the directive. It has to be either a variable or a string (optionally using pipes).

In this case the easiest fix for you would be the string notation:
```blade
@hasanyrole('mod|admin')
    Hello admin
@else
    Hello other people
@endhasanyrole
```

Good luck!

**Comment by Doublemedia** [comment]
I have tested it with the pipes, but this results in the same error as before.
The parsed code in the cache is also the same as before.

The else is parsed, but the @hasanyrole isn't.

**Comment by Doublemedia** [comment]
$this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {

This is not executed. Debugging before this show the output. But in it doensn't.

**Comment by Doublemedia** [comment]
Solved. Cleaning cached fixed it. I though I did this already ...
