### ISSUE TITLE
redirect users base on their role

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-permission#632]
Hi,

I've added code below to my `LoginController` in order to redirect users after login base on their roles:

```php
protected function authenticated($request, $user){
        if($user->role('Admin')){
            return redirect('/admin/dashboard');
        } else {
            return redirect('/');
        }
    }
```

the problem is all users regardless to their roles will redirect to dashboard, I want only admins redirect there and the rest of users redirect to homepage.

any idea?

**Comment by drbyte** [comment]
Small change:

```diff
-        if($user->role('Admin')){
+        if($user->hasRole('Admin')){
```
