### ISSUE TITLE
Failure Setting direct permissions on users with no pemission initially

### ISSUE THREAD

**Issue by Aryan1** [spatie/laravel-permission#635]
I have been testing a laravel app. The problem is when I create a new user (one with no permissions or roles) and check for permissions, it returns false as it should but then I give a permission to the user, and check for it, it still says 'false'.
Now if I remove the `hasPermissionTo()`, it works fine

So far:
1. Checked with web routes.
2. Checked with few lower versions
3. and checked other issues for help

Code Example:
```
# Roles and permissions are already seeded

$user = User::find($id);    // No roles or permissions assigned
$user->hasPermissionTo('edit articles');     // False, as it should

#and now even if I assign 
$user->givePermissionTo('edit articles);

$user->hasPermissionTo('edit articles);      // Still, false
$user->permission->pluck('name'); //    Still empty

```
but when I remove the line `$user->hasPermissionTo('edit articles');` Everything works fine again

**Comment by drbyte** [comment]
This is a simple Eloquent in-memory object issue.  If you reload the relations it will give you the correct results.

After `$user->givePermissionTo()` you will need to run `$user = $user->fresh();` or `$user = User::find($id);`  to reload the relations. Then the `hasPermissionTo()` will reflect the changes.
