### ISSUE TITLE
Sometimes suddenly losing permissions

### ISSUE THREAD

**Issue by vanrijs** [spatie/laravel-permission#636]
Hi!

We use Spatie Permissions class for a couple of months now. Sometimes we suddenly lose our permissions and we get to see the permission does not exist view.
I asked my client to logout and login again but this wont fix it. I have to clear the cache (cache:clear) before they can login again.

In the config/cache i've set already a (unique) prefix.

Is there anything we can do or where do i need to start debugging?

Best regards,

Raymond

**Comment by drbyte** [comment]
>  I have to clear the cache (cache:clear) before they can login again.

I'm confused: This package doesn't do anything with preventing logins based on roles or permissions.

**Comment by drbyte** [comment]
Did you find out why your app is preventing logins?  What is the code that you've used to tie permissions into login capability?

**Comment by vanrijs** [comment]
Hi DrByte, is has nothing to do with the preventing logins. Suddenly the permissions are not available and the users get "no permission to view this page". We swiched last week from memcached to file caching. I know its slower but it works.. I will check the memcached settings later this week.
