### ISSUE TITLE
assignRole() not working

### ISSUE THREAD

**Issue by rafaelxim** [spatie/laravel-permission#639]
I'm trying to seed my **model_has_roles** table with a laravel seed. I have a **role** named cliente already create in roles table. 
When I run this seeder i get this error at cmd: 

> Integrity constraint violation: 1048 Column 'model_id' cannot be null

I don't know why this is not getting the model_id : 

>  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (, App\User, 5))

It's getting model_type, role_id. But not the model_id. If I comment the assignRole, the seeder run without errors.

This is the code at the seeder :
 
```
$user = new User ;
	         $user->name =  $faker->name ;
	         $user->email =  $faker->email ;
	         $user->password =  bcrypt('123456') ;
	         $user->assignRole('cliente');	
	         $cliente->user()->save($user) ;
```

Client and User are a morphMany relationship.

**Comment by rafaelxim** [comment]
Solved with this....I needed to assign AFTER querying for the user.

$user = User::orderBy('id', 'desc')->first();
$user->assignRole('cliente');

**Comment by drbyte** [comment]
Yes. Or at least `save()` the User first.
