### ISSUE TITLE
Laravel 5.6 Support plans

### ISSUE THREAD

**Issue by judahnator** [spatie/laravel-permission#647]
Hello friends!

What is the status of 5.6 support? I tried giving the 5.5->5.6 shift a shot, but discovered that this package was holding me back.

Is it just a matter of waiting for the official release? If not, what can I do to help get a dev version out the door for testing?

**Comment by drbyte** [comment]
The usual Spatie release pattern is to publish a release shortly after a new Laravel version is published.  Never before. 

If all goes well, I expect to see something either the same day or the next day after the Laravel release.

**Comment by drbyte** [comment]
Laravel 5.6 support is now added. See v2.9.0
