### ISSUE TITLE
Call to undefined method hasAnyRole()

### ISSUE THREAD

**Issue by secrethash** [spatie/laravel-permission#648]
### Error
 **"Call to undefined method Illuminate\Database\Query\Builder::hasAnyRole()"**
### Usage
I was using the `@hasanyrole` blade directive when this error arised. I have used the `getDirectPermissions()`, `getAllPermissions()`, etc and they all are working perfectly fine. I have the `HasRoles` Trait set in `App\User`.

**Comment by drbyte** [comment]
You have a `Query\Builder` object, not an `App\User` object. 

This usually occurs when you've swapped out the normal `App\User`, or the normal Laravel authentication infrastructure, for one provided by another package. 

For further help, please post the following:
- the code from the controller method that is calling your blade view
- the `__construct()` method from that controller
- the `route` definition that's leading to calling that controller method, including any middleware connected with that route definition
- your `App\User` code
- your `composer.json`
