### ISSUE TITLE
[Question] findOrCreate() for Roles

### ISSUE THREAD

**Issue by lguima** [spatie/laravel-permission#653]
Is there any reason for not having implemented the `findOrCreate()` for Roles?

**Comment by drbyte** [comment]
Hasn't been PR'd.

Although, I must ask: What's your "use case"?

**Comment by lguima** [comment]
I have a seeder class for permissions and roles. As I create a new permission I sync with the role already created or not.

**Comment by drbyte** [comment]
Are you comfortable submitting a pull request which includes the changes needed, and supporting tests?
