### ISSUE TITLE
Return value of Spatie\Permission\PermissionRegistrar::getPermissions() must be an instance of Illuminate\Support\Collection, boolean returned

### ISSUE THREAD

**Issue by Barzin73** [spatie/laravel-permission#654]
This site has been working for five months, But this problem happened suddenly.

Laravel 5.4
spatie/laravel-permission 2.3
Err : Return value of Spatie\Permission\PermissionRegistrar::getPermissions() must be an instance of Illuminate\Support\Collection, boolean returned

**Comment by drbyte** [comment]
> @Barzin73 wrote:
> This site has been working for five months, But this problem happened suddenly.

That's the sort of symptom that points to something being changed in your app or on your server.

**Comment by AlexVanderbist** [comment]
The only way I can see this happening if the cache has been invalidated or you've significantly changed the way `getPermissions()` works. If the cache is the issue (it usually is)`php artisan cache:clear` will probably fix it.
