### ISSUE TITLE
Revoking a Permission

### ISSUE THREAD

**Issue by JDBlackman** [spatie/laravel-permission#655]
## Error
I am trying to revoke a permission from a user, but does not work. 
The permission usually comes from the role, I am not revoking the role just the permission.

## Usage

`$user->revokePermissionTo('dj');`

**Comment by drbyte** [comment]
This package doesn't allow you to "subtract from a role" for a specific user. Only add.

If a user has a role that contains the permission to `dj`, then they have that permission.

If you want to give them "less" permissions, create a different role with fewer permissions.
