### ISSUE TITLE
I think we have to improve wiki - how to assign user to role

### ISSUE THREAD

**Issue by KalanaPerera** [spatie/laravel-permission#656]
Still I don't understand how to assign user to role. Could someone help me.

**Comment by KalanaPerera** [comment]
Finally I have found solution to assign user to role, 

Here is the solution: https://github.com/drbyte/spatie-permissions-demo/blob/master/database/seeds/PermissionsDemoSeeder.php

But now I have issue. 

The user to role permission not recorded in database right? Please explain.

**Comment by drbyte** [comment]
From the README:
`$user->assignRole('writer');`
... where $user is an `App\User` object, such as `$user = App\User::find(1);`
... and `'writer'` is the name of the role you created.

**Comment by KalanaPerera** [comment]
Above comment mistakenly removed. sorry for that. 

Actually, I got solution after going through your account. 


From here: https://github.com/drbyte/spatie-permissions-demo/blob/master/database/seeds/PermissionsDemoSeeder.php

I think we have to improve code samples ( Suggestion and I'll also help )

Anyway thanks for fast reply.

**Comment by rathesDot** [comment]
Was running in the same issue as well.
In the docs at [Using permissions via roles](https://github.com/spatie/laravel-permission#using-permissions-via-roles) it says that `$user->assignRole('writer');` would work, so I assumed that I could assign a role by name, but that does not work. You can only assign the role by passing the object.

I think that should be updated in the docs.

**Comment by drbyte** [comment]
@rathesDot wrote:
> You can only assign the role by passing the object.

Sorry, no, that is not correct. The string name of the role can be passed as documented: `$user->assignRole('string name');`
