### ISSUE TITLE
how to have roles in multi-tenant application

### ISSUE THREAD

**Issue by ashgibson** [spatie/laravel-permission#657]
I have a multi-tenant application where a user could be an admin in one account but limited in another. How can I extend the package to cater for this?

I think I would need to add the account_id field that I use on all my other tables in the model_has_roles and model_has_permissions tables but then I need some way of passing extra information to the $user->assignRole() and $user->hasRole() methods, along with all the other ones?

I currently have an account_user pivot table for joining users to accounts and vice versa. My other thought is to create a model (Custom Intermediate Table Model as per laravel docs) for the pivot table and then use that to assign roles.

**Comment by pablorsk** [comment]
I need something very similar (one database, users can have different roles and permissions on each organization/company).

Any recipes for this? On my case, also, every organization/tenant has the same set of available permissions.

A some of issues about this was opened, but #280 is the most complete. Also, a some discussions  mention another library: https://github.com/JosephSilber/bouncer/releases/tag/v1.0.0-beta.5

**Comment by JGamboa** [comment]
@pablorsk  I already did and overwrite to support multi companys, i have one of my applications working that way.

**Comment by satishnreddy999** [comment]
> @pablorsk I already did and overwrite to support multi companys, i have one of my applications working that way.
Hi, I also got exactly same scenario and requirement. can you guide me how you do it? if possible with example. thanx in advance

**Comment by AlanRezende** [comment]
@JGamboa Can you share your code?
