### ISSUE TITLE
Use hasPermissionTo in a closure

### ISSUE THREAD

**Issue by stefro** [spatie/laravel-permission#66]
Not sure if this is a bug or if it's just me.

I would like to get all the users which have permission to 'write_post'.
```
        $users = User::where(function ($q) {
            $q->hasPermissionTo('write_post');
        })->get();
```
this fails with a `BadMethodCallException thrown with message "Call to undefined method Illuminate\Database\Query\Builder::hasPermissionTo()"`

**Comment by sebastiandedeyne** [comment]
`hasPermissionTo` is a method on the model itself (it's not a query scope), so you'd have to filter the users after retrieving them.

A PR adding query scopes to this package would be nice I think (pinging @freekmurze for a second opinion).

**Comment by stefro** [comment]
Thanks @sebastiandedeyne 

So, after all, it was just me :-)

**Comment by freekmurze** [comment]
A PR that adds the query scope would definitely be accepted.
