### ISSUE TITLE
show user roles on edit

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-permission#663]
Hi,

I try to get user assigned roles on user edit page but i can't.

Here is my blade code:

```html
<label>Roles</label><br>
<select data-placeholder="Select a Roles" class="form-control tagsselector" name="roles[]" multiple="multiple">
  @foreach($roles as $role)
    <option value="{{ $role->id }}"  {{ $role->id == ' ' ? 'selected' : '' }}>{{ $role->name }}</option>
  @endforeach
</select>
```

I know this part is the issue `$role->id == ' '` but i'm not sure what i have to replace with `' '`

thanks.

**Comment by hamidafghan** [comment]
As the relationship between user and role is many to many to you have to  user ***foreach*** for user roles.
`<select data-placeholder="Select a Roles" class="form-control tagsselector" name="roles[]" multiple="multiple">
  @foreach($user->roles as $role)
    <option value="{{ $role->id }}"  {{ $role->id == ' ' ? 'selected' : '' }}>{{ $role->name }}</option>
  @endforeach
</select>`

May be you assign just a role for user so you have to select the `->first()` laravel function.

**Comment by robertnicjoo** [comment]
@hamidafghan It returns empty

here is my function

```php
$roles = Role::get();
```

**Q.** why I get all roles instead of only roles assigned to users?
**A.** because I might need to add or remove roles to user.

**Comment by drbyte** [comment]
Try:

`$roles = Role::get();`

and

```diff
<label>Roles</label><br>
<select data-placeholder="Select a Roles" class="form-control tagsselector" name="roles[]" multiple="multiple">
  @foreach($roles as $role)
-    <option value="{{ $role->id }}"  {{ $role->id == ' ' ? 'selected' : '' }}>{{ $role->name }}</option>
+    <option value="{{ $role->id }}"  {{ $user->roles->contains($role->id) ? 'selected' : '' }}>{{ $role->name }}</option>
  @endforeach
</select>
```

**Comment by robertnicjoo** [comment]
@drbyte  works perfectly, thank you.

**Comment by icynets** [comment]
> ```diff
> $user
> ```

Where did you get the $user from in the foreach ?

**Comment by madmouse17** [comment]
Where did you get the $user from in the foreach ?

**Comment by madmouse17** [comment]
> Try:
> 
> `$roles = Role::get();`
> 
> and
> 
> ```diff
> <label>Roles</label><br>
> <select data-placeholder="Select a Roles" class="form-control tagsselector" name="roles[]" multiple="multiple">
>   @foreach($roles as $role)
> -    <option value="{{ $role->id }}"  {{ $role->id == ' ' ? 'selected' : '' }}>{{ $role->name }}</option>
> +    <option value="{{ $role->id }}"  {{ $user->roles->contains($role->id) ? 'selected' : '' }}>{{ $role->name }}</option>
>   @endforeach
> </select>
> ```
Where did you get the $user from in the foreach ?
