### ISSUE TITLE
Checking for both Role and Permission

### ISSUE THREAD

**Issue by schajee** [spatie/laravel-permission#667]
I have a scenario where I need to check for both Role and Permissions assigned to a user. Right now I am using something similar to `if ($user->role('role') || $user->can('permission'))`. 

Is there a way of doing this similar to what _Zizaco/Entrust_ does with **ability** such as 
`if ($user->ability(['roles'],['permissions'])`?

**Comment by ultrono** [comment]
I've not seen anything specific for this package, but you could add a simple helper method onto your user model. Something along the lines of (may vary depending your use case and how strict you wish to be):

```
public function ability(array $roles, array $permissions) : bool
{
   return $this->hasAnyRole($roles) && $this->hasAnyPermission($permissions);
}
```

**Comment by schajee** [comment]
Thanks, but now it throws a _Spatie\Permission\Exceptions\PermissionDoesNotExist_ whenever the said permissions don't exist. I guess I can check for permissions with `app(Permission::class)->findByName()` and return false. 

But since this is more of a requirement in Blade, I think I'll continue with `@role ... @else @can ... @else ... @endcan @endrole` structure. For some reason the exception is not thrown in this case if the permission doesn't exist.

**Comment by drbyte** [comment]
@schajee wrote:
> I have a scenario where I need to check for both Role and Permissions assigned to a user. Right now I am using something similar to if ($user->role('role') || $user->can('permission')).

Can you give more details about why your `role` in this case doesn't already contain the `permission`?

**Comment by ultrono** [comment]
@schajee - the code I posted is just an quick untested idea. As your requirement is fairly specific I'd image some more robust code would be required your end. i.e. https://github.com/Zizaco/entrust/blob/master/src/Entrust/Traits/EntrustUserTrait.php#L186-L243

**Comment by schajee** [comment]
@drbyte My usual setup would include administrator and user roles; the administrator would be allowed to do anything or everything, and the user would be given permission on a need basis. So now when I want the admin to be able to `create-node` I can check `@ability(['admin'],['create-node'])` instead of assigning him permissions every time there is something new added to the system and then checking via `can('create-node')`. 

This setup is required more often during development than after it. But in situations where capabilities keep changing I'd rather have the ability to do something quickly rather than permit the admin to do it. 

Ps. I can also counter this by permitting admin every time I create a new permission.
