### ISSUE TITLE
Roles relation is not refresh after assignRole

### ISSUE THREAD

**Issue by sazo** [spatie/laravel-permission#668]
Hallo,

If you do 

```
$user->hasRole('admin')
$user->assignRole('admin')

if($user->hasRole('admin')){
   return 'yes'
}else{
   return 'no'
}

// Prints 'no'
```

This is because the first 'hasRole' loads the relation 'roles' and stores the relation on the model (eleqount magic)

When the secount hasRole comes it just loads from the cached relation on model which do not have the new assigned role.

The solution is to clear roles when assigning role(s) or reload roles agian

Laravel : 5.5

**Comment by drbyte** [comment]
Or just use `$user->fresh()` to reload the user's assigned relations.
