### ISSUE TITLE
[Request] [v3] add sort-order to permissions, for display purposes

### ISSUE THREAD

**Issue by hakimihamdan88** [spatie/laravel-permission#669]
how do I group permissions into a group?

something like this

![](https://i.imgur.com/PdYXQvw.png)

**Comment by drbyte** [comment]
Assign them to a role.

Example from the README:
```php
        // create permissions
        Permission::create(['name' => 'edit articles']);
        Permission::create(['name' => 'delete articles']);
        Permission::create(['name' => 'publish articles']);
        Permission::create(['name' => 'unpublish articles']);

        // create roles and assign permissions
        $role = Role::create(['name' => 'writer']);
        $role->givePermissionTo('edit articles');

        $role = Role::create(['name' => 'moderator']);
        $role->givePermissionTo(['publish articles', 'unpublish articles', 'delete articles']);
```

**Comment by hakimihamdan88** [comment]
@drbyte what I'm trying to do is output permissions on checkbox for every role. But when adding new permission for articles (edit others article) for example, it will on bottom. As for now, I create another order_by field, so it will be after edit articles.

**Comment by drbyte** [comment]
I see. By "group" you meant "assign a sort order".

You could also simply name the permissions with a group/sort prefix, and then have your UI display them according to that group/sort strategy.

**Comment by drbyte** [comment]
Deferring to @AlexVanderbist for consideration in v3.
