### ISSUE TITLE
Migration does not create foreign key in user table and SQLSTATE[42S22]: Column not found model_id

### ISSUE THREAD

**Issue by ronaldaraujo** [spatie/laravel-permission#671]
Hello! I've two questions.

**Question 1**
In version **2.9** should the migration not have the commands for creating the foreign keys in the tables *'model_has_permissions'* and *'model_has_roles'* equal to version [**1.9**](https://github.com/spatie/laravel-permission/blob/v1/resources/migrations/create_permission_tables.php.stub) (line 34 and line 51)?

**Question 2**
Why is not my query using the correct column? It is using *'model_id'* instead of *'user_id'*. Look:

`select name from roles inner join user_has_roles on roles.id = user_has_roles.role_id where user_has_roles.model_id = 1 and user_has_roles.model_type = App\User`

Thank you.

**Comment by drbyte** [comment]
1. It does. See lines 36 and 48 https://github.com/spatie/laravel-permission/blob/master/database/migrations/create_permission_tables.php.stub#L36

2. It should be using `model_id`.  The old v1.9 used `user_id`, but the schema in v2 is different.
