### ISSUE TITLE
Method [permission] does not exist

### ISSUE THREAD

**Issue by vexsolutions** [spatie/laravel-permission#673]
"message": "Method [permission] does not exist on [App\\Http\\Controllers\\RolePermissionController].",
    "exception": "BadMethodCallException",

--- Controller

`namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

 public function addPermission(Request $request)
    {

        $request->validate([
            'name' => 'required',
        ]);

        //Permission::create(['name' => $request->name]);

        $permission = Permission::create(['name' => $request->name]);

        return $permission;

    }`

Followed installation instructions for Laravel.

**Comment by drbyte** [comment]
The error you're getting is NOT coming from this package.

It is telling you that your self-written `RolePermissionController` doesn't have a `permission`method in it, which is correct, since your method is named `addPermission`.

**Comment by vexsolutions** [comment]
This is a face palm moment if ever there was one. Thank you @drbyte you have show me the error of my ways
