### ISSUE TITLE
Has Permission To not finding permission.

### ISSUE THREAD

**Issue by Rihoj** [spatie/laravel-permission#674]
I have created a role called Admin. I give it the permission "edit_user". In my controller, I check if the user has permission to "edit_user" and the application throws an exception stating that the permission does not exist.

Create role and permission and assign them to the user.
`$role = Role::create(['name'=>'admin']);
$canEditUserPerm = Permission::create(['name'=>'edit_user']);
 $role->givePermissionTo($canEditUserPerm);
 $user = User::find(1);
 $user->assignRole('admin');`

Controller
`if (!Auth::user()->hasPermissionTo('edit_user') && $id != Auth::user()->id) {
    abort(403, 'Unauthorized action.');
}`

Exception: There is no permission named `edit_user` for guard `web`.

User model has trait "HasRoles" with the proper use statement.

Database has the record:
# id, name, guard_name, created_at, updated_at
'1', 'edit_user', 'web', '2018-03-02 04:10:43', '2018-03-02 04:10:43'

If there is more information you would like let me know.

**Comment by drbyte** [comment]
Do you mind sharing your complete controller class, and the route that's triggering the error?

**Comment by Rihoj** [comment]
Controller class:
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function patch(Request $request, $id)
    {
        if (!Auth::user()->hasPermissionTo('edit_user') && $id != Auth::user()->id) {
            abort(403, 'Unauthorized action.');
        }
        $rules = [
            'name' => 'required|max:255',
        ];
        if (Auth::user()->email !== $request->email) {
            // $rules["email"] = "required|unique:users";
        }
        $request->flashExcept('password');
        $validatedData = $request->validate($rules);

        $user = User::findOrFail($id);
        $user->fill($request->all());
        $user->save();
        return view('/user/settings',['user'=>$user]);
    }
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function settings($id=null)
    {
        if(!is_null($id)){
            if (!Auth::user()->hasPermissionTo('edit_user') && $id != Auth::user()->id) {
                abort(403, 'Unauthorized action.');
            }
            $user = User::findOrFail($id);
        }else{
            $user = Auth::user();
        }
        return view('/user/settings', ['user'=>$user]);
    }
}
`

route (in web.php with web as default guard)
`Route::patch('user/{id}/settings', 'UserController@patch')->name('user.settings.patch');`


Some additional information. I have tried running `php artisan cache:clear` and that did not work. I did run a `composer update spatie/laravel-permission` and got the following information:

`Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/socialite
Discovered Package: spatie/laravel-permission
Discovered Package: laravel/tinker
Discovered Package: intervention/image
Discovered Package: graham-campbell/markdown
Discovered Package: laravelcollective/html
Discovered Package: yab/formmaker
Discovered Package: yab/crudmaker
Discovered Package: yab/laracogs
Discovered Package: yab/quarx
Discovered Package: pragmarx/yaml
Discovered Package: pragmarx/version
Package manifest generated successfully.`

After running the update the permissions worked.

**Comment by drbyte** [comment]
> After running the update the permissions worked.

I suppose the composer autoload data might have been damaged, and therefore the `composer update` repaired them.

**Comment by Rihoj** [comment]
I tried to do some more testing today, and I am getting the error again. Here is how it started. I migrate and seed my db. I then changed the naming convention of my permission. Then I started getting the error.
I changed the permission from "can edit user" to "edit user".
Migrating and seeding with command `php artisan migrate:fresh --seed`

UsersTableSeeder.php
```
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\User;
class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'name' => "James",
            'email' => "example@example.com",
            'password' => bcrypt('secret'),
        ]);
        $role = Role::create(['name'=>'admin']);

        $canEditUserPerm = Permission::create(['name'=>'edit user']);
        $role->givePermissionTo($canEditUserPerm);
        $user = User::find(1);
        $user->assignRole('admin');

        $role = Role::create(['name'=>'client']);
    }
}
```

**Comment by drbyte** [comment]
I'm not surprised that a seeder would run into those sorts of errors, because the cache doesn't get a chance to be refreshed. 

See: https://github.com/spatie/laravel-permission#database-seeding
.. and you might want to trigger the cache-refresh mid-seed.

**Comment by Rihoj** [comment]
Awesome! Thank you! I am sorry I missed that in the documentation. Thank you for taking the time to step through this with me.

**Comment by Rihoj** [comment]
As a note. I had to switch to DB cache as file cache still was not getting refreshed with either command (in the seeder or in the cli)

**Comment by drbyte** [comment]
> As a note. I had to switch to DB cache as file cache still was not getting refreshed with either command (in the seeder or in the cli)

Interesting. For my [demo app](https://github.com/drbyte/spatie-permissions-demo/blob/master/database/seeds/PermissionsDemoSeeder.php), my dev environment uses `file`, and CI (Travis) uses `array`, and seeder tests are passing.

**Comment by Rihoj** [comment]
That is interesting. I wonder if it has something to do with file permissions on my end. My production environment uses DB for now so I don't mind being on DB.
