### ISSUE TITLE
assignRole not using default guard, but first guard

### ISSUE THREAD

**Issue by jmfederico** [spatie/laravel-permission#675]
When assigning a role to a user with:
```php
    $user->assignRole('name');
```
The app is trying to find the role using the first guard from the `'guards'` list in `auth.php` but not from the default guard. This is not the same behavior as when creating a role, which creates it using the default guard.

my setup:

```php
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],
```

```php
# Uses api for the guard_name
Role::create(['name' => 'admin']);
```

```php
# Uses web for the guard_name
$user->assignRole('name');
```

**Comment by drbyte** [comment]
What's the `guard_name` property on your User model (whatever your `$user` object is created from)?

**Comment by jmfederico** [comment]
It has none set.

```php
use App\User;
$user = new User();
$user->guard_name;
# null
```

`$user->assignRole('name');` is taking the one that comes first in the `guards` array. I changed the order in the array to `api` first, and it then uses the `api` guard.

**Comment by irakliOrbis** [comment]
This solved my issue.

![screen shot 2018-03-06 at 10 34 58 am](https://user-images.githubusercontent.com/32687522/37041466-49eac06c-212a-11e8-990b-e0c5081704d0.png)

**Comment by jmfederico** [comment]
@drbyte May I ask if this was fixed? Or, if not, why is the issue closed?

Thanks

**Comment by drbyte** [comment]
Sigh. Thanks for catching that. I misread the last post as being a resolution.

**Comment by drbyte** [comment]
I was just reviewing this again. 
I think it is resolved. 

`Role::create` and `assignRole()` both use this package's `->getDefaultGuardName()`, which first looks for `$guard_name` as a property on the model, and if not found will fallback to Laravel's default guard.

**Comment by Vimiso** [comment]
In my case it's not falling back to Laravel's default. Having to enforce:

```
/**
     * The guard for `laravel-permissions` to use.
     *
     * Patching `Spatie\Permission\Guard` because its not picking up Laravel's default.
     *
     * @return string
     */
    public function guardName(): string
    {
        return 'api';
    }
```

on my User model.

**Comment by bhargavraviya** [comment]
Easy Way change on User Model 

Please check first on the database because you created a role in guard_name is a "web" and you used role management on the API side and then made a role based on guard_name "API"

otherwise used like this

add a line on User Model
```
protected $guard_name = 'web';
```
