### ISSUE TITLE
There is no permission named `edit_project` for guard `api`

### ISSUE THREAD

**Issue by zakiullahbarakzai** [spatie/laravel-permission#676]
I am using Laravel 5.6 with spatie/laravel-permission version 2.9 also using Laravel Passport as auth driver with `$guard = 'api'.`

When I am trying to assign an array of permission like `['edit_project', 'add_project' 'delete_project']` to a role with help of this function

```
public function assignPermissions($role, $permissions)
    {

        $role = Role::findByName($role);

        $role->givePermissionTo($permissions);

        return $role;
    }
```

but getting the error `There is no permission namededit_projectfor guardapi`.`

Also I have at config/auth.php

```
return [

/*
|--------------------------------------------------------------------------
| Authentication Defaults
|--------------------------------------------------------------------------
|
| This option controls the default authentication "guard" and password
| reset options for your application. You may change these defaults
| as required, but they're a perfect start for most applications.
|
*/

'defaults' => [
    'guard' => 'web',
    'passwords' => 'users',
],

'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],

    'api' => [
        'driver' => 'passport',
        'provider' => 'users',
    ],
],

'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\User::class,
    ],

    // 'users' => [
    //     'driver' => 'database',
    //     'table' => 'users',
    // ],
],

'passwords' => [
    'users' => [
        'provider' => 'users',
        'table' => 'password_resets',
        'expire' => 60,
    ],
],

];
```

**Comment by drbyte** [comment]
What is the code you used to create the permissions you are attempting to assign?  (permissions must be created before they can be assigned to a role)

**Comment by zakiullahbarakzai** [comment]
I am seeding the permission table by help of Larvel seeder which means I have predefined permissions in my system as well as roles I have attached my permission table which  looks at the first time when I am seeding it like below that the `guard_name` is `web.`
<img width="1586" alt="web" src="https://user-images.githubusercontent.com/8676917/36942546-8229513a-1f92-11e8-962e-59295f5f7528.png">

but manually I am changing the` guard_name` field to `api` which my permission table became like this.

<img width="1585" alt="api" src="https://user-images.githubusercontent.com/8676917/36942553-95915d62-1f92-11e8-885d-c7357087271e.png">

**Comment by drbyte** [comment]
After you make the manual edits to the database content, are you clearing the laravel cache?

**Comment by gregoriochiko** [comment]
I have a similliar problem.
What I want to achieve is in case I have two permissions, one belongs to `api` guard and the other to `web` guard, then I want to give the `User` both permissions, how can I achieve that?

**Comment by drbyte** [comment]
@gregoriochiko you mentioned permissions and didn't say anything about roles, so I'll assume your'e only interested in specific permissions.
This also assumes you want to assign permissions for all guards, and have already created separate permissions for all guards.

```
// pick a permission name
$permission_name = 'whatever';
// lookup all defined permissions, regardless of guard
$permissions = app(PermissionRegistrar::class)->getPermissions()
   // filter down to just those matching the specified name
    ->filter(function ($permission) use ($permission_name) {
        return $permission->name === $permission_name;
    });
// grant those specific permissions to the user
$user->givePermissionTo($permissions);
```

**Comment by gregoriochiko** [comment]
I've fixed this by creating another model that extends `User` model, so that new model can have `api` guard while `User` still have the default guard (`web`).

**Comment by ayrasys** [comment]
i m also facing this problem that it works web guard but not with api so  help us how to fix this by api guard too 
Thanks
