### ISSUE TITLE
Best way to update roles and groups after update

### ISSUE THREAD

**Issue by joveice** [spatie/laravel-permission#679]
Whats the best way to update the database (reseed) with new roles and groups? I added them to the seed file, but if I reseed each time I update it wont I get the same roles over and over again?

**Comment by drbyte** [comment]
@joveice wrote:
> each time I update it

What do you mean by "update it"?  Are you referring to when you add new features to your code and add more roles/permissions, and want to add them to new deployments? In that case you could use database migrations: the `up` method can be used to add the new roles and permissions as part of regular deployment activities.

**Comment by joveice** [comment]
Hm, maby. I'll see if I can make that work 😄
