### ISSUE TITLE
A 'admin.view' permission already exists for guard 'web'.

### ISSUE THREAD

**Issue by joveice** [spatie/laravel-permission#680]
I keep having issues with permissions which does not exist, or exist but it doesn't see them.

```
$ php artisan cache:clear
Cache cleared successfully.
$ php artisan db:seed --class RolesAndPermissionsSeeder


In PermissionAlreadyExists.php line 11:

  A 'admin.view' permission already exists for guard'`web'.


$ php artisan tinker
Psy Shell v0.8.17 (PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> $p = Spatie\Permission\Models\Permission::where('name', 'admin.view')->get();
=> Illuminate\Database\Eloquent\Collection {#971
     all: [],
   }
```

**Comment by drbyte** [comment]
Is this part of the same issue as #681 you posted?

**Comment by joveice** [comment]
I don't know.

I had a role which I didn't add a permission to so I added a permission using the artisan command. used the database to link it to the role and cache clear.
Tried to check if the user in the role had permission > false. the items where correctly linked in the database, so I had no idea.
Deleted the link and the permission then cache clear.
And tried to add it using the code way, "permission already exists".

I hope you understand what I wrote.

**Comment by drbyte** [comment]
I suspect there's an order-of-operations clash between your commands and cache reset.

Here's a demo project where I've demonstrated most of the commands in the README, including seeds, tests, and some views: https://github.com/drbyte/spatie-permissions-demo

**Comment by joveice** [comment]
I "solved" it by wiping the database and wiping the project and re cloning it (was only testing) and my script created the roles and permissions (no fails or erros) and I where able to use the can on myself on the last broken permission. Some cache have gone wrong here for sure.

**Comment by drbyte** [comment]
Glad you've been able to solve it.

**Comment by lemonjp** [comment]
I got same issue.
but when I put 'sudo' on the clear command, now everything its ok.

```
$ sudo php artisan cache:clear
$ sudo php artisan config:clear
$ sudo php artisan route:clear
$ sudo php artisan view:clear
```
