### ISSUE TITLE
"User does not have the right permissions" although user does have permission

### ISSUE THREAD

**Issue by komirad** [spatie/laravel-permission#681]
Not sure where I am going wrong. This is my first time setting this up.

`Auth::user()->getAllPermissions();` shows `{id: 1, name: "admin", guard_name: "api", created_at: "2018-03-07 12:16:47",…}`

But when accessing an api route using a middleware like so:
`Route::group(['middleware' => ['permission:admin'], 'prefix' => 'admin'], function() {});` I get the error "User does not have the right permissions. Necessary permissions are admin"

The user is a super admin so I have assigned a generic permission named "admin" which protects all admin related routes.

Using `['middleware' => ['role:super-admin']]` works but what am I missing above?

**Comment by komirad** [comment]
@drbyte I must admit am not very familiar with the concept of guards even though I have read a little about them but the routes are within the api.php file. My config for auth are as follows:

```
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
    ],
```

The routes are also wrapped in a `jwt.auth` middleware if that matters. Should I be setting something differently?

**Comment by drbyte** [comment]
Did you get this sorted out?

**Comment by peterson-umoke** [comment]
been trying to assign roles but it is not reflecting in the column?

**Comment by haught** [comment]
Hey @drbyte I am having the same problem that @komirad is having. When checking a role from the middleware, it works, but checking a permission from the middleware fails. After playing around with it for a bit I have found that a permission assigned to a model works, but when they are assigned to a role (like all of mine) they are not looked up. The can() function used in PermissionMiddleware.php seems to fail to look at assigned roles for associated permissions. Am I missing something?

**Comment by haught** [comment]
I ended up putting in a fresh migration of the database schema and after importing my data - everything works...

**Comment by drbyte** [comment]
Yes, the v2 code uses the model guard first, and only uses the "default" as the last fallback.
We may revisit this in v3 since it has caused confusion for some.

**Comment by humaneguy** [comment]
This is still an issue. @haught answer just fixed it. Currently running Laravel 8 with version 5 of `spatie/laravel-permission`
