### ISSUE TITLE
How To Get Users by Role/Permission

### ISSUE THREAD

**Issue by benyanke** [spatie/laravel-permission#682]
I am planning on using this additionally to create some user lists by role - for example, list all users in a given department. This could also be useful to get all users with a given permission, but that isn't as important for me currently.

Is there a built-in method to enumerate users in a given role, or should this be accomplished with a raw query on the tables?

**Comment by drbyte** [comment]
Nothing special required, since the data is all in Eloquent models. 

Role has a `users` relationship, so $role->users gives a collection of related objects.
Users has a `roles` relationship, so $user->roles gives a collection of roles.

Example controller method, where it also filters for a set of "non-members" based on role, is :

```php
    public function report_roles()
    {
        $roles = Spatie\Permission\Models\Role::all();
        $users = \App\User::with('roles')->get();
        $nonmembers = $users->reject(function ($user, $key) {
            return $user->hasRole('Member');
        });
        return view('admin.report_roles', ['roles'=>$roles, 'nonmembers' => $nonmembers]);
    }
```

and corresponding view:
```blade
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-md-offset-1">

        <div class="panel panel-default">
          <div class="panel-heading panel-title">Role Assignments</div>
          <div class="panel-body">

            <p>Available roles:</p>
            @foreach($roles as $r)
              @if($r->name == 'Member')
                @continue
              @endif
              <ul class="listBox">
                <li>{{$r->name}}
                  <ul class="listBox">
                    @foreach ($r->users as $u)
                      <li>{{$u->name}}</li>
                    @endforeach
                  </ul>
                </li>
              </ul>
            @endforeach
          </div>
        </div>
      </div>

      <div class="col-md-5">

        <div class="panel panel-default">
          <div class="panel-heading panel-title">Role Assignments</div>
          <div class="panel-body">

            <p>Users WITHOUT "Member" role:</p>
            <ul class="listBox">
              @foreach($nonmembers as $u)
                <li><a href="/members/{{ $u->id }}">{{ $u->name }}</a> ({{ $u->weekend }})</li>
              @endforeach
            </ul>
          </div>
        </div>


      </div>
    </div>
  </div>

```

**Comment by benyanke** [comment]
Very helpful, thank you!

**Comment by jonaselan** [comment]
For how search others way to do that:

```
User::whereHas("roles", function($q){ $q->where("name", "collaborator"); })->get()
```

**Comment by omadoyeabraham** [comment]
Thanks @jonaselan

**Comment by RobbyAJM** [comment]
For anyone looking for "get all roles but exclude specific role"

For an example I have 3 roles which is ['Administrator','Instructor','Student'] and I wanna exclude 'Student' role from the collection.
Then I can use filter function.

```
$roles = Spatie\Permission\Models\Role::all();
$roles->filter( function($item){ $item->name != 'Student' });
```

Output: ['Administrator','Instructor']

**Comment by hardcoremore** [comment]
> For anyone looking for another way to do this:
> 
> ```
> User::whereHas("roles", function($q){ $q->where("name", "Member"); })->get()
> ```

What is "Member" in this case? Is the "Member" role name so for users with admin role we would do it like this

`User::whereHas("roles", function($q){ $q->where("name", "admin"); })->get()`

**Comment by jonaselan** [comment]
@hardcoremore yep

**Comment by ultrono** [comment]
Semi related, if you just require a count of users within a role, where a single query is executed: 

````
// $role is the required role by name i.e. 'Staff'
User::whereHas('roles', function (Builder $query) use ($role) {
   $query->where('name', $role);
})->count()
````

**Comment by rohan-khatri** [comment]
or, you can directly use, its method,

```
User::role('writer')->get()
```

will return users having writer role.

**Comment by hendisantika** [comment]
> User::role('writer')->get()

That doesn't work for me.

**Comment by davide-casiraghi** [comment]
> ### For anyone looking for "get all roles but exclude specific role":
> Example I have 3 roles which are ['Administrator','Instructor','Student'] and I wanna exclude 'Student' role from the collection.
> Then I can use filter function.
> 
> ```
> $roles = Spatie\Permission\Models\Role::all();
> $roles->filter( function($item){ return $item->name != 'Student'; });
> ```
> 
> Output: ['Administrator','Instructor']

To exclude roles I found also this option, and in this way, you can pass even an array of roles to exclude.

Role::whereNotIn('name', ['Student', 'another role to exclude'])->get();

**Comment by drbyte** [comment]
Good point. Yes, there are many Eloquent helpers that can help with such filtering.
A few more are listed at: https://spatie.be/docs/laravel-permission/v3/basic-usage/basic-usage#eloquent

**Comment by doliskani** [comment]
just using this simple code :
    User::role(['admin' , 'writer'])->get();

**Comment by ericknyoto** [comment]
> For anyone looking for another way to do this:
> 
> ```
> User::whereHas("roles", function($q){ $q->where("name", "Member"); })->get()
> ```

Could not using laravel pagination of using whereHas (pagination, simplePaginate). Method not found on Eloquent builder. Anyone know how to do the pagination with the whereHas?

**Comment by RayhanYulanda** [comment]
> just using this simple code :
> 
> `User::role(['admin' , 'writer'])->get(); `

I've tried this but i got an error Non-static method App\User::roles() cannot be called statically

**Comment by nipunTharuksha** [comment]
> User::role(['admin' , 'writer'])->get()

This throw an error ` Spatie\Permission\Exceptions\RoleDoesNotExist with message 'There is no role named `

**Comment by RayhanYulanda** [comment]
I got the problem. The problem is i override the Role method in User model

**Comment by daeehamid** [comment]
there is method to get all users except 'user' role ?

**Comment by danFWD** [comment]
Here is how to get all users with a certain permission, rather than just a role:
```
$users = User::whereHas('roles', function($q) {
  $q->whereHas('permissions', function($q1) {
    $q1->where('name', '=', 'permission name');
  });
})->get();
```

**Comment by mostadev** [comment]
public function scopeHasRoles($q, $roles = [])
{
    $q->whereHas('roles', function ($q) use ($roles) {
        $q->where(function($q) use ($roles){
            foreach ($roles as $role) {
                $q->orWhere('name', $role);
            }
        });
    });
}

**Comment by ronappleton** [comment]
```php
    public function scopeHasPermission(Builder $query, string $permission): Builder
    {
        return $query->whereHas('roles.permissions', function (Builder $query) use ($permission) {
            $query->where('name', $permission);
        })->orWhereHas('permissions', function (Builder $query) use ($permission) {
            $query->where('name', $permission);
        });
    }

    public function scopeHasAnyPermission(Builder $query, string ...$permissions): Builder
    {
        return $query->whereHas('roles.permissions', function (Builder $query) use ($permissions) {
            $query->whereIn('name', $permissions);
        })->orWhereHas('permissions', function (Builder $query) use ($permissions) {
            $query->whereIn('name', $permissions);
        });
    }

    public function scopeHasAllPermissions(Builder $query, string ...$permissions): Builder
    {
        foreach ($permissions as $permission) {
            $query->where(function (Builder $query) use ($permission) {
                $query->whereHas('roles.permissions', function (Builder $query) use ($permission) {
                    $query->where('name', $permission);
                })->orWhereHas('permissions', function (Builder $query) use ($permission) {
                    $query->where('name', $permission);
                });
            });
        }

        return $query;
    }

    public function scopeHasRole(Builder $query, string $role): Builder
    {
        return $query->whereHas('roles', function (Builder $query) use ($role) {
            $query->where('name', $role);
        });
    }

    public function scopeHasAnyRole(Builder $query, string ...$roles): Builder
    {
        return $query->whereHas('roles', function (Builder $query) use ($roles) {
            $query->whereIn('name', $roles);
        });
    }

    public function scopeHasAllRoles(Builder $query, string ...$roles): Builder
    {
        foreach ($roles as $role) {
            $query->where(function (Builder $query) use ($role) {
                $query->whereHas('roles', function (Builder $query) use ($role) {
                    $query->where('name', $role);
                });
            });
        }

        return $query;
    }
```

If it helps anyone, just add to user model, or create a trait and use it.

**Comment by bloodykheeng** [comment]
Here's an improved and more structured version of your explanation for better readability and clarity:  

---

### **Issue: Role Filters Reset When Using `orWhere` in Laravel Queries**  

@jonaselan, I initially thought this wouldn't work:  
```php
User::whereHas("roles", function($q) {
    $q->where("name", "Member");
})->get();
```
But after troubleshooting, I realized the issue wasn’t Laravel’s `whereHas`, but how `orWhere` behaves in queries.  

### **What Happened?**  
I structured my filters in the `index` method as follows:  
1️⃣ **First, I applied the role filter** using `whereHas('roles')`.  
2️⃣ **Then, I applied search filters** using `orWhere`.  

However, **`orWhere` does not respect previous query constraints** and resets the filter.  

#### **Unexpected Behavior**  
- If no users had the role "Member," the role filter returned **zero results** as expected. ✅  
- But when applying search filters, I suddenly got **all users**, even those without the role. ❌  
- This was because `orWhere` ignored the role filter and fetched users based on email or phone, even if they didn't have the role.  

### **Original Code (Causing the Issue)**
```php
public function index(Request $request)
{
    $query = User::with(['createdBy', 'updatedBy']);

    // Apply role filter
    $query->whereHas('roles', function ($q) {
        $q->where('name', "System Admin");
    });

    // Apply search filters (Incorrect)
    if ($request->has('search')) {
        $query->where('name', 'like', '%' . $request->query('search') . '%')
            ->orWhere('email', 'like', '%' . $request->query('search') . '%')
            ->orWhere('phone', 'like', '%' . $request->query('search') . '%'); // ❌ Resets role filter
    }

    $data = $query->get();
    return response()->json(['data' => $data]);
}
```
🔴 **Issue:** `orWhere` fetches users by search terms, overriding the role filter and including unintended users.  

---

### **Solution: Wrap `orWhere` Inside a `where` Closure**  
To ensure the search applies **only to users within the role filter**, we need to **group search conditions inside a `where` callback**.  

#### ✅ **Fixed Code:**
```php
// Apply search filter (wrapped in a `where` closure)
if ($request->has('search')) {
    $searchTerm = '%' . $request->query('search') . '%';

    $query->where(function ($q) use ($searchTerm) {
        $q->where('name', 'like', $searchTerm)
          ->orWhere('email', 'like', $searchTerm)
          ->orWhere('phone', 'like', $searchTerm);
    });
}
```
✅ **Keeps role filtering intact**  
✅ **Ensures search applies only within the role-filtered users**  
✅ **Prevents unintended resets**  

### **Final Thoughts**  
If you use `orWhere` after `whereHas`, **always wrap search conditions inside a `where` closure** to maintain proper filtering. This saved me from a major headache, and I hope it helps others facing the same issue! 🚀
