### ISSUE TITLE
Does this delete relationships when deleting a model?

### ISSUE THREAD

**Issue by joveice** [spatie/laravel-permission#683]
Yo,

If I delete using Role:: and Permission:: will it wipe the relationships between users and the permissions/roles?

(Good to know)

**Comment by drbyte** [comment]
Yes. That's what the `onCascade('delete')` clause is for in the database foreign-key relationships.
ie: https://github.com/spatie/laravel-permission/blob/master/database/migrations/create_permission_tables.php.stub#L39

**Comment by joveice** [comment]
Awesome, then I have a good idea how I can solve my permission updating on new updates for my app.
