### ISSUE TITLE
[Request] Role hierarchy

### ISSUE THREAD

**Issue by Rihoj** [spatie/laravel-permission#685]
I would like to see where we can have role hierarchy. To explain this further. Let's look at what roles and permissions there are for this example:
Roles
* Admin
* Manager

Permissions
* View Users
* Edit Users
* Delete Users
* Create Users

Relations
- Admin
- - View Users
- - Edit Users
- - Delete Users
- - Create Users
- Manager
- - View Users
- - Edit Users

Instead of adding the permissions individually to each role, I know that all permissions the manager has the Admin should as well. I propose that we would be able to create both roles and then assign a role to another role.

**Comment by drbyte** [comment]
Do you really mean "hierarchy"?  Or did you mean "inheritance"?

**Comment by Rihoj** [comment]
Inheritance to me means the parent class (role in this case) passes on values, methods, etc to the child. Whereas hierarchy to me is the inverse, where the child passes it's values up to the parent.

Admin is higher than manger so it would be there parent. It contains it's permissions and that of it's children. Manager is a child of Admin and contains a subset of permissions.

This is if course just my understanding, if I am wrong here let me know please.

**Comment by drbyte** [comment]
I understand your interpretation of Inheritance; and while I don't think I'd use "hierarchy" to only mean the opposite, you've described better what you're looking for, so that's good.

I perhaps should have suggested "reverse-inheritance". But that's just semantics. 
This package will never pass something from parent "role" down to child "permissions", as that wouldn't make sense.

But making multi-tiered roles is a different architecture. I suppose the `role` relationship could be defined to also have `sub-roles`. But I'm guessing that's way more complex than what Spatie originally envisioned.

However, in saying that, given that you specifically mentioned wanting "Admin" to have basically ALL the permissions of everyone else, why not bypass the complexity of that and just let Admin automatically respond `true` for all permission checks?  This way, as long as you use the native auth/gate methods of `can()`, `cannot()`, `@can`, `@cannot` Admin will always be allowed. To do this just use Laravel's `Gate::before()`. Example here: https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role

**Comment by Rihoj** [comment]
Thank you for that clarification. Reverse-inheritance might fit my question better.

In this specific situation you would be correct, just allowing true for Admin would work. However, in the app that I am making that spawned this thought process I actually have 4 roles. Site Admin, Admin, Manager, Client. Site Admin could also be seen as the Owner of the system, so they get to bypass everything. Admin users cannot edit, create, or delete other users in their same role. Managers can only view data. Clients can only view their own data. 

At this time I am accomplishing this by doing the following:

```
        $editAdminPermission = Permission::create(['name'=>'Edit Admin User']);
        $deleteAdminPermission = Permission::create(['name'=>'Delete Admin User']);
        $viewUserPermission = Permission::create(['name'=>'View User']);
        $editUserPermission = Permission::create(['name'=>'Edit User']);
        $deleteUserPermission = Permission::create(['name'=>'Delete User']);
        $createUserPermission = Permission::create(['name'=>'Create User']);

        $editAdminPropertyPermission = Permission::create(['name'=>'Edit Admin Property']);
        $deleteAdminPropertyPermission = Permission::create(['name'=>'Delete Admin Property']);
        $createPropertyPermission = Permission::create(['name'=>'Create Property']);
        $editPropertyPermission = Permission::create(['name'=>'Edit Property']);
        $deletePropertyPermission = Permission::create(['name'=>'Delete Property']);
        $viewPropertyPermission = Permission::create(['name'=>'View Property']);

        $siteAdminPermissions = [
            $editAdminPermission,
            $deleteAdminPermission,
            $editAdminPropertyPermission,
            $deleteAdminPropertyPermission,
        ];

        $adminPermissions = [
            $deleteUserPermission
            $editUserPermission,
            $createUserPermission,
            $createPropertyPermission,
            $editPropertyPermission,
            $deletePropertyPermission,
        ];

        $managerPermissions = [
            $viewUserPermission,
            $viewPropertyPermission,
        ];

        $siteAdminRole = Role::create(['name'=>'Site Admin']);
        $siteAdminRole->syncPermissions($siteAdminPermissions);

        $adminRole = Role::create(['name'=>'Admin']);
        $adminRole->syncPermissions($adminPermissions);

        $managerRole = Role::create(['name'=>'Manager']);
        $managerRole->syncPermissions($managerPermissions);

        $clientRole = Role::create(['name'=>'Client']);

        $user = User::whereEmail("site@example.com")->first();
        $user->assignRole('Site Admin', 'Admin', 'Manager');

        $adminUser = User::whereEmail("admin@example.com")->first();
        $adminUser->assignRole('Admin', 'Manager');

        $managerUser = User::whereEmail("manager@example.com")->first();
        $managerUser->assignRole('Manager');
```


However, during role management, I don't want to have to have to display that the user is assigned to multiple roles. I also feel that moving forward if I make one permission I could have to add it to all three roles. 

Am I approaching this from the wrong direction?

Note: Even though site admin is set to true for many items, I still have the permissions attached for testing purposes.

**Comment by robov** [comment]
Let me join in this conversation. I am searching for a package with role inheritance.
Something that allows me to define a base set of permissions and then when the user progresses to a higher role/membership, additional permissions are added.

gold member
-- silver member
---- bronze member

The only way i could create a supermember GOLD to have a bronze, silver and gold membership.. with inheritance I could just give them GOLD role and then the silver and bronze are inherited. This seems more natural and easy to understand.

Are you planning on inheriting roles? or am I overlooking something (inheritance is bad  and you choise not to implement ?)

**Comment by bmichotte** [comment]
@drbyte Since you tagged this issue for v3, I guess that's mean this will be implemented for v3 right ?

Do you have some approximative ETA on v3 ?

**Comment by drbyte** [comment]
> Since you tagged this issue for v3, I guess that's mean this will be implemented for v3 right ?

No, it's tagged as `revisit for v3` ... as in re-visit the idea for consideration. Not promised. 

No ETAs at this time.

**Comment by bmichotte** [comment]
All right. Thanks for the clarification @drbyte

**Comment by lucas-quinn-guru** [comment]
I was also looking for this exact same thing.  I find it so much more intuitive.  If you assign a RoleB to RoleA, RoleA would adopt RoleB's permissions.

**Comment by Rihoj** [comment]
So initially I had thought about this in the sense of having parent-child relations where it would have to recursively step into each permission that has a parent id of the one you are looking at. I knew this could be slow an inefficient. I recently came to mind that it might be better to do the following.

Set a role to "observe" another role. When that second role is updated it will broadcast that it has changed and the watching roles will update based on what was broadcast.

To implement this I would suggest the following using observer pattern:
Observer Table; observe_id (int(11), AI, NOT NULL), observer: int (relates to Role id), observable: int (relates to another Role id)
```
$observer = new Role("Admin");
$observable = new Role("Manager");
// This terminology is slightly backwards to the pattern, but I think it makes sense if you think about calling watch is registering with the parameter being passed.
$observer->watch($observable);

class Role
{
...
    public function watch(Role $observable)
    {
        // add connection in the database.
    }

    // called when a permission is added, deleted, or updated in any way. In this case it would need to be adding a role.
    public function updateRole($action, $permission)
    {
        // call db to look for roles watching this observable
        $observers = $db->getObservables($this->id);
        foreach($observers as $observer){
            $observer->addPermission($permission);
        }
    }
...
}
```

This would allow you to not have to perform any recursive look ups to see if a permission is within any children or grand-children. As a permission is added, removed, or updated it just adds it to the parent. The only real issue I could see doing it this way is that you might want to make a `source` field on the role_permissions table so that if the permission had been added to the parent and the child, and the permission gets removed from the child it is not removed from the parent as well.

Please let me know what your thoughts are on this, and if this would give you any more reason to add it to v3.

Thank you for considering this atleast.

**Comment by ereztdev** [comment]
Hi, I am also looking for hierarchy / inheritance.

So if an associate level has an array of $permissions or designated $role = associate, then manager of associate would inherit all associate permissions relieving a lot of 'assigning clutter' for every depth in the hierarchy.

I would like to see this in V3 and would be more than happy to know how close would be V3 release.

thanks!

**Comment by ntraykov** [comment]
This would be very valuable functionality

**Comment by Phunky** [comment]
ultraware/roles (fork of romanbican/roles) handles this by giving each role a level value, permissions are then assigned provided based on those available to their highest role level.

The downside is this currently it is not possible to revoke a inherited role.

Another option is to just ensure you can apply many roles to a user and manage it that way, which I actually think is better as your being more explicit with whats being assigned.

**Comment by drbyte** [comment]
@Rihoj @robov @bmichotte @lucas-quinn-guru @ereztdev @ntraykov @Phunky
It's been awhile since this discussion was started. 
What approaches have you taken in the meantime?

I'm looking at next steps with this package and it would be helpful to have feedback about what direction you've taken in the absence of this feature so far.

**Comment by drbyte** [comment]
For named (string) role hierarchy, #440 offers a good option.

**Comment by esaesa** [comment]
It will be very handy to implement role can be assigned to role so parent role has all child role permissions. I already used such feature in other frameworks like Yii2. Here is a page with use case and implementation [Yii2 implementation](https://www.yiiframework.com/doc/guide/2.0/en/security-authorization)
