### ISSUE TITLE
There is no role named `admin` ???

### ISSUE THREAD

**Issue by echobool** [spatie/laravel-permission#686]
my code:
$user_id=1;
$user = User::find($user_id);
$roles = $user->getRoleNames();
            $roles->map(function ($role) use ($user) {
                $user->removeRole($role);
            });

auth file

'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
    ],

roles table
<img width="578" alt="qq20180312-212827 2x" src="https://user-images.githubusercontent.com/8441357/37286277-6e69f0c2-263c-11e8-9373-e31fd314e438.png">

model_has_roles table
<img width="291" alt="qq20180312-213026 2x" src="https://user-images.githubusercontent.com/8441357/37286362-a72c803c-263c-11e8-9538-f6a1ec4129bb.png">

**Comment by echobool** [comment]
Why I add to User Model

Protected $guard_name ='api';

Just fine


<img width="652" alt="qq20180312-215818 2x" src="https://user-images.githubusercontent.com/8441357/37287768-88637d28-2640-11e8-977f-ab7cf72b2170.png">


auth.php 
'defaults' => [
'guard' => 'api',
'passwords' => 'users',
], ？？？？？？？？？？？？？？

**Comment by drbyte** [comment]
I'm not sure I understand your post.

**Comment by SzymonLisowiec** [comment]
#Problem
OP emans, that `HasRoles` doesn't use default `guard` from `config/auth.php`.

I have in `config/auth.php`:
```php
'defaults' => [
     'guard' => 'api',
     'passwords' => 'users',
]
```

and seeder:
```
$role = Role::create(['name' => 'super-admin']);
$role->givePermissionTo(Permission::all());
```
The seeder will add "super-admin" role to `api` guard.

While using `$user->assignRole('super-admin');` is throwed error:
> There is no role named `super-admin`

and need add `protected $guard_name = 'api';` to model, to fix it.


# Reason
https://github.com/spatie/laravel-permission/blob/master/src/Guard.php#L49
`static::getNames($class)->first()` returns "web" despite default guard set on "api". Probably User model have guard defaults set on 'web'.

**Comment by canvural** [comment]
I had the same issue. Spent 1 hour wondering why it wouldn't find the role.

Like written, defining `guard_name` on model solves it. But this shouldn't be necessary.

**Comment by drbyte** [comment]
@canvural wrote:
> But this shouldn't be necessary.

I understand, and agree. We're rewriting a number of things for v3 and aim to improve this... particularly the way it handles guards. (Right now it looks to the model as the primary source of truth, and if not set there then falls back to other options based on configs.)

**Comment by kjdion84** [comment]
This is a bad idea:

	$role = Role::create(['name' => 'super-admin']);
	$role->givePermissionTo(Permission::all());

Because when new permissions are added, `super-admin` will not have perm.

It is much better to do this through Laravel Gate:

    Gate::before(function (User $user) {
        if ($user->hasRole('super-admin')) {
            return true;
        }
    });

**Comment by drbyte** [comment]
True, this is better: https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role

**Comment by danvim** [comment]
I am still experiencing this issue in v3 despite setting default guard in my config to api. I still need to add `$guard_name` to my `User` model.

Is this intended?

**Comment by drbyte** [comment]
> @drbyte I am still experiencing this issue in v3 despite setting default guard in my config to api. I still need to add `$guard_name` to my `User` model.
> 
> Is this intended?

Yes. v3 didn't get those sweeping changes. They haven't been completed yet.

For compatibility with Laravel's semantic numbering change, and other dependencies, we released v3 as basically v2 but with modern dependencies. This also allowed us to remove code required to patch for much older Laravel and PHP versions.
Apologies for any confusion. Numbering is sometimes hard :)

**Comment by danvim** [comment]
@drbyte Right. I was just confused since I saw the issue was closed and thought it has been fixed and released. If the issue is tracked somewhere else, that's fine. It's working with `$guard_name` anyway.

**Comment by Dictator1999** [comment]
@SzymonLisowiec
I had another guard alongsite api and web.
As you followed to add `$guard_name = "web"` property in User class, It work with web guard but **what about another guard (here my guard name is **customer**)?**
customer guard does not work.

**Comment by SzymonLisowiec** [comment]
> @SzymonLisowiec
> I had another guard alongsite api and web.
> As you followed to add `$guard_name = "web"` property in User class, It work with web guard but **what about another guard (here my guard name is **customer**)?**
> customer guard does not work.
Check it: https://docs.spatie.be/laravel-permission/v3/basic-usage/multiple-guards/

**Comment by Dictator1999** [comment]
I got a solution for this.

- [ ] Add `public static $guard_name = "customer"` or empty value of guard_name variable.
- [ ] Than before assignRole() method, Just rewrite `$guard_name` property as like this
       `User::$guard_name = 'guard name';`
- [ ] Than you can call asignRole() method. 
       `$user->assignRole("role name");`
Make sure the role has valid guard name..
Hope it will help you.

**Comment by jbricenoz** [comment]
Do not change the auto populate values in guard_name colunm, them declare into the **User.php** model 
`    protected $guard_name = 'sanctum'; `

**Comment by bajki** [comment]
> **This is on Laravel 8, using Jetstream.**
> 
> Do not change the auto-populated or default values added into the guard_name column,
> then just declare into the **User.php** model
> 
> ` protected $guard_name = 'sanctum';`
> 
> ![image](https://user-images.githubusercontent.com/8043209/107840419-32c1d900-6d78-11eb-8b81-eabb05210cda.png)
> 
> ![image](https://user-images.githubusercontent.com/8043209/107840387-f55d4b80-6d77-11eb-999a-4eb34259c794.png)
> 
> ` $role = Role::create(['name' => 'super-admin']); $role = Role::findByName('super-admin'); $role->givePermissionTo(Permission::all()); $user = auth()->user(); $user->assignRole("super-admin");`

Can you share your project?

**Comment by rickyanwar** [comment]
How if guard is use in both (api/web) ? i used `guard_name = *` but when assign to roles got error 

`There is no role named `
`The given role or permission should use guard `web, api` instead o`

![image](https://github.com/spatie/laravel-permission/assets/36995966/224a0cee-676a-4750-962e-d359b08b14f9)
![image](https://github.com/spatie/laravel-permission/assets/36995966/990b3be6-1902-437f-94bf-cd06711f1641)
