### ISSUE TITLE
How can I override UnauthorizedException?

### ISSUE THREAD

**Issue by alejandri** [spatie/laravel-permission#690]
Hi, when cache session closed, and refresh page. Show this message 

Spatie \ Permission \ Exceptions \ UnauthorizedException
User is not logged in.

From vendor\spatie\laravel-permission\src\Exceptions\UnauthorizedException.php
on this line:  return new static(403, 'User is not logged in.', null, []);

How I can redirect to another view (403.blade.php) on occurs this exception? Help please. Thanks

**Comment by drbyte** [comment]
This package's README contains an example already: https://github.com/spatie/laravel-permission#catching-role-and-permission-failures
