### ISSUE TITLE
Multi-customer multi-user roles

### ISSUE THREAD

**Issue by yougotnet** [spatie/laravel-permission#692]
I have a single application that has Customers with multiple Users per Customer.

How can I have a set of Roles for one Customer and a set of Roles for a different Customer (separately) that may or may not be the same, that are dynamically added by each Customer?

I'm really trying to create a hierarchy structure where Agents report to Managers that reports to Districts that report to Regions.  But to allow each Customer to create what each level title is.

**Comment by AlexVanderbist** [comment]
Hi @yougotnet, you're looking for multi-tenancy. If you want to support this you'll need some extra columns and custom models. There was an interesting thread about it here: #280.

Joseph Silber's Bouncer looks promising for multi-tenancy as well. You might want to look into that as well: https://github.com/JosephSilber/bouncer
