### ISSUE TITLE
Unknown column 'user_has_roles.model_id' 

### ISSUE THREAD

**Issue by dennis1502** [spatie/laravel-permission#696]
When changing the table names in the `config/permission.php`, the application crashes and gives me the follow error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_has_roles.model_id' in 'field list' (SQL: select `roles`.*, `user_has_roles`.`model_id` as `pivot_model_id`, `user_has_roles`.`role_id` as `pivot_role_id` from `roles` inner join `user_has_roles` on `roles`.`id` = `user_has_roles`.`role_id` where `user_has_roles`.`model_id` = 1 and `user_has_roles`.`model_type` = Modules\Users\Entities\User) 
``` 

In issue #577 there was another fix for the `permission_id` and `role_id`, but this one is harder.

Default the table name is `model_has_permissions` and `model_has_roles`, in V1 this was `user_`. Now I want to change this back, but the `model_` prefix is hardcoded in multiple files like `HasRoles.php` and `Role.php`

```
public function users(): MorphToMany
    {
        return $this->morphedByMany(
            getModelForGuard($this->attributes['guard_name']),
            'model',
            config('permission.table_names.model_has_roles'),
            'role_id',
            'model_id'
        );
    }
```
Please let me know how to safely change the table names. I can't work around with the current table names.

**Comment by drbyte** [comment]
Currently #577 is NOT in the code, as it caused breaking changes with multiple implementations.
It will be revisited as part of future major releases where breaking changes are acceptable.

In the meantime, you could for the repo, re-merge #577 and configure to suit your needs.

Or, if the feature-set of v1 still suits your needs, you could go back to using that version.
