### ISSUE TITLE
Specify the connection in the models

### ISSUE THREAD

**Issue by patogalarzar** [spatie/laravel-permission#697]
I'm getting the following error

`SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "permissions" does not exist LINE 1: select * from "permissions" ^ (SQL: select * from "permissions")`

But the permissions table does exist in the database. in my project I have multiple database connections two of Postgres and one of Mysql, so in the models I always specify the connection.

`   protected $connection = 'pgsql';
    protected $table = 'users';
`

In the past I had a problem similar to that reported with the user model, because I did not recognize which connection to use to bring the information from the database, but in this case I can not solve it in the same way (well, I can but I should not) because the models are in vendor folder and therefore out of version control.

there is some correct way of doing what I tell you, some way of modifying the models, or being able to specify the connection as the migrations with the artisan command

`php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"`

in the migrations I specify it in the following way

`Schema::connection('pgsql')->create($tableNames['permissions'], function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('guard_name');
            $table->timestamps();
        });`

What can I do? I'm waiting for your help.
Greetings.

**Comment by drbyte** [comment]
1. You haven't clearly stated which tables are found on which connections. It would be helpful to understand which data is stored on which connection and why. 

2. And also which connection is configured as primary (guessing it's mysql, from what you posted).

3. If you (temporarily for testing) add your connection property `protected $connection = 'pgsql';` to the `vendor/Spatie/Permission/src/Models/Permission.php` and `Role.php` models, does it solve your problem?

4. You only mentioned using this with the `User` model, which appears to be on your `pgsql` connection. Will there be other models you use this package on? and will their data be on the same connection?

**Comment by patogalarzar** [comment]
Hi thank you for answering.

1. Tables in postgres connection pgsql (main): users, permissions, roles, clients, suppliers, offices, etc.
gammu connection (secundria only for sending sms): inbox, outbox, sentitems, phones.
The mysql connection is to extract information from a previous system which is in process of migration but for workflows it is necessary to access this information.

2. The main connection is to postgres with the name pgsql.

3. Yes for test purposes, I specify the  connection property `protected $connection = 'pgsql';` to the `vendor/Spatie/Permission/src/Models/Permission.php` and `Role.php` models and it worked, I could read and write in the database.

4. Yes, there are going to be other models using this package, I only put users as an example because there I realized that I had to specify the connection in the model.

Having connections of postgres and mysql did not give me problems in the past, the problem started when I added the database of sms that is also in postgres.

I hope I have been able to answer all your questions so you can help me

**Comment by drbyte** [comment]
See PR #719 for an attempt at supporting this.

**Comment by patogalarzar** [comment]
Thank you for your help, I will apply your recommendation.

**Comment by kevinp1005** [comment]
@AlexVanderbist 
> You can always copy those models to your own codebase and update the permissions.php config file to use those models instead.

Hi, I have tried using this method and it can only get the data without relationship. 

These codes below works : 

```
MyCustomApp\Modesl\Permission:all();
MyCustomApp\Modesl\Role:all();
```

But this doesn't : 

```
Auth::user()->permissions;
Auth::user()->roles;

```

I tried to look into the code and its using `morphToMany` to get the **permissions**, so I'm not sure if its an issue with laravel or with the library, I haven't tested `morphToMany` relationship with multiple connections.

**Comment by JefferyWong** [comment]
Is this enhance not in the 3.13 release? I use version 3.13 and had same problem, searched and found this. but no db_connection in permission config. and not work after i added it.

**Comment by drbyte** [comment]
No, it was not merged: not needed.

You can simply extend the models and set the Eloquent `$connection` property there.
