### ISSUE TITLE
Route permission middleware incorrectly returns exception for user with authorised role

### ISSUE THREAD

**Issue by sheixt** [spatie/laravel-permission#701]
# The issue
When a user (with the correct role) attempts to visit a protected route,  they are presented with the following exception:

        Symfony \ Component \ HttpKernel \ Exception \ AccessDenied
        HttpException
        This action is unauthorized.

The route is protected by the use of the `permissions` middleware as follows:

    Route::group([
        'prefix'     => 'auth',
        'as'         => 'auth.',
        'namespace'  => 'Auth',
    ], function () {
        Route::group([
            'middleware' => 'permission:manage users',
        ], function () {
            // routes defined here
        });
    });

The strange thing is that the `super-admin` role can access these routes without issue. The other role type that should be able to access these routes is `admin` and it's this role-type which experiences the exception.

Below I've outlined how I've created the user, roles, permissions and assigned them for full disclosure. I presume I'm missing something?

# Background
I've used a seeder to generate a number of permissions, create a set of roles  and associated a differing number of permissions to each role.

Here' is an extract from the `PermissionRoleTableSeeder` seeder:

        $this->command->info('Generating Permissions');
        // Create Permissions
        Permission::create(['name' => 'view backend']);
        Permission::create(['name' => 'create surveys']);
        Permission::create(['name' => 'create attributes']);
        Permission::create(['name' => 'create templates']);
        Permission::create(['name' => 'manage users']);

        $this->command->info('Generating Roles');
        // Create Roles
        $super_admin    = Role::create(['name' => 'super-admin']);
        $admin          = Role::create(['name' => 'admin']);
        $supervisor     = Role::create(['name' => 'supervisor']);
        $user           = Role::create(['name' => 'user']);
        $participant    = Role::create(['name' => 'participant']);

        $this->command->info('Assigning Permissions to Roles');

        // ALWAYS GIVE ADMIN ROLE ALL PERMISSIONS
        $super_admin->givePermissionTo(Permission::all());
        $admin->givePermissionTo(Permission::all());

        // Assign Permissions to other Roles
        $supervisor->givePermissionTo([
            'view backend',
            'create surveys',
            'create attributes',
            'create templates',
        ]);

        $user->givePermissionTo('view backend');

The Users are created like so:

        $user = User::create([
            'first_name'        => 'Super',
            'last_name'         => 'Admin',
            'email'             => 'super@admin.com',
            'password'          => bcrypt('1234'),
            'confirmation_code' => md5(uniqid(mt_rand(), true)),
            'confirmed'         => true,
        ]);
        $user->accounts()->attach(1);

        $user = User::create([
            'first_name'        => 'Account',
            'last_name'         => 'Admin',
            'email'             => 'admin@account.com',
            'password'          => bcrypt('1234'),
            'confirmation_code' => md5(uniqid(mt_rand(), true)),
            'confirmed'         => true,
        ]);
        $user->accounts()->attach(1);

        $user = User::create([
            'first_name'        => 'Account',
            'last_name'         => 'Supervisor',
            'email'             => 'supervisor@account.com',
            'password'          => bcrypt('1234'),
            'confirmation_code' => md5(uniqid(mt_rand(), true)),
            'confirmed'         => true,
        ]);
        $user->accounts()->attach(1);

        $user = User::create([
            'first_name'        => 'Account',
            'last_name'         => 'User',
            'email'             => 'user@account.com',
            'password'          => bcrypt('1234'),
            'confirmation_code' => md5(uniqid(mt_rand(), true)),
            'confirmed'         => true,
        ]);
        $user->accounts()->attach(1);

        $user = User::create([
            'first_name'        => 'Some',
            'last_name'         => 'Participant',
            'email'             => 'some@participant.com',
            'password'          => bcrypt('1234'),
            'confirmation_code' => md5(uniqid(mt_rand(), true)),
            'confirmed'         => true,
        ]);

And then assigned a role here:

        User::find(1)->assignRole('super-admin');
        User::find(2)->assignRole('super-admin');
        User::find(3)->assignRole('admin');
        User::find(4)->assignRole('supervisor');
        User::find(5)->assignRole('user');
        User::find(6)->assignRole('participant');

In the database the tables `roles`, `permissions`, `role_has_permissions`, and `model_has_roles` are populated as expected. `model_has_permissions` is empty but as this is done via the `roles -> permissions` relationship, I presume this is to be expected?

After reading through the documentation, I have noticed that no cache file is created when the seeder is run. Is this expected? Just as I've run a few commands I assume the cache should be purged and recreated.
Could this be a related issue or am I misunderstanding how the role permission relationship works?

**Comment by drbyte** [comment]
Is the following inconsistency between "default_role" and "admin" just a mistake in posting example data, and not an error in your implementation? 

```
    // Create Roles
    $super_admin    = Role::create(['name' => config('access.users.admin_role')]);
    $admin          = Role::create(['name' => config('access.users.default_role')]);
```

```
    User::find(1)->assignRole(config('access.users.admin_role')); //'super-admin'
    User::find(2)->assignRole(config('access.users.admin_role')); //'admin'
    User::find(3)->assignRole('admin');
```

**Comment by drbyte** [comment]
> When a user (with the correct role) attempts to visit a protected route, they are presented with the following exception:
    Symfony \ Component \ HttpKernel \ Exception \ AccessDenied
    HttpException
    This action is unauthorized.

This is curious, since this package throws Spatie\...\[UnauthorizedException](https://github.com/spatie/laravel-permission/blob/master/src/Exceptions/UnauthorizedException.php) ... which gives a different error than you're quoting. 
Perhaps a different middleware is actually causing your problems?

**Comment by drbyte** [comment]
Question: is this manifesting in your test suite? or is it while clicking through the app in dev/prod? 
Reason for question: the test suite environment instantiates things very differently than the app does when being hit via the browser, which affects the order of how caching interacts with the auth/guard layer.
Context is important. Helpful to know the behavior encountered in both environments.

**Comment by sheixt** [comment]
Thanks for the prompt response.

I've amended the information to clarify

**Comment by sheixt** [comment]
I think I've wasted you time... After removing the `permissions` middleware the exception persists so I'm inclined to this the problem lies elsewhere! Thanks for your help and quick response.

Sorry for the inconvenience!
