### ISSUE TITLE
Permission throught role issue

### ISSUE THREAD

**Issue by MickaelViaud** [spatie/laravel-permission#703]
Hello,

I've seeded permissions through various roles and when I try to check the current user permissions, it doestn't work.

I've also try to clear the app cache without success. The issue seems to be similar to #702 

I already did this operation with older version of laravel-permission on L5.5 without any problem.

- user()->permissions : don't work
- user()->getAllPermissions() : work
- user()->can('PERMISSION_NAME') : don't work

Here is a screenshot of a result : 
![Code](https://i.imgur.com/Oo8TjZi.png)

**Comment by MickaelViaud** [comment]
#702

**Comment by drbyte** [comment]
> I already did this operation with older version of laravel-permission on L5.5 without any problem.

Which older version of laravel-permission? 
Is this new scenario also on L5.5 ?

**Comment by MickaelViaud** [comment]
I've made the same things (I think !) with L5.5 and Spatie 2.8.1 and it's working.

Here's all the process : 
1 - Creating manager guard on config/auth.php
```php
return [

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'manager' => [
            'driver' => 'session',
            'provider' => 'manager',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'manager' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

2- Seed user, role and permissions
```php
app()['cache']->forget('spatie.permission.cache');

// Create roles
$admin = \Spatie\Permission\Models\Role::create(['name'=>User::ROLE_ADMIN, 'guard_name'=>'manager']);
$writer = \Spatie\Permission\Models\Role::create(['name'=>User::ROLE_WRITER, 'guard_name'=>'manager']);
$moderator = \Spatie\Permission\Models\Role::create(['name'=>User::ROLE_MODERATOR, 'guard_name'=>'manager']);

// Creating permissions
$handleUsers = Permission::create(['name'=>User::PERMISSION_USER, 'guard_name'=>'manager']);
$handleForum = Permission::create(['name'=>User::PERMISSION_FORUM, 'guard_name'=>'manager']);
$handleContent = Permission::create(['name'=>User::PERMISSION_CONTENT, 'guard_name'=>'manager']);

$admin->givePermissionTo(
    $handleUsers,
    $handleForum,
    $handleContent
);

$writer->givePermissionTo(
    $handleContent
);

$moderator->givePermissionTo(
    $handleForum
);

// Assign default super-admin account to super-admin role
$userSuperAdmin = User::where("email", "admin@site.com")->first();
if (!empty($userSuperAdmin)) {
    $userSuperAdmin->syncRoles($admin);
}
```
3- Make guard manager to route group
```php
Route::group([
    'middleware' => ['manager', 'auth:manager'],
    'namespace'  => $this->namespace,
], function ($router) {
    require module_path('manager', 'Routes/manager.php');
});
```
4- Auth work
![Auth](https://i.imgur.com/CZtusIs.png)
5- In a controller behind guard
```php
dd(
	'user()->permissions',
	Auth::guard('manager')->user()->permissions,
	'user()->getAllPermissions()',
	Auth::guard('manager')->user()->getAllPermissions(),
	'can '.User::PERMISSION_USER,
	Auth::guard('manager')->user()->can(User::PERMISSION_USER, 'manager'),
	'user()->hasPermissionTo(\''.User::PERMISSION_USER.'\')',
	Auth::guard('manager')->user()->hasPermissionTo(User::PERMISSION_USER, 'manager')
);
```

Which give the screen posted before :( 

Thanks !

**Comment by drbyte** [comment]
In your local test environment, can you try out the changes I made in this PR, which addresses your `can()` issue:  https://github.com/spatie/laravel-permission/pull/704/files

**Comment by MickaelViaud** [comment]
Ok, 

So I update my other project to L5.6 with the latest version of laravel-permission and it' still working ! So the problem come to my code :( 

The only difference, I think, with my other project is that my guard manager use other entity and table than the web guard. I'll make a try.

**Comment by MickaelViaud** [comment]
@drbyte Found it !

When two guards use the same Model class, can() don't work. Maybe he is trying to fetch the first registered guard with the class ?

Did I open another issue @AlexVanderbist ?
