### ISSUE TITLE
givePermissionTo returns error "model_id" violates not-null

### ISSUE THREAD

**Issue by fmsouza1990** [spatie/laravel-permission#705]
Hi guys,

I'm starting my laravel studies and I'm trying to implement acl, I've already performed all the documentation steps, I've been able to create roles and permissions, but I can not assign permissions or roles to a user, or assign permissions to a role.

- The code that I implemented is the following

**public function setPermission(User $user){
          $user->givePermissionTo('write');
}**

- The error displayed is as follows

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "model_id" violates not-null constraint DETAIL: Failing row contains (1, App\User, null). (SQL: insert into "model_has_permissions" ("model_id", "model_type", "permission_id") values (, App\User, 1))

I'm using laravel 5.6 and laravel-permission 2.9, has anyone had this problem and could you help me solve this problem?

I thank the attention.

**Comment by drbyte** [comment]
It seems like you haven't persisted your $user object to the database yet. Perhaps you're using `User::make()` (which only creates objects in memory), but should be using `User::create()` (which creates objects and saves them to the database)?

**Comment by cristophernando** [comment]
Hi Guy.
I have a similar problem. When I'm trying to do migration I have a SQL ERROR.

`  Illuminate\Database\QueryException  : Error Code    : 1400
Error Message : ORA-01400: cannot insert NULL into ("MYDATABASE"."MODEL_HAS_ROLES"."MODEL_ID")
Position      : 77
Statement     : insert into "MODEL_HAS_ROLES" ("MODEL_ID", "MODEL_TYPE", "ROLE_ID") values (:p0, :p1, :p2)
Bindings      : [,App\Laravue\Models\User,3]
 (SQL: insert into "MODEL_HAS_ROLES" ("MODEL_ID", "MODEL_TYPE", "ROLE_ID") values (?, App\Laravue\Models\User, 3))`

I just modify the USER Model to this ->

` class User extends Authenticatable implements JWTSubject
{
    use Notifiable, HasRoles;

    protected $table = 'SEG_USUARIO';

    protected $primaryKey = 'ID_WEB';

    public $timestamps = false;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
       'USR_LOGIN', 'USR_NOMBRE', 'USR_APELLI', 'USR_EMAIL', 'USR_PASWRD'
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    protected $hidden = [
        'USR_PASWRD',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'USR_FECCRE' => 'date',
    ];

    /**
     * Set permissions guard to API by default
     * @var string
     */
    protected $guard_name = 'api';

    /**
     * @inheritdoc
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * @inheritdoc
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    /**
     * @return bool
     */
    public function isAdmin(): bool
    {
        foreach ($this->roles  as $role) {
            if ($role->isAdmin()) {
                return true;
            }
        }

        return false;
    }

    public function getAuthPassword(){
        return $this->USR_PASWRD;
    }
}
`

Any idea what I'm doing wrong??
Thanks.

**Comment by drbyte** [comment]
What’s your migration code?

Your model_id is null, which could be because you’re trying to give permissions to a User you haven’t created (saved) yet.
