### ISSUE TITLE
[Question] list multiple users and their permissions

### ISSUE THREAD

**Issue by jorgeTCC** [spatie/laravel-permission#706]
Good evening.

How do I list the permissions of multiple users?

For example, I am listing the return of user id [1,2,3]

How to list user id and permission name?

Example: [('1' => 'Administrator', '2' => 'Administrator', '3' => 'Contributor')]

**Comment by drbyte** [comment]
From the Readme:

---
// get a list of all permissions directly assigned to the user
`$permissions = $user->permissions;`

// get all permissions inherited by the user via roles
`$permissions = $user->getAllPermissions();`

// get a collection of all defined roles
`$roles = $user->getRoleNames();` // Returns a collection

---

So you could loop through your users, and use one of the above methods to obtain their permissions or role names.
