### ISSUE TITLE
User Edit requires new password and has 'Add' button

### ISSUE THREAD

**Issue by stevenhillsr** [spatie/laravel-permission#708]
Just installed latest laravel-permissioin and I am seeing that a new password must be entered if you edit a user. I think this should not be the case. Also, the edit page's submission button is 'Add' rather than 'Save'.

The button text is a simple change in the user.edit view. The required password would be a bit more involved, changing the validation rule to 'nullable' rather than 'required' and then setting the $input variable based on password having a value other than null. I can make these changes here locally, but as I anticipate using this package in the future I would rather they be made to the package.

**Comment by drbyte** [comment]
This package doesn't do anything with user passwords or page-submit buttons. Those are all in your app's domain.
