### ISSUE TITLE
[Question] Unable to assignRole due to Integrity constraint violation

### ISSUE THREAD

**Issue by k3vin023** [spatie/laravel-permission#709]
Hello,

When trying to do the `$user->assignRole('admin')`  the error is showing `SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails` what do I need to check in my database?

**Comment by drbyte** [comment]
The `assignRole` method adds records to the `model_has_roles` table in relationship to the `roles` table entries.

In what ways have you altered the table structures or added foreign keys connecting this package's tables to other tables?

**Comment by k3vin023** [comment]
I just figured out that I put the wrong foreign key to my model_has_roles and to my users table.

**Comment by drbyte** [comment]
Why did you add more foreign keys?

**Comment by k3vin023** [comment]
Because I have roles and users table before and altered it for some functionalities needed in my project. Because I never thought of using this package before. I just only rely on user role_id. A huge thanks for spatie for making this easy

**Comment by drbyte** [comment]
> Because I have roles and users table before

Okay, that makes sense.
Yes, in that case you'd need to customize the migrations to match up to your existing table.

**Comment by k3vin023** [comment]
> Yes, in that case you'd need to customize the migrations to match up to your existing table.

Correct. I just realized that it's a must to match the migrations
