### ISSUE TITLE
Seed Error

### ISSUE THREAD

**Issue by sagearslan** [spatie/laravel-permission#71]
I have a seeder which truncates the Users table, but when I run `artisan db:seed`, I get this error message:

```
[Illuminate\Database\QueryException] 
SQLSTATE[42000]: Syntax error or access violation:
1701 Cannot truncate a table referenced in a foreign key constraint (`mydatabasename`.`user_has_permissions`, CONSTRAINT `user_has_permissions_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `mydatabasename`.`users` (`id`)) (SQL: truncate `users`)
```

I've managed to get around it by disabling and reenabling foreign_key_checks around the truncate method.

```
DB::statement('SET FOREIGN_KEY_CHECKS = 0');
DB::table('users')->truncate();
DB::statement('SET FOREIGN_KEY_CHECKS = 1');
```

Is there better way of addressing this issue?

**Comment by sebastiandedeyne** [comment]
Not really, this is always the case when truncating tables that have foreign keys.

**Comment by inzig** [comment]
facing the same error.

**Comment by drbyte** [comment]
@inzig wrote:
<img width="792" alt="screen shot 2018-08-28 at 9 25 35 am" src="https://user-images.githubusercontent.com/404472/44725846-60c9da80-aaa4-11e8-8304-c7db35604c73.png">

As @sebastiandedeyne wrote, that is something you must resolve in your app. It's not a problem with this package.
The solution posted by @sagearslan is a good way to deal with it.
