### ISSUE TITLE
How to assign multiple users with a role at one times?

### ISSUE THREAD

**Issue by zong0828** [spatie/laravel-permission#712]
I need to assign all user with student role at one time, but i cant find a useful method to solve it. 
This is my method, but it doesnt work. ($user and $userinfo are array)
```
$createuser=User::insert($user); 
$createuser->assignRole('student');
$createuserinfo=UserInfo::insert($userinfo);
```
Only get

>  Call to a member function assignRole() on boolean

This is my function to upload excel.

```
public function excelUpload(Request $request){

         if($request->hasFile('ex_file')){
             $updateFile = $request->file('ex_file');
             $fileExtension = $updateFile->getClientOriginalExtension();
              if ($fileExtension == "xlsx" || $fileExtension == "xls" || $fileExtension == "csv") {
                $path = $request->file('ex_file')->getRealPath();
                $data = Excel::load($path)->get();
                 if($data->count()){

                    foreach ($data as $key => $value) {
                    $compare_user= $this->UserRepository->getSutdentdata($value->s_id);

                        if($compare_user->isEmpty()){
                            $user[]=['s_id'=>$value->s_id,'r_id'=>1,'name'=>$value->name,'email'=>$value->email,'password'=>bcrypt($value->usn) ];

                            $userinfo[]=['school_id'=>$value->s_id,'semester'=>$value->semester,'USN' => $value->usn ,'phone'=>$value->phone,'address'=>$value->address,'Department'=>$value->department];
                        }
                    }

                    if(!empty($user) &&!empty($userinfo) ){
                        $createuser=User::insert($user); 
                        $createuser->assignRole('student');
                        $createuserinfo=UserInfo::insert($userinfo);

                        dd($user); 
                    }

                }
              }else{
                dd('wrong fomat'); 
              }
         }
         return "nofile";
    }

```
Do you have any suggestion to design it ?

**Comment by drbyte** [comment]
In your app it appears you may have a typo. Was this intentional?

`getSutdentdata`

```diff
-                    $compare_user= $this->UserRepository->getSutdentdata($value->s_id);
+                    $compare_user= $this->UserRepository->getStudentdata($value->s_id);
```

**Comment by zong0828** [comment]
@drbyte  LOL 	
I didn't notice this. Thank you! But this function name also called getSutdentdata. Therefore, i think it is not the reason to cause assign role error.

**Comment by drbyte** [comment]
`User::insert()` will return a boolean in some cases.

Why aren't you using the standard `User::create([array $data])`. This will return the object of the created user, which you can then run `assignRole` against.

**Comment by drbyte** [comment]
Your SQL error shows only the timestamp fields being inserted. This tells me there's a logic error in your code. 

Upon further inspection, I see you're filling `$user` as an array of users, but then trying to `insert` it as an array of new users.
Why not move your create-user logic up inside your if(compare_user) loop? You wouldnt' need the empty() check then either would you?

**Comment by NiDo0o** [comment]
Can Anyone share the link...I am new to laravel and want to use spatie(laravel-permission) in my project and I just install it...I dont have any idea how to do it now So I want to watch a video But i not find a single video on youtube..
Kindly Help me

**Comment by drbyte** [comment]
Hi @NiDo0o 
It's best to start a "New Issue" (see green button in the top right of the page) if your question is not directly related to the specific subject of another conversation, such as this one. 

That said, the README does explain the basics quite well, and if you'd like to see an example implementation of it, check out my demo repository at: https://github.com/drbyte/spatie-permissions-demo/commits/master ... if you look at those commits in reverse order you can see me building up the app step by step. It's not a video, but it is real code. 

If you have other questions, please start a new Issue for that discussion. Let's not hijack this current one ;)

**Comment by NiDo0o** [comment]
Thankyou Soo Much @drbyte 
I am following what you have done...It's a great effort And will start the new issue If i am getting problems
