### ISSUE TITLE
[QUESTION] Redirect to 404 page when user has no permissions

### ISSUE THREAD

**Issue by k3vin023** [spatie/laravel-permission#713]
I have controlled the permission through my routes and it is working, but then, I want the user to see a 404 page instead of the laravel error page.  How do I know if the user got permission for this specific route? here is my code:

```
Route::group(['middleware' => ['permission:View Dashboard Chart']], function () {
    //
    Route::get('/', 'DashboardController@index');
    Route::get('/dashboard', 'DashboardController@index');
});
```

**Comment by drbyte** [comment]
This package's [middleware](https://github.com/spatie/laravel-permission/blob/master/src/Middlewares/PermissionMiddleware.php#L27) will thrown an [UnauthorizedException](https://github.com/spatie/laravel-permission/blob/master/src/Exceptions/UnauthorizedException.php) which includes the name of the requested permission for which they were not authorized.
