### ISSUE TITLE
This action is unauthorized. Middleware with multiple roles listed

### ISSUE THREAD

**Issue by perffy** [spatie/laravel-permission#714]
Hi guys,

I have just installed this nice package and now i am trying to get used with it, but I got stacked in one situation.

I have three roles: administrator, executive and user. Some of my routes are only accessible for administrator, so I protect them like this:

```
Route::group([ 'middleware' => ['role:administrator']], function () {
	// routes
});
```
This works fine if I try to access the routes logged in as administrator and it gives me the view, if I try to access this routes as executive, it gives me an Spatie/Permission/UnauthorizedException, which is correct.

But if I get access to that routes to both roles: administrator and executive like this:

```
Route::group([ 'middleware' => ['role:administrator|executive']], function () {
	// routes
});
```
When I am logged in as executive I get:
Symfony \ Component \ HttpKernel \ Exception \ AccessDeniedHttpException
This action is unauthorized.

The question is, what I am doing wrong ?

**Comment by drbyte** [comment]
I'm guessing you have something else firing before it, either a different route group defined for that same route action or a different middleware interrupting.

**Comment by drbyte** [comment]
Did you get this sorted?

**Comment by perffy** [comment]
Unfortunately i havent tried anymore.
Now i have installed the https://github.com/rappasoft/laravel-5-boilerplate, in which is included the Spatie/Permission package and there i have tried the same thing and i get the same error.

**Comment by drbyte** [comment]
Are you getting these errors via FeatureTests? Or by actually using the browser?

**Comment by perffy** [comment]
By using the browser

**Comment by gamevnlc** [comment]
Same issue like this. 
Do you have any idea how to fix it ?

**Comment by gamevnlc** [comment]
nvm I found the problem. There is some config in request file. it cause the problem

**Comment by SBeausoleil** [comment]
I have the same problem. @gamevnlc Did you fix this by installing the laravel5-boilerplate or did you fix it without that plugin?

**Comment by gamevnlc** [comment]
@SBeausoleil 
I fixed it without plugin.  My issue is that I don't specific the role in the authorize method in my custom request.

**Comment by drbyte** [comment]
I'm pretty certain your `AccessDeniedHttpException` is coming from something outside the operation of this package.

**Comment by nimeshc64** [comment]
> Unfortunately i havent tried anymore.
> Now i have installed the https://github.com/rappasoft/laravel-5-boilerplate, in which is included the Spatie/Permission package and there i have tried the same thing and i get the same error.

after you give middlware permisson you need change ManageUserRequest -> authorize()
`return $this->user()->isAdmin();`
to 
`return $this->user()->can('YOURE_PERMISSION');`
