### ISSUE TITLE
Why default guard doesn't work?

### ISSUE THREAD

**Issue by johncloud200** [spatie/laravel-permission#722]
I have set my default config/auth/guard to **api**
```
'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
    
    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'jwt',
            'provider' => 'users',
        ],
    ],
```

- `app('auth')->user()->hasPermissionTo('cars.read')` return "There is no permission named `cars.read` for guard **`web`**."

- `app('auth')->user()->can('cars.read')` return **false**

- although `$user->getDirectPermissions()` have that permission

will be work as expected if I add explicit $guard_name="api" on UserModel

**Comment by drbyte** [comment]
Currently this package treats the model's `$guard_name` property as the authority, not the `config` array.

We will probably switch to using the config array as first authority after a rewrite for v3.

In the meantime, I've found that using `auth('api')->user()->can()` will return expected results for `api`.

**Comment by gitBC** [comment]
@drbyte Was just looking at a similar problem. I wanted to propose that you also read the config value instead from the config/permission.php file first as opposed to the Laravel defaults so that it can be overridden 

`public static function getDefaultName($class): string
    {
        //$default = config('auth.defaults.guard');
       $default = isset( config('permission.default_guard') )  ?    config('permission.default_guard'  : config('auth.defaults.guard') ;

        return static::getNames($class)->first() ?: $default;
    }`

**Comment by drbyte** [comment]
Yes, that could be done. In fact a few PRs have come and gone for variations of that. But I'm pretty sure that would be a breaking change for people who have coded their apps to work with the way things are right now.
