### ISSUE TITLE
Multiauth not detect user

### ISSUE THREAD

**Issue by ssheduardo** [spatie/laravel-permission#723]
Hi,
I have multi auth (tables: users and admin), the login is correct and the creation the permission and roles is correct.

**model_has_role**
![image](https://user-images.githubusercontent.com/1160138/39201132-5fbc0938-47ee-11e8-88fb-6c144134d367.png)

**permissions**

![image](https://user-images.githubusercontent.com/1160138/39201197-894a0890-47ee-11e8-9392-aed0aa89883a.png)

Everything is great
But in my view, I can uses @role, added guard  this not return true and not show the string.
Ex.
```
@role('view_orders', 'admin')
    My string
@endrole
```
This return empty, the condition is not valid

But I uses this

```
@if(auth('admin')->user()->can('view_orders'))
    Hi, It's demo
@endif

```
The text show: **Hi, It's demo**

Where are the problem?

**Comment by drbyte** [comment]
Does `App\Entities\Admin` have a `protected $guard = 'admin';` property defined?

**Comment by ssheduardo** [comment]
Yes

![imagen](https://user-images.githubusercontent.com/1160138/39211270-6c085ad0-480b-11e8-8970-a0ed3280b26e.png)

**Comment by ssheduardo** [comment]
Some help?

**Comment by drbyte** [comment]
`@role()` requires a role name, not a permission name. In your example, you said you're using `@role('view_orders', 'admin')` but `'view_orders'` is a permission, not a role.

**Comment by ssheduardo** [comment]
I made a mistake,
Is not role is **can**
```
@can('view_orders', 'admin')
    My string
@endcan
```
If apply the befor code , return false but 

```
@if(auth('admin')->user()->can('view_orders'))
    Hi, It's demo
@endif
```
Return true.

**Comment by drbyte** [comment]
@ssheduardo I'm pretty sure it's finding the wrong guard because of the order of lookup, as explained in https://github.com/spatie/laravel-permission/issues/72
