### ISSUE TITLE
No support for multiple database

### ISSUE THREAD

**Issue by shijosap** [spatie/laravel-permission#728]
I have user table in different database and permissions ans roles in another database. Getting users with specific roles doesn't work in this scenario.

**Comment by drbyte** [comment]
You could extend the package using customizations like I made in #719 related to #697

**Comment by adminlacaq** [comment]
Yes it's possible !

First of all, you'll have to create 2 files 
App\Models\Auth\Role.php
App\Models\Auth\Permission.php

Those files need to extend the Spatie Model like 

class Role extends \Spatie\Permission\Models\Role
class Permission extends \Spatie\Permission\Models\Permission

And then you specify your default connection within the new created class file

protected $connection = 'mysql';

You'll need to change your config/permission.php to specify the new class
'permission' => App\Models\Auth\Permission::class,
'role' => App\Models\Auth\Role::class,


in your User Model, you specify your other DB like 
protected $connection = "name_of_your_other_db"

Dont forget to modify you config/database.php accordingly 

So with that modification, your user's informations are pulled from database x and the permissions/roles are set in database y with the reference id of database x

I hope that was helpful :)

**Comment by asadbek-fayzulloev** [comment]
Thank you! I did same, it is working now. But there is other case. $query = $query->role($role_name); Undefined table: 7 ERROR:  relation \"model_has_roles\" does not exist
