### ISSUE TITLE
 How to return the controller without permission？

### ISSUE THREAD

**Issue by PerJoy** [spatie/laravel-permission#731]
I've created two roles. `Administrator` and `Maintainer`.
`Administrator` have all permissions,
`Maintainer` just have part Permissions.

 Now I want to use Maintainer role access URL and prompt no permissions.

Currently is a function in each controller using the hasPermissionTo function.

Is there a better solution？

**Comment by drbyte** [comment]
I'm not sure I fully understand your question.

If you don't want to put the code in your controller, then use middleware in your routes: `role:Maintainer`

Alternatively you could use model policies.
