### ISSUE TITLE
<Question> Roles + Permissions + **Groups**? 

### ISSUE THREAD

**Issue by ereztdev** [spatie/laravel-permission#735]
Hi,

We really like your package out of the box, yet we are trying to achieve the following:

Each user gets associated with a role+group; Like in real life, for example your role is backend developer, and you are part of the r&d group, as a result your job is different than someone in the same r&d group with a different role (or different group).

>ATM - we are using roles + permissions, yet trying to harness guard_name to be our "group", while using only the User model (not extending User).

As Laravel ships out with web & api, would it make sense to amend `config/auth.php` to the following:

```
 'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
        'sales' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],
```
Please let me know if more detail is needed in order to achieve what we need.

Thanks.

**Comment by drbyte** [comment]
As of v2.8.0 of this package, guard-matching is done in the following order:
1. `protected $guard_name` on the model
2. `config` lookups for `auth.guards` where `auth.providers` has a guard defined for the model
3. `config` for `auth.defaults.guard`

https://github.com/spatie/laravel-permission/blob/master/src/Guard.php#L15-L50

I'm aware that many people would prefer to rely on `auth.defaults.guard` so they can programmatically set it and depend on it as the first match, particularly in some middleware processing, amongst other places. I'm hoping we can make that change as part of a future update without it being a backward-compatibility mess.

Does that help answer your question?

**Comment by ereztdev** [comment]
Thanks for the quick reply @drbyte, I'll go ahead and try it out.
So i'll require the version like this? 
`"spatie/laravel-permission": "^2.8.0"`

Please let me know if 2.8.0 is stable, I can't find any documentation on that version

**Comment by ereztdev** [comment]
@drbyte  - I am I looking to register multiple guard types on User model, would that be even possible?

So if I create `protected $guard_name` on User, there can be only 1 guard_name, yet I was asking about implementing multiple guards on 1 model (User).

To reiterate what I was asking before: 
I am looking to have permissions rely on 2 conditions role and group, I thought I could somehow use guard_name as a group.

Let me know, thx

**Comment by drbyte** [comment]
You can use the latest version. I was just pointing out that it's been that way since v2.8.0.

**Comment by drbyte** [comment]
@ereztdev wrote:
> I am looking to have permissions rely on 2 conditions role and group, I thought I could somehow use guard_name as a group.

How are you utilizing the guard to differentiate users now? ie: for your `sales` group (or r&d in your other example), are you using (or planning to use) `sales` as ...
- blade filters via `can` rules?
- routing?
- middleware filtering?

To be sure we're looking at your objective from the same angle, do you have example code or an example app you could post to a repo? 
I understand your wish to do additional groupings, but would like to see how you are wishing to implement it with guards.

**Comment by ereztdev** [comment]
Re the code sorry in advance but we can't share our repo or part of it.

 We saw guard_name appearing as a key in a few tables in spatie so we just
thought of utilizing it as a conditional to differentiate same roles that
would have differebt group policies, or vice versa i.e. a sales manager and
a sales associate would have different roles yet share much of the common
permissions, on the flipside you can have a compliance associate and a
sales manager that could also share many common permissions on a group (or
c-level execs to that same example) and a minor amount of exclusions, it's
just another  intersection level that would make non-common roles share a
common group policy and provide more clarity, less code writing and clutter.

**Comment by ereztdev** [comment]
@drbyte edited my answer to better reflect your question.

**Comment by drbyte** [comment]
Thanks. 
From your various posts I get the sense that you're not already using any guards other than the defaults of `web` and `api`. Is that correct? 
And you're using this package currently in some form, but I guessing without any leveraging of its guard support?
Or am I misreading where you're at currently?

I'm trying to ascertain what you're ultimately asking for here. Are you asking:
- "How do we start adding guards to our application?"
- "We have a few guards; how do we wire them up to this package?"
- "How can we refactor our group policies to be enforced by guards and middleware?"
- "We would like to expand our existing use of guards to provide group policies. How?."

I'm happy to help. Just trying to know what direction to go.

**Comment by ereztdev** [comment]
@drbyte - did not abandon thread, waiting for decisions to be made if we will use groups or not.

In the meantime, can you be kind to share a few links of examples on how Roles is extended? 
I went over `Spatie\Permission\Models\Role` and it's Contract , (plz don't link the git readme :) ) if you know of some sort of fork or other source that I would be able to understand how far my options can go re extending roles / permissions would be greatly appreciated.
Many thanks.

**Comment by drbyte** [comment]
@ereztdev Did you sort out your need for groups or extending code?

**Comment by drbyte** [comment]
Great! That sounds like it's probably even more flexible that the original direction of this thread.
Plus if we add some sort of hierarchical structure or prefixing in a future version that might naturally tie into what you're already doing.
