### ISSUE TITLE
Limit user to a selected role at login, even if other roles are assigned

### ISSUE THREAD

**Issue by enricouniurb** [spatie/laravel-permission#738]
Hi,
 I have this use case, and I'm new user of spatie/laravel-permission

A user can have multiple roles for instace admin and writer, but he can choise to be only one at time.
The user have only one user name and password.

How can approach this scenario?

Thank you in advance
Enrico

**Comment by drbyte** [comment]
Hi @enricouniurb , 
This package currently responds to all role/permission requests equally. ie: it doesn't exclude "admin" under certain conditions.

In your example you listed 2 roles, but 
Are you wanting the user to choose 1 role from 2-5 options, and have only the rights associated with that 1 role? Where would you want them to choose that?
Or are you specifically wanting to treat "admin" different from "everything else"?  

The approaches for each may be different. I'd like to understand your need better.
