### ISSUE TITLE
getRoleNames() - With examples, not working, why?

### ISSUE THREAD

**Issue by pxpm** [spatie/laravel-permission#740]
Hi there.

Hope you doing great, i hope you can explain me the behavior to get user roles.

if i do:

```
$user = auth()->user();

$userRoles = $user->roles()->get(); 

OR

$userHasRole = $user->hasRole('role');

```
It works as expected.

Otherwise, if i do:

```
$user = auth()->user();

$userRoles = $user->getRoleNames(); 

```
I get exception:

`Call to undefined method Illuminate\Database\Query\Builder::getRoleNames()`

I tried with:

```
Auth::user();

UserModel::find(1);

UserModel::where('id',1)->first();

```

Thanks in advance.

Have a nice day,
Pxpm

**Comment by drbyte** [comment]
`getRoleNames()` was added in v2.5.1 and is part of the `HasRoles` trait:
https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L206

Perhaps you're using a very old version?

**Comment by pxpm** [comment]
Sure .. That was the problem. 

Thanks @drbyte
