### ISSUE TITLE
Permissions are not working correctly.

### ISSUE THREAD

**Issue by shahbazk9** [spatie/laravel-permission#744]
Hello.

I'm facing a weird issue. I have two roles for my app (Admin and User). Admin has all the permissions (edit role, create role, delete role etc) and User has no permissions. When i call the $user->hasPermissionTo('edit role') where the $user is currently authenticated user has Admin role, it returns true which is correct. But when i delete (edit role) permission from my database, that method always returns true. I'm wondering what is the issue?

**Comment by drbyte** [comment]
Sounds like you're doing a manual delete from the database, but not clearing the package's cache, and therefore you're getting the cached results back.
