### ISSUE TITLE
variable user roles / permissions

### ISSUE THREAD

**Issue by fake-fur** [spatie/laravel-permission#745]
hi - not sure that's the correct way to refer to what i'm asking but essentially suppose you had users who could do things at different companies, and you needed to have user roles / permissions specific to each company they are employed by, could this package handle that? or is this for a single "global" set of user roles / permissions?

i hope i managed to explain that in a way that makes sense, and thanks for a great package btw

**Comment by fake-fur** [comment]
thanks again but it's a multi-tennant single database so i think this is difficult to do with this package no?

i think my requirement is not so usual

**Comment by drbyte** [comment]
Context question: can you explain "why" these users have permissions on other tenants?
(I don't know for certain, are they "administrators"? are they employees of multiple tenants? Are they IT support techs who need certain access across tenants? Are they traveling professors who need certain permissions at multiple places where they teach?)

Will the permissions across tenants be "identical"? ie: will user A have exactly same permissions in company X and company Y? Will user B also have exact same permissions as user A, just maybe with company Z and X?

I don't know if it matters, but this context info may help in considering implementation approaches.

**Comment by fake-fur** [comment]
>Context question: can you explain "why" these users have permissions on other tenants?
>(I don't know for certain, are they "administrators"? are they employees of multiple tenants? Are >they IT support techs who need certain access across tenants? Are they traveling professors >who need certain permissions at multiple places where they teach?)

a user may work at different sites in different roles (here i use role to mean a set of permissions), and so will need a separate set of permissions for each "tennant"

>Will the permissions across tenants be "identical"? ie: will user A have exactly same permissions >in company X and company Y? Will user B also have exact same permissions as user A, just >maybe with company Z and X?

there would be a system-wide set of permissions for the app (which would grow as more functionality is added) that roles are made from, so yes global set of available permissions but no a given user can have (in theory) completely different permissions in one tennant from another tennant

again thanks very much for taking time to respond to me
:)

**Comment by drbyte** [comment]
I feel like this package could work for that. 
I imagine you've probably already extended the User model to store a specific tenant id for each User. Therefore I'm guessing these cross-tenant Users have multiple almost-identical User records.
So the normal installation of this package by adding the HasRoles trait to this model will probably be sufficient.

**Comment by fake-fur** [comment]
a user can belong to many tenants

**Comment by drbyte** [comment]
How do you control access for those users, per tenant, now?

**Comment by fake-fur** [comment]
they are currently all in individual databases

**Comment by drbyte** [comment]
Earlier you said:
>  it's a multi-tennant single database

**Comment by fake-fur** [comment]
the old system is many single tenant databases - the new system in a single multi-tenant database

**Comment by drbyte** [comment]
Okay. Then you've got a pivot table for Users-to-Tenants, and probably a corresponding Model.
You could extend things to leverage this package to work with that.
I don't have code samples for you, but I think that's the direction I'd suggest exploring for now.

Alternatively, if that becomes too complex, you could look at the [JosephSilber/Bouncer](https://github.com/JosephSilber/bouncer) package. It has some multi-tenant features, but implements roles and permissions in a different way than this package does.

**Comment by fake-fur** [comment]
yes but it got really messy trying to maintain a 3 way join table and get lazy loading working in a way that didn't mangle my brain

thanks so much for your thoughts and input - it really is invaluable
:)

**Comment by drbyte** [comment]
You're welcome.

Hopefully something in our conversation will lead to an eventual solution.

Do we need to keep this Issue open?
