### ISSUE TITLE
Class Inheritance and `model_has_*` for Roles (and probably Permissions too)

### ISSUE THREAD

**Issue by lloy0076** [spatie/laravel-permission#749]
### Issue

I have some classes:

```
class \App\User {}
class \App\EmailOnlyUser extends User()
```

Do:

```
$user = new \App\User();
$user->id = 1;
$user->save();

$user->assignRole('admin');

$emailUser = \App\EmailOnlyUser()->find(1); // This gets the above user BUT it's using the sub-class

if ($user->hasRole('admin') === false) {
  die('Why are we not an admin?');
}
```

You'll get **Why are we not an admin?**

### Expected Behaviour / Desired Behaviour

It would be nice if the sub-class "inherited" the roles of the parent.

** Note:** I don't believe this is the same as #685 - I'm not looking for a hierarchy of roles.

### Why does this occur?

It occurs because the query to get the roles uses the class name of `$this` when looking up the `model_has_roles`, see:

```
>>> $user->roles()->toSql()
=> "select * from `roles` inner join `model_has_roles` on `roles`.`id` = `model_has_roles`.`role_id` where `model_has_roles`.`model_id` = ? and `model_has_roles`.`model_type` = ?"
>>> $user->roles()->getBindings()
=> [
     194,
     "App\EmailOnlyUser",
   ]
```

But I want that toe be `App\User` and *not* `App\EmailOnlyUser` 😞 

### Possible Fixes

* Should the checks climb the PHP object inheritance hierachy?
* If so, should that be configurable (probably not default, at least at first, because it might change current apps)?
* Is this expected behaviour (i.e. this isn't a bug)?

### Version Info

2.12

 `"spatie/laravel-permission": "^2.12"`

**Comment by drbyte** [comment]
There's a caching layer that may be causing you to see the unexpected results.
Does this make any difference?

```diff
$user->assignRole('admin');

$emailUser = \App\EmailOnlyUser()->find(1); // This gets the above user BUT it's using the sub-class

-if ($user->hasRole('admin') === false) {
+if ($user->fresh()->hasRole('admin') === false) {
  die('Why are we not an admin?');
}
```

**Comment by lloy0076** [comment]
It has nothing do do with caching - the underlying table(s) have:

```
INSERT INTO `model_has_roles` (`role_id`, `model_id`, `model_type`) VALUES
	(13, 194, 'App\\User'),
```

The SQL which is **not** cached is **not** looking for `App\\EmailOnlyUser` - it **is** looking for `App\\User` (i.e. no, it's not cached).

I also have tried with:

```
% php artisan cache:clear
```

**Comment by drbyte** [comment]
Okay, I see your point.
Maybe there's a bug there.

I can't investigate this until early next week.  If you're already got an idea you want to PR, that's welcome too.

**Comment by drbyte** [comment]
Apologies for the delay. I've finally had some time to look into this further, and I understand what you're saying and what you're wishing for.
Thanks for indulging my early responses: duh, I dunno why I made the cache comment! :s 

Unfortunately you may not like my answer: At this point I see it as expected behavior.

That said, I haven't dug into investigating whether the MorphToMany relationship can be told to inherit from parent classes when retrieving relations. The MorphMap might be leveragable, but isn't really for that purpose.

**Comment by marianperca** [comment]
A solution would be to change the morph map to this:
```php
Relation::morphMap([
  'App\User' => 'App\EmailOnlyUser',
]);
```
Or change the map entirely so both `App\User` and `App\EmailOnlyUser` point to the same key.
Check out Laravel documentation for [Custom Polymorphic Types](https://laravel.com/docs/5.8/eloquent-relationships)

**Comment by jvittetoe** [comment]
@lloy0076 I was having the same issue you outlined in your post here. After some more digging, I came across this answer https://github.com/laravel/framework/issues/17830#issuecomment-345619085 when researching "laravel morphmap model inheritance"

I have the exact same model inheritance that you've outlined, and after adding this to my child model, my call to `->roles()` generates the correct query.

```
public function getMorphClass()
    {
        return 'users';
    }
```
