### ISSUE TITLE
[Feature] Deny granted permission on a role for a specific user

### ISSUE THREAD

**Issue by shadoWalker89** [spatie/laravel-permission#75]
Hi,

The idea is to deny a specific user from a permission that is granted on the role.

Let's say we have a role called "reviewer" with a permission called "validate-papers". Each user that has the "reviewer" role will inherit the "validate-papers" permission.
It would be nice if we can deny the "validate-papers" permission from a specific user.

This will make the package a lot more flexible, and we don't have to make a lot of variations of the same role to deny some users a permission.

May be the you can add another relation called deniedPermissions() that will hold the denied permissions.

**Comment by freekmurze** [comment]
I'm not a big fan of this. I'm thinking that permissions should always be positive. 

Maybe you could remove the "validate-papers" permission from the "reviewer" role and create a new role "paperValidator" with a permission "validate-papers" and assign that role to users that may validate papers.

You don't even need need a role. Permissions can be granted to users directly without the need for a role.
