### ISSUE TITLE
Lumen support: Can't assign a role?

### ISSUE THREAD

**Issue by gedditnl** [spatie/laravel-permission#750]
Hey guys,

I've just installed Lumen and added spatie/laravel-permission. All seemed fine, until I wanted to assign a role to a user.

I have custom Role and Permission classes, that extend the original ones. The tables are on a tenant database (while the users table isn't):

```
namespace App;

use Spatie\Permission\Models\Role as BaseRole;
use App\Traits\UsesTenantConnection;

class Role extends BaseRole
{
    use UsesTenantConnection;
}
```

```
namespace App;

use Spatie\Permission\Models\Permission as BasePermission;
use App\Traits\UsesTenantConnection;

class Permission extends BasePermission
{
    use UsesTenantConnection;
}
```

bootstrap/app.php:

```
$app->register(Spatie\Permission\PermissionServiceProvider::class);
$app->configure('permission');
```

config/permission.php:

```
    'models' => [
        'permission' => App\Permission::class,
        'role' => App\Role::class,
    ],
```

Whenever I try to assign a role to a user, I get the following error: `Target [Spatie\Permission\Contracts\Role] is not instantiable.`

I figured out that it has to do with the "HasRoles" trait, that is used in the User model.
The User model in Laravel is different from Lumen. In my laravel project it works fine, but in Lumen is doesn't. My User model looks like this:

```
namespace App;

use Laravel\Passport\HasApiTokens;
use Illuminate\Auth\Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Laravel\Lumen\Auth\Authorizable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use App\Traits\UsesSystemConnection;

class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use UsesSystemConnection, HasRoles, HasApiTokens, Authenticatable, Authorizable;
}
```

In `HasRoles.php`  on line 214 and 218 it uses `Role::class`, which returns the Spatie role class, and not my version. My guess is that this has to do with the difference in the User model.

I've fixed this for now by copying the HasRoles and HasPermissions traits and replacing the `Role::class` on line 214 and 218 with `\App\Role::class`. All is fine now.

I would assume that `Role::class` should be replaced with a lookup in the config in `config/permission.php` for the correct class. But maybe I did something wrong in the User model.

Any thoughts?

**Comment by drbyte** [comment]
Hmmm ... The `Role::class` contract registration does do a lookup from `config/permission.php` for the correct class:

https://github.com/spatie/laravel-permission/blob/2affce0021cb9b6f4e249f7c5d94eb68039ffccc/src/PermissionServiceProvider.php#L54-L57
