### ISSUE TITLE
Permission table add column

### ISSUE THREAD

**Issue by volkankurt2** [spatie/laravel-permission#752]
I want to add a comment column to the Permissions table. How can I do that?

While adding new permissions via the interface, I want to enter the permission name and description. I guess I could not.

I did the editing events, but I could not created do it.

![image](https://user-images.githubusercontent.com/11972311/40578744-28ec7ada-6122-11e8-9382-b84eddfbbbf1.png)

![image](https://user-images.githubusercontent.com/11972311/40578753-478b59b6-6122-11e8-817e-7d517a4bb78e.png)

![image](https://user-images.githubusercontent.com/11972311/40578758-69f6096a-6122-11e8-9d3d-0eb5b4cc1c54.png)

**Comment by mvatansever** [comment]
Just add a new Permission entity and extend the "**Spatie\Permission\Models\Permission**" class. Then add the new Permission entity to configuration file:

**configuration.php** file:

    'models' => [

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your permissions. Of course, it
         * is often just the "Permission" model but you may use whatever you like.
         *
         * The model you want to use as a Permission model needs to implement the
         * `Spatie\Permission\Contracts\Permission` contract.
         */

        'permission' => App\Models\Permission::class,
...

In the new Permission entity you should add the new columns and you should create a new migration to add this columns.

**Comment by volkankurt2** [comment]
Thank you @mvatansever but It did not work

**Comment by Nowi5** [comment]
Can we close here? I think there is no general issue. Similar to #766
