### ISSUE TITLE
Delete Role

### ISSUE THREAD

**Issue by D34DlyM4N** [spatie/laravel-permission#755]
Hello

I Installed version 2.10 and when i try to remove role i have error message
`"message": "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'roles_model_id' in 'where clause' (SQL: delete from `role_has_permissions` where `roles_model_id` = 2)",`

My Delete function is 
`
        $role = RolesModel::findOrFail($request->id);
        $role->delete()`

and RolesModel is model extends to Spatie\Permission\Models\Role this issue didn't happend in version 2.9 but when i update to 2.10 i have this issue.

**Comment by D34DlyM4N** [comment]
i figure it out
i changed the RolesModel to extends Model
changed my code to 
`        $role = Role::findOrFail($request->id);
 $role->delete()

`

and now it's work perfectly

**Comment by meredevelopment** [comment]
Just for the bots. I landed here while trying to delete a permission by name, in this case "write post".

```
$perm = Permission::findByName("write post");
$perm->delete();
```

Works a treat.
