### ISSUE TITLE
hasPermissionTo() and hasDirectPermission() with inexpected argument types

### ISSUE THREAD

**Issue by dimitvassilev** [spatie/laravel-permission#764]
Hello,
First of all: thank you for this so very useful package!

I think there is a potential problem in some corner use cases with the hasPermissionTo() and hasDirectPermission() methods:

https://github.com/spatie/laravel-permission/blob/f4763cc8957c2ce04efe4a84dbe7ad9d45c8cb39/src/Traits/HasPermissions.php#L106-L120

https://github.com/spatie/laravel-permission/blob/f4763cc8957c2ce04efe4a84dbe7ad9d45c8cb39/src/Traits/HasPermissions.php#L163-L180

specifically the  hasPermissionTo() performs no checks to ensure the $permission argument is no other type than an instance of \Spatie\Permission\Contracts\Permission, string or int (btw, the int option has been omitted in the PhpDoc block).  If it is anything other than an int or a string, it is passed over to the hasDirectPermission() method where again it is checked only if being a string or an int and only presuming that it is an instance of \Spatie\Permission\Contracts\Permission otherwise, but it could be anything else. If it is null, it would not have an id attribute to be called in the return statement and if it is an instance of another class type having an id attribute, it would yield an irrelevent id and difficult to debug weird behaviour. Also, it seems the intention is to return false in case a name or an id has not been found in the permission records, however the findByName() and findById() methods throw exceptions in this case (and the hasPermissionTo() method counts on that as it does not perform the checks in case name or id are not found).

Thanks for your consideration and again - thanks for the great work you've been doing with the package!

**Comment by drbyte** [comment]
Thanks for this. You raise good points.

Can you describe the workflow or app conditions that you're finding are introducing the "corner use cases" that you mention?

**Comment by dimitvassilev** [comment]
I am dynamically deducing the permission name against which to check in my models policies, based on the CRUD action and a language attribute. The language comes from the client data for 'create' action, so it is unreliable which made me look into the code to see what I should expect in case the persmission I check against doesn't exist. I should, of course, pass the language through validation first, so there will be no problem, however I thought that somenone might encounter such in some other scenario of dynamically deducing the permission name where wrong names/ids, nulls or unexpected object types might be produced. These would be probably quite rare occasions but still possible, I guess.

**Comment by drbyte** [comment]
@dimitvassilev ,
Apologies for the delay in replying. 
I agree with you. The assumption that the unchecked "type" is a valid one ought to be made more strict.
A tested PR is welcome. (I'm not sure if you were offering.)
I've made a note to include this in a future release.
