### ISSUE TITLE
Add a custom properties column

### ISSUE THREAD

**Issue by lucasdcrk** [spatie/laravel-permission#766]
Hi!

I'd really like to have a json custom properties column for each roles, so I can associate a role to a color for exemple.

**Comment by Nowi5** [comment]
Yes you can do. Just run a migration after installing Spatie which add the column. Define your own model, set the config right and done. I use this to have a role description.

**Comment by drbyte** [comment]
Closing because this is essentially a duplicate of #670

**Comment by HakerTag** [comment]
https://spatie.be/docs/laravel-permission/v4/advanced-usage/extending
