### ISSUE TITLE
'HasRoles' wrong relationship

### ISSUE THREAD

**Issue by potatoshrike** [spatie/laravel-permission#769]
I'm using this:

```
// get all permissions inherited by the user via roles
$permissions = $user->getAllPermissions();
```
But it does not bring **only** the permissions inherited by the user via roles, it brings every single permissions, even the ones directly assigned to the user.

**Comment by drbyte** [comment]
Looks like a typo in the readme.

Later down it describes them like this:

>// Direct permissions
$user->getDirectPermissions() // Or $user->permissions;
>
>// Permissions inherited from the user's roles
$user->getPermissionsViaRoles();
>
>// All permissions which apply on the user (inherited and direct)
$user->getAllPermissions();
