### ISSUE TITLE
Checking that role has permission

### ISSUE THREAD

**Issue by nWidart** [spatie/laravel-permission#77]
Hello,

Is it possible to check if a role has a certain permission ? 

I may have missed it but I only see this on a user, `user->can('delete something')`. I would like to have the same, on roles basically.

The use-case behind is so that one the roles GUI, I can check whether or not the checkbox needs to be checked for each permission on a role.

Thank you,

**Comment by nWidart** [comment]
I was able to add the required logic on the Role model with this:


``` php
public function hasPermissionTo($permission)
{
    if (is_string($permission)) {
        $permission = app(Permission::class)->findByName($permission);
    }

    return $this->hasDirectPermission($permission);
}

protected function hasDirectPermission($permission)
{
    if (is_string($permission)) {
        $permission = app(Permission::class)->findByName($permission);

        if (!$permission) {
            return false;
        }
    }

    return $this->permissions->contains('id', $permission->id);
}
```

Would a PR with adding this be ok, or do I keep it in my extended Role class ?

**Comment by freekmurze** [comment]
Hi Nicolas,

thanks for whipping up this code.

I'm thinking that role doesn't real need separate `hasPermissionTo` and `hasDirectPermission` functions. A role's permissions are always direct.  I'd accept a PR that add a `hasPermissionTo` to the Role class (please add some tests 😄).

**Comment by nWidart** [comment]
It has been a while since I wanted to use this package. 😄 

PR sent, #78 .

**Comment by freekmurze** [comment]
Your PR has been merged. A new version `1.4.0` has been tagged with these changes.

**Comment by nWidart** [comment]
Awesome, thank you! 👍
