### ISSUE TITLE
Null issue with syncPermissions & syncRoles on array

### ISSUE THREAD

**Issue by ereztdev** [spatie/laravel-permission#770]
This applies to both `syncPermissions` and `syncRoles`.
If I add/remove all permissions from a user, I do it like so:
```
public function updateUserRolesPermissions(Request $request, $id){
$request->permissions ? $user->syncPermissions($request->permissions) : false;
$request->roles ? $user->syncRoles($request->roles) : false;
        Session::flash('success', 'Changes were saved');
        return Redirect::back();
}
```
I would need the false on null, since the last permission revoked that would go into this method (as null) would actually falisify these functions.

Yet if I just write: ` $user->syncPermissions($request->permissions);`, I would get : `Trying to get property of non-object` tracing to this line:
```
    protected function ensureModelSharesGuard($roleOrPermission)
    {
        if (! $this->getGuardNames()->contains($roleOrPermission->guard_name)) {
            throw GuardDoesNotMatch::create($roleOrPermission->guard_name, $this->getGuardNames());
        }
    }
```
if I have null roles, I would get this error:
```
Type error: Return value of App\User::getStoredRole() must implement interface Spatie\Permission\Contracts\Role, null returned
```
tracing to `spatie\laravel-permission\src\Traits\HasRoles.php` on return for function:
`protected function getStoredRole($role): Role`

What would be a good course of action?

### Just to reiterate the main issue:
I am updating user roles/permissions with `syncPermissions` and `syncRoles`, on an array, if permissions or roles return null (user has no permissions and/or no roles), app is thrown into error.

**Comment by malickateeq** [comment]
I trapped in the same issue and temp fixed it by ;
        if($request->permissions == null)
        {
            $all = $role->getAllPermissions();
            $role->revokePermissionTo($all);
        }
        else
        {
            $role->syncPermissions($request->permissions);
        }
