### ISSUE TITLE
UnauthorizedException VS ModelNotFoundException

### ISSUE THREAD

**Issue by lapswr** [spatie/laravel-permission#772]
Hi,

I've added the code on exception handler to catch the UnauthorizedException but I'm also using the laravel's routes model binding that checking for the existence of the models id.
The problem is that the user don't have the permission to access the client route (I'm implementing the routes middleware see code below ), 
so if the url has a valid client id the exception is UnauthorizedException 
But if the url doesn't have a valid client id the exception is ModelNotFoundException
```
Route::group(['middleware' => ['permission:update clients|manage clients']], function () {
            Route::put('/{client}', 'ClientController@update')->name('clients.update');
});
```
I should be taking only the UnauthorizedException.
Also something strange the DELETE request is working as expected, giving only the UnauthorizedException.
Any suggestions?

**Comment by lapswr** [comment]
@drbyte not sure how the route model binding have been implemented but this makes no sense,
routes should first be checked for the permissions with the middleware and then lookout the input data if they are correct.

**Comment by drbyte** [comment]
Perhaps. 
It feels like a chicken-vs-egg conflict.

Perhaps changing middleware registration order may help? See brief discussion of similar sort of situation at https://github.com/laravel/ideas/issues/716#issuecomment-321926444
