### ISSUE TITLE
Detect User ?

### ISSUE THREAD

**Issue by lvar** [spatie/laravel-permission#773]
I'm trying to use roles and verify if one specific user has a role...but have a lot of doubts...

 Documentation say : $user->hasRole('admin');

 $user variable, where it comes from? , how it takes the value of the current logged in user ? 

I'm trying to verify this on the dashboard controller.

**Comment by drbyte** [comment]
In the examples, `$user` could be any user/model about whom you want to check role/permission status.

In the case of the currently-logged-in-user, in Laravel there are several ways to determine that:
- `$user` where `$user` is an injected instance of `\App\User` (or whatever your User model is)
- `auth()->user()`
- `Auth::user()`
- `request()->user()`
- `$request->user` where `$request` is an injected instance of `Request`
