### ISSUE TITLE
Using another key name than 'model_id'

### ISSUE THREAD

**Issue by vpratfr** [spatie/laravel-permission#777]
In our app, we use UUIDs as ids.

For consistency within the application, we suffix the foreign key names with _uuid instead of _id as our primary key column is 'uuid'.

We can easily update the migration files to change the `$table->morphsTo('model')` to use a different name and type for the schema.

However, it it more difficult to let the `HasRoles` and `HasPermissions` traits know about it.

My first attempt was to redefine just the relationship method inside a custom trait :  

```
namespace App\Models\Traits;

use Illuminate\Database\Eloquent\Relations\MorphToMany;

trait HasRoles
{
    use \Spatie\Permission\Traits\HasRoles;

    /**
     * A model may have multiple roles.
     */
    public function roles(): MorphToMany
    {
        return $this->morphToMany(
            config('permission.models.role'),
            'model',
            config('permission.table_names.model_has_roles'),
            'model_uuid',
            'role_id'
        );
    }
}
```

And same kind of thing for `HasPermissions`

However, the `HasRoles` trait includes your own `HasPermissions` trait and thus it does not take into account my customized version. So, currently I am stuck with either : 

- Redefining the whole trait (not so great as I would copy-paste all methods including the ones which do not show any issues)
- Sticking with `model_id` as column name. But does not feel right/consistent when looking at the whole application DB schema.

Possible ways to solve it (unless you have a better idea) : 

- Allow a custom column name within the traits (could be a property which could be set in the class, like `private $permissionModelForeignColumn = 'model_uuid';` and check if that propery is set in the relationship method (defaulting to current name if not)
- Do not include `HasPermissions in your `HasRoles` trait and let the user include both traits in their models
- Have a configuration variable for that column name

Option 1 seems the nicest to me. Would you accept a PR for that?

**Comment by drbyte** [comment]
True, overriding the nested traits is indeed a challenge.  So is helping prevent forgetting to include all the necessary traits.

Hmmmm ...

**Comment by vpratfr** [comment]
Yep. Got the same kind of issue in https://github.com/spatie/laravel-model-status/issues/39 too ;)

**Comment by drbyte** [comment]
I would accept a tested PR much like you did with https://github.com/spatie/laravel-model-status/pull/40

**Comment by vpratfr** [comment]
Will do when I get some time.

**Comment by vpratfr** [comment]
Done ;)

**Comment by drbyte** [comment]
Thanks!
This opens up options for #793
