### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by WidurangaJayawickrama** [spatie/laravel-permission#778]
how to add special permission in user 
eg:- A user has x user role, but x user role has add/edit/view permission, we need to give delete permission in A user without his role. how to do that?

**Comment by drbyte** [comment]
From this section of the README:
https://github.com/spatie/laravel-permission#using-direct-permissions-see-below-to-use-both-roles-and-permissions

`$user->givePermissionTo('delete articles');`

**Comment by WidurangaJayawickrama** [comment]
ok thz.
