### ISSUE TITLE
Assign Role to Controller Method via middleware

### ISSUE THREAD

**Issue by arunmisra2273** [spatie/laravel-permission#782]
I am new to this package. I need a little basic help.
I have a resource controller. I have 3 roles, superadmin, admin and prime.
I want users with superadmin and admin roles to access all controller methods.
ADDITIONALLY, I want users with prime role to be able to access ONLY the update method.

I have used the following and I get "message": "User does not have the right roles.", when a user with prime role tries to use the update function. 

public function __construct()
    {
        $this->middleware('JWT');
        $this->middleware(['role:superadmin|admin']);
        $this->middleware(['role:prime'])->only('update');
        
    }

I will be obliged if someone could kindly guide me.
P.S. I understand I can check for user role inside the update method. But is there a clean way of doing it from the constructor?

**Comment by drbyte** [comment]
I think there's something else conflicting.
In this demo app, the constructor middleware `->only` call works properly: https://github.com/drbyte/spatie-permissions-demo/commit/7eb7fdef32ff38ebbaa4b64d6e999c66bbfd42af

**Comment by arunmisra2273** [comment]
Thank you for your time @drbyte 
There is definitely something conflicting. As per my example above, a 'prime' user is not able to access the update method.
