### ISSUE TITLE
hasPermissionTo return False, even if the permission on the database exists

### ISSUE THREAD

**Issue by xdasty** [spatie/laravel-permission#783]
AppServiceProviders.php
------------------------------------------
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use Illuminate\View\Compilers\BladeCompiler;

    public function register()
    {
        $this->app->afterResolving('blade.compiler', function (BladeCompiler $bladeCompiler) {
            $bladeCompiler->directive('haspermission', function ($permission) {
               list($module, $guard) = explode(',',$permission);
                return "< ?php if(auth()->check() && auth()->user()->hasPermissionTo({$module},{$guard})): ? >";
            });

            $bladeCompiler->directive('endhaspermission', function () {
                return '<?php endif; ?>';
            });
        });
    }
------------------------------------------

sidebar.blade.php
---------------------------------------------
@haspermission('menu1', 'admin')
Hello World :-)
@endhaspermission
---------------------------------------------

permission exists in the database, but:
auth()->check() -> return True
auth()->user()->hasPermissionTo({$module},{$guard}) ->return False

Update:

HasPermissions.php

call function hasPermissionTo
-- $this->hasDirectPermission($permission)  -- return False (OK)
-- $this->hasPermissionViaRole($permission) -- return False  (NO the permission via Role Exist)

call hasPermissionViaRole
-- $permission->roles  -- return object 'items' =>  Role (OK Find Role)
-- $this->hasRole($permission->roles) -- return False (NO the Role Exist)

Laravel Framework 5.6.26
spatie/laravel-permission 2.12.2

PHP 7.2.1
Mysql 5.7.21

**Comment by xdasty** [comment]
I solved

using a third-party package

I had to edit the file:
config/auth.php

**Comment by pankajsanam** [comment]
How did you solve it? I am facing the same problem.

**Comment by zgldh** [comment]
That's a bug I guess. #809

**Comment by drbyte** [comment]
@pankajsanam  The original issue posted by @ xdasty was (most likely) fixed by editing `config/auth.php` to switch order of which guard is listed first, so that when the original lookups fail the first-listed one would be selected.

I'm not sure where @zgldh is getting the need to cast roles as an array. That feels unrelated and even probably limiting (it should be discussed in a separate Issue post).

**Comment by xdasty** [comment]
@pankajsanam I use a third-party package that invokes: spatie / laravel-permission

I solved by editing the config file.
As written above
