### ISSUE TITLE
Method order issue when using with \Illuminate\Database\Eloquent\Builder::when() method

### ISSUE THREAD

**Issue by mgsmus** [spatie/laravel-permission#784]
Laravel Framework 5.6.26
PHP 7.2.2
spatie/laravel-permission 2.12.2

This doesn't work as expected. Returns all corresponding users regardless of given role if province_id is filled:

```
$architects = User::role('architect')
    ->when($request->get('province_id'), function ($query, $value) {
        return $query->where('province_id', $value);
    })->withCount('projects')->latest()->paginate(30);
```

I've added _role_ method after _when_ method and it worked:
```
$architects = User::when($request->get('province_id'), function ($query, $value) {
    return $query->where('province_id', $value);
})->role('architect')->withCount('projects')->latest()->paginate(30);
```

**Comment by drbyte** [comment]
Yes, that's correct. 
`when()` must be applied to the model first if you wish to use it for filtering that model's objects using the provided callback, and then apply the scope-via-related-tables to that result.
