### ISSUE TITLE
Best practice to save data for every role.

### ISSUE THREAD

**Issue by yamenarahman** [spatie/laravel-permission#786]
Let's say that I have multiple roles like 'admin', 'student' and 'instructor'. What is the best way to save dedicated data for each role? for example students have ids but instructors have degrees, should I add degree column in users table or should I make a new table called instructors_info and make a 1-1 relation with users with role instructor?

**Comment by drbyte** [comment]
This package's goal is to provide just the association of the model (user) and roles/permissions, for the purpose of providing authorization support.

Other associations should be handled in your app's own schema. Even role-related information that's unique to each related model (ie: an instructor's own degrees/credentials) varies per instructor, and isn't related to authorization details.
Whether your app needs an additional pivot table, or just additional fields on your (user) model table, is up to you. If it's display-only information perhaps an additional field may suit; but if it's something you might query on or filter/group by, then a related table may be preferable.

Hope that helps.

**Comment by yamenarahman** [comment]
Thanks @drbyte .
