### ISSUE TITLE
200+ permissions slowing down the website :(

### ISSUE THREAD

**Issue by mailnike** [spatie/laravel-permission#789]
Hi,

I have more than 200 permissions and SaaS solution. with only 50+ users, my permission_role table has already crossed 4000 entries. Basically in my webapp, every user can create his/her own roles then assign any of these 200 permissions. 

I applied solution mentioned in #759 but it didn't reduce the memory usage ( at the moment more than 70mb :( as per laravel debugger )

It is slowing down my entire web-app and causing lot of other issues. Any solutions or suggestions? :(
I don't mind working with freelancer to get this fixed but I really need some solution for this. Page should not take more than 2-3 seconds to load. 

Thanks.

**Comment by mailnike** [comment]
@Nowi5  Thanks for your reply. Are you saying that I should first modify the table 'role_has_permissions'? adding a field 'tenant_id'? then add where condition in the TRAIT: HasPermissions.php (Vendor >> Spatie)? Let me know if this makes sense. Also, if you think you can fix this, please let me know. I will be more than happy to hire you (freelance work).

**Comment by Nowi5** [comment]
Hi, not sure if only extending the Trait helps, I believe you need to attach a scope to all selections. Maybe some of the others can provide feedback on my idea first. 
@all: Where beside the traits I would have to attach additional where conditions?

**Comment by drbyte** [comment]
This package doesn't dictate how to do multi-tenant implementations. It can be done with a few variations as you mention, along with some app-specific adapter wrapping.
@Nowi5 the traits would need where conditions, and the models probably need global scope as well as additional attribute handling for the extra data. If all the tenants choose from a core set of roles and permissions and the only variation is who they assign those to, then it's simpler.

**Comment by kamov** [comment]
I am posting the same here regarding the performance issue:

Why this library don't use json fields for cache roles and permissions?

Or even for remove pivot table so it have roles and permissions table and then those models that need to use roles and permissions like users add field roles_json and permissions_json

**Comment by kamov** [comment]
I may be wrong but why all this tables for roles and permissions, why it could not just be:

- role table with id, name and permission_json (text or json field)
- users table with role_id (foreign key) and permissions_json (as text or json field) - or any other table that require roles/permissions)

Then we can just check if `in_array($permission, $user->permission_json)` 
and $user_permission_json can be an array which merge custom user permissions with role permission.

**Comment by mailnike** [comment]
I moved to [Bouncer](https://github.com/JosephSilber/bouncer/) due to memory issue. Otherwise Spatie was wonderful but it was taking 15+ seconds to load simple pages. Bouncer is very similar, took less than hour to migrate.

**Comment by kamov** [comment]
I see Bouncer, but I didn't want use it since they seem have the same issue with performance, see here https://github.com/JosephSilber/bouncer/issues/345
