### ISSUE TITLE
hasPermissionTo differs from can

### ISSUE THREAD

**Issue by dvdheiden** [spatie/laravel-permission#79]
I'm using Laravel version 5.2.31 and laravel-permission version 1.4.0 and I'm encountering a strange problem. I've created a permission and assigned it to a role:

```
$manageUsersPermission = Permission::create(['name' => 'manage_users']);

$administratorRole = Role::create(['name' => 'Administrator']);
$administratorRole->givePermissionTo($manageUsersPermission);
```

Next I've created a user and assigned the role:

`$user->assignRole('Administrator');`

When the user is logged in, there's a difference between hasPermissionTo and can:

`$this->user->hasPermissionTo('manage_users');`
// -> true
`$this->user->can('manage_users');`
// -> false

I already tried refreshing the cache. Does anybody have an idea what's going wrong?

**Workaround:**
It's solvable by overriding the `can` method in the user model with:

```
public function can($ability, $arguments = []) 
{ 
    return $this->hasPermissionTo($ability);
}
```

And by using custom middleware in which you replace `can` by `hasPermissionTo`.

But it would be nice if I can fix this problem without workarounds.

**Comment by freekmurze** [comment]
The tests seem to prove that `can` should be working as intented: https://github.com/spatie/laravel-permission/blob/master/tests/GateTest.php#L23

Could you please add a failing test?

**Comment by dvdheiden** [comment]
Thank you for the reply. The test indeed proves I'm doing something wrong. I've also tested it on a fresh laravel installation and it works. The test your pointing to, gave me an idea to find the solution for my problem. 

For others who might experience this problem:
On the multi-tenant project I'm using this for, the database is selected manually and the permission service providers run before the database selection. When manually registering the service provider after the database selection, this problem doesn't occur anymore.

**Comment by rickselby** [comment]
I'm having the same issue, and would appreciate any assistance in sorting it.

I don't think I'm doing anything clever with database selection, but the project is already quite large, so there might be something in there causing a similar issue.

Where would I manually register the provider to get around this?

**Comment by rickselby** [comment]
It's working again now; it was a cache issue.
