### ISSUE TITLE
Column not found: 1054 Unknown column 'permissions.user_id'

### ISSUE THREAD

**Issue by lohmag** [spatie/laravel-permission#790]
I created tables through migration but when I try anything that gives or checks permissions this error occurs
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'permissions.user_id' in 'where clause' (SQL: select * from `permissions` where `permissions`.`user_id` = 3 and `permissions`.`user_id` is not null and `mask` & 0)`
What is this column user_id and why migration not created it?

**Comment by drbyte** [comment]
I think something in your app is interfering. This package doesn't directly reference a `user_id` column on the `permissions` table.
