### ISSUE TITLE
How to setup Admin Role has all permissions?

### ISSUE THREAD

**Issue by r94ever** [spatie/laravel-permission#791]
Hi all,

I am building an application with many roles and permissions for users. And thanks to this package, my work became easier very much.

But I have a problem without answer on Google. I created a Role named "Super Admin" and some permissions. How can I set any user who have "Super Admin" role, will have all permissions, not care about permissions they are owning.

Every help will be appropriate!

**Comment by drbyte** [comment]
You can use Laravel's `Gate::before()` method for that, as explained here: https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role

**Comment by r94ever** [comment]
Exactly what I need. Thanks so much ☺️

**Comment by jayenne** [comment]
I could use a little more info on using this?
I've added axactly as is shown here but don't understand why my superadmin still doesn't have all perms.

I also don't understand how gate:before needs $user and $abilities but can't see where there are provided.
