### ISSUE TITLE
Problem with DB connection and prefix

### ISSUE THREAD

**Issue by mapodev** [spatie/laravel-permission#792]
Hey there,

say if we set a prefix in `config/database.php` in main DB connection, the permission methods `User::find(0)->permission('seePromoters')->first()` does not work, because they are missing the prefix.

**Comment by drbyte** [comment]
This package currently supports just one db connection. If you need multiple connections, consider the suggestions I posted in https://github.com/spatie/laravel-permission/issues/728

Changing the prefix after creating the tables would require manually adjusting tablenames.
