### ISSUE TITLE
How to get all permissions of authorized user

### ISSUE THREAD

**Issue by mkskr** [spatie/laravel-permission#798]
Hello,
first time using spatie permission package. but find problem to get all permissions of log-in user.
i want to know which user has which role/permissions.
I have tried some code listed below but  nothing happened & returned empty array. can someone guide me how to do this.
I am using laravel 5.6. 
// get a list of all permissions directly assigned to the user
$permissions = $user->permissions;
// get all permissions inherited by the user via roles
$permissions = $user->getAllPermissions();
// get a collection of all defined roles
$roles = $user->getRoleNames(); // Returns a collection

Thanks.

**Comment by MikeMnD** [comment]
Shouldn't this be closed! :)

**Comment by hemendraajmera** [comment]
Hi,
I have a array which contains all navigation URLs of application and i have same name as permission name. now i want to check logged user have permission or not , based on that i want to show the navigation.
i tried couple of option but not working and also tried above solution but unable to check user permission with my array permissions.
here i have array like 
$nav_array='items' => [
        // Dashboard
        [
            'title' => 'Dashboard',
            'root' => true,
            'icon' => 'media/svg/icons/Design/Layers.svg', // or can be 'flaticon-home' or any flaticon-*
            'page' => '/',
            'new-tab' => false,
        ],
        // sales lead
        [
            'title' => 'Sales leads',
            //'root' => true,
            'icon' => 'media/svg/icons/Home/Door-open.svg', // or can be 'flaticon-home' or any flaticon-*
            'page' => 'salesleads',
            'new-tab' => false,
        ],
        // Projects
        [
            'title' => 'Projects',
            'root' => true,
            'icon' => 'fas fa-project-diagram', // or can be 'flaticon-home' or any flaticon-*
            'page' => '/projects',
            'new-tab' => false,
        ],
];
in array title which is same as permission name.
Can any open help me to provide solution. i am new to spatie and laravel.

Thanks in advance.
