### ISSUE TITLE
How to apply authorization on resource routes using spatie permissions

### ISSUE THREAD

**Issue by Satendra-SR** [spatie/laravel-permission#799]
#### To add another level of security, I was trying to apply authorization on routes.
**what I did yet.**
My Client Policy:
` public function view(User $user, Client $client)
    {
        return $user->hasPermissionTo('clients.view');
    }` and similar for edit, create and delete.

In web.php: 
`Route::resource('clients', 'ClientController')->except(['show'])->middleware('can:clients.view, clients.create, clients.update, clients.delete');`
it seems that I was giving all permissions to every users.

Do anyone has any idea that how I should implement spatie permissions to resource routes for authorization? 
thank you

**Comment by drbyte** [comment]
I would think the best way for this is to use Laravel Policies.
Here's an example: 
https://github.com/drbyte/spatie-permissions-demo/commit/fbb35a3589f57453a37c99dab2a265e97e3bb301

**Comment by drbyte** [comment]
You may want to use `authorizeResource` in your controller constructor -- example in https://josephsilber.com/posts/2016/08/03/authorization-improvements-in-laravel-5-3

**Comment by drbyte** [comment]
You said you used:
`->middleware('can:clients.view, clients.create, clients.update, clients.delete')`
Did you try:
`->middleware('permission:clients.view|clients.create|clients.update|clients.delete')`

**Comment by woottonn** [comment]
To expand on this - I am struggling with route resources. 

If I do this it works great:::: `Route::get('users', 'UsersController@index')->middleware('permission:view-users');

However, I have a resource in my web routes like so: `Route::resource('users', 'UsersController');`

What is the best way to authorise within the controller?

**Comment by woottonn** [comment]
Turns out this didn't work...

```
public function __construct() {
           $this->middleware('permission:view-users', ['only' => ['index, show']]);
}
```

I am unsure why. 

`@can` works perfectly in blade templates.
`Route::get('users', 'UsersController@index')->middleware('permission:view-users');` works fine in the web routes file.

**Comment by woottonn** [comment]
Fixed - this did it!

`$this->middleware('permission:view-users')->only('index', 'show');`

**Comment by bhagchandani** [comment]
Did anyone find a way to use this in routes file ?

**Comment by Neeraj1005** [comment]
> Fixed - this did it!
> 
> `$this->middleware('permission:view-users')->only('index', 'show');`

Thanks buddy it worked. In my controller I used this technique like this:
```
$this->middleware('auth');
        $this->middleware('permission:list-post')->only('index');
        $this->middleware('permission:create-post')->only('create');
        $this->middleware('permission:view-post')->only('view');
        $this->middleware('permission:edit-post')->only('edit');
        $this->middleware('permission:delete-post')->only('destroy');
```

**Comment by alimarchal** [comment]
This will work
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:list-post')->only('index');
        $this->middleware('permission:create-post')->only('create');
        $this->middleware('permission:view-post')->only('view');
        $this->middleware('permission:edit-post')->only('edit');
        $this->middleware('permission:delete-post')->only('destroy');
    }

**Comment by Arlong-kit** [comment]
> 有没有人找到在路线文件中使用它的方法？

Hello, do you have a solution in the routing file?

**Comment by Arlong-kit** [comment]
> Did anyone find a way to use this in routes file ?

Hello, do you have a solution in the routing file?

**Comment by olvanotjeanclaude** [comment]
you can create a trait for them then use it as many time you want
// ArticlesAuthorizable.php
<?php
namespace App\Traits;

trait ArticlesAuthorizable{
    public function __construct(){
        $this->middleware('permission:view article')->only("index","show");
        $this->middleware('permission:create article')->only("create");
        $this->middleware('permission:edit article')->only("edit");
        $this->middleware('permission:delete article')->only("destroy");
    }
}

in your controller ProductController.php
class ProductController extends Controller
{
    use ArticlesAuthorizable;
}

 public function index(){...}
 public function create(){...}
 public function show($id){...}
 public function edit($id){...}
 public function destroy($id){...}
