### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by francoismart** [spatie/laravel-permission#8]
Hello
nice package. would it be possible to add a "Teams" or "Workspaces" a la spark on top of roles ?
For my saas project i would need a user-teams role definition so that I can have administrators, team administrators and members roles for each team. Permissions would be declared one time only like read, write, updated, delete, etc ... and would be reusable across roles. So one user could have many teams and in each team it would have different roles, connected with different permissions.
I'm asking instead of doing because i'm not sure how to figure it out.
have nice day
Francois

**Comment by freekmurze** [comment]
Hi, currently there are no plans to add a team-layer. I haven't looked at in in detail, but I suppose that [Laravel Spark](https://github.com/laravel/spark) will offer team based authentication out of the box.

**Comment by cyberhicham** [comment]
Hello,
I have the very similar need @francoismart : how did you manage it finally ?
@freekmurze : any *updated* plans about this team-layer ?

**Comment by freekmurze** [comment]
@cyberhicham Nope

**Comment by francoismart** [comment]
hello
we've segregated  teams at database level. need maintenance (1 db per team) but works. 
major drawback is how you connect to db and how to associate to subdomain.
Our code is not generic enough to share. But one package to check is https://laravel-tenancy.com
(did to test it but use same tactics)
hope it helps
François

**Comment by cyberhicham** [comment]
@francoismart : I see, not exactly what I have in mind. Thanks :)

**Comment by mihailovskim** [comment]
Hi everyone,

Few years after this issue is opened... is there any improvement now? Is there possibility spatie/laravel-permission to be used in SAAS applications?

Kind regards,
Martin
