### ISSUE TITLE
Using Eloquent's sync() method to update roles and permissions

### ISSUE THREAD

**Issue by matbeard** [spatie/laravel-permission#80]
I'm creating the user management functions for my app, part of which consists of multi-selects for a user's roles and permissions. When submitted, these pass arrays of role/permission ids to my controller.

Can you think of any reason for not using Eloquent's sync() method to update a user's roles and permissions, as this makes life a lot easier to add/remove in a single operation.

    $user->roles()->sync($request->input('roles'));

It appears to work... I just wondered if there was a reason to not do it.

**Comment by freekmurze** [comment]
That code seems ok and seems like a good way to go about it.

If you want to improve the code of this package, feel free to submit a PR. There are a lot of unit tests that'll help if your refactor works.
