### ISSUE TITLE
Call to undefined method Illuminate\Auth\GenericUser::hasPermissionTo()

### ISSUE THREAD

**Issue by nishanthii2w** [spatie/laravel-permission#801]
I am trying to add new user but these error throws Call to undefined method Illuminate\Auth\GenericUser::hasPermissionTo() by adding new roles, permissions and user.
https://i.imgur.com/moFgrhk.png

**Comment by drbyte** [comment]
The `hasPermissionTo()` is made available via the `HasPermissions` trait. 

In your custom middleware your `Auth::user()` call is doing a lookup that's finding a `Illuminate\Auth\GenericUser` model, which doesn't have the `HasPermissions` trait on it. 

You'll need to fix your code.

**Comment by nishanthii2w** [comment]
Where i have to fix this if you know the file name please mention that where i have to fix this bug

**Comment by hgopi** [comment]
I had the same issue. I resolved this issue by changing the `driver` value from `database` to `eloquent` in the `auth.php` file. 

Refer:
https://laracasts.com/discuss/channels/laravel/authuser-returning-generic-user#best-reply-593380
