### ISSUE TITLE
hasPermissionTo method should return bool

### ISSUE THREAD

**Issue by mifas** [spatie/laravel-permission#802]
When there is no permission in the database, this method currently returing an exception. It should return false

```[2018-07-21 17:24:04] local.ERROR: There is no permission named `list-products` for guard `web`. {"userId":1,"email":"admin@admin.com","exception":"[object] (Spatie\\Permission\\Exceptions\\PermissionDoesNotExist(code: 0): There is no permission named `fetch-products` for guard `web`. at /app/vendor/spatie/laravel-permission/src/Exceptions/PermissionDoesNotExist.php:11)```

**Comment by ifty-rahman** [comment]
That make sense. There is no reason for a checking method to throw exception. If the record doesn't exists in database, it should return false.

I faced the same issue today and until it's getting resolved, I decided to use my custom function to handle that exception.

```
// declaration
function hasPermission( $user, $permission ){
    try{
        return $user->hasPermissionTo( $permission  );
    } catch ( Exception $e ){
        return false;
    }
}
```

```
// uses
if( hasPermission(Auth::user(), "create_post") ){
    // do stuff
}
```

**Comment by drbyte** [comment]
Note: Due to the risk of breaking changes, we will be waiting to fix this in v3.

**Comment by lk77** [comment]
Hello,

i'm not sure about this, hasPermissionTo checks if a user has a permission,
but it's not a normal that the permission doesn't exist in database, and we should show a warning no ?

**Comment by drbyte** [comment]
Note: release 2.24.0 added the `checkPermissionTo()` method which returns a boolean.
