### ISSUE TITLE
Eager loading roles?

### ISSUE THREAD

**Issue by MadMikeyB** [spatie/laravel-permission#806]
Hiya,

I've got an N+1 issue which I know I can fix with eager loading - but when I try with('role') on my query, I get the following:

```
Type error: Too few arguments to function App\User::scopeRole(), 1 passed in /Users/mikey/sites/xxx/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 957 and exactly 2 expected
```
This is my code:

```
        $users = User::with('role')->withoutGlobalScopes()->get();
```

And my N+1 looks like this:

![screen shot 2018-07-29 at 16 20 54](https://user-images.githubusercontent.com/831828/43367861-9f1a936c-934b-11e8-8254-0acd9c2bef50.jpg)

How would I eager load the roles so we avoid this N+1 issue?

Using `spatie/laravel-permission:^2.9` at the moment. I'm unsure if upgrading would fix the N+1 issue?

**Comment by drbyte** [comment]
Note: If your `composer.json` lists `spatie/laravel-permission:^2.9` and you've run `composer update`, then it should have actually installed the latest version (the `^` in `^2.9` means use the newest `2.xx` release).

**Comment by drbyte** [comment]
I think you're using the API wrong:

For eager loading use `->with('roles')` (plural "roles", not "role")

The scope `App\User::scopeRole($roleName)` is used to limit the query to a specified role, not to do eager-loading.

**Comment by MadMikeyB** [comment]
Thanks @drbyte I'll give that a shot. Trust me to use it wrong!

**Comment by MadMikeyB** [comment]
Alas, the old `General error: 1390 Prepared statement contains too many placeholders`

I suspect my dataset is far too large to eager load.

Anyway, this is not your problem @drbyte , this is mine.

Thanks for the support man.

**Comment by newtekDev** [comment]
@MadMikeyB Did you ever find a solution for this?

**Comment by MadMikeyB** [comment]
@newtekDev I believe I refactored the query I was running, I don't think there's a one size fits all solution.
