### ISSUE TITLE
Trait HasRoles line 179&180

### ISSUE THREAD

**Issue by Nowi5** [spatie/laravel-permission#807]
Hi,

in HasRoles.php you check in line 179 that the $roles does not include |, but why you try to explode in convertPipeToArray if there is no pipe in the string?

```
if (is_string($roles) && false !== strpos($roles, '|')) {
            $roles = $this->convertPipeToArray($roles);
        }
```

In general I'm not sure why you have duplicates in hasAllRoles and hasRole?

Thanks for double checking!

**Comment by drbyte** [comment]
`false !== strpos($roles, '|')` translates to:

"if the position of `|` (pipe) in $roles is not false", 
...which means "it is found somewhere in the string"

So, the overall logic of the code you quoted is:
"if $roles is a string and there is no pipe in $roles, then convert the pipe-delimited string to an array"

I think it's doing what it is intended to do.

**Comment by Nowi5** [comment]
I'm sorry...

**Comment by drbyte** [comment]
`hasRole` and `hasAllRoles` are slightly different in what they do. Yes there's a small bit of duplication but it's necessary. And it's minimal enough that it doesn't really need extracting to another method. Nevertheless, thanks for mentioning it. It's always good to look for overuse of duplication etc.
