### ISSUE TITLE
assignRole - Duplicate entry

### ISSUE THREAD

**Issue by Nowi5** [spatie/laravel-permission#808]
Hi,

when I use assignRole([..]) with multiple roles I get an MySQL error because the user has already one of the roles. Can we please surround that with a nice check? Splitting this up in a loop to run hasRole() in front is not the best, as I would need to replicate in a lot of Controller.

Thank you.

**Comment by Nowi5** [comment]
```
$roles = $request->input('roles') ? $request->input('roles') : [];

 foreach($roles as $role){
          if(!$user->hasRole($role){
            $user->assignRole($role);
          }
        }
```

**Comment by warlord0** [comment]
Why not use syncRoles if you're passing roles and not just a role? No need for duplicate checking then.

**Comment by Nowi5** [comment]
Because syncRoles would delete all other roles. To use syncRoles I would need to read all roles, put it into an array, add my new role (if not already exists) and than use syncRoles. But more important, a php function should never let a mysql dump unhandled.
