### ISSUE TITLE
Permissions cached incorrectly when CACHE_DRIVER=database

### ISSUE THREAD

**Issue by mstralka** [spatie/laravel-permission#81]
I'm using this package and I have two users with two different roles and permissions:
User 1 has the admin role, and the admin role has the ADMIN, EDIT, and VIEW permissions
User 2 has the user role, and the user role has the EDIT and VIEW permissions

My view has:

````
@can('ADMIN')
<a href="#">Some admin button</a>
@endcan
@can('EDIT')
<a href="#">Some edit button</a>
@endcan
````

When `CACHE_DRIVER=file` in my `.env` file, I can login as either user and I see the appropriate buttons in the views.  If I change `CACHE_DRIVER=database`, and login as the admin user in one Chrome incognito window, and login as the regular user in another window, the appropriate buttons appear for the first user I logged in as, but the appropriate buttons do not appear for the user in the 2nd window. 

If I run `./artisan cache:clear` and refresh either window, then that user's permissions are fixed, but the other user's permissions are still broken.

Looking at `PermissionRegistrar.php`, the getPermissions() function is putting the permissions into the cache forever:
````
protected function getPermissions()
{
    return $this->cache->rememberForever($this->cacheKey, function () {
        return app(Permission::class)->with('roles')->get();
    });
}
````

If I remove the caching layer it works properly, but that obviously has performance implications:
````
protected function getPermissions()
{
    return app(Permission::class)->with('roles')->get();
}
````

I'm not sure why it works properly when `CACHE_DRIVER=file` but doesn't work when `CACHE_DRIVER=database`?

Thanks

**Comment by freekmurze** [comment]
It should work with the `database` driver, not sure why this is giving problems.

I'd accept a PR that would add a `cache_store_name` in the config file and let the package use that cache store.

In that way you can have a separate cache which won't be cleared when flushing the main cache.

**Comment by graphem** [comment]
I am experiencing the same issue, with cache database, the permissions seems to not be respected.

**Comment by JiovannaManriquez** [comment]
It happends when value field of cache table is text type, you need to change it to longText.

**Comment by khangvm53** [comment]
I got exactly problem like mr @mstralka got for CACHE_DRIVER=database 
Do we have any new on there?

**Comment by RidaNoor** [comment]
> I got exactly problem like mr @mstralka got for CACHE_DRIVER=database
> Do we have any new on there?

Hi, any success? @mstralka @khangvm53

**Comment by drbyte** [comment]
If the `database` cache is failing, then your app's db schema for Laravel's `cache` table is probably old or fields too small.
Check your schema against Laravel's latest migration.

You can maybe fix it by running `php artisan cache:table`; you may have to temporarily delete an old migration for this to run, and then compare the files for differences, and then make a new migration to apply changes.

If your app is doing a lot of caching then you may need to override `mediumText` with `longText` as mentioned already.

**Comment by RidaNoor** [comment]
@drbyte  thankyou for the reply.
Actually, I have implemented Multi-tenancy inside the application, and I setup the database dynamically using ServiceProvider. 
But the ServiceProvider for this package runs before all other ServiceProviders no matter where-ever I put it inside the Providers list.
So, as the TenancyServiceProvider runs afterwards, it throws error as no DB is connected.
Maybe, we shouldn't make the registration of this ServiceProvider as an option rather we should have a control over when we want to boot this provider.

**Comment by drbyte** [comment]
> Maybe, we shouldn't make the registration of this ServiceProvider as an option rather we should have a control over when we want to boot this provider.

You can certainly [tell Laravel not to register this package automatically](https://laravel.com/docs/master/packages#opting-out-of-package-discovery). Then you can specify its order in your list of service providers in order to control it in relation to other dependencies your app has introduced.
