### ISSUE TITLE
remove table from migration next release

### ISSUE THREAD

**Issue by mohamedsharaf** [spatie/laravel-permission#810]
Role_has_permissions . (this can be removed and saved in ) below table

Model_has_permissions
id , type , permission_id
4 , role , permission_id 

am I missing anything here

**Comment by drbyte** [comment]
Yes, the v1 branch used some tables that v2 does not. 

**You should remove those manually. We will not automatically remove old tables.**

The v1 table names which are no longer used in v2 are:
`role_has_permissions`, `user_has_roles`, `user_has_permissions`
