### ISSUE TITLE
Role syncPermissions() issue

### ISSUE THREAD

**Issue by vagifrzada** [spatie/laravel-permission#812]
Hi !
When I'm use syncPermissions() and passing empty array to the method, i get an Exception : trying to get property 'guard_name' of non-object.
The problem coming from ensureModelSharesGuard() method. 
So, method accepts $roleOrPermission variable and without controlling tries to fetch guard_name property.

Please, fix that.

**Comment by drbyte** [comment]
Hi @vagifrzada 
Thanks for posting. 
Is your problem the same as #770?

**Comment by vagifrzada** [comment]
Yes it is.

**Comment by drbyte** [comment]
Okay. Thanks.
I will close this issue and we can continue relevant discussion over in #770.
