### ISSUE TITLE
SQL error when I assign the role or permission

### ISSUE THREAD

**Issue by FabrizioCafolla** [spatie/laravel-permission#822]
Lumen 5.6
I followed the guide and installed the 2.13 package

when run function to assign Role or Permission to user
$user->assignRole('writer');

return 
![schermata del 2018-08-09 13-41-49](https://user-images.githubusercontent.com/13237032/43896706-07f2f686-9bda-11e8-94a3-3ef1e0bdd1cd.png)

**Comment by diogogomeswww** [comment]
Is your user stored on the DB?

What does this show:
dd(`$user->getKey()`);

**Comment by FabrizioCafolla** [comment]
@diogogomeswwwt  sorry my error, user doesn't exist! thanks.
