### ISSUE TITLE
getPermissionsViaRoles() : Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by dariuszjastrzebski** [spatie/laravel-permission#824]
Hi,

I have issue with ``getPermissionsViaRoles()`` for just new created model:
```
    $user = new \App\User();
    $user->user_id = \Ramsey\Uuid\Uuid::uuid4();
    $user->email = 'email@gmail.com';
    $user->password = Hash::make('password');
    $user->save();

    $user->assignRole('role_name');

    $permissions = $user->getPermissionsViaRoles();  // throw: Illegal offset type in isset or empty
```

It's throw exception:
```
"Illegal offset type in isset or empty"
"/var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php"
239
array:6 [▼
  "models" => array:1 [▼
    0 => User {#260}
  ]
  "results" => Collection {#330}
  "relation" => "roles"
  "dictionary" => array:1 [▼
    "f1ccabf8-5f95-462c-9124-ef9e0ab4e8c1" => array:1 [▼
      0 => Role {#329}
    ]
  ]
  "model" => User {#260}
  "key" => Uuid {#265}
]
 ```

Of course I have done everything like in docs:

- Changed spatie migration to:
```
$table->uuid('model_id');
$table->string('model_type');
```
- use ``HasRoles`` trait in ``User`` model
- added sample Roles and permissions etc.

I use ``Laravel 5.5`` and ``Spatie 2.13.0`` and ``UUIDv4`` for primary key

I figured out that if I change on the model attributes like that: 
```
protected $keyType = 'string'; // add this line
public $incrementing = false; //remove this line
```
it's works correctly.

Writing this issue I realized that there is similiar issue #489 and the similar solution but one thing is different. For me it doesn't work with ``$incrementing = false;`` . Does any have idea why? Is this a good approach with setting ``$keyType`` to string?

**Comment by drbyte** [comment]
@dariuszjastrzebski v2.14.0 was released which adds some more flexibility in the polymorphic relationships by addressing #777 via #827
