### ISSUE TITLE
Extending the user model

### ISSUE THREAD

**Issue by angelformica** [spatie/laravel-permission#825]
Hello, I need some help here please. How can I extend the user model using this package?

I would like to be able to fetch for example Admin::all();

or $admin = new Admin;

Thank you for your help.

**Comment by drbyte** [comment]
I'm not sure I understand the question.

This package doesn't provide a User model. That's part of your app.

So you would extend the User model the same way you would extend any other model: 
`class foo extends bar`

**Comment by angelformica** [comment]
Thank you for your quick response. Well, I am not an expert, so I am a
little confused here.

Normally I would define a scope with a where(is_Admin,true)

but in this case, this is a relationship, and I can't seem to find a way to
do it with a relationship, I tried whereHas, but that also did not work.
May be you could put me in the right direction here.

Thanks for your help

**Comment by drbyte** [comment]
Okay, if your question is about scopes, this package provides the ability to return models associated with a certain role or permission, like these examples:

```php
$admin_role_name = 'administration';
$administrators = \App\User::role($admin_role_name);
```
or
```php
$users_with_write_permission = \App\User::permission('write');
```

**Comment by angelformica** [comment]
ok, thank you.
