### ISSUE TITLE
Laravel permissions in Vue.js

### ISSUE THREAD

**Issue by George2215** [spatie/laravel-permission#834]
I am implementing Laravel permissions in Vue.js, but I can not show the roles of each user in a table, likewise I can not show the permissions assigned to a role for its editing, the field shows me undefined.

I have used the package only with laravel and it works perfect, I appreciate the help

use App\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class UserController extends Controller
{        
    public function index(Request $request){                
        $users = User::all();        
        return ['users' => $users];
    }
}

//View
<tr v-for="user in arrayUsers" :key="user.id">
      <td v-text="user.identity_number"></td>
      <td v-text="user.first_name"></td>
      <td v-text="user.last_name"></td>
      <td v-text="user.email"></td>
      <td v-text="user.phone_number"></td>                                
      <td v-for="role in user.roles"v-text="role.name"></td>
</tr>

**Comment by drbyte** [comment]
To include the roles of each user when you query the Eloquent model, include the roles relationship:

`$users = User::with('roles)->all();`

**Comment by George2215** [comment]
my User model would be like this:

```
public function roles()
{
    return $this->belongsToMany(Role::class);
}
```

This error message is generated:

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'appconsultorio.role_user' doesn't exist (SQL: select `roles`.*, `role_user`.`user_id` as `pivot_user_id`, `role_user`.`role_id` as `pivot_role_id` from `roles` inner join `role_user` on `roles`.`id` = `role_user`.`role_id` where `role_user`.`user_id` = 1)`

**Comment by drbyte** [comment]
No. The `roles` relationship is already set by the `HasRoles` trait:
https://github.com/spatie/laravel-permission/blob/master/src/Traits/HasRoles.php#L40

Since it's a polymorphic relationship, the pivot details are different, hence the error you get in your basic `belongsToMany` attempt.

**Comment by George2215** [comment]
ok understood, already delete the method. but it is showing the error message
Call to undefined method Illuminate\Database\Query\Builder::all()

**Comment by George2215** [comment]
@drbyte Thank you very much for your time, I already solve it
