### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by deadmouse** [spatie/laravel-permission#835]
I'm receiving the following error: 

> Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of &#039;256&#039; reached, aborting! in file C:\wamp\www\...\API\vendor\laravel\framework\src\Illuminate\Support\Str.php on line 103
> Stack trace:
>   1. Symfony\Component\Debug\Exception\FatalThrowableError-&gt;() C:\wamp\www\proyecto3\...\vendor\laravel\framework\src\Illuminate\Support\Str.php:103
>   2. {main}() C:\wamp\www\proyecto3\...\public\index.php:0

With this code in User.php:

```
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;
use Laravel\Cashier\Billable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable, Billable, HasRoles;

    protected $fillable = [
        'name', 'email', 'password'
    ];

    protected $hidden = [
        'password', 'remember_token'
    ];

    public function roles()
    {
        $user = User::find(48);
        $roles = $user->getRoleNames();
        return $roles;
    }
}
```

I have done a little bit of research and almost everything talks about Xdebug, which I use to debug. From [stackoverflow](https://stackoverflow.com/a/10512188/3525362):

![Image](https://i.imgur.com/2PAxEvK.png)

I have already tried that solution, increasing to 1000 or 2000 I get in Postman: "Could not get any response", and less than 1000 the error mentioned above.

When I try to debug _getRoleNames()_ with `xdebug.max_nesting_level = 400` (for example), this is what happens:

![Gif](https://media.giphy.com/media/jl6VU3nXgT2IxpuBB0/giphy.gif)

But that weird infinite loop doesn't happen if instead of `$roles = $user->getRoleNames();`, I put `$roles = $user->permissions;`.

What is happening? I just want to get the roles of the user who requests.

**Comment by drbyte** [comment]
Ya, that's a PHP configuration issue on your end. Nothing to do with this package.
