### ISSUE TITLE
BadMethodCallException Method Illuminate\Database\Query\Builder::can does not exist.

### ISSUE THREAD

**Issue by yashjethva** [spatie/laravel-permission#836]
issue in permissionmiddleware.php
Line No 22

```
if (app('auth')->user()->can($permission)) {
     return $next($request);
}
```

**Comment by drbyte** [comment]
Have you bound `app('auth')` to something other than Laravel's default? What specifically?

**Comment by drbyte** [comment]
@yashjethva Did you resolve your problem?
