### ISSUE TITLE
use @can inside a vue component

### ISSUE THREAD

**Issue by ksromero** [spatie/laravel-permission#839]
How can i use blade directive @can inside a vue component to authorize a user?

```
@can('edit-post')
     <button><button>
@endcan
```

**Comment by drbyte** [comment]
This package doesn't do anything specific to Vue.

The answer to your question is general to Laravel/Vue.
Here are some articles to consider for learning how to bring back-end server logic to the front-end:
https://pineco.de/implementing-laravels-authorization-front-end/
https://stackoverflow.com/questions/45868924/using-laravels-gate-authorization-in-vuejs
https://vuejsdevelopers.com/2018/01/08/vue-js-roles-permissions-casl/
https://vegibit.com/how-to-use-vuejs-with-laravel-blade/

**Comment by iamgergo** [comment]
Hey guys! We get a quite much click from this issue (pineco.de), so it made us convert the article to a real package. Give it a show if you wish: https://github.com/thepinecode/policy
