### ISSUE TITLE
Reverse relations

### ISSUE THREAD

**Issue by ediblemanager** [spatie/laravel-permission#840]
I have my app configured for two distinct kinds of users, `Administrators` and `Members`. As `Administrators` can view lists of `Members` and pull certain data about them, I wanted to access the data stored in `users`, but can't work out how to go backwards through the Morph relationship between a `Member` and a `User`.

I've read over as many issues as matched my searching for this, but didn't find anything that matched. I've also read over the Morph relations sections on the Laravel docs, but can't seem to formulate my relations in `Administrator` and `Member` correctly to pull data from `users`.

**Comment by ediblemanager** [comment]
Yeah, I'm daft, closing this as I've found a solution

**Comment by ediblemanager** [comment]
The purpose of accessing `users`: I've added some columns to `users` that I'd like to access when accessing a `Member` (`last_login` etc.), or a collection of `Member`'s. 

The relationship between the `users` table, `model_has_roles` table and my `members` table is where my conundrum lies: like mentioned in the paragraph above, I want to be able to access data for the member which is stored in `users`. Since this package is managing that, I guessed this was the place to ask!

How does `users` get linked to `model_has_roles`? I see that there's a `role_id` and a `model_id` (the latter the same as on `users`), but I don't understand how they are linked when you use this package to access a user. This is probably a weak understanding of a Laravel concept, apologies if so!

**Comment by ediblemanager** [comment]
I reckon I'm using Laravel's built in Auth wrong (I log in, then check roles and redirect appropriately), using the same guard for both Admin and Member users. I'll investigate using two different user models for this.

**Comment by drbyte** [comment]
@ediblemanager Did you sort out what you needed?

**Comment by ediblemanager** [comment]
I did. I figured out where I was going wrong in implementing two guards and got things working. Thanks for your help!
