### ISSUE TITLE
Laravel 5.7 Dependancy Issue

### ISSUE THREAD

**Issue by bhargav960143** [spatie/laravel-permission#843]
- Installation request for spatie/laravel-permission ^2.16 -> satisfiable by spatie/laravel-permission[2.16.0].
    - Conclusion: remove laravel/framework 5.7.x-dev
    - Conclusion: don't install laravel/framework 5.7.x-dev
    - spatie/laravel-permission 2.16.0 requires illuminate/database ~5.4.0|~5.5.0|~5.6.0 -> satisfiable by illuminate/database[5.4.x-dev, 5.5.x-dev, 5.6.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28
, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5
.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].

**Comment by drbyte** [comment]
We will tag a 5.7 compatible release when 5.7 comes out.
https://github.com/spatie/laravel-permission/pull/829#issuecomment-413176994

**Comment by drbyte** [comment]
New release tagged.
