### ISSUE TITLE
Extending assignRole method.

### ISSUE THREAD

**Issue by enbermudez** [spatie/laravel-permission#848]
Hi! I want to extend the ``assignRole`` method so I can work with new field on my ``model_has_role`` table and this field would be: ``code``. Why so? Well, if I do this:

```$user->assignRole('writer');```

It will throw an error because the field ``code`` can't be ``null``. Is there any way to change this method to work like this:

```$user->assignRole('writer', 'TT000');```

**Comment by drbyte** [comment]
You can copy the code for that method from the trait into your model and customize it there.
