### ISSUE TITLE
Permissions Checked

### ISSUE THREAD

**Issue by George2215** [spatie/laravel-permission#850]
I am doing the edition of the permissions of the role, but it is not showing me the ones already assigned, within my tests identify that I have conflict with the pivot of the role, as I can show the assigned permissions without this affecting me in the view. I have the whole view inside a Vue component

how can I make a query and not return the pivot data?

```
public function index()
{
$roles = Role::with('permissions')->get();				
return['roles' => $roles];
}
```

```
editRole(role){                       
     this.fillRole.id   = role.id;
      this.fillRole.name = role.name;
      this.permissions = role['permissions'];
      this.editModal();//muestra el formulario
}
```
[Role.txt](https://github.com/spatie/laravel-permission/files/2337079/Role.txt)

**Comment by enbermudez** [comment]
``$roles->makeHidden(['pivot']);``

**Comment by George2215** [comment]
Solved,
class Permission extends \Spatie\Permission\Models\Permission
{
    protected $hidden = ['pivot'];
}

**Comment by enbermudez** [comment]
Wait, i didn't see that structure. It would be like this:

```$roles->permissions->makeHidden(['pivot']);```

**Comment by George2215** [comment]
solved.

class Permission extends \Spatie\Permission\Models\Permission
{
    protected $hidden = ['pivot'];
}
