### ISSUE TITLE
$table->morphs('model') This thing doesn't exists on create_permission_table

### ISSUE THREAD

**Issue by NietzscheCoder** [spatie/laravel-permission#851]
"If you're using UUIDs or GUIDs for your User models you can update the.."

I can nowhere find $table->morphs('model') under create_permission_table

**Comment by drbyte** [comment]
Oops - you're right. The README is outdated. 
Now you just change
```diff
-$table->unsignedBigInteger($columnNames['model_morph_key']);
+$table->uuid($columnNames['model_morph_key']);
```
and change the `model_morph_key` in the config file to `model_uuid` or whatever you want the column called for consistency.

README is getting updated.
