### ISSUE TITLE
Skeleton Key for a super admin that circumvents Gate::class Permissions?

### ISSUE THREAD

**Issue by ereztdev** [spatie/laravel-permission#852]
I've set up all my permissions/roles from admin to the lowest user.
Now I need to create a super user (above admin) **that is not** DB/Permission/Role dependable, he can enter any route and can see any blade `@can()` directive.
Super-Admin would have access by accessing DB one time to query `Auth::user()->email.

I just need to know if this is doable at this stage, can a middleware circumvent Laravel's `Gate::class`? I need to know if at this stage it's possible or would I have to private fork and diverge (bad option for me) to build this small issue.

Thanks!

**Comment by drbyte** [comment]
I would use a `Gate::before()` call, similar to https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role
