### ISSUE TITLE
Problems with permission exist or "user dont have the right permission" everytime

### ISSUE THREAD

**Issue by MatiasNovoa** [spatie/laravel-permission#853]
I have an api laravel with spatie / laravel permission but it does not work. Every time I try to use the permission middleware, I get the errors, the name or the permission is incorrect, but the permission exists and the user really has that permission.

For the solution, copy the role middleware in the permission middleware and change the variables to $ role for $ permission, then in the config / auth file, change the guard position api first than the web guard.

And now work.

**Comment by drbyte** [comment]
For v2 of this package, since your app is using only the `api` guard, changing the guard position in the config file is sufficient. Otherwise you must specify the guard in every request and every affected model.
