### ISSUE TITLE
why i should set guard_name at user model , and how can i set one user to two guard，such as 'api'，'web' together?

### ISSUE THREAD

**Issue by qujsh** [spatie/laravel-permission#856]
why i should set guard_name at user model？when i want to set one user about two guard，like: $user->assignRole('Founder', Founder_web'); ( founder's guard_name is api， Founder_web‘s guard_name is web)，throw me an error, from errorinfo，it looks like you select data by default guard_name，and i assignRole twice。so，why i don't execute  $user->assignRole('Founder', Founder_web') ? in addition, when my user model's guard_name is api, i use the middleware, like: $api->post('/', 'UserController@create')->middleware('permission:add user');  and "add user" permission's guard_name is web，it show me "User does not have the right permissions". i have 'api' and 'web' rights，but it throw me an error. i think it's wrong and can be patch。sorry to say so and no do it myself, it's a little difficult for me at present.

**Comment by drbyte** [comment]
Currently v2  of this package works best when a model is associated with 1 guard, specified as $guard_name in the model. That means if you have a need for multiple guards, it is easiest to create a new model to associate with it.

But most apps don't require separate permissions per guard. If that's also your case, you could use v1 of this package.
