### ISSUE TITLE
Role/Permission Expiry

### ISSUE THREAD

**Issue by Rjs37** [spatie/laravel-permission#86]
Have you considered possibly expanding the system to include roles (or even permissions) that expire?

A few potential use-cases: temporarily suspending a user (suspended user role), temporarily promoting someone to be an admin, giving temporary access to a particular permission.

This is something that I'm looking to do for myself, but thought I'd add a suggestion for the package too. 

I'd do it with an expires_at date field and then introducing a console command to remove expired roles/permissions. Something you might accept a PR for?

**Comment by freekmurze** [comment]
Hi,

The proposed functionality makes sense but I'd probably not accept a PR for this because:
- it would add some complexity to the package
- not many users needs this
- I don't need this 😄 

You're of course free to fork this package and add the features you need.

**Comment by Rjs37** [comment]
Fair enough, cheers for the prompt reply :). I won't bother doing it as a fork as I'd rather keep to the original repo. I'll stick to doing it separate from the package.

**Comment by royanon** [comment]
Right, I think we can keep an expiry in user table, and keep a scheduler to scan through it everyday and change the role whenever role is expired.
