### ISSUE TITLE
Calling $user->getAllPermissions() returns an error

### ISSUE THREAD

**Issue by Shadomax** [spatie/laravel-permission#860]
Hey, thanks for this awesome package. I have been using this package excellent well until now that i want to using this method `$user->getAllPermissions()`
When i call the method i get this error message
`"Undefined property: App\\User::$permissions"`

Please can anyone point out to me what am doing wrong here. Thanks.

**Comment by zhiyong80** [comment]
What is your version of Laravel and laravel-permission?

With Laravel 5.5.43 & laravel-permission 2.17.1, I get the following:
```
{
    "withTimestamps": false
}
```

**Comment by drbyte** [comment]
When you add the `HasRoles` trait to your `User` model, it will add the `HasPermissions` trait.
The `HasPermissions` trait defines the `getAllPermissions()` method:
https://github.com/spatie/laravel-permission/blob/63ef871cf85d664babc4556c6e5b826cda9f141e/src/Traits/HasPermissions.php#L245-L251

... which refers to `$this->permissions`, which is from the `permissions()` relationship also defined inside the `HasPermissions` trait:
https://github.com/spatie/laravel-permission/blob/63ef871cf85d664babc4556c6e5b826cda9f141e/src/Traits/HasPermissions.php#L41-L50

If you're getting `"Undefined property: App\\User::$permissions"` errors, then it would seem that you've done something which overrides the code or inheritances supplied by the traits in this package.

**Comment by Shadomax** [comment]
Thanks. I have resolve the issue.

**Comment by diesel437** [comment]
Hi, I have the same issue.. what did you do to fix it @drbyte ??

**Comment by aeadedoyin** [comment]
For those having the same issue, in your user model:.
```
    public function __construct()
    {
        $this->getAllPermissions();
    }
```
