### ISSUE TITLE
getAllPermissions() and roles() not supported in API guard?

### ISSUE THREAD

**Issue by zhiyong80** [spatie/laravel-permission#863]
Laravel 5.5.43, Passport 3.0, laravel-permission: 2.17.1

I am trying to return all the roles and permissions a user has as JSON via API calls.

Code in controller:
```
return ($request->user()->roles());
```
When I query the API end point, I get this:
```
{
    "withTimestamps": false
}
```
When I place following code guarded by default web guard:
```
var_dump($request->user()->roles());
```
output into web pages in browser seems working as expected.

The other functions, assignRole(), syncRoles() seems working fine in Passport API guarded routes though.

**Comment by drbyte** [comment]
Shouldn't that be:

```diff
-return ($request->user()->roles());
+return ($request->user()->roles);
```

**Comment by zhiyong80** [comment]
@drbyte thanks. This works.
