### ISSUE TITLE
@unlessrole directive

### ISSUE THREAD

**Issue by futzlarson** [spatie/laravel-permission#866]
Not an issue, but a request. Even though php itself doesn't support this, I am quickly finding myself desiring an `@unlessrole` directive. I added some roles and so far the most common request has been "do this unless the user has this role", which means a lot of:

```
@role('production-only')
    {{-- Hide. --}}
@else
    /* Code. */
@endrole
```

Which feels wrong. In php I would have a bit more flexibility because I could do `if (! $user->hasRole('production-only'))`. Is there a way to do this in Blade that I am missing?

**Comment by drbyte** [comment]
The simplest would be to use blade's `@unless` directive

```blade
@unless($user->hasRole('production-only'))
```

Alternatively we could consider adding an unlessrole directive to this package.

**Comment by futzlarson** [comment]
In my case it would actually be:

```
@unless(auth()->user()->hasRole('production-only'))
```
Which is a little less elegant so yeah, seems worth adding to me.

**Comment by drbyte** [comment]
v2.19.0 released with `@unlessrole` directive
