### ISSUE TITLE
I need to delete a role, do not delete the role directly by the user, how should I delete it? Need to delete database records directly?

### ISSUE THREAD

**Issue by xuekew** [spatie/laravel-permission#869]
I need to delete a role, do not delete the role directly by the user, how should I delete it? Need to delete database records directly?

**Comment by drbyte** [comment]
`$role = Role::findByName();`
or 
`$role = Role::findById();`

then since it's just an Eloquent model, a normal Eloquent command to delete will work:
`$role->delete();`

**Comment by szabizs** [comment]
> `$role = Role::findByName();`
> or
> `$role = Role::findById();`
> 
> then since it's just an Eloquent model, a normal Eloquent command to delete will work:
> `$role->delete();`

But be sure to refresh the cache as noted in the documentation.

> HOWEVER, if you manipulate permission/role data directly in the database instead of calling the supplied methods, then you will not see the changes reflected in the application unless you manually reset the cache.

**Comment by osueke-christian** [comment]
`Because the Role and Permission models are Eloquent models which implement the RefreshesPermissionCache trait, creating and deleting Roles and Permissions will automatically clear the cache.`
