### ISSUE TITLE
Laravel 5.2 - doesn't recognise Blade directive (@role, @hasanyrole, etc.) 

### ISSUE THREAD

**Issue by kingsloi** [spatie/laravel-permission#87]
Hi, 

Absolutely love Spatie's work - use them in every project - thanks for all your hard work!

I'm having trouble using the Blade directives. I've used `@hasanyrole(['manager','admin'])` and `@endhasanyrole` but the code is just spat out and not being processed. 

I've `dd('here')` on this line in the [PermissionServiceProvider.php](https://github.com/spatie/laravel-permission/blob/master/src/PermissionServiceProvider.php#L63) and it's not called either. 

Following the 5.2 docs on registering a Blade extension, [they say use the Blade::directive()](https://laravel.com/docs/5.2/blade#extending-blade).

Here's my fix:
https://gist.github.com/kingsloi/e2edc22d507147367142b5b24e111c7d

And it works a treat. 

Any ideas?

**Comment by LKDevelopment** [comment]
Can't reproduce this on Laravel 5.2.39

**Comment by kingsloi** [comment]
Weird as I also have v5.2.39. I did definitely dump composer, clear cache views, etc. I'll have another look!

**Comment by freekmurze** [comment]
Reopen if this is still a problem and if possible submit a failing test.
