### ISSUE TITLE
Integrity constraint violation: 1048 Column 'model_id' cannot be null

### ISSUE THREAD

**Issue by musman92** [spatie/laravel-permission#870]
my package details are 
"laravel/framework": "5.6.*",
"spatie/laravel-permission": "^2.19"

when i assign a role 
$user->syncRoles(['role']);
$user->assignRole('role');

 Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'model_id' cannot be null (SQL: insert into `model_has_roles` (`model_id`, `model_type`, `role_id`) values (, App\User, 2))

thanks in advance

**Comment by drbyte** [comment]
In your Eloquent model for `App\User`, what is the column-type for your `id` field? 

This package expects it to match the `model_id` type of the `model_has_roles` table.

**Comment by musman92** [comment]
`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
how I match model_id?

**Comment by drbyte** [comment]
What is the value for `model_morph_key` in your `config/permission.php`?

https://github.com/spatie/laravel-permission/blob/master/config/permission.php#L83

**Comment by musman92** [comment]
the value is 
'model_morph_key' => 'model_id',

**Comment by drbyte** [comment]
No, it should be model_id.

This is puzzling. I think you've changed something in your `App\User` model that's causing it.
It's hard to troubleshoot this without seeing your code.

**Comment by musman92** [comment]
below is the my user model`<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
  use Notifiable, HasRoles;

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'name', 'email', 'password',
  ];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [
    'password', 'remember_token',
  ];

}
`

**Comment by drbyte** [comment]
Can you share the code where you're trying to assign and sync roles to users?

**Comment by drbyte** [comment]
You can't sync something to a model that hasn't been persisted yet.

You must call `$user->save()` before you sync or assign.

**Comment by musman92** [comment]
@drbyte  thank you it works. but it should send a proper message. thank you anyway

**Comment by seasoftnaymyohtet** [comment]
> _hhhdfhdndjcjkdsaj****_

**Comment by IgorRadovic** [comment]
Thank you @drbyte you saved my day.
You are my hero :D

**Comment by brenoassp** [comment]
Hello,
I have a similar problem, but `$user->save();` didn't fix the problem for me.
Can I describe it here or need to create a new issue?

**Comment by drbyte** [comment]
@brenoassp Please open a new issue for it, containing as much information as possible to recreate your problem with a fresh Laravel install.

**Comment by hasmukh-dharajiya** [comment]
@musman92 
Open the User model and in case of this is include in your model so please remove this.
**Befor**
```
    protected $primaryKey = 'id';
    public $incrementing = false;
    public $timestamps = false;
```
**After**    

    ```
protected $guard_name = 'admin';
    protected $table = 'agnt_users';
```
