### ISSUE TITLE
Too few arguments to function on RoleMiddleware and PermissionMiddleware

### ISSUE THREAD

**Issue by antweny** [spatie/laravel-permission#871]
Hi,

I'm trying to use this package in Laravel 5.7 but i received this error msg
"Too few arguments to function Spatie\Permission\Middlewares\PermissionMiddleware::handle(), 2 passed in C:\xampp\htdocs\www\expert\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php on line 151 and exactly 3 expected"

My route/web.php

Route::group(['middleware' => ['super-admin']], function () {
    Route::resource('permissions','PermissionController');
    Route::resource('roles','RoleController');
    Route::resource('dashboard','DashboardController');
    Route::resource('users','UserController');
});

My kernel.php

protected $middleware = [
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class,
        'permission' => \Spatie\Permission\Middlewares\PermissionMiddleware::class,
        'super-admin' => \App\Http\Middleware\SuperAdmin::class,
        'clearance' => \App\Http\Middleware\Clearance::class,
    ];

Where is the problem?, i have stacked here for weeks now

**Comment by drbyte** [comment]
Since the error message says `PermissionMiddleware::handle()` isn't receiving correct parameters, and you've defined `permission` to be the middleware that calls it, you need to look at everywhere your app which attempts to use the `permission` middleware and make sure you're actually passing the name of permission you want the middleware to check for.

**Comment by 4unkur** [comment]
I faced the same issue. The problem was: I put  
```
'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class
```  
in ` protected $middleware `  
and not in `    protected $routeMiddleware `

**Comment by antweny** [comment]
> I faced the same issue. The problem was: I put
> 
> ```
> 'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class
> ```
> in `protected $middleware`
> and not in `protected $routeMiddleware`

Thank you very much for reply but already figured it out.

**Comment by romaricsylvain** [comment]
Solved it by moving 
'role' => \Spatie\Permission\Middlewares\RoleMiddleware::class
 to  
protected $routeMiddleware = [ 
];

**Comment by k4khuram** [comment]
and in laravel 10 you have to add this in protected $middlewareAliases

**Comment by MohamedAtef777** [comment]
> and in laravel 10 you have to add this in protected $middlewareAliases

what about laravel 11

**Comment by houssamHADELAMOUS** [comment]
> > and in laravel 10 you have to add this in protected $middlewareAliases
> 
> what about laravel 11
hahaha no one gonna answer hahaha

**Comment by V13tthnh** [comment]
> > and in laravel 10 you have to add this in protected $middlewareAliases
> 
> what about laravel 11
In bootstrap/app.php add this shit in withMiddleware callback func:
 $middleware->alias(['role' => \Spatie\Permission\Middleware\RoleMiddleware::class,]);
It works for me

**Comment by drbyte** [comment]
https://github.com/spatie/laravel-permission/blob/main/docs/basic-usage/middleware.md
