### ISSUE TITLE
Cannot get permissions by Role ID

### ISSUE THREAD

**Issue by paulcanning** [spatie/laravel-permission#876]
I am trying to get the permissions attached to a role via

```
$role = Role::findById($id);
```

And then loop through the permissions via

```
foreach ($role->permissions as $perm) {
    $role_permissions[] = $perm->id;
}
```

But this simply isn't working. Any ideas?

**Comment by drbyte** [comment]
Since it's just a typical Laravel model, you just need to `load` the relations if you want to query them.
Various ways to do that, but in your context the following will probably suffice:
 
```php
$role = Role::findById($id);
$role->load('permissions');
```
