### ISSUE TITLE
hasPermissionTo() returning the first user and not the logged in user

### ISSUE THREAD

**Issue by gregorise** [spatie/laravel-permission#879]
I have an issue where Auth::user()->hasPermissionTo('permission_name') is always returning the first user. 

In my User model I'm using the HasRoles trait. After debugging the only workaround I could find is copying the hasRole() method from the trait to the User model. E.g.

public function hasRole($roles): bool
{
..
}

Then it seems to behave as expected. 

I'm using version: ^2.17

**Comment by drbyte** [comment]
I cannot duplicate this, which suggests it's something unique to your application.
Can you share your code and config?  config/permission.php, config/auth.php, config/app.php, app/User.php, and any code related to your uses of `Auth::user()->hasPermissionTo('permission_name')`

**Comment by lk77** [comment]
Hello,

perhaps you are calling ->newQuery() or ->query() somewhere,
and resetting the query parameters by mistake.

**Comment by gregorise** [comment]
I was stuck on this for a while, so for good measure I tried a fresh install, composer update and it seems to be behaving correctly now (both role and permission checks).
