### ISSUE TITLE
Middleware usage

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-permission#88]
I am on Laravel 5.2.39, how can I use this package in combination with middleware? I would like to protect a few routes with this package.

**Comment by peterquentin** [comment]
@Cannonb4ll Here's how I do it:

`php artisan make:middleware RoleMiddleware`

This will create a `RoleMiddleware` for you and here is a gist of mine: https://gist.github.com/peterquentin/7c7fbe49b9f2d34ab20f0b2b2b50c84a

Don't forget to add the route middleware to your `App\HTTP\Kernel`

And last but not least protect your routes with the middleware:

```
Route::group(['middleware' => ['role:admin,access_backend']], function () {
    //
});
```

**Comment by Cannonb4ll** [comment]
Thanks mate! Great solution :)

**Comment by drbyte** [comment]
Is there value in this middleware example being added to the README for this project?

**Comment by peterquentin** [comment]
I'd say yes, though it's not up to me ;D

**Comment by drbyte** [comment]
Fair ... I know spatie is generally very open to useful PRs ;)

**Comment by freekmurze** [comment]
Enjoying a holiday atm😎☀️🌊
Will take a look at it in the coming week

**Comment by freekmurze** [comment]
Yup, I'd must certainly would accept a PR that adds the example above to the readme.

**Comment by peterquentin** [comment]
@freekmurze Pull request  #92 made, please review if it's to your liking. :grin:

**Comment by freekmurze** [comment]
Reviewing it now 😄

**Comment by drbyte** [comment]
Kudos. Thanks for adding this.
