### ISSUE TITLE
Problem while doing preview User, roles and permissions on backpack

### ISSUE THREAD

**Issue by jperdomo95** [spatie/laravel-permission#882]
Good evening, I have  problem with laravel backpack API when I try to preview users, roles and permissions.
Whenever I try to use the preview action I get a custom 403 error page made by me.
Laravel debug bar shows the following message:
![errorhassaccessorfail](https://user-images.githubusercontent.com/25458295/46160844-c4852600-c251-11e8-84e4-4db924942aef.png)

**Comment by jperdomo95** [comment]
Good evening, I have  problem with laravel backpack API when I try to preview users, roles and permissions.
Whenever I try to use the preview action I get a custom 403 error page made by me.
Laravel debug bar shows the following message:
![error403](https://user-images.githubusercontent.com/25458295/46160809-a4edfd80-c251-11e8-8f85-1ab4799ac4e3.png)

**Comment by drbyte** [comment]
That appears to be a problem with your site and/or Backpack, not this package.
According to the error message, whatever user you're logged in as doesn't have the necessary permissions assigned.

**Comment by jperdomo95** [comment]
I actually managed to figure out the problem, I'm not sure if it's because of my local configuration but I found out the following:
Somehow the 'show' method is disabled by default, so I had to add $this->crud->allowAccess('show'); to the vendor/backpack/permissionmanager/src/app/Http/Controllers/UserCrudController.php to make it work.
