### ISSUE TITLE
Assign all permissions to a role

### ISSUE THREAD

**Issue by kamov** [spatie/laravel-permission#893]
If you have multi guard and try to assign all permissions to a role, then it give an error, because Permission::all() return all permissions of all guards.

I think that we should be able to return all permissions by guard name.

Example:

```php
        $role = Role::create(['guard_name' => 'admin', 'name' => 'super-admin']);
        $role->givePermissionTo(Permission::all('admin')); // Permission of guard_name = admin
```

**Comment by hulkur** [comment]
It's a query builder

`Permission::where('guard_name', 'admin')->get()`

**Comment by kamov** [comment]
oh You are right... thank you!

so even more quick Permissin::whereName('admin')->get();

**Comment by drbyte** [comment]
Or better yet, instead of linking up a bunch of permissions and having to maintain that list for a super-admin, use a Gate::before policy hook as explained at: https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role
