### ISSUE TITLE
Sessions and middleware not working anymore in controller's constructor

### ISSUE THREAD

**Issue by enghelewa** [spatie/laravel-permission#895]
According to[ laravel's upgrade docs](https://laravel.com/docs/5.3/upgrade#5.3-session-in-constructors) this will not work for `laravel 5.3+` as session variables will not exist in controller. `Auth::user()` will always return [null](url).

```
public function __construct()
{
     $this->middleware('auth:api', ['except' => ['login']]);
}
```

Is there any workaround?

**Comment by drbyte** [comment]
This package doesn't use the `auth` middleware.
