### ISSUE TITLE
Taking to much time to assign permission to role 

### ISSUE THREAD

**Issue by vchampanery** [spatie/laravel-permission#896]
I have superadmin role and 150 category and each have 6 action  and when i try to give permission to that role  as per following code, its taking too much time can you please help me out and show me way to resolve my issue and assign permission faster 

$role = \Spatie\Permission\Models\Role::find($roleId);
$permission = \Spatie\Permission\Models\Permission::findByName($permissionName);
$role->givePermissionTo($permission);

**Comment by drbyte** [comment]
A more common practice for super-admin handling is to NOT assign every permission to the super-admin, but rather to use the Gate to identify a super-admin by their role, and treat them as though they have every permission. This can be done with a few lines of code like this: 
https://github.com/spatie/laravel-permission/wiki/Global-%22Admin%22-role

**Comment by drbyte** [comment]
`givePermissionTo()` can accept a collection of Permission objects. So instead of assigning one-by-one, you can pass a collection, which will skip some of the lookups it has to do.
