### ISSUE TITLE
Permission (non)caching is a result of blade directives

### ISSUE THREAD

**Issue by hotsaucejake** [spatie/laravel-permission#897]
If I use the @can directive, my permissions are not accessing the cached permissions.

However, using `@if(auth()->user()->hasPermissionTo('add_users'))` etc... it can properly access the cached permissions.

I went from ~400 gate checks to 1 when I switched out my blade directives.

Perhaps in [the documentation here](https://github.com/spatie/laravel-permission#blade-and-permissions) it should be changed to reflect that.

**Comment by drbyte** [comment]
> I went from ~400 gate checks to 1 when I switched out my blade directives.

If you don't use the `@can` Gate directive, then yes your gate checks will go down because you're completely bypassing the Gate.

This package currently registers a Gate callback for permission checks. The query which feeds the results of that is cached. But the calls to the gate itself are not cached.

**Comment by lloricode** [comment]
we can add this as blade directive?

```php

       Blade::directive('hasPermissionTo', function ($permission) {
            if (!auth()->check()) {
                return false;
            }
            return auth()->user()->hasPermissionTo($permission);
        });


// @hasPermissionTo('view backend')

```

**Comment by antweny** [comment]
You can create a custom blade directive:

```
Blade::if('permission',function ($permission) {
            if (auth()->user()->hasRole('superAdmin')) {  //if auth user is super admin the system will grant you full access
                return true;
            }
            return auth()->check() && auth()->user()->hasAnyPermission($permission);
        });
```

and you can pass your permissions on view like this

```
@permission('add_users')
your code here
@endpermission

```
