### ISSUE TITLE
Not possible to remove role with collection

### ISSUE THREAD

**Issue by mstaroste** [spatie/laravel-permission#898]
Hello,

the documentation says: 

> The assignRole, hasRole, hasAnyRole, hasAllRoles and removeRole functions can accept a string, a \Spatie\Permission\Models\Role object or an \Illuminate\Support\Collection object.

But

`$roles = $user->getRoleNames();
$user->removeRole($roles);`

Wont work.

**Comment by vchampanery** [comment]
Following is works for me :

```
$role = $userobj->roles->first()->name;
$userobj->removeRole($role);
```
