### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::assignRole()

### ISSUE THREAD

**Issue by Reydesel** [spatie/laravel-permission#90]
I keep getting this error and i checked many times every link.

        namespace App\Http\Controllers;

        use App\Http\Requests;
        use App\User;
        use Illuminate\Http\Request;
        use Spatie\Permission\Traits\HasRoles;

        class HomeController extends Controller
        {
            use HasRoles;
            /**
             * Create a new controller instance.
             *
             * @return void
             */
            public function __construct()
            {
                $this->middleware('auth');
            }

            /**
             * Show the application dashboard.
             *
             * @return \Illuminate\Http\Response
             */
            public function index()
            {

                $user =User::first();
                $user->assignRole('writer');
                return view('home');
            }
        }

**Comment by freekmurze** [comment]
Did you use the `HasRoles` trait on your user model?

https://github.com/spatie/laravel-permission#usage

**Comment by Reydesel** [comment]
Ok that worked, sorry i was using it on the controller. Thanks
