### ISSUE TITLE
How can i save user_has_permission and role_has_permission in json to avoid multiple entry

### ISSUE THREAD

**Issue by vchampanery** [spatie/laravel-permission#900]
current when i  assign 5 permissions to user than in my user_has_permission table has five entry and also when i enter 15 permission to role than in my role_has_permission table has 15 entry .

I want to change that both table entry into single entry each i means i will convert into  json and save into json format

how can do that ? and also how hasPermission() function will react and what i need to changes on use haspermissionI() from json

for exmaple 
current  user_has_permission  table 
user_id permission_id
1069      712
1069      713
1069     714
1069     715
want to convert 
user_id permission_id
1069  { 712 ,713, 714, 715}

also want to know how haspermission() function will use in new structure?

**Comment by drbyte** [comment]
This package is not currently built around storing the data that way.

You've posted in multiple other issues suggesting that you want json instead. You're welcome to use your own fork of the package which flattens the storage to drop the polymorphic relation and store json text instead.
