### ISSUE TITLE
Lumen: Class 'Illuminate\Routing\Route' not found

### ISSUE THREAD

**Issue by moeen-basra** [spatie/laravel-permission#904]
After upgrading package for lumen 5.7 I'm facing this problem.

I think there is no support for macros in lumen router and Facade for router you are trying to use its for laravel not for lumen.

**Comment by urukalo** [comment]
same for lumen 5.6

**Comment by stefanvanherwijnen** [comment]
I am having the same issue with Lumen 5.6 and laravel-permission 2.22.0. Version 2.17.0 works fine.
Probably related to this commit:
https://github.com/spatie/laravel-permission/commit/69fba17fe864da9cb2e9b03e7d97bb7fced75595
