### ISSUE TITLE
Get Permission by role name

### ISSUE THREAD

**Issue by vchampanery** [spatie/laravel-permission#906]
if i  give two role to one user  than how can i find  permission for the only one role 
$permissions = $user->getDirectPermissions(); // all direct permission
$permissions = $user->getPermissionsViaRoles(); // alll roles permission
$permissions = $user->getAllPermissions(); // all permission

 But how i can fetch particular roles permission : 

That is 
$permission = $user-getPermissionViaRoles('customerplan');

**Comment by drbyte** [comment]
`$role->permissions`
