### ISSUE TITLE
how to get softdeleted on permission table  that is user_has_permission and role_has_permission?

### ISSUE THREAD

**Issue by vchampanery** [spatie/laravel-permission#907]
I want to add soft delete as is_deleted in user_has_permission and role_has_permission? 
also i want to know how i can identify for user's permission  by 
1. $user->hasPermission('permissionname') and 2. @can('permissionname') and consider also for is_deleted = 0 only and return true/false?
2. how to modify  $user->hasPermission() and @can()  function for ignour is_deleted = 1 values.
Please help me.. it as per my system requirement i stuck with this.

**Comment by drbyte** [comment]
This package only supports soft-deletes at the User model level, not the role/permission level. 
There are no plans to change this.

You will need to override the various trait methods to add your custom logic for handling soft-deletes safely.
