### ISSUE TITLE
Where should I catch UnauthorizedException?

### ISSUE THREAD

**Issue by 4unkur** [spatie/laravel-permission#908]
Could someone guide me where should I write this logic:  
https://github.com/spatie/laravel-permission#catching-role-and-permission-failures

I just want to redirect user to login page if not logged in  
and to index page with some message if user is logged in but has no permissions to do that action

**Comment by zcwilt** [comment]
Fortunately I just did this recently.

In ``app/Exceptions/Handler.php``,  I added this to the ``render`` method.

    if ($exception instanceof UnauthorizedException) {
         //  ...handle the exception here
        // e.g. return response()->view('errors.403', [], 403);
    }

Don't forget to add

    use Spatie\Permission\Exceptions\UnauthorizedException;

to the other use statements.

**Comment by 4unkur** [comment]
@zcwilt Thanks dude.

@drbyte are you that Chris Brown who is rapper? )

**Comment by drbyte** [comment]
Haha @4unkur I can spit a mean rhyme, but I'm not the same guy. :)
