### ISSUE TITLE
How to disable multi-guards functionality?

### ISSUE THREAD

**Issue by Rux77** [spatie/laravel-permission#910]
I want to use roles and permissions for both of my **guards** ( 'web' , 'api' ), I don't see whats the point behind **multi-guards** functionality!? which force me to duplicate the same roles and permissions for both of my guards ( 'web' , 'api' ).

Is there a way to disable **multi-guards** functionality?

**Comment by drbyte** [comment]
Not with v2.
However, with v1 of this package, there is no differentiation between guards. I use v1 in a few projects for this reason.
But keep in mind that v1 also ties directly with a User model, not polymorphically to multiple models.

Also, v3 aims to be guard-agnostic, but also retain the polymorphism that v2 supports. There's no ETA set yet for v3 release.

**Comment by jjoek** [comment]
I am using the latest version as of the time of this writing.

Basically I have a laravue project and now, it is nagging, since there are instances where I want to access the roles via the api guard and other instances via web guard since the app is not a full spa. 

I think we deserve an option to disable this functionality if need be.

**Comment by drbyte** [comment]
<img width="774" alt="Screen Shot 2019-03-25 at 7 34 12 PM" src="https://user-images.githubusercontent.com/404472/54960921-12df5d00-4f35-11e9-82b2-c8d5e6489750.png">

_Originally posted by @jjoek in https://github.com/spatie/laravel-permission/issues/910#issuecomment-476413935_
> I think we deserve an option to disable this functionality if need be.

"deserve"? Seriously?

As posted already above, v1 of this package has no guard differentiation. You can use it.
But if you're offering to pay for the many hours of coding work required to finish off the v3 for everyone to benefit, reach out to me or @freekmurze and we'll work out a sponsorship deal.
Or contribute a pull request containing the code, so we can share it for everyone.

**Comment by maxcelos** [comment]
A workaround is to override the `hasPermissionTo` method in your User model, forcing the `$guardName` to be whatever you want.

With this customization you can use same permission to authorize requests from api and web for example.

Not pretty but works.

```php
class User extends Authenticatable implements MustVerifyEmail
{
    use HasRoles;

    public function hasPermissionTo($permission, $guardName = null): bool
    {
        // This disables the multi-guard
        $guardName = 'api';
        ...
```
