### ISSUE TITLE
Blade directives failing on Laravel 5.7

### ISSUE THREAD

**Issue by yespbs** [spatie/laravel-permission#911]
I am not sure but it was working with 5.6 

```
@role('admin') 
....
@endrole
```

does nothing and prints as plain text

**Comment by drbyte** [comment]
I once had that happen on a project that had a package installed that had done something to interfere with registering of directives by the service provider. 
I don't recall now which package it was. However, you may wish to review all the ways in which your app is different from a fresh Laravel install, including which packages you've added.

**Comment by yespbs** [comment]
Thanks for the pointer

I have two other projects upgraded to 5.7 and did not see the issue. I will revisit all the packages.

**Comment by yespbs** [comment]
Package htmlmin/htmlmin was causing issue with blade optimization.

**Comment by drbyte** [comment]
> Package htmlmin/htmlmin was causing issue with blade optimization.

Thanks for posting the resolution!
