### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::syncRoles does not exist.

### ISSUE THREAD

**Issue by thomasbuckle-uk** [spatie/laravel-permission#912]
Getting this error when trying to use syncRoles()

Any help would be appreciated.

**Comment by muhamadrafli255** [comment]
> Getting this error when trying to use syncRoles()
> 
> Any help would be appreciated.

You can foreach before syncRole()

**Comment by muhamadrafli255** [comment]
> Getting this error when trying to use syncRoles()
> 
> Any help would be appreciated.

You can foreach before syncRole()

**Comment by muhamadrafli255** [comment]
> Getting this error when trying to use syncRoles()
> 
> Any help would be appreciated.

You can foreach before syncRoles()

Example code :

$users = User::where(‘id’, $request->id)->get();
foreach($users as $user)
{
	$user->syncRoles(‘admin’);
}
