### ISSUE TITLE
Role relation does not get updated after assigning role

### ISSUE THREAD

**Issue by deviouspk** [spatie/laravel-permission#914]
consider the following example:

```
public function testRoles()
    {
        $user = User::first();
        $this->assertFalse($user->hasRole('admin'));
        $user->assignRole('admin');
        $this->assertTrue($user->hasRole('admin'));
    }
```

The second assertion fails. I'm not sure if there's something wrong with the laravel internals or this package didn't go in depth yet. But atleast i fixed it for now by overriding and extending the hasRoles trait and adding

`unset($this->roles);`

to the end of the assignrole method.

What could be causing this?

**Comment by hulkur** [comment]
Will have PR ready in an hour.

**Comment by hulkur** [comment]
What is the use-case for needing that?

**Comment by hulkur** [comment]
with `fresh` you need to know which relations were loaded and load them again

**Comment by drbyte** [comment]
Yes, but in the scenario presented earlier, there were no other relations loaded, so `fresh` is sufficient. One could use `refresh()` if that met their needs more thoroughly.
