### ISSUE TITLE
Using middleware with additional condition

### ISSUE THREAD

**Issue by SPQRInc** [spatie/laravel-permission#915]
Hi there,

I am trying to allow access to a specific route only if the user's permission allows it; or if an other condition matches:

```
Route::group(['middleware' => ['role_or_permission:access page']], function () {
    //
});
```

This is clear - but I would really love to add a check, that allows to access the route, if `Auth::user()->id` matches `$user->id` (`user` comes from a parameter).

So only allow access, if a specific permission is set or if the user tries to access his own page.

Any idea how to solve that? :-)

**Comment by drbyte** [comment]
You could clone that role_or_permission middleware into your app namespace and add the check to it. Then register your custom middleware, with a new name, and use that new middleware in your route.
