### ISSUE TITLE
role_has_permissions not work

### ISSUE THREAD

**Issue by vahidalvandi** [spatie/laravel-permission#917]
in table **role_has_permissions** have permission id and role id . how i can check permission with role_has_permissions  , In the event that i don't fill table **model_has_permissions**

???

**Comment by drbyte** [comment]
`$role->permissions` is a standard BelongsToMany relationship, and therefore will give you all the permission (object records) associated with the given `$role`.
So, you could write your own gate rules to test a role-permission relationship independent of a model being associated.
But, this package doesn't provide any commands for doing that, so it will need to be done inside your own app code.
