### ISSUE TITLE
returning specific role users

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-permission#919]
I want to return all users with "Admin" role.
How can I get specific role users from controller?

**Comment by drbyte** [comment]
You can use the `role` scope provided with the package:
```php
$admins = User::role('Admin');
```

**Comment by robertnicjoo** [comment]
@drbyte hi, thanks for the answer it's working perfectly, as following this question: how can i except this role users from total users? is there a way to do so?

I have

```php
$users = User::withTrashed()->orderby('id', 'desc')->get(); //getting everyone including admins
$admins = User::role('Admin')->get();  //getting admins only
```

> What I want is now that I have admins separately , in `$users` getting all users except admins.

any idea?

**Comment by robertnicjoo** [comment]
Does this get second value? like we filter `admin` and `editors` from `users` both?

**Comment by drbyte** [comment]
The code I posted above will replace `$users` with the original values in `$users`, after removing any that were in `$admins`.

You can do the same for other roles or reasons. It's just regular Laravel Collections stuff.

**Comment by helloKeyur** [comment]
This is really working for me thank you for helping me @drbyte
