### ISSUE TITLE
getRoleNames() missing multiple guard parameter 

### ISSUE THREAD

**Issue by swerwajod** [spatie/laravel-permission#923]
getRoleNames is missing the guard_name parameter. 

It would also be useful to have Role ids too to help when Roles are related to other models.  
getRoleNames()  could work as it does currently for backward compatibility
and 
getRoleNames('key' => 'id', guard_name => 'team') would give a key-value pair collection of [id, RoleName]

also maybe add a getRoles() that returns all columns in the roles table for the given user and guard, then we could just pluck the id and name or other information.

**Comment by drbyte** [comment]
Hi @swerwajod 

Does your app need to be assigning and using specific roles "per guard", in a db-stored-dynamic manner?

ie: role "editor" has different responsibilities for the "team" guard than it does for the "office" guard, and where those editor-to-team and editor-to-office relationships need to be alterable by the end user and not coded into the app?

Or is the `guard` implementation at this level something that could be merely a "pass-thru" if this package didn't define specific roles per-guard?

I'm asking because your answer affects the response to your question :)
(And because almost every app I've encountered has no need to define roles/permissions "per guard" in a dynamic way like this package "forces" one to do.)

**Comment by swerwajod** [comment]
@drbyte 
Thank for responding. I'm using guards in two ways.  One is the intended way, with an auth guard for corporate employees, off-site employees, and sub-contract users.  So that all access is segmented by the user's authentication guard and sub-contractors never have access to the other segments.  With that, each guard has roles per guard in the DB. So the same named Role may exist for different guards with different functions.  but if role name is unique then I'll deal with it. However, I don't think what you asked about 'altered by end user' is needed. I plan that access for guards and roles would be coded. But I may misunderstand what that question is asking, sorry.

Secondly, Since guard designation is in the role table, they can be used as a label of roles types even if not truly using auth guards. Also the guards allow different types of roles to be attached to different models as well as attaching these other Roles to the user. I may be stretching the use a bit but this module does allow for other models to have roles.

So with the team guard, I'm able to create a list of teams (roles with a team name as the role) that are attached to a team model through the guard. I can also add the team/role to the user as in any other role.  So that was the main driver for asking about getRoleName() to have a gaurd_name parameter since roles were already identified with different guards. I can then get what roles a user has in the team guard to get a list of their teams and then produce any information for those team in the application including the roles in the team model.
Hope I explained what you were looking for. Thanks

**Comment by drbyte** [comment]
Okay, I think I understand your situation.

To get a collection of all roles with guard names, you could just access the Eloquent model directly: 
`Spatie\Permission\Models\Role::all()`

And as far as a particular User, given the following scenario: a user has been assigned 3 roles, associated with 2 different guards.
... running the following in `tinker` gives this output:
```
>>> $roles = $user->roles->pluck('guard_name', 'name')
=> Illuminate\Support\Collection {#2914
     all: [
       "writer" => "web",
       "admin" => "web",
       "apiRole" => "api",
     ],
   }
```

Hope that's helpful.

**Comment by swerwajod** [comment]
Yes, Talk about seeing the forest for the trees.  Was looking at all the methods and forgot about the capabilities of the model itself.
