### ISSUE TITLE
temporarily (only till the user is logged out) permissions?

### ISSUE THREAD

**Issue by dburucu** [spatie/laravel-permission#924]
how can I give temporarily (only till the user is logged out) permissions to the logged in user without saving it to the database?

**Comment by drbyte** [comment]
You could set it in a session variable, and define a Gate rule to check against that value.

Do you mind explaining the bigger picture of how/why this temporarily permission works in your case? Maybe there's an even better solution?

**Comment by dburucu** [comment]
yes I could, but than I have a second permission check function. 

It would be better, when I could use $auth()->user()->can('my-permission').

Explaination:
I have regular users. They have permissions, roles, .... Users logging in with login-form.
In addition I have other users -> surveyusers. This are in another table than users. Surveyusers are preponderantly independent from the rest of the system. They are changing very often. I dont want to insert the relations in the model_to_roles or model_to_permissions table. I want to assign a permission or role when they are logged in with an url with token.

It can be usefull to have the functions to add/remove a role or permission only for the session.

These can also be used for certain events in the system to add or remove certain rights or roles for the current user.

**Comment by drbyte** [comment]
Yes, that's exactly why you'd use a session variable.

1. AuthServiceProvider
Declare a `can` permission which checks both the session var and the user's normal permissions. Then in your app, always this this permission (not the one in the "permissions" db).
```
Gate::define('my-permission', function ($user) {
    return ($user->can('my-db-permission-name') || session('key-name') == 'truthy-value');
});
```
2. Login action
Set the session var:  `session('key-name', 'truthy-value');`

3. App logic
Always test against `my-permission` and not `my-db-permission-name`.

https://laravel.com/docs/5.7/session
