### ISSUE TITLE
List of all users with specific role

### ISSUE THREAD

**Issue by stijnvanouplines** [spatie/laravel-permission#93]
I just installed this packages, every thing works great. I only have one question. How can I get a list of all users with a specific role? As an example, I want to get a list of all users with the role of 'customer'.

Previous I had a column 'role' in the users table. Now I can't do like this anymore:
$users_list = User::where(‘role’, ‘customer’)
    ->lists(‘name’, 'id')
    ->all();

Thanks,
Stijn

**Comment by jryd** [comment]
You can use the relationships between user and role to retrieve this.

I've been doing it like this:

1. Retrieve the role; `$role= Role::findOrFail($id);` inside the controller and pass it to the view
2. In my view access it through `$role->users->username` where `username` can be whatever you want to retrieve.

In your case it seems like you are wanting to list them all, the following should do the trick, although I haven't tested it:

`$users_list= Role::findOrFail($id)->users->lists('name', 'id');`

**Comment by freekmurze** [comment]
What @jryd said. 👍

**Comment by stijnvanouplines** [comment]
@jryd Thanks, this worked for me:

```
$users_list= Role::findOrFail($role_id)->users()
    ->select(DB::raw("CONCAT(first_name,' ', last_name) AS full_name, id"))
    ->lists('full_name', 'id')
    ->all();
```
