### ISSUE TITLE
Assign limit permission to a numeric value in spatie permission pakige.

### ISSUE THREAD

**Issue by 3ubeen3** [spatie/laravel-permission#931]
Hi i'm using spatie permission pakige in my project.The requirement is that a permission has to assigned a role Like $limit=5,

But we have $permission = create(['name','permission_name']);

i want to add here limit =5.

**Comment by drbyte** [comment]
Permissions and Roles can be given names that are `string`s.

Your app can apply other logic around enforcing limits or other rules based on the name.

**Comment by 3ubeen3** [comment]
how ?i want to put limt = 5 in instead of string and i want to update this value.

**Comment by drbyte** [comment]
This package provide permission/role authorization based on comparing the string name of the requested permission against the string name of the permission in the database.
It does not provide any means for interpreting/converting it to some other dynamic value.

If your permission name is `limit = 5` then this package will allow you to test for that permission using various approaches, such as:
- `$user->can('limit = 5')`
- blade `@can('limit = 5')

You could create several permissions with different numbers on them, like:
```
limit = 1
limit = 2
limit = 5
limit = 10
```

And then your app could check using combined strings like:
- `$user->can('limit = ' . $val)
- blade `@if($user->can('limit = ' . $val))`
