### ISSUE TITLE
please update PermissionMiddleware 

### ISSUE THREAD

**Issue by faridfr** [spatie/laravel-permission#933]
Hi ,
I get this error when i set permission middleware in routes :

```json
"message": "Method Illuminate\\Database\\Query\\Builder::can does not exist.",
"exception": "BadMethodCallException",
"file": "/home/admin/domains/XXXXXX/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
"line": 2816,
```
I check the guard and auth but it isn't enough .
I solved it by replacing **can** with **hasPermissionTo** in **PermissionMiddleware** like this : 

```php
if (app('auth')->user()->hasPermissionTo($permission)) {
                return $next($request);
            }
```

**Comment by drbyte** [comment]
Sorry, I'm unable to recreate the problem you're reporting. 

Please provide code examples including your routes and defined gate rules and AuthProvider code.
