### ISSUE TITLE
Request for cache configurations

### ISSUE THREAD

**Issue by ShahinSorkh** [spatie/laravel-permission#934]
I need some config keys to opt out of caching entirely
Also some keys to choose the cache driver just for roles/permissions caching system

The problem is when using in a large scale ecosystem using external memcached/redis servers, besides possible conflicts, __the server__ flushes the cache before its timeout (2hrs) and it stops working until you notify the application __"Hey it's gone! What are you waiting for? Reload them from db!"__
I prefer to use file driver for permissions and memcached for other needs

**Comment by drbyte** [comment]
@fullstackfool do you have any thoughts on the best approach for both things requested here?

**Comment by drbyte** [comment]
A few observations:

1. Having your server flush the cache before its entries have properly expired sounds like a mismatch in strategies. I'm sure you have your reasons, but I don't see why that's an issue with this package.

2. I've pushed PR #940 which allows you to specify a separate cache driver by indicating which configured `cache.store` you want it to use. Please test whether it solves your problem.

Note that using `array` for the cache driver effectively expires the cache immediately after the current request.

**Comment by ShahinSorkh** [comment]
1. The issue with the package is that for some reasons (I did not dig into the package yet) it doesn't recognize cache has been flushed and returns 403 for all requests after some time when using memcached, it's ok with redis tho. I'm sure the session exists in both cases. Likely cache is flushing partially I will check this


2. That's what I need exactly! Thank you. I will test and let you know if it has any problem

**Comment by fullstackfool** [comment]
@ShahinSorkh Are you able to give any more information as to the environment/lead-up to this issue, so we can attempt to reproduce it?

Given your initial comment was several days ago, this won't be linked to the very recent caching changes - have you tried updating to the latest version and testing again? The caching strategy is now quite different, so you may get different results. If the same issues are occurring, it sounds more likely there's an issue with the caching environment you are using?

**Comment by fullstackfool** [comment]
@drbyte #940 looks like a nice and simple solution!

**Comment by drbyte** [comment]
v2.27.0 has been released, which contains the ability to specify a cache driver
