### ISSUE TITLE
Cannot seed data

### ISSUE THREAD

**Issue by jag-obviux** [spatie/laravel-permission#946]
I have tried all suggestions I can find.
set cache timeout to 0
Include 
        app()['cache']->forget('spatie.permission.cache');
clear cache from artisan command etc. 
But I keep getting: a 'xxxx' permission already exists for guard 'web'
I then tried: $this->app->make(\Spatie\Permission\PermissionRegistrar::class)->forgetCachedPermissions();
But there is no $this->app in the seed scop :-( 
Any suggestions?

**Comment by fullstackfool** [comment]
Can you try `app(Spatie\Permission\PermissionRegistrar::class)->forgetCachedPermissions()`?

**Comment by drbyte** [comment]
Ya, that or I've seen some prefer this format:
`app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();`
Apologies for the copy/paste error in the readme - it's been updated.

**Comment by jag-obviux** [comment]
Thanks. Works for me now
