### ISSUE TITLE
Give Multiple permissions to a role

### ISSUE THREAD

**Issue by peterquentin** [spatie/laravel-permission#95]
Can someone look at this little function before I make a pull request?

For me it's useful when I populate my database using seeders.

https://github.com/peterquentin/laravel-permission/commit/0f48477fd788dccec6684bebabc182292cd43a61

**Comment by freekmurze** [comment]
Granting multiple permission at once would be a nice features. How about making it work like this

```php
$user->givePermissionTo('permission-one'); // grant a single permission
$user->givePermissionTo(['permission-one', 'persion-two']) // granting multiple permission with an array
$user->givePermissionTo('permission-one', 'persion-two', ...) // granting multiple permission with arguments
```

To make that last example work we could leverage argument unpacking introduced in PHP5.6. The package currently support PHP5.5, but I'm willing to up the requirements to PHP 5.6, as PHP 5.5 is not maintained anymore.

If you create a PR for this (with tests) I'll probably accept it.

**Comment by autosplitz** [comment]
![code](https://user-images.githubusercontent.com/61923177/112390465-a8658100-8cf6-11eb-9f56-e94760fe6b4b.png)
