### ISSUE TITLE
How to use this package with laravel passport scopes?

### ISSUE THREAD

**Issue by amirpiri** [spatie/laravel-permission#951]
Hi, thanks for your great role base permission systems. I wonder why you didn't add laravel passport oauth2.0 support on this.

**Comment by freekmurze** [comment]
We've never had to use this package in combination with Passport. If this integration is easy and testable code, feel free to PR it to this package. 

If the integration is rather complicated, we don't want to maintain it ourselves. In that case, create your own package and we'll happily add a link to your package in our readme.

**Comment by Atiladanvi** [comment]
> Hi, thanks for your great role base permission systems. I wonder why you didn't add laravel passport oauth2.0 support on this.

I am waiting your PR :smile:
