### ISSUE TITLE
Method Illuminate\\Database\\Query\\Builder::assignRole does not exist

### ISSUE THREAD

**Issue by kameskarthi** [spatie/laravel-permission#952]
I have integrated this laravel-permission in jwt api

Here is my user model code
[<?php

namespace App;
use Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use  Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','remember_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Automatically creates hash for the user password.
     *
     * @param  string  $value
     * @return void
     */
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}](url)

Here is my signupcontroller page

[<?php

namespace App\Api\V1\Controllers;

use Config;
use App\User;
use Tymon\JWTAuth\JWTAuth;
use App\Http\Controllers\Controller;
use App\Api\V1\Requests\SignUpRequest;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class SignUpController extends Controller
{
    public function signUp(SignUpRequest $request, JWTAuth $JWTAuth)
    {
        $user = new User($request->all());
        if(!$user->save()) {
            throw new HttpException(500);
        }
         $user->assignRole($request->input('roles'));

        if(!Config::get('boilerplate.sign_up.release_token')) {
            return response()->json([
                'status' => 'ok'
            ], 201);
        }

        $token = $JWTAuth->fromUser($user);
        return response()->json([
            'status' => 'ok',
            'token' => $token
        ], 201);
    }
}
](url)

When i add a new user i got the following error message
[{
    "error": {
        "message": "Method Illuminate\\Database\\Query\\Builder::assignRole does not exist.",
        "status_code": 500
    }
}
](url)

**Comment by drbyte** [comment]
Your problem is in your application. I think your user object isn't being saved.
I set up a demo project similar to yours and it gave errors about the password not being savable. If for some reason your exception handling is intercepting and ignoring the error, then the assignRole would fail because you'd have a query object instead of a persisted user object.
