### ISSUE TITLE
I have an error exception of undefined index: name when Role::create function called?

### ISSUE THREAD

**Issue by rehanaslam328** [spatie/laravel-permission#957]
http://prntscr.com/lo4yl2

Click on this link and you will see the error of what I am talking about

**Comment by drbyte** [comment]
Yes, you must pass the associative array when creating Roles using an Eloquent call.

Example [from the README](https://github.com/spatie/laravel-permission#usage):
```php
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

$role = Role::create(['name' => 'writer']);
$permission = Permission::create(['name' => 'edit articles']);
```
