### ISSUE TITLE
Nova hitting cache 4 times per model when using a Policy

### ISSUE THREAD

**Issue by Livijn** [spatie/laravel-permission#958]
- Laravel Version: 5.7
- Nova Version: 1.1.9
- PHP Version: 7.2.12

### Description:
When I visit the *index* page of a resource that has a *Policy*, it hits the cache 4 times per model. Here is a Telescope result from a resource that has exactly 20 rows. Every time it is the same `spatie.permission.cache`. 

![Telescope](https://i.gyazo.com/6c9d673c103424e7747eb78b3b1ece14.png)

### Steps To Reproduce:
* Install Laravel + Nova + Telescope
* Install [Spatie's Permission](https://github.com/spatie/laravel-permission) and create a role + permission
* Create a normal `Model` and then a Nova `Resource` for that model
* Add a `Policy` to the `Model` (just return true on all methods)
* Add about 20 rows.
* Visit the `Resource`'s index page 
* Look at the request in Telescope - tada

### Updates:
Switching `CACHE_DRIVER` from `file` to `redis` changes the cache keys to this:

![Telescope](https://i.gyazo.com/4bb90a686c097c5c1a04d71d46b292a9.png)

**Comment by drbyte** [comment]
With `CACHE_DRIVER` set to `file` you can't benefit from `tagged` caching, but the `redis` driver supports tagging, where we are able to be more performant.
Hence the difference between the two drivers.

The actual policy hits are handled by Laravel's Gate.

**Comment by Livijn** [comment]
This is actually an issue from Nova’s side. Thanks.
