### ISSUE TITLE
Ability to sync multiple roles at once

### ISSUE THREAD

**Issue by nWidart** [spatie/laravel-permission#96]
Hello,

Currently I couldn't find a way to sync roles on a user. As it is now I had to work like this:

``` php
// Update method on the UserRepository
if ($user->roles->isEmpty() === false) {
    foreach ($user->roles as $role) {
        $user->removeRole($role);
    }
}
$user->assignRole(data_get($data, 'role', 'customer'));
```

Meaning I first had to remove the roles on the user, to then add the needed ones back.

Using a sync method, those lines can be replaced by:

``` php
$user->syncRoles([data_get($data, 'role', 'customer')]);
```

(Note I wrap in an array, b/c in my current use-case a user can only have one role, ie: not a multi select).

The code I added on the `User` model for this:

``` php
public function syncRoles(array $roles)
{
    $this->roles()->sync($this->getStoredRoleIds($roles));
}

protected function getStoredRoleIds($roles)
{
    $ids = [];
    foreach ($roles as $role) {
        $ids[] = $this->getRoleId($role);
    }
    return $ids;
}

private function getRoleId($role)
{
    if (is_string($role)) {
        return app(Role::class)->findByName($role)->id;
    }

    return $role->id;
}
```

Now, I'm guessing that foreach can be replaced by something like

``` php
return collect($roles)->each(function ($role) {
    return $this->getRoleId($role);
});
```

I haven't tested this though.

What are your thoughts on adding this functionality to the `HasRoles` trait ?

**Comment by freekmurze** [comment]
Hi Nicolas,

I'm ok with adding a `syncRoles` function.

I've I'm not mistaken the native sync method will already take both `id`'s and model.

```php
$this->roles()->sync($ids) // ok
$this->roles()->sync($arrayWIthRoleModels) // also ok
```

So the only thing that's not supported out of the box are an array with the names of permission names.

```php
$this->roles()->sync(['permission-one', 'permission-two']);
```

So the `syncRoles` function could do something like this

```php
public function syncRoles(array $roles)
{
     $roles = collect($roles)->map(
     ... // convert int / strings to roles models
     );

    $this->roles()->sync($roles);
}
```

If would be super nice if there also was a equivalent function `syncPermissions`.

And of course tests are mandatory 😄 

Thoughts?

**Comment by freekmurze** [comment]
I did have some time to implement it myself.

Added `syncRoles` and `syncPermissions` in version `1.5.0`.

**Comment by nWidart** [comment]
That's awesome, thanks! 😄
