### ISSUE TITLE
Check for already published migration doesn't work

### ISSUE THREAD

**Issue by bjuppa** [spatie/laravel-permission#960]
Hi
Running `php artisan vendor:publish --tag=migrations` publishes a new migration file from this package, with a new timestamp every time.

The [current if-statement](https://github.com/spatie/laravel-permission/blob/e4c3801008c2b4d1002b6b8c624a6a216d32f4f8/src/PermissionServiceProvider.php#L20
) around the migration publisher in the service provider doesn't have the desired effect.

It checks if the classname exists in the global namespace, but classes from the `database/migrations` directory are not autoloaded in a normal Laravel app (only seeds and factories).

I don't know what would be the best strategy to prevent this from happening...
Could one check the already published migration filenames instead of class existence?

**Comment by drbyte** [comment]
Hi @bjuppa ,
Would you explain your workflow, to help me understand why you're re-publishing migrations?
I just want to understand your use-case as we consider the right fix.

**Comment by bjuppa** [comment]
Sure @drbyte !

I have a situation where I've required `spatie/laravel-permission` in a Laravel app and I've published the migrations for the package once, run the migrations, and commit migrations to version control. Everything is fine at this point!

Later I require another package that also publishes its migrations under the tag `migrations` so I run `php artisan vendor:publish --tag=migrations` ...and that's when a second migration from laravel-permission is published in the app's migrations directory, along with the new package's migrations.

If I'm diligent at that point, I'll notice and just remove the new "duplicate" migration file, but if I'm not and I run `php artisan migrate` I get an error about tables already existing.

So the problem will never reach production, which is great, but it may be confusing that the flow differs from other publishing scenarios, like assets or views, where the filename is fixed, not containing a timestamp. One expects artisan's publish command to skip any files that already exists with a warning (and you can overwrite them with the `--force` flag if you really want to).

I guess the class-checking if-statement in the service provider was originally meant for avoiding these duplicates. I wonder if earlier versions of Laravel did load migration classes into the global namespace, perhaps at one time it was working as intended?

**Comment by drbyte** [comment]
@bjuppa I think I've got a working solution for this:
https://github.com/spatie/laravel-permission/pull/962/files

**Comment by bjuppa** [comment]
Impressive work @drbyte, very elegant!
