### ISSUE TITLE
removeRole function does nothing

### ISSUE THREAD

**Issue by mustorze** [spatie/laravel-permission#963]
Hello,
first of all i rly like this package and use in my intire projects.

After i've upgraded the package from version `2.23.0` to `2.28` the function removeRole happendly stops working.
i've already updated the `permissions.php` config file and run'it `composer dump` to renew the cache.

There something more can i do to fix ou try to fix it?

Thanks in advance

Henrique.

**Comment by drbyte** [comment]
I think you'll need to share your application code.

In addition to the package tests passing, I just tested it myself [with my basic demo app](https://github.com/drbyte/spatie-permissions-demo), and it works properly:
<img width="604" alt="screen shot 2018-12-03 at 10 44 16 am" src="https://user-images.githubusercontent.com/404472/49384238-99530300-f6e8-11e8-8a82-136cf62297c9.png">

**Comment by avblink** [comment]
I can confirm that $user->removeRole('admin') is not working.
The sql deletes by role name instead of role id.
```
delete from `model_has_roles` where `model_id` = '15' and `model_type` = 'App\Models\User' and `role_id` in ('admin')
```
where it should be

```
delete from `model_has_roles` where `model_id` = '15' and `model_type` = 'App\Models\User' and `role_id` in (1,2,3)
```

Unless documentation has a mistake. At the moment example tells to use role name, not id.

**Comment by Arkanius** [comment]
Had the same problem here. As @avblink said, looks like sometimes the query tries to remove by role name and not by role id

**Comment by waleedakhlaq** [comment]
You can use syncRole function instead of assignRole. syncRole will automatically delete the previous roles assigned to user and assigned the new ones. 

$user->syncRoles($roles)
