### ISSUE TITLE
Question: Set Default Role and Permission Values without seeding?

### ISSUE THREAD

**Issue by pmochine** [spatie/laravel-permission#964]
It would be cool to have default role and permission values, so one can refresh the migration without seeding the values.

One idea would be to insert the values in the migration file. You could set the default values in config and it would be read out in create_permission_tables.php

**Comment by drbyte** [comment]
Can you explain the workflow where you would want this?

It strikes me that when one is refreshing the migration that that's also the ideal time to use a seeder, so seeding makes good sense. But your idea comes from another line of thinking: would you share your use case?

**Comment by pmochine** [comment]
@drbyte I'm pretty sure my thinking is wrong :P However, when I'm doing phpunit testing, I'm refreshing the database with each test. Because I know that I have specific roles in my DB, I have an extra migration file that DB inserts the initial default role values.

**Comment by drbyte** [comment]
> I have an extra migration file that DB inserts the initial default role values.

That's an acceptable alternative to using a db seeder. 
Both approaches can be used, depending on your needs and your overall dev strategy.

I don't think there's any need to change this package for that.

A third approach you could use is to create your permissions in a specific test's `setUp()` method. You can see an example of that here: 
https://github.com/drbyte/spatie-permissions-demo/blob/master/tests/Feature/PermissionsDemoTest.php
(You could also put it in the setUp() of TestCase, to share with all test classes.)

**Comment by pmochine** [comment]
@drbyte thanks chris!
