### ISSUE TITLE
package in api?

### ISSUE THREAD

**Issue by shahzaibanwar009** [spatie/laravel-permission#965]
Thanks for this package.one question is how to use this package in apis?

**Comment by drbyte** [comment]
This package simply provides a means of doing Authorization checks to see if an action should be allowed.
Simply perform those checks in your code where needed.

**Comment by mobayen** [comment]
@drbyte is it possible? I mean does laravel-permission support passport?

**Comment by drbyte** [comment]
**Authentication** and **Authorization** are different things, but they interact with each other all the time in every app, everywhere.

**Authentication** methods include combinations of sessions, JWT, Passport/OAUTH, etc.

**Authorization** methods in Laravel are driven by Gate and Policy rules. This package provides data for the Gate layer, which you can leverage with your own policies, middleware, etc.

So, while I've not personally used it with Passport, I don't see why it would have any conflict.

You can use Passport for what Passport does, and use this package for what this package does. Your own application code can do the necessary bridging between functionalities.
