### ISSUE TITLE
Allow creating roles and permissions for multiple guards

### ISSUE THREAD

**Issue by scheMeZa** [spatie/laravel-permission#968]
Hello,

I'm seeding 113 permissions and 20 roles, currently I'm doing this through a foreach guard loop.

My suggestion is to maybe allow the following syntax?
```php
// Create a superadmin role for the admin users
$role = Role::create(['guard_name' => ['admin', 'web', 'api'], 'name' => 'superadmin']);

// Define a `publish articles` permission for the admin users belonging to the admin guard
$permission = Permission::create(['guard_name' => ['admin', 'web', 'api'], 'name' => 'publish articles']);

// Define a *different* `publish articles` permission for the regular users belonging to the web guard
$permission = Permission::create(['guard_name' => ['admin', 'web', 'api'], 'name' => 'publish articles']);
```

Refer to current documentation syntax:
```php
// Create a superadmin role for the admin users
$role = Role::create(['guard_name' => 'admin', 'name' => 'superadmin']);

// Define a `publish articles` permission for the admin users belonging to the admin guard
$permission = Permission::create(['guard_name' => 'admin', 'name' => 'publish articles']);

// Define a *different* `publish articles` permission for the regular users belonging to the web guard
$permission = Permission::create(['guard_name' => 'web', 'name' => 'publish articles']);
```

**Comment by drbyte** [comment]
Just to be clear, am I correct in observing that you are creating identical sets of roles and permissions for *every* guard?
And that if this package were to allow the guard factor to simply pass through to your app and allow the app take care of guard logic, that the roles/permissions would stand as sufficient on their own?

I find that the vast majority of apps are in exactly this situation, and therefore `v3` of this package will be dropping logic for intercepting and defining guard-specific Authorization activities, and allow the app to handle that part.

**Comment by scheMeZa** [comment]
Yes Sir,

I'm following principles of DDD - a manager via API or WEB should be able to do identical actions - just different mediums, thus is why I end up having to duplicate Roles and Permissions over guards.

**Comment by drbyte** [comment]
Great! I think you'll like the simplification of `v3` with guard-specific logic removed.
We have a few more things to sort out with it, so unfortunately it's not quite ready to go yet.

Thanks for sharing your suggestion. Fortunately it should become moot when v3 is ready.

**Comment by kylebarney** [comment]
It sounds like I need the guard handling logic coming in v3. What's the timeline for release? (Happy to help out if I can.)

**Comment by sscots** [comment]
+1

**Comment by MostafaAttia** [comment]
+1

**Comment by gautam-patadiya** [comment]
+1

**Comment by Tofandel** [comment]
Any news on this one?

**Comment by aralvi** [comment]
i want to create multiple permissions for one role with single command how could i?

**Comment by chris-skilltech** [comment]
Any idea what is happening with this one?

We've just upgraded to v5 and our API is breaking because the permissions are defined under the Web guard. I don't want to duplicate every permission because they are shared regardless of the user performing the action via the Web or the API.

Does anyone have a valid workaround? Can't believe this has been sitting here for 4 years.

**Comment by erikn69** [comment]
@chris-skilltech maybe with a workaround
```php
// overwrite on User model with 'web' as default $guardName
public function checkPermissionTo($permission, $guardName = 'web'): bool 
 { 
     try { 
         return $this->hasPermissionTo($permission, $guardName); 
     } catch (PermissionDoesNotExist $e) { 
         return false; 
     } 
 } 
```

**Comment by erikn69** [comment]
>Also setting `protected $guard_name = 'web';` propertie on User model could work
Read documentation, for other options

**Comment by chris-skilltech** [comment]
That looks to be working at the moment.
I've added comments to ensure that our other developers aren't confused because our API auth uses Passport.
