### ISSUE TITLE
 undefined hasRole()

### ISSUE THREAD

**Issue by raficopuntiando** [spatie/laravel-permission#969]
Hi,  I have a problem when I try to hidden div or pages using the function Role.
it is the message: Call to undefined method Illuminate\Auth\GenericUser::hasRole()

i did step by step the same as in the video but i has this error

how can i do?

**Comment by drbyte** [comment]
I don't know which video you're referring to, but perhaps it isn't guiding you correctly.

If you follow the [README](url
https://github.com/spatie/laravel-permission#usage) you'll see that you add the `hasRoles` trait to your model. In your case you've retrieved an instance of GenericUser, which does not have the trait applied.

**Comment by hgopi** [comment]
I had the same issue. I resolved this issue by changing the `driver` value from `database` to `eloquent` in the `auth.php` file. 

Refer:
https://laracasts.com/discuss/channels/laravel/authuser-returning-generic-user#best-reply-593380
