### ISSUE TITLE
Route Middleware Error

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-permission#97]
I'm using the route middleware and encountered an issue: if a route is protected and a user is not logged in I receive the following error.

`Call to a member function hasRole() on null`

The solution was to add an `Auth::guest()` check in `RoleMiddleware.php`

```
<?php

namespace App\Http\Middleware;

use Auth;
use Closure;

class RoleMiddleware
{
    public function handle($request, Closure $next, $role)
    {
        if (Auth::guest()) {
            return redirect('/login');
        }

        if (!$request->user()->hasRole($role)) {
            abort(403, 'Not Authorized');
        }

        return $next($request);
    }
}
```

**Comment by freekmurze** [comment]
You're right, I'll fix the example.
