### ISSUE TITLE
These credentials do not match

### ISSUE THREAD

**Issue by rehanaslam328** [spatie/laravel-permission#972]
When i assign permission directly to user then when i am going to login with that credentials , these credentials do not match error occurs.....Before assigning permission to user , it logins successfully

**Comment by drbyte** [comment]
This package doesn't touch login credentials.
I think your problem is somewhere else in your app.

If you believe there is a problem with this package, please post all your code so I can set up the same situation here to recreate the problem.

**Comment by rehanaslam328** [comment]
![auth](https://user-images.githubusercontent.com/36721148/49699116-0259df80-fbef-11e8-8f62-bd15f85003d8.png)

I have used hasrole in AuthenticatesUsers trait

**Comment by rehanaslam328** [comment]
> This package doesn't touch login credentials.
> I think your problem is somewhere else in your app.
> 
> If you believe there is a problem with this package, please post all your code so I can set up the same situation here to recreate the problem.

![auth](https://user-images.githubusercontent.com/36721148/49699144-68466700-fbef-11e8-958d-27171dc075ee.png)

I have used Hasrole in AuthenticatesUsers trait and user which is going to login are redirected to different direction on the basis of role

**Comment by drbyte** [comment]
Please provide detailed instructions on how to recreate this problem on a fresh new Laravel install.
