### ISSUE TITLE
RoleMiddleware checks for default guard user only 

### ISSUE THREAD

**Issue by MohamedQabbani** [spatie/laravel-permission#978]
Hello 

in the RoleMiddleware file it checks for the Auth::guest(), since I'm using different guard for my backend dashboard it always return true even when i'm logged in with different guard. 

```php
public function handle($request, Closure $next, $role)
    {
        if (Auth::guest()) {
            throw UnauthorizedException::notLoggedIn();
        }

        $roles = is_array($role)
            ? $role
            : explode('|', $role);

        if (! Auth::user()->hasAnyRole($roles)) {
            throw UnauthorizedException::forRoles($roles);
        }

        return $next($request);
    }
```

Before I submit my PR, would this change be acceptable? 

```php

public function handle($request, Closure $next, $role, $guard = null)
    {
        if (is_null($guard))
        {
            $guard = config('auth.defaults.guard');
        }
        if (Auth::guard($guard)->guest()) {
            throw UnauthorizedException::notLoggedIn();
        }

        $roles = is_array($role)
            ? $role
            : explode('|', $role);

        if (! Auth::guard($guard)->user()->hasAnyRole($roles)) {
            throw UnauthorizedException::forRoles($roles);
        }

        return $next($request);
    }

```

Thanks!

**Comment by drbyte** [comment]
Hey, thanks for this.

I like your suggestion.

I think we should also apply it to the other middleware, since they have the same limitation.
Some of them use `app('auth')->` instead of the `Auth::` facade syntax, but the change is basically the same.

But we should also add some tests for this. Are you comfortable writing a test that demonstrates the need for this change?

**Comment by helmut** [comment]
Happy to submit a pull request for this if you are still interested? I also came across this where having multiple logged in users from different guards gave unexpected access.

**Comment by drbyte** [comment]
Certainly!
