### ISSUE TITLE
Undefined variable: class in vendor/spatie/laravel-permission/src/Guard.php

### ISSUE THREAD

**Issue by ajay-webpatriot** [spatie/laravel-permission#980]
Hi,

After folowwing all the installation steps I am getting error of "Undefined class". see attached image describing error. Please let me know how to resolve this.

![capture](https://user-images.githubusercontent.com/33543828/50210417-12ff1800-039c-11e9-822a-f038f0a231e1.PNG)

Thanks.

**Comment by ajay-webpatriot** [comment]
My Bad, I have modified one database column in local and fotgot to do the same on server. which was causing this error. So applied that db change and it worked.

**Comment by DiogoDuart3** [comment]
how did u fix it?

**Comment by santerref** [comment]
> how did u fix it?

If you have an existing Role model and table, make sure that the `guard_name` column exists and is not empty.
