### ISSUE TITLE
Incompatible with Swoole

### ISSUE THREAD

**Issue by codercms** [spatie/laravel-permission#981]
Laravel version: 5.7.19
Package version: 2.29.0
PHP version: 7.2.8
Swoole implementation for Laravel used - https://github.com/swooletw/laravel-swoole (v 2.5.0)

Part of swoole config:
```php
/*
|--------------------------------------------------------------------------
| Providers here will be registered on every request.
|--------------------------------------------------------------------------
*/
'providers' => [
    Illuminate\Pagination\PaginationServiceProvider::class,
    Illuminate\Auth\AuthServiceProvider::class,
    App\Providers\AuthServiceProvider::class,
    Spatie\Permission\PermissionServiceProvider::class,
    Laravel\Passport\PassportServiceProvider::class
],
```

Last compatible version of this package with swoole is 2.25.0. 2.26.0 and higher doesn't work as expected.
This issue is related to following code in PermissionRegistar class:
```php
    /**
     * Register the permission check method on the gate.
     *
     * @return bool
     */
    public function registerPermissions(): bool
    {
       // added by myself
        \Log::info('Register permissions call');

        $this->gate->before(function (Authorizable $user, string $ability) {
            // added by myself
            \Log::info('Gate before call', ['user' => $user, 'ability' => $ability]);

            try {
                if (method_exists($user, 'hasPermissionTo')) {
                    return $user->hasPermissionTo($ability) ?: null;
                }
            } catch (PermissionDoesNotExist $e) {
            }
        });

        return true;
    }
```

Gate's before callback just isn't called as expected, and it makes all permissions checks to fail.
I fixed this issue by adding the following code to the App/Providers/AuthServiceProvider class::
```php
use Illuminate\Contracts\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Access\Gate;
use Spatie\Permission\Exceptions\PermissionDoesNotExist;

//....
// register spatie permissions package
$this->app[Gate::class]->before(function (Authorizable $user, string $ability) {
    try {
        if (method_exists($user, 'hasPermissionTo')) {
            return $user->hasPermissionTo($ability) ?: null;
        }
    } catch (PermissionDoesNotExist $e) {
    }
});
```
Can this issue be solved at the package level?

**Comment by drbyte** [comment]
Your post suggests that the `Gate` is incorrectly resolved, and therefore must be manually retrieved from the Container, and that this is a new problem introduced in 2.26.0

However, the Gate has been being resolved as a dependency injection since v1 of this package, and the `gate->before` call has been present since 2.0.0.

If 2.25.0 works but 2.26.0 doesn't, then it's more likely that you've got something conflicting at the cache layer, not with the Gate resolution.

Swoole support is not a priority for this package; however, if you want to submit a PR with appropriate compatibility fixes, including passing tests, we will consider it for inclusion.

**Comment by Beshelmek** [comment]
Since Swoole and Roadrunner is gaining popularity. I would be glad if this were corrected at the package level. Thx @codercms :)

**Comment by drbyte** [comment]
Can you explain why Swoole isn't handling normal dependency injection?

**Comment by codercms** [comment]
@drbyte it's not the correct dependency injection for long-live app.
Because PermissionRegistar is registered as a singleton, and it uses the "Gate" instance.
But for Laravel which is running under Swoole (or another tool that gives ability to use long-live approach) - AuthProvider (and some other things) should be re-initialized on each request, otherwise user data will be shared across all requests. So, PermissionRegistar->registerPermissions also should be re-initialized (re-called) with new "Gate" instance.

Here is some information about using Laravel under Swoole - https://github.com/swooletw/laravel-swoole/wiki/2.-Swoole-Structure

**Comment by drbyte** [comment]
Thanks @codercms

**Comment by drbyte** [comment]
@codercms Thoughts on this: https://github.com/spatie/laravel-permission/pull/1310 ?

**Comment by codercms** [comment]
@drbyte just tested this patch with swoole and I can confirm it works

**Comment by drbyte** [comment]
Thanks
