### ISSUE TITLE
How to get user roles with query builder?

### ISSUE THREAD

**Issue by jeraldpunx** [spatie/laravel-permission#985]
I am still trying to figure out how to do this on laravel query builder cause I am using it on datatables, and only like this command I can do.
for example:
`$users = User::select(['id', 'name', 'email', 'phone', 'created_at']);` 

How to get the roles?

Am I doing it right?

```
$users = User::join('model_has_roles', 'users.id', '=', 'model_has_roles.model_id')
                        ->join('roles', 'model_has_roles.role_id', '=', 'roles.id')
                        ->where('model_type', '=', 'App\\User');

return $users->get();
```

I am using this package [datatables.yajrabox](https://datatables.yajrabox.com/eloquent/basic) to implement, and most of the tutorial implementation need `User::select` but when I try `User::all()` it's not working though.

Really having hard time how to implement this. I just want to display it like this 
*Temporary Role Column*
![image](https://user-images.githubusercontent.com/5249781/50571538-2ec8dc00-0de8-11e9-8467-89452f3db10b.png)

This is my current implementation on yajrabox datatable package, all I want is how to implement the user roles, just really need help. 
![image](https://user-images.githubusercontent.com/5249781/50571615-dc88ba80-0de9-11e9-800b-6f9a616bcf09.png)

**Comment by jeraldpunx** [comment]
nevermind, figure it out
```
public function getUsers()
    {
        $users = User::select(['id', 'name', 'email', 'phone', 'created_at'])->with('roles');

        return Datatables::of($users)
            ->editColumn('created_at', function ($user) {
                return $user->created_at->format('Y/m/d');
            })
            ->filterColumn('created_at', function ($query, $keyword) {
                $query->whereRaw("DATE_FORMAT(created_at,'%Y/%m/%d') like ?", ["%$keyword%"]);
            })
            ->addColumn('role', function ($user) {
                return '<a class="btn btn-primary" href="#">'. ucfirst($user->roles->first()->name) .'</a>';
            })
            ->addColumn('action', function ($user) {
                return '<a href="'.route('admin.users.edit', $user->id).'" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i> Edit</a>
                <a href="'.route('admin.users.destroy', $user->id).'" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i> Delete</a>';
            })
            ->editColumn('id', 'ID: {{$id}}')
            ->make(true);
    }
```

**Comment by drbyte** [comment]
Yes, simply add the Eloquent relation to your query:
`User::all()` becomes `User::with('roles')->all()`
`User::select([])` becomes `User::select([])->with('roles')`

**Comment by jeraldpunx** [comment]
does `$user->assignRole($request->role);` role remove recent role and overwrite it?

for example: I have `admin` then I choose to `member`, and when I execute `$user->assignRole("role_name");`, does admin removed and changed to member right?

**Comment by jeraldpunx** [comment]
Thanks this is what I did, 
`$user->roles()->sync($role_id);`

**Comment by TheGlitch1** [comment]
User::with('roles')->all() this is actually working but what if we want to retrieve something more, lets say departments many to many , 
will thi swork if we do User::with('roles','departements)->all() ?'

**Comment by noumanbhai** [comment]
Nice
