### ISSUE TITLE
InvalidArgumentException in src/Composer/Command/InitCommand.php

### ISSUE THREAD

**Issue by ycancc** [spatie/laravel-permission#986]
[InvalidArgumentException]
  Could not find a matching version of package spatie/laravel-permission. Check the package spelling, your version constraint and that the package is available in a stability which
  matches your minimum-stability (stable).

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:740
 Composer\Command\InitCommand->findBestVersionAndNameForPackage() at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:394
 Composer\Command\InitCommand->determineRequirements() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:122
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:254
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:103
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:56
 require() at /usr/local/bin/composer:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by drbyte** [comment]
This package is registered as stable, so it seems your problem is something related to either the composer command you entered, or other limitations by other packages already in your app.

The correct installation instructions are listed in the README.

**Comment by ycancc** [comment]
Seems to be in conflict with some packages? I tried to modify me command, but it all failed.

> This package is registered as stable, so it seems your problem is something related to either the composer command you entered, or other limitations by other packages already in your app.
> 
> The correct installation instructions are listed in the README.

Seems to be in conflict with some packages? I tried to modify me command, but it all failed.

**Comment by drbyte** [comment]
Composer checks your existing app's requirements before adding another package, and if the new package isn't compatible with all the requirements your existing app's composer.json and your existing packages' composer.json rule dictate, then it won't install the new package.

Normally composer doesn't throw a bunch of exceptions like you're reporting, so either something's wrong with your composer or php setup, or your machine's filesystem permissions, or your app has something in its composer.json which is making composer very confused.

Installation of this spatie package is incredibly simple. Here's how to create a new laravel app and add this package to it: 
```php
laravel new myApp
cd myApp
composer require spatie/laravel-permission
php artisan vendor:publish

php artisan make:auth
```
And then manually
- add HasRoles trait to User.php
- add middlewares to Kernel.php

That's it.

If that's failing, then you'll need to fix your composer or php or permissions or app.
