### ISSUE TITLE
how to retrieve users with roles information included?, not the opposite

### ISSUE THREAD

**Issue by hackerunet** [spatie/laravel-permission#988]
Hello, I'm trying to retrieve the users list with all role information included inside the User model results, how can I get NOT THE USERS WITH CERTAIN ROLE but ALL USERS WITH ITS ROLE INFORMATION INCLUDED.
I want to be very clear about this, I need to include the role information in as part of the user model so I can do User::with('roles')->get() this is for admin only to be able to view the role of each user in the system.
thanks.

**Comment by hackerunet** [comment]
already found the answer, User::with('roles')->get();

**Comment by Glu-TTM** [comment]
thanks i had the same  isse

**Comment by laravel-devs-crescode** [comment]
for example if I wanted to get the 'name' of the role only how do I do that?
