### ISSUE TITLE
Is there a way to expose a similar API to the front-end ?

### ISSUE THREAD

**Issue by TamkeenLMS** [spatie/laravel-permission#989]
My app relies heavily on Angular JS for the front-end, and I am using Laravel Permissions on the backend. Now I want a way to use functions like can(), hasRole(), ... etc in the front end, is there an existing library that goes with Laravel Permissions, or should I write my own implementation ?

**Comment by drbyte** [comment]
Others may have some specific recommendations, but I'll just point out a related post from which you might find some ideas or inspiration: 
https://github.com/spatie/laravel-permission/issues/839
