### ISSUE TITLE
Can't check two specific roles

### ISSUE THREAD

**Issue by ramzan15596** [spatie/laravel-permission#990]
I tried searching and thinking of a solution but I couldn't come up with one...
I have an application where writer can only write post and editor can only edit post. 
For this i check for a specific role 
`@role('writer')
    I am a writer!
@endrole`
But i have a third user admin and admin can write and edit post for this i have done this
`@role('writer|admin')
    I am a writer!
@endrole` 
but this didn't work. I have tried other options too
`@hasanyrole('writer|admin')

@endhasanyrole`
But Did not work

Thanks for this amazing package and for possible feedback!

**Comment by drbyte** [comment]
For checking multiple roles in blade, the `@hasanyrole` directive does it.

```blade
@hasanyrole('writer|admin')
    I am either a writer or an admin or both!
@else
    I have none of these roles...
@endhasanyrole
```

**Comment by ramzan15596** [comment]
I Have tried this but this is not working. But when i try with this
`@can('writer|admin')
    Permission
@else
    I have none of these permission...
@endcan`
Its Works

**Comment by drbyte** [comment]
@can checks permissions, not roles.
So, if @can is working, then in your app you have created permissions instead of roles.

**Comment by ramzan15596** [comment]
ok thank u

**Comment by ramzan15596** [comment]
i have another issue.  Gives exception while using 
`Route::get('/orders/create', 'OrderController@create')->middleware('role:manager');`
and this error comes 
Class Spatie\Permission\Middlewares\RoleMiddleware does not exist

**Comment by drbyte** [comment]
> i have another issue. Gives exception while using
> `Route::get('/orders/create', 'OrderController@create')->middleware('role:manager');`
> and this error comes
> Class Spatie\Permission\Middlewares\RoleMiddleware does not exist

Did you forget the beginning `\` in front of `\Spatie\Permission\Middlewares\RoleMiddleware::class,` when registering the middleware in your kernel?

**Comment by drbyte** [comment]
> I have slash in the beginning of `\Spatie\Permission\Middlewares\RoleMiddleware::class,` but still getting this error

Then I guess you're not using v2 of this package. 
Note that v1 doesn't contain the middleware, but if you read the v1 readme it explains how to create it for yourself within your app and to register it.

**Comment by ramzan15596** [comment]
I Installed the spatie permission as it is in documentation. but how can i get v2 of this package.

**Comment by drbyte** [comment]
Currently when you run `composer require spatie/laravel-permission` it will give you v2.
You can confirm this by looking in the `require` section of your `composer.json`. It should say something like:
`        "spatie/laravel-permission": "^2.29.0",`

**Comment by ramzan15596** [comment]
Yes i have an old version  `"spatie/laravel-permission": "^1.17",` but when i run this command `composer require spatie/laravel-permission` to upgrade to be in the stable version. it can not upgrade. This old version remain the same.

**Comment by drbyte** [comment]
Leave it as v1. 
Look at the v1 README and create your own middleware for it using the code provided:
https://github.com/spatie/laravel-permission/tree/v1#using-a-middleware

(Upgrading to v2 requires rebuilding all your role/permission data. There's a script to help with that in the v2 readme. But treat upgrading as a separate project. It may not even be necessary. But if you're posting here for help, always mention you're using v1.)

**Comment by ramzan15596** [comment]
Thank u soo much chris. It works

**Comment by ramzan15596** [comment]
but i can't check two specific roles in web.php
`Route::group(['middleware' => ['role:manager|super-admin,manager']], function () {`
when i try this with single role, without pipe
`Route::group(['middleware' => ['role:manager,manager']], function () {`
I works with single role.

This is my db roles and permissions which i have created
Users table
![git1](https://user-images.githubusercontent.com/20531882/50849584-4e05c300-132c-11e9-83dd-664e8f4afe8d.PNG)

roles table
![git2](https://user-images.githubusercontent.com/20531882/50849601-5e1da280-132c-11e9-8edc-d9d2bf404cac.PNG)

permission table
![git3](https://user-images.githubusercontent.com/20531882/50849627-6c6bbe80-132c-11e9-93fd-40d9b6f850ae.PNG)

role_has_permissions table
![git4](https://user-images.githubusercontent.com/20531882/50849684-83aaac00-132c-11e9-92e8-059bed4e9e72.PNG)

user_has_permissions table
![git5](https://user-images.githubusercontent.com/20531882/50849740-afc62d00-132c-11e9-8b1e-b0a50f9c987c.PNG)

user_has_roles table
![git6](https://user-images.githubusercontent.com/20531882/50849765-c7051a80-132c-11e9-8b75-fb9ca2f5b15d.PNG)

Thank u

**Comment by ramzan15596** [comment]
I put this code in my RoleMiddleware.php 
`$roles = is_array($role) ? $role : explode('|', $role);
        if (! $request->user()->hasAnyRole($roles)) {
            abort(403);
        }`
but still getting the same error that i can't check two specific roles in web.php

**Comment by rajucs** [comment]
> For checking multiple roles in blade, the `@hasanyrole` directive does it.
> 
> ```
> @hasanyrole('writer|admin')
>     I am either a writer or an admin or both!
> @else
>     I have none of these roles...
> @endhasanyrole
> ```

THis worked for me.
thanks
as their doc @role('super admin','admin')
not working
