### ISSUE TITLE
Why use gate->before and not gate->define? in permission registrar

### ISSUE THREAD

**Issue by kamov** [spatie/laravel-permission#993]
I would like to know why it's used gate->before and not gate->define to define permissions in permission registrar class.

The result is the same ? 

Thanks

**Comment by drbyte** [comment]
#480

**Comment by kamov** [comment]
I see someone are using controller callAction() by overriding it like:


```
public function callAction($method, $parameters)
    {
        if( $ability = $this->getAbility($method) ) {
            $this->authorize($ability);
        }

        return parent::callAction($method, $parameters);
    }
```

What do you think to define here the permissions?

**Comment by drbyte** [comment]
> But this way seem that have other issue in performance, see #804

Yes. But you'll see there that making that change breaks all the tests.

> I see someone are using controller callAction() by overriding it like:
> What do you think to define here the permissions?

Doesn't `callAction()` have to be registered in the controller itself? That feels like the wrong direction for a package to go.

**Comment by kamov** [comment]
> Doesn't callAction() have to be registered in the controller itself? That feels like the wrong direction for a package to go.

Yes right... But you could create a Trait that can be added to a BaseController, that then other extend or add to each controllers.. Not sure if this is acceptable..

**Comment by drbyte** [comment]
Yes that could be done. 
But I don't think that's a good solution for this package. And I don't think it's the ideal solution to the mentioned problem.
