### ISSUE TITLE
Two roles classes and two permission classes for 2 models

### ISSUE THREAD

**Issue by bastien-phi** [spatie/laravel-permission#995]
In context of multi-tenant application, I have 2 models :
- Admin, which are stored in system database, authenticated by admin-guard
- User, which are stored in tenant specific database, authenticated by user-guard

These 2 models need to have Roles and Permissions, let's says AdminRole, AdminPermission, UserRole and UserPermission.

AdminRole and AdminPermission are stored in system database and UserRole and UserPermission in tenant database.

Adding roles and permissions to an admin or to a user is not a problem, just overriding `roles()`, `permissions()`, `getRoleClass()` and `getPermissionClass()` in Admin and User. 

 The problem is, when I want to run `$user->hasPermissionTo('do something')`, the UserPermission and UserRole classes are not used. Indeed, `PermissionRegistrar` uses the permission class and role class defined in config file (and, obviously, it can't be defined with both AdminRole and UserRole at the same time...)

How can I do to use different models of roles and permissions ? Do I have to completely rewrite `PermissionRegistrar` to fit my needs and register it in Laravel service container ? Is there another way ? Did I start wrong  when I overrode the methods ?

spatie/laravel-permission 2.29.0

**Comment by mrajabtech** [comment]
I'm using https://laravel-tenancy.com and having the same issue. I even tried setting the config permission and role values runtime but no luck

`config(['permission.models.role' => This\Is\Second\Role::class]);`

@bastien-phi did you find a way to fix this?

**Comment by azeos** [comment]
I'm facing the same problem with the same package.

I created a middlware where I set the config with my own models. But `PermissionRegistar` is called before the middleware:

```php
config([
    'permission.models.permission' => Permission::class,
    'permission.models.role'       => Role::class,
]);
```

Also tried to override the config from the [tenant folder](https://laravel-tenancy.com/docs/hyn/5.3/structure#config), but again, `PermissionRegistar` is called before the override happens.

I can only think in 2 possible solutions:

- Create a ServiceProvider that runs before `PermissionServiceProvider` and change the config there. But I change the config conditionally according to the route, and I'm not sure if I can access route params within a Service Provider.
- Just use one model and specify the DB connection within the `__construct()` some how.

Did you find any solution?

**Comment by bastien-phi** [comment]
I found a solution but it is not a good one.

I override a lot of the package (`PermissionRegistrar`, `PermissionServiceProvider`, `HasRoles`, ...) and do not use `permission.models` configs.

In a few words : 
- override `PermissionRegistrar` to tweak `getPermissions` and `forgetCachedPermissions`
- override `PermissionServiceProvider` (and remove auto-registration of genuine `PermissionServiceProvider`) to swap `PermissionRegistrar` to yours
- in your `CustomPermission` class, override `getPermissions` with :
```php
protected static function getPermissions($params = null): \Illuminate\Support\Collection
    {
        return app(PermissionRegistrar::class)->getPermissions(array_merge($params, ['class' => static::class]));
    }
```
or something like that. The idea is to pass an extra parameter to the permission registrar to let it know which class it has to fetch.

There will be other methods to override (but honestly, I can't remember which ones...)

Not sure this is the best way to do this. (I just cried when I updated from 2.30 to 2.36...)

It would imply a lot of changes to support this feature natively...

**Comment by drbyte** [comment]
The laravel-tenancy documentation specifically outlines how to make permissions available separately for all tenants:
https://laravel-tenancy.com/docs/hyn/5.4/spatie-laravel-permission

Simply override the Role and Permission models, inserting the UsesTenantConnection trait in both. And move the migration to the tenant subdir so that it runs for each tenant's database during provisioning.

**Comment by springleng** [comment]
> The laravel-tenancy documentation specifically outlines how to make permissions available separately for all tenants:
> https://laravel-tenancy.com/docs/hyn/5.4/spatie-laravel-permission
> 
> Simply override the Role and Permission models, inserting the UsesTenantConnection trait in both. And move the migration to the tenant subdir so that it runs for each tenant's database during provisioning.


Hi,  laravel-tenancy documentation can't solve this problem.

```php
    protected static function getPermissions(array $params = []): Collection
    {
        return app(PermissionRegistrar::class)->getPermissions($params);
    }
```

```php
    public function getPermissions(array $params = []): Collection
    {
        if ($this->permissions === null) {
            $this->permissions = $this->cache->remember(self::$cacheKey, self::$cacheExpirationTime, function () {
                return $this->getPermissionClass()
                    ->with('roles')
                    ->get();
            });
        }

        $permissions = clone $this->permissions;

        foreach ($params as $attr => $value) {
            $permissions = $permissions->where($attr, $value);
        }

        return $permissions;
    }
```

```php
$this->getPermissionClass()->with('roles')->get();
```

By the above method, get PermissionClass is always config('permission.models.permission').

So, UsesTenantConnection unused in two model Permission.

**Comment by drbyte** [comment]
Closed by merge of #1142

**Comment by drbyte** [comment]
This is now supported in v2.38.0

**Comment by syedhassan25** [comment]
hello hi guys laravel spatie package role base permission is very owsum but i am using in my project to different laravel projects
using database in both project single database but its not working problem is i am assign permission to user in first project its working fine ... but its user using in second project permissions not working... i see problem is ... please tell me what we do i am stuck in my both project have you any idea pleaase suggest me.
problem conclusion

assign permission to user first project is woking in same project...
but this user is not wrokign in second prject... but if you can assign user to permisssion in second he is working fine in second project but dosent work in first project please help me and sorry for poor englihs

NOte: please tell me is it possible single database using in laravel multiple project with laravel spatie role and permission
