### ISSUE TITLE
getAllPermissions() return error

### ISSUE THREAD

**Issue by marcelo2605** [spatie/laravel-permission#997]
Hey guys, I'm getting an error with this method on Laravel version 5.7:  `Trying to get property 'permissions' of non-object`

Here is my code on my controller:

```
$users = User::select('id', 'name', 'email')->get();

foreach ($users as $user) {
    $user->roles = $user->getRoleNames();
    $user->permissions = $user->getAllPermissions();
}
```

**Comment by drbyte** [comment]
This package requires that you add the `HasRoles` trait to your `User` model. This trait then automatically also adds the `HasPermissions` trait, which in turn adds the `permissions` property.

Therefore if you're getting `Trying to get property 'permissions' of non-object` then it would appear that you've got something interfering with this package. Perhaps a different permissions package? Perhaps your User model is not directly extending Laravel's Eloquent model? Or has other traits whose methods are interfering with this package's methods and properties?

**Comment by marcelo2605** [comment]
Hey @drbyte, I'm trying to find out the error. I can confirm that I added `use HasRoles;` on my User.php as explained on README file. And my Laravel installation is almost fresh. This is the only pckage I added.

**Comment by drbyte** [comment]
I guess something's wrong in your app.

I just created a demo app for you, which gives no errors for `getAllPermissions()`: 
https://github.com/drbyte/permtesting-marcelo-2605
You can see all the steps to create the demo, both in the README and in the commit history.

I suggest comparing it against the code in your own app to see what's different.

**Comment by marcelo2605** [comment]
Fixed! It was a silly error. I was trying to store all permissions inside a `permissions` key. Like that:

```
$users = User::select('id', 'name', 'email')->get();

foreach ($users as $user) {
    $user->roles = $user->getRoleNames();
    $user->permissions = $user->getAllPermissions();
}
```

Just change the key to another string and the problem is fixed. Thanks for the great support ;-)

**Comment by drbyte** [comment]
NOTE: since $user->roles and $user->permissions are both ALREADY present because of the trait, you shouldn't be re-assigning them. What you're doing is redundant.

**Comment by marcelo2605** [comment]
Nice! I figure out this few minutes ago.
