### ISSUE TITLE
ErrorException when Using @can in blade, Spatie Roles and Permissions

### ISSUE THREAD

**Issue by sokeno** [spatie/laravel-permission#998]
I get the following error when I used @can directive to check for permission

ErrorException (E_ERROR) SQLSTATE[HY093]: Invalid parameter number (SQL: select roles.*, employee_role.employee_id as pivot_employee_id, employee_role.role_id as pivot_role_id from roles inner join employee_role on roles.id = employee_role.role_id where employee_role.employee_id = 1 and name = ? limit 1) (View: /opt/lampp/htdocs/esurance/esurance-v2-laravel/resources/views/company/roles/roles.blade.php)

Im using Spatie roles and permissions package with multiple guards

**Comment by drbyte** [comment]
Hi,
More context is necessary to investigate.

Please explain how to re-create this situation, starting from a fresh new Laravel install. Please list all packages added, and show the code needed to create your custom models and guards in order to trigger this same problem.

**Comment by sokeno** [comment]
Steps to recreate
1.Did a fresh laravel install, configured the guards
'guards' => [
            'employee' => [
            'driver' => 'session',
            'provider' => 'employees',
        ],

    ]
2.configured model 
namespace App\Company;

//use Eloquent as Model;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;


class Employee extends Authenticatable
{
    use HasRoles;
    use SoftDeletes;
    use Notifiable;
    

    public $table = 'employees';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];
    protected $guard_name = 'employee';

3.After creating employee , I assign role 
     if ($employee==true) {
            $employee->assignRole($role);
        }
4.I create role and assign permissions
$role = Role::create(['guard_name' => 'employee', 'name' => $request->role_name])
$role->syncPermissions($request->permissions)
5. I use artisan to create permissions
php artisan permission:create-permission "manage_parameters" employee
6. On my blade file, I check for permission
@can('manage_parameters','employee')
  ---
@endcan

**Comment by sokeno** [comment]
Thanks @drbyte for your input, I actually got the fix for it, The fix was to get rid of any defined relationships on my Employee model and add protected $guard_name = 'employee'; , Thanks
